"use client";

import {useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1",CHARACTER_KEY="hanami.portal.character.v1";
type Homeroom={homeroom_id:string;code:string;grade_level:number;school_year:string;room_label:string|null;description:string;adviser_name:string|null;adviser_handle:string|null};
type Roster={character_id:string;display_name:string;handle:string;is_representative:boolean;representative_title:string|null};
type Feed={item_type:string;item_id:string;title:string;body:string;starts_at:string|null;published_at:string;location:string|null};
function auth(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string};return {token:s.accessToken??"",characterId:localStorage.getItem(CHARACTER_KEY)??""};}catch{return {token:"",characterId:""};}}
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function rpc<T>(token:string,name:string,characterId:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:characterId})});if(!r.ok)throw new Error();return await r.json() as T;}
export default function HomeroomPage(){const credentials=useMemo(()=>typeof window==="undefined"?{token:"",characterId:""}:auth(),[]);const [homeroom,setHomeroom]=useState<Homeroom|null>(null),[roster,setRoster]=useState<Roster[]>([]),[feed,setFeed]=useState<Feed[]>([]),[status,setStatus]=useState("Sign in and activate a Student character to open Homeroom.");
 useEffect(()=>{if(!credentials.token||!credentials.characterId)return;Promise.all([rpc<Homeroom[]>(credentials.token,"current_homeroom",credentials.characterId),rpc<Roster[]>(credentials.token,"current_homeroom_roster",credentials.characterId),rpc<Feed[]>(credentials.token,"current_homeroom_feed",credentials.characterId)]).then(([h,r,f])=>{setHomeroom(h[0]??null);setRoster(r);setFeed(f);setStatus(h[0]?`Homeroom ${h[0].code} loaded.`:"No homeroom is assigned to this Student yet.");}).catch(()=>setStatus("Homeroom could not be loaded."));},[credentials]);
 const fmt=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v)):"—";
 return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • HOMEROOM NETWORK • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark"><span>花</span></div><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Homeroom</p></div></a></div><div className="nav-row"><nav><a href="../">School Home</a><a className="active" href="./">Homeroom</a><a href="../organizations/">Organizations</a><a href="../rooms/">Rooms</a></nav><a className="portal-button" href="../portal/student/">Student Portal</a></div></header><section className="info-section" style={{margin:"24px"}}><div className="section-heading"><h2>{homeroom?`HOMEROOM ${homeroom.code}`:"HOMEROOM"}</h2><span>{homeroom?.school_year??"2006-2007"}</span></div><p className="content-note">{status}</p>{homeroom&&<><article style={{border:"1px solid #b8c3cf",padding:16,background:"#fffdf8",marginBottom:14}}><p className="eyebrow">GRADE {homeroom.grade_level}{homeroom.room_label?` • ${homeroom.room_label}`:""}</p><h3 style={{fontFamily:"Georgia,serif",color:"#17375f"}}>Class {homeroom.code}</h3><p>{homeroom.description||"Hanami High homeroom community."}</p><p><strong>Homeroom Adviser:</strong> {homeroom.adviser_name??"TBA"}{homeroom.adviser_handle?` (@${homeroom.adviser_handle})`:""}</p></article><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><article style={{border:"1px solid #b8c3cf",padding:14,background:"#fffdf8"}}><h3>Roster & Representatives</h3>{roster.map(member=><p key={member.character_id}><strong>{member.display_name}</strong> (@{member.handle}){member.is_representative?` • ${member.representative_title}`:""}</p>)}</article><article style={{border:"1px solid #b8c3cf",padding:14,background:"#fffdf8"}}><h3>Notices & Events</h3>{feed.length?feed.map(item=><div key={item.item_id} style={{borderTop:"1px dotted #aab8c8",padding:"8px 0"}}><p className="eyebrow">{item.item_type.toUpperCase()} • {fmt(item.starts_at??item.published_at)}</p><strong>{item.title}</strong><p>{item.body}</p>{item.location&&<small>{item.location}</small>}</div>):<p>No homeroom notices or events are posted.</p>}</article></div></>}</section><footer><p>HANAMI HIGH SCHOOL • HOMEROOM NETWORK • 2006</p><nav><a href="../portal/student/">Student Portal</a><a href="../organizations/">Organizations</a><a href="../">School Home</a></nav></footer></main>;}
