"use client";

import {useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1",CHARACTER_KEY="hanami.portal.character.v1";
type Activity={id:string;kind:string;name:string;description:string;meeting_location:string|null;meeting_schedule:string|null;is_active:boolean;is_test_data:boolean};
type Profile={activity_id:string;recruitment_status:string;application_required:boolean};type Officer={activity_id:string;character_id:string;title:string};type Announcement={id:string;activity_id:string;title:string;body:string;published_at:string};type Event={id:string;activity_id:string;title:string;starts_at:string;location:string|null};type Membership={activity_id:string;status:string};type Application={activity_id:string;status:string;staff_response:string};
function auth(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string};return {token:s.accessToken??"",characterId:localStorage.getItem(CHARACTER_KEY)??""};}catch{return {token:"",characterId:""};}}
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
export default function OrganizationsPage(){const [activities,setActivities]=useState<Activity[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [officers,setOfficers]=useState<Officer[]>([]);const [announcements,setAnnouncements]=useState<Announcement[]>([]);const [events,setEvents]=useState<Event[]>([]);const [memberships,setMemberships]=useState<Membership[]>([]);const [applications,setApplications]=useState<Application[]>([]);const [status,setStatus]=useState("Sign in through the Portal Gateway to open Organizations.");const [statement,setStatement]=useState<Record<string,string>>({});
 const credentials=useMemo(()=>typeof window==="undefined"?{token:"",characterId:""}:auth(),[]);
 useEffect(()=>{if(!credentials.token)return;Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/campus_activities?select=id,kind,name,description,meeting_location,meeting_schedule,is_active,is_test_data&is_active=eq.true&order=name`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Activity[]>),
  fetch(`${SUPABASE_URL}/rest/v1/organization_profiles?select=activity_id,recruitment_status,application_required`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Profile[]>),
  fetch(`${SUPABASE_URL}/rest/v1/organization_officers?select=activity_id,character_id,title`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Officer[]>),
  fetch(`${SUPABASE_URL}/rest/v1/organization_announcements?select=id,activity_id,title,body,published_at&order=published_at.desc`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Announcement[]>),
  fetch(`${SUPABASE_URL}/rest/v1/campus_activity_events?select=id,activity_id,title,starts_at,location&order=starts_at.asc`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Event[]>),
  credentials.characterId?fetch(`${SUPABASE_URL}/rest/v1/campus_activity_memberships?select=activity_id,status&character_id=eq.${encodeURIComponent(credentials.characterId)}`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Membership[]>):Promise.resolve([]),
  credentials.characterId?fetch(`${SUPABASE_URL}/rest/v1/organization_applications?select=activity_id,status,staff_response&student_character_id=eq.${encodeURIComponent(credentials.characterId)}`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Application[]>):Promise.resolve([])
 ]).then(([a,p,o,n,e,m,ap])=>{setActivities(a);setProfiles(p);setOfficers(o);setAnnouncements(n);setEvents(e);setMemberships(m);setApplications(ap);setStatus(`${a.length} active organization${a.length===1?"":"s"}.`);}).catch(()=>setStatus("Organizations could not be loaded."));},[credentials]);
 async function apply(activityId:string){if(!credentials.token||!credentials.characterId)return;const text=(statement[activityId]??"").trim();if(text.length<5){setStatus("Application statement must be at least 5 characters.");return;}const r=await fetch(`${SUPABASE_URL}/rest/v1/organization_applications`,{method:"POST",headers:headers(credentials.token,{"Content-Type":"application/json"}),body:JSON.stringify({activity_id:activityId,student_character_id:credentials.characterId,statement:text})});setStatus(r.ok?"Organization application submitted.":"Application could not be submitted or already exists.");if(r.ok)setApplications(x=>[...x,{activity_id:activityId,status:"submitted",staff_response:""}]);}
 const fmt=(v:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
 return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • ORGANIZATIONS PORTAL • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark"><span>花</span></div><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Organizations Portal</p></div></a></div><div className="nav-row"><nav><a href="../">School Home</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Organizations</a><a href="../elections/">Elections</a></nav><a className="portal-button" href="../portal/">Portal Gateway</a></div></header><section className="info-section" style={{margin:"24px"}}><div className="section-heading"><h2>ORGANIZATIONS PORTAL</h2><span>CLUBS • GROUPS • TEAMS • 2006</span></div><p className="content-note">{status}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}>{activities.map(a=>{const profile=profiles.find(p=>p.activity_id===a.id);const member=memberships.find(m=>m.activity_id===a.id);const app=applications.find(x=>x.activity_id===a.id);return <article key={a.id} style={{border:"1px solid #b8c3cf",padding:14,background:"#fffdf8"}}><p className="eyebrow">{a.kind.toUpperCase()}{a.is_test_data?" • TEST":""}</p><h3 style={{fontFamily:"Georgia,serif",color:"#17375f"}}>{a.name}</h3><p>{a.description}</p><p><strong>Meetings:</strong> {a.meeting_schedule??"TBA"}{a.meeting_location?` • ${a.meeting_location}`:""}</p><p><strong>Recruitment:</strong> {(profile?.recruitment_status??"open").replaceAll("_"," ")}</p>{member&&<p><strong>Your membership:</strong> {member.status}</p>}{officers.filter(o=>o.activity_id===a.id).length>0&&<p><strong>Officers:</strong> {officers.filter(o=>o.activity_id===a.id).map(o=>o.title).join(" • ")}</p>}{announcements.filter(n=>n.activity_id===a.id).slice(0,2).map(n=><div key={n.id}><strong>{n.title}</strong><p>{n.body}</p></div>)}{events.filter(e=>e.activity_id===a.id).slice(0,2).map(e=><p key={e.id}><strong>{e.title}</strong> • {fmt(e.starts_at)}{e.location?` • ${e.location}`:""}</p>)}{profile?.application_required&&!member&&!app&&profile.recruitment_status==="open"&&<><textarea style={{width:"100%",minHeight:70,boxSizing:"border-box"}} value={statement[a.id]??""} onChange={e=>setStatement(s=>({...s,[a.id]:e.target.value}))} placeholder="Why would you like to join?"/><button type="button" onClick={()=>apply(a.id)}>Apply to organization</button></>}{app&&<p><strong>Application:</strong> {app.status}{app.staff_response?` • ${app.staff_response}`:""}</p>}</article>;})}</div></section><footer><p>HANAMI HIGH SCHOOL • ORGANIZATIONS PORTAL • 2006</p><nav><a href="../portal/">Portal</a><a href="../elections/">Elections</a><a href="../">School Home</a></nav></footer></main>;}
