"use client";

import {useEffect,useMemo,useState} from "react";
import {hanamiRoleplayDate} from "../components/roleplay-date";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1",CHARACTER_KEY="hanami.portal.character.v1";
type Activity={id:string;kind:string;name:string;description:string;meeting_location:string|null;meeting_schedule:string|null;is_active:boolean};
type Membership={activity_id:string;status:string};
function auth(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string};return {token:s.accessToken??"",characterId:localStorage.getItem(CHARACTER_KEY)??""};}catch{return {token:"",characterId:""};}}
function headers(token?:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,...(token?{Authorization:`Bearer ${token}`}:{})};}

export default function OrganizationsPage(){
 const [activities,setActivities]=useState<Activity[]>([]);const [memberships,setMemberships]=useState<Membership[]>([]);const [status,setStatus]=useState("Loading Hanami clubs and organizations…");const credentials=useMemo(()=>typeof window==="undefined"?{token:"",characterId:""}:auth(),[]);const currentDate=hanamiRoleplayDate();
 useEffect(()=>{let cancelled=false;async function load(){try{const activityResponse=await fetch(`${SUPABASE_URL}/rest/v1/campus_activities?select=id,kind,name,description,meeting_location,meeting_schedule,is_active&is_active=eq.true&is_test_data=eq.false&order=name.asc`,{headers:headers(credentials.token)});if(!activityResponse.ok)throw new Error();const rows=await activityResponse.json() as Activity[];let joined:Membership[]=[];if(credentials.token&&credentials.characterId){const membershipResponse=await fetch(`${SUPABASE_URL}/rest/v1/campus_activity_memberships?select=activity_id,status&character_id=eq.${encodeURIComponent(credentials.characterId)}`,{headers:headers(credentials.token)});if(membershipResponse.ok)joined=await membershipResponse.json() as Membership[];}if(cancelled)return;setActivities(rows);setMemberships(joined);setStatus(`${rows.length} active club${rows.length===1?"":"s"} and organization${rows.length===1?"":"s"}.`);}catch{if(!cancelled)setStatus("The club directory could not be loaded. You can still return to Campus Life and try again.");}}void load();return()=>{cancelled=true;};},[credentials]);
 return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • CLUBS &amp; ORGANIZATIONS • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><img src="../hanami-high-portal-icon.png" alt="Hanami High" style={{width:82,height:82,objectFit:"contain"}}/><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Clubs &amp; Organizations</p></div></a><div className="school-clock"><strong data-hanami-roleplay-clock>{currentDate.toUpperCase()}</strong><span>HANAMI CITY • JAPAN STANDARD TIME</span></div></div><div className="nav-row"><nav><a href="../">School Home</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Clubs</a><a href="../calendar/">Calendar</a></nav><a className="portal-button" href="../portal/">Portal Gateway</a></div></header><section className="info-section" style={{margin:"18px 24px"}}><div className="section-heading"><h2>CLUB DIRECTORY</h2><span>2006–07 • HANAMI CAMPUS</span></div><p className="content-note" aria-live="polite">{status}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:0,borderTop:"1px solid #c7d0da",borderLeft:"1px solid #c7d0da"}}>{activities.map(activity=>{const membership=memberships.find(item=>item.activity_id===activity.id);return <article key={activity.id} style={{borderRight:"1px solid #c7d0da",borderBottom:"1px solid #c7d0da",padding:16,background:"#fffdf8",minWidth:0}}><p className="eyebrow">{activity.kind.toUpperCase()}</p><h3 style={{margin:"5px 0 8px",fontFamily:"Georgia,serif",color:"#17375f"}}>{activity.name}</h3><p>{activity.description}</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:12}}><div style={{background:"#edf3f8",padding:8}}><small>MEETS</small><br/><strong>{activity.meeting_schedule??"Not posted"}</strong></div><div style={{background:"#edf3f8",padding:8}}><small>LOCATION</small><br/><strong>{activity.meeting_location??"Not posted"}</strong></div></div>{membership&&<p style={{marginTop:10}}><strong>Your membership:</strong> {membership.status}</p>}</article>;})}</div><div style={{padding:"12px 0"}}><a href="../portal/student/">Open Student Portal to join clubs →</a></div></section><footer><p>HANAMI HIGH SCHOOL • CLUBS &amp; ORGANIZATIONS • 2006</p><nav><a href="../campus-life/">Campus Life</a><a href="../portal/">Portal</a><a href="../">School Home</a></nav></footer></main>;
}
