"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "../StandaloneCommunityPage.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
const CHARACTER_SESSION_KEY="hanami.portal.character.v1";
type Entry={id:string;cadence:"daily"|"weekly";roleplay_date:string;title:string;prompt:string;continuity_summary:string;category:string;published_at:string|null};
type Session={access_token?:string};
type Character={id:string;display_name:string;role:string};
function schoolDate(value:string){const d=new Date(`${value}T12:00:00+09:00`);return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(d);}

export default function RoleplayHubPage(){
 const [session,setSession]=useState<Session|null>(null),[character,setCharacter]=useState<Character|null>(null),[entries,setEntries]=useState<Entry[]>([]),[message,setMessage]=useState("Opening roleplay calendar…");
 useEffect(()=>{try{setSession(JSON.parse(localStorage.getItem(SESSION_KEY)||"null"));setCharacter(JSON.parse(localStorage.getItem(CHARACTER_SESSION_KEY)||"null"));}catch{setMessage("Your portal session could not be read.");}},[]);
 useEffect(()=>{const token=session?.access_token;if(!token)return;(async()=>{try{const r=await fetch(`${SUPABASE_URL}/rest/v1/roleplay_calendar_entries?select=id,cadence,roleplay_date,title,prompt,continuity_summary,category,published_at&status=eq.published&order=roleplay_date.desc,published_at.desc&limit=60`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(await r.text());setEntries(await r.json() as Entry[]);setMessage("Daily and weekly roleplay calendar ready.");}catch(e){setMessage(e instanceof Error?e.message:"Roleplay calendar could not be loaded.");}})();},[session?.access_token]);
 const daily=useMemo(()=>entries.filter(x=>x.cadence==="daily"),[entries]);const weekly=useMemo(()=>entries.filter(x=>x.cadence==="weekly"),[entries]);
 return <main className={styles.page}><div className={styles.shell}><header className={styles.top}><div><p>HANAMI HIGH • ROLEPLAY</p><h1>Daily & weekly roleplay hub</h1><p>Daily prompts are for ordinary school-life scenes. Weekly prompts carry the larger continuity and lore-forward beats.</p></div><a href="../student/">Back to Student Portal</a></header><div className={styles.notice}>{character?`${character.display_name} • ${message}`:message}</div><section className={styles.grid}><div className={styles.stack}><div className={styles.sectionTitle}><h2>Daily roleplays</h2><span>School-life scenes</span></div>{daily.length?daily.map(entry=><article className={styles.card} key={entry.id}><div className={styles.meta}><span>{schoolDate(entry.roleplay_date)}</span><span>{entry.category.replaceAll("_"," ")}</span></div><h3>{entry.title}</h3><p className={styles.prompt}>{entry.prompt||"Open school-life roleplay."}</p>{entry.continuity_summary&&<><strong>Continuity note</strong><p>{entry.continuity_summary}</p></>}</article>):<div className={styles.empty}>No daily roleplay has been published yet.</div>}</div><div className={styles.stack}><div className={styles.sectionTitle}><h2>Weekly roleplays</h2><span>Major continuity</span></div>{weekly.length?weekly.map(entry=><article className={`${styles.card} ${styles.campaign}`} key={entry.id}><div className={styles.meta}><span>{schoolDate(entry.roleplay_date)}</span><span>Weekly story</span></div><h3>{entry.title}</h3><p className={styles.prompt}>{entry.prompt||"Weekly school story event."}</p>{entry.continuity_summary&&<><strong>What this changes</strong><p>{entry.continuity_summary}</p></>}</article>):<div className={styles.empty}>No weekly roleplay has been published yet.</div>}</div></section><section className={styles.card}><h2>Roleplay rhythm</h2><p><strong>Daily:</strong> classroom moments, lunch, club prep, rumors, friendships, small conflicts, errands, announcements, and slice-of-life scenes that make the school feel active.</p><p><strong>Weekly:</strong> elections, festivals, investigations, rivalries, school-wide incidents, major character turning points, and continuity events worth preserving in the archive.</p></section></div></main>;
}
