import {hanamiRoleplayDate} from "../components/roleplay-date";

const websiteRules=[
 ["Respectful Behaviour","Be respectful to other members and do not intentionally start or prolong drama. Body shaming, gaslighting, victim blaming, incitement to violence, sexual objectification, dehumanising terms, slurs, and unwanted sexualisation are prohibited."],
 ["No Harassment","Harassment based on ethnicity, sexual orientation, gender, occupation, age, religious belief, or location of residency is prohibited. This includes private messages and private chats."],
 ["No NSFW or Romantic Content","Do not post sexual, graphic, self-harm, or otherwise NSFW content in profiles, messages, forums, uploads, forms, or any other website area. Sexual speech, suggestive comments, romantic roleplay, crushes, or anything beyond platonic admiration are not allowed."],
 ["Respect Boundaries & Controversial Topics","If another member says a topic is controversial or uncomfortable for them, stop discussing it with them. Do not pressure people to continue conversations they have asked to leave."],
 ["No Spamming","Do not flood messages, forums, guestbooks, forms, or profiles with repeated posts, walls of text, single-word spam, counting, or other disruptive content outside spaces specifically intended for it."],
 ["No Alt-Account Abuse or Impersonation","Do not use alternate accounts to evade punishment, impersonate another person, misrepresent your identity, or circumvent a ban. A ban from the Official Rintama server may also affect Hanami access."],
 ["No Unauthorised Links or Advertising","Advertising requires Faculty or Administration permission. Suspicious or unauthorised links may be removed automatically or by staff."],
 ["No Exploits, Loopholes, or System Abuse","Do not exploit bugs, bypass permissions, manipulate school systems, abuse moderation tools, or use loopholes to violate the intent of the rules. Report bugs instead of exploiting them."],
 ["Use Common Sense","Ragebaiting, passive-aggressive behaviour, targeted disruption, and conduct clearly intended to provoke or upset others are prohibited even when the exact behaviour is not listed word-for-word."],
 ["Age Requirement","Members must be at least 16 years old to participate in Hanami High roleplay and community interaction."],
] as const;

const roleplayRules=[
 ["No Romance","No crushes, insinuations of crushes, romantic relationships, romantic actions, or sexual behaviour. Platonic admiration, role models, and wanting to become friends are allowed. No romance."],
 ["Respect the Area","You may observe roleplay in progress when you are not disruptive. If players ask you to leave a low-traffic roleplay area, respect the request. High-traffic spaces such as hallways, lockers, entrances, and the front of the school cannot be claimed as private areas."],
 ["Respect Faculty and Each Other","Students are expected to follow reasonable Faculty instructions. Faculty may assign detention at their discretion, but they may not personally suspend or expel students. Faculty are expected to remain fair and unbiased when resolving student issues."],
 ["No Exploiting","Game exploits, cheats, unauthorised scripts, or abuse of game systems may result in an automatic ban and report."],
 ["Uniforms and Clothes","Uniforms must be worn on school grounds during school hours. Variants are permitted and encouraged if they remain recognisably school uniforms. Delinquent and Gyaru styling may appear in moderation during school. Casual clothing and cosplay are permitted after school hours. Character appearance should follow established setting rules for hair colour and background."],
 ["Foreigners","Foreigner Student and Teacher slots are limited. Certain Teacher roles may be foreigners, while Student foreigner characters require screening. Townies may be foreigners with fewer school-uniform restrictions."],
 ["Graduation","Students can graduate after multiple in-world years. Graduates may become townies; some may later become teachers, while teachers may retire. If you fully graduate or exit a student role, create a new unrelated student for a fresh school-character slot. Students may also drop out and become townies without graduating."],
 ["Time and Sessions","Roleplay timing is based on majority availability. One session represents roughly one school year, but one individual roleplay does not equal a full session. Sessions function like anime chapters or seasons, cover all seasons and major events, and follow an event schedule before concluding. Students nearing graduation are notified one session early so they can choose whether to graduate, become a townie, or continue with a new character."],
] as const;

export default function RulesPage(){
 const currentDate=hanamiRoleplayDate();
 return <main className="site-page"><a className="skip-link" href="#rules-main">Skip to rules</a>
  <header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • RULES & CONDUCT • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark"><span>花</span></div><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Rules & Conduct</p></div></a><div className="school-clock"><strong>{currentDate.toUpperCase()}</strong><span>HANAMI CITY • COMMUNITY STANDARDS</span></div></div><div className="nav-row"><nav><a href="../">Home</a><a href="../about/">About</a><a href="../academics/">Academics</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Rules</a><a href="../apply/">Apply</a></nav><a className="portal-button" href="../portal/">Login / Portal</a></div></header>
  <section id="rules-main" className="hero-panel" style={{margin:"18px 24px"}}><p className="eyebrow">HANAMI HIGH • COMMUNITY STANDARDS</p><h1 style={{margin:"6px 0 10px",font:"400 36px Georgia,serif"}}>Website Rules & Roleplay Rules</h1><p>These rules work together with the Hanami Discord server rules. Students and Faculty must follow the applicable platform rules, Hanami community rules, website rules, and roleplay rules at all times.</p><div className="portal-status"><strong>RULE PRIORITY</strong><span>If Discord, Roblox, or Official Rintama rules are stricter than a Hanami rule, the stricter platform/community rule applies.</span></div></section>
  <section style={{margin:"0 24px 18px",padding:16,border:"1px solid #aab7c6",background:"#fff"}}><p className="eyebrow">REQUIRED PLATFORM RULES</p><h2 style={{font:"400 24px Georgia,serif"}}>Review before participating</h2><p>Hanami High operates alongside Discord, Roblox, and the Official Rintama community. Prospective students and staff are expected to review the relevant platform policies.</p><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><a className="secondary-action" href="https://discord.com/terms" target="_blank" rel="noreferrer">Discord Terms of Service</a><a className="secondary-action" href="https://discord.com/guidelines" target="_blank" rel="noreferrer">Discord Community Guidelines</a><a className="secondary-action" href="https://en.help.roblox.com/hc/en-us/articles/115004647846-Roblox-Terms-of-Use" target="_blank" rel="noreferrer">Roblox Terms of Use</a></div></section>
  <section style={{margin:"0 24px 18px",border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:"14px 16px",background:"#eef3f8",borderBottom:"1px solid #c5ced8"}}><p className="eyebrow">WEBSITE & COMMUNITY</p><h2 style={{margin:"3px 0",font:"400 25px Georgia,serif"}}>Website Rules</h2><p style={{margin:"5px 0 0"}}>These apply to profiles, messages, forums, guestbooks, applications, school forms, uploads, and all other interactive website features.</p></div><div style={{display:"grid",gap:0}}>{websiteRules.map(([title,body],index)=><article key={title} style={{padding:"14px 16px",borderBottom:index===websiteRules.length-1?"0":"1px dotted #c5ced8"}}><p className="eyebrow">RULE {index+1}</p><h3 style={{margin:"3px 0 6px",font:"700 18px Georgia,serif"}}>{title}</h3><p style={{margin:0,lineHeight:1.6}}>{body}</p></article>)}</div></section>
  <section style={{margin:"0 24px 24px",border:"1px solid #d8b7c5",background:"#fffafc"}}><div style={{padding:"14px 16px",background:"#f8e9f1",borderBottom:"1px solid #d8b7c5"}}><p className="eyebrow">IN-CHARACTER / GAMEPLAY</p><h2 style={{margin:"3px 0",font:"400 25px Georgia,serif"}}>Roleplay Rules</h2><p style={{margin:"5px 0 0"}}>These rules apply in addition to all Server and Website Rules. In this section, Student and Faculty refer to the in-roleplay school roles.</p></div><div style={{display:"grid",gap:0}}>{roleplayRules.map(([title,body],index)=><article key={title} style={{padding:"14px 16px",borderBottom:index===roleplayRules.length-1?"0":"1px dotted #d8b7c5"}}><p className="eyebrow">ROLEPLAY RULE {index+1}</p><h3 style={{margin:"3px 0 6px",font:"700 18px Georgia,serif"}}>{title}</h3><p style={{margin:0,lineHeight:1.6}}>{body}</p></article>)}</div></section>
  <section className="portal-rules"><div><p className="eyebrow">ACKNOWLEDGEMENT</p><strong>Read before joining.</strong><p>These rules are also published in the School Handbook for enrolled members.</p></div><div><p className="eyebrow">MODERATION</p><strong>Intent matters.</strong><p>Attempts to exploit loopholes or evade the spirit of the rules may still result in moderation.</p></div><div><p className="eyebrow">QUESTIONS</p><strong>Ask before acting.</strong><p>If you are uncertain whether something is appropriate, contact staff before posting or roleplaying it.</p></div></section>
  <footer><p>HANAMI HIGH SCHOOL • RULES & CONDUCT • EST. 2006</p><nav><a href="../apply/">Apply</a><a href="../portal/help/">Help</a><a href="#rules-main">Back to top ↑</a></nav></footer>
 </main>;
}
