"use client";

import {useEffect,useMemo,useState,type CSSProperties} from "react";
import styles from "./StudentClassPage.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
const CHARACTER_KEY="hanami.portal.character.v1";
type Session={accessToken:string;refreshToken:string;expiresAt:number};
type FacultyProfile={welcome_message?:string;teaching_philosophy?:string;favorite_subjects?:string[];office_location?:string|null;profile_banner_url?:string|null};
type Person={id?:string;display_name:string;handle:string;profile?:FacultyProfile};
type Meeting={id:string;weekday:number;starts_at:string;ends_at:string;label:string|null};
type Submission={id:string;status:string;submitted_at:string|null;grade:number|null;feedback:string;body:string};
type Assignment={id:string;title:string;description:string;due_at:string|null;points:number;status:string;assessment_type:string;assignment_group:string|null;late_policy:string|null;is_test_data?:boolean;submission:Submission|null};
type Attendance={id:string;attendance_date:string;status:string;note:string|null};
type ClassIdentity={banner_url?:string|null;welcome_message?:string;class_rules?:string;weekly_agenda?:string;updated_at?:string};
type Detail={section:{id:string;section_code:string;term:string;room:string|null;is_test_data?:boolean;identity?:ClassIdentity;course:{code:string;title:string;department:string;description:string;credits:number;is_test_data?:boolean}};instructors:Person[];students:Person[];meetings:Meeting[];assignments:Assignment[];attendance:Attendance[]};
type Tab="overview"|"assignments"|"materials"|"grades"|"attendance"|"classmates";
const DAYS=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
function readSession():Session|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<Session>;return typeof value.accessToken==="string"&&typeof value.refreshToken==="string"&&typeof value.expiresAt==="number"?value as Session:null;}catch{return null;}}
async function refreshSession(session:Session){const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return null;const data=await response.json() as {access_token?:string;refresh_token?:string;expires_in?:number};if(!data.access_token||!data.refresh_token)return null;const next={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+(data.expires_in??3600)*1000};localStorage.setItem(SESSION_KEY,JSON.stringify(next));return next;}
function due(value:string|null){return value?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value)):"No due date";}
function time(value:string){const [h,m]=value.split(":");const n=Number(h);return `${n%12||12}:${m} ${n>=12?"PM":"AM"}`;}
function statusLabel(value:string){return value.replaceAll("_"," ");}
function lines(value?:string){return (value??"").split(/\n+/).map(x=>x.trim()).filter(Boolean);}

export default function StudentClassPageClient(){
 const [detail,setDetail]=useState<Detail|null>(null);const [message,setMessage]=useState("Opening class workspace…");const [error,setError]=useState(false);const [tab,setTab]=useState<Tab>("overview");
 useEffect(()=>{let cancelled=false;async function load(){try{let session=readSession();if(!session)throw new Error("You are signed out. Return to the Student Portal and sign in again.");if(session.expiresAt-Date.now()<120000){session=await refreshSession(session);if(!session)throw new Error("Your Hanami session expired. Sign in again.");}const characterId=localStorage.getItem(CHARACTER_KEY);if(!characterId)throw new Error("Choose an active Student character first.");const sectionId=new URLSearchParams(window.location.search).get("section")??"";if(!/^[0-9a-f-]{36}$/i.test(sectionId))throw new Error("This class link is missing its section information.");const characterResponse=await fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,role,is_active&id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(session.accessToken)});if(!characterResponse.ok)throw new Error("Your active character could not be checked.");const character=(await characterResponse.json() as {id:string;role:string;is_active:boolean}[])[0];if(!character?.is_active||character.role!=="student")throw new Error("This class page requires your active Student character.");const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/student_class_detail`,{method:"POST",cache:"no-store",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({viewer_character_id:characterId,target_section_id:sectionId})});if(!response.ok)throw new Error("This class could not be opened. Make sure the active Student is enrolled in it.");const data=await response.json() as Detail;if(!cancelled){setDetail({...data,instructors:data.instructors??[],students:data.students??[],assignments:data.assignments??[],attendance:data.attendance??[],meetings:data.meetings??[]});setMessage("Class workspace ready.");setError(false);}}catch(err){if(!cancelled){setDetail(null);setMessage(err instanceof Error?err.message:"Class workspace could not be opened.");setError(true);}}}void load();return()=>{cancelled=true;};},[]);
 const attendanceCounts=useMemo(()=>{const out:Record<string,number>={};for(const row of detail?.attendance??[])out[row.status]=(out[row.status]??0)+1;return out;},[detail]);
 const upcoming=useMemo(()=>[...(detail?.assignments??[])].filter(item=>item.due_at).sort((a,b)=>new Date(a.due_at!).getTime()-new Date(b.due_at!).getTime()).slice(0,5),[detail]);
 if(!detail)return <section className={styles.state}><p className="eyebrow">MY CLASS</p><h2>{error?"Class unavailable":"Opening class…"}</h2><p>{message}</p><a href="../">Return to Student Portal</a></section>;
 const identity=detail.section.identity??{};const testData=Boolean(detail.section.is_test_data||detail.section.course.is_test_data);const tabs:[Tab,string][]=[["overview","Overview"],["assignments","Assignments"],["materials","Materials"],["grades","Grades"],["attendance","Attendance"],["classmates","Classmates"]];const headerStyle=identity.banner_url?({backgroundImage:`linear-gradient(90deg,rgba(23,40,60,.94),rgba(23,40,60,.68)),url("${identity.banner_url.replaceAll('"','\\"')}")`,backgroundSize:"cover",backgroundPosition:"center"} as CSSProperties):undefined;
 return <div className={styles.workspace}>
  <header className={styles.courseHeader} style={headerStyle}><div className={styles.courseTop}><a href="../" className={styles.back}>← My Classes</a><div><p>{detail.section.course.code} • {detail.section.section_code}</p><h1>{detail.section.course.title}</h1><span>{detail.section.term} • {detail.section.room?`Room ${detail.section.room}`:"Room TBA"}</span></div>{testData&&<b>TEST DATA</b>}</div></header>
  <div className={styles.courseFrame}><aside className={styles.courseNav}><div className={styles.courseIdentity}><strong>{detail.section.course.code}</strong><span>{detail.section.course.department}</span></div><nav aria-label="Course navigation">{tabs.map(([key,label])=><button key={key} type="button" className={tab===key?styles.tabActive:""} onClick={()=>setTab(key)}>{label}</button>)}</nav></aside><div className={styles.courseContent}>
   {tab==="overview"&&<main className={styles.streamLayout}><section className={styles.streamFeed}><div className={styles.pageTitle}><div><p className="eyebrow">CLASS OVERVIEW</p><h2>{detail.section.course.title}</h2></div></div>{(identity.welcome_message||identity.weekly_agenda||identity.class_rules)&&<article className={styles.identityPost}><p className="eyebrow">CLASSROOM BOARD</p><h3>{identity.welcome_message||"Welcome to class."}</h3>{identity.weekly_agenda&&<div className={styles.agenda}><strong>This week</strong>{lines(identity.weekly_agenda).map((line,i)=><span key={i}>{line}</span>)}</div>}{identity.class_rules&&<button type="button" onClick={()=>setTab("materials")}>View class reference →</button>}</article>}{detail.instructors.map(instructor=><article className={styles.teacherCard} key={instructor.id??instructor.handle}>{instructor.profile?.profile_banner_url&&<div className={styles.teacherBanner} style={{backgroundImage:`url("${instructor.profile.profile_banner_url.replaceAll('"','\\"')}")`}}/>}<div><span className={styles.personAvatar}>{instructor.display_name.slice(0,1).toUpperCase()}</span><div><small>YOUR INSTRUCTOR</small><h3>{instructor.display_name}</h3><p>{instructor.profile?.welcome_message||`@${instructor.handle}`}</p>{instructor.profile?.favorite_subjects?.length?<div className={styles.subjectTags}>{instructor.profile.favorite_subjects.map(subject=><span key={subject}>{subject}</span>)}</div>:null}</div></div></article>)}<article className={styles.streamPost}><span className={styles.avatar}>H</span><div><div className={styles.postMeta}><strong>Course information</strong><span>{detail.instructors.length?detail.instructors.map(i=>i.display_name).join(", "):"Instructor pending"}</span></div><p>{detail.section.course.description||"No course description has been posted."}</p></div></article>{detail.assignments.slice(0,4).map(item=><article className={styles.streamPost} key={item.id}><span className={styles.assignmentIcon}>✓</span><div><div className={styles.postMeta}><strong>{item.title}</strong><span>{item.assessment_type} • {due(item.due_at)}</span></div><p>{item.description||"No instructions posted."}</p><button type="button" onClick={()=>setTab("assignments")}>Open assignment</button></div></article>)}</section><aside className={styles.upcomingCard}><div className={styles.cardHeading}><h2>To Do</h2><button type="button" onClick={()=>setTab("assignments")}>View all</button></div>{upcoming.length?upcoming.map(item=><button type="button" key={item.id} className={styles.upcomingItem} onClick={()=>setTab("assignments")}><strong>{item.title}</strong><span>{due(item.due_at)}</span></button>):<p className={styles.muted}>Nothing due soon.</p>}</aside></main>}
   {tab==="assignments"&&<main className={styles.contentPage}><div className={styles.pageTitle}><div><p className="eyebrow">ASSIGNMENTS</p><h2>Assignments & feedback</h2></div><span>{detail.assignments.length} posted</span></div><section className={styles.assignments}>{detail.assignments.length?detail.assignments.map(item=><article key={item.id}><div className={styles.assignmentTop}><span className={styles.assignmentIcon}>✓</span><div><strong>{item.title}</strong><span>{item.assessment_type.toUpperCase()}{item.assignment_group?` • ${item.assignment_group}`:""}</span></div>{item.is_test_data&&<b>TEST</b>}</div><p>{item.description||"No instructions posted."}</p><dl><div><dt>Due</dt><dd>{due(item.due_at)}</dd></div><div><dt>Points</dt><dd>{item.points}</dd></div><div><dt>Status</dt><dd>{statusLabel(item.submission?.status??"not started")}</dd></div><div><dt>Grade</dt><dd>{item.submission?.grade==null?"Not graded":`${item.submission.grade} / ${item.points}`}</dd></div></dl>{item.late_policy&&<div className={styles.note}><strong>Late policy</strong><span>{item.late_policy}</span></div>}{item.submission?.feedback&&<div className={styles.feedback}><strong>Teacher comment</strong><p>{item.submission.feedback}</p></div>}{item.submission?.submitted_at&&<small>Submitted {due(item.submission.submitted_at)}</small>}</article>):<div className={styles.empty}>No published assignments in this class yet.</div>}</section></main>}
   {tab==="materials"&&<main className={styles.infoGrid}><section className={styles.card}><p className="eyebrow">CLASS MATERIALS</p><h2>Course reference</h2><p>{detail.section.course.description||"No course reference has been posted yet."}</p>{identity.weekly_agenda&&<div className={styles.classInfoBlock}><h3>Weekly agenda</h3>{lines(identity.weekly_agenda).map((line,i)=><p key={i}>{line}</p>)}</div>}{identity.class_rules&&<div className={styles.classInfoBlock}><h3>Class rules</h3>{lines(identity.class_rules).map((line,i)=><p key={i}>{line}</p>)}</div>}<h3>Meeting times</h3>{detail.meetings.length?detail.meetings.map(m=><div className={styles.meeting} key={m.id}><strong>{DAYS[m.weekday]??"Day"}</strong><span>{time(m.starts_at)}–{time(m.ends_at)}{m.label?` • ${m.label}`:""}</span></div>):<p>No meeting time scheduled.</p>}</section><section className={styles.card}><p className="eyebrow">COURSE DETAILS</p><h2>{detail.section.course.code}</h2><dl><div><dt>Credits</dt><dd>{detail.section.course.credits}</dd></div><div><dt>Room</dt><dd>{detail.section.room??"TBA"}</dd></div><div><dt>Term</dt><dd>{detail.section.term}</dd></div><div><dt>Section</dt><dd>{detail.section.section_code}</dd></div></dl><p className={styles.materialHint}>Teacher-uploaded files can be added here later without changing the class workspace layout.</p></section></main>}
   {tab==="grades"&&<main className={styles.contentPage}><div className={styles.pageTitle}><div><p className="eyebrow">GRADES</p><h2>Grades for {detail.section.course.code}</h2></div></div><section className={styles.gradeTable}><div className={styles.gradeHeader}><span>Assignment</span><span>Status</span><span>Score</span></div>{detail.assignments.length?detail.assignments.map(item=><div className={styles.gradeRow} key={item.id}><div><strong>{item.title}</strong><span>{due(item.due_at)}</span></div><span>{statusLabel(item.submission?.status??"not started")}</span><strong>{item.submission?.grade==null?"—":`${item.submission.grade} / ${item.points}`}</strong></div>):<p className={styles.empty}>No graded work has been posted yet.</p>}</section></main>}
   {tab==="attendance"&&<main className={styles.contentPage}><div className={styles.pageTitle}><div><p className="eyebrow">ATTENDANCE</p><h2>Attendance history</h2></div><span>{detail.attendance.length} records</span></div><section className={styles.card}><div className={styles.attendanceSummary}>{Object.entries(attendanceCounts).length?Object.entries(attendanceCounts).map(([key,value])=><span key={key}><strong>{value}</strong>{statusLabel(key)}</span>):<p>No attendance records yet.</p>}</div>{detail.attendance.length?detail.attendance.map(row=><div className={styles.attendanceRow} key={row.id}><strong>{row.attendance_date}</strong><span>{statusLabel(row.status)}{row.note?` • ${row.note}`:""}</span></div>):<p className={styles.empty}>No attendance records have been posted for this class.</p>}</section></main>}
   {tab==="classmates"&&<main className={styles.contentPage}><div className={styles.pageTitle}><div><p className="eyebrow">CLASSMATES</p><h2>Class roster</h2></div><span>{detail.students.length} student{detail.students.length===1?"":"s"}</span></div><section className={styles.peopleList}><h3>Instructor{detail.instructors.length===1?"":"s"}</h3>{detail.instructors.length?detail.instructors.map(i=><article key={i.id??i.handle}><span className={styles.personAvatar}>{i.display_name.slice(0,1).toUpperCase()}</span><div><strong>{i.display_name}</strong><span>@{i.handle}{i.profile?.office_location?` • ${i.profile.office_location}`:""}</span>{i.profile?.teaching_philosophy&&<p>{i.profile.teaching_philosophy}</p>}</div></article>):<p className={styles.empty}>No instructor has been assigned yet.</p>}<h3>Students</h3>{detail.students.length?detail.students.map(student=><article key={student.id??student.handle}><span className={styles.personAvatar}>{student.display_name.slice(0,1).toUpperCase()}</span><div><strong>{student.display_name}</strong><span>@{student.handle}</span></div></article>):<p className={styles.empty}>No students are currently registered in this class.</p>}</section></main>}
  </div></div>
 </div>;
}
