"use client";
import {useMemo,useState} from "react";
const activities=[
  {name:"Art Club",type:"Club",category:"Arts",schedule:"Thu • 3:45 PM",place:"Art Room",description:"Painting, illustration, murals, and student exhibitions."},
  {name:"Computer & Gaming Club",type:"Club",category:"Academic",schedule:"Fri • 4:00 PM",place:"Computer Lab",description:"Coding projects, game design, and supervised tournaments."},
  {name:"Literature Society",type:"Club",category:"Academic",schedule:"Wed • 3:30 PM",place:"Library",description:"Reading circles, writing workshops, and the school journal."},
  {name:"Basketball",type:"Athletics",category:"Sports",schedule:"Tue/Thu • 4:00 PM",place:"Gymnasium",description:"Team practices, conditioning, and interschool competition."},
  {name:"Track & Field",type:"Athletics",category:"Sports",schedule:"Mon/Wed • 4:00 PM",place:"Athletics Field",description:"Sprint, distance, relay, and field-event training."},
  {name:"Broadcast Committee",type:"Organization",category:"Media",schedule:"Daily • 3:30 PM",place:"Media Room",description:"Announcements, interviews, event coverage, and campus stories."},
] as const;
export default function CampusDirectory(){const[query,setQuery]=useState("");const[type,setType]=useState("All");const matches=useMemo(()=>activities.filter(item=>(type==="All"||item.type===type)&&`${item.name} ${item.category} ${item.description}`.toLowerCase().includes(query.toLowerCase())),[query,type]);return <section className="info-section" id="directory"><div className="section-heading"><h2>CLUBS, ATHLETICS & ORGANIZATIONS</h2><span>TEST DIRECTORY • {matches.length} SHOWN</span></div><div className="test-data-notice"><strong>DEVELOPMENT DATA</strong><p>These sample activities test discovery and filtering. Official rosters will come from approved portal records.</p></div><div className="campus-directory-controls"><label><span>Search activities</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search clubs, teams, or interests"/></label><label><span>Activity type</span><select value={type} onChange={event=>setType(event.target.value)}><option>All</option><option>Club</option><option>Athletics</option><option>Organization</option></select></label></div><div className="activity-results" aria-live="polite">{matches.length?matches.map(item=><article key={item.name}><p className="eyebrow">{item.type} • {item.category}</p><h3>{item.name}</h3><p>{item.description}</p><dl><div><dt>Meets</dt><dd>{item.schedule}</dd></div><div><dt>Location</dt><dd>{item.place}</dd></div></dl><button disabled>Interest opens in portal</button></article>):<p className="no-results">No activities match that search.</p>}</div></section>}
