"use client";

import {FormEvent,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
export const OWNER_WEB_EDIT_KEY="hanami.owner.web-edit.v1";

function rpcHeaders(){return {apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"};}
function normalizeOwnerHandle(value:string){
 const clean=value.trim().toLowerCase();
 if(clean.endsWith("@hanamihigh.edu"))return clean.slice(0,-"@hanamihigh.edu".length);
 return clean.replace(/^@/,"");
}

export default function OwnerWebsiteAccess(){
 const [active,setActive]=useState(false);const [open,setOpen]=useState(false);const [handle,setHandle]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{let cancelled=false;async function restore(){const token=localStorage.getItem(OWNER_WEB_EDIT_KEY);if(!token)return;try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_session_valid`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:token})});const valid=response.ok&&Boolean(await response.json());if(cancelled)return;if(valid)setActive(true);else localStorage.removeItem(OWNER_WEB_EDIT_KEY);}catch{if(!cancelled)setActive(false);}}void restore();return()=>{cancelled=true;};},[]);
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;const form=new FormData(event.currentTarget);const typedHandle=String(form.get("ownerHandle")??handle);const typedPassword=String(form.get("ownerPassword")??password);const clean=normalizeOwnerHandle(typedHandle);if(!/^[a-z0-9_]{3,32}$/.test(clean)){setMessage("Enter your Owner handle, with or without @hanamihigh.edu.");return;}if(typedPassword.length<12){setMessage("Owner passwords are at least 12 characters.");return;}setLoading(true);setMessage("Verifying Owner access…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_login`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_handle:clean,requested_password:typedPassword})});if(!response.ok)throw new Error("Owner sign-in could not be completed.");const token=await response.json() as string|null;if(!token)throw new Error("Owner credentials were not accepted. Repeated failures temporarily lock the handle.");localStorage.setItem(OWNER_WEB_EDIT_KEY,token);setPassword("");setActive(true);setOpen(false);setMessage("");window.dispatchEvent(new CustomEvent("hanami-owner-web-edit-change",{detail:{active:true}}));if(/\/portal\/?$/.test(window.location.pathname))window.location.assign("../");}catch(error){setMessage(error instanceof Error?error.message:"Owner sign-in failed.");}finally{setLoading(false);}}
 async function logout(){const token=localStorage.getItem(OWNER_WEB_EDIT_KEY);localStorage.removeItem(OWNER_WEB_EDIT_KEY);setActive(false);setOpen(false);window.dispatchEvent(new CustomEvent("hanami-owner-web-edit-change",{detail:{active:false}}));if(token){try{await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_logout`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:token})});}catch{}}window.location.reload();}
 if(active)return <div data-owner-editor-ignore style={{position:"fixed",left:10,bottom:10,zIndex:10060,display:"flex",alignItems:"center",gap:8,border:"1px solid #7f2c4d",background:"#fff7fb",boxShadow:"0 6px 22px rgba(0,0,0,.18)",padding:"6px 8px",fontFamily:"Arial,sans-serif",fontSize:10}}><strong style={{color:"#7f2c4d"}}>OWNER EDIT MODE</strong><button type="button" onClick={()=>void logout()}>Exit</button></div>;
 return <>{!open?<button data-owner-editor-ignore type="button" onClick={()=>setOpen(true)} style={{position:"fixed",left:0,top:"50%",transform:"translateY(-50%)",zIndex:10060,border:"1px solid #7f2c4d",borderLeft:0,background:"#fff",padding:"7px 6px",fontSize:9,fontWeight:700,cursor:"pointer",writingMode:"vertical-rl",textOrientation:"mixed",boxShadow:"2px 3px 10px rgba(0,0,0,.12)"}}>Owner Edit</button>:<div data-owner-editor-ignore onMouseDown={event=>{if(event.target===event.currentTarget){setOpen(false);setMessage("");}}} style={{position:"fixed",inset:0,zIndex:10070,display:"grid",placeItems:"center",padding:16,background:"rgba(17,31,51,.28)",fontFamily:"Arial,sans-serif"}}><section style={{width:"min(390px,calc(100vw - 32px))",maxHeight:"calc(100vh - 32px)",overflowY:"auto",border:"1px solid #7f2c4d",background:"#fff",boxShadow:"0 14px 40px rgba(0,0,0,.28)",padding:16,boxSizing:"border-box"}} aria-label="Owner website edit login"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><strong>OWNER WEBSITE ACCESS</strong><button type="button" onClick={()=>{setOpen(false);setMessage("");}} aria-label="Close Owner login">×</button></div><p style={{fontSize:11,lineHeight:1.4}}>Sign in with your Owner handle and password to edit the normal Hanami website directly. You may enter just the handle or your @hanamihigh.edu address. This does not sign you into a Student or Faculty character.</p><form onSubmit={login} style={{display:"grid",gap:10}}><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:3}}>OWNER HANDLE</span><input name="ownerHandle" value={handle} onChange={event=>setHandle(event.target.value)} autoComplete="username" maxLength={64} required style={{width:"100%",boxSizing:"border-box",padding:9}}/></label><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:3}}>PASSWORD</span><input name="ownerPassword" type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" required style={{width:"100%",boxSizing:"border-box",padding:9}}/></label><button type="submit" disabled={loading} style={{minHeight:40}}>{loading?"Verifying…":"Enter Owner Edit Mode"}</button></form>{message&&<small aria-live="polite" style={{display:"block",marginTop:8}}>{message}</small>}</section></div>}</>;
}
