"use client";

import {FormEvent,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
export const OWNER_WEB_EDIT_KEY="hanami.owner.web-edit.v1";

function rpcHeaders(){return {apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"};}

export default function OwnerWebsiteAccess(){
 const [active,setActive]=useState(false);const [open,setOpen]=useState(false);const [handle,setHandle]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
 useEffect(()=>{let cancelled=false;async function restore(){const token=localStorage.getItem(OWNER_WEB_EDIT_KEY);if(!token)return;try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_session_valid`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:token})});const valid=response.ok&&Boolean(await response.json());if(cancelled)return;if(valid)setActive(true);else localStorage.removeItem(OWNER_WEB_EDIT_KEY);}catch{if(!cancelled)setActive(false);}}void restore();return()=>{cancelled=true;};},[]);
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;const clean=handle.trim().toLowerCase();if(!/^[a-z0-9_]{3,32}$/.test(clean)){setMessage("Enter your Owner handle.");return;}if(password.length<12){setMessage("Owner passwords are at least 12 characters.");return;}setLoading(true);setMessage("Verifying Owner access…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_login`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_handle:clean,requested_password:password})});if(!response.ok)throw new Error("Owner sign-in could not be completed.");const token=await response.json() as string|null;if(!token)throw new Error("Owner credentials were not accepted. Repeated failures temporarily lock the handle.");localStorage.setItem(OWNER_WEB_EDIT_KEY,token);setPassword("");setActive(true);setOpen(false);setMessage("");window.dispatchEvent(new CustomEvent("hanami-owner-web-edit-change",{detail:{active:true}}));if(/\/portal\/?$/.test(window.location.pathname))window.location.assign("../");}catch(error){setMessage(error instanceof Error?error.message:"Owner sign-in failed.");}finally{setLoading(false);}}
 async function logout(){const token=localStorage.getItem(OWNER_WEB_EDIT_KEY);localStorage.removeItem(OWNER_WEB_EDIT_KEY);setActive(false);setOpen(false);window.dispatchEvent(new CustomEvent("hanami-owner-web-edit-change",{detail:{active:false}}));if(token){try{await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_logout`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:token})});}catch{}}window.location.reload();}
 if(active)return <div data-owner-editor-ignore style={{position:"fixed",left:14,bottom:14,zIndex:10060,display:"flex",alignItems:"center",gap:8,border:"1px solid #7f2c4d",background:"#fff7fb",boxShadow:"0 6px 22px rgba(0,0,0,.18)",padding:"8px 10px",fontFamily:"Arial,sans-serif",fontSize:11}}><strong style={{color:"#7f2c4d"}}>OWNER EDIT MODE</strong><button type="button" onClick={()=>void logout()}>Exit</button></div>;
 return <div data-owner-editor-ignore style={{position:"fixed",left:14,bottom:14,zIndex:10060,fontFamily:"Arial,sans-serif"}}>{!open?<button type="button" onClick={()=>setOpen(true)} style={{border:"1px solid #7f2c4d",background:"#fff",padding:"8px 10px",fontSize:10,fontWeight:700,cursor:"pointer"}}>Owner Edit Login</button>:<section style={{width:"min(330px,calc(100vw - 28px))",border:"1px solid #7f2c4d",background:"#fff",boxShadow:"0 8px 28px rgba(0,0,0,.2)",padding:12}} aria-label="Owner website edit login"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><strong>OWNER WEBSITE ACCESS</strong><button type="button" onClick={()=>{setOpen(false);setMessage("");}} aria-label="Close Owner login">×</button></div><p style={{fontSize:11,lineHeight:1.4}}>Sign in with your Owner handle and password to edit the normal Hanami website directly. This does not sign you into a Student or Faculty character.</p><form onSubmit={login} style={{display:"grid",gap:8}}><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:3}}>OWNER HANDLE</span><input value={handle} onChange={event=>setHandle(event.target.value)} autoComplete="username" maxLength={32} required style={{width:"100%",boxSizing:"border-box",padding:8}}/></label><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:3}}>PASSWORD</span><input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" required style={{width:"100%",boxSizing:"border-box",padding:8}}/></label><button type="submit" disabled={loading}>{loading?"Verifying…":"Enter Owner Edit Mode"}</button></form>{message&&<small aria-live="polite" style={{display:"block",marginTop:7}}>{message}</small>}</section>}</div>;
}
