/* eslint-disable react-hooks/immutability -- This component intentionally edits contentEditable DOM text nodes in Owner Edit Mode. */
"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {OWNER_WEB_EDIT_KEY} from "./OwnerWebsiteAccess";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Block={block_key:string;content:string};
type Editable={key:string;element:HTMLElement;baseline:string};

function publicPath(){let path=window.location.pathname;if(path.startsWith("/Hanami-High"))path=path.slice("/Hanami-High".length)||"/";if(!path.startsWith("/"))path=`/${path}`;return path.endsWith("/")&&path!=="/"?path.slice(0,-1):path;}
function roleDeskPath(path:string){return /^\/portal\/(student|faculty|admin|owner)(\/|$)/.test(path);}
function candidateNodes(){return [...document.querySelectorAll<HTMLElement>("header h1,header h2,header h3,header h4,header p,header li,main h1,main h2,main h3,main h4,main h5,main h6,main p,main li,main blockquote,main figcaption,main dt,main dd,aside h2,aside h3,aside h4,aside p,aside li,footer h2,footer h3,footer p,footer li")];}
function candidates(){return candidateNodes().filter(node=>{if((node.textContent??"").trim().length===0)return false;if(node.closest("form,button,a,nav,[data-owner-editor-ignore]"))return false;if(node.querySelector("a,button,input,select,textarea,form,[contenteditable='true']"))return false;return true;});}
function scanItems(){const seen=new Set<HTMLElement>();return candidates().filter(element=>{if(seen.has(element))return false;seen.add(element);return true;}).map((element,index)=>{const key=element.dataset.ownerTextKey??`${element.tagName.toLowerCase()}-${index}`;element.dataset.ownerTextKey=key;return {key,element,baseline:(element.textContent??"").trim()};});}
function applyEditableState(items:Editable[],enabled:boolean){for(const item of items){item.element.contentEditable=enabled?"true":"false";item.element.spellcheck=enabled;item.element.dataset.ownerEditable=enabled?"true":"false";if(enabled){item.element.style.outline="2px dashed #9b315b";item.element.style.outlineOffset="3px";item.element.style.cursor="text";item.element.style.backgroundColor="rgba(255,246,250,.72)";}else{item.element.style.removeProperty("outline");item.element.style.removeProperty("outline-offset");item.element.style.removeProperty("cursor");item.element.style.removeProperty("background-color");}}}
function rpcHeaders(){return {apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"};}

export default function PublicPageTextEditor(){
 const [owner,setOwner]=useState(false);const [editing,setEditing]=useState(false);const [status,setStatus]=useState("");const [detectedCount,setDetectedCount]=useState(0);const [webToken,setWebToken]=useState("");const itemsRef=useRef<Editable[]>([]);const page=useMemo(()=>typeof window==="undefined"?"/":publicPath(),[]);
 useEffect(()=>{if(roleDeskPath(page))return;let cancelled=false;async function init(){let ownerAccess=false;const storedWebToken=localStorage.getItem(OWNER_WEB_EDIT_KEY);if(storedWebToken){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_session_valid`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:storedWebToken})});if(response.ok&&Boolean(await response.json())){ownerAccess=true;setWebToken(storedWebToken);}else localStorage.removeItem(OWNER_WEB_EDIT_KEY);}catch{}}
 const detected=scanItems();try{const response=await fetch(`${SUPABASE_URL}/rest/v1/public_page_text_blocks?select=block_key,content&page_path=eq.${encodeURIComponent(page)}`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(response.ok){const blocks=await response.json() as Block[];const map=new Map(blocks.map(block=>[block.block_key,block.content]));for(const item of detected){const override=map.get(item.key);if(typeof override==="string"){item.element.textContent=override;item.baseline=override;}}}}catch{}if(!cancelled){itemsRef.current=detected;setDetectedCount(detected.length);setOwner(ownerAccess);}}void init();return()=>{cancelled=true;applyEditableState(itemsRef.current,false);};},[page]);
 useEffect(()=>{applyEditableState(itemsRef.current,editing);return()=>applyEditableState(itemsRef.current,false);},[editing]);
 function beginEditing(){const rescanned=scanItems();itemsRef.current=rescanned;setDetectedCount(rescanned.length);applyEditableState(rescanned,true);setEditing(true);setStatus(rescanned.length?`Editing ${rescanned.length} text blocks. Click any outlined text and type.`:"No editable text blocks were detected on this page.");}
 async function save(){if(!webToken)return;setStatus("Saving page text…");let changed=0;const nextItems:Editable[]=[];for(const item of itemsRef.current){const content=(item.element.textContent??"").trim();if(content===item.baseline){nextItems.push(item);continue;}const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_save_public_page_text`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:webToken,requested_page_path:page,requested_block_key:item.key,requested_content:content})});if(!response.ok){setStatus("One or more text blocks could not be saved.");return;}nextItems.push({...item,baseline:content});changed++;}itemsRef.current=nextItems;setEditing(false);setStatus(changed?`${changed} text block${changed===1?"":"s"} published.`:"No text changes to publish.");}
 function cancel(){for(const item of itemsRef.current)item.element.textContent=item.baseline;setEditing(false);setStatus("Changes cancelled.");}
 async function exitEditMode(){applyEditableState(itemsRef.current,false);setEditing(false);const stored=localStorage.getItem(OWNER_WEB_EDIT_KEY);localStorage.removeItem(OWNER_WEB_EDIT_KEY);if(stored){try{await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_web_edit_logout`,{method:"POST",headers:rpcHeaders(),body:JSON.stringify({requested_token:stored})});}catch{}}setWebToken("");setOwner(false);window.location.reload();}
 if(!owner||roleDeskPath(page))return null;
 return <div data-owner-editor-ignore style={{position:"fixed",right:14,bottom:14,zIndex:10050,width:"min(380px,calc(100vw - 28px))",border:"1px solid #7f2c4d",background:"#fff",boxShadow:"0 8px 28px rgba(0,0,0,.2)",padding:10,fontFamily:"Verdana,Arial,sans-serif",fontSize:12}} aria-label="Owner public page editor"><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong>OWNER PAGE EDITOR</strong><span>{page}</span></div><p style={{margin:"6px 0",fontSize:11}}>You are viewing the normal website in Owner Edit Mode. Plain text content can be edited in place. Dynamic school data stays managed by its normal Admin tools.</p><small style={{display:"block",marginBottom:6}}>{detectedCount} editable text block{detectedCount===1?"":"s"} detected</small><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{!editing?<button type="button" onClick={beginEditing}>Edit page text</button>:<><button type="button" onClick={()=>void save()}>Publish changes</button><button type="button" onClick={cancel}>Cancel</button></>}<button type="button" onClick={()=>void exitEditMode()}>Exit edit mode</button></div>{status&&<small style={{display:"block",marginTop:6}}>{status}</small>}</div>;
}
