"use client";

import {useEffect} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const CONFIG_KEY="hanami.roleplay.clock.v2";
type ClockConfig={timezone:string;roleplay_anchor_date:string;real_anchor_date:string;manual_active?:boolean;manual_roleplay_at?:string;manual_real_at?:string;manual_frozen?:boolean};
const DEFAULT_CONFIG:ClockConfig={timezone:"Asia/Tokyo",roleplay_anchor_date:"2006-04-07",real_anchor_date:"2026-08-21",manual_active:false,manual_frozen:false};

function zonedParts(now:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(now);const read=(type:Intl.DateTimeFormatPartTypes)=>Number(parts.find(part=>part.type===type)?.value??0);return {year:read("year"),month:read("month"),day:read("day"),hour:read("hour"),minute:read("minute"),second:read("second")};}
function dayNumber(iso:string){const [y,m,d]=iso.split("-").map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000);}
function automaticRoleplayNow(config:ClockConfig){const real=zonedParts(new Date(),config.timezone);const realToday=Math.floor(Date.UTC(real.year,real.month-1,real.day)/86400000);const delta=realToday-dayNumber(config.real_anchor_date);const yearStart=dayNumber("2006-01-01");const anchor=dayNumber(config.roleplay_anchor_date);const wrapped=((anchor+delta-yearStart)%365+365)%365;const roleplayDay=new Date((yearStart+wrapped)*86400000);const y=roleplayDay.getUTCFullYear(),m=String(roleplayDay.getUTCMonth()+1).padStart(2,"0"),d=String(roleplayDay.getUTCDate()).padStart(2,"0");const hh=String(real.hour).padStart(2,"0"),mm=String(real.minute).padStart(2,"0"),ss=String(real.second).padStart(2,"0");return new Date(`${y}-${m}-${d}T${hh}:${mm}:${ss}+09:00`);}
function roleplayNow(config:ClockConfig){if(config.manual_active&&config.manual_roleplay_at){const base=new Date(config.manual_roleplay_at);if(config.manual_frozen)return base;const setAt=config.manual_real_at?new Date(config.manual_real_at):new Date();return new Date(base.getTime()+Math.max(0,Date.now()-setAt.getTime()));}return automaticRoleplayNow(config);}
function formatClock(config:ClockConfig){return `${new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",hour12:true,timeZone:config.timezone}).format(roleplayNow(config))} JST`;}

export default function RoleplayClockRuntime(){useEffect(()=>{let cancelled=false;let config=DEFAULT_CONFIG;let timer:number|undefined;function paint(){const value=formatClock(config).toUpperCase();document.querySelectorAll<HTMLElement>(".school-clock strong,[data-hanami-roleplay-clock]").forEach(node=>{node.textContent=value;});}function apply(next:ClockConfig){config={...DEFAULT_CONFIG,...next};try{localStorage.setItem(CONFIG_KEY,JSON.stringify(config));}catch{}paint();window.dispatchEvent(new CustomEvent("hanami-roleplay-clock-runtime",{detail:config}));}async function start(){try{const cached=localStorage.getItem(CONFIG_KEY);if(cached)config={...DEFAULT_CONFIG,...JSON.parse(cached) as ClockConfig};}catch{}paint();try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_runtime_config?select=value&key=eq.roleplay_clock&limit=1`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(response.ok){const rows=await response.json() as Array<{value?:Partial<ClockConfig>}>;const value=rows[0]?.value;if(value)apply({...config,...value});}}catch{}if(cancelled)return;timer=window.setInterval(paint,30000);}function manualUpdate(event:Event){const next=(event as CustomEvent<ClockConfig>).detail;if(next)apply(next);}window.addEventListener("hanami-roleplay-clock-updated",manualUpdate);void start();return()=>{cancelled=true;window.removeEventListener("hanami-roleplay-clock-updated",manualUpdate);if(timer)window.clearInterval(timer);};},[]);return null;}
