"use client";

import {useEffect} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
function readToken(){try{return (JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string}).accessToken??"";}catch{return "";}}
function readCharacter(){try{return localStorage.getItem("hanami.portal.character.v1")||null;}catch{return null;}}
function fingerprint(text:string){let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return `runtime:${(hash>>>0).toString(16)}:${text.slice(0,80)}`.slice(0,240);}
async function health(nativeFetch:typeof fetch,eventType:"request_failure"|"upload_failure"|"client_error"|"warning",summary:string,detail:Record<string,unknown>={}){const token=readToken();if(!token)return;try{await nativeFetch(`${SUPABASE_URL}/rest/v1/client_health_events`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({character_id:readCharacter(),event_type:eventType,page_path:location.pathname+location.search,summary:summary.slice(0,500),detail})});}catch{/* health reporting must never break the page */}}
async function report(nativeFetch:typeof fetch,title:string,details:string,metadata:Record<string,unknown>={}){const token=readToken();if(!token)return;const key=fingerprint(`${location.pathname}|${title}|${details.slice(0,240)}`);try{await nativeFetch(`${SUPABASE_URL}/rest/v1/rpc/report_client_bug`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({bug_fingerprint:key,bug_title:title.slice(0,220),bug_details:details.slice(0,8000),bug_route:location.pathname+location.search,bug_area:location.pathname.startsWith("/portal")?"portal":"public-site",bug_severity:"medium",bug_metadata:{userAgent:navigator.userAgent,...metadata}})});}catch{/* detector reporting must never break the page */}}
export default function RuntimeBugReporter(){useEffect(()=>{const nativeFetch=window.fetch.bind(window);const onError=(event:ErrorEvent)=>{const details=event.error?.stack||`${event.filename??""}:${event.lineno??0}:${event.colno??0}`;void report(nativeFetch,event.message||"Unhandled browser error",details,{kind:"error"});void health(nativeFetch,"client_error",event.message||"Unhandled browser error",{details});};const onRejection=(event:PromiseRejectionEvent)=>{const reason=event.reason instanceof Error?`${event.reason.message}\n${event.reason.stack??""}`:String(event.reason);void report(nativeFetch,"Unhandled promise rejection",reason,{kind:"unhandledrejection"});void health(nativeFetch,"client_error","Unhandled promise rejection",{reason:reason.slice(0,2000)});};const monitoredFetch:typeof fetch=async(input,init)=>{const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url;if(url.includes("/client_health_events")||url.includes("/rpc/report_client_bug"))return nativeFetch(input,init);try{const response=await nativeFetch(input,init);if(response.status>=500){const upload=url.includes("/storage/v1/object/");void health(nativeFetch,upload?"upload_failure":"request_failure",`${response.status} ${response.statusText||"request failed"}`,{url:url.slice(0,500),method:init?.method??"GET"});}return response;}catch(error){const upload=url.includes("/storage/v1/object/");void health(nativeFetch,upload?"upload_failure":"request_failure",error instanceof Error?error.message:"Network request failed",{url:url.slice(0,500),method:init?.method??"GET"});throw error;}};window.fetch=monitoredFetch;window.addEventListener("error",onError);window.addEventListener("unhandledrejection",onRejection);return()=>{window.fetch=nativeFetch;window.removeEventListener("error",onError);window.removeEventListener("unhandledrejection",onRejection);};},[]);return null;}
