"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./OwnerOperationsPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Flag={key:string;description:string;enabled:boolean;tester_only:boolean;updated_at:string};
type Account={user_id:string;display_name:string;discord_username:string;discord_user_id:string;account_status:string};
type Sanction={id:string;user_id:string;character_id:string|null;sanction_type:string;reason:string;starts_at:string;ends_at:string|null;active:boolean};
type Maintenance={enabled?:boolean;message?:string};

export default function OwnerOperationsPanel({accessToken}:{accessToken:string}){
 const [flags,setFlags]=useState<Flag[]>([]);const [accounts,setAccounts]=useState<Account[]>([]);const [sanctions,setSanctions]=useState<Sanction[]>([]);const [maintenance,setMaintenance]=useState<Maintenance>({enabled:false,message:"Hanami School Network maintenance is in progress."});const [notice,setNotice]=useState("Loading Owner operations…");const [saving,setSaving]=useState(false);
 const [targetUser,setTargetUser]=useState("");const [sanctionType,setSanctionType]=useState("messaging_mute");const [reason,setReason]=useState("");const [endAt,setEndAt]=useState("");
 const load=useCallback(async()=>{try{const [f,r,s,a]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/feature_flags?select=key,description,enabled,tester_only,updated_at&order=key.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/site_runtime_config?select=key,value&key=eq.maintenance&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/account_sanctions?select=id,user_id,character_id,sanction_type,reason,starts_at,ends_at,active&active=eq.true&order=created_at.desc&limit=100`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/account_governance_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({search_text:""})})
 ]);if(!f.ok||!r.ok||!s.ok||!a.ok)throw new Error("Owner operations data could not be loaded.");const [flagRows,runtimeRows,sanctionRows,accountRows]=await Promise.all([f.json() as Promise<Flag[]>,r.json() as Promise<Array<{value:Maintenance}>>,s.json() as Promise<Sanction[]>,a.json() as Promise<Account[]>]);setFlags(flagRows);setMaintenance(runtimeRows[0]?.value??{enabled:false});setSanctions(sanctionRows);setAccounts(accountRows);setTargetUser(current=>current||accountRows[0]?.user_id||"");setNotice(`${flagRows.length} feature flags • ${sanctionRows.length} active sanction${sanctionRows.length===1?"":"s"}.`);}catch(error){setNotice(error instanceof Error?error.message:"Owner operations could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function saveFlag(flag:Flag,patch:Partial<Flag>){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/feature_flags?key=eq.${encodeURIComponent(flag.key)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Feature flag could not be changed.");await load();setNotice(`${flag.key} updated.`);}catch(error){setNotice(error instanceof Error?error.message:"Feature flag could not be changed.");}finally{setSaving(false);}}
 async function saveMaintenance(next:Maintenance){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_runtime_config?key=eq.maintenance`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({value:next,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Maintenance setting could not be changed.");setMaintenance(next);setNotice(next.enabled?"Maintenance mode enabled for the Hanami network.":"Maintenance mode disabled.");}catch(error){setNotice(error instanceof Error?error.message:"Maintenance setting could not be changed.");}finally{setSaving(false);}}
 async function createSanction(event:FormEvent){event.preventDefault();if(!targetUser||reason.trim().length<3)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/account_sanctions`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({user_id:targetUser,sanction_type:sanctionType,reason:reason.trim(),ends_at:endAt?new Date(endAt).toISOString():null})});if(!response.ok)throw new Error("Sanction could not be created.");setReason("");setEndAt("");await load();setNotice("Granular account sanction applied.");}catch(error){setNotice(error instanceof Error?error.message:"Sanction could not be created.");}finally{setSaving(false);}}
 async function liftSanction(item:Sanction){if(!confirm("Lift this sanction now?"))return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/account_sanctions?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({active:false,lifted_at:new Date().toISOString()})});if(!response.ok)throw new Error("Sanction could not be lifted.");await load();setNotice("Sanction lifted.");}catch(error){setNotice(error instanceof Error?error.message:"Sanction could not be lifted.");}finally{setSaving(false);}}
 const accountName=(id:string)=>{const a=accounts.find(x=>x.user_id===id);return a?.display_name||a?.discord_username||a?.discord_user_id||id.slice(0,8);};
 return <section className={styles.panel} aria-labelledby="owner-operations-title"><div className={styles.heading}><div><p className="eyebrow">OWNER • NETWORK OPERATIONS</p><h3 id="owner-operations-title">Rollouts, maintenance & sanctions</h3></div><span>OWNER ONLY</span></div><div className={styles.notice}>{notice}</div>
  <div className={styles.grid}>
   <div className={styles.block}><h4>Feature Flags</h4><p>Turn unfinished or tester-only systems on and off without deleting code.</p>{flags.map(flag=><article key={flag.key}><div><strong>{flag.key}</strong><span>{flag.description}</span></div><label><input type="checkbox" checked={flag.enabled} disabled={saving} onChange={e=>saveFlag(flag,{enabled:e.target.checked})}/> Enabled</label><label><input type="checkbox" checked={flag.tester_only} disabled={saving} onChange={e=>saveFlag(flag,{tester_only:e.target.checked})}/> Tester only</label></article>)}</div>
   <div className={styles.block}><h4>Maintenance Mode</h4><p>Keep Owner/Admin access available while placing the school network into maintenance.</p><label className={styles.switch}><input type="checkbox" checked={Boolean(maintenance.enabled)} disabled={saving} onChange={e=>saveMaintenance({...maintenance,enabled:e.target.checked})}/> Maintenance enabled</label><textarea value={maintenance.message??""} onChange={e=>setMaintenance(current=>({...current,message:e.target.value}))}/><button type="button" disabled={saving} onClick={()=>saveMaintenance(maintenance)}>Save maintenance message</button></div>
   <div className={styles.block}><h4>Apply Account Sanction</h4><p>Use a narrow restriction when a full account suspension is unnecessary.</p><form onSubmit={createSanction}><select value={targetUser} onChange={e=>setTargetUser(e.target.value)}>{accounts.map(a=><option key={a.user_id} value={a.user_id}>{accountName(a.user_id)}</option>)}</select><select value={sanctionType} onChange={e=>setSanctionType(e.target.value)}><option value="portal_restriction">Portal restriction</option><option value="messaging_mute">Messaging mute</option><option value="profile_studio_restriction">Profile Studio restriction</option><option value="club_restriction">Club restriction</option><option value="full_suspension">Full suspension</option></select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason" required/><label>Optional expiration <input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label><button disabled={saving}>Apply sanction</button></form></div>
   <div className={styles.block}><h4>Active Sanctions</h4>{sanctions.length?sanctions.map(item=><article key={item.id}><div><strong>{accountName(item.user_id)}</strong><span>{item.sanction_type.replaceAll("_"," ")} • {item.ends_at?`until ${new Date(item.ends_at).toLocaleString()}`:"no automatic expiration"}</span><p>{item.reason}</p></div><button type="button" disabled={saving} onClick={()=>liftSanction(item)}>Lift</button></article>):<p>No active granular sanctions.</p>}</div>
  </div>
 </section>;
}
