"use client";

import {FormEvent,useEffect,useState} from "react";
import styles from "./OwnerRoleplayClockPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const CONFIG_KEY="hanami.roleplay.clock.v2";
type Props={accessToken:string};
type ClockConfig={timezone:string;roleplay_anchor_date:string;real_anchor_date:string;manual_active?:boolean;manual_roleplay_at?:string;manual_real_at?:string;manual_frozen?:boolean};
const DEFAULT:ClockConfig={timezone:"Asia/Tokyo",roleplay_anchor_date:"2006-04-07",real_anchor_date:"2026-08-21",manual_active:false,manual_frozen:false};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function localInputFromIso(value:string|undefined){if(!value)return "2006-04-07T08:00";const date=new Date(value);return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(date).replace(" ","T");}
function tokyoIsoFromLocal(value:string){return `${value}:00+09:00`;}

export default function OwnerRoleplayClockPanel({accessToken}:Props){
 const [config,setConfig]=useState<ClockConfig>(DEFAULT);const [dateTime,setDateTime]=useState("2006-04-07T08:00");const [frozen,setFrozen]=useState(false);const [message,setMessage]=useState("Loading Hanami clock configuration…");const [saving,setSaving]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_runtime_config?select=value&key=eq.roleplay_clock&limit=1`,{headers:headers(accessToken)});if(!response.ok)throw new Error("Clock configuration could not be loaded.");const rows=await response.json() as {value?:ClockConfig}[];const value={...DEFAULT,...(rows[0]?.value??{})};if(cancelled)return;setConfig(value);setDateTime(localInputFromIso(value.manual_active?value.manual_roleplay_at:`${value.roleplay_anchor_date}T08:00:00+09:00`));setFrozen(Boolean(value.manual_frozen));setMessage(value.manual_active?`Manual school clock is active${value.manual_frozen?" and frozen":" and running"}.`:"Automatic roleplay clock is active.");}catch(error){if(!cancelled)setMessage(error instanceof Error?error.message:"Clock configuration unavailable.");}})();return()=>{cancelled=true;};},[accessToken]);
 async function persist(next:ClockConfig,success:string){setSaving(true);setMessage("Updating the school-wide clock…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_runtime_config?key=eq.roleplay_clock`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({value:next,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("The roleplay clock could not be updated.");localStorage.setItem(CONFIG_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent("hanami-roleplay-clock-updated",{detail:next}));setConfig(next);setMessage(success);window.setTimeout(()=>window.location.reload(),350);}catch(error){setMessage(error instanceof Error?error.message:"The roleplay clock could not be updated.");}finally{setSaving(false);}}
 async function setManual(event:FormEvent){event.preventDefault();if(!dateTime.startsWith("2006-")){setMessage("Hanami roleplay dates must stay in 2006.");return;}const now=new Date();const next:ClockConfig={...config,timezone:"Asia/Tokyo",manual_active:true,manual_roleplay_at:tokyoIsoFromLocal(dateTime),manual_real_at:now.toISOString(),manual_frozen:frozen};await persist(next,`School-wide date and time set to ${dateTime.replace("T"," ")} JST${frozen?" (frozen)":""}.`);}
 async function reset(){const next:ClockConfig={...config,manual_active:false,manual_roleplay_at:undefined,manual_real_at:undefined,manual_frozen:false};await persist(next,"Automatic Hanami 2006 clock restored.");}
 return <section className={styles.panel} aria-labelledby="owner-clock-title"><div className={styles.heading}><div><p className="eyebrow">GLOBAL ROLEPLAY CLOCK</p><h3 id="owner-clock-title">Set website date & time</h3></div><span>{config.manual_active?config.manual_frozen?"MANUAL • FROZEN":"MANUAL • RUNNING":"AUTOMATIC"}</span></div><p className={styles.help}>This controls the date and time used across Hanami High. Dates stay in 2006. A running manual clock continues forward from the time you set; frozen mode keeps the entire website at the exact selected moment.</p><form className={styles.form} onSubmit={setManual}><label><span>HANAMI DATE & TIME • JST</span><input type="datetime-local" min="2006-01-01T00:00" max="2006-12-31T23:59" value={dateTime} onChange={event=>setDateTime(event.target.value)} required/></label><label className={styles.check}><input type="checkbox" checked={frozen} onChange={event=>setFrozen(event.target.checked)}/><span>Freeze the school clock at this exact time</span></label><div className={styles.actions}><button type="submit" disabled={saving}>{saving?"Updating…":"Set global date & time"}</button><button type="button" onClick={reset} disabled={saving}>Restore automatic clock</button></div></form><div className={styles.status} aria-live="polite">{message}</div></section>;
}
