"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import PrivilegedPortalLogin from "../PrivilegedPortalLogin";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}

export default function OwnerPortalClient(){
 const [session,setSession]=useState<PortalSession|null>(null);const [state,setState]=useState<"loading"|"signin"|"ready"|"blocked">("loading");const [message,setMessage]=useState("Checking Owner identity…");const [adminHandle,setAdminHandle]=useState("");const [adminPassword,setAdminPassword]=useState("");const [adminDiscordId,setAdminDiscordId]=useState("");const [saving,setSaving]=useState(false);
 const initialize=useCallback(async()=>{const stored=readSession();if(!stored){setState("blocked");setMessage("Sign in through the Hanami Portal Gateway first.");return;}setSession(stored);const [ownerResponse,privilegedResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(stored.accessToken,{"Content-Type":"application/json"}),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/rpc/has_privileged_portal_session`,{method:"POST",headers:headers(stored.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:"owner"})})]);if(!ownerResponse.ok||!privilegedResponse.ok){setState("blocked");setMessage("Owner access could not be verified.");return;}const isOwner=Boolean(await ownerResponse.json());if(!isOwner){setState("blocked");setMessage("This Discord account is not the configured Hanami Owner account.");return;}const privileged=Boolean(await privilegedResponse.json());if(!privileged){setState("signin");setMessage("Owner identity confirmed. Enter the separate Owner credentials.");return;}setState("ready");setMessage("Owner identity and privileged sign-in verified.");},[]);
 useEffect(()=>{initialize();},[initialize]);
 async function createAdmin(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!session||saving)return;setSaving(true);setMessage("Creating administrator credential…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_create_admin_credential`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_handle:adminHandle.trim().toLowerCase(),requested_password:adminPassword,target_discord_user_id:adminDiscordId.trim()})});if(!response.ok)throw new Error("Administrator credential could not be created. Use a unique handle, 12+ character password, and the administrator's Discord user ID.");setAdminHandle("");setAdminPassword("");setAdminDiscordId("");setMessage("Administrator credential created and bound to that Discord user ID.");}catch(error){setMessage(error instanceof Error?error.message:"Administrator credential could not be created.");}finally{setSaving(false);}}
 async function lockOwner(){if(session)await fetch(`${SUPABASE_URL}/rest/v1/rpc/end_privileged_portal_session`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:"owner"})});setState("signin");setMessage("Owner portal locked. Normal Hanami sign-in remains active.");}
 if(state==="signin")return <PrivilegedPortalLogin portalKind="owner" allowOwnerBootstrap onUnlocked={initialize}/>;
 if(state!=="ready"||!session)return <section className="portal-account-card"><p className="eyebrow">OWNER PORTAL</p><h2>{state==="loading"?"Verifying Owner access…":"Owner access unavailable"}</h2><p>{message}</p><a className="secondary-action" href="../">Return to Portal Gateway</a></section>;
 return <div className="portal-account-card"><p className="eyebrow">HANAMI OWNER CONTROL</p><h2>Owner access verified</h2><p className="portal-account-note">Owner controls are separate from Student, Faculty, and Administrator character roles. This session remains unlocked for up to 8 hours unless you lock it sooner.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}><a className="secondary-action" href="../admin/">Administrator Portal</a><a className="secondary-action" href="../student/">Student Portal</a><a className="secondary-action" href="../faculty/">Faculty Portal</a><button className="secondary-action" type="button" onClick={lockOwner}>Lock Owner Portal</button></div><section style={{marginTop:18,paddingTop:14,borderTop:"1px solid #c8b5bf"}}><p className="eyebrow">ADMINISTRATOR CREDENTIALS</p><h3>Create a bound Administrator sign-in</h3><p style={{fontSize:10,color:"#66758a"}}>Use the administrator's Discord <b>user ID</b>, not the Discord role ID. The Administrator password is hashed immediately and never stored in plaintext.</p><form onSubmit={createAdmin} style={{display:"grid",gap:9,maxWidth:520}}><label><span style={{display:"block",fontSize:8,fontWeight:700}}>ADMIN HANDLE</span><input value={adminHandle} onChange={event=>setAdminHandle(event.target.value)} maxLength={32} required style={{width:"100%",padding:8,boxSizing:"border-box"}}/></label><label><span style={{display:"block",fontSize:8,fontWeight:700}}>ADMIN DISCORD USER ID</span><input value={adminDiscordId} onChange={event=>setAdminDiscordId(event.target.value)} inputMode="numeric" required style={{width:"100%",padding:8,boxSizing:"border-box"}}/></label><label><span style={{display:"block",fontSize:8,fontWeight:700}}>ADMIN PASSWORD • 12+ CHARACTERS</span><input type="password" value={adminPassword} onChange={event=>setAdminPassword(event.target.value)} minLength={12} required style={{width:"100%",padding:8,boxSizing:"border-box"}}/></label><button className="discord-button" type="submit" disabled={saving}>{saving?"Saving…":"Create Administrator Credential"}</button></form></section><small aria-live="polite">{message}</small></div>;
}
