"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./OwnerDiscordRoleSyncPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}

export default function OwnerDiscordRoleSyncPanel({accessToken}:{accessToken:string}){
 const [guildId,setGuildId]=useState("");const [savedGuildId,setSavedGuildId]=useState("");const [notice,setNotice]=useState("Loading Discord server configuration…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_discord_guild_configuration`,{method:"POST",headers:headers(accessToken),body:"{}"});if(!response.ok)throw new Error("Discord server configuration could not be loaded.");const rows=await response.json() as {guild_id:string}[];const value=rows[0]?.guild_id??"";setGuildId(value);setSavedGuildId(value);setNotice(value?"Discord server ID configured. Members can synchronize roles after signing in with the expanded Discord permissions.":"Enter the Hanami Discord server ID to activate automatic role synchronization.");}catch(error){setNotice(error instanceof Error?error.message:"Discord server configuration could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function save(event:FormEvent){event.preventDefault();const clean=guildId.trim();if(!/^\d{16,22}$/.test(clean)){setNotice("Enter a valid numeric Discord server ID.");return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_set_discord_guild_id`,{method:"POST",headers:headers(accessToken),body:JSON.stringify({requested_guild_id:clean})});if(!response.ok)throw new Error("Discord server ID could not be saved.");setSavedGuildId(clean);setNotice("Discord server ID saved. Existing members should sign out and sign back in once so Discord can grant the role-reading scope, then use Resync roles in the Portal Gateway.");}catch(error){setNotice(error instanceof Error?error.message:"Discord server ID could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="owner-discord-sync-title"><div className={styles.heading}><div><p className="eyebrow">DISCORD ROLE SYNCHRONIZATION</p><h3 id="owner-discord-sync-title">Server role authority</h3></div><span>{savedGuildId?"CONFIGURED":"SETUP REQUIRED"}</span></div><p>Hanami verifies Student, Faculty, and Administrator roles from each member&apos;s own Discord authorization. No Discord bot token is required.</p><form onSubmit={save}><label><span>HANAMI DISCORD SERVER ID</span><input value={guildId} onChange={event=>setGuildId(event.target.value)} inputMode="numeric" placeholder="Example: 123456789012345678" maxLength={22}/></label><button disabled={saving} type="submit">{saving?"Saving…":"Save Server ID"}</button></form><div className={styles.notice} aria-live="polite">{notice}</div><small>To copy the server ID in Discord, enable Developer Mode, then right-click the Hanami server and choose Copy Server ID. The ID is an identifier, not a private credential.</small></section>;
}
