"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./OwnerHomeroomScheduleEditor.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const DAYS=[{id:1,label:"Monday"},{id:2,label:"Tuesday"},{id:3,label:"Wednesday"},{id:4,label:"Thursday"},{id:5,label:"Friday"}] as const;
const PERIODS=[{number:1,label:"Period 1",time:"8:50–9:40"},{number:2,label:"Period 2",time:"9:50–10:40"},{number:3,label:"Period 3",time:"10:50–11:40"},{number:4,label:"Period 4",time:"11:50–12:40"},{number:5,label:"Period 5",time:"1:25–2:15"},{number:6,label:"Period 6",time:"2:25–3:15"}] as const;

type Homeroom={id:string;code:string;school_year:string;is_active:boolean};
type Course={code:string;title:string};
type Section={id:string;section_code:string;room:string|null;academic_courses:Course|null};
type Block={id:string;block_type:string;title:string;weekday:number;starts_at:string;homeroom_label:string|null;notes:string|null};
type InstructorMembership={section_id:string;character_id:string};
type Faculty={id:string;display_name:string};
type WeekDraft=Record<number,string[]>;

function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
function blankWeek():WeekDraft{return Object.fromEntries(DAYS.map(day=>[day.id,Array(6).fill("__OPEN__")])) as WeekDraft;}
function normalizedHomeroom(value:string|null){return (value??"").replace(/^Homeroom\s+/i,"").trim().toUpperCase();}
function periodFromStart(value:string){const key=value.slice(0,5);return ({"08:50":1,"09:50":2,"10:50":3,"11:50":4,"13:25":5,"14:25":6} as Record<string,number>)[key]??0;}
function isClass(value:string){return !value.startsWith("__");}
function shortLabel(value:string,courses:Map<string,Course>){if(value==="__OPEN__")return "Open";if(value==="__STUDY__")return "Study";if(value==="__EXTRACURRICULAR__")return "Extracurricular";return courses.get(value)?.title??value;}

export default function OwnerHomeroomScheduleEditor({accessToken}:{accessToken:string}){
 const [homerooms,setHomerooms]=useState<Homeroom[]>([]),[homeroomCode,setHomeroomCode]=useState(""),[sections,setSections]=useState<Section[]>([]),[blocks,setBlocks]=useState<Block[]>([]),[memberships,setMemberships]=useState<InstructorMembership[]>([]),[faculty,setFaculty]=useState<Faculty[]>([]),[week,setWeek]=useState<WeekDraft>(blankWeek()),[activeDay,setActiveDay]=useState(1),[notice,setNotice]=useState("Loading weekly classroom planner…"),[saving,setSaving]=useState(false);
 const facultyNames=useMemo(()=>new Map(faculty.map(row=>[row.id,row.display_name])),[faculty]);
 const instructorIdsBySection=useMemo(()=>{const map=new Map<string,string[]>();for(const row of memberships)map.set(row.section_id,[...(map.get(row.section_id)??[]),row.character_id]);return map;},[memberships]);
 const sectionFor=useCallback((courseCode:string)=>sections.find(section=>section.academic_courses?.code.toUpperCase()===courseCode.toUpperCase()),[sections]);
 const courses=useMemo(()=>{const map=new Map<string,Course>();for(const section of sections){const course=section.academic_courses;if(course&&!map.has(course.code))map.set(course.code,course);}return [...map.values()].sort((a,b)=>a.title.localeCompare(b.title));},[sections]);
 const courseMap=useMemo(()=>new Map(courses.map(course=>[course.code,course])),[courses]);
 const buildSavedWeek=useCallback((code:string,allBlocks=blocks)=>{const next=blankWeek();for(const block of allBlocks){if(block.notes!=="owner_homeroom_daily_schedule"||normalizedHomeroom(block.homeroom_label)!==code.toUpperCase())continue;const period=periodFromStart(block.starts_at);if(!period||block.weekday<1||block.weekday>5)continue;if(block.block_type==="class_period")next[block.weekday][period-1]=block.title.toUpperCase();else if(block.block_type==="study")next[block.weekday][period-1]="__STUDY__";else if(block.block_type==="extracurricular")next[block.weekday][period-1]="__EXTRACURRICULAR__";}return next;},[blocks]);
 const schoolWeek=useMemo(()=>{const result=new Map<string,WeekDraft>();for(const room of homerooms)result.set(room.code,buildSavedWeek(room.code));if(homeroomCode)result.set(homeroomCode,week);return result;},[homerooms,buildSavedWeek,homeroomCode,week]);
 const conflicts=useMemo(()=>{const map=new Map<string,string[]>();const add=(code:string,day:number,period:number,msg:string)=>{const key=`${code}:${day}:${period}`;map.set(key,[...(map.get(key)??[]),msg]);};for(const day of DAYS)for(const period of PERIODS)for(let i=0;i<homerooms.length;i++)for(let j=i+1;j<homerooms.length;j++){const a=homerooms[i].code,b=homerooms[j].code,aa=schoolWeek.get(a)?.[day.id]?.[period.number-1]??"__OPEN__",bb=schoolWeek.get(b)?.[day.id]?.[period.number-1]??"__OPEN__";if(!isClass(aa)||!isClass(bb))continue;const sa=sectionFor(aa),sb=sectionFor(bb);if(!sa||!sb)continue;const shared=(instructorIdsBySection.get(sa.id)??[]).filter(id=>(instructorIdsBySection.get(sb.id)??[]).includes(id));for(const id of shared){const name=facultyNames.get(id)??"Same instructor";add(a,day.id,period.number,`${name} is also teaching Homeroom ${b}.`);add(b,day.id,period.number,`${name} is also teaching Homeroom ${a}.`);}const roomA=(sa.room??"").trim().toLowerCase(),roomB=(sb.room??"").trim().toLowerCase();if(roomA&&roomB&&roomA===roomB){add(a,day.id,period.number,`${sa.room} is also assigned to Homeroom ${b}.`);add(b,day.id,period.number,`${sb.room} is also assigned to Homeroom ${a}.`);}}return map;},[homerooms,schoolWeek,sectionFor,instructorIdsBySection,facultyNames]);
 const selectedConflictCount=useMemo(()=>DAYS.reduce((total,day)=>total+PERIODS.filter(period=>(conflicts.get(`${homeroomCode}:${day.id}:${period.number}`)?.length??0)>0).length,0),[conflicts,homeroomCode]);
 const activeDayConflicts=useMemo(()=>PERIODS.filter(period=>(conflicts.get(`${homeroomCode}:${activeDay}:${period.number}`)?.length??0)>0).length,[conflicts,homeroomCode,activeDay]);

 const load=useCallback(async(targetCode?:string)=>{try{const [h,s,b,m,f]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/homerooms?select=id,code,school_year,is_active&is_active=eq.true&order=code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=${encodeURIComponent("id,section_code,room,academic_courses(code,title)")}&order=created_at.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,block_type,title,weekday,starts_at,homeroom_label,notes&notes=eq.owner_homeroom_daily_schedule`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id,character_id&relationship=eq.instructor`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name&role=eq.faculty`,{headers:headers(accessToken)})
 ]);if(!h.ok||!s.ok||!b.ok||!m.ok||!f.ok)throw new Error("The weekly classroom schedule could not be loaded.");const hs=await h.json() as Homeroom[],ss=await s.json() as Section[],bb=await b.json() as Block[];setHomerooms(hs);setSections(ss);setBlocks(bb);setMemberships(await m.json() as InstructorMembership[]);setFaculty(await f.json() as Faculty[]);const code=targetCode||homeroomCode||hs[0]?.code||"";if(!code){setNotice("No active homerooms are available.");return;}if(code!==homeroomCode)setHomeroomCode(code);setWeek(buildSavedWeek(code,bb));setNotice(`Editing the full Monday–Friday schedule for Homeroom ${code}. ${ss.length?"Shared classes are available in every period menu.":"No shared classes have been created yet."}`);}catch(error){setNotice(error instanceof Error?error.message:"Weekly schedule unavailable.");}},[accessToken,homeroomCode,buildSavedWeek]);
 useEffect(()=>{void load();},[load]);
 function changeHomeroom(code:string){setHomeroomCode(code);setWeek(buildSavedWeek(code));setNotice(`Editing the full Monday–Friday schedule for Homeroom ${code}. Shared classes are available in every period menu.`);}
 function changeCell(day:number,periodIndex:number,value:string){setWeek(current=>({...current,[day]:current[day].map((item,index)=>index===periodIndex?value:item)}));}
 function sectionDetails(assignment:string){if(!isClass(assignment))return "";const section=sectionFor(assignment);if(!section)return "Class details unavailable";const names=(instructorIdsBySection.get(section.id)??[]).map(id=>facultyNames.get(id)).filter(Boolean);return [names.length?names.join(", "):"Unstaffed",section.room?`Room ${section.room}`:"No room required"].join(" • ");}
 async function saveWeek(){if(!homeroomCode||saving)return;if(selectedConflictCount){setNotice(`Resolve ${selectedConflictCount} weekly conflict${selectedConflictCount===1?"":"s"} before publishing this homeroom schedule.`);return;}setSaving(true);setNotice(`Saving the full week for Homeroom ${homeroomCode}…`);try{for(const day of DAYS){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_set_homeroom_daily_schedule`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_homeroom_code:homeroomCode,requested_weekday:day.id,requested_periods:week[day.id].map((assignment,index)=>({period:index+1,assignment}))})});if(!response.ok){let message=`${day.label} could not be saved.`;try{const body=await response.json() as {message?:string};if(body.message)message=body.message;}catch{}throw new Error(message);}}await load(homeroomCode);setNotice(`Homeroom ${homeroomCode}'s Monday–Friday schedule is published.`);}catch(error){setNotice(error instanceof Error?error.message:"The weekly schedule could not be saved.");}finally{setSaving(false);}}

 return <section className={styles.panel} aria-labelledby="weekly-scheduler-title">
  <div className={styles.heading}><div><p className="eyebrow">OWNER • CLASSROOM CONTROL CENTER</p><h3 id="weekly-scheduler-title">Weekly Homeroom Scheduler</h3><p>Assign the schoolwide shared class catalog to each homeroom’s week. Every assignment is checked against the other homerooms for teacher conflicts and assigned-room conflicts before publishing. Classes without a room are allowed.</p></div><span className={styles.badge}>WEEKLY PLANNER</span></div>
  <div className={styles.notice} aria-live="polite">{notice}</div>
  <div className={styles.topControls}><label>Homeroom<select value={homeroomCode} onChange={e=>changeHomeroom(e.target.value)}>{homerooms.map(room=><option key={room.id} value={room.code}>Homeroom {room.code} • {room.school_year}</option>)}</select></label><div className={selectedConflictCount?styles.conflictSummary:styles.clearSummary}><strong>{selectedConflictCount?`${selectedConflictCount} scheduling conflict${selectedConflictCount===1?"":"s"}`:"Week clear"}</strong><span>{selectedConflictCount?"Resolve highlighted cells before publishing.":`${courses.length} shared class${courses.length===1?"":"es"} available • no collisions detected.`}</span></div></div>
  <section className={styles.weekSection}><div className={styles.sectionTitle}><div><strong>Homeroom {homeroomCode} • full week</strong><span>Each dropdown uses the same shared class catalog. The schedule is not published until you press Save Full Week.</span></div></div><div className={styles.tableWrap}><table className={styles.weekTable}><thead><tr><th>Period</th>{DAYS.map(day=><th key={day.id}>{day.label}</th>)}</tr></thead><tbody>{PERIODS.map((period,index)=><tr key={period.number}><th><strong>{period.label}</strong><span>{period.time}</span></th>{DAYS.map(day=>{const assignment=week[day.id]?.[index]??"__OPEN__",issues=conflicts.get(`${homeroomCode}:${day.id}:${period.number}`)??[];return <td key={day.id} className={issues.length?styles.conflictCell:""}><select aria-label={`${day.label} ${period.label}`} value={assignment} onChange={e=>changeCell(day.id,index,e.target.value)}><option value="__OPEN__">Open period</option><option value="__STUDY__">Study Period</option><option value="__EXTRACURRICULAR__">Extracurriculars</option>{courses.map(course=><option key={course.code} value={course.code}>{course.code} • {course.title}</option>)}</select>{assignment!=="__OPEN__"&&<small>{sectionDetails(assignment)}</small>}{issues.map((issue,i)=><em key={i}>⚠ {issue}</em>)}</td>})}</tr>)}</tbody></table></div></section>
  <section className={styles.masterSection}><div className={styles.masterHeading}><div><strong>All-homeroom conflict check</strong><span>Select a day to compare every homeroom period-by-period while you edit the week above.</span></div><div className={styles.dayTabs}>{DAYS.map(day=><button type="button" key={day.id} className={activeDay===day.id?styles.activeDay:""} onClick={()=>setActiveDay(day.id)}>{day.label.slice(0,3)}</button>)}</div></div><div className={styles.tableWrap}><table className={styles.masterTable}><thead><tr><th>Period</th>{homerooms.map(room=><th key={room.id} className={room.code===homeroomCode?styles.editingColumn:""}>Homeroom {room.code}</th>)}</tr></thead><tbody>{PERIODS.map(period=><tr key={period.number}><th><strong>{period.label}</strong><span>{period.time}</span></th>{homerooms.map(room=>{const assignment=schoolWeek.get(room.code)?.[activeDay]?.[period.number-1]??"__OPEN__",issues=conflicts.get(`${room.code}:${activeDay}:${period.number}`)??[];return <td key={room.id} className={issues.length?styles.conflictCell:""}><strong>{shortLabel(assignment,courseMap)}</strong>{isClass(assignment)&&<small>{sectionDetails(assignment)}</small>}{issues.map((issue,i)=><em key={i}>⚠ {issue}</em>)}</td>})}</tr>)}</tbody></table></div><div className={styles.dayStatus}>{activeDayConflicts?`${activeDayConflicts} conflict${activeDayConflicts===1?"":"s"} affect the homeroom being edited on ${DAYS.find(day=>day.id===activeDay)?.label}.`:`${DAYS.find(day=>day.id===activeDay)?.label} is clear for the homeroom being edited.`}</div></section>
  <div className={styles.actions}><button type="button" onClick={saveWeek} disabled={saving||!homeroomCode||selectedConflictCount>0}>{saving?"Saving full week…":"Save Full Week"}</button></div>
  <div className={styles.help}><strong>Shared-class model:</strong> Classes are created once in Courses &amp; Sections and can then be assigned to Homeroom A, B, C, or any future homeroom from this scheduler. A class may have a room assigned, or no room at all when one is not needed.</div>
 </section>;
}