"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./OwnerOperationsCommandPanel.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type Watch={id:string;item_type:string;title:string;note:string;reference_id:string|null;status:string;priority:string;created_at:string;updated_at:string};
type Health={id:string;check_key:string;check_type:string;summary:string;status:string;details:Record<string,unknown>;checked_at:string;resolved_at:string|null};
type Usage={page_key:string;portal_role:string;event_type:string;occurred_at:string};
type Audit={id:number;actor_user_id:string|null;action:string;target_type:string|null;target_id:string|null;details:Record<string,unknown>;created_at:string};
type Tab="commands"|"watchlist"|"health"|"analytics"|"changes";
function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}
function pretty(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function short(v:string|null){return v?v.slice(0,8):"System"}
export default function OwnerOperationsCommandPanel({accessToken}:Props){
 const [renderNow]=useState(()=>Date.now()),[tab,setTab]=useState<Tab>("commands"),[watch,setWatch]=useState<Watch[]>([]),[health,setHealth]=useState<Health[]>([]),[usage,setUsage]=useState<Usage[]>([]),[audit,setAudit]=useState<Audit[]>([]),[message,setMessage]=useState("Loading Owner operations…"),[saving,setSaving]=useState(false);
 const [draft,setDraft]=useState({item_type:"feature",title:"",note:"",reference_id:"",priority:"normal"});
 const load=useCallback(async()=>{try{const since=new Date(Date.now()-7*864e5).toISOString();const [w,he,u,a]=await Promise.all([
  fetch(`${U}/rest/v1/owner_watchlist?select=id,item_type,title,note,reference_id,status,priority,created_at,updated_at&order=updated_at.desc`,{headers:h(accessToken)}),
  fetch(`${U}/rest/v1/portal_health_checks?select=id,check_key,check_type,summary,status,details,checked_at,resolved_at&order=checked_at.desc&limit=40`,{headers:h(accessToken)}),
  fetch(`${U}/rest/v1/portal_usage_events?select=page_key,portal_role,event_type,occurred_at&occurred_at=gte.${encodeURIComponent(since)}&order=occurred_at.desc&limit=1000`,{headers:h(accessToken)}),
  fetch(`${U}/rest/v1/rpc/owner_governance_audit_feed`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({row_limit:150})})
 ]);if(!w.ok||!he.ok||!u.ok||!a.ok)throw new Error("Owner operations data could not be loaded.");setWatch(await w.json());setHealth(await he.json());setUsage(await u.json());setAudit(await a.json());setMessage("Owner operations are current.");}catch(e){setMessage(e instanceof Error?e.message:"Owner operations unavailable.");}},[accessToken]);
 useEffect(()=>{void load()},[load]);
 const analytics=useMemo(()=>{const pages=new Map<string,number>(),roles=new Map<string,number>();for(const row of usage){pages.set(row.page_key,(pages.get(row.page_key)??0)+1);roles.set(row.portal_role,(roles.get(row.portal_role)??0)+1);}return {top:[...pages].sort((a,b)=>b[1]-a[1]).slice(0,8),roles:[...roles].sort((a,b)=>b[1]-a[1]),total:usage.length};},[usage]);
 const today=useMemo(()=>{const cutoff=renderNow-864e5;return audit.filter(x=>new Date(x.created_at).getTime()>=cutoff)},[audit,renderNow]);
 function command(view:string,tool:string){window.dispatchEvent(new CustomEvent("hanami-admin-command",{detail:{view,tool}}));setMessage(`Opened ${pretty(tool)}.`)}
 async function addWatch(event:FormEvent){event.preventDefault();if(!draft.title.trim())return;setSaving(true);try{const r=await fetch(`${U}/rest/v1/owner_watchlist`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({...draft,title:draft.title.trim(),note:draft.note.trim(),reference_id:draft.reference_id.trim()||null,status:"watching"})});if(!r.ok)throw new Error("Watchlist item could not be saved.");setDraft({item_type:"feature",title:"",note:"",reference_id:"",priority:"normal"});await load();}catch(e){setMessage(e instanceof Error?e.message:"Watchlist item could not be saved.");}finally{setSaving(false)}}
 async function setWatchStatus(id:string,status:string){setSaving(true);try{const r=await fetch(`${U}/rest/v1/owner_watchlist?id=eq.${id}`,{method:"PATCH",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Watchlist status could not be changed.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Watchlist status could not be changed.");}finally{setSaving(false)}}
 async function runHealth(){setSaving(true);setMessage("Running Owner health snapshot…");const checks=[
  ["owner_directory","rpc","Owner portal directory",`${U}/rest/v1/rpc/owner_portal_directory`,"POST"],
  ["school_state","data","School state configuration",`${U}/rest/v1/school_state_config?select=id&limit=1`,"GET"],
  ["announcements","data","Announcements feed",`${U}/rest/v1/site_announcements?select=id&limit=1`,"GET"],
  ["school_schedule","data","School schedule",`${U}/rest/v1/school_schedule_blocks?select=id&limit=1`,"GET"]
 ] as const;try{for(const [key,type,summary,url,method] of checks){let ok=false;let note="";try{const r=await fetch(url,{method,headers:h(accessToken,method==="POST"?{"Content-Type":"application/json"}:{}),body:method==="POST"?"{}":undefined,cache:"no-store"});ok=r.ok;note=`HTTP ${r.status}`;}catch(e){note=e instanceof Error?e.message:"Request failed"}await fetch(`${U}/rest/v1/portal_health_checks`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({check_key:key,check_type:type,summary,status:ok?"healthy":"error",details:{note}})});}await load();setMessage("Health snapshot completed.");}catch(e){setMessage(e instanceof Error?e.message:"Health snapshot could not finish.");}finally{setSaving(false)}}
 const tabs:[Tab,string][]=[["commands","Command Palette"],["watchlist","Watchlist"],["health","Portal Health"],["analytics","Activity Analytics"],["changes","Today’s Changes"]];
 return <section className={styles.panel} aria-labelledby="owner-ops-title"><header><div><p className="eyebrow">OWNER SCHOOL OPERATIONS</p><h3 id="owner-ops-title">Command & health center</h3></div><span>{message}</span></header><nav>{tabs.map(([id,label])=><button key={id} type="button" className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="commands"&&<div className={styles.commands}><button onClick={()=>command("people","directory")}><b>Open a user</b><span>People → Directory</span></button><button onClick={()=>command("content","events")}><b>Build an event</b><span>Content → Events</span></button><button onClick={()=>command("home","announcements")}><b>Publish announcement</b><span>Dashboard → Announcements</span></button><button onClick={()=>command("home","status")}><b>Change school state</b><span>Dashboard → School Status</span></button><button onClick={()=>command("systems","roleplay")}><b>Open RP controls</b><span>Admin → Roleplay Systems</span></button><button onClick={()=>command("content","drafts")}><b>Open draft workspace</b><span>Content → Draft Workspace</span></button><a href="../student/"><b>Preview Student Portal</b><span>Owner stays signed in</span></a><a href="../faculty/"><b>Preview Faculty Portal</b><span>Owner stays signed in</span></a></div>}
 {tab==="watchlist"&&<div className={styles.split}><form onSubmit={addWatch}><h4>Pin something important</h4><select value={draft.item_type} onChange={e=>setDraft({...draft,item_type:e.target.value})}><option value="bug">Bug</option><option value="feature">Feature</option><option value="event">Event</option><option value="election">Election</option><option value="moderation">Moderation case</option><option value="roleplay">Roleplay arc</option></select><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Watchlist title" required/><textarea value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="Why are you watching this?"/><input value={draft.reference_id} onChange={e=>setDraft({...draft,reference_id:e.target.value})} placeholder="Optional reference ID"/><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select><button disabled={saving}>Add to watchlist</button></form><div className={styles.stack}>{watch.map(item=><article key={item.id}><div><small>{pretty(item.item_type)} · {pretty(item.priority)} · {pretty(item.status)}</small><h4>{item.title}</h4><p>{item.note||"No note."}</p>{item.reference_id&&<code>{item.reference_id}</code>}</div><div className={styles.actions}><button disabled={saving} onClick={()=>setWatchStatus(item.id,"watching")}>Watching</button><button disabled={saving} onClick={()=>setWatchStatus(item.id,"resolved")}>Resolved</button><button disabled={saving} onClick={()=>setWatchStatus(item.id,"archived")}>Archive</button></div></article>)}{!watch.length&&<p>No Owner watchlist items yet.</p>}</div></div>}
 {tab==="health"&&<div><div className={styles.toolbar}><button disabled={saving} onClick={runHealth}>Run health snapshot</button><span>{health.filter(x=>x.status!=="healthy").length} current/recent non-healthy checks</span></div><div className={styles.stack}>{health.map(item=><article key={item.id}><div><small>{pretty(item.check_type)} · {new Date(item.checked_at).toLocaleString()}</small><h4>{item.summary}</h4><p>{item.check_key}</p></div><b className={item.status==="healthy"?styles.good:styles.bad}>{pretty(item.status)}</b></article>)}{!health.length&&<p>No portal health snapshots recorded yet.</p>}</div></div>}
 {tab==="analytics"&&<div className={styles.analytics}><article><small>LAST 7 DAYS</small><strong>{analytics.total}</strong><span>Recorded portal interactions</span></article>{analytics.roles.map(([role,count])=><article key={role}><small>{pretty(role)}</small><strong>{count}</strong><span>Interactions</span></article>)}<section><h4>Most visited portal areas</h4>{analytics.top.map(([page,count])=><div key={page}><span>{pretty(page)}</span><b>{count}</b></div>)}{!analytics.top.length&&<p>Usage data will appear as members navigate the new portal journey.</p>}</section></div>}
 {tab==="changes"&&<div className={styles.stack}>{today.map(item=><article key={item.id}><div><small>{new Date(item.created_at).toLocaleString()} · actor {short(item.actor_user_id)}</small><h4>{pretty(item.action)}</h4><p>{item.target_type?`${pretty(item.target_type)}${item.target_id?` · ${item.target_id}`:""}`:"System change"}</p></div></article>)}{!today.length&&<p>No audit entries have been recorded in the last 24 hours.</p>}</div>}
 </section>;
}
