"use client";

const groups=[
 {title:"Student experience",items:["Today at Hanami","Attendance & grade trends","Assignment planner","Club dashboard","Achievements","Student ID","Saved resources","Guestbook","Profile widgets","Status & friend activity","Roleplay journal","School map","Lost & found"]},
 {title:"Faculty experience",items:["Today's classes","Quick attendance","Grading queue","Missing-work alerts","Class analytics","Homeroom advisor","Student notes","Commendations","Lesson planner","Assignment templates","Rubrics","Bulk grading","Office hours","Club advising","Sub plans"]},
 {title:"Administration",items:["People directories","Homerooms","Courses & sections","Bulk enrollment","Attendance admin","Academic records","Report cards","Exam operations","Calendar & announcements","Club oversight","Moderation","School-year rollover","Exports","Audit log"]},
 {title:"Owner controls",items:["Full portal viewer","Owner Preview Mode","Edit Portal separation","Character management","Visibility override","Daily homeroom schedules","Schedule templates","Bell schedule","Academic-year settings","Global design","Feature flags","Permissions","Broadcasts","Maintenance","Activity & audit logs","System health","Website editor","Role tester","Backups"]}
];
export default function OwnerPortalExpansionPanel(){return <section style={{border:"1px solid #9babc0",background:"#fff",padding:16,borderRadius:0}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"baseline",flexWrap:"wrap"}}><div><p className="eyebrow">OWNER • PORTAL EXPANSION</p><h3 style={{margin:"3px 0",font:"400 25px Georgia,serif",color:"#17375f"}}>School experience control map</h3></div><a href="../../features/" style={{padding:"8px 10px",border:"1px solid #17375f",textDecoration:"none",borderRadius:0}}>Open full Feature Center →</a></div><p style={{marginTop:6}}>The Owner portal now tracks the full Student, Faculty, Administration, and Owner experience in one place so features are not lost across separate portal sections.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:0,borderTop:"1px solid #d3d9e1",borderLeft:"1px solid #d3d9e1"}}>{groups.map(group=><article key={group.title} style={{padding:12,borderRight:"1px solid #d3d9e1",borderBottom:"1px solid #d3d9e1"}}><strong style={{color:"#17375f"}}>{group.title}</strong><ul style={{margin:"8px 0 0",paddingLeft:18}}>{group.items.map(item=><li key={item} style={{marginBottom:4}}>{item}</li>)}</ul></article>)}</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><a href="../../changelog/" style={{padding:"8px 10px",border:"1px solid #17375f",textDecoration:"none",borderRadius:0}}>Website changelog</a><a href="../../ideas/" style={{padding:"8px 10px",border:"1px solid #17375f",textDecoration:"none",borderRadius:0}}>Feature ideas</a><a href="./portal-viewer/" style={{padding:"8px 10px",border:"1px solid #17375f",textDecoration:"none",borderRadius:0}}>Portal viewer</a></div></section>}
