"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./OwnerBugDetectorPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Bug={id:string;source:string;severity:"low"|"medium"|"high"|"critical";title:string;details:string;affected_area:string;route:string|null;status:"detected"|"investigating"|"fixed"|"ignored";owner_notes:string;occurrences:number;first_seen_at:string;last_seen_at:string;resolved_at:string|null;metadata:Record<string,unknown>};
type WorkflowRun={id:number;name:string;head_sha:string;status:string;conclusion:string|null;html_url:string;created_at:string;updated_at:string};
export default function OwnerBugDetectorPanel({accessToken}:{accessToken:string}){
 const [bugs,setBugs]=useState<Bug[]>([]);const [workflow,setWorkflow]=useState<WorkflowRun|null>(null);const [status,setStatus]=useState("Scanning Hanami systems…");const [notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_capture_bug_support_tickets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_bug_detector_feed`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)throw new Error("Owner Bug Detector could not be loaded.");const rows=await response.json() as Bug[];setBugs(rows);setNotes(Object.fromEntries(rows.map(row=>[row.id,row.owner_notes])));setStatus(`${rows.filter(row=>row.status==="detected"||row.status==="investigating").length} active detector finding${rows.filter(row=>row.status==="detected"||row.status==="investigating").length===1?"":"s"}.`);}catch(error){setStatus(error instanceof Error?error.message:"Owner Bug Detector could not be loaded.");}
  try{const gh=await fetch("https://api.github.com/repos/hanamihalladmin/Hanami-High/actions/runs?per_page=1",{headers:{Accept:"application/vnd.github+json"}});if(gh.ok){const data=await gh.json() as {workflow_runs?:WorkflowRun[]};setWorkflow(data.workflow_runs?.[0]??null);}else setWorkflow(null);}catch{setWorkflow(null);}},[accessToken]);
 useEffect(()=>{queueMicrotask(()=>void load());},[load]);
 async function updateBug(id:string,nextStatus:Bug["status"]){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_update_bug_report`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_bug_id:id,new_status:nextStatus,new_notes:notes[id]??""})});if(response.ok){setStatus("Bug record updated.");await load();}else setStatus("Bug record could not be updated.");}
 const active=useMemo(()=>bugs.filter(b=>b.status==="detected"||b.status==="investigating"),[bugs]);const critical=active.filter(b=>b.severity==="critical").length;const high=active.filter(b=>b.severity==="high").length;
 const fmt=(v:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">OWNER ONLY • BUG DETECTOR</p><h3>Hanami QA Monitor</h3><p>Runtime errors, bug-tagged Support Tickets, deployment status, and QA findings stay visible only to the verified Owner.</p></div><button type="button" onClick={()=>void load()}>Run detector scan</button></div>
  <div className={styles.summary}><div><strong>{active.length}</strong><span>Active findings</span></div><div><strong>{critical}</strong><span>Critical</span></div><div><strong>{high}</strong><span>High severity</span></div><div><strong>{bugs.reduce((sum,b)=>sum+b.occurrences,0)}</strong><span>Total occurrences</span></div></div>
  <div className={styles.deployment}><div><strong>GitHub Pages / Actions</strong>{workflow?<><span>{workflow.status.toUpperCase()} • {(workflow.conclusion??"PENDING").toUpperCase()}</span><small>{workflow.name} • {workflow.head_sha.slice(0,8)} • {fmt(workflow.updated_at)}</small></>:<><span>STATUS UNAVAILABLE</span><small>GitHub API could not be reached from this browser session.</small></>}</div>{workflow&&<a href={workflow.html_url} target="_blank" rel="noreferrer">Open latest Actions run</a>}</div>
  <p className={styles.status} aria-live="polite">{status}</p>
  <div className={styles.list}>{bugs.length?bugs.map(bug=><article key={bug.id} data-severity={bug.severity}><div className={styles.meta}><span className={styles.badge}>{bug.severity.toUpperCase()}</span><span>{bug.source.replaceAll("_"," ").toUpperCase()}</span><span>{bug.affected_area}</span><span>{bug.occurrences} occurrence{bug.occurrences===1?"":"s"}</span></div><h4>{bug.title}</h4><p>{bug.details||"No additional details were captured."}</p><small>First seen {fmt(bug.first_seen_at)} • Last seen {fmt(bug.last_seen_at)}{bug.route?` • ${bug.route}`:""}</small><label><span>OWNER NOTES</span><textarea value={notes[bug.id]??""} onChange={e=>setNotes(current=>({...current,[bug.id]:e.target.value}))} maxLength={6000}/></label><div className={styles.actions}><button type="button" disabled={bug.status==="detected"} onClick={()=>updateBug(bug.id,"detected")}>Detected</button><button type="button" disabled={bug.status==="investigating"} onClick={()=>updateBug(bug.id,"investigating")}>Investigating</button><button type="button" disabled={bug.status==="fixed"} onClick={()=>updateBug(bug.id,"fixed")}>Fixed</button><button type="button" disabled={bug.status==="ignored"} onClick={()=>updateBug(bug.id,"ignored")}>Ignore</button></div></article>):<div className={styles.empty}><strong>No detector findings yet.</strong><p>Runtime errors and bug-tagged Support Tickets will appear here automatically.</p></div>}</div>
 </section>;
}
