"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./OwnerHomeroomScheduleEditor.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const DAYS=["","Monday","Tuesday","Wednesday","Thursday","Friday"];
const PERIODS=[
 {number:1,label:"Period 1",time:"8:50 AM–9:40 AM"},
 {number:2,label:"Period 2",time:"9:50 AM–10:40 AM"},
 {number:3,label:"Period 3",time:"10:50 AM–11:40 AM"},
 {number:4,label:"Period 4",time:"11:50 AM–12:40 PM"},
 {number:5,label:"Period 5",time:"1:25 PM–2:15 PM"},
 {number:6,label:"Period 6",time:"2:25 PM–3:15 PM"},
] as const;
type Homeroom={id:string;code:string;school_year:string;is_active:boolean};
type Course={code:string;title:string};
type Meeting={weekday:number;label:string|null;starts_at:string;ends_at:string};
type Section={id:string;section_code:string;academic_courses:Course|null;section_meetings:Meeting[]};
type Block={id:string;block_type:string;weekday:number;starts_at:string;homeroom_label:string|null;notes:string|null};
type Props={accessToken:string};
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
function normalizedHomeroom(value:string|null){const clean=(value??"").trim().toUpperCase();const match=clean.match(/([A-Z])$/);return match?.[1]??clean;}
function periodFromLabel(label:string|null){const match=(label??"").match(/period\s*([1-6])/i);return match?Number(match[1]):0;}
function periodFromStart(value:string){const key=value.slice(0,5);return ({"08:50":1,"09:50":2,"10:50":3,"11:50":4,"13:25":5,"14:25":6} as Record<string,number>)[key]??0;}

export default function OwnerHomeroomScheduleEditor({accessToken}:Props){
 const [homerooms,setHomerooms]=useState<Homeroom[]>([]),[homeroomCode,setHomeroomCode]=useState("");const [weekday,setWeekday]=useState(1);const [sections,setSections]=useState<Section[]>([]);const [assignments,setAssignments]=useState<string[]>(Array(6).fill("__OPEN__"));const [notice,setNotice]=useState("Loading homeroom schedules…"),[saving,setSaving]=useState(false);
 const courses=useMemo(()=>sections.map(section=>section.academic_courses).filter((course):course is Course=>Boolean(course)).sort((a,b)=>a.title.localeCompare(b.title)),[sections]);
 const load=useCallback(async()=>{try{const homeroomResponse=await fetch(`${SUPABASE_URL}/rest/v1/homerooms?select=id,code,school_year,is_active&is_active=eq.true&order=code.asc`,{headers:headers(accessToken)});if(!homeroomResponse.ok)throw new Error("Homerooms could not be loaded.");const hs=await homeroomResponse.json() as Homeroom[];setHomerooms(hs);const code=homeroomCode||hs[0]?.code||"";if(!code){setNotice("No active homerooms are available.");return;}if(!homeroomCode){setHomeroomCode(code);return;}const [sectionResponse,blockResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=${encodeURIComponent("id,section_code,academic_courses(code,title),section_meetings(weekday,label,starts_at,ends_at)")}&section_code=eq.${encodeURIComponent(code)}`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,block_type,weekday,starts_at,homeroom_label,notes&weekday=eq.${weekday}&notes=eq.owner_homeroom_daily_schedule`,{headers:headers(accessToken)})]);if(!sectionResponse.ok||!blockResponse.ok)throw new Error("The selected homeroom schedule could not be loaded.");const nextSections=await sectionResponse.json() as Section[];const blocks=await blockResponse.json() as Block[];setSections(nextSections);const next=Array(6).fill("__OPEN__") as string[];nextSections.forEach(section=>(section.section_meetings??[]).filter(meeting=>meeting.weekday===weekday).forEach(meeting=>{const period=periodFromLabel(meeting.label);if(period&&section.academic_courses)next[period-1]=section.academic_courses.code;}));blocks.filter(block=>normalizedHomeroom(block.homeroom_label)===code.toUpperCase()).forEach(block=>{const period=periodFromStart(block.starts_at);if(!period)return;if(block.block_type==="study")next[period-1]="__STUDY__";if(block.block_type==="extracurricular")next[period-1]="__EXTRACURRICULAR__";});setAssignments(next);setNotice(`Editing Homeroom ${code} • ${DAYS[weekday]}. Changes apply to the whole homeroom.`);}catch(error){setNotice(error instanceof Error?error.message:"Schedule unavailable.");}},[accessToken,homeroomCode,weekday]);
 useEffect(()=>{void load();},[load]);
 function changeAssignment(index:number,value:string){setAssignments(current=>current.map((item,i)=>i===index?value:item));}
 async function save(){if(!homeroomCode||saving)return;setSaving(true);setNotice(`Saving Homeroom ${homeroomCode} • ${DAYS[weekday]}…`);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_set_homeroom_daily_schedule`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_homeroom_code:homeroomCode,requested_weekday:weekday,requested_periods:assignments.map((assignment,index)=>({period:index+1,assignment}))})});if(!response.ok)throw new Error("The daily schedule could not be saved.");const count=Number(await response.json());await load();setNotice(`Saved Homeroom ${homeroomCode} • ${DAYS[weekday]}. ${count} scheduled period${count===1?"":"s"} updated for every student in that homeroom.`);}catch(error){setNotice(error instanceof Error?error.message:"The daily schedule could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="owner-homeroom-schedule-title"><div className={styles.heading}><div><p className="eyebrow">OWNER • HOMEROOM SCHEDULER</p><h3 id="owner-homeroom-schedule-title">Daily Homeroom Schedules</h3><p>Edit one homeroom's entire day at once. Students inherit the schedule automatically from their homeroom, so you do not need to assign the same classes student-by-student.</p></div><span className={styles.badge}>OWNER ONLY</span></div><div className={styles.notice} aria-live="polite">{notice}</div><div className={styles.controls}><label>Homeroom<select value={homeroomCode} onChange={e=>setHomeroomCode(e.target.value)}>{homerooms.map(room=><option key={room.id} value={room.code}>Homeroom {room.code} • {room.school_year}</option>)}</select></label><label>Day<select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.slice(1).map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label></div><div className={styles.periods}>{PERIODS.map((period,index)=><article className={styles.period} key={period.number}><div className={styles.periodMeta}><strong>{period.label}</strong><span>{period.time}</span></div><label>Assignment<select value={assignments[index]} onChange={e=>changeAssignment(index,e.target.value)}><option value="__OPEN__">Open period</option><option value="__STUDY__">Study Period</option><option value="__EXTRACURRICULAR__">Extracurriculars Period</option>{courses.map(course=><option key={course.code} value={course.code}>{course.title} • {course.code}</option>)}</select></label></article>)}</div><div className={styles.actions}><button type="button" disabled={saving||!homeroomCode} onClick={()=>void save()}>{saving?"Saving…":"Save Daily Schedule"}</button></div><div className={styles.help}><strong>Automatic behavior:</strong> changing a class here edits the matching A/B/C class section meeting itself. Because homeroom placement already auto-enrolls students into matching sections, every student in the homeroom sees the new schedule without individual class assignment.</div></section>;
}
