"use client";

import {useEffect,useState,type ReactNode} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string;providerToken?:string};

function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer",providerToken:typeof value.providerToken==="string"?value.providerToken:undefined};}catch{return null;}}
function sessionFromHash():PortalSession|null{if(!window.location.hash)return null;const params=new URLSearchParams(window.location.hash.slice(1));const accessToken=params.get("access_token"),refreshToken=params.get("refresh_token");if(!accessToken||!refreshToken)return null;const expiresIn=Number(params.get("expires_in")??3600);return {accessToken,refreshToken,expiresAt:Date.now()+Math.max(60,expiresIn)*1000,tokenType:params.get("token_type")??"bearer",providerToken:params.get("provider_token")??undefined};}
function oauthError(){const hash=new URLSearchParams(window.location.hash.slice(1));const query=new URLSearchParams(window.location.search);return hash.get("error_description")??query.get("error_description")??hash.get("error")??query.get("error");}
function discordUrl(){const redirect=new URL(window.location.href);redirect.search="";redirect.hash="";const url=new URL(`${SUPABASE_URL}/auth/v1/authorize`);url.searchParams.set("provider","discord");url.searchParams.set("redirect_to",redirect.toString());url.searchParams.set("scopes","identify guilds guilds.members.read");return url.toString();}
async function refreshSession(session:PortalSession):Promise<PortalSession|null>{const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return null;const data=await response.json() as {access_token?:string;refresh_token?:string;expires_in?:number;token_type?:string};if(!data.access_token||!data.refresh_token)return null;return {accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+(data.expires_in??3600)*1000,tokenType:data.token_type??"bearer",providerToken:session.providerToken};}

export default function OwnerEntryGate({children}:{children:ReactNode}){
 const [ready,setReady]=useState(false),[message,setMessage]=useState("Checking Owner session…");
 useEffect(()=>{let cancelled=false;void(async()=>{try{const error=oauthError();if(error){localStorage.removeItem(SESSION_KEY);history.replaceState({},document.title,window.location.pathname);if(!cancelled){setMessage(`Discord sign-in was not completed: ${error}`);setReady(false);}return;}const returned=sessionFromHash();if(returned){localStorage.setItem(SESSION_KEY,JSON.stringify(returned));history.replaceState({},document.title,window.location.pathname);if(!cancelled)setReady(true);return;}let stored=readSession();if(stored&&stored.expiresAt-Date.now()<120000){stored=await refreshSession(stored);if(stored)localStorage.setItem(SESSION_KEY,JSON.stringify(stored));else localStorage.removeItem(SESSION_KEY);}if(!cancelled){setReady(Boolean(stored));setMessage(stored?"Owner session restored.":"Sign in with Discord to continue to the Owner portal.");}}catch{if(!cancelled){setReady(false);setMessage("The Owner sign-in session could not be restored.");}}})();return()=>{cancelled=true;};},[]);
 if(ready)return <>{children}</>;
 return <section className="portal-account-card"><p className="eyebrow">OWNER PORTAL</p><h2>Owner sign-in</h2><p>{message}</p><p className="portal-account-note">You can sign in here directly. You do not need to visit the normal Student/Faculty gateway first.</p><button className="discord-button" type="button" onClick={()=>window.location.assign(discordUrl())}><span>◉</span> Continue with Discord</button><a className="secondary-action" href="../">Return to Portal Gateway</a></section>;
}
