"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import PrivilegedPortalLogin from "../PrivilegedPortalLogin";
import AdminWorkspace from "../admin/AdminWorkspace";
import OwnerWebsiteAccess from "../../components/OwnerWebsiteAccess";
import OwnerBugDetectorPanel from "./OwnerBugDetectorPanel";
import OwnerDiscordRoleSyncPanel from "./OwnerDiscordRoleSyncPanel";
import OwnerOperationsPanel from "./OwnerOperationsPanel";
import OwnerSystemHealthAnalyticsPanel from "./OwnerSystemHealthAnalyticsPanel";
import styles from "./OwnerPortalClient.module.css";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";const SESSION_KEY="hanami.portal.session.v1";const OWNER_ADMIN_ACCESS={site_admin:true,content_editor:true,moderator:true} as const;type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
export default function OwnerPortalClient(){
 const [session,setSession]=useState<PortalSession|null>(null);const [userId,setUserId]=useState("");const [state,setState]=useState<"loading"|"signin"|"ready"|"blocked">("loading");const [message,setMessage]=useState("Checking Owner identity…");const [adminHandle,setAdminHandle]=useState("");const [adminPassword,setAdminPassword]=useState("");const [adminDiscordId,setAdminDiscordId]=useState("");const [saving,setSaving]=useState(false);
 const initialize=useCallback(async()=>{const stored=readSession();if(!stored){setState("blocked");setMessage("Sign in through the Hanami Portal Gateway first.");return;}setSession(stored);const [ownerResponse,privilegedResponse,userResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(stored.accessToken,{"Content-Type":"application/json"}),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/rpc/has_privileged_portal_session`,{method:"POST",headers:headers(stored.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:"owner"})}),fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(stored.accessToken)})]);if(!ownerResponse.ok||!privilegedResponse.ok||!userResponse.ok){setState("blocked");setMessage("Owner access could not be verified.");return;}if(!Boolean(await ownerResponse.json())){setState("blocked");setMessage("This Discord account is not the configured Hanami Owner account.");return;}const user=await userResponse.json() as {id?:string};if(!user.id){setState("blocked");setMessage("Owner account ID could not be loaded.");return;}setUserId(user.id);if(!Boolean(await privilegedResponse.json())){setState("signin");setMessage("Owner identity confirmed. Enter the separate Owner credentials.");return;}setState("ready");setMessage("Owner identity and privileged sign-in verified.");},[]);useEffect(()=>{queueMicrotask(()=>void initialize());},[initialize]);
 async function createAdmin(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!session||saving)return;const cleanTarget=adminDiscordId.trim();setSaving(true);setMessage("Creating administrator credential…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_create_admin_credential`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_handle:adminHandle.trim().toLowerCase(),requested_password:adminPassword,target_discord_user_id:cleanTarget||null})});if(!response.ok)throw new Error("Administrator credential could not be created. Use a unique handle and a 12+ character password.");setAdminHandle("");setAdminPassword("");setAdminDiscordId("");setMessage("Administrator credential created.");}catch(error){setMessage(error instanceof Error?error.message:"Administrator credential could not be created.");}finally{setSaving(false);}}
 async function lockOwner(){if(session)await fetch(`${SUPABASE_URL}/rest/v1/rpc/end_privileged_portal_session`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:"owner"})});setState("signin");setMessage("Owner portal locked. Normal Hanami sign-in remains active.");}
 function logout(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem("hanami.portal.character.v1");window.location.assign("../");}
 if(state==="signin")return <PrivilegedPortalLogin portalKind="owner" allowOwnerBootstrap onUnlocked={initialize}/>;if(state!=="ready"||!session||!userId)return <section className="portal-account-card"><p className="eyebrow">OWNER PORTAL</p><h2>{state==="loading"?"Verifying Owner access…":"Owner access unavailable"}</h2><p>{message}</p><a className="secondary-action" href="../">Return to Portal Gateway</a></section>;
 const ownerOverview=<><div className={styles.grid}><section className={`${styles.panel} ${styles.ownerOnly}`}><div className={styles.label}>NETWORK OVERVIEW</div><h3>Owner authority</h3><p>Full Administration access plus Owner-only network controls and preview access to every portal.</p><div className={styles.statusList}><div className={styles.statusRow}><strong>Discord Owner identity</strong><span>VERIFIED</span></div><div className={styles.statusRow}><strong>Admin permissions</strong><span>FULL ACCESS</span></div><div className={styles.statusRow}><strong>Portal previews</strong><span>STUDENT • FACULTY • ADMIN</span></div><div className={styles.statusRow}><strong>System health</strong><span>OWNER ONLY</span></div></div></section><section className={styles.panel}><div className={styles.label}>ADMINISTRATOR PROVISIONING</div><h3>Create an Administrator sign-in</h3><form className={styles.form} onSubmit={createAdmin}><label><span>ADMIN HANDLE</span><input value={adminHandle} onChange={event=>setAdminHandle(event.target.value)} maxLength={64} required/></label><label><span>ADMIN DISCORD USER ID • OPTIONAL</span><input value={adminDiscordId} onChange={event=>setAdminDiscordId(event.target.value)} inputMode="numeric" placeholder="Leave blank for first-login claim"/></label><label><span>ADMIN PASSWORD • 12+ CHARACTERS</span><input type="password" value={adminPassword} onChange={event=>setAdminPassword(event.target.value)} minLength={12} required/></label><button type="submit" disabled={saving}>{saving?"Saving…":"Create Administrator Login"}</button></form></section></div><OwnerSystemHealthAnalyticsPanel accessToken={session.accessToken}/><OwnerOperationsPanel accessToken={session.accessToken}/><OwnerDiscordRoleSyncPanel accessToken={session.accessToken}/><section className={styles.panel}><div className={styles.label}>Bug Detector</div><OwnerBugDetectorPanel accessToken={session.accessToken}/></section><div className={styles.notice} aria-live="polite">{message}</div></>;
 const railActions=<><a href="../student/"><span aria-hidden="true">◫</span><b>Student Portal</b></a><a href="../faculty/"><span aria-hidden="true">▣</span><b>Faculty Portal</b></a><a href="../admin/"><span aria-hidden="true">◇</span><b>Admin Portal</b></a><OwnerWebsiteAccess/><a href="../"><span aria-hidden="true">↩</span><b>Gateway</b></a><button type="button" onClick={lockOwner}><span aria-hidden="true">▣</span><b>Lock</b></button><button type="button" onClick={logout}><span aria-hidden="true">⇥</span><b>Logout</b></button></>;
 return <AdminWorkspace accessToken={session.accessToken} userId={userId} access={OWNER_ADMIN_ACCESS} ownerMode ownerOverview={ownerOverview} actions={railActions}/>;
}
