"use client";

import {useEffect,useMemo,useState} from "react";
import {HANAMI_ROLEPLAY_YEAR,hanamiRoleplayDate} from "../components/roleplay-date";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type EventRow={id:string;title:string;description:string;location:string|null;starts_at:string;ends_at:string|null;all_day:boolean;category:string;featured:boolean;status:string};

export default function FullSchoolCalendarPage(){
 const [events,setEvents]=useState<EventRow[]>([]);const [status,setStatus]=useState("Loading the complete Hanami school calendar…");const currentDate=hanamiRoleplayDate();
 useEffect(()=>{let cancelled=false;async function load(){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_calendar_events?select=id,title,description,location,starts_at,ends_at,all_day,category,featured,status&status=eq.published&order=starts_at.asc`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(!response.ok)throw new Error("The complete school calendar could not be loaded.");const rows=await response.json() as EventRow[];if(!cancelled){setEvents(rows);setStatus(rows.length?`${rows.length} published school event${rows.length===1?"":"s"}.`:"No school events have been published yet.");}}catch(error){if(!cancelled)setStatus(error instanceof Error?error.message:"The complete school calendar could not be loaded.");}}load();return()=>{cancelled=true;};},[]);
 const grouped=useMemo(()=>{const groups=new Map<string,EventRow[]>();for(const event of events){const eventDate=new Date(event.starts_at);const month=new Intl.DateTimeFormat("en-US",{month:"long",timeZone:"Asia/Tokyo"}).format(eventDate);const key=`${month} ${HANAMI_ROLEPLAY_YEAR}`;groups.set(key,[...(groups.get(key)??[]),event]);}return [...groups.entries()];},[events]);
 return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • COMPLETE SCHOOL CALENDAR • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><img src="../hanami-high-portal-icon.png" alt="Hanami High" style={{width:82,height:82,objectFit:"contain"}}/><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">School Calendar • {HANAMI_ROLEPLAY_YEAR}</p></div></a><div className="school-clock"><strong data-hanami-roleplay-clock>{currentDate.toUpperCase()}</strong><span>HANAMI CITY • SCHOOL YEAR 2006–07</span></div></div><div className="nav-row"><nav><a href="../">School Home</a><a href="../academics/">Academics</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Calendar</a></nav><a className="portal-button" href="../portal/">Return to Portal</a></div></header><section className="info-section" style={{margin:"18px 24px"}}><div className="section-heading"><h2>COMPLETE SCHOOL CALENDAR</h2><span>LIVE CMS • {HANAMI_ROLEPLAY_YEAR} • JST</span></div><p className="content-note" aria-live="polite">{status}</p>{grouped.map(([month,items])=><section key={month} style={{marginTop:14}}><h3 style={{fontFamily:"Georgia,serif",color:"#17375f"}}>{month}</h3><div className="campus-events">{items.map(item=>{const start=new Date(item.starts_at);return <article key={item.id}><time><strong>{new Intl.DateTimeFormat("en-US",{day:"2-digit",timeZone:"Asia/Tokyo"}).format(start)}</strong>{new Intl.DateTimeFormat("en-US",{month:"short",timeZone:"Asia/Tokyo"}).format(start).toUpperCase()}</time><div><p className="eyebrow">{item.category.toUpperCase()}{item.featured?" • FEATURED":""}</p><h3>{item.title}</h3><p>{item.description}</p><small>{item.all_day?"ALL DAY":new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(start)}{item.location?` • ${item.location}`:""}</small></div></article>;})}</div></section>)}</section><footer><p>HANAMI HIGH SCHOOL • COMPLETE SCHOOL CALENDAR • {HANAMI_ROLEPLAY_YEAR}</p><nav><a href="../portal/">Portal</a><a href="../about/#contact">Contact</a><a href="../">School Home</a></nav></footer></main>;
}
