"use client";

import {useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type Room={room_id:string;room_number:string;building:string;floor_label:string;purpose:string;department:string|null;availability_status:string;current_class:string|null;current_section_code:string|null;class_starts:string|null;class_ends:string|null;notes:string};
function token(){try{return (JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string}).accessToken??"";}catch{return "";}}
export default function RoomDirectoryPage(){const [rooms,setRooms]=useState<Room[]>([]);const [status,setStatus]=useState("Sign in through the Portal Gateway to open the room directory.");useEffect(()=>{const accessToken=token();if(!accessToken)return;fetch(`${SUPABASE_URL}/rest/v1/rpc/room_directory_feed`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:"{}"}).then(async r=>{if(!r.ok)throw new Error();const rows=await r.json() as Room[];setRooms(rows);setStatus(`${rows.length} school room${rows.length===1?"":"s"} listed.`);}).catch(()=>setStatus("The room directory could not be loaded."));},[]);return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • ROOM DIRECTORY • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark"><span>花</span></div><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Campus Room Directory</p></div></a></div><div className="nav-row"><nav><a href="../">School Home</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Rooms</a></nav><a className="portal-button" href="../portal/">Portal Gateway</a></div></header><section className="info-section" style={{margin:"24px"}}><div className="section-heading"><h2>ROOM DIRECTORY</h2><span>LIVE AVAILABILITY • JST</span></div><p className="content-note">{status}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{rooms.map(r=><article key={r.room_id} style={{border:"1px solid #b8c3cf",padding:14,background:"#fffdf8"}}><p className="eyebrow">{r.building} • {r.floor_label}</p><h3 style={{fontFamily:"Georgia,serif",color:"#17375f",margin:"4px 0"}}>{r.room_number} — {r.purpose}</h3><p><strong>{r.availability_status.toUpperCase()}</strong>{r.department?` • ${r.department}`:""}</p>{r.current_class?<p>Current class: <strong>{r.current_class}</strong> ({r.current_section_code}) • {r.class_starts?.slice(0,5)}–{r.class_ends?.slice(0,5)}</p>:<p>No class is currently scheduled in this room.</p>}{r.notes&&<small>{r.notes}</small>}</article>)}</div></section><footer><p>HANAMI HIGH SCHOOL • ROOM DIRECTORY • 2006</p><nav><a href="../portal/">Portal</a><a href="../campus-life/">Campus Life</a><a href="../">School Home</a></nav></footer></main>;}
