"use client";

import {useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Entry={id:string;version:string;title:string;summary:string;added:string[];improved:string[];fixed:string[];known_issues:string[];published_at:string|null};
function dateLabel(value:string|null){return value?new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",year:"numeric",month:"long",day:"numeric"}).format(new Date(value)):"Unscheduled";}
function Group({title,items}:{title:string;items:string[]}){if(!items?.length)return null;return <section style={{borderTop:"1px solid #eadce3",paddingTop:10}}><strong style={{fontSize:10,letterSpacing:".08em",color:"#8f365b"}}>{title}</strong><ul style={{margin:"7px 0 0",paddingLeft:18}}>{items.map((item,index)=><li key={`${title}-${index}`} style={{marginBottom:5}}>{item}</li>)}</ul></section>}
export default function ChangelogPage(){const [entries,setEntries]=useState<Entry[]>([]);const [status,setStatus]=useState("Loading Hanami development history…");useEffect(()=>{void(async()=>{try{const response=await fetch(`${SUPABASE_URL}/rest/v1/changelog_entries?select=id,version,title,summary,added,improved,fixed,known_issues,published_at&status=eq.published&order=published_at.desc`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(!response.ok)throw new Error("The public changelog could not be loaded.");const rows=await response.json() as Entry[];setEntries(rows);setStatus(rows.length?`${rows.length} published release${rows.length===1?"":"s"}.`:"No public releases have been published yet.");}catch(error){setStatus(error instanceof Error?error.message:"The public changelog could not be loaded.");}})();},[]);return <main style={{maxWidth:980,margin:"34px auto",padding:"0 18px 60px"}}><header style={{marginBottom:18}}><p className="eyebrow">HANAMI HIGH DEVELOPMENT</p><h1 style={{margin:"4px 0",font:"400 36px Georgia,serif",color:"#17375f"}}>Website changelog</h1><p style={{maxWidth:720}}>A public record of major Hanami website additions, improvements, fixes, and known issues. Current website package version: <strong>v0.1.0</strong>.</p><small>{status}</small></header><div style={{display:"grid",gap:16}}>{entries.map(entry=><article key={entry.id} style={{border:"1px solid #cdbbc4",background:"#fffafc",padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"baseline"}}><div><p className="eyebrow">VERSION {entry.version}</p><h2 style={{margin:"3px 0",font:"400 24px Georgia,serif",color:"#17375f"}}>{entry.title}</h2></div><small>{dateLabel(entry.published_at)} • Tokyo</small></div><p>{entry.summary}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Group title="ADDED" items={entry.added}/><Group title="IMPROVED" items={entry.improved}/><Group title="FIXED" items={entry.fixed}/><Group title="KNOWN ISSUES" items={entry.known_issues}/></div></article>)}</div><p style={{marginTop:20}}><a href="../">Return to Hanami High</a></p></main>}
