const groups=[
 {title:"Social & roleplay",items:["Relationship and friend-group pages","Yearbook pages and senior superlatives","Public or friends-only character journals","Profile guestbooks and wall posts","Roleplay status messages","Anonymous question box with moderation","School confession board with moderation","Friend activity feed","NPC directory and relationship map","Rumor timeline and story archive"]},
 {title:"School life",items:["Locker customization","Classroom seating charts","Study-group finder","Cafeteria menu and lunch polls","Lost & found board","School newspaper","School radio or morning broadcast","Photo booth and event photo albums","School map with rooms and club spaces","Daily school announcements archive"]},
 {title:"Clubs & events",items:["Club recruitment week","Cultural festival booth planner","Sports season standings","Tournament brackets","Club attendance streaks","Club achievement badges","Student council elections","Event RSVP and volunteer sign-ups","Festival passport or stamp collection","Seasonal school event themes"]},
 {title:"Academic extras",items:["Study streaks and optional progress badges","Peer tutoring board","Office-hours booking","Exam countdown widgets","Personal study timer","Class resource collections","Assignment study checklists","Teacher-created study guides","Academic honor wall","Graduation progress tracker"]},
 {title:"Customization",items:["More profile widget types","Custom profile music links where permitted","Decorative stickers and frames","Profile themes by club or season","Custom dashboard layouts","Pinned favorite classes or clubs","Widget visibility controls","Public profile badges","Theme presets made by users","Yearbook-style profile templates"]},
 {title:"Owner & moderation",items:["Feature request voting","Owner-visible user feedback inbox","Site-wide audit timeline","One-click role preview","Permission comparison tool","Maintenance notice composer","Backup/export snapshots","Feature beta groups","Moderation appeal workflow","System health history"]}
];
export default function IdeasPage(){return <main style={{maxWidth:1100,margin:"30px auto",padding:"0 18px 70px"}}><header><p style={{margin:0,font:"700 10px Arial",letterSpacing:".1em",color:"#8f365b"}}>COMMUNITY-STYLE IDEAS</p><h1 style={{margin:"5px 0",font:"400 38px Georgia,serif",color:"#17375f"}}>Things Hanami users may want next</h1><p style={{maxWidth:800}}>These are optional ideas that fit the school-roleplay format without replacing the core academic systems. They can be prioritized later based on what students, faculty, and staff actually use.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:18}}><a href="../features/" style={{padding:"8px 11px",border:"1px solid #17375f",textDecoration:"none"}}>Portal Feature Center</a><a href="../changelog/" style={{padding:"8px 11px",border:"1px solid #17375f",textDecoration:"none"}}>Website changelog</a></div></header><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}>{groups.map(group=><section key={group.title} style={{border:"1px solid #c7cdd6",background:"#fff",padding:15}}><h2 style={{margin:"0 0 8px",font:"400 23px Georgia,serif",color:"#17375f"}}>{group.title}</h2><ul style={{margin:0,paddingLeft:18}}>{group.items.map(item=><li key={item} style={{marginBottom:6}}>{item}</li>)}</ul></section>)}</div></main>}
