"use client";

import {useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1",CHARACTER_KEY="hanami.portal.character.v1";
type Team={id:string;name:string;sport:string;season:string;description:string;is_active:boolean};type Practice={id:string;team_id:string;starts_at:string;ends_at:string|null;location:string|null;note:string};type Fixture={id:string;team_id:string;opponent:string;starts_at:string;location:string|null;home_away:string;status:string;hanami_score:number|null;opponent_score:number|null;result_note:string};type Standing={team_id:string;team_name:string;sport:string;games_played:number;wins:number;losses:number;ties:number};type Player={character_id:string;display_name:string;handle:string;player_position:string|null;jersey_number:string|null;roster_status:string};type Eligibility={eligible:boolean;academic_status:string;attendance_status:string;note:string};
function auth(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)??"{}") as {accessToken?:string};return {token:s.accessToken??"",characterId:localStorage.getItem(CHARACTER_KEY)??""};}catch{return {token:"",characterId:""};}}
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
export default function SportsPage(){const credentials=useMemo(()=>typeof window==="undefined"?{token:"",characterId:""}:auth(),[]);const [teams,setTeams]=useState<Team[]>([]),[practices,setPractices]=useState<Practice[]>([]),[fixtures,setFixtures]=useState<Fixture[]>([]),[standings,setStandings]=useState<Standing[]>([]),[rosters,setRosters]=useState<Record<string,Player[]>>({}),[eligibility,setEligibility]=useState<Eligibility|null>(null),[status,setStatus]=useState("Sign in through the Portal Gateway to open Athletics.");
 useEffect(()=>{if(!credentials.token)return;Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/sports_teams?select=id,name,sport,season,description,is_active&is_active=eq.true&order=sport,name`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Team[]>),
  fetch(`${SUPABASE_URL}/rest/v1/sports_practices?select=id,team_id,starts_at,ends_at,location,note&order=starts_at.asc`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Practice[]>),
  fetch(`${SUPABASE_URL}/rest/v1/sports_fixtures?select=id,team_id,opponent,starts_at,location,home_away,status,hanami_score,opponent_score,result_note&order=starts_at.desc`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Fixture[]>),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/sports_team_standings`,{method:"POST",headers:headers(credentials.token,{"Content-Type":"application/json"}),body:"{}"}).then(r=>r.json() as Promise<Standing[]>),
  credentials.characterId?fetch(`${SUPABASE_URL}/rest/v1/athletics_eligibility?select=eligible,academic_status,attendance_status,note&student_character_id=eq.${encodeURIComponent(credentials.characterId)}&limit=1`,{headers:headers(credentials.token)}).then(r=>r.json() as Promise<Eligibility[]>):Promise.resolve([])
 ]).then(async([t,p,f,s,e])=>{setTeams(t);setPractices(p);setFixtures(f);setStandings(s);setEligibility(e[0]??null);const pairs=await Promise.all(t.map(async team=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/sports_team_roster_directory`,{method:"POST",headers:headers(credentials.token,{"Content-Type":"application/json"}),body:JSON.stringify({target_team_id:team.id})});return [team.id,r.ok?await r.json() as Player[]:[]] as const;}));setRosters(Object.fromEntries(pairs));setStatus(`${t.length} active sports team${t.length===1?"":"s"}.`);}).catch(()=>setStatus("Athletics information could not be loaded."));},[credentials]);
 const fmt=(v:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
 return <main className="site-page"><header className="school-header"><div className="network-strip">HANAMI HIGH SCHOOL • SPORTS & ATHLETICS • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark"><span>H</span></div><div><p className="jp-name">HANAMI HIGH SCHOOL</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Sports & Athletics</p></div></a></div><div className="nav-row"><nav><a href="../">School Home</a><a href="../campus-life/">Campus Life</a><a className="active" href="./">Athletics</a><a href="../organizations/">Organizations</a></nav><a className="portal-button" href="../portal/">Portal Gateway</a></div></header><section className="info-section" style={{margin:"24px"}}><div className="section-heading"><h2>SPORTS & ATHLETICS</h2><span>TEAMS • FIXTURES • STANDINGS</span></div><p className="content-note">{status}</p>{eligibility&&<article style={{border:"1px solid #9fb0c2",padding:12,background:"#fffdf8",marginBottom:14}}><p className="eyebrow">YOUR ATHLETICS ELIGIBILITY</p><h3>{eligibility.eligible?"ELIGIBLE":"NOT ELIGIBLE"}</h3><p>Academics: {eligibility.academic_status} • Attendance: {eligibility.attendance_status}</p>{eligibility.note&&<p>{eligibility.note}</p>}</article>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14}}>{teams.map(team=>{const standing=standings.find(s=>s.team_id===team.id);return <article key={team.id} style={{border:"1px solid #b8c3cf",padding:14,background:"#fffdf8"}}><p className="eyebrow">{team.sport.toUpperCase()} • {team.season}</p><h3 style={{fontFamily:"Georgia,serif",color:"#17375f"}}>{team.name}</h3><p>{team.description}</p>{standing&&<p><strong>Standings:</strong> {standing.wins}W–{standing.losses}L–{standing.ties}T • {standing.games_played} played</p>}<h4>Roster</h4>{(rosters[team.id]??[]).map(player=><p key={player.character_id}>{player.jersey_number?`#${player.jersey_number} `:""}<strong>{player.display_name}</strong> (@{player.handle}){player.player_position?` • ${player.player_position}`:""} • {player.roster_status}</p>)}<h4>Practice Schedule</h4>{practices.filter(p=>p.team_id===team.id).slice(0,4).map(p=><p key={p.id}>{fmt(p.starts_at)}{p.location?` • ${p.location}`:""}{p.note?` • ${p.note}`:""}</p>)}<h4>Fixtures & Scores</h4>{fixtures.filter(f=>f.team_id===team.id).slice(0,6).map(f=><p key={f.id}><strong>{f.home_away.toUpperCase()}</strong> vs. {f.opponent} • {fmt(f.starts_at)}{f.location?` • ${f.location}`:""}<br/>{f.status==="completed"?`Final: Hanami ${f.hanami_score??0} – ${f.opponent_score??0}`:f.status}{f.result_note?` • ${f.result_note}`:""}</p>)}</article>;})}</div></section><footer><p>HANAMI HIGH SCHOOL • SPORTS & ATHLETICS • 2006</p><nav><a href="../organizations/">Organizations</a><a href="../portal/">Portal</a><a href="../">School Home</a></nav></footer></main>;}
