"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./AcademicProgressPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type Tab="exams"|"guides"|"graduation"|"honors"|"seating"|"passes"|"hours"|"mentorship"|"handbook";
type Exam={id:string;section_id:string;exam_title:string;exam_at:string;room:string|null;seat_number:string|null;review_materials:string|null};
type Guide={id:string;section_id:string;exam_id:string|null;title:string;content:string;attachment_url:string|null;created_at:string};
type Requirement={id:string;requirement_key:string;title:string;description:string|null;category:string;required_amount:number;sort_order:number};
type Progress={id:string;requirement_id:string;amount:number;completed:boolean;note:string|null};
type Honor={id:string;student_character_id:string;term:string;honor_title:string;description:string|null;class_rank:number|null;show_rank_publicly:boolean;created_at:string};
type Character={id:string;display_name:string;handle:string;role:string};
type SectionMembership={class_sections:{id:string;section_code:string;room:string|null;academic_courses:{code:string;title:string}|null}|null};
type Seat={id:string;section_id:string;student_character_id:string;seat_label:string;row_number:number;column_number:number};
type HallPass={id:string;pass_type:string;destination:string;reason:string|null;status:string;valid_from:string|null;valid_until:string|null;staff_note:string|null;created_at:string};
type VolunteerHour={id:string;activity_name:string;hours:number;service_date:string;note:string|null;verified_by:string|null};
type Shift={id:string;workplace_name:string;shift_date:string;starts_at:string;ends_at:string;status:string;notes:string|null};
type Mentorship={id:string;mentee_character_id:string;mentor_character_id:string|null;topic:string;note:string|null;status:string;created_at:string};
type Handbook={id:string;slug:string;category:string;title:string;body:string;policy_version:string;acknowledgement_required:boolean;sort_order:number};
type Ack={section_id:string;character_id:string;policy_version:string;acknowledged_at:string};
type Streak={character_id:string;current_streak:number;longest_streak:number;last_study_date:string|null;badges:unknown};

function h(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function get<T>(token:string,path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:h(token)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}
async function mutate(token:string,path:string,method:string,body:unknown,prefer="return=minimal"){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:h(token,{"Content-Type":"application/json",Prefer:prefer}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r;}
function nice(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function roleplayNow(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const value=(t:string)=>parts.find(p=>p.type===t)?.value??"00";return new Date(`2006-${value("month")}-${value("day")}T${value("hour")}:${value("minute")}:00+09:00`);}
function countdown(at:string){const diff=new Date(at).getTime()-roleplayNow().getTime();if(diff<=0)return "Started / completed";const days=Math.floor(diff/86400000),hours=Math.floor((diff%86400000)/3600000);return days>0?`${days}d ${hours}h`:`${hours}h ${Math.max(0,Math.floor((diff%3600000)/60000))}m`;}
function dateLabel(v:string){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));}

export default function AcademicProgressPanel({accessToken,characterId}:Props){
 const [tab,setTab]=useState<Tab>("exams"),[message,setMessage]=useState("Loading academic tools…");
 const [exams,setExams]=useState<Exam[]>([]),[guides,setGuides]=useState<Guide[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[progress,setProgress]=useState<Progress[]>([]),[honors,setHonors]=useState<Honor[]>([]),[characters,setCharacters]=useState<Character[]>([]),[memberships,setMemberships]=useState<SectionMembership[]>([]),[seats,setSeats]=useState<Seat[]>([]),[passes,setPasses]=useState<HallPass[]>([]),[volunteerHours,setVolunteerHours]=useState<VolunteerHour[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[mentorships,setMentorships]=useState<Mentorship[]>([]),[handbook,setHandbook]=useState<Handbook[]>([]),[acks,setAcks]=useState<Ack[]>([]),[streak,setStreak]=useState<Streak|null>(null);
 const [passDraft,setPassDraft]=useState({type:"hall",destination:"Library",reason:""}),[mentorDraft,setMentorDraft]=useState({mentor:"",topic:"Study support",note:""});
 const charMap=useMemo(()=>new Map(characters.map(c=>[c.id,c])),[characters]);const sectionRows=useMemo(()=>memberships.map(m=>m.class_sections).filter(Boolean) as NonNullable<SectionMembership["class_sections"]>[],[memberships]);const sectionMap=useMemo(()=>new Map(sectionRows.map(s=>[s.id,s])),[sectionRows]);
 async function load(){try{setMessage("Refreshing academic tools…");const membershipRows=await get<SectionMembership[]>(accessToken,`section_memberships?select=class_sections(id,section_code,room,academic_courses(code,title))&character_id=eq.${characterId}&relationship=eq.student`);const sectionIds=membershipRows.map(x=>x.class_sections?.id).filter(Boolean) as string[];const seatFilter=sectionIds.length?`section_id=in.(${sectionIds.join(",")})`:"id=eq.00000000-0000-0000-0000-000000000000";const [examRows,guideRows,reqRows,progRows,honorRows,charRows,seatRows,passRows,vhRows,shiftRows,mentorRows,handbookRows,ackRows,streakRows]=await Promise.all([
  get<Exam[]>(accessToken,`exam_assignments?select=id,section_id,exam_title,exam_at,room,seat_number,review_materials&student_character_id=eq.${characterId}&order=exam_at.asc`),
  get<Guide[]>(accessToken,"study_guides?select=id,section_id,exam_id,title,content,attachment_url,created_at&published=eq.true&order=created_at.desc"),
  get<Requirement[]>(accessToken,"graduation_requirements?select=id,requirement_key,title,description,category,required_amount,sort_order&active=eq.true&order=sort_order.asc"),
  get<Progress[]>(accessToken,`student_graduation_progress?select=id,requirement_id,amount,completed,note&character_id=eq.${characterId}`),
  get<Honor[]>(accessToken,"student_honors?select=id,student_character_id,term,honor_title,description,class_rank,show_rank_publicly,created_at&order=created_at.desc&limit=60"),
  get<Character[]>(accessToken,"characters?select=id,display_name,handle,role"),
  get<Seat[]>(accessToken,`classroom_seating_assignments?select=id,section_id,student_character_id,seat_label,row_number,column_number&${seatFilter}&order=section_id.asc,row_number.asc,column_number.asc`),
  get<HallPass[]>(accessToken,`hall_passes?select=id,pass_type,destination,reason,status,valid_from,valid_until,staff_note,created_at&student_character_id=eq.${characterId}&order=created_at.desc`),
  get<VolunteerHour[]>(accessToken,`volunteer_hours?select=id,activity_name,hours,service_date,note,verified_by&character_id=eq.${characterId}&order=service_date.desc`),
  get<Shift[]>(accessToken,`student_work_shifts?select=id,workplace_name,shift_date,starts_at,ends_at,status,notes&character_id=eq.${characterId}&order=shift_date.desc`),
  get<Mentorship[]>(accessToken,`mentorship_requests?select=id,mentee_character_id,mentor_character_id,topic,note,status,created_at&mentee_character_id=eq.${characterId}&order=created_at.desc`),
  get<Handbook[]>(accessToken,"handbook_sections?select=id,slug,category,title,body,policy_version,acknowledgement_required,sort_order&status=eq.published&order=sort_order.asc"),
  get<Ack[]>(accessToken,`policy_acknowledgements?select=section_id,character_id,policy_version,acknowledged_at&character_id=eq.${characterId}`),
  get<Streak[]>(accessToken,`study_streaks?select=character_id,current_streak,longest_streak,last_study_date,badges&character_id=eq.${characterId}&limit=1`)
 ]);setMemberships(membershipRows);setExams(examRows);setGuides(guideRows);setRequirements(reqRows);setProgress(progRows);setHonors(honorRows);setCharacters(charRows);setSeats(seatRows);setPasses(passRows);setVolunteerHours(vhRows);setShifts(shiftRows);setMentorships(mentorRows);setHandbook(handbookRows);setAcks(ackRows);setStreak(streakRows[0]??null);setMessage("Academic & productivity batch is ready.");}catch(error){setMessage(error instanceof Error?error.message:"Academic tools could not be loaded.");}}
 useEffect(()=>{void load();},[accessToken,characterId]);
 async function requestPass(e:FormEvent){e.preventDefault();if(!passDraft.destination.trim())return;try{await mutate(accessToken,"hall_passes","POST",{student_character_id:characterId,requested_by_character_id:characterId,pass_type:passDraft.type,destination:passDraft.destination.trim(),reason:passDraft.reason||null,status:"requested"});setPassDraft({type:"hall",destination:"Library",reason:""});await load();setMessage("Hall pass request sent to staff.");}catch(error){setMessage(error instanceof Error?error.message:"Hall pass could not be requested.");}}
 async function requestMentor(e:FormEvent){e.preventDefault();try{await mutate(accessToken,"mentorship_requests","POST",{mentee_character_id:characterId,mentor_character_id:mentorDraft.mentor||null,topic:mentorDraft.topic.trim(),note:mentorDraft.note||null,status:"pending"});setMentorDraft({mentor:"",topic:"Study support",note:""});await load();setMessage("Mentorship request sent.");}catch(error){setMessage(error instanceof Error?error.message:"Mentorship request could not be sent.");}}
 async function acknowledge(section:Handbook){try{await mutate(accessToken,"policy_acknowledgements","POST",{section_id:section.id,character_id:characterId,policy_version:section.policy_version},"resolution=merge-duplicates,return=minimal");await load();setMessage(`${section.title} acknowledged.`);}catch(error){setMessage(error instanceof Error?error.message:"Acknowledgement could not be saved.");}}
 const totalVolunteer=volunteerHours.reduce((s,v)=>s+Number(v.hours),0);const completedReq=requirements.filter(r=>progress.find(p=>p.requirement_id===r.id)?.completed).length;const percent=requirements.length?Math.round(completedReq/requirements.length*100):0;const tabs:[Tab,string][]=[["exams","Exam Countdown"],["guides","Study Guides"],["graduation","Graduation"],["honors","Honor Wall"],["seating","Seating Charts"],["passes","Hall Passes"],["hours","Work & Service"],["mentorship","Mentorship"],["handbook","Handbook"]];
 return <section className={styles.panel}><header className={styles.header}><div><p className="eyebrow">ACADEMICS & PRODUCTIVITY</p><h3>Student progress center</h3><p>Exam preparation, graduation progress, school recognition, classroom tools, and support.</p></div><span>{message}</span></header><nav className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="exams"&&<div className={styles.grid}><article className={styles.heroCard}><small>OPTIONAL STUDY STREAK</small><strong>{streak?.current_streak??0} days</strong><span>Longest: {streak?.longest_streak??0} days</span><p>Study streaks are optional encouragement only; they do not affect grades, eligibility, or school standing.</p></article>{exams.map(e=><article className={styles.card} key={e.id}><div className={styles.row}><small>{sectionMap.get(e.section_id)?.academic_courses?.title??"Exam"}</small><b>{countdown(e.exam_at)}</b></div><h4>{e.exam_title}</h4><p>{dateLabel(e.exam_at)} • {e.room||"Room TBA"}{e.seat_number?` • Seat ${e.seat_number}`:""}</p>{e.review_materials&&<p>{e.review_materials}</p>}</article>)}{!exams.length&&<div className={styles.card}>No exams are assigned right now.</div>}</div>}
 {tab==="guides"&&<div className={styles.stack}>{guides.filter(g=>sectionMap.has(g.section_id)).map(g=><article className={styles.card} key={g.id}><small>{sectionMap.get(g.section_id)?.academic_courses?.title??"Course"}</small><h4>{g.title}</h4><p className={styles.guide}>{g.content}</p>{g.attachment_url&&<a href={g.attachment_url} target="_blank" rel="noreferrer">Open study-guide attachment →</a>}</article>)}{!guides.filter(g=>sectionMap.has(g.section_id)).length&&<div className={styles.card}>Teachers have not published study guides for your courses yet.</div>}</div>}
 {tab==="graduation"&&<div className={styles.stack}><article className={styles.progressHero}><div><small>GRADUATION PROGRESS</small><strong>{percent}%</strong></div><progress max={100} value={percent}/><span>{completedReq} of {requirements.length} requirements complete</span></article>{requirements.map(r=>{const p=progress.find(x=>x.requirement_id===r.id);const amount=Number(p?.amount??0);return <article className={styles.requirement} key={r.id}><div><small>{nice(r.category)}</small><h4>{r.title}</h4>{r.description&&<p>{r.description}</p>}{p?.note&&<small>{p.note}</small>}</div><div><strong>{amount}/{Number(r.required_amount)}</strong><span>{p?.completed?"✓ Complete":"In progress"}</span></div></article>})}</div>}
 {tab==="honors"&&<div className={styles.honorGrid}>{honors.map(honor=><article className={styles.honor} key={honor.id}><span>✦</span><small>{honor.term}</small><h4>{honor.honor_title}</h4><strong>{charMap.get(honor.student_character_id)?.display_name??"Hanami Student"}</strong>{honor.description&&<p>{honor.description}</p>}{honor.show_rank_publicly&&honor.class_rank&&<b>Class Rank #{honor.class_rank}</b>}</article>)}{!honors.length&&<div className={styles.card}>Academic honors will appear here as they are awarded.</div>}</div>}
 {tab==="seating"&&<div className={styles.stack}>{sectionRows.map(section=>{const rows=seats.filter(s=>s.section_id===section.id);const maxCol=Math.max(1,...rows.map(s=>s.column_number));return <article className={styles.card} key={section.id}><div className={styles.row}><div><small>{section.academic_courses?.code}</small><h4>{section.academic_courses?.title??"Class"} • Section {section.section_code}</h4></div><span>{section.room?`Room ${section.room}`:""}</span></div><div className={styles.seating} style={{gridTemplateColumns:`repeat(${Math.min(maxCol,8)},minmax(70px,1fr))`}}>{rows.map(seat=><div key={seat.id} className={seat.student_character_id===characterId?styles.mySeat:""}><b>{seat.seat_label}</b><span>{charMap.get(seat.student_character_id)?.display_name??"Student"}</span></div>)}</div>{!rows.length&&<p>No seating chart published for this course yet.</p>}</article>})}</div>}
 {tab==="passes"&&<div className={styles.split}><form className={styles.card} onSubmit={requestPass}><h4>Request a hall pass</h4><select value={passDraft.type} onChange={e=>setPassDraft({...passDraft,type:e.target.value})}><option value="hall">Hall pass</option><option value="library">Library</option><option value="office">School office</option><option value="nurse">Nurse</option><option value="restroom">Restroom</option></select><input placeholder="Destination" value={passDraft.destination} onChange={e=>setPassDraft({...passDraft,destination:e.target.value})}/><textarea rows={4} placeholder="Reason (optional)" value={passDraft.reason} onChange={e=>setPassDraft({...passDraft,reason:e.target.value})}/><button>Request pass</button></form><div className={styles.stack}>{passes.map(p=><article className={styles.card} key={p.id}><div className={styles.row}><strong>{nice(p.pass_type)} → {p.destination}</strong><span>{nice(p.status)}</span></div>{p.reason&&<p>{p.reason}</p>}{p.valid_from&&<small>Valid {dateLabel(p.valid_from)}{p.valid_until?`–${dateLabel(p.valid_until)}`:""}</small>}{p.staff_note&&<p>Staff: {p.staff_note}</p>}</article>)}</div></div>}
 {tab==="hours"&&<div className={styles.split}><article className={styles.heroCard}><small>VERIFIED SERVICE</small><strong>{totalVolunteer.toFixed(1)} hours</strong><span>{volunteerHours.length} service record{volunteerHours.length===1?"":"s"}</span></article><div className={styles.stack}>{volunteerHours.map(v=><article className={styles.card} key={v.id}><div className={styles.row}><strong>{v.activity_name}</strong><b>{Number(v.hours).toFixed(1)}h</b></div><small>{v.service_date}{v.verified_by?" • Verified":" • Awaiting verification"}</small>{v.note&&<p>{v.note}</p>}</article>)}{shifts.map(s=><article className={styles.card} key={s.id}><div className={styles.row}><strong>{s.workplace_name}</strong><span>{nice(s.status)}</span></div><p>{s.shift_date} • {s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)}</p>{s.notes&&<small>{s.notes}</small>}</article>)}</div></div>}
 {tab==="mentorship"&&<div className={styles.split}><form className={styles.card} onSubmit={requestMentor}><h4>Request mentorship</h4><select value={mentorDraft.mentor} onChange={e=>setMentorDraft({...mentorDraft,mentor:e.target.value})}><option value="">Let staff match me</option>{characters.filter(c=>c.id!==characterId).map(c=><option value={c.id} key={c.id}>{c.display_name} • {nice(c.role)}</option>)}</select><input value={mentorDraft.topic} placeholder="Topic" onChange={e=>setMentorDraft({...mentorDraft,topic:e.target.value})}/><textarea rows={5} placeholder="What would you like help with?" value={mentorDraft.note} onChange={e=>setMentorDraft({...mentorDraft,note:e.target.value})}/><button>Send mentorship request</button></form><div className={styles.stack}>{mentorships.map(m=><article className={styles.card} key={m.id}><div className={styles.row}><strong>{m.topic}</strong><span>{nice(m.status)}</span></div><p>Mentor: {m.mentor_character_id?charMap.get(m.mentor_character_id)?.display_name??"Selected mentor":"Staff match requested"}</p>{m.note&&<small>{m.note}</small>}</article>)}</div></div>}
 {tab==="handbook"&&<div className={styles.stack}>{handbook.map(section=>{const acknowledged=acks.some(a=>a.section_id===section.id&&a.policy_version===section.policy_version);return <article className={styles.card} key={section.id}><div className={styles.row}><div><small>{nice(section.category)} • Version {section.policy_version}</small><h4>{section.title}</h4></div>{section.acknowledgement_required&&<span>{acknowledged?"✓ ACKNOWLEDGED":"ACTION REQUIRED"}</span>}</div><div className={styles.handbookBody}>{section.body}</div>{section.acknowledgement_required&&!acknowledged&&<button onClick={()=>acknowledge(section)}>I have read and acknowledge this section</button>}</article>})}</div>}
 </section>;
}
