"use client";

import {useCallback,useEffect,useState} from "react";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function h(token:string,extra:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${token}`,...extra};}
type AccountStatus={account_status:string;suspension_reason:string|null};
type PlusStatus={active:boolean;permanent:boolean;active_until:string|null;last_source_type:string|null;last_source_ref:string|null};
type Wallet={balance:number;lifetime_earned:number};
type Slot={id:string;slot:number;display_name:string;handle:string;role:string;is_active:boolean};
type Entitlement={entitlement_key:string;source_type:string;granted_at:string};
type Grant={id:string;duration_days:number|null;permanent:boolean;source_type:string;source_ref:string|null;note:string|null;granted_at:string};
function formatDate(value:string|null){if(!value)return "—";return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value));}

export default function AccountMembershipSettingsPanel({accessToken}:{accessToken:string}){
 const [account,setAccount]=useState<AccountStatus|null>(null);const [plus,setPlus]=useState<PlusStatus|null>(null);const [wallet,setWallet]=useState<Wallet|null>(null);const [slots,setSlots]=useState<Slot[]>([]);const [entitlements,setEntitlements]=useState<Entitlement[]>([]);const [grants,setGrants]=useState<Grant[]>([]);const [notice,setNotice]=useState("Loading account details…");
 const load=useCallback(async()=>{setNotice("Loading account details…");try{await fetch(`${U}/rest/v1/rpc/ensure_current_petal_wallet`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:"{}"});const [a,p,w,s,e,g]=await Promise.all([fetch(`${U}/rest/v1/rpc/current_account_status`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:"{}",cache:"no-store"}),fetch(`${U}/rest/v1/rpc/current_hanami_plus_status`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:"{}",cache:"no-store"}),fetch(`${U}/rest/v1/petal_wallets?select=balance,lifetime_earned&limit=1`,{headers:h(accessToken),cache:"no-store"}),fetch(`${U}/rest/v1/rpc/current_user_character_slots`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:"{}",cache:"no-store"}),fetch(`${U}/rest/v1/account_entitlements?select=entitlement_key,source_type,granted_at&order=granted_at.desc`,{headers:h(accessToken),cache:"no-store"}),fetch(`${U}/rest/v1/hanami_plus_grants?select=id,duration_days,permanent,source_type,source_ref,note,granted_at&order=granted_at.desc&limit=12`,{headers:h(accessToken),cache:"no-store"})]);if(a.ok)setAccount(((await a.json()) as AccountStatus[])[0]??null);if(p.ok)setPlus(((await p.json()) as PlusStatus[])[0]??null);if(w.ok)setWallet(((await w.json()) as Wallet[])[0]??null);if(s.ok)setSlots(await s.json() as Slot[]);if(e.ok)setEntitlements(await e.json() as Entitlement[]);if(g.ok)setGrants(await g.json() as Grant[]);setNotice("Account and membership details are current.");}catch{setNotice("Account details could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 const accountGood=(account?.account_status??"active")==="active";const bloom=entitlements.some(x=>x.entitlement_key==="hanami_bloom");
 return <section aria-label="Account and membership settings" style={{display:"grid",gap:14}}>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10}}>
   <article style={{border:"1px solid #c5ced8",background:"#fff",padding:14}}><p className="eyebrow">ACCOUNT STANDING</p><h4 style={{margin:"4px 0",font:"400 20px Georgia,serif"}}>{accountGood?"In good standing":account?.account_status??"Checking…"}</h4><p style={{fontSize:10,margin:"4px 0"}}>{account?.suspension_reason||"No account restriction is currently reported."}</p><small>{notice}</small></article>
   <article style={{border:"1px solid #c5ced8",background:"#fff",padding:14}}><p className="eyebrow">CHARACTER SLOTS</p><h4 style={{margin:"4px 0",font:"400 20px Georgia,serif"}}>{Math.min(slots.length,2)}/2 used</h4><p style={{fontSize:10,margin:"4px 0"}}>One Hanami account may hold up to two Student/Faculty characters. Admin and Owner access remains account-level.</p></article>
   <article style={{border:"1px solid #c5ced8",background:"#fff",padding:14}}><p className="eyebrow">PETALS</p><h4 style={{margin:"4px 0",font:"400 20px Georgia,serif"}}>✿ {wallet?.balance??0}</h4><p style={{fontSize:10,margin:"4px 0"}}>{wallet?.lifetime_earned??0} lifetime Petals earned through Hanami participation.</p></article>
  </div>
  <article style={{border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:"13px 14px",background:"#eef3f8",borderBottom:"1px solid #c5ced8",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><p className="eyebrow">HANAMI+</p><h4 style={{margin:"3px 0",font:"400 20px Georgia,serif"}}>{plus?.active?plus.permanent?"Hanami+ Forever":"Hanami+ active":"Standard membership"}</h4><small>{plus?.active&&!plus.permanent?`Active through ${formatDate(plus.active_until)}`:plus?.permanent?"Permanent Hanami+ unlock":"Hanami+ is optional and earnable; standard Hanami access remains available without it."}</small></div><span style={{padding:"5px 8px",border:"1px solid #9dacba",fontSize:9,fontWeight:700}}>{plus?.active?"ACTIVE":"STANDARD"}</span></div><div style={{padding:14,display:"grid",gap:10}}><p style={{fontSize:10,lineHeight:1.55,margin:0}}>Hanami+ unlocks advanced profile and identity customization tools. It is not required to participate in school roleplay, classes, clubs, messages, or the core community.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:8}}>{["1 / 7 / 30-day Petal passes","Milestones & activity rewards","School events & free Bloom Days","Gift passes","Staff & community awards","Rare Hanami+ Forever unlocks"].map(item=><div key={item} style={{border:"1px solid #d8dee5",background:"#f8fafc",padding:9,fontSize:10}}>{item}</div>)}</div>{plus?.last_source_type&&<small>Most recent source: {plus.last_source_type.replaceAll("_"," ")}{plus.last_source_ref?` · ${plus.last_source_ref}`:""}</small>}<p style={{fontSize:9,color:"#687789",margin:0}}>Petal pass prices are intentionally not shown until Hanami&apos;s owner-configured rates are set. Passes stack when granted, and earned Boutique cosmetics remain owned even when Hanami+ expires.</p></div></article>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:10}}><article style={{border:"1px solid #c5ced8",background:"#fff",padding:14}}><h5 style={{marginTop:0}}>Characters on this account</h5>{slots.length?slots.map(slot=><div key={slot.id} style={{borderTop:"1px solid #e0e5ea",padding:"8px 0",fontSize:10}}><strong>Slot {slot.slot}: {slot.display_name}</strong><div>@{slot.handle} · {slot.role}{slot.is_active?" · active":""}</div></div>):<p style={{fontSize:10}}>No character slots are filled yet.</p>}</article><article style={{border:"1px solid #c5ced8",background:"#fff",padding:14}}><h5 style={{marginTop:0}}>Membership history</h5>{grants.length?grants.map(grant=><div key={grant.id} style={{borderTop:"1px solid #e0e5ea",padding:"8px 0",fontSize:10}}><strong>{grant.permanent?"Forever":`${grant.duration_days}-day`} Hanami+</strong><div>{grant.source_type.replaceAll("_"," ")} · {formatDate(grant.granted_at)}</div>{grant.note&&<small>{grant.note}</small>}</div>):<p style={{fontSize:10}}>No Hanami+ grants have been recorded for this account yet.</p>} {bloom&&<div style={{marginTop:8,padding:8,border:"1px solid #d8dee5",fontSize:10}}><strong>Hanami Bloom entitlement active</strong><div>Bloom remains a separate Discord-role/configured entitlement used by selected Exchange collectibles.</div></div>}</article></div>
 </section>;
}
