"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CanvasTodoRail.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string;role:"student"|"faculty"};
type Item={id:string;title:string;due_at:string|null;points:number;status:string;class_sections:{id:string;section_code:string;academic_courses:{code:string;title:string}|null}|null};
type Submission={assignment_id:string;status:string};
type Range="day"|"week"|"month";
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`};}
function due(value:string|null){if(!value)return "No due date";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}
export default function CanvasTodoRail({accessToken,characterId,role}:Props){
 const [items,setItems]=useState<Item[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);const [range,setRange]=useState<Range>("week");const [state,setState]=useState("Loading…");
 useEffect(()=>{let dead=false;(async()=>{try{const rel=role==="student"?"student":"instructor";const m=await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.${rel}`,{headers:headers(accessToken)});if(!m.ok)throw new Error();const sections=(await m.json() as {section_id:string}[]).map(x=>x.section_id);if(!sections.length){if(!dead){setItems([]);setState("Nothing due yet.");}return;}const filter=`(${sections.join(",")})`;const a=await fetch(`${SUPABASE_URL}/rest/v1/course_assignments?select=${encodeURIComponent("id,title,due_at,points,status,class_sections(id,section_code,academic_courses(code,title))")}&section_id=in.${encodeURIComponent(filter)}&status=in.(published,closed)&order=due_at.asc.nullslast`,{headers:headers(accessToken)});if(!a.ok)throw new Error();const assignmentRows=await a.json() as Item[];let submissionRows:Submission[]=[];if(role==="student"){const s=await fetch(`${SUPABASE_URL}/rest/v1/assignment_submissions?select=assignment_id,status&student_character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)});if(s.ok)submissionRows=await s.json() as Submission[];}if(!dead){setItems(assignmentRows);setSubmissions(submissionRows);setState(assignmentRows.length?"":"Nothing due yet.");}}catch{if(!dead)setState("To-do list unavailable.");}})();return()=>{dead=true};},[accessToken,characterId,role]);
 const done=new Set(submissions.filter(x=>x.status==="submitted"||x.status==="returned").map(x=>x.assignment_id));
 const visible=useMemo(()=>{const now=new Date();const days=range==="day"?1:range==="week"?7:31;const end=new Date(now.getTime()+days*86400000);return items.filter(x=>!x.due_at||new Date(x.due_at)<=end).slice(0,12);},[items,range]);
 const completed=role==="student"?items.filter(x=>done.has(x.id)).length:items.filter(x=>x.status==="closed").length;const total=Math.max(items.length,1);const pct=Math.round(completed/total*100);
 const overdue=visible.filter(x=>x.due_at&&new Date(x.due_at)<new Date()&&!done.has(x.id));const upcoming=visible.filter(x=>!overdue.includes(x)&&!done.has(x.id));
 return <aside className={styles.rail} aria-label="To do"><div className={styles.head}><h3>To-Do</h3><button type="button" aria-label="To-do settings">⚙</button></div><div className={styles.tabs}>{(["day","week","month"] as Range[]).map(x=><button key={x} type="button" className={range===x?styles.active:""} onClick={()=>setRange(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className={styles.ring} style={{"--pct":`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{pct}%</strong><span>{completed}/{items.length} complete</span></div></div><div className={styles.legend}><span>Assignments</span><span>Hanami High</span></div>{state&&<p className={styles.state}>{state}</p>}{overdue.length>0&&<section><h4><span>{overdue.length}</span> Overdue</h4>{overdue.map(x=><article key={x.id}><i/><div><strong>{x.title}</strong><small>{x.class_sections?.academic_courses?.code??"COURSE"}</small><span>Due {due(x.due_at)} · {x.points} pts</span></div><b>○</b></article>)}</section>}<section><h4>Due {range==="day"?"today":range==="week"?"this week":"this month"}</h4>{upcoming.length?upcoming.map(x=><article key={x.id}><i/><div><strong>{x.title}</strong><small>{x.class_sections?.academic_courses?.code??"COURSE"}</small><span>{x.due_at?`Due ${due(x.due_at)}`:"No due date"} · {x.points} pts</span></div><b>{done.has(x.id)?"✓":"○"}</b></article>):<p className={styles.empty}>You&apos;re caught up.</p>}</section></aside>;
}
