"use client";

import {useEffect,useMemo,useState} from "react";
import {hanamiRoleplayNow} from "../components/roleplay-date";
import styles from "./CanvasTodoRail.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string;role:"student"|"faculty"};
type Item={id:string;title:string;due_at:string|null;points:number;status:string;class_sections:{id:string;section_code:string;academic_courses:{code:string;title:string}|null}|null};
type Submission={assignment_id:string;status:string};
type Meeting={weekday:number;starts_at:string;ends_at:string};
type TeachingSection={id:string;section_code:string;room:string|null;academic_courses:{code:string;title:string}|null;section_meetings:Meeting[]};
type TeachingMembership={section_id:string;class_sections:TeachingSection|null};
type FacultySubmission={id:string;status:string;assignment_id:string};
type Range="day"|"week"|"month";
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`};}
function due(value:string|null){if(!value)return "No due date";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}
function timeLabel(value:string){const [h,m]=value.split(":");const hour=Number(h);return `${hour%12||12}:${m} ${hour>=12?"PM":"AM"}`;}
function minuteOf(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
function currentMinute(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(hanamiRoleplayNow());return Number(parts.find(p=>p.type==="hour")?.value??0)*60+Number(parts.find(p=>p.type==="minute")?.value??0);}
function roleplayWeekday(){const day=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(hanamiRoleplayNow());return ["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].indexOf(day);}

export default function CanvasTodoRail({accessToken,characterId,role}:Props){
 const [items,setItems]=useState<Item[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);const [teaching,setTeaching]=useState<TeachingSection[]>([]);const [facultySubmissions,setFacultySubmissions]=useState<FacultySubmission[]>([]);const [range,setRange]=useState<Range>("week");const [state,setState]=useState("Loading…");const [clock,setClock]=useState(()=>hanamiRoleplayNow());
 useEffect(()=>{const timer=window.setInterval(()=>setClock(hanamiRoleplayNow()),30000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{let dead=false;(async()=>{try{
  if(role==="student"){
   const m=await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.student`,{headers:headers(accessToken)});if(!m.ok)throw new Error();const sections=(await m.json() as {section_id:string}[]).map(x=>x.section_id);if(!sections.length){if(!dead){setItems([]);setState("Nothing due yet.");}return;}const filter=`(${sections.join(",")})`;const a=await fetch(`${SUPABASE_URL}/rest/v1/course_assignments?select=${encodeURIComponent("id,title,due_at,points,status,class_sections(id,section_code,academic_courses(code,title))")}&section_id=in.${encodeURIComponent(filter)}&status=in.(published,closed)&order=due_at.asc.nullslast`,{headers:headers(accessToken)});if(!a.ok)throw new Error();const assignmentRows=await a.json() as Item[];let submissionRows:Submission[]=[];const s=await fetch(`${SUPABASE_URL}/rest/v1/assignment_submissions?select=assignment_id,status&student_character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)});if(s.ok)submissionRows=await s.json() as Submission[];if(!dead){setItems(assignmentRows);setSubmissions(submissionRows);setState(assignmentRows.length?"":"Nothing due yet.");}
  }else{
   const select="section_id,class_sections(id,section_code,room,academic_courses(code,title),section_meetings(weekday,starts_at,ends_at))";
   const m=await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.instructor`,{headers:headers(accessToken)});if(!m.ok)throw new Error();const memberships=await m.json() as TeachingMembership[];const sections=memberships.map(x=>x.class_sections).filter((x):x is TeachingSection=>Boolean(x));const sectionIds=sections.map(x=>x.id);let queue:FacultySubmission[]=[];if(sectionIds.length){const sectionFilter=`(${sectionIds.join(",")})`;const a=await fetch(`${SUPABASE_URL}/rest/v1/course_assignments?select=id&section_id=in.${encodeURIComponent(sectionFilter)}`,{headers:headers(accessToken)});if(a.ok){const assignmentIds=(await a.json() as {id:string}[]).map(x=>x.id);if(assignmentIds.length){const assignmentFilter=`(${assignmentIds.join(",")})`;const s=await fetch(`${SUPABASE_URL}/rest/v1/assignment_submissions?select=id,status,assignment_id&assignment_id=in.${encodeURIComponent(assignmentFilter)}&status=eq.submitted`,{headers:headers(accessToken)});if(s.ok)queue=await s.json() as FacultySubmission[];}}}if(!dead){setTeaching(sections);setFacultySubmissions(queue);setState(sections.length?"":"No teaching sections assigned yet.");}
  }
 }catch{if(!dead)setState(role==="student"?"To-do list unavailable.":"Teaching dashboard unavailable.");}})();return()=>{dead=true};},[accessToken,characterId,role]);

 const done=new Set(submissions.filter(x=>x.status==="submitted"||x.status==="returned").map(x=>x.assignment_id));
 const visible=useMemo(()=>{const now=hanamiRoleplayNow();const days=range==="day"?1:range==="week"?7:31;const end=new Date(now.getTime()+days*86400000);return items.filter(x=>!x.due_at||(new Date(x.due_at)>=now&&new Date(x.due_at)<=end)).slice(0,12);},[items,range,clock]);
 if(role==="faculty"){
  const day=roleplayWeekday(),minute=currentMinute();const today=teaching.flatMap(section=>(section.section_meetings??[]).filter(m=>m.weekday===day).map(m=>({section,meeting:m}))).sort((a,b)=>a.meeting.starts_at.localeCompare(b.meeting.starts_at));const current=today.find(x=>minute>=minuteOf(x.meeting.starts_at)&&minute<minuteOf(x.meeting.ends_at));const next=today.find(x=>minuteOf(x.meeting.starts_at)>minute);const clockLabel=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit"}).format(clock);
  return <aside className={`${styles.rail} ${styles.facultyRail}`} aria-label="Faculty daily command center"><div className={styles.head}><div><small>FACULTY COMMAND CENTER</small><h3>Today</h3></div><b>{clockLabel}</b></div><div className={styles.facultyNow}><span>{current?"TEACHING NOW":next?"BETWEEN CLASSES":"DAY COMPLETE"}</span><strong>{current?.section.academic_courses?.title??(next?"Open / passing time":"No active class")}</strong><small>{current?`${timeLabel(current.meeting.starts_at)}–${timeLabel(current.meeting.ends_at)} · ${current.section.section_code}${current.section.room?` · Room ${current.section.room}`:""}`:next?`Next: ${next.section.academic_courses?.title??"Class"} at ${timeLabel(next.meeting.starts_at)}`:"No more teaching meetings today."}</small></div><div className={styles.facultyStats}><article><span>SECTIONS</span><strong>{teaching.length}</strong></article><article><span>TO GRADE</span><strong>{facultySubmissions.length}</strong></article><article><span>TODAY</span><strong>{today.length}</strong></article></div>{state&&<p className={styles.state}>{state}</p>}<section className={styles.facultySchedule}><h4>Today&apos;s teaching schedule</h4>{today.length?today.map(({section,meeting},index)=><article key={`${section.id}-${index}`} className={current?.section.id===section.id&&current.meeting.starts_at===meeting.starts_at?styles.liveClass:""}><i/><div><strong>{section.academic_courses?.title??"Class"}</strong><small>{section.academic_courses?.code??"COURSE"} · {section.section_code}</small><span>{timeLabel(meeting.starts_at)}–{timeLabel(meeting.ends_at)}{section.room?` · Room ${section.room}`:""}</span></div><b>{current?.section.id===section.id&&current.meeting.starts_at===meeting.starts_at?"LIVE":"→"}</b></article>):<p className={styles.empty}>No classes scheduled today.</p>}</section><div className={styles.facultyTips}><strong>Quick workflow</strong><span>Use School → Attendance to take roll.</span><span>Use Courses → Grading for the {facultySubmissions.length} submitted item{facultySubmissions.length===1?"":"s"} waiting for review.</span></div></aside>;
 }
 const completed=items.filter(x=>done.has(x.id)).length;const total=Math.max(items.length,1);const pct=Math.round(completed/total*100);const now=hanamiRoleplayNow();const overdue=items.filter(x=>x.due_at&&new Date(x.due_at)<now&&!done.has(x.id)).slice(0,6);const upcoming=visible.filter(x=>!done.has(x.id));
 return <aside className={styles.rail} aria-label="To do"><div className={styles.head}><h3>To-Do</h3><button type="button" aria-label="To-do settings">⚙</button></div><div className={styles.tabs}>{(["day","week","month"] as Range[]).map(x=><button key={x} type="button" className={range===x?styles.active:""} onClick={()=>setRange(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className={styles.ring} style={{"--pct":`${pct*3.6}deg`} as React.CSSProperties}><div><strong>{pct}%</strong><span>{completed}/{items.length} complete</span></div></div><div className={styles.legend}><span>Assignments</span><span>2006</span></div>{state&&<p className={styles.state}>{state}</p>}{overdue.length>0&&<section><h4><span>{overdue.length}</span> Overdue</h4>{overdue.map(x=><article key={x.id}><i/><div><strong>{x.title}</strong><small>{x.class_sections?.academic_courses?.code??"COURSE"}</small><span>Due {due(x.due_at)} · {x.points} pts</span></div><b>○</b></article>)}</section>}<section><h4>Due {range==="day"?"today":range==="week"?"this week":"this month"}</h4>{upcoming.length?upcoming.map(x=><article key={x.id}><i/><div><strong>{x.title}</strong><small>{x.class_sections?.academic_courses?.code??"COURSE"}</small><span>{x.due_at?`Due ${due(x.due_at)}`:"No due date"} · {x.points} pts</span></div><b>{done.has(x.id)?"✓":"○"}</b></article>):<p className={styles.empty}>You&apos;re caught up.</p>}</section></aside>;
}
