"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Archive={id:string;display_name:string;role:string;archive_reason:string;snapshot:Record<string,unknown>;archived_at:string};
type Continuity={id:string;entry_type:string;title:string;summary:string;payload:Record<string,unknown>;sort_date:string|null;created_at:string};
export default function CharacterArchiveExportPanel({accessToken,characterId}:{accessToken:string;characterId:string}){
 const [archives,setArchives]=useState<Archive[]>([]);const [continuity,setContinuity]=useState<Continuity[]>([]);const [note,setNote]=useState("manual export");const [notice,setNotice]=useState("Loading archives…");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [a,c]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/character_archives?select=id,display_name,role,archive_reason,snapshot,archived_at&character_id=eq.${encodeURIComponent(characterId)}&order=archived_at.desc&limit=20`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/roleplay_continuity_archive?select=id,entry_type,title,summary,payload,sort_date,created_at&order=sort_date.desc.nullslast,created_at.desc&limit=50`,{headers:headers(accessToken)})]);if(a.ok)setArchives(await a.json() as Archive[]);if(c.ok)setContinuity(await c.json() as Continuity[]);setNotice("Archive and continuity tools ready.");},[accessToken,characterId]);useEffect(()=>{void load();},[load]);
 async function createArchive(){if(busy)return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/archive_my_character`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({viewer_character_id:characterId,archive_note:note.trim()||"manual export"})});if(!r.ok)throw new Error("Character archive could not be created.");setNotice("Character snapshot archived. You can download the JSON export below.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Character archive could not be created.");}finally{setBusy(false);}}
 function downloadArchive(row:Archive){const blob=new Blob([JSON.stringify(row.snapshot,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`hanami-${row.display_name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${row.archived_at.slice(0,10)}.json`;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section style={{border:"1px solid #b7c3d0",background:"#f7f9fb",padding:12,display:"grid",gap:12}} aria-label="Character archive and continuity"><div><p className="eyebrow">ARCHIVE & CONTINUITY</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Character Data Export & RP Continuity</h4><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}><article style={{border:"1px solid #cbd4dd",background:"#fff",padding:10}}><h5>My Character Archive</h5><p style={{fontSize:9}}>Creates a private snapshot of this character’s core profile, canvas/widgets, school ID, honors, enrollments, and onboarding state. It does not delete or alter the live character.</p><input value={note} onChange={e=>setNote(e.target.value)} maxLength={200} placeholder="Archive reason" style={{width:"100%",boxSizing:"border-box"}}/><button type="button" disabled={busy} onClick={()=>void createArchive()} style={{marginTop:6}}>{busy?"Archiving…":"Create archive snapshot"}</button>{archives.map(row=><div key={row.id} style={{borderTop:"1px solid #e2e7ec",padding:"7px 0"}}><strong>{new Date(row.archived_at).toLocaleString()}</strong><small style={{display:"block"}}>{row.archive_reason} • {row.role}</small><button type="button" onClick={()=>downloadArchive(row)}>Download JSON export</button></div>)}</article><article style={{border:"1px solid #cbd4dd",background:"#fff",padding:10}}><h5>Roleplay Continuity Archive</h5><p style={{fontSize:9}}>Confirmed session milestones and continuity records published by Administration. These are read-only for Students and Faculty.</p>{continuity.length?continuity.map(row=><details key={row.id} style={{borderTop:"1px solid #e2e7ec",padding:"7px 0"}}><summary><strong>{row.title}</strong> <small>• {row.entry_type.replaceAll("_"," ")}</small></summary><p>{row.summary}</p>{row.sort_date&&<small>{row.sort_date}</small>}</details>):<p>No continuity records have been archived yet.</p>}</article></div></section>;
}
