"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Props={accessToken:string;characterId:string;role:"student"|"faculty"};
type Faculty={character_id:string;display_name:string;handle:string};
type OfficeHour={id:string;faculty_character_id:string;weekday:number;starts_at:string;ends_at:string;location:string|null;note:string};
type OfficeRequest={id:string;student_character_id:string;faculty_character_id:string;requested_for:string|null;reason:string;status:string;staff_note:string;created_at:string};
type Seat={id:string;section_id:string;student_character_id:string;seat_label:string;row_number:number|null;column_number:number|null};
type Roster={student_character_id:string;display_name:string;handle:string;section_id:string;section_code:string;course_code:string;course_title:string};
type Section={id:string;section_code:string};
type Sub={id:string;section_id:string;substitute_character_id:string;starts_at:string;ends_at:string;note:string};
type Honor={id:string;term:string;honor_title:string;description:string;class_rank:number|null;show_rank_publicly:boolean;created_at:string};
type StudentSeatRow={section_id:string;section_code:string;course_code:string;course_title:string;room:string|null;student_character_id:string;display_name:string;handle:string;seat_label:string|null;row_number:number|null;column_number:number|null;is_self:boolean};

const weekdays=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const SEAT_ROWS=5,SEAT_COLS=4;
function seatName(row:number,column:number){return `${String.fromCharCode(64+row)}${column}`;}

export default function ClassroomOperationsPanel({accessToken,characterId,role}:Props){
 const [faculty,setFaculty]=useState<Faculty[]>([]),[officeHours,setOfficeHours]=useState<OfficeHour[]>([]),[requests,setRequests]=useState<OfficeRequest[]>([]),[seats,setSeats]=useState<Seat[]>([]),[roster,setRoster]=useState<Roster[]>([]),[sections,setSections]=useState<Section[]>([]),[subs,setSubs]=useState<Sub[]>([]),[honors,setHonors]=useState<Honor[]>([]),[studentSeatRows,setStudentSeatRows]=useState<StudentSeatRow[]>([]),[notice,setNotice]=useState("Loading classroom operations…");
 const [facultyId,setFacultyId]=useState(""),[requestWhen,setRequestWhen]=useState(""),[requestReason,setRequestReason]=useState("");
 const [officeDay,setOfficeDay]=useState("1"),[officeStart,setOfficeStart]=useState("15:15"),[officeEnd,setOfficeEnd]=useState("16:00"),[officeLocation,setOfficeLocation]=useState(""),[officeNote,setOfficeNote]=useState("");
 const [sectionId,setSectionId]=useState(""),[studentId,setStudentId]=useState(""),[seatLabel,setSeatLabel]=useState(""),[seatRow,setSeatRow]=useState(1),[seatColumn,setSeatColumn]=useState(1),[studentSectionId,setStudentSectionId]=useState("");
 const [subFacultyId,setSubFacultyId]=useState(""),[subStart,setSubStart]=useState(""),[subEnd,setSubEnd]=useState(""),[subNote,setSubNote]=useState("");
 const [overrideTitle,setOverrideTitle]=useState(""),[overrideLabel,setOverrideLabel]=useState(""),[overrideStart,setOverrideStart]=useState(""),[overrideEnd,setOverrideEnd]=useState(""),[overrideReason,setOverrideReason]=useState("");

 const load=useCallback(async()=>{
  const dir=await fetch(`${SUPABASE_URL}/rest/v1/rpc/school_faculty_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});
  if(dir.ok){const rows=await dir.json() as Faculty[];setFaculty(rows);setFacultyId(v=>v||rows[0]?.character_id||"");setSubFacultyId(v=>v||rows[0]?.character_id||"");}
  const [oh,orq]=await Promise.all([
   fetch(`${SUPABASE_URL}/rest/v1/faculty_office_hours?select=id,faculty_character_id,weekday,starts_at,ends_at,location,note&is_active=eq.true&order=weekday,starts_at`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/office_hour_requests?select=id,student_character_id,faculty_character_id,requested_for,reason,status,staff_note,created_at&order=created_at.desc&limit=30`,{headers:headers(accessToken)})
  ]);
  if(oh.ok)setOfficeHours(await oh.json());if(orq.ok)setRequests(await orq.json());

  if(role==="student"){
   const [chart,h]=await Promise.all([
    fetch(`${SUPABASE_URL}/rest/v1/rpc/student_classroom_seating_chart`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:characterId})}),
    fetch(`${SUPABASE_URL}/rest/v1/student_honors?select=id,term,honor_title,description,class_rank,show_rank_publicly,created_at&student_character_id=eq.${characterId}&order=created_at.desc`,{headers:headers(accessToken)})
   ]);
   if(chart.ok){const rows=await chart.json() as StudentSeatRow[];setStudentSeatRows(rows);setStudentSectionId(v=>v||rows[0]?.section_id||"");setSeats(rows.filter(r=>r.is_self&&r.seat_label).map(r=>({id:`self-${r.section_id}`,section_id:r.section_id,student_character_id:r.student_character_id,seat_label:r.seat_label??"",row_number:r.row_number,column_number:r.column_number})));}
   if(h.ok)setHonors(await h.json());
  }else{
   const [membership,rosterResponse]=await Promise.all([
    fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id&character_id=eq.${characterId}&relationship=eq.instructor`,{headers:headers(accessToken)}),
    fetch(`${SUPABASE_URL}/rest/v1/rpc/faculty_student_roster`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({faculty_character_id:characterId})})
   ]);
   const mids=membership.ok?(await membership.json() as {section_id:string}[]).map(x=>x.section_id):[];
   if(rosterResponse.ok)setRoster(await rosterResponse.json() as Roster[]);
   if(mids.length){
    const filter=`(${mids.join(",")})`;
    const [sec,seat,sub]=await Promise.all([
     fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,section_code&id=in.${encodeURIComponent(filter)}`,{headers:headers(accessToken)}),
     fetch(`${SUPABASE_URL}/rest/v1/classroom_seating_assignments?select=id,section_id,student_character_id,seat_label,row_number,column_number&section_id=in.${encodeURIComponent(filter)}`,{headers:headers(accessToken)}),
     fetch(`${SUPABASE_URL}/rest/v1/substitute_teacher_assignments?select=id,section_id,substitute_character_id,starts_at,ends_at,note&section_id=in.${encodeURIComponent(filter)}&order=starts_at.desc`,{headers:headers(accessToken)})
    ]);
    if(sec.ok){const sr=await sec.json() as Section[];setSections(sr);setSectionId(v=>v||sr[0]?.id||"");}
    if(seat.ok)setSeats(await seat.json());if(sub.ok)setSubs(await sub.json());
   }
  }
  setNotice("Classroom operations updated.");
 },[accessToken,characterId,role]);
 useEffect(()=>{void load();},[load]);

 const selectedRoster=useMemo(()=>roster.filter(r=>r.section_id===sectionId),[roster,sectionId]);
 const selectedSeats=useMemo(()=>seats.filter(s=>s.section_id===sectionId),[seats,sectionId]);
 const studentSectionChoices=useMemo(()=>Array.from(new Map(studentSeatRows.map(r=>[r.section_id,{id:r.section_id,section_code:r.section_code,course_code:r.course_code,course_title:r.course_title,room:r.room}])).values()),[studentSeatRows]);
 const studentChartRows=useMemo(()=>studentSeatRows.filter(r=>r.section_id===studentSectionId),[studentSeatRows,studentSectionId]);
 const selectedStudentSection=studentSectionChoices.find(s=>s.id===studentSectionId)??null;
 useEffect(()=>{if(selectedRoster.length&&!selectedRoster.some(r=>r.student_character_id===studentId))setStudentId(selectedRoster[0].student_character_id);},[selectedRoster,studentId]);

 async function requestOffice(){if(!facultyId||requestReason.trim().length<3)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/office_hour_requests`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({student_character_id:characterId,faculty_character_id:facultyId,requested_for:requestWhen?new Date(requestWhen).toISOString():null,reason:requestReason.trim()})});if(r.ok){setRequestReason("");setRequestWhen("");setNotice("Office-hours request submitted.");await load();}}
 async function publishHours(){const r=await fetch(`${SUPABASE_URL}/rest/v1/faculty_office_hours`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({faculty_character_id:characterId,weekday:Number(officeDay),starts_at:officeStart,ends_at:officeEnd,location:officeLocation.trim()||null,note:officeNote.trim()})});if(r.ok){setOfficeLocation("");setOfficeNote("");setNotice("Office hours published.");await load();}}
 async function reviewRequest(id:string,status:"approved"|"declined"){const r=await fetch(`${SUPABASE_URL}/rest/v1/office_hour_requests?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(r.ok){setNotice(`Office-hours request ${status}.`);await load();}}
 function chooseSeat(row:number,column:number){setSeatRow(row);setSeatColumn(column);setSeatLabel(seatName(row,column));}
 async function assignSeat(){if(!sectionId||!studentId)return;const label=seatLabel.trim()||seatName(seatRow,seatColumn);const r=await fetch(`${SUPABASE_URL}/rest/v1/classroom_seating_assignments?on_conflict=section_id,student_character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({section_id:sectionId,student_character_id:studentId,seat_label:label,row_number:seatRow,column_number:seatColumn})});if(r.ok){setSeatLabel("");setNotice(`Seat ${label} saved.`);await load();}else setNotice("That seat may already be assigned to someone else.");}
 async function assignSub(){if(!sectionId||!subFacultyId||!subStart||!subEnd)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/substitute_teacher_assignments`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:sectionId,substitute_character_id:subFacultyId,starts_at:new Date(subStart).toISOString(),ends_at:new Date(subEnd).toISOString(),note:subNote.trim()})});if(r.ok){setSubStart("");setSubEnd("");setSubNote("");setNotice("Temporary substitute assignment published.");await load();}}
 async function createOverride(){if(!overrideTitle.trim()||!overrideLabel.trim()||!overrideStart||!overrideEnd)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/bell_schedule_overrides`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({title:overrideTitle.trim(),status_label:overrideLabel.trim(),starts_at:new Date(overrideStart).toISOString(),ends_at:new Date(overrideEnd).toISOString(),reason:overrideReason.trim()})});if(r.ok){setOverrideTitle("");setOverrideLabel("");setOverrideStart("");setOverrideEnd("");setOverrideReason("");setNotice("Temporary bell override published.");}}

 return <section style={{border:"1px solid #aeb9c5",background:"#fff"}}>
  <div style={{padding:12,background:"#eef3f8",borderBottom:"1px solid #ccd4dc"}}><p className="eyebrow">CLASSROOM OPERATIONS</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>{role==="student"?"Seats, office hours & honors":"Seating, substitutes & office hours"}</h4><small>{notice}</small></div>
  <div style={{padding:12,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:12}}>
   {role==="student"?<>
    <article style={{gridColumn:"1 / -1"}}><h5>My classroom seating charts</h5>{studentSectionChoices.length?<><select value={studentSectionId} onChange={e=>setStudentSectionId(e.target.value)}>{studentSectionChoices.map(s=><option key={s.id} value={s.id}>{s.course_title} • Section {s.section_code}</option>)}</select><p style={{fontSize:10,margin:"6px 0"}}>{selectedStudentSection?.course_code} • {selectedStudentSection?.room??"Room not assigned"}</p><div style={{margin:"10px 0",padding:10,border:"1px solid #ccd4dc",background:"#f8fafc",overflowX:"auto"}}><div style={{textAlign:"center",border:"1px solid #9da9b6",padding:6,marginBottom:10,fontSize:10,fontWeight:700}}>FRONT OF CLASS / BOARD</div><div style={{display:"grid",gridTemplateColumns:`repeat(${SEAT_COLS},minmax(78px,1fr))`,gap:6,minWidth:520}}>{Array.from({length:SEAT_ROWS*SEAT_COLS},(_,index)=>{const row=Math.floor(index/SEAT_COLS)+1,column=index%SEAT_COLS+1,label=seatName(row,column);const assigned=studentChartRows.find(s=>(s.row_number===row&&s.column_number===column)||s.seat_label===label);return <div key={label} style={{minHeight:64,border:assigned?.is_self?"2px solid #8f365b":"1px solid #b8c2cc",background:assigned?.is_self?"#fff0f5":assigned?"#eef3f8":"#fff",padding:6,color:"#17375f"}}><strong>{label}</strong><small style={{display:"block",marginTop:4,whiteSpace:"normal"}}>{assigned?assigned.display_name:"Empty"}</small>{assigned?.is_self&&<b style={{display:"block",marginTop:3,fontSize:8,color:"#8f365b"}}>YOUR SEAT</b>}</div>})}</div></div></>:<p>No seating charts are available for your current classes yet.</p>}</article>
    <article><h5>My seats</h5>{seats.length?seats.map(s=><p key={s.id}><strong>Seat {s.seat_label}</strong>{s.row_number&&s.column_number?<small style={{display:"block"}}>Row {s.row_number} • Column {s.column_number}</small>:null}</p>):<p>No assigned classroom seats yet.</p>}<h5>Honors</h5>{honors.length?honors.map(h=><div key={h.id} style={{padding:7,border:"1px solid #ddd",marginBottom:5}}><strong>{h.honor_title}</strong><div style={{fontSize:9}}>{h.term}</div><p style={{fontSize:9}}>{h.description}</p>{h.class_rank&&<small>Class rank: {h.show_rank_publicly?h.class_rank:"Private"}</small>}</div>):<p>No honors on file.</p>}</article>
    <article><h5>Teacher office hours</h5>{officeHours.map(h=>{const f=faculty.find(x=>x.character_id===h.faculty_character_id);return <div key={h.id} style={{fontSize:9,marginBottom:5}}><b>{f?.display_name??"Faculty"}</b> • {weekdays[h.weekday]} {h.starts_at.slice(0,5)}–{h.ends_at.slice(0,5)}{h.location?` • ${h.location}`:""}</div>})}<select value={facultyId} onChange={e=>setFacultyId(e.target.value)}>{faculty.map(f=><option key={f.character_id} value={f.character_id}>{f.display_name} (@{f.handle})</option>)}</select><input type="datetime-local" value={requestWhen} onChange={e=>setRequestWhen(e.target.value)} style={{display:"block",marginTop:5}}/><textarea value={requestReason} onChange={e=>setRequestReason(e.target.value)} placeholder="Reason for meeting" style={{width:"100%",boxSizing:"border-box",marginTop:5}}/><button type="button" onClick={requestOffice}>Request meeting</button>{requests.filter(r=>r.student_character_id===characterId).slice(0,5).map(r=><p key={r.id} style={{fontSize:9}}><b>{r.status.toUpperCase()}</b> • {r.reason}</p>)}</article>
   </>:<>
    <article style={{gridColumn:"span 2"}}><h5>Visual seating chart</h5><select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{sections.map(s=><option key={s.id} value={s.id}>{s.section_code}</option>)}</select><div style={{margin:"10px 0",padding:10,border:"1px solid #ccd4dc",background:"#f8fafc"}}><div style={{textAlign:"center",border:"1px solid #9da9b6",padding:6,marginBottom:10,fontSize:10,fontWeight:700}}>FRONT OF CLASS / BOARD</div><div style={{display:"grid",gridTemplateColumns:`repeat(${SEAT_COLS},minmax(70px,1fr))`,gap:6,overflowX:"auto"}}>{Array.from({length:SEAT_ROWS*SEAT_COLS},(_,index)=>{const row=Math.floor(index/SEAT_COLS)+1,column=index%SEAT_COLS+1,label=seatName(row,column);const assigned=selectedSeats.find(s=>(s.row_number===row&&s.column_number===column)||s.seat_label===label);const person=assigned?roster.find(r=>r.student_character_id===assigned.student_character_id&&r.section_id===sectionId):null;const active=seatRow===row&&seatColumn===column;return <button type="button" key={label} onClick={()=>chooseSeat(row,column)} style={{minHeight:58,border:active?"2px solid #17375f":"1px solid #b8c2cc",background:assigned?"#eef3f8":"#fff",color:"#17375f",padding:5,textAlign:"left"}}><strong>{label}</strong><small style={{display:"block",marginTop:3,whiteSpace:"normal"}}>{person?.display_name??"Empty"}</small></button>})}</div></div><div style={{display:"grid",gridTemplateColumns:"1fr 90px 90px",gap:6}}><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{selectedRoster.map(r=><option key={r.student_character_id} value={r.student_character_id}>{r.display_name} (@{r.handle})</option>)}</select><input type="number" min={1} max={SEAT_ROWS} value={seatRow} onChange={e=>{const row=Number(e.target.value);setSeatRow(row);setSeatLabel(seatName(row,seatColumn))}} aria-label="Seat row"/><input type="number" min={1} max={SEAT_COLS} value={seatColumn} onChange={e=>{const column=Number(e.target.value);setSeatColumn(column);setSeatLabel(seatName(seatRow,column))}} aria-label="Seat column"/></div><input value={seatLabel} onChange={e=>setSeatLabel(e.target.value)} placeholder={`Seat label, e.g. ${seatName(seatRow,seatColumn)}`} style={{display:"block",marginTop:5,width:"100%",boxSizing:"border-box"}}/><button type="button" onClick={assignSeat}>Assign / update selected seat</button></article>
    <article><h5>Substitute teacher assignment</h5><select value={subFacultyId} onChange={e=>setSubFacultyId(e.target.value)}>{faculty.filter(f=>f.character_id!==characterId).map(f=><option key={f.character_id} value={f.character_id}>{f.display_name}</option>)}</select><label style={{display:"block"}}>Starts <input type="datetime-local" value={subStart} onChange={e=>setSubStart(e.target.value)}/></label><label style={{display:"block"}}>Ends <input type="datetime-local" value={subEnd} onChange={e=>setSubEnd(e.target.value)}/></label><textarea value={subNote} onChange={e=>setSubNote(e.target.value)} placeholder="Optional note" style={{width:"100%",boxSizing:"border-box"}}/><button type="button" onClick={assignSub}>Assign substitute</button>{subs.slice(0,6).map(s=><p key={s.id} style={{fontSize:9}}><b>{sections.find(x=>x.id===s.section_id)?.section_code??"Section"}</b> • {faculty.find(f=>f.character_id===s.substitute_character_id)?.display_name??"Faculty"}</p>)}</article>
    <article><h5>Publish office hours</h5><select value={officeDay} onChange={e=>setOfficeDay(e.target.value)}>{weekdays.map((w,i)=><option key={w} value={i}>{w}</option>)}</select><input type="time" value={officeStart} onChange={e=>setOfficeStart(e.target.value)}/><input type="time" value={officeEnd} onChange={e=>setOfficeEnd(e.target.value)}/><input value={officeLocation} onChange={e=>setOfficeLocation(e.target.value)} placeholder="Location" style={{display:"block",marginTop:5}}/><textarea value={officeNote} onChange={e=>setOfficeNote(e.target.value)} placeholder="Optional note" style={{width:"100%",boxSizing:"border-box"}}/><button type="button" onClick={publishHours}>Publish hours</button><h5>Meeting requests</h5>{requests.filter(r=>r.faculty_character_id===characterId&&r.status==="requested").map(r=><div key={r.id} style={{padding:7,border:"1px solid #ddd",marginBottom:5}}><div style={{fontSize:9}}>{r.reason}</div><button type="button" onClick={()=>reviewRequest(r.id,"approved")}>Approve</button><button type="button" onClick={()=>reviewRequest(r.id,"declined")}>Decline</button></div>)}</article>
    <article><h5>Temporary bell override</h5><input value={overrideTitle} onChange={e=>setOverrideTitle(e.target.value)} placeholder="Event / schedule title" style={{width:"100%",boxSizing:"border-box"}}/><input value={overrideLabel} onChange={e=>setOverrideLabel(e.target.value)} placeholder="Displayed status, e.g. Assembly" style={{width:"100%",boxSizing:"border-box",marginTop:5}}/><label style={{display:"block"}}>Starts <input type="datetime-local" value={overrideStart} onChange={e=>setOverrideStart(e.target.value)}/></label><label style={{display:"block"}}>Ends <input type="datetime-local" value={overrideEnd} onChange={e=>setOverrideEnd(e.target.value)}/></label><textarea value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Reason / event details" style={{width:"100%",boxSizing:"border-box"}}/><button type="button" onClick={createOverride}>Publish temporary override</button></article>
   </>}
  </div>
 </section>;
}