"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Props={accessToken:string;characterId:string;role:"student"|"faculty"};
type Competition={id:string;title:string;competition_type:string;starts_at:string|null;ends_at:string|null;status:string;description:string};
type Point={id:string;competition_id:string;homeroom_id:string;points:number;reason:string;created_at:string};
type Homeroom={id:string;code:string;grade_level:number;school_year:string};
type ExamMode={key:string;enabled:boolean;title:string;starts_on:string|null;ends_on:string|null;temporary_style:string;announcement:string};
type Exam={id:string;section_id:string;student_character_id:string;exam_title:string;exam_at:string;room:string|null;seat_number:string|null;review_materials:string};
type Roster={student_character_id:string;display_name:string;handle:string;section_id:string;section_code:string;course_code:string;course_title:string};
const card:React.CSSProperties={border:"1px solid #ccd5de",background:"#fff",padding:10};
function tokyo(value:string){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));}

export default function ClassCompetitionExamPanel({accessToken,characterId,role}:Props){
 const [competitions,setCompetitions]=useState<Competition[]>([]);const [points,setPoints]=useState<Point[]>([]);const [homerooms,setHomerooms]=useState<Homeroom[]>([]);const [examMode,setExamMode]=useState<ExamMode|null>(null);const [exams,setExams]=useState<Exam[]>([]);const [roster,setRoster]=useState<Roster[]>([]);const [notice,setNotice]=useState("Loading competitions and exam details…");const [busy,setBusy]=useState(false);
 const [competitionId,setCompetitionId]=useState("");const [homeroomId,setHomeroomId]=useState("");const [pointAmount,setPointAmount]=useState("1");const [pointReason,setPointReason]=useState("");
 const [examStudent,setExamStudent]=useState("");const [examSection,setExamSection]=useState("");const [examTitle,setExamTitle]=useState("");const [examAt,setExamAt]=useState("");const [examRoom,setExamRoom]=useState("");const [examSeat,setExamSeat]=useState("");const [reviewMaterials,setReviewMaterials]=useState("");
 const load=useCallback(async()=>{try{const [c,p,h,m]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/class_competitions?select=id,title,competition_type,starts_at,ends_at,status,description&status=neq.archived&order=created_at.desc&limit=30`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/class_competition_points?select=id,competition_id,homeroom_id,points,reason,created_at&order=created_at.desc&limit=200`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/homerooms?select=id,code,grade_level,school_year&is_active=eq.true&order=grade_level,code`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/exam_week_config?select=key,enabled,title,starts_on,ends_on,temporary_style,announcement&key=eq.current&limit=1`,{headers:headers(accessToken)})
 ]);if(c.ok){const rows=await c.json() as Competition[];setCompetitions(rows);setCompetitionId(v=>v||rows[0]?.id||"");}if(p.ok)setPoints(await p.json() as Point[]);if(h.ok){const rows=await h.json() as Homeroom[];setHomerooms(rows);setHomeroomId(v=>v||rows[0]?.id||"");}if(m.ok)setExamMode((await m.json() as ExamMode[])[0]??null);
 if(role==="student"){const e=await fetch(`${SUPABASE_URL}/rest/v1/exam_assignments?select=id,section_id,student_character_id,exam_title,exam_at,room,seat_number,review_materials&student_character_id=eq.${encodeURIComponent(characterId)}&order=exam_at.asc`,{headers:headers(accessToken)});if(e.ok)setExams(await e.json() as Exam[]);}else{const rr=await fetch(`${SUPABASE_URL}/rest/v1/rpc/faculty_student_roster`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({faculty_character_id:characterId})});if(rr.ok){const rows=await rr.json() as Roster[];setRoster(rows);setExamStudent(v=>v||rows[0]?.student_character_id||"");setExamSection(v=>v||rows[0]?.section_id||"");}const sectionIds=[...new Set((rr.ok?await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.instructor`,{headers:headers(accessToken)}).then(r=>r.ok?r.json():[]):[] as unknown) as Array<{section_id:string}>).map(x=>x.section_id)];if(sectionIds.length){const filter=`(${sectionIds.join(",")})`;const e=await fetch(`${SUPABASE_URL}/rest/v1/exam_assignments?select=id,section_id,student_character_id,exam_title,exam_at,room,seat_number,review_materials&section_id=in.${encodeURIComponent(filter)}&order=exam_at.desc&limit=100`,{headers:headers(accessToken)});if(e.ok)setExams(await e.json() as Exam[]);}}
 setNotice("Competitions and Exams Week updated.");}catch(error){setNotice(error instanceof Error?error.message:"Competition or exam data could not be loaded.");}},[accessToken,characterId,role]);
 useEffect(()=>{void load();},[load]);
 const leaderboard=useMemo(()=>competitions.map(comp=>({comp,rows:homerooms.map(h=>({h,total:points.filter(p=>p.competition_id===comp.id&&p.homeroom_id===h.id).reduce((sum,p)=>sum+Number(p.points),0)})).filter(x=>x.total!==0).sort((a,b)=>b.total-a.total)})),[competitions,homerooms,points]);
 async function awardPoints(e:FormEvent){e.preventDefault();if(role!=="faculty"||!competitionId||!homeroomId)return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/class_competition_points`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({competition_id:competitionId,homeroom_id:homeroomId,points:Number(pointAmount),reason:pointReason.trim()})});if(!r.ok)throw new Error("Competition points could not be awarded.");setPointReason("");setNotice("Class competition points awarded.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Competition points could not be awarded.");}finally{setBusy(false);}}
 async function assignExam(e:FormEvent){e.preventDefault();if(role!=="faculty"||!examStudent||!examSection||!examTitle.trim()||!examAt)return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/exam_assignments`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:examSection,student_character_id:examStudent,exam_title:examTitle.trim(),exam_at:new Date(examAt).toISOString(),room:examRoom.trim()||null,seat_number:examSeat.trim()||null,review_materials:reviewMaterials.trim()})});if(!r.ok)throw new Error("Exam assignment could not be published.");setExamTitle("");setExamAt("");setExamRoom("");setExamSeat("");setReviewMaterials("");setNotice("Student exam room, seat, and review materials published.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Exam assignment could not be published.");}finally{setBusy(false);}}
 function chooseRoster(value:string){const item=roster.find(r=>r.student_character_id===value);setExamStudent(value);if(item)setExamSection(item.section_id);}
 return <section style={{border:"1px solid #aeb9c5",background:"#f8fafc"}} aria-label="Class competitions and Exams Week"><div style={{padding:12,background:"#eef3f8",borderBottom:"1px solid #ccd4dc"}}><p className="eyebrow">COMPETITIONS & EXAMS WEEK</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>{role==="student"?"Class standings & my exams":"Class points & exam assignments"}</h4><small>{notice}</small></div><div style={{padding:12,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:12}}>
 <article style={card}><h5>Class Competitions</h5>{leaderboard.length?leaderboard.map(({comp,rows})=><div key={comp.id} style={{marginBottom:10}}><strong>{comp.title}</strong><small style={{display:"block"}}>{comp.competition_type.replaceAll("_"," ")} • {comp.status}</small>{comp.description&&<p style={{fontSize:9}}>{comp.description}</p>}{rows.length?rows.map((row,index)=><div key={row.h.id} style={{display:"flex",justifyContent:"space-between",fontSize:9,padding:"3px 0"}}><span>{index+1}. {row.h.code}</span><b>{row.total} pts</b></div>):<small>No points posted yet.</small>}</div>):<p>No class competitions are active.</p>}{role==="faculty"&&<form onSubmit={awardPoints} style={{display:"grid",gap:5,borderTop:"1px solid #dde3e8",paddingTop:8}}><select value={competitionId} onChange={e=>setCompetitionId(e.target.value)}>{competitions.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select value={homeroomId} onChange={e=>setHomeroomId(e.target.value)}>{homerooms.map(h=><option key={h.id} value={h.id}>{h.code} • Year {h.grade_level}</option>)}</select><input type="number" value={pointAmount} onChange={e=>setPointAmount(e.target.value)} min="-100" max="100"/><input value={pointReason} onChange={e=>setPointReason(e.target.value)} placeholder="Sports day, academics, cleanup, etc."/><button disabled={busy||!competitionId}>Award points</button></form>}</article>
 <article style={card}><h5>{examMode?.title??"Exams Week"}</h5>{examMode?.enabled?<><strong>EXAMS WEEK MODE ACTIVE</strong><small style={{display:"block"}}>{examMode.starts_on??"TBA"} – {examMode.ends_on??"TBA"}</small>{examMode.announcement&&<p>{examMode.announcement}</p>}</>:<p>Exams Week mode is not active.</p>}{role==="student"?<div>{exams.length?exams.map(exam=><div key={exam.id} style={{borderTop:"1px solid #e1e6eb",padding:"8px 0"}}><strong>{exam.exam_title}</strong><small style={{display:"block"}}>{tokyo(exam.exam_at)}{exam.room?` • Room ${exam.room}`:""}{exam.seat_number?` • Seat ${exam.seat_number}`:""}</small>{exam.review_materials&&<p style={{fontSize:9}}><b>Review materials:</b> {exam.review_materials}</p>}</div>):<p>No exam assignments are published for this character.</p>}</div>:<form onSubmit={assignExam} style={{display:"grid",gap:5}}><select value={examStudent} onChange={e=>chooseRoster(e.target.value)}>{roster.map(r=><option key={`${r.section_id}-${r.student_character_id}`} value={r.student_character_id}>{r.display_name} • {r.course_code} {r.section_code}</option>)}</select><input value={examTitle} onChange={e=>setExamTitle(e.target.value)} placeholder="Exam title" required/><input type="datetime-local" value={examAt} onChange={e=>setExamAt(e.target.value)} required/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:5}}><input value={examRoom} onChange={e=>setExamRoom(e.target.value)} placeholder="Exam room"/><input value={examSeat} onChange={e=>setExamSeat(e.target.value)} placeholder="Seat number"/></div><textarea value={reviewMaterials} onChange={e=>setReviewMaterials(e.target.value)} placeholder="Review materials / study notes" rows={3}/><button disabled={busy||!roster.length}>Publish exam assignment</button></form>}</article>
 </div></section>;
}
