"use client";

import {ChangeEvent,FormEvent,useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Tab="forums"|"bulletins"|"study"|"newspaper"|"gallery";
type Board={id:string;name:string;description:string;audience:string};type Thread={id:string;board_id:string;title:string;created_at:string};type Post={id:string;thread_id:string;body:string;created_at:string};
type Bulletin={id:string;board:string;title:string;body:string;created_at:string};type Group={id:string;name:string;subject:string;meeting_location:string|null;meeting_schedule:string|null;member_limit:number;conversation_id:string|null;status:string};
type Article={id:string;headline:string;dek:string;section:string;body:string;published_at:string|null};type Gallery={id:string;title:string;description:string;event_type:string;rp_year:number};type Photo={id:string;gallery_id:string;storage_path:string;caption:string;moderation_status:string};
export default function CommunityCenterPanel({accessToken,characterId,role}:{accessToken:string;characterId:string;role:"student"|"faculty"}){
 const [tab,setTab]=useState<Tab>("forums");const [notice,setNotice]=useState("Loading Community Center…");const [boards,setBoards]=useState<Board[]>([]);const [threads,setThreads]=useState<Thread[]>([]);const [posts,setPosts]=useState<Post[]>([]);const [bulletins,setBulletins]=useState<Bulletin[]>([]);const [groups,setGroups]=useState<Group[]>([]);const [articles,setArticles]=useState<Article[]>([]);const [galleries,setGalleries]=useState<Gallery[]>([]);const [photos,setPhotos]=useState<Photo[]>([]);const [selectedBoard,setSelectedBoard]=useState("");const [selectedThread,setSelectedThread]=useState("");const [threadTitle,setThreadTitle]=useState("");const [reply,setReply]=useState("");const [bulletinBoard,setBulletinBoard]=useState("general");const [bulletinTitle,setBulletinTitle]=useState("");const [bulletinBody,setBulletinBody]=useState("");const [groupName,setGroupName]=useState("");const [groupSubject,setGroupSubject]=useState("");const [groupSchedule,setGroupSchedule]=useState("");const [groupLocation,setGroupLocation]=useState("");const [inviteHandles,setInviteHandles]=useState("");const [selectedGallery,setSelectedGallery]=useState("");const [caption,setCaption]=useState("");
 const load=useCallback(async()=>{const req=(path:string)=>fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:headers(accessToken)});const [b,t,bu,g,a,ga,p]=await Promise.all([req("forum_boards?select=id,name,description,audience&order=sort_order.asc"),req("forum_threads?select=id,board_id,title,created_at&status=eq.published&order=created_at.desc&limit=60"),req("bulletin_posts?select=id,board,title,body,created_at&status=eq.published&order=pinned.desc,created_at.desc&limit=60"),req("study_groups?select=id,name,subject,meeting_location,meeting_schedule,member_limit,conversation_id,status&order=created_at.desc&limit=60"),req("newspaper_articles?select=id,headline,dek,section,body,published_at&status=eq.published&order=published_at.desc&limit=40"),req("photo_galleries?select=id,title,description,event_type,rp_year&status=eq.published&order=rp_year.desc,created_at.desc"),req("photo_gallery_items?select=id,gallery_id,storage_path,caption,moderation_status&moderation_status=eq.approved&order=created_at.desc&limit=100")]);if(b.ok){const rows=await b.json();setBoards(rows);if(!selectedBoard&&rows[0])setSelectedBoard(rows[0].id);}if(t.ok)setThreads(await t.json());if(bu.ok)setBulletins(await bu.json());if(g.ok)setGroups(await g.json());if(a.ok)setArticles(await a.json());if(ga.ok){const rows=await ga.json();setGalleries(rows);if(!selectedGallery&&rows[0])setSelectedGallery(rows[0].id);}if(p.ok)setPhotos(await p.json());setNotice("Community Center is live.");},[accessToken,selectedBoard,selectedGallery]);
 useEffect(()=>{load().catch(()=>setNotice("Community Center could not be loaded."));},[load]);
 useEffect(()=>{if(!selectedThread){setPosts([]);return;}fetch(`${SUPABASE_URL}/rest/v1/forum_posts?select=id,thread_id,body,created_at&thread_id=eq.${selectedThread}&status=eq.published&order=created_at.asc`,{headers:headers(accessToken)}).then(async r=>{if(r.ok)setPosts(await r.json());});},[accessToken,selectedThread]);
 async function createThread(e:FormEvent){e.preventDefault();if(!selectedBoard||!threadTitle.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/forum_threads`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify({board_id:selectedBoard,author_character_id:characterId,title:threadTitle.trim()})});if(r.ok){setThreadTitle("");setNotice("Forum thread created.");await load();}else setNotice("Forum thread could not be created.");}
 async function createReply(e:FormEvent){e.preventDefault();if(!selectedThread||!reply.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/forum_posts`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({thread_id:selectedThread,author_character_id:characterId,body:reply.trim()})});if(r.ok){setReply("");const p=await fetch(`${SUPABASE_URL}/rest/v1/forum_posts?select=id,thread_id,body,created_at&thread_id=eq.${selectedThread}&status=eq.published&order=created_at.asc`,{headers:headers(accessToken)});if(p.ok)setPosts(await p.json());}else setNotice("Reply could not be posted.");}
 async function createBulletin(e:FormEvent){e.preventDefault();const r=await fetch(`${SUPABASE_URL}/rest/v1/bulletin_posts`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({board:bulletinBoard,author_character_id:characterId,title:bulletinTitle.trim(),body:bulletinBody.trim(),audience:"all"})});if(r.ok){setBulletinTitle("");setBulletinBody("");setNotice("Bulletin posted.");await load();}else setNotice("Bulletin could not be posted.");}
 async function createStudyGroup(e:FormEvent){e.preventDefault();if(role!=="student")return;const handles=inviteHandles.split(",").map(v=>v.trim()).filter(Boolean);if(!handles.length){setNotice("Study groups need at least one invited Hanami handle so a group chat can be created.");return;}const chat=await fetch(`${SUPABASE_URL}/rest/v1/rpc/start_group_conversation`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({sender_character_id:characterId,conversation_title:`Study Group • ${groupName.trim()}`,target_handles:handles})});if(!chat.ok){setNotice("Study group chat could not be created. Check the invited handles.");return;}const conversationId=await chat.json();const r=await fetch(`${SUPABASE_URL}/rest/v1/study_groups`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify({creator_character_id:characterId,name:groupName.trim(),subject:groupSubject.trim(),meeting_schedule:groupSchedule.trim()||null,meeting_location:groupLocation.trim()||null,conversation_id:conversationId})});if(!r.ok){setNotice("Study group record could not be created.");return;}const row=(await r.json())[0];await fetch(`${SUPABASE_URL}/rest/v1/study_group_members`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({group_id:row.id,character_id:characterId,role:"leader"})});setGroupName("");setGroupSubject("");setGroupSchedule("");setGroupLocation("");setInviteHandles("");setNotice("Study group and Hanami group chat created.");await load();}
 async function joinGroup(id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/study_group_members`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({group_id:id,character_id:characterId,role:"member"})});setNotice(r.ok?"Joined study group.":"Could not join this study group (it may be full or you may already be a member).");}
 async function uploadGalleryPhoto(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file||!selectedGallery)return;if(!["image/jpeg","image/png","image/gif","image/webp"].includes(file.type)||file.size>8*1024*1024){setNotice("Gallery uploads must be JPEG/PNG/GIF/WebP and 8 MB or smaller.");return;}const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1];const path=`${characterId}/${crypto.randomUUID()}.${ext}`;const up=await fetch(`${SUPABASE_URL}/storage/v1/object/gallery-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":file.type}),body:file});if(!up.ok){setNotice("Photo upload failed.");return;}const row=await fetch(`${SUPABASE_URL}/rest/v1/photo_gallery_items`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({gallery_id:selectedGallery,submitted_by_character_id:characterId,storage_path:path,caption:caption.trim()})});setNotice(row.ok?"Photo submitted for moderation.":"Photo uploaded but could not be submitted to the gallery.");if(row.ok)setCaption("");}
 const tabs:Tab[]=["forums","bulletins","study","newspaper","gallery"];
 return <section style={{marginTop:16,border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:"12px 14px",background:"#f8e9f1",borderBottom:"1px solid #d8b7c5"}}><p className="eyebrow">HANAMI COMMUNITY</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Community Center</h4><small>{notice}</small></div><nav style={{display:"flex",gap:5,flexWrap:"wrap",padding:10,background:"#eef3f8"}}>{tabs.map(x=><button key={x} type="button" onClick={()=>setTab(x)} style={{fontWeight:tab===x?700:400}}>{x.replace("study","study groups")}</button>)}</nav>
 {tab==="forums"&&<div style={{padding:14,display:"grid",gap:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}>{boards.map(b=><button key={b.id} type="button" onClick={()=>{setSelectedBoard(b.id);setSelectedThread("")}} style={{padding:10,textAlign:"left",border:selectedBoard===b.id?"2px solid #17375f":"1px solid #bcc7d2",background:"#fff"}}><strong>{b.name}</strong><small style={{display:"block",marginTop:4}}>{b.description} • {b.audience}</small></button>)}</div><form onSubmit={createThread} style={{display:"flex",gap:6}}><input style={{flex:1}} value={threadTitle} onChange={e=>setThreadTitle(e.target.value)} placeholder="Start a new discussion…"/><button>Create thread</button></form><div style={{display:"grid",gridTemplateColumns:"minmax(220px,.7fr) minmax(280px,1.3fr)",gap:12}}><div>{threads.filter(t=>!selectedBoard||t.board_id===selectedBoard).map(t=><button key={t.id} type="button" onClick={()=>setSelectedThread(t.id)} style={{display:"block",width:"100%",textAlign:"left",padding:9,marginBottom:5}}>{t.title}</button>)}</div><div>{selectedThread?<><div style={{display:"grid",gap:6}}>{posts.map(p=><article key={p.id} style={{padding:9,border:"1px solid #d2d8df"}}><p style={{margin:0}}>{p.body}</p><small>{new Date(p.created_at).toLocaleString()}</small></article>)}</div><form onSubmit={createReply} style={{marginTop:8,display:"grid",gap:5}}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…"/><button>Post reply</button></form></>:<p>Select a thread to read the discussion.</p>}</div></div></div>}
 {tab==="bulletins"&&<div style={{padding:14,display:"grid",gap:12}}><form onSubmit={createBulletin} style={{display:"grid",gap:6}}><select value={bulletinBoard} onChange={e=>setBulletinBoard(e.target.value)}><option value="student_council">Student Council</option><option value="clubs">Clubs</option><option value="academics">Academics</option><option value="events">Events</option><option value="study_groups">Study Groups</option><option value="general">General School Life</option></select><input value={bulletinTitle} onChange={e=>setBulletinTitle(e.target.value)} placeholder="Bulletin title" required/><textarea value={bulletinBody} onChange={e=>setBulletinBody(e.target.value)} placeholder="Post details" required/><button>Post bulletin</button></form>{bulletins.map(b=><article key={b.id} style={{padding:10,border:"1px solid #d1d8df"}}><small>{b.board.replaceAll("_"," ").toUpperCase()}</small><h5 style={{margin:"4px 0"}}>{b.title}</h5><p>{b.body}</p></article>)}</div>}
 {tab==="study"&&<div style={{padding:14,display:"grid",gap:12}}>{role==="student"&&<form onSubmit={createStudyGroup} style={{display:"grid",gap:6}}><input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Study group name" required/><input value={groupSubject} onChange={e=>setGroupSubject(e.target.value)} placeholder="Subject / course"/><input value={groupSchedule} onChange={e=>setGroupSchedule(e.target.value)} placeholder="Meeting schedule"/><input value={groupLocation} onChange={e=>setGroupLocation(e.target.value)} placeholder="Meeting location"/><input value={inviteHandles} onChange={e=>setInviteHandles(e.target.value)} placeholder="Invite Hanami handles, comma separated" required/><button>Create study group + chat</button></form>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:8}}>{groups.map(g=><article key={g.id} style={{padding:10,border:"1px solid #d1d8df"}}><strong>{g.name}</strong><div>{g.subject||"General study"}</div><small>{g.meeting_schedule||"Schedule TBD"} • {g.meeting_location||"Location TBD"} • limit {g.member_limit}</small>{role==="student"&&<button type="button" onClick={()=>joinGroup(g.id)} style={{display:"block",marginTop:7}}>Join group</button>}{g.conversation_id&&<small style={{display:"block",marginTop:5}}>Hanami group chat attached</small>}</article>)}</div></div>}
 {tab==="newspaper"&&<div style={{padding:14,display:"grid",gap:10}}>{articles.length?articles.map(a=><article key={a.id} style={{padding:12,borderBottom:"1px dotted #c3ccd6"}}><small>{a.section.toUpperCase()}</small><h4 style={{margin:"4px 0"}}>{a.headline}</h4>{a.dek&&<strong>{a.dek}</strong>}<p style={{whiteSpace:"pre-wrap"}}>{a.body}</p></article>):<p>No published newspaper articles yet. Approved student editors can submit the first issue.</p>}</div>}
 {tab==="gallery"&&<div style={{padding:14,display:"grid",gap:12}}><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{galleries.map(g=><button key={g.id} type="button" onClick={()=>setSelectedGallery(g.id)}>{g.title} • {g.rp_year}</button>)}</div>{selectedGallery&&<div style={{padding:10,border:"1px dashed #aab7c6"}}><strong>Submit a photo for moderation</strong><input style={{display:"block",marginTop:6,width:"100%"}} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Caption"/><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadGalleryPhoto} style={{marginTop:6}}/></div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}>{photos.filter(p=>!selectedGallery||p.gallery_id===selectedGallery).map(p=><article key={p.id} style={{padding:10,border:"1px solid #d1d8df"}}><strong>{p.caption||"Hanami event photo"}</strong><small style={{display:"block",overflow:"hidden",textOverflow:"ellipsis"}}>{p.storage_path}</small></article>)}</div></div>}
 </section>;
}
