"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./CommunityBoardsPanel.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type Confession={id:string;author_character_id:string|null;body:string;status:string;is_anonymous:boolean;created_at:string;moderator_note:string|null};
type Group={id:string;creator_character_id:string;name:string;description:string;subject:string;meeting_location:string|null;meeting_schedule:string|null;member_limit:number;status:string;created_at:string};
type Member={group_id:string;character_id:string;role:string;joined_at:string};
type Character={id:string;display_name:string};
function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}
async function get<T>(t:string,path:string){const r=await fetch(`${U}/rest/v1/${path}`,{headers:h(t)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<T>}
async function write(t:string,path:string,method:string,body?:unknown){const r=await fetch(`${U}/rest/v1/${path}`,{method,headers:h(t,{"Content-Type":"application/json",Prefer:"return=minimal"}),body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());}
export default function CommunityBoardsPanel({accessToken,characterId}:Props){
 const [tab,setTab]=useState<"confessions"|"study">("confessions"),[message,setMessage]=useState("Loading community boards…"),[confessions,setConfessions]=useState<Confession[]>([]),[groups,setGroups]=useState<Group[]>([]),[members,setMembers]=useState<Member[]>([]),[characters,setCharacters]=useState<Character[]>([]);
 const [confession,setConfession]=useState({body:"",anonymous:true});const [draft,setDraft]=useState({name:"",subject:"",description:"",location:"",schedule:"",limit:8});
 const names=useMemo(()=>new Map(characters.map(c=>[c.id,c.display_name])),[characters]);const counts=useMemo(()=>{const m=new Map<string,number>();for(const row of members)m.set(row.group_id,(m.get(row.group_id)??0)+1);return m},[members]);
 async function load(){try{const [c,g,m,ch]=await Promise.all([get<Confession[]>(accessToken,"school_confessions?select=id,author_character_id,body,status,is_anonymous,created_at,moderator_note&order=created_at.desc&limit=60"),get<Group[]>(accessToken,"study_groups?select=id,creator_character_id,name,description,subject,meeting_location,meeting_schedule,member_limit,status,created_at&status=eq.open&order=created_at.desc&limit=60"),get<Member[]>(accessToken,"study_group_members?select=group_id,character_id,role,joined_at"),get<Character[]>(accessToken,"characters?select=id,display_name&role=eq.student")]);setConfessions(c);setGroups(g);setMembers(m);setCharacters(ch);setMessage("Community boards ready.")}catch(e){setMessage(e instanceof Error?e.message:"Community boards could not be loaded.")}}
 useEffect(()=>{void load()},[accessToken,characterId]);
 async function submitConfession(e:FormEvent){e.preventDefault();if(confession.body.trim().length<3)return;try{await write(accessToken,"school_confessions","POST",{author_character_id:confession.anonymous?null:characterId,body:confession.body.trim(),status:"pending",is_anonymous:confession.anonymous});setConfession({body:"",anonymous:true});await load();setMessage("Confession submitted for moderation. It will not appear publicly until approved.")}catch(e){setMessage(e instanceof Error?e.message:"Confession could not be submitted.")}}
 async function createGroup(e:FormEvent){e.preventDefault();if(!draft.name.trim()||!draft.subject.trim())return;try{const r=await fetch(`${U}/rest/v1/study_groups`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({creator_character_id:characterId,name:draft.name.trim(),description:draft.description.trim(),subject:draft.subject.trim(),meeting_location:draft.location.trim()||null,meeting_schedule:draft.schedule.trim()||null,member_limit:draft.limit,status:"open"})});if(!r.ok)throw new Error(await r.text());const rows=await r.json() as Group[];if(rows[0])await write(accessToken,"study_group_members","POST",{group_id:rows[0].id,character_id:characterId,role:"leader"});setDraft({name:"",subject:"",description:"",location:"",schedule:"",limit:8});await load();setMessage("Study group created and added to the finder.")}catch(e){setMessage(e instanceof Error?e.message:"Study group could not be created.")}}
 async function toggleGroup(group:Group){const mine=members.find(m=>m.group_id===group.id&&m.character_id===characterId);try{if(mine)await write(accessToken,`study_group_members?group_id=eq.${group.id}&character_id=eq.${characterId}`,"DELETE");else await write(accessToken,"study_group_members","POST",{group_id:group.id,character_id:characterId,role:"member"});await load();setMessage(mine?"You left the study group.":"You joined the study group.")}catch(e){setMessage(e instanceof Error?e.message:"Study group membership could not be changed.")}}
 const approved=confessions.filter(c=>c.status==="approved");const ownPending=confessions.filter(c=>c.status!=="approved"&&c.author_character_id===characterId);
 return <section className={styles.panel}><header><div><p className="eyebrow">COMMUNITY BOARDS</p><h3>Confessions & study groups</h3><p>Moderated schoolwide roleplay posts and practical student study-group discovery.</p></div><span>{message}</span></header><nav><button className={tab==="confessions"?styles.active:""} onClick={()=>setTab("confessions")}>Confession Board</button><button className={tab==="study"?styles.active:""} onClick={()=>setTab("study")}>Study-Group Finder</button></nav>
 {tab==="confessions"&&<div className={styles.split}><form onSubmit={submitConfession}><h4>Submit a confession</h4><p>Every submission is moderated before becoming visible to the school.</p><textarea rows={7} maxLength={1500} value={confession.body} onChange={e=>setConfession({...confession,body:e.target.value})} placeholder="Write a school confession…" required/><label><input type="checkbox" checked={confession.anonymous} onChange={e=>setConfession({...confession,anonymous:e.target.checked})}/> Submit anonymously</label><button>Send for moderation</button>{ownPending.length>0&&<small>{ownPending.length} non-anonymous submission{ownPending.length===1?" is":"s are"} awaiting/reviewing moderation.</small>}</form><div className={styles.stack}>{approved.length?approved.map(c=><article key={c.id}><small>{c.is_anonymous?"ANONYMOUS CONFESSION":names.get(c.author_character_id??"")??"HANAMI STUDENT"}</small><p>{c.body}</p><span>{new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(c.created_at))} JST</span></article>):<article>No approved confessions yet.</article>}</div></div>}
 {tab==="study"&&<div className={styles.split}><form onSubmit={createGroup}><h4>Create a study group</h4><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Group name" required/><input value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})} placeholder="Subject" required/><textarea rows={4} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="What will the group work on?"/><input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="Meeting location"/><input value={draft.schedule} onChange={e=>setDraft({...draft,schedule:e.target.value})} placeholder="Availability / meeting schedule"/><label>Member limit <input type="number" min={2} max={30} value={draft.limit} onChange={e=>setDraft({...draft,limit:Number(e.target.value)})}/></label><button>Create study group</button></form><div className={styles.stack}>{groups.length?groups.map(g=>{const mine=members.some(m=>m.group_id===g.id&&m.character_id===characterId);const count=counts.get(g.id)??0;return <article key={g.id}><div className={styles.row}><div><small>{g.subject.toUpperCase()}</small><h4>{g.name}</h4></div><b>{count}/{g.member_limit}</b></div><p>{g.description||"No description provided."}</p><span>{g.meeting_location||"Location TBA"}{g.meeting_schedule?` • ${g.meeting_schedule}`:""}</span><small>Created by {names.get(g.creator_character_id)??"Hanami Student"}</small><button disabled={!mine&&count>=g.member_limit} onClick={()=>toggleGroup(g)}>{mine?"Leave group":count>=g.member_limit?"Group full":"Join group"}</button></article>}):<article>No open study groups yet.</article>}</div></div>}
 </section>;
}
