"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./CommunityBoardsPanel.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type Tab="polls"|"lost"|"classifieds"|"suggestions"|"confessions"|"study"|"events"|"help";
type Poll={id:string;question:string;description:string|null;status:string;opens_at:string|null;closes_at:string|null};
type PollOption={id:string;poll_id:string;label:string;sort_order:number;vote_count:number};
type PollVote={poll_id:string;option_id:string;character_id:string};
type LostPost={id:string;character_id:string|null;post_type:"lost"|"found";title:string;description:string;location:string|null;roleplay_date:string|null;status:string;created_at:string};
type RequestPost={id:string;character_id:string;request_type:string;title:string;body:string;visibility:string;status:string;created_at:string};
type Confession={id:string;author_character_id:string|null;body:string;status:string;is_anonymous:boolean;created_at:string;moderator_note:string|null};
type Group={id:string;creator_character_id:string;name:string;description:string;subject:string;meeting_location:string|null;meeting_schedule:string|null;member_limit:number;status:string;created_at:string};
type Member={group_id:string;character_id:string;role:string;joined_at:string};
type Character={id:string;display_name:string};

function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}
async function get<T>(t:string,path:string){const r=await fetch(`${U}/rest/v1/${path}`,{headers:h(t)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<T>}
async function write(t:string,path:string,method:string,body?:unknown,prefer="return=minimal"){const r=await fetch(`${U}/rest/v1/${path}`,{method,headers:h(t,{"Content-Type":"application/json",Prefer:prefer}),body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r;}
function nice(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function stamp(v:string){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v))}

export default function CommunityBoardsPanel({accessToken,characterId}:Props){
 const [tab,setTab]=useState<Tab>("polls"),[message,setMessage]=useState("Loading community network…");
 const [polls,setPolls]=useState<Poll[]>([]),[options,setOptions]=useState<PollOption[]>([]),[votes,setVotes]=useState<PollVote[]>([]);
 const [lostPosts,setLostPosts]=useState<LostPost[]>([]),[requests,setRequests]=useState<RequestPost[]>([]);
 const [confessions,setConfessions]=useState<Confession[]>([]),[groups,setGroups]=useState<Group[]>([]),[members,setMembers]=useState<Member[]>([]),[characters,setCharacters]=useState<Character[]>([]);
 const [lostDraft,setLostDraft]=useState({post_type:"lost" as "lost"|"found",title:"",description:"",location:"",date:""});
 const [requestDraft,setRequestDraft]=useState({request_type:"study_partner",title:"",body:"",visibility:"school"});
 const [suggestion,setSuggestion]=useState({category:"general",message:""});
 const [confession,setConfession]=useState({body:"",anonymous:true});
 const [groupDraft,setGroupDraft]=useState({name:"",subject:"",description:"",location:"",schedule:"",limit:8});
 const names=useMemo(()=>new Map(characters.map(c=>[c.id,c.display_name])),[characters]);
 const counts=useMemo(()=>{const m=new Map<string,number>();for(const row of members)m.set(row.group_id,(m.get(row.group_id)??0)+1);return m},[members]);

 async function load(){
  try{
   const [p,o,v,l,r,c,g,m,ch]=await Promise.all([
    get<Poll[]>(accessToken,"school_polls?select=id,question,description,status,opens_at,closes_at&status=in.(published,closed)&order=created_at.desc&limit=20"),
    get<PollOption[]>(accessToken,"school_poll_options?select=id,poll_id,label,sort_order,vote_count&order=sort_order.asc"),
    get<PollVote[]>(accessToken,`school_poll_votes?select=poll_id,option_id,character_id&character_id=eq.${characterId}`),
    get<LostPost[]>(accessToken,"lost_found_posts?select=id,character_id,post_type,title,description,location,roleplay_date,status,created_at&status=in.(open,matched)&order=created_at.desc&limit=80"),
    get<RequestPost[]>(accessToken,"student_request_board?select=id,character_id,request_type,title,body,visibility,status,created_at&status=eq.open&order=created_at.desc&limit=80"),
    get<Confession[]>(accessToken,"school_confessions?select=id,author_character_id,body,status,is_anonymous,created_at,moderator_note&order=created_at.desc&limit=60"),
    get<Group[]>(accessToken,"study_groups?select=id,creator_character_id,name,description,subject,meeting_location,meeting_schedule,member_limit,status,created_at&status=eq.open&order=created_at.desc&limit=60"),
    get<Member[]>(accessToken,"study_group_members?select=group_id,character_id,role,joined_at"),
    get<Character[]>(accessToken,"characters?select=id,display_name&role=eq.student")
   ]);
   setPolls(p);setOptions(o);setVotes(v);setLostPosts(l);setRequests(r);setConfessions(c);setGroups(g);setMembers(m);setCharacters(ch);setMessage("Community network ready.");
  }catch(e){setMessage(e instanceof Error?e.message:"Community network could not be loaded.")}
 }
 useEffect(()=>{void load()},[accessToken,characterId]);

 async function vote(poll:Poll,optionId:string){if(votes.some(v=>v.poll_id===poll.id))return;try{await write(accessToken,"school_poll_votes","POST",{poll_id:poll.id,option_id:optionId,character_id:characterId});await load();setMessage("Vote recorded. Each character gets one vote per poll.")}catch(e){setMessage(e instanceof Error?e.message:"Vote could not be recorded.")}}
 async function submitLost(e:FormEvent){e.preventDefault();if(!lostDraft.title.trim()||!lostDraft.description.trim())return;try{await write(accessToken,"lost_found_posts","POST",{character_id:characterId,post_type:lostDraft.post_type,title:lostDraft.title.trim(),description:lostDraft.description.trim(),location:lostDraft.location.trim()||null,roleplay_date:lostDraft.date||null,status:"open"});setLostDraft({post_type:"lost",title:"",description:"",location:"",date:""});await load();setMessage("Lost & Found post published to the school board.")}catch(e){setMessage(e instanceof Error?e.message:"Lost & Found post could not be saved.")}}
 async function closeLost(post:LostPost){try{await write(accessToken,`lost_found_posts?id=eq.${post.id}`,"PATCH",{status:post.post_type==="lost"?"returned":"closed",updated_at:new Date().toISOString()});await load();setMessage("Lost & Found post closed.")}catch(e){setMessage(e instanceof Error?e.message:"Post could not be closed.")}}
 async function submitRequest(e:FormEvent){e.preventDefault();if(!requestDraft.title.trim()||!requestDraft.body.trim())return;try{await write(accessToken,"student_request_board","POST",{character_id:characterId,request_type:requestDraft.request_type,title:requestDraft.title.trim(),body:requestDraft.body.trim(),visibility:requestDraft.visibility,status:"open"});setRequestDraft({request_type:"study_partner",title:"",body:"",visibility:"school"});await load();setMessage("Classified posted to the student bulletin board.")}catch(e){setMessage(e instanceof Error?e.message:"Classified could not be posted.")}}
 async function closeRequest(post:RequestPost){try{await write(accessToken,`student_request_board?id=eq.${post.id}`,"PATCH",{status:"closed",updated_at:new Date().toISOString()});await load();setMessage("Classified closed.")}catch(e){setMessage(e instanceof Error?e.message:"Classified could not be closed.")}}
 async function submitSuggestion(e:FormEvent){e.preventDefault();if(suggestion.message.trim().length<5)return;try{await write(accessToken,"anonymous_school_suggestions","POST",{category:suggestion.category,message:suggestion.message.trim(),status:"new"});setSuggestion({category:"general",message:""});setMessage("Suggestion delivered anonymously to the Owner review queue. No character ID is stored with the submission.")}catch(e){setMessage(e instanceof Error?e.message:"Suggestion could not be delivered.")}}
 async function submitConfession(e:FormEvent){e.preventDefault();if(confession.body.trim().length<3)return;try{await write(accessToken,"school_confessions","POST",{author_character_id:confession.anonymous?null:characterId,body:confession.body.trim(),status:"pending",is_anonymous:confession.anonymous});setConfession({body:"",anonymous:true});await load();setMessage("Confession submitted for moderation.")}catch(e){setMessage(e instanceof Error?e.message:"Confession could not be submitted.")}}
 async function createGroup(e:FormEvent){e.preventDefault();if(!groupDraft.name.trim()||!groupDraft.subject.trim())return;try{const r=await write(accessToken,"study_groups","POST",{creator_character_id:characterId,name:groupDraft.name.trim(),description:groupDraft.description.trim(),subject:groupDraft.subject.trim(),meeting_location:groupDraft.location.trim()||null,meeting_schedule:groupDraft.schedule.trim()||null,member_limit:groupDraft.limit,status:"open"},"return=representation");const rows=await r.json() as Group[];if(rows[0])await write(accessToken,"study_group_members","POST",{group_id:rows[0].id,character_id:characterId,role:"leader"});setGroupDraft({name:"",subject:"",description:"",location:"",schedule:"",limit:8});await load();setMessage("Study group created.")}catch(e){setMessage(e instanceof Error?e.message:"Study group could not be created.")}}
 async function toggleGroup(group:Group){const mine=members.find(m=>m.group_id===group.id&&m.character_id===characterId);try{if(mine)await write(accessToken,`study_group_members?group_id=eq.${group.id}&character_id=eq.${characterId}`,"DELETE");else await write(accessToken,"study_group_members","POST",{group_id:group.id,character_id:characterId,role:"member"});await load();setMessage(mine?"You left the study group.":"You joined the study group.")}catch(e){setMessage(e instanceof Error?e.message:"Study group membership could not be changed.")}}
 function route(view:string,subView:string){window.dispatchEvent(new CustomEvent("hanami-portal-command",{detail:{view,subView}}))}

 const approved=confessions.filter(c=>c.status==="approved");
 const ownPending=confessions.filter(c=>c.status!=="approved"&&c.author_character_id===characterId);
 const tabs:[Tab,string][]=[["polls","School Polls"],["lost","Lost & Found"],["classifieds","Classifieds"],["suggestions","Suggestion Box"],["confessions","Confessions"],["study","Study Groups"],["events","Events / RSVP"],["help","Help Desk"]];

 return <section className={styles.panel}>
  <header><div><p className="eyebrow">COMMUNITY NETWORK · BATCH D COMPLETE</p><h3>School boards & participation</h3><p>Polls, low-stakes roleplay boards, event participation, anonymous feedback, and support in one 2006-style school network area.</p></div><span>{message}</span></header>
  <nav>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>

  {tab==="polls"&&<div className={styles.stack}>{polls.length?polls.map(p=>{const opts=options.filter(o=>o.poll_id===p.id);const mine=votes.find(v=>v.poll_id===p.id);const total=opts.reduce((n,o)=>n+(o.vote_count??0),0);return <article key={p.id}><div className={styles.row}><div><small>SCHOOL POLL · {p.status.toUpperCase()}</small><h4>{p.question}</h4></div><b>{total} vote{total===1?"":"s"}</b></div>{p.description&&<p>{p.description}</p>}<div className={styles.pollOptions}>{opts.map(o=>{const pct=total?Math.round((o.vote_count/total)*100):0;return <button key={o.id} disabled={Boolean(mine)||p.status!=="published"} onClick={()=>vote(p,o.id)} className={mine?.option_id===o.id?styles.voted:""}><span>{o.label}</span><i style={{width:`${pct}%`}}/><b>{total?`${pct}%`:"Vote"}</b></button>})}</div>{mine&&<small>Your vote is locked for this poll.</small>}</article>}):<article>No published school polls yet.</article>}</div>}

  {tab==="lost"&&<div className={styles.split}><form onSubmit={submitLost}><h4>Post to Lost & Found</h4><select value={lostDraft.post_type} onChange={e=>setLostDraft({...lostDraft,post_type:e.target.value as "lost"|"found"})}><option value="lost">I lost something</option><option value="found">I found something</option></select><input value={lostDraft.title} onChange={e=>setLostDraft({...lostDraft,title:e.target.value})} placeholder="Item / short title" required/><textarea rows={5} value={lostDraft.description} onChange={e=>setLostDraft({...lostDraft,description:e.target.value})} placeholder="Description" required/><input value={lostDraft.location} onChange={e=>setLostDraft({...lostDraft,location:e.target.value})} placeholder="Last seen / found location"/><label>Roleplay date <input type="date" value={lostDraft.date} onChange={e=>setLostDraft({...lostDraft,date:e.target.value})}/></label><button>Publish board post</button></form><div className={styles.stack}>{lostPosts.length?lostPosts.map(p=><article key={p.id}><small>{p.post_type.toUpperCase()} · {p.location||"LOCATION UNKNOWN"}</small><h4>{p.title}</h4><p>{p.description}</p><span>{p.roleplay_date||stamp(p.created_at)} · Posted by {p.character_id?names.get(p.character_id)??"Hanami Student":"School Office"}</span>{p.character_id===characterId&&<button onClick={()=>closeLost(p)}>Mark resolved</button>}</article>):<article>No open Lost & Found posts.</article>}</div></div>}

  {tab==="classifieds"&&<div className={styles.split}><form onSubmit={submitRequest}><h4>Post a classified</h4><select value={requestDraft.request_type} onChange={e=>setRequestDraft({...requestDraft,request_type:e.target.value})}><option value="study_partner">Study partner</option><option value="tutoring">Tutoring</option><option value="club_help">Club help</option><option value="festival_volunteer">Festival volunteer</option><option value="photography">Photography</option><option value="event_partner">Event partner</option><option value="missed_notes">Missed notes</option><option value="other">Other</option></select><input value={requestDraft.title} onChange={e=>setRequestDraft({...requestDraft,title:e.target.value})} placeholder="Short headline" required/><textarea rows={6} value={requestDraft.body} onChange={e=>setRequestDraft({...requestDraft,body:e.target.value})} placeholder="What are you looking for?" required/><select value={requestDraft.visibility} onChange={e=>setRequestDraft({...requestDraft,visibility:e.target.value})}><option value="school">Whole school</option><option value="friends_only">Friends only</option></select><button>Post classified</button></form><div className={styles.stack}>{requests.length?requests.map(p=><article key={p.id}><small>{nice(p.request_type).toUpperCase()} · {p.visibility==="friends_only"?"FRIENDS":"SCHOOL"}</small><h4>{p.title}</h4><p>{p.body}</p><span>Posted by {names.get(p.character_id)??"Hanami Student"} · {stamp(p.created_at)} JST</span>{p.character_id===characterId&&<button onClick={()=>closeRequest(p)}>Close classified</button>}</article>):<article>No open classifieds.</article>}</div></div>}

  {tab==="suggestions"&&<div className={styles.single}><form onSubmit={submitSuggestion}><h4>Anonymous Suggestion Box</h4><p>This form requires a signed-in school account to prevent spam, but the database record intentionally stores no user or character ID.</p><select value={suggestion.category} onChange={e=>setSuggestion({...suggestion,category:e.target.value})}><option value="general">General</option><option value="school_life">School life</option><option value="website">Website</option><option value="events">Events</option><option value="safety">Safety / concern</option></select><textarea rows={9} maxLength={3000} value={suggestion.message} onChange={e=>setSuggestion({...suggestion,message:e.target.value})} placeholder="Write your suggestion…" required/><button>Drop into suggestion box</button><small>Submissions are visible only to the Owner review queue.</small></form></div>}

  {tab==="confessions"&&<div className={styles.split}><form onSubmit={submitConfession}><h4>Submit a confession</h4><p>Every submission is moderated before becoming visible to the school.</p><textarea rows={7} maxLength={1500} value={confession.body} onChange={e=>setConfession({...confession,body:e.target.value})} placeholder="Write a school confession…" required/><label><input type="checkbox" checked={confession.anonymous} onChange={e=>setConfession({...confession,anonymous:e.target.checked})}/> Submit anonymously</label><button>Send for moderation</button>{ownPending.length>0&&<small>{ownPending.length} non-anonymous submission{ownPending.length===1?" is":"s are"} awaiting/reviewing moderation.</small>}</form><div className={styles.stack}>{approved.length?approved.map(c=><article key={c.id}><small>{c.is_anonymous?"ANONYMOUS CONFESSION":names.get(c.author_character_id??"")??"HANAMI STUDENT"}</small><p>{c.body}</p><span>{stamp(c.created_at)} JST</span></article>):<article>No approved confessions yet.</article>}</div></div>}

  {tab==="study"&&<div className={styles.split}><form onSubmit={createGroup}><h4>Create a study group</h4><input value={groupDraft.name} onChange={e=>setGroupDraft({...groupDraft,name:e.target.value})} placeholder="Group name" required/><input value={groupDraft.subject} onChange={e=>setGroupDraft({...groupDraft,subject:e.target.value})} placeholder="Subject" required/><textarea rows={4} value={groupDraft.description} onChange={e=>setGroupDraft({...groupDraft,description:e.target.value})} placeholder="What will the group work on?"/><input value={groupDraft.location} onChange={e=>setGroupDraft({...groupDraft,location:e.target.value})} placeholder="Meeting location"/><input value={groupDraft.schedule} onChange={e=>setGroupDraft({...groupDraft,schedule:e.target.value})} placeholder="Availability / meeting schedule"/><label>Member limit <input type="number" min={2} max={30} value={groupDraft.limit} onChange={e=>setGroupDraft({...groupDraft,limit:Number(e.target.value)})}/></label><button>Create study group</button></form><div className={styles.stack}>{groups.length?groups.map(g=>{const mine=members.some(m=>m.group_id===g.id&&m.character_id===characterId);const count=counts.get(g.id)??0;return <article key={g.id}><div className={styles.row}><div><small>{g.subject.toUpperCase()}</small><h4>{g.name}</h4></div><b>{count}/{g.member_limit}</b></div><p>{g.description||"No description provided."}</p><span>{g.meeting_location||"Location TBA"}{g.meeting_schedule?` · ${g.meeting_schedule}`:""}</span><small>Created by {names.get(g.creator_character_id)??"Hanami Student"}</small><button disabled={!mine&&count>=g.member_limit} onClick={()=>toggleGroup(g)}>{mine?"Leave group":count>=g.member_limit?"Group full":"Join group"}</button></article>}):<article>No open study groups yet.</article>}</div></div>}

  {tab==="events"&&<div className={styles.jumpCard}><div><small>EVENT RSVP SYSTEM</small><h4>School events, RSVP & volunteer signups</h4><p>The existing live event system already supports Going / Maybe / Not Going responses and volunteer registration against published calendar events.</p></div><button onClick={()=>route("community","campus")}>Open Events & RSVP →</button></div>}
  {tab==="help"&&<div className={styles.jumpCard}><div><small>HELP DESK / TECH SUPPORT</small><h4>Portal support tickets</h4><p>Open a private support ticket, follow its status, and read staff responses from the existing school support system.</p></div><button onClick={()=>route("school","support")}>Open Help Desk →</button></div>}
 </section>;
}
