"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./CourseRegistrationPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Role="student"|"faculty";
type Section={id:string;course_id:string;section_code:string;term:string;room:string|null;capacity:number};
type Course={id:string;code:string;title:string;department:string;description:string;credits:number};
type Request={id:string;student_character_id:string;section_id:string;note:string;status:string;faculty_note:string;faculty_reviewed_by_character_id:string|null;faculty_reviewed_at:string|null;admin_note:string;created_at:string};
type Member={section_id:string;character_id:string};
type Character={id:string;display_name:string;handle:string};
type Props={accessToken:string;characterId:string;role:Role};

export default function CourseRegistrationPanel({accessToken,characterId,role}:Props){
 const [sections,setSections]=useState<Section[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [requests,setRequests]=useState<Request[]>([]);const [memberships,setMemberships]=useState<Member[]>([]);const [characters,setCharacters]=useState<Character[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [studentNotes,setStudentNotes]=useState<Record<string,string>>({});const [status,setStatus]=useState("Loading course registration…");const [saving,setSaving]=useState(false);
 const isStudent=role==="student";
 const load=useCallback(async()=>{try{const [s,c,r,m,ch]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,course_id,section_code,term,room,capacity&order=term.asc,section_code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=id,code,title,department,description,credits&order=code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?select=id,student_character_id,section_id,note,status,faculty_note,faculty_reviewed_by_character_id,faculty_reviewed_at,admin_note,created_at&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id,character_id&relationship=eq.student`,{headers:headers(accessToken)}),
  isStudent?Promise.resolve(null):fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&role=eq.student&order=display_name.asc`,{headers:headers(accessToken)})
 ]);if(s.ok)setSections(await s.json());if(c.ok)setCourses(await c.json());if(r.ok){const rows=await r.json() as Request[];setRequests(rows);setNotes(Object.fromEntries(rows.map(x=>[x.id,x.faculty_note??""])));}if(m.ok)setMemberships(await m.json());if(ch&&ch.ok)setCharacters(await ch.json());setStatus("Course registration ready.");}catch{setStatus("Course registration could not be loaded.");}},[accessToken,isStudent]);
 useEffect(()=>{void load();},[load]);
 const course=(id:string)=>courses.find(x=>x.id===id);const section=(id:string)=>sections.find(x=>x.id===id);const student=(id:string)=>characters.find(x=>x.id===id);const ownRequests=useMemo(()=>isStudent?requests.filter(x=>x.student_character_id===characterId):requests,[requests,isStudent,characterId]);
 async function requestSection(sectionId:string){if(!isStudent||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({student_character_id:characterId,section_id:sectionId,note:(studentNotes[sectionId]??"").trim()})});if(!response.ok)throw new Error("Course request could not be submitted or already exists.");await load();setStatus("Course registration request submitted for Faculty review.");}catch(error){setStatus(error instanceof Error?error.message:"Course request could not be submitted.");}finally{setSaving(false);}}
 async function withdraw(item:Request){if(!isStudent||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:"withdrawn",updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Request could not be withdrawn.");await load();setStatus("Course request withdrawn.");}catch(error){setStatus(error instanceof Error?error.message:"Request could not be withdrawn.");}finally{setSaving(false);}}
 async function facultyReview(item:Request,next:"faculty_recommended"|"changes_requested"|"admin_review"){if(isStudent||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,faculty_note:notes[item.id]??"",faculty_reviewed_by_character_id:characterId,faculty_reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Registration review could not be saved.");await load();setStatus(`Registration request marked ${next.replaceAll("_"," ")}.`);}catch(error){setStatus(error instanceof Error?error.message:"Registration review could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">ACADEMIC PLANNING</p><h4>Course Registration</h4></div><span>{isStudent?"STUDENT REQUESTS":"FACULTY REVIEW"}</span></div><div className={styles.status}>{status}</div>{isStudent?<div className={styles.grid}>{sections.map(sec=>{const crs=course(sec.course_id);const request=ownRequests.find(x=>x.section_id===sec.id);const enrolled=memberships.some(x=>x.section_id===sec.id&&x.character_id===characterId);return <article key={sec.id}><p className="eyebrow">{sec.term} • {sec.section_code}</p><h5>{crs?`${crs.code} • ${crs.title}`:"Course section"}</h5><span>{crs?.department??"General"} • {crs?.credits??0} credits • Capacity {sec.capacity}{sec.room?` • ${sec.room}`:""}</span><p>{crs?.description??""}</p>{enrolled?<strong className={styles.good}>✓ Enrolled</strong>:request?<><strong>{request.status.replaceAll("_"," ")}</strong>{request.faculty_note&&<p><b>Faculty note:</b> {request.faculty_note}</p>}{request.admin_note&&<p><b>Administration:</b> {request.admin_note}</p>}{!["enrolled","waitlisted","denied","withdrawn"].includes(request.status)&&<button type="button" onClick={()=>withdraw(request)} disabled={saving}>Withdraw request</button>}</>:<><textarea value={studentNotes[sec.id]??""} onChange={e=>setStudentNotes(v=>({...v,[sec.id]:e.target.value}))} placeholder="Optional note for your adviser"/><button type="button" onClick={()=>requestSection(sec.id)} disabled={saving}>Request this class</button></>}</article>;})}</div>:<div className={styles.grid}>{requests.filter(x=>!["enrolled","waitlisted","denied","withdrawn"].includes(x.status)).map(item=>{const sec=section(item.section_id);const crs=sec?course(sec.course_id):null;const person=student(item.student_character_id);return <article key={item.id}><p className="eyebrow">{item.status.replaceAll("_"," ").toUpperCase()}</p><h5>{person?`${person.display_name} (@${person.handle})`:item.student_character_id.slice(0,8)}</h5><span>{crs?`${crs.code} • ${crs.title}`:"Course"}{sec?` • ${sec.term} • ${sec.section_code}`:""}</span>{item.note&&<p><b>Student note:</b> {item.note}</p>}<textarea value={notes[item.id]??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Faculty advising note"/><div className={styles.actions}><button disabled={saving} onClick={()=>facultyReview(item,"faculty_recommended")}>Recommend</button><button disabled={saving} onClick={()=>facultyReview(item,"admin_review")}>Send to Admin</button><button disabled={saving} onClick={()=>facultyReview(item,"changes_requested")}>Request changes</button></div></article>;})}{!requests.some(x=>!["enrolled","waitlisted","denied","withdrawn"].includes(x.status))&&<p>No course requests are waiting for Faculty review.</p>}</div>}</section>;
}
