"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import SchoolStatusPanel from "./SchoolStatusPanel";
import SchoolNoticesPanel from "./SchoolNoticesPanel";
import SchoolCalendarPanel from "./SchoolCalendarPanel";
import NotificationAccessibilityPanel from "./NotificationAccessibilityPanel";
import InboxPanel from "./InboxPanel";
import SupportTicketPanel from "./SupportTicketPanel";
import SchoolResourcesPanel from "./SchoolResourcesPanel";
import SystemAnnouncementBanner from "./SystemAnnouncementBanner";
import styles from "./FacultyNurseDashboard.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Visit={visit_id:string;student_character_id:string;student_display_name:string;student_handle:string;reason:string;requested_for:string|null;status:"requested"|"scheduled"|"seen"|"cancelled";staff_response:string;created_at:string;updated_at:string};
type Notice={id:string;title:string;body:string;office_hours:string|null;published:boolean;created_at:string};
type Props={accessToken:string;characterId:string;displayName:string;onReturn:()=>void};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function localInput(value:string|null){if(!value)return "";const d=new Date(value);const offset=d.getTimezoneOffset()*60000;return new Date(d.getTime()-offset).toISOString().slice(0,16);}

export default function FacultyNurseDashboard({accessToken,characterId,displayName,onReturn}:Props){
 const [visits,setVisits]=useState<Visit[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [status,setStatus]=useState("Opening Health Office queue…");const [savingId,setSavingId]=useState("");const [refreshing,setRefreshing]=useState(false);const [noticeTitle,setNoticeTitle]=useState("");const [noticeBody,setNoticeBody]=useState("");const [officeHours,setOfficeHours]=useState("Mon–Fri • 08:00–16:30");const [publishing,setPublishing]=useState(false);
 const load=useCallback(async()=>{const stamp=Date.now();const [visitResponse,noticeResponse]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/rpc/nurse_health_office_feed?_=${stamp}`,{method:"POST",cache:"no-store",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({nurse_character_id:characterId})}),
  fetch(`${SUPABASE_URL}/rest/v1/health_office_notices?select=id,title,body,office_hours,published,created_at&order=created_at.desc&_=${stamp}`,{cache:"no-store",headers:headers(accessToken)})
 ]);if(!visitResponse.ok)throw new Error("The Nurse Health Office queue could not be loaded.");if(!noticeResponse.ok)throw new Error("Health Office notices could not be loaded.");const visitRows=await visitResponse.json() as Visit[];const noticeRows=await noticeResponse.json() as Notice[];setVisits(visitRows);setNotices(noticeRows);setStatus(`${visitRows.filter(v=>v.status==="requested").length} waiting • ${visitRows.filter(v=>v.status==="scheduled").length} scheduled • ${visitRows.filter(v=>v.status==="seen").length} seen`);},[accessToken,characterId]);
 useEffect(()=>{load().catch(error=>setStatus(error instanceof Error?error.message:"Nurse Dashboard could not be loaded."));},[load]);
 const counts=useMemo(()=>({waiting:visits.filter(v=>v.status==="requested").length,scheduled:visits.filter(v=>v.status==="scheduled").length,seen:visits.filter(v=>v.status==="seen").length}),[visits]);
 async function refresh(){if(refreshing)return;setRefreshing(true);setStatus("Refreshing Health Office appointments…");try{await load();setStatus("Health Office appointments refreshed.");}catch(error){setStatus(error instanceof Error?error.message:"Health Office appointments could not be refreshed.");}finally{setRefreshing(false);}}
 async function saveVisit(visit:Visit){setSavingId(visit.visit_id);setStatus(`Saving ${visit.student_display_name}'s Health Office record…`);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/health_office_visits?id=eq.${encodeURIComponent(visit.visit_id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:visit.status,staff_response:visit.staff_response,requested_for:visit.requested_for||null,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("The Health Office record could not be saved.");await load();setStatus(`${visit.student_display_name}'s Health Office record saved.`);}catch(error){setStatus(error instanceof Error?error.message:"The Health Office record could not be saved.");}finally{setSavingId("");}}
 async function publishNotice(event:FormEvent){event.preventDefault();if(noticeTitle.trim().length<2||noticeBody.trim().length<2)return;setPublishing(true);setStatus("Publishing Health Office notice…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/health_office_notices`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({title:noticeTitle.trim(),body:noticeBody.trim(),office_hours:officeHours.trim()||null,published:true})});if(!response.ok)throw new Error("The Health Office notice could not be published.");setNoticeTitle("");setNoticeBody("");await load();setStatus("Health Office notice published.");}catch(error){setStatus(error instanceof Error?error.message:"The Health Office notice could not be published.");}finally{setPublishing(false);}}
 function patchLocal(id:string,patch:Partial<Visit>){setVisits(rows=>rows.map(row=>row.visit_id===id?{...row,...patch}:row));}
 return <section className={styles.dashboard} aria-labelledby="nurse-dashboard-title">
  <div className={styles.hero}><div><p className="eyebrow">FACULTY SPECIAL DESK • HEALTH OFFICE</p><h3 id="nurse-dashboard-title">Nurse Dashboard</h3><p>{displayName} • School Nurse workspace • Private health-request operations</p></div><button type="button" onClick={onReturn}>Switch to Faculty Dashboard</button></div>
  <SystemAnnouncementBanner accessToken={accessToken} role="faculty"/>
  <div className={styles.stats}><article><span>WAITING</span><strong>{counts.waiting}</strong></article><article><span>SCHEDULED</span><strong>{counts.scheduled}</strong></article><article><span>SEEN</span><strong>{counts.seen}</strong></article><article><span>OFFICE</span><strong>OPEN</strong></article></div>
  <div className={styles.status} aria-live="polite">{status}</div>
  <SchoolStatusPanel accessToken={accessToken}/><SchoolNoticesPanel accessToken={accessToken}/><SchoolCalendarPanel accessToken={accessToken} characterId={characterId}/><NotificationAccessibilityPanel accessToken={accessToken}/>
  <section className={styles.healthPanel}><div className={styles.heading}><div><p className="eyebrow">PRIVATE HEALTH OFFICE</p><h4>Visit requests & appointments</h4></div><button type="button" onClick={refresh} disabled={refreshing}>{refreshing?"Refreshing…":"Refresh"}</button></div>{visits.length===0?<p className={styles.empty}>No Health Office requests are waiting.</p>:<div className={styles.visitList}>{visits.map(visit=><article key={visit.visit_id}><div className={styles.visitTop}><div><strong>{visit.student_display_name}</strong><span>@{visit.student_handle}</span></div><span className={styles[visit.status]}>{visit.status.toUpperCase()}</span></div><p>{visit.reason}</p><div className={styles.visitGrid}><label><span>Status</span><select value={visit.status} onChange={e=>patchLocal(visit.visit_id,{status:e.target.value as Visit["status"]})}><option value="requested">Requested</option><option value="scheduled">Scheduled</option><option value="seen">Seen</option><option value="cancelled">Cancelled</option></select></label><label><span>Appointment</span><input type="datetime-local" value={localInput(visit.requested_for)} onChange={e=>patchLocal(visit.visit_id,{requested_for:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div><label><span>Private nurse response</span><textarea value={visit.staff_response} onChange={e=>patchLocal(visit.visit_id,{staff_response:e.target.value})} maxLength={2000} placeholder="Type the nurse response, scheduling note, or follow-up instructions here…"/></label><button type="button" onClick={()=>saveVisit(visit)} disabled={savingId===visit.visit_id}>{savingId===visit.visit_id?"Saving…":"Save Health Office record"}</button></article>)}</div>}</section>
  <section className={styles.noticePanel}><div className={styles.heading}><div><p className="eyebrow">HEALTH OFFICE NOTICES</p><h4>Publish a nurse notice</h4></div></div><form onSubmit={publishNotice}><label><span>Title</span><input value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)} maxLength={120} placeholder="Type a notice title…" required/></label><label><span>Office hours</span><input value={officeHours} onChange={e=>setOfficeHours(e.target.value)} maxLength={160} placeholder="Type office hours…"/></label><label><span>Notice</span><textarea value={noticeBody} onChange={e=>setNoticeBody(e.target.value)} maxLength={2000} placeholder="Type Health Office information for students and faculty here…" required/></label><button type="submit" disabled={publishing}>{publishing?"Publishing…":"Publish Health Office notice"}</button></form><div className={styles.noticeList}>{notices.slice(0,6).map(notice=><article key={notice.id}><strong>{notice.title}</strong><span>{notice.published?"PUBLISHED":"DRAFT"}{notice.office_hours?` • ${notice.office_hours}`:""}</span><p>{notice.body}</p></article>)}</div></section>
  <InboxPanel accessToken={accessToken} characterId={characterId}/><SupportTicketPanel accessToken={accessToken} characterId={characterId}/><SchoolResourcesPanel accessToken={accessToken} characterId={characterId}/>
 </section>;
}
