"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./FacultyPetalAwardPanel.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";

type Student={id:string;display_name:string;handle:string};
type Grant={id:string;recipient_character_id:string;amount:number;note:string;created_at:string};

function h(token:string,extra:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${token}`,...extra};}

export default function FacultyPetalAwardPanel({accessToken}:{accessToken:string}){
 const [students,setStudents]=useState<Student[]>([]);const [grants,setGrants]=useState<Grant[]>([]);const [studentId,setStudentId]=useState("");const [amount,setAmount]=useState(5);const [note,setNote]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const studentMap=useMemo(()=>new Map(students.map(s=>[s.id,s])),[students]);
 const todayTotal=useMemo(()=>{const fmt=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"});const tokyoDay=fmt.format(new Date());return grants.filter(g=>fmt.format(new Date(g.created_at))===tokyoDay).reduce((sum,g)=>sum+g.amount,0)},[grants]);
 useEffect(()=>{let dead=false;(async()=>{try{const [studentsR,grantsR]=await Promise.all([fetch(`${U}/rest/v1/characters?select=id,display_name,handle&role=eq.student&is_active=eq.true&order=display_name.asc`,{headers:h(accessToken),cache:"no-store"}),fetch(`${U}/rest/v1/petal_teacher_grants?select=id,recipient_character_id,amount,note,created_at&order=created_at.desc&limit=25`,{headers:h(accessToken),cache:"no-store"})]);if(!dead){if(studentsR.ok)setStudents(await studentsR.json() as Student[]);if(grantsR.ok)setGrants(await grantsR.json() as Grant[])}}catch{if(!dead)setMessage("Teacher Petal awards could not be loaded.")}})();return()=>{dead=true}},[accessToken]);
 async function submit(e:FormEvent){e.preventDefault();if(!studentId){setMessage("Choose a student first.");return;}if(amount<1||amount>25){setMessage("Choose between 1 and 25 Petals.");return;}if(!note.trim()){setMessage("Add a short reason for the award.");return;}setBusy(true);setMessage("");try{const r=await fetch(`${U}/rest/v1/rpc/teacher_grant_petals`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:studentId,amount,note:note.trim()})});if(!r.ok){let text="Petal award could not be sent.";try{const body=await r.json() as {message?:string};if(body.message)text=body.message}catch{}throw new Error(text);}const newId=await r.json() as string;setGrants(current=>[{id:newId,recipient_character_id:studentId,amount,note:note.trim(),created_at:new Date().toISOString()},...current]);setNote("");setMessage(`${amount} Petals awarded to ${studentMap.get(studentId)?.display_name??"student"}.`);window.dispatchEvent(new CustomEvent("hanami-petal-balance-changed"));}catch(error){setMessage(error instanceof Error?error.message:"Petal award failed.");}finally{setBusy(false)}}
 return <section className={styles.panel} aria-label="Teacher Petal awards"><header><div><p className={styles.eyebrow}>FACULTY RECOGNITION</p><h3>Award Petals</h3><p>Recognize participation, kindness, improvement, or school spirit. Awards are audited and credited server-side.</p></div><div className={styles.cap}><strong>{todayTotal}/100</strong><span>awarded today</span></div></header><form onSubmit={submit}><label><span>Student</span><select value={studentId} onChange={e=>setStudentId(e.target.value)} required><option value="">Choose a student…</option>{students.map(s=><option key={s.id} value={s.id}>{s.display_name} (@{s.handle})</option>)}</select></label><label><span>Petals</span><input type="number" min="1" max="25" value={amount} onChange={e=>setAmount(Math.max(1,Math.min(25,Number(e.target.value)||1)))}/></label><label className={styles.reason}><span>Reason</span><input maxLength={280} value={note} onChange={e=>setNote(e.target.value)} placeholder="Great teamwork during homeroom" required/></label><button type="submit" disabled={busy||todayTotal>=100}>{busy?"Awarding…":todayTotal>=100?"Daily limit reached":"Award Petals"}</button></form>{message&&<p className={styles.notice}>{message}</p>}<div className={styles.rules}><span>1–25 Petals per award</span><span>100 Petals/day server-enforced cap</span><span>Wallet balances cannot be edited here</span></div>{grants.length>0&&<div className={styles.recent}><strong>Recent awards</strong>{grants.slice(0,5).map(g=><div key={g.id}><span>{studentMap.get(g.recipient_character_id)?.display_name??"Student"}</span><small>{g.note}</small><b>+{g.amount}</b></div>)}</div>}</section>;
}
