"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./FacultyAttendanceReportPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type RosterRow={student_character_id:string;display_name:string;handle:string;section_id:string;section_code:string;course_code:string;course_title:string};
type AttendanceStatus="present"|"absent"|"tardy"|"excused";
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function tokyoDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}

export default function FacultyAttendanceReportPanel({accessToken,characterId}:Props){
 const [roster,setRoster]=useState<RosterRow[]>([]);const [sectionId,setSectionId]=useState("");const [attendanceDate,setAttendanceDate]=useState(tokyoDate());const [attendance,setAttendance]=useState<Record<string,AttendanceStatus>>({});const [term,setTerm]=useState("Spring 2006");const [grades,setGrades]=useState<Record<string,{numeric:string;letter:string;comment:string}>>({});const [message,setMessage]=useState("Loading attendance tools…");const [saving,setSaving]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/faculty_student_roster`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({faculty_character_id:characterId})});if(!response.ok)throw new Error("Teaching roster could not be loaded.");const rows=await response.json() as RosterRow[];if(cancelled)return;setRoster(rows);setSectionId(current=>current||rows[0]?.section_id||"");setMessage(rows.length?"Attendance and report-card tools ready.":"No enrolled students are available yet.");}catch(error){if(!cancelled)setMessage(error instanceof Error?error.message:"Academic tools unavailable.");}})();return()=>{cancelled=true;};},[accessToken,characterId]);
 const sections=useMemo(()=>{const map=new Map<string,RosterRow>();for(const row of roster)if(!map.has(row.section_id))map.set(row.section_id,row);return [...map.values()];},[roster]);
 const students=useMemo(()=>roster.filter(row=>row.section_id===sectionId),[roster,sectionId]);
 async function saveAttendance(){if(!sectionId||!students.length)return;setSaving(true);try{for(const student of students){const status=attendance[student.student_character_id]??"present";const response=await fetch(`${SUPABASE_URL}/rest/v1/attendance_records?on_conflict=section_id,student_character_id,attendance_date`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify({section_id:sectionId,student_character_id:student.student_character_id,attendance_date:attendanceDate,status,marked_by_character_id:characterId})});if(!response.ok)throw new Error("Attendance could not be saved.");}setMessage(`Attendance saved for ${students.length} student${students.length===1?"":"s"} on ${attendanceDate}.`);}catch(error){setMessage(error instanceof Error?error.message:"Attendance could not be saved.");}finally{setSaving(false);}}
 async function saveReport(student:RosterRow,publish:boolean){const data=grades[student.student_character_id]??{numeric:"",letter:"",comment:""};const numeric=data.numeric===""?null:Number(data.numeric);if(numeric!=null&&(numeric<0||numeric>100)){setMessage("Numeric grade must be between 0 and 100.");return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/student_report_cards?on_conflict=section_id,student_character_id,term`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify({section_id:sectionId,student_character_id:student.student_character_id,term,numeric_grade:numeric,letter_grade:data.letter.trim()||null,instructor_comment:data.comment.trim()||null,status:publish?"published":"draft",created_by_character_id:characterId,published_at:publish?new Date().toISOString():null,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Report card could not be saved.");setMessage(`${student.display_name}'s report card ${publish?"published":"saved as draft"}.`);}catch(error){setMessage(error instanceof Error?error.message:"Report card could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="attendance-report-title"><div className={styles.heading}><div><p className="eyebrow">ACADEMIC RECORDS</p><h4 id="attendance-report-title">Attendance & report cards</h4></div><span>INSTRUCTOR-SCOPED</span></div><div className={styles.status}>{message}</div>
 <div className={styles.controls}><label><span>Teaching section</span><select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{sections.map(row=><option key={row.section_id} value={row.section_id}>{row.course_code} • {row.course_title} • SEC {row.section_code}</option>)}</select></label><label><span>Attendance date</span><input type="date" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/></label><button type="button" onClick={saveAttendance} disabled={saving||!students.length}>Save attendance</button></div>
 {students.length>0&&<div className={styles.roster}><h5>Daily attendance</h5>{students.map(student=><div key={`attendance-${student.student_character_id}`} className={styles.studentRow}><div><strong>{student.display_name}</strong><span>@{student.handle}</span></div><select value={attendance[student.student_character_id]??"present"} onChange={e=>setAttendance(current=>({...current,[student.student_character_id]:e.target.value as AttendanceStatus}))}><option value="present">Present</option><option value="tardy">Tardy</option><option value="absent">Absent</option><option value="excused">Excused</option></select></div>)}</div>}
 <div className={styles.reportControls}><label><span>Report term</span><input value={term} onChange={e=>setTerm(e.target.value)}/></label></div>
 {students.length>0&&<div className={styles.reports}><h5>Report cards</h5>{students.map(student=>{const value=grades[student.student_character_id]??{numeric:"",letter:"",comment:""};return <article key={`report-${student.student_character_id}`}><div className={styles.studentHead}><strong>{student.display_name}</strong><span>@{student.handle}</span></div><div className={styles.gradeInputs}><label><span>Numeric</span><input type="number" min="0" max="100" value={value.numeric} onChange={e=>setGrades(current=>({...current,[student.student_character_id]:{...value,numeric:e.target.value}}))}/></label><label><span>Letter</span><input maxLength={4} value={value.letter} onChange={e=>setGrades(current=>({...current,[student.student_character_id]:{...value,letter:e.target.value}}))}/></label></div><label><span>Instructor comment</span><textarea value={value.comment} onChange={e=>setGrades(current=>({...current,[student.student_character_id]:{...value,comment:e.target.value}}))}/></label><div className={styles.actions}><button type="button" onClick={()=>saveReport(student,false)} disabled={saving}>Save draft</button><button type="button" onClick={()=>saveReport(student,true)} disabled={saving}>Publish report card</button></div></article>;})}</div>}
 </section>;
}
