"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./FacultyCourseManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Course={code:string;title:string;is_test_data:boolean};
type Section={id:string;section_code:string;term:string;room:string|null;is_test_data:boolean;academic_courses:Course|null};
type Category={id:string;section_id:string;name:string;weight_percent:number};
type AssessmentType="assignment"|"quiz"|"exam"|"project"|"presentation"|"other";
type Assignment={id:string;section_id:string;title:string;description:string;due_at:string|null;points:number;status:"draft"|"published"|"closed";is_test_data:boolean;grade_category_id:string|null;assignment_group:string|null;late_policy:string|null;assessment_type:AssessmentType};
type Props={accessToken:string;characterId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function dueLabel(value:string|null){if(!value)return "No due date";return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo",timeZoneName:"short"}).format(new Date(value));}

export default function FacultyCourseManager({accessToken,characterId}:Props){
 const [sections,setSections]=useState<Section[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [message,setMessage]=useState("Loading your teaching sections…");const [saving,setSaving]=useState(false);
 const [sectionId,setSectionId]=useState("");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [dueAt,setDueAt]=useState("");const [points,setPoints]=useState("100");const [status,setStatus]=useState<"draft"|"published">("draft");const [assessmentType,setAssessmentType]=useState<AssessmentType>("assignment");const [categoryId,setCategoryId]=useState("");const [assignmentGroup,setAssignmentGroup]=useState("");const [latePolicy,setLatePolicy]=useState("");const [categoryName,setCategoryName]=useState("");const [categoryWeight,setCategoryWeight]=useState("25");
 const loadData=useCallback(async()=>{const membershipResponse=await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.instructor`,{headers:headers(accessToken)});if(!membershipResponse.ok)throw new Error("Your instructor assignments could not be checked.");const memberships=await membershipResponse.json() as {section_id:string}[];const ids=memberships.map(item=>item.section_id);if(ids.length===0){setSections([]);setAssignments([]);setCategories([]);setSectionId("");setMessage("No teaching sections are assigned to this faculty character yet.");return;}const filter=`(${ids.join(",")})`;const [sectionResponse,assignmentResponse,categoryResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,section_code,term,room,is_test_data,academic_courses(code,title,is_test_data)&id=in.${encodeURIComponent(filter)}`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/course_assignments?select=id,section_id,title,description,due_at,points,status,is_test_data,grade_category_id,assignment_group,late_policy,assessment_type&section_id=in.${encodeURIComponent(filter)}&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/section_grade_categories?select=id,section_id,name,weight_percent&section_id=in.${encodeURIComponent(filter)}&order=created_at.asc`,{headers:headers(accessToken)})]);if(!sectionResponse.ok||!assignmentResponse.ok||!categoryResponse.ok)throw new Error("Your course management data could not be loaded.");const sectionRows=await sectionResponse.json() as Section[];setSections(sectionRows);setAssignments(await assignmentResponse.json() as Assignment[]);setCategories(await categoryResponse.json() as Category[]);setSectionId(current=>current||sectionRows[0]?.id||"");setMessage(`${sectionRows.length} teaching section${sectionRows.length===1?"":"s"} loaded with weighted grading tools.`);},[accessToken,characterId]);
 useEffect(()=>{loadData().catch(error=>setMessage(error instanceof Error?error.message:"Course management could not be loaded."));},[loadData]);
 const currentCategories=categories.filter(item=>item.section_id===sectionId);const weightTotal=currentCategories.reduce((sum,item)=>sum+Number(item.weight_percent),0);
 async function createCategory(event:FormEvent){event.preventDefault();const name=categoryName.trim();const weight=Number(categoryWeight);if(!sectionId||name.length<2||!Number.isFinite(weight)||weight<=0||weight>100){setMessage("Choose a section, enter a category name, and use a weight from 0.01–100%.");return;}if(weightTotal+weight>100.001){setMessage(`Category weights cannot exceed 100%. Current section total is ${weightTotal}%.`);return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/section_grade_categories`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:sectionId,name,weight_percent:weight})});if(!response.ok)throw new Error("Grade category could not be created.");setCategoryName("");setCategoryWeight("25");await loadData();setMessage("Weighted grade category created.");}catch(error){setMessage(error instanceof Error?error.message:"Grade category could not be created.");}finally{setSaving(false);}}
 async function createAssignment(event:FormEvent<HTMLFormElement>){event.preventDefault();const cleanTitle=title.trim();const numericPoints=Number(points);if(!sectionId||cleanTitle.length<2){setMessage("Choose a teaching section and enter an assignment title.");return;}if(!Number.isFinite(numericPoints)||numericPoints<0||numericPoints>10000){setMessage("Points must be between 0 and 10,000.");return;}setSaving(true);setMessage(`Creating ${status} ${assessmentType}…`);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/course_assignments`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:sectionId,created_by_character_id:characterId,title:cleanTitle,description:description.trim(),due_at:dueAt?new Date(dueAt).toISOString():null,points:numericPoints,status,is_test_data:false,grade_category_id:categoryId||null,assignment_group:assignmentGroup.trim()||null,late_policy:latePolicy.trim()||null,assessment_type:assessmentType})});if(!response.ok)throw new Error("The assessment could not be created for this teaching section.");setTitle("");setDescription("");setDueAt("");setPoints("100");setStatus("draft");setAssessmentType("assignment");setCategoryId("");setAssignmentGroup("");setLatePolicy("");await loadData();setMessage("Assessment created successfully.");}catch(error){setMessage(error instanceof Error?error.message:"The assessment could not be created.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="faculty-course-title"><div className={styles.heading}><div><p className="eyebrow">COURSE MANAGEMENT</p><h4 id="faculty-course-title">Assignments & weighted grading</h4></div><span>{assignments.length} ASSESSMENTS</span></div><div className={styles.status} aria-live="polite">{message}</div>{sections.length===0?<div className={styles.empty}><strong>No assigned sections</strong><p>Administration must assign this faculty character as an instructor before course tools become available.</p></div>:<>
  <form className={styles.form} onSubmit={createCategory}><div className={styles.formTitle}><strong>GRADE CATEGORIES</strong><span>{weightTotal.toFixed(0)}% / 100%</span></div><label><span>Teaching section</span><select value={sectionId} onChange={event=>{setSectionId(event.target.value);setCategoryId("");}}>{sections.map(section=><option value={section.id} key={section.id}>{section.academic_courses?.code??"COURSE"} — {section.section_code}</option>)}</select></label><label><span>Category name</span><input value={categoryName} onChange={event=>setCategoryName(event.target.value)} placeholder="Exams" maxLength={60}/></label><label><span>Weight %</span><input type="number" min="0.01" max="100" step="0.01" value={categoryWeight} onChange={event=>setCategoryWeight(event.target.value)}/></label><button type="submit" disabled={saving}>Add category</button><div className={styles.wide}>{currentCategories.length?currentCategories.map(category=><span key={category.id} style={{display:"inline-block",margin:"3px 6px 3px 0",padding:"5px 7px",border:"1px solid #b8c8d9",background:"#eef3f8",fontSize:8}}>{category.name} • {category.weight_percent}%</span>):<small>No weighted categories yet. Points-only grading still works until categories are added.</small>}</div></form>
  <form className={styles.form} onSubmit={createAssignment}><div className={styles.formTitle}><strong>NEW ASSESSMENT</strong><span>FACULTY TOOL</span></div><label><span>Teaching section</span><select value={sectionId} onChange={event=>{setSectionId(event.target.value);setCategoryId("");}}>{sections.map(section=><option value={section.id} key={section.id}>{section.academic_courses?.code??"COURSE"} — {section.academic_courses?.title??"Untitled"} / {section.section_code}</option>)}</select></label><label><span>Assessment title</span><input value={title} onChange={event=>setTitle(event.target.value)} maxLength={120} required/></label><label><span>Assessment type</span><select value={assessmentType} onChange={event=>setAssessmentType(event.target.value as AssessmentType)}><option value="assignment">Assignment</option><option value="quiz">Quiz</option><option value="exam">Exam</option><option value="project">Project</option><option value="presentation">Presentation</option><option value="other">Other</option></select></label><label><span>Grade category</span><select value={categoryId} onChange={event=>setCategoryId(event.target.value)}><option value="">Uncategorized</option>{currentCategories.map(category=><option key={category.id} value={category.id}>{category.name} • {category.weight_percent}%</option>)}</select></label><label className={styles.wide}><span>Instructions</span><textarea value={description} onChange={event=>setDescription(event.target.value)} maxLength={12000}/></label><label><span>Assignment group</span><input value={assignmentGroup} onChange={event=>setAssignmentGroup(event.target.value)} placeholder="Unit 1" maxLength={80}/></label><label><span>Due / exam date & time</span><input type="datetime-local" value={dueAt} onChange={event=>setDueAt(event.target.value)}/></label><label><span>Points</span><input type="number" min="0" max="10000" step="0.01" value={points} onChange={event=>setPoints(event.target.value)}/></label><label className={styles.wide}><span>Late policy</span><input value={latePolicy} onChange={event=>setLatePolicy(event.target.value)} placeholder="Example: accepted up to 3 days late with 10% deduction" maxLength={500}/></label><label><span>Initial status</span><select value={status} onChange={event=>setStatus(event.target.value as "draft"|"published")}><option value="draft">Draft — hidden from students</option><option value="published">Published — visible to students</option></select></label><button type="submit" disabled={saving}>{saving?"Creating…":"Create assessment"}</button></form>
  <div className={styles.assignmentList}>{assignments.length?assignments.map(assignment=>{const section=sections.find(item=>item.id===assignment.section_id);const category=categories.find(item=>item.id===assignment.grade_category_id);const testData=assignment.is_test_data||Boolean(section?.is_test_data||section?.academic_courses?.is_test_data);return <article key={assignment.id}><div className={styles.meta}><span>{section?.academic_courses?.code??"COURSE"} • {section?.section_code??"—"} • {assignment.assessment_type.toUpperCase()}</span>{testData&&<b>TEST</b>}</div><h5>{assignment.title}</h5><p>{assignment.description||"No instructions posted."}</p><dl><div><dt>Status</dt><dd>{assignment.status}</dd></div><div><dt>Due</dt><dd>{dueLabel(assignment.due_at)}</dd></div><div><dt>Points</dt><dd>{assignment.points}</dd></div><div><dt>Category</dt><dd>{category?.name??"Uncategorized"}</dd></div><div><dt>Group</dt><dd>{assignment.assignment_group||"—"}</dd></div><div><dt>Late policy</dt><dd>{assignment.late_policy||"Standard faculty discretion"}</dd></div></dl></article>}):<div className={styles.empty}><strong>No assessments created yet</strong><p>Use the faculty form above to create a draft or publish the first assessment.</p></div>}</div></>}
 </section>;
}
