"use client";

import {useEffect,useMemo,useState} from "react";
import {hanamiRoleplayNow} from "../components/roleplay-date";
import styles from "./HanamiSchoolPulse.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type SchoolState={term:string;day_type:string;closure_state:string;exam_week:boolean;festival_mode:boolean;election_mode:boolean;seasonal_state:string;rp_focus:string;status_message:string};
type Block={id:string;title:string;block_type:string;weekday:number;starts_at:string;ends_at:string};
type CourseMeeting={weekday:number;starts_at:string;ends_at:string};
type Membership={class_sections:{id:string;room:string|null;academic_courses:{code:string;title:string}|null;section_meetings:CourseMeeting[]}|null};
type Lunch={title:string;items:string[];note:string};
type Roleplay={title:string;prompt:string;category:string};
type Notice={title:string;body:string;severity:string;published_at:string|null};
type Birthday={character_id:string;month:number;day:number;visible:boolean};
type Person={id:string;display_name:string};
type Event={title:string;starts_at:string;location:string|null};
type Focus="all"|"school"|"academic"|"social"|"rp";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,...extra};}
function dateParts(date:Date){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",month:"2-digit",day:"2-digit",weekday:"long"}).formatToParts(date);return {month:Number(p.find(x=>x.type==="month")?.value??1),day:Number(p.find(x=>x.type==="day")?.value??1),weekday:p.find(x=>x.type==="weekday")?.value??"Monday"};}
function isoDate(date:Date){const {month,day}=dateParts(date);return `2006-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;}
function minutes(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
function currentMinutes(date:Date){const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date);return Number(p.find(x=>x.type==="hour")?.value??0)*60+Number(p.find(x=>x.type==="minute")?.value??0);}
function timeLabel(value:string){const [h,m]=value.split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`;}
function pretty(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}

export default function HanamiSchoolPulse({accessToken,characterId}:Props){
 const [clock,setClock]=useState(()=>hanamiRoleplayNow()),[focus,setFocus]=useState<Focus>("all"),[schoolState,setSchoolState]=useState<SchoolState|null>(null),[blocks,setBlocks]=useState<Block[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[lunch,setLunch]=useState<Lunch|null>(null),[roleplay,setRoleplay]=useState<Roleplay|null>(null),[notice,setNotice]=useState<Notice|null>(null),[birthdays,setBirthdays]=useState<Birthday[]>([]),[people,setPeople]=useState<Person[]>([]),[events,setEvents]=useState<Event[]>([]),[status,setStatus]=useState("Loading Today at Hanami…");
 useEffect(()=>{try{const saved=localStorage.getItem("hanami.dashboard.focus.v1") as Focus|null;if(saved&&["all","school","academic","social","rp"].includes(saved))setFocus(saved);}catch{}const timer=window.setInterval(()=>setClock(hanamiRoleplayNow()),30000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{let cancelled=false;async function applyDue(){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/apply_due_school_state_transitions`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return;const applied=Number(await response.json());if(applied>0&&!cancelled){const stateResponse=await fetch(`${SUPABASE_URL}/rest/v1/school_state_config?select=term,day_type,closure_state,exam_week,festival_mode,election_mode,seasonal_state,rp_focus,status_message&id=eq.1&limit=1`,{headers:headers(accessToken)});if(stateResponse.ok&&!cancelled)setSchoolState((await stateResponse.json() as SchoolState[])[0]??null);}}catch{}}void applyDue();const timer=window.setInterval(()=>void applyDue(),60000);return()=>{cancelled=true;window.clearInterval(timer);};},[accessToken]);
 useEffect(()=>{let cancelled=false;(async()=>{try{const today=isoDate(hanamiRoleplayNow());const [stateR,blocksR,membersR,lunchR,rpR,noticeR,birthR,peopleR,eventR]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/school_state_config?select=term,day_type,closure_state,exam_week,festival_mode,election_mode,seasonal_state,rp_focus,status_message&id=eq.1&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,title,block_type,weekday,starts_at,ends_at&order=weekday.asc,starts_at.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=class_sections(id,room,academic_courses(code,title),section_meetings(weekday,starts_at,ends_at))&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.student`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_lunch_menus?select=title,items,note&menu_date=eq.${today}&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/roleplay_calendar_entries?select=title,prompt,category&cadence=eq.daily&roleplay_date=eq.${today}&status=eq.published&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/site_announcements?select=title,body,severity,published_at&status=eq.published&order=featured.desc,published_at.desc.nullslast&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/character_school_birthdays?select=character_id,month,day,visible&visible=eq.true`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name&role=eq.student`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_calendar_events?select=title,starts_at,location&status=eq.published&starts_at=gte.${today}T00:00:00%2B09:00&starts_at=lt.${today}T23:59:59%2B09:00&order=starts_at.asc&limit=4`,{headers:headers(accessToken)})
 ]);if(cancelled)return;setSchoolState(stateR.ok?(await stateR.json() as SchoolState[])[0]??null:null);setBlocks(blocksR.ok?await blocksR.json():[]);setMemberships(membersR.ok?await membersR.json():[]);setLunch(lunchR.ok?(await lunchR.json() as Lunch[])[0]??null:null);setRoleplay(rpR.ok?(await rpR.json() as Roleplay[])[0]??null:null);setNotice(noticeR.ok?(await noticeR.json() as Notice[])[0]??null:null);setBirthdays(birthR.ok?await birthR.json():[]);setPeople(peopleR.ok?await peopleR.json():[]);setEvents(eventR.ok?await eventR.json():[]);setStatus("Today at Hanami is live.");}catch(e){if(!cancelled)setStatus(e instanceof Error?e.message:"Today at Hanami could not be loaded.");}})();return()=>{cancelled=true};},[accessToken,characterId]);
 const parts=dateParts(clock);const weekdayIndex=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].indexOf(parts.weekday);const minute=currentMinutes(clock);
 const dayItems=useMemo(()=>{const items:{title:string;starts_at:string;ends_at:string;meta:string}[]=[];blocks.filter(b=>b.weekday===weekdayIndex).forEach(b=>items.push({title:b.title,starts_at:b.starts_at,ends_at:b.ends_at,meta:pretty(b.block_type)}));memberships.forEach(m=>m.class_sections?.section_meetings?.filter(meeting=>meeting.weekday===weekdayIndex).forEach(meeting=>items.push({title:m.class_sections?.academic_courses?.title??"Class",starts_at:meeting.starts_at,ends_at:meeting.ends_at,meta:`${m.class_sections?.academic_courses?.code??"COURSE"}${m.class_sections?.room?` · Room ${m.class_sections.room}`:""}`})));return items.sort((a,b)=>a.starts_at.localeCompare(b.starts_at));},[blocks,memberships,weekdayIndex]);
 const live=dayItems.find(item=>minute>=minutes(item.starts_at)&&minute<minutes(item.ends_at))??null;const next=dayItems.find(item=>minutes(item.starts_at)>minute)??null;const birthdayNames=useMemo(()=>{const ids=new Set(birthdays.filter(b=>b.month===parts.month&&b.day===parts.day).map(b=>b.character_id));return people.filter(p=>ids.has(p.id)).map(p=>p.display_name);},[birthdays,people,parts.day,parts.month]);
 const dateLabel=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long",month:"long",day:"numeric",year:"numeric"}).format(clock);const clockLabel=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit"}).format(clock);
 function choose(nextFocus:Focus){setFocus(nextFocus);try{localStorage.setItem("hanami.dashboard.focus.v1",nextFocus);}catch{}}
 const modes=[schoolState?.closure_state!=="open"?pretty(schoolState?.closure_state??"open"):null,schoolState?.exam_week?"Exam Week":null,schoolState?.festival_mode?"Festival Mode":null,schoolState?.election_mode?"Election Season":null,schoolState?.day_type&&schoolState.day_type!=="normal"?pretty(schoolState.day_type):null].filter(Boolean);
 return <section className={styles.pulse} aria-label="Today at Hanami"><header className={styles.hero}><div><p className="eyebrow">HANAMI SCHOOL PULSE · {clockLabel} JST</p><h2>Today at Hanami</h2><p>{dateLabel} · {schoolState?.term??"2006–07 School Year"}</p></div><div className={styles.state}><strong>{live?.title??(next?"Passing / open time":weekdayIndex>=6?"Weekend campus":"School day complete")}</strong><span>{live?`${timeLabel(live.starts_at)}–${timeLabel(live.ends_at)} · ${live.meta}`:next?`Next: ${next.title} at ${timeLabel(next.starts_at)}`:schoolState?.status_message||"No active period right now."}</span></div></header><div className={styles.modeRow}>{modes.length?modes.map(mode=><span key={mode}>{mode}</span>):<span>Normal School Day</span>}<span>{schoolState?.seasonal_state?pretty(schoolState.seasonal_state):"Seasonal State"}</span></div><nav className={styles.focus} aria-label="Dashboard focus">{(["all","school","academic","social","rp"] as Focus[]).map(item=><button type="button" key={item} className={focus===item?styles.active:""} onClick={()=>choose(item)}>{pretty(item)}</button>)}</nav><div className={styles.grid}>
  {(focus==="all"||focus==="school")&&<article className={styles.card}><span className={styles.kicker}>CURRENT DAY</span><h3>{live?.title??"Open time"}</h3><p>{live?live.meta:next?`Next up: ${next.title}`:"No more scheduled blocks today."}</p><small>{schoolState?.status_message||status}</small></article>}
  {(focus==="all"||focus==="academic")&&<article className={styles.card}><span className={styles.kicker}>LUNCH</span><h3>{lunch?.title??"Lunch menu not posted"}</h3><p>{lunch?.items?.length?lunch.items.join(" · "):"When today’s menu is posted, it will appear here."}</p>{lunch?.note&&<small>{lunch.note}</small>}</article>}
  {(focus==="all"||focus==="rp")&&<article className={styles.card}><span className={styles.kicker}>TODAY&apos;S ROLEPLAY</span><h3>{roleplay?.title??"Open school-life roleplay"}</h3><p>{(roleplay?.prompt??schoolState?.rp_focus)||"No formal daily prompt is published, so freeform school-life scenes are open."}</p>{roleplay&&<small>{pretty(roleplay.category)}</small>}</article>}
  {(focus==="all"||focus==="school")&&<article className={styles.card}><span className={styles.kicker}>ANNOUNCEMENT</span><h3>{notice?.title??"No new announcement"}</h3><p>{notice?.body??"You are caught up on school-wide announcements."}</p>{notice?.severity&&<small>{pretty(notice.severity)}</small>}</article>}
  {(focus==="all"||focus==="social")&&<article className={styles.card}><span className={styles.kicker}>BIRTHDAYS</span><h3>{birthdayNames.length?birthdayNames.join(", "):"No listed birthdays today"}</h3><p>{birthdayNames.length?"Send them a note or add a memory to the day.":"The birthday board is quiet today."}</p></article>}
  {(focus==="all"||focus==="school")&&<article className={styles.card}><span className={styles.kicker}>TODAY&apos;S EVENTS</span><h3>{events[0]?.title??"No school event today"}</h3><p>{events.length?events.map(e=>`${new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit"}).format(new Date(e.starts_at))} ${e.title}${e.location?` · ${e.location}`:""}`).join(" • "):weekdayIndex>=6?"Weekend sports and scheduled activities can appear here.":"The regular school day is the main event."}</p></article>}
 </div></section>;
}
