"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Notification={id:string;category:string;title:string;body:string;href:string|null;is_read:boolean;created_at:string};
type SystemNotice={id:string;title:string;body:string;severity:string;created_at:string};
type Preferences={unread_messages:boolean;grades:boolean;assignments:boolean;friend_requests:boolean;office_requests:boolean;organization_updates:boolean;event_reminders:boolean;application_decisions:boolean;account_notices:boolean;admin_announcements:boolean};
type Accessibility={font_scale:number;high_contrast:boolean;dyslexia_friendly:boolean;reduce_motion:boolean;disable_glitter:boolean;simplified_profile_studio:boolean;custom_cursor_disabled:boolean;music_muted:boolean;music_volume:number;dark_mode:boolean;soft_contrast:boolean;brightness:number};
const defaultPrefs:Preferences={unread_messages:true,grades:true,assignments:true,friend_requests:true,office_requests:true,organization_updates:true,event_reminders:true,application_decisions:true,account_notices:true,admin_announcements:true};
const defaultAccess:Accessibility={font_scale:1,high_contrast:false,dyslexia_friendly:false,reduce_motion:false,disable_glitter:false,simplified_profile_studio:false,custom_cursor_disabled:false,music_muted:false,music_volume:.55,dark_mode:false,soft_contrast:false,brightness:1};

export default function NotificationAccessibilityPanel({accessToken}:{accessToken:string}){
 const [notifications,setNotifications]=useState<Notification[]>([]);const [systemNotices,setSystemNotices]=useState<SystemNotice[]>([]);const [prefs,setPrefs]=useState<Preferences>(defaultPrefs);const [access,setAccess]=useState<Accessibility>(defaultAccess);const [open,setOpen]=useState(false);const [settingsOpen,setSettingsOpen]=useState(false);const [notice,setNotice]=useState("Loading notifications…");
 const unread=useMemo(()=>notifications.filter(item=>!item.is_read).length,[notifications]);
 const applyAccessibility=useCallback((next:Accessibility)=>{const root=document.documentElement;root.style.setProperty("--hanami-user-font-scale",String(next.font_scale));root.style.setProperty("--hanami-user-brightness",String(next.brightness));root.dataset.hanamiContrast=next.high_contrast?"high":next.soft_contrast?"soft":"normal";root.dataset.hanamiDyslexia=next.dyslexia_friendly?"on":"off";root.dataset.hanamiMotion=next.reduce_motion?"reduced":"normal";root.dataset.hanamiGlitter=next.disable_glitter?"off":"on";root.dataset.hanamiCursor=next.custom_cursor_disabled?"standard":"custom";root.dataset.hanamiMusic=next.music_muted?"muted":"enabled";root.dataset.hanamiStudio=next.simplified_profile_studio?"simplified":"full";root.dataset.hanamiTheme=next.dark_mode?"dark":"light";window.dispatchEvent(new CustomEvent("hanami-accessibility-changed",{detail:next}));},[]);
 const load=useCallback(async()=>{const [n,s,p,a]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/notifications?select=id,category,title,body,href,is_read,created_at&order=created_at.desc&limit=50`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/system_announcements?select=id,title,body,severity,created_at&order=created_at.desc&limit=10`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/notification_preferences?select=*&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/accessibility_preferences?select=*&limit=1`,{headers:headers(accessToken)})]);
  if(n.ok)setNotifications(await n.json());if(s.ok)setSystemNotices(await s.json());if(p.ok){const rows=await p.json();if(rows[0])setPrefs(rows[0]);}if(a.ok){const rows=await a.json();if(rows[0]){const row=rows[0];const next:Accessibility={font_scale:Number(row.font_scale??1),high_contrast:Boolean(row.high_contrast),dyslexia_friendly:Boolean(row.dyslexia_friendly),reduce_motion:Boolean(row.reduce_motion),disable_glitter:Boolean(row.disable_glitter),simplified_profile_studio:Boolean(row.simplified_profile_studio),custom_cursor_disabled:Boolean(row.custom_cursor_disabled),music_muted:Boolean(row.music_muted),music_volume:Number(row.music_volume??.55),dark_mode:Boolean(row.dark_mode),soft_contrast:Boolean(row.soft_contrast),brightness:Number(row.brightness??1)};setAccess(next);applyAccessibility(next);}}setNotice("Notification Center ready.");},[accessToken,applyAccessibility]);
 useEffect(()=>{load().catch(()=>setNotice("Notifications could not be loaded."));},[load]);
 async function markRead(id:string){await fetch(`${SUPABASE_URL}/rest/v1/notifications?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({is_read:true})});setNotifications(items=>items.map(item=>item.id===id?{...item,is_read:true}:item));}
 async function markAllRead(){const response=await fetch(`${SUPABASE_URL}/rest/v1/notifications?is_read=eq.false`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({is_read:true})});if(response.ok){setNotifications(items=>items.map(item=>({...item,is_read:true})));setNotice("All notifications marked read.");}}
 async function savePrefs(next:Preferences){setPrefs(next);const response=await fetch(`${SUPABASE_URL}/rest/v1/notification_preferences?on_conflict=user_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify(next)});setNotice(response.ok?"Notification preferences saved.":"Notification preferences could not be saved.");}
 async function saveAccess(next:Accessibility){setAccess(next);applyAccessibility(next);const response=await fetch(`${SUPABASE_URL}/rest/v1/accessibility_preferences?on_conflict=user_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify(next)});setNotice(response.ok?"Accessibility settings saved and applied.":"Accessibility settings could not be saved.");}
 const toggles:Array<[string,keyof Accessibility,string]>=[["Higher contrast","high_contrast","Increase separation between page elements."],["Soft contrast","soft_contrast","Reduce harsh contrast without switching to dark mode."],["Dyslexia-friendly text","dyslexia_friendly","Use a simpler, more open reading style."],["Reduce animations","reduce_motion","Reduce transitions, movement, marquees, and animated profile effects."],["Disable glitter effects","disable_glitter","Hide decorative glitter and sparkle animation while keeping layouts intact."],["Use simplified Profile Studio","simplified_profile_studio","Prefer a reduced-control editor that is easier on phones and smaller screens."],["Disable custom cursors","custom_cursor_disabled","Always use your browser/system cursor instead of profile cursors."],["Mute profile music","music_muted","Prevent profile music from playing automatically."],["Dark display mode","dark_mode","Use the darker Hanami display treatment where supported."]];
 return <section style={{marginTop:16,border:"1px solid #aab7c6",background:"#fff"}} aria-label="Notifications and accessibility">
  <div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 14px",background:"#eef3f8",borderBottom:"1px solid #c5ced8",alignItems:"center",flexWrap:"wrap"}}><div><p className="eyebrow">HANAMI NETWORK</p><h4 style={{margin:"3px 0",font:"400 20px Georgia,serif"}}>Notification Center</h4><small>{notice}</small></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" onClick={()=>setOpen(v=>!v)} style={{minHeight:34}}>🔔 Notifications {unread?`(${unread})`:""}</button>{unread>0&&<button type="button" onClick={markAllRead} style={{minHeight:34}}>Mark all read</button>}<button type="button" onClick={()=>setSettingsOpen(v=>!v)} style={{minHeight:34}}>Accessibility & Preferences</button></div></div>
  {systemNotices.length>0&&<div style={{padding:"10px 14px",background:"#fff8dc",borderBottom:"1px solid #dbc981"}}>{systemNotices.map(item=><article key={item.id} style={{marginBottom:6}}><strong>[{item.severity.toUpperCase()}] {item.title}</strong><div style={{fontSize:10,marginTop:2}}>{item.body}</div></article>)}</div>}
  {open&&<div style={{padding:14,display:"grid",gap:8}}>{notifications.length?notifications.map(item=><article key={item.id} style={{padding:10,border:"1px solid #ccd4dc",background:item.is_read?"#fff":"#f3f8ff"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{item.title}</strong><small>{item.category.replaceAll("_"," ")}</small></div><p style={{margin:"5px 0",fontSize:10}}>{item.body}</p>{item.href&&<a href={item.href} style={{fontSize:9}}>Open related item →</a>}{!item.is_read&&<button type="button" onClick={()=>markRead(item.id)}>Mark read</button>}</article>):<p>No notifications yet.</p>}</div>}
  {settingsOpen&&<div style={{padding:14,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14}}><div><h5>Accessibility & Profile Effects</h5><label style={{display:"block",marginBottom:8}}>Font size <select value={access.font_scale} onChange={e=>saveAccess({...access,font_scale:Number(e.target.value)})}><option value={0.9}>Smaller</option><option value={1}>Standard</option><option value={1.1}>Large</option><option value={1.2}>Extra large</option><option value={1.3}>Maximum</option></select></label><label style={{display:"block",marginBottom:9}}>Display brightness <input type="range" min="0.7" max="1.15" step="0.05" value={access.brightness} onChange={e=>saveAccess({...access,brightness:Number(e.target.value)})}/></label><label style={{display:"block",marginBottom:9}}>Profile music volume <input type="range" min="0" max="1" step="0.05" disabled={access.music_muted} value={access.music_volume} onChange={e=>saveAccess({...access,music_volume:Number(e.target.value)})}/></label>{toggles.map(([label,key,help])=><label key={key} style={{display:"grid",gridTemplateColumns:"auto 1fr",gap:"2px 7px",marginBottom:8,alignItems:"start"}}><input type="checkbox" checked={Boolean(access[key])} onChange={e=>saveAccess({...access,[key]:e.target.checked})}/><span>{label}<small style={{display:"block",color:"#6d7987",fontSize:8,marginTop:2}}>{help}</small></span></label>)}</div><div><h5>Notification Preferences</h5><p style={{fontSize:9,color:"#66758a"}}>Control which categories should create a bell notification. Critical account or safety notices may still appear as required banners.</p>{Object.entries(prefs).map(([key,value])=><label key={key} style={{display:"block",marginBottom:6}}><input type="checkbox" checked={Boolean(value)} onChange={e=>savePrefs({...prefs,[key]:e.target.checked})}/> {key.replaceAll("_"," ")}</label>)}</div></div>}
 </section>;
}
