"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./OfficeRequestPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type RequestType="schedule_change"|"records"|"club_paperwork"|"technical_help"|"general";
type RequestStatus="submitted"|"in_review"|"waiting_on_member"|"resolved"|"closed";
type RequestRow={id:string;request_type:RequestType;subject:string;body:string;status:RequestStatus;staff_note:string;created_at:string;updated_at:string;closed_at:string|null};
type Props={accessToken:string;characterId:string};
const labels:Record<RequestType,string>={schedule_change:"Schedule Change",records:"Records / Documents",club_paperwork:"Club Paperwork",technical_help:"Technical Help",general:"General Office Help"};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function timeLabel(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}

export default function OfficeRequestPanel({accessToken,characterId}:Props){
 const [rows,setRows]=useState<RequestRow[]>([]);const [type,setType]=useState<RequestType>("general");const [subject,setSubject]=useState("");const [body,setBody]=useState("");const [replyDrafts,setReplyDrafts]=useState<Record<string,string>>({});const [status,setStatus]=useState("Loading your School Office requests…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_office_requests?select=id,request_type,subject,body,status,staff_note,created_at,updated_at,closed_at&character_id=eq.${encodeURIComponent(characterId)}&order=created_at.desc`,{headers:headers(accessToken)});if(!response.ok)throw new Error("Your School Office requests could not be loaded.");const data=await response.json() as RequestRow[];setRows(data);setStatus(data.length?`${data.length} School Office request${data.length===1?"":"s"} on file.`:"No School Office requests yet.");},[accessToken,characterId]);
 useEffect(()=>{load().catch(error=>setStatus(error instanceof Error?error.message:"School Office could not be loaded."));},[load]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const cleanSubject=subject.trim();const cleanBody=body.trim();if(cleanSubject.length<2||cleanSubject.length>140||!cleanBody){setStatus("Add a subject and message before submitting.");return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_office_requests`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({character_id:characterId,request_type:type,subject:cleanSubject,body:cleanBody,status:"submitted",staff_note:""})});if(!response.ok)throw new Error("Your request could not be submitted.");setSubject("");setBody("");await load();setStatus("Request submitted to the Hanami School Office. No external email was sent.");}catch(error){setStatus(error instanceof Error?error.message:"Your request could not be submitted.");}finally{setSaving(false);}}
 async function respond(row:RequestRow){const message=(replyDrafts[row.id]??"").trim();if(row.status!=="waiting_on_member"||!message)return;setSaving(true);try{const updatedBody=`${row.body}\n\nMEMBER FOLLOW-UP — ${new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Tokyo"}).format(new Date())}\n${message}`;const response=await fetch(`${SUPABASE_URL}/rest/v1/school_office_requests?id=eq.${encodeURIComponent(row.id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({body:updatedBody,status:"submitted",staff_note:"",assigned_to:null,closed_at:null,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Your follow-up could not be sent.");setReplyDrafts(current=>({...current,[row.id]:""}));await load();setStatus("Follow-up returned to the School Office.");}catch(error){setStatus(error instanceof Error?error.message:"Your follow-up could not be sent.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="office-request-title"><div className={styles.heading}><div><p className="eyebrow">SCHOOL OFFICE</p><h4 id="office-request-title">Requests & support</h4></div><span>WEBSITE-NATIVE</span></div><div className={styles.status} aria-live="polite">{status}</div><form className={styles.form} onSubmit={submit}><label><span>Request type</span><select value={type} onChange={event=>setType(event.target.value as RequestType)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Subject</span><input value={subject} onChange={event=>setSubject(event.target.value)} maxLength={140} placeholder="What do you need help with?"/></label><label className={styles.full}><span>Message</span><textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={5000} placeholder="Describe your request for the Hanami School Office."/></label><button type="submit" disabled={saving}>{saving?"Sending…":"Submit inside Hanami"}</button><small>No external email is used. This request stays attached to your active character.</small></form><div className={styles.list}>{rows.map(row=><article key={row.id}><div className={styles.itemHead}><div><b>{row.subject}</b><span>{labels[row.request_type]}</span></div><strong data-status={row.status}>{row.status.replaceAll("_"," ").toUpperCase()}</strong></div><p className={styles.body}>{row.body}</p>{row.staff_note&&<div className={styles.staffNote}><b>SCHOOL OFFICE RESPONSE</b><p>{row.staff_note}</p></div>}<small>Opened {timeLabel(row.created_at)} • Updated {timeLabel(row.updated_at)}</small>{row.status==="waiting_on_member"&&<div className={styles.followup}><label><span>Office needs more information</span><textarea value={replyDrafts[row.id]??""} onChange={event=>setReplyDrafts(current=>({...current,[row.id]:event.target.value}))} maxLength={3000} placeholder="Add your follow-up…"/></label><button type="button" onClick={()=>respond(row)} disabled={saving||!(replyDrafts[row.id]??"").trim()}>Send follow-up</button></div>}</article>)}</div></section>;
}
