"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Course={code:string;title:string;department:string;credits:number};
type Bot={display_name:string;handle:string;department:string;staff_title:string;specialty:string};
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
export default function OwnerFacultyQaPanel({accessToken,characterId}:{accessToken:string;characterId:string}){
 const [owner,setOwner]=useState(false);const [courses,setCourses]=useState<Course[]>([]);const [bots,setBots]=useState<Bot[]>([]);const [notice,setNotice]=useState("Checking Owner QA fixtures…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const ownerResponse=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});const isOwner=ownerResponse.ok&&Boolean(await ownerResponse.json());setOwner(isOwner);if(!isOwner){setNotice("Owner QA tools unavailable.");return;}const [courseResponse,botResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=code,title,department,credits&is_test_data=eq.true&order=code.asc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/test_bot_faculty?select=display_name,handle,department,staff_title,specialty&order=handle.asc`,{headers:headers(accessToken)})]);if(courseResponse.ok)setCourses(await courseResponse.json());if(botResponse.ok)setBots(await botResponse.json());setNotice("Owner QA fixture pack ready.");},[accessToken]);
 useEffect(()=>{load().catch(()=>setNotice("Owner QA fixtures could not be loaded."));},[load]);
 async function attachPack(){setSaving(true);setNotice("Attaching QA classes and Nurse role to this TEST Faculty character…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/attach_owner_test_faculty_qa_pack`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:characterId,include_nurse:true})});if(!response.ok){const detail=await response.text();throw new Error(detail||"QA pack could not be attached.");}setNotice("QA pack attached. Reloading Faculty Portal so Nurse Dashboard access becomes available…");window.setTimeout(()=>window.location.reload(),700);}catch(error){setNotice(error instanceof Error?error.message:"QA pack could not be attached.");setSaving(false);}}
 if(!owner)return null;
 return <section style={{marginTop:14,border:"2px solid #8e4364",background:"#fff8fb"}}><div style={{padding:"11px 13px",background:"#f5dce8",borderBottom:"1px solid #d5a8bb"}}><p className="eyebrow">OWNER ONLY • QA LAB</p><h4 style={{margin:"3px 0",font:"400 20px Georgia,serif"}}>TEST Faculty fixture pack</h4><small>{notice}</small></div><div style={{padding:12,display:"grid",gap:12}}><div><button type="button" onClick={attachPack} disabled={saving} style={{minHeight:36,padding:"7px 11px",border:"1px solid #17375f",background:"#17375f",color:"#fff",fontWeight:700,cursor:"pointer"}}>{saving?"Attaching…":"Attach all TEST classes + Nurse access"}</button><p style={{fontSize:9,color:"#687789",lineHeight:1.5}}>This keeps the character Faculty-role compatible while enabling the alternate Nurse Dashboard. TEST/BOT Faculty below are data-only and cannot sign in.</p></div><div><strong style={{fontSize:9}}>TEST CLASSES</strong><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:7,marginTop:6}}>{courses.map(c=><article key={c.code} style={{padding:9,border:"1px solid #cfbac4",background:"#fff"}}><b>{c.code}</b><div>{c.title}</div><small>{c.department} • {c.credits} credit{c.credits===1?"":"s"}</small></article>)}</div></div><div><strong style={{fontSize:9}}>OWNER-ONLY BOT FACULTY</strong><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:7,marginTop:6}}>{bots.map(b=><article key={b.handle} style={{padding:9,border:"1px solid #b9c7d2",background:"#f8fbfd"}}><b>{b.display_name}</b><div>@{b.handle}</div><small>{b.department} • {b.specialty}</small></article>)}</div></div></div></section>;
}
