"use client";

import {ChangeEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./PortalAppearancePanel.module.css";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";const IMAGE_TYPES=["image/jpeg","image/png","image/gif","image/webp"];const MAX_IMAGE_SIZE=5*1024*1024;
type PortalPreference={text_color:string;accent_color:string};type Skin={sidebar?:string;surface?:string;radius?:string;pattern?:string};type CharacterPreference={profile_image_path:string|null;class_banner_colors:Record<string,string>;class_banner_images:Record<string,string>;dashboard_background_path:string|null;portal_skin:Skin};type Course={code:string;title:string};type Section={id:string;section_code:string;academic_courses:Course|null};type Membership={relationship:"student"|"instructor";class_sections:Section|null};type Props={accessToken:string;characterId:string;displayName:string;role:"student"|"faculty"};
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}function validHex(value:string){return /^#[0-9a-f]{6}$/i.test(value);}function uploadPath(characterId:string,label:string,file:File){const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1];return `${characterId}/${label}-${crypto.randomUUID()}.${ext}`;}
const PRESETS:{name:string;skin:Skin;accent:string}[]=[{name:"Sakura",accent:"#d985a0",skin:{sidebar:"#dda2b4",surface:"#fff9fb",radius:"15px",pattern:"soft"}},{name:"Blue Gingham",accent:"#6586b2",skin:{sidebar:"#8fa8c8",surface:"#f7faff",radius:"12px",pattern:"gingham"}},{name:"Lavender",accent:"#9a78bd",skin:{sidebar:"#aa8bc8",surface:"#fbf8ff",radius:"16px",pattern:"floral"}},{name:"Burgundy",accent:"#6f1f2b",skin:{sidebar:"#5f1722",surface:"#fffafa",radius:"10px",pattern:"minimal"}}];
export default function PortalAppearancePanel({accessToken,characterId,displayName,role}:Props){
 const [portal,setPortal]=useState<PortalPreference>({text_color:"#2d3b45",accent_color:"#d985a0"});const [character,setCharacter]=useState<CharacterPreference>({profile_image_path:null,class_banner_colors:{},class_banner_images:{},dashboard_background_path:null,portal_skin:{}});const [memberships,setMemberships]=useState<Membership[]>([]);const [avatarUrl,setAvatarUrl]=useState("");const [status,setStatus]=useState("Loading appearance settings…");const [saving,setSaving]=useState(false);const expected=role==="student"?"student":"instructor";const classes=useMemo(()=>memberships.filter(row=>row.relationship===expected&&row.class_sections).map(row=>row.class_sections!),[memberships,expected]);
 const loadAvatar=useCallback(async(path:string|null)=>{if(!path){setAvatarUrl("");return;}const response=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/profile-media/${encodeURI(path)}`,{headers:headers(accessToken)});if(response.ok)setAvatarUrl(URL.createObjectURL(await response.blob()));},[accessToken]);
 const load=useCallback(async()=>{try{const select="relationship,class_sections(id,section_code,academic_courses(code,title))";const [p,c,m]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/portal_ui_preferences?select=text_color,accent_color&limit=1`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?select=profile_image_path,class_banner_colors,class_banner_images,dashboard_background_path,portal_skin&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)})]);if(!p.ok||!c.ok||!m.ok)throw new Error("Appearance settings could not be loaded.");setPortal((await p.json() as PortalPreference[])[0]??{text_color:"#2d3b45",accent_color:"#d985a0"});const row=(await c.json() as CharacterPreference[])[0]??{profile_image_path:null,class_banner_colors:{},class_banner_images:{},dashboard_background_path:null,portal_skin:{}};setCharacter(row);setMemberships(await m.json() as Membership[]);await loadAvatar(row.profile_image_path);setStatus("Appearance settings ready.");}catch(e){setStatus(e instanceof Error?e.message:"Appearance settings could not be loaded.");}},[accessToken,characterId,loadAvatar]);useEffect(()=>{void load();return()=>{if(avatarUrl.startsWith("blob:"))URL.revokeObjectURL(avatarUrl);};},[load]);
 async function savePortalTheme(next=portal){if(!validHex(next.text_color)||!validHex(next.accent_color))return;setSaving(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/portal_ui_preferences?on_conflict=user_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({...next,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Portal colors could not be saved.");document.documentElement.style.setProperty("--hanami-portal-text",next.text_color);document.documentElement.style.setProperty("--hanami-portal-accent",next.accent_color);setStatus("Portal theme saved.");}catch(e){setStatus(e instanceof Error?e.message:"Theme could not be saved.");}finally{setSaving(false);}}
 async function saveCharacter(next:CharacterPreference,message="Appearance could not be saved."){const r=await fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({...next,character_id:characterId,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(message);setCharacter(next);window.dispatchEvent(new CustomEvent("hanami-character-identity-changed",{detail:{characterId}}));}
 async function uploadFile(file:File,label:string){if(!IMAGE_TYPES.includes(file.type)||file.size>MAX_IMAGE_SIZE)throw new Error("Images support JPEG, PNG, GIF, or WebP up to 5 MB.");const path=uploadPath(characterId,label,file);const r=await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":file.type,"x-upsert":"false"}),body:file});if(!r.ok)throw new Error("Image upload failed.");return path;}
 async function uploadAvatar(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,"avatar");await saveCharacter({...character,profile_image_path:path});await loadAvatar(path);setStatus("Profile image updated.");}catch(x){setStatus(x instanceof Error?x.message:"Upload failed.");}finally{setSaving(false);}}
 async function uploadBanner(sectionId:string,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,`course-${sectionId}`);await saveCharacter({...character,class_banner_images:{...character.class_banner_images,[sectionId]:path}});setStatus("Course-card image saved.");}catch(x){setStatus(x instanceof Error?x.message:"Upload failed.");}finally{setSaving(false);}}
 async function uploadBackground(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,"dashboard-bg");await saveCharacter({...character,dashboard_background_path:path});setStatus("Dashboard background saved.");}catch(x){setStatus(x instanceof Error?x.message:"Upload failed.");}finally{setSaving(false);}}
 async function setBanner(sectionId:string,color:string){if(!validHex(color))return;setSaving(true);try{await saveCharacter({...character,class_banner_colors:{...character.class_banner_colors,[sectionId]:color}});setStatus("Class banner color saved.");}finally{setSaving(false);}}
 async function applyPreset(preset:(typeof PRESETS)[number]){const nextPortal={...portal,accent_color:preset.accent};const nextCharacter={...character,portal_skin:preset.skin};setPortal(nextPortal);setSaving(true);try{await Promise.all([savePortalTheme(nextPortal),saveCharacter(nextCharacter)]);setStatus(`${preset.name} workspace applied.`);}finally{setSaving(false);}}
 return <section className={styles.panel}><div className={styles.heading}><p className="eyebrow">BETTERCANVAS STUDIO</p><h4>Customize your Canvas-style workspace</h4><p>Personalize the shell, course images, colors, and dashboard background while keeping every school feature intact.</p></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Quick themes</strong><span>Apply a complete Canvas-inspired aesthetic.</span></div><div className={styles.presetGrid}>{PRESETS.map(p=><button type="button" key={p.name} onClick={()=>void applyPreset(p)} style={{"--swatch":p.accent} as React.CSSProperties}><i/><span>{p.name}</span></button>)}</div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Portal colors</strong><span>Used throughout Student, Faculty, Admin, and Owner interfaces.</span></div><div className={styles.controls}><div className={styles.colorGrid}><label className={styles.colorField}><input type="color" value={portal.text_color} onChange={e=>setPortal({...portal,text_color:e.target.value})}/><span>Text<code>{portal.text_color}</code></span></label><label className={styles.colorField}><input type="color" value={portal.accent_color} onChange={e=>setPortal({...portal,accent_color:e.target.value})}/><span>Accent<code>{portal.accent_color}</code></span></label></div><button className={styles.button} type="button" onClick={()=>void savePortalTheme()}>Save portal colors</button></div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Dashboard wallpaper</strong><span>Add a subtle image behind the Canvas workspace.</span></div><label className={styles.uploadLabel}>Upload background<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadBackground}/></label></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Profile image</strong><span>Shown in the Canvas account navigation.</span></div><div className={styles.avatarRow}><div className={styles.avatar}>{avatarUrl?<img src={avatarUrl} alt=""/>:displayName.slice(0,1)}</div><label className={styles.uploadLabel}>Choose profile image<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadAvatar}/></label></div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Course cards</strong><span>Use custom colors or upload aesthetic images/patterns for each class card.</span></div><div className={styles.classList}>{classes.map(section=>{const color=character.class_banner_colors[section.id]??portal.accent_color;return <div className={styles.classRow} key={section.id}><div><strong>{section.academic_courses?.title??"Untitled course"}</strong><span>{section.academic_courses?.code??"COURSE"} · Section {section.section_code}</span></div><div className={styles.bannerActions}><label className={styles.bannerControl}><input type="color" value={validHex(color)?color:portal.accent_color} onChange={e=>void setBanner(section.id,e.target.value)}/><span>Color</span></label><label className={styles.uploadLabel}>Upload image<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={e=>void uploadBanner(section.id,e)}/></label>{character.class_banner_images[section.id]&&<button type="button" className={styles.clearButton} onClick={()=>void saveCharacter({...character,class_banner_images:{...character.class_banner_images,[section.id]:""}})}>Remove image</button>}</div></div>})}</div></div><div className={styles.status} aria-live="polite">{saving?"Saving…":status}</div></section>;
}
