"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./PortalContextBar.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Role="student"|"faculty";type Target={view:string;subView:string;label:string};type Change={id:string;title:string;summary:string;version:string|null;published_at:string};
const HELP:Record<string,string>={
 "home.overview":"See the live school day, priorities, notices, deadlines, roleplay, lunch, events, and your quickest routes back into school life.",
 "classes.overview":"Open enrolled courses or teaching sections, then move into assignments, grading, classroom operations, or academic support.",
 "classes.assignments":"Review active coursework, submission status, deadlines, teacher feedback, and class requirements.",
 "school.homeroom":"See your classmates, adviser, seating identity, bulletin, class goals, events, rankings, and homeroom memories.",
 "school.identity":"Manage your school identity, yearbook presence, milestones, reputation, achievements, signatures, and notifications.",
 "school.services":"Use Hanami school services including library, cafeteria, school store, requests, tutoring, lost and found, and support systems.",
 "community.activities":"Browse Tuesday/Wednesday clubs, weekend sports, and election-only Student Council activity paths.",
 "community.friends":"Manage friendships, relationship context, shared memories, and social connections.",
 "profile.designer":"Build your character page with profile widgets, templates, scrapbook content, stickers, and layout tools.",
 "messages.inbox":"Read and send Hanami messages without leaving the school website."
};
function shortcuts(view:string,role:Role):Target[]{if(view==="home")return[{view:"schedule",subView:"week",label:"Weekly Schedule"},{view:"classes",subView:"overview",label:role==="student"?"My Courses":"Teaching Courses"},{view:"school",subView:"life",label:"School Life"},{view:"messages",subView:"inbox",label:"Inbox"}];if(view==="classes")return role==="student"?[{view:"classes",subView:"assignments",label:"Assignments"},{view:"schedule",subView:"week",label:"Schedule"},{view:"school",subView:"officehours",label:"Office Hours"},{view:"school",subView:"records",label:"Academic Record"}]:[{view:"classes",subView:"teaching",label:"Course Setup"},{view:"classes",subView:"grading",label:"Grading"},{view:"school",subView:"attendance",label:"Attendance"},{view:"school",subView:"tools",label:"Faculty Tools"}];if(view==="school")return role==="student"?[{view:"school",subView:"homeroom",label:"Homeroom"},{view:"school",subView:"services",label:"Student Services"},{view:"school",subView:"progress",label:"Progress Center"},{view:"school",subView:"resources",label:"Resources"}]:[{view:"school",subView:"tools",label:"Faculty Tools"},{view:"school",subView:"attendance",label:"Attendance"},{view:"school",subView:"advising",label:"Advising"},{view:"school",subView:"resources",label:"Resources"}];if(view==="community")return role==="student"?[{view:"community",subView:"activities",label:"Activities"},{view:"community",subView:"friends",label:"Friends"},{view:"community",subView:"boards",label:"Community Boards"},{view:"community",subView:"campus",label:"Campus Systems"}]:[{view:"community",subView:"hub",label:"Community Hub"},{view:"community",subView:"friends",label:"Friends"},{view:"community",subView:"rumors",label:"Rumors"},{view:"messages",subView:"inbox",label:"Inbox"}];if(view==="profile")return[{view:"profile",subView:"profile",label:"Profile & Privacy"},{view:"profile",subView:"designer",label:"Profile Designer"},{view:"profile",subView:"people",label:"Find Profiles"},{view:"profile",subView:"preferences",label:"Preferences"}];return[{view:"home",subView:"overview",label:"Dashboard"},{view:"school",subView:"life",label:"School Life"},{view:"community",subView:"hub",label:"Community"}];}
function h(token:string){return{apikey:K,Authorization:`Bearer ${token}`}}
export default function PortalContextBar({accessToken,view,subView,role}:{accessToken:string;view:string;subView:string;role:Role}){const [change,setChange]=useState<Change|null>(null);const key=`${view}.${subView}`;const actions=useMemo(()=>shortcuts(view,role),[view,role]);useEffect(()=>{let dead=false;fetch(`${U}/rest/v1/page_changelog_entries?select=id,title,summary,version,published_at&page_key=eq.${encodeURIComponent(key)}&or=(visibility.eq.all,visibility.eq.${role})&order=published_at.desc&limit=1`,{headers:h(accessToken)}).then(async r=>r.ok?await r.json() as Change[]:[]).then(rows=>{if(!dead)setChange(rows[0]??null)}).catch(()=>undefined);return()=>{dead=true}},[accessToken,key,role]);function go(target:Target){window.dispatchEvent(new CustomEvent("hanami-portal-navigate",{detail:{view:target.view,subView:target.subView}}));}return <aside className={styles.bar} aria-label="Page help and contextual shortcuts"><div className={styles.help}><strong>What can I do here?</strong><span>{HELP[key]??"Use the shortcuts to move between the Hanami tools most closely related to this page without returning to the main dashboard."}</span></div><nav>{actions.map(item=><button type="button" key={`${item.view}.${item.subView}`} onClick={()=>go(item)}>{item.label}</button>)}</nav>{change&&<div className={styles.change}><b>Recently updated{change.version?` · v${change.version}`:""}</b><strong>{change.title}</strong><span>{change.summary}</span></div>}</aside>}
