"use client";

import {ChangeEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./PortalAppearancePanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const IMAGE_TYPES=["image/jpeg","image/png","image/gif","image/webp"];
const MAX_IMAGE_SIZE=5*1024*1024;

type PortalPreference={text_color:string;accent_color:string};
type Skin={sidebar?:string;surface?:string;radius?:string;pattern?:string;preset?:string;wallpaperOpacity?:number};
type CharacterPreference={profile_image_path:string|null;class_banner_colors:Record<string,string>;class_banner_images:Record<string,string>;dashboard_background_path:string|null;portal_skin:Skin};
type Course={code:string;title:string};
type Section={id:string;section_code:string;academic_courses:Course|null};
type Membership={relationship:"student"|"instructor";class_sections:Section|null};
type Props={accessToken:string;characterId:string;displayName:string;role:"student"|"faculty"};
type Preset={name:string;color:string;pattern:string;sidebarMix:number;surfaceMix:number};

const EMPTY_CHARACTER:CharacterPreference={profile_image_path:null,class_banner_colors:{},class_banner_images:{},dashboard_background_path:null,portal_skin:{wallpaperOpacity:.55}};
const PRESETS:Preset[]=[
 {name:"Sakura Pink",color:"#b34f75",pattern:"soft",sidebarMix:78,surfaceMix:5},
 {name:"Hanami Blue",color:"#416da8",pattern:"gingham",sidebarMix:78,surfaceMix:4},
 {name:"Lavender",color:"#76579b",pattern:"floral",sidebarMix:76,surfaceMix:5},
 {name:"Burgundy",color:"#7f304b",pattern:"minimal",sidebarMix:84,surfaceMix:3},
 {name:"Forest",color:"#456b55",pattern:"soft",sidebarMix:80,surfaceMix:4},
 {name:"Amber",color:"#9a612b",pattern:"minimal",sidebarMix:78,surfaceMix:4}
];

function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
function validHex(value:string){return /^#[0-9a-f]{6}$/i.test(value);}
function uploadPath(characterId:string,label:string,file:File){const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1];return `${characterId}/${label}-${crypto.randomUUID()}.${ext}`;}
function colorMix(accent:string,amount:number){return `color-mix(in srgb, ${accent} ${amount}%, #fff ${100-amount}%)`;}
function themedSkin(current:Skin,accent:string,preset="Custom",pattern=current.pattern??"minimal",sidebarMix=80,surfaceMix=4):Skin{return {...current,preset,pattern,radius:"0px",sidebar:colorMix(accent,sidebarMix),surface:colorMix(accent,surfaceMix)};}

export default function PortalAppearancePanel({accessToken,characterId,displayName,role}:Props){
 const [portal,setPortal]=useState<PortalPreference>({text_color:"#2d3b45",accent_color:"#d985a0"});
 const [character,setCharacter]=useState<CharacterPreference>(EMPTY_CHARACTER);
 const [memberships,setMemberships]=useState<Membership[]>([]);
 const [avatarUrl,setAvatarUrl]=useState("");
 const [bannerDrafts,setBannerDrafts]=useState<Record<string,string>>({});
 const [opacity,setOpacity]=useState(55);
 const [status,setStatus]=useState("Loading appearance settings…");
 const [saving,setSaving]=useState(false);
 const expected=role==="student"?"student":"instructor";
 const classes=useMemo(()=>memberships.filter(row=>row.relationship===expected&&row.class_sections).map(row=>row.class_sections!),[memberships,expected]);

 const loadAvatar=useCallback(async(path:string|null)=>{if(!path){setAvatarUrl("");return;}const response=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/profile-media/${encodeURI(path)}`,{headers:headers(accessToken)});if(response.ok)setAvatarUrl(URL.createObjectURL(await response.blob()));},[accessToken]);
 const load=useCallback(async()=>{try{const select="relationship,class_sections(id,section_code,academic_courses(code,title))";const [p,c,m]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/portal_ui_preferences?select=text_color,accent_color&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?select=profile_image_path,class_banner_colors,class_banner_images,dashboard_background_path,portal_skin&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)})
 ]);if(!p.ok||!c.ok||!m.ok)throw new Error("Appearance settings could not be loaded.");const portalRow=(await p.json() as PortalPreference[])[0]??{text_color:"#2d3b45",accent_color:"#d985a0"};const raw=(await c.json() as CharacterPreference[])[0]??EMPTY_CHARACTER;const row={...raw,portal_skin:{wallpaperOpacity:.55,...(raw.portal_skin??{})}};setPortal(portalRow);setCharacter(row);setOpacity(Math.round((row.portal_skin.wallpaperOpacity??.55)*100));setBannerDrafts(row.class_banner_colors??{});setMemberships(await m.json() as Membership[]);await loadAvatar(row.profile_image_path);setStatus("Appearance settings ready.");}catch(e){setStatus(e instanceof Error?e.message:"Appearance settings could not be loaded.");}},[accessToken,characterId,loadAvatar]);
 useEffect(()=>{void load();},[load]);

 async function errorText(response:Response,fallback:string){try{const body=await response.json() as {message?:string;hint?:string;details?:string};return body.message||body.hint||body.details||fallback;}catch{return fallback;}}
 async function persistPortalTheme(next:PortalPreference){const r=await fetch(`${SUPABASE_URL}/rest/v1/portal_ui_preferences?on_conflict=user_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({...next,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await errorText(r,"Portal colors could not be saved."));document.documentElement.style.setProperty("--hanami-portal-text",next.text_color);document.documentElement.style.setProperty("--hanami-portal-accent",next.accent_color);document.documentElement.style.setProperty("--hanami-portal-accent-soft",`${next.accent_color}18`);setPortal(next);window.dispatchEvent(new CustomEvent("hanami-portal-theme-changed",{detail:next}));}
 async function freshCharacter(){const r=await fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?select=profile_image_path,class_banner_colors,class_banner_images,dashboard_background_path,portal_skin&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)});if(!r.ok)throw new Error(await errorText(r,"Appearance settings could not be refreshed."));return (await r.json() as CharacterPreference[])[0]??EMPTY_CHARACTER;}
 async function saveCharacterPatch(patch:Partial<CharacterPreference>,message="Appearance could not be saved."){const current=await freshCharacter();const next:CharacterPreference={...current,...patch,class_banner_colors:patch.class_banner_colors??current.class_banner_colors??{},class_banner_images:patch.class_banner_images??current.class_banner_images??{},portal_skin:patch.portal_skin??current.portal_skin??{}};const r=await fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=representation"}),body:JSON.stringify({...next,character_id:characterId,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await errorText(r,message));setCharacter(next);setBannerDrafts(next.class_banner_colors);window.dispatchEvent(new CustomEvent("hanami-character-identity-changed",{detail:{characterId}}));return next;}
 async function saveColors(){if(!validHex(portal.text_color)||!validHex(portal.accent_color)){setStatus("Choose valid six-digit colors first.");return;}setSaving(true);try{await persistPortalTheme(portal);await saveCharacterPatch({portal_skin:themedSkin(character.portal_skin,portal.accent_color)});setStatus(`Text color ${portal.text_color} and theme color ${portal.accent_color} saved.`);}catch(e){setStatus(e instanceof Error?e.message:"Portal colors could not be saved.");}finally{setSaving(false);}}
 async function applyPreset(preset:Preset){const next={...portal,accent_color:preset.color};setSaving(true);try{await persistPortalTheme(next);await saveCharacterPatch({portal_skin:themedSkin(character.portal_skin,preset.color,preset.name,preset.pattern,preset.sidebarMix,preset.surfaceMix)});setStatus(`${preset.name} theme applied. Your text color remains ${next.text_color}.`);}catch(e){setStatus(e instanceof Error?e.message:"Quick theme could not be applied.");}finally{setSaving(false);}}
 async function uploadFile(file:File,label:string){if(!IMAGE_TYPES.includes(file.type)||file.size>MAX_IMAGE_SIZE)throw new Error("Images support JPEG, PNG, GIF, or WebP up to 5 MB.");const path=uploadPath(characterId,label,file);const r=await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":file.type,"x-upsert":"false"}),body:file});if(!r.ok)throw new Error(await errorText(r,"Image upload failed."));return path;}
 async function uploadAvatar(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,"avatar");await saveCharacterPatch({profile_image_path:path});await loadAvatar(path);setStatus("Profile image updated.");}catch(x){setStatus(x instanceof Error?x.message:"Upload failed.");}finally{setSaving(false);}}
 async function uploadBackground(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,"dashboard-bg");await saveCharacterPatch({dashboard_background_path:path});setStatus("Dashboard background saved.");}catch(x){setStatus(x instanceof Error?x.message:"Upload failed.");}finally{setSaving(false);}}
 async function saveOpacity(){setSaving(true);try{await saveCharacterPatch({portal_skin:{...character.portal_skin,wallpaperOpacity:opacity/100}});setStatus(`Dashboard background opacity saved at ${opacity}%.`);}catch(x){setStatus(x instanceof Error?x.message:"Background opacity could not be saved.");}finally{setSaving(false);}}
 async function callBannerRpc(name:"set_my_class_banner_color"|"set_my_class_banner_image",body:Record<string,string>){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await errorText(r,"Classroom banner could not be saved."));return await r.json() as Record<string,string>;}
 async function refreshBanners(colors?:Record<string,string>,images?:Record<string,string>){const latest=await freshCharacter();const next={...latest,class_banner_colors:colors??latest.class_banner_colors??{},class_banner_images:images??latest.class_banner_images??{}};setCharacter(next);setBannerDrafts(next.class_banner_colors);window.dispatchEvent(new CustomEvent("hanami-character-identity-changed",{detail:{characterId}}));}
 async function saveBannerColor(sectionId:string){const color=bannerDrafts[sectionId]??portal.accent_color;if(!validHex(color))return;setSaving(true);try{const colors=await callBannerRpc("set_my_class_banner_color",{p_character_id:characterId,p_section_id:sectionId,p_color:color});await refreshBanners(colors);setStatus(`Classroom banner color ${color} saved.`);}catch(x){setStatus(x instanceof Error?x.message:"Classroom banner color could not be saved.");}finally{setSaving(false);}}
 async function uploadBanner(sectionId:string,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setSaving(true);try{const path=await uploadFile(file,`course-${sectionId}`);const images=await callBannerRpc("set_my_class_banner_image",{p_character_id:characterId,p_section_id:sectionId,p_path:path});await refreshBanners(undefined,images);setStatus("Classroom banner image saved.");}catch(x){setStatus(x instanceof Error?x.message:"Classroom banner upload failed.");}finally{setSaving(false);}}
 async function clearBannerImage(sectionId:string){setSaving(true);try{const images=await callBannerRpc("set_my_class_banner_image",{p_character_id:characterId,p_section_id:sectionId,p_path:""});await refreshBanners(undefined,images);setStatus("Classroom banner image removed.");}catch(x){setStatus(x instanceof Error?x.message:"Classroom banner image could not be removed.");}finally{setSaving(false);}}

 return <section className={styles.panel}><div className={styles.heading}><p className="eyebrow">BETTERCANVAS STUDIO</p><h4>Customize your Canvas-style workspace</h4><p>Text and theme colors are independent. Personalize your portal without changing school functionality.</p></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Quick themes</strong><span>Quick themes change the portal accent, navigation rail, and surfaces. Your chosen text color stays separate.</span></div><div className={styles.presetGrid}>{PRESETS.map(p=><button type="button" key={p.name} disabled={saving} onClick={()=>void applyPreset(p)} style={{"--swatch":p.color} as React.CSSProperties}><i/><span>{p.name}</span></button>)}</div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Text & theme colors</strong><span>Choose the text color and the theme/accent color independently, then save both.</span></div><div className={styles.controls}><div className={styles.colorGrid}><label className={styles.colorField}><input type="color" value={portal.text_color} onChange={e=>setPortal(v=>({...v,text_color:e.target.value}))}/><span>Text color<code>{portal.text_color}</code></span></label><label className={styles.colorField}><input type="color" value={portal.accent_color} onChange={e=>setPortal(v=>({...v,accent_color:e.target.value}))}/><span>Theme / accent color<code>{portal.accent_color}</code></span></label></div><button className={styles.button} type="button" onClick={()=>void saveColors()} disabled={saving}>Save text & theme colors</button></div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Dashboard wallpaper</strong><span>Upload an image and choose how visible it is behind the portal.</span></div><div className={styles.controls}><label className={styles.uploadLabel}>Upload background<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadBackground}/></label><label className={styles.opacityControl}><span>Background opacity <b>{opacity}%</b></span><input type="range" min="0" max="100" step="1" value={opacity} onChange={e=>{setOpacity(Number(e.target.value));document.documentElement.style.setProperty("--hanami-wallpaper-opacity",String(Number(e.target.value)/100));}}/><button className={styles.button} type="button" onClick={()=>void saveOpacity()} disabled={saving}>Save opacity</button></label></div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Profile image</strong><span>Shown in the Canvas account navigation.</span></div><div className={styles.avatarRow}><div className={styles.avatar}>{avatarUrl?<img src={avatarUrl} alt=""/>:displayName.slice(0,1)}</div><label className={styles.uploadLabel}>Choose profile image<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadAvatar}/></label></div></div>
 <div className={styles.section}><div className={styles.sectionTitle}><strong>Classroom banners</strong><span>Choose a banner color or upload an image for each assigned class.</span></div><div className={styles.classList}>{classes.length===0?<p>No assigned classes are available to customize yet.</p>:classes.map(section=>{const saved=character.class_banner_colors[section.id]??portal.accent_color;const draft=bannerDrafts[section.id]??saved;return <div className={styles.classRow} key={section.id}><div><strong>{section.academic_courses?.title??"Untitled course"}</strong><span>{section.academic_courses?.code??"COURSE"} · Section {section.section_code}</span></div><div className={styles.bannerActions}><label className={styles.bannerControl}><input type="color" value={validHex(draft)?draft:portal.accent_color} onChange={e=>setBannerDrafts(v=>({...v,[section.id]:e.target.value}))}/><span>Color</span></label><button type="button" className={styles.button} disabled={saving} onClick={()=>void saveBannerColor(section.id)}>Save color</button><label className={styles.uploadLabel}>Upload image<input type="file" accept="image/jpeg,image/png,image/gif,image/webp" disabled={saving} onChange={e=>void uploadBanner(section.id,e)}/></label>{character.class_banner_images[section.id]&&<button type="button" className={styles.clearButton} disabled={saving} onClick={()=>void clearBannerImage(section.id)}>Remove image</button>}</div></div>})}</div></div>
 <div className={styles.status} aria-live="polite">{saving?"Saving…":status}</div></section>;
}
