"use client";

import {FormEvent,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalKind="administrator"|"owner";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
type Props={portalKind:PortalKind;allowOwnerBootstrap?:boolean;onUnlocked:()=>void};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}

export default function PrivilegedPortalLogin({portalKind,allowOwnerBootstrap=false,onUnlocked}:Props){
 const [handle,setHandle]=useState("");const [password,setPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [message,setMessage]=useState("Enter your privileged Hanami credentials.");const [saving,setSaving]=useState(false);const [canBootstrap,setCanBootstrap]=useState(false);const [accessToken,setAccessToken]=useState("");
 useEffect(()=>{let cancelled=false;async function check(){const session=readSession();if(!session){if(!cancelled)setMessage("Sign in with Discord through the Portal Gateway first.");return;}setAccessToken(session.accessToken);const existing=await fetch(`${SUPABASE_URL}/rest/v1/rpc/has_privileged_portal_session`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:portalKind})});if(existing.ok&&await existing.json()){if(!cancelled)onUnlocked();return;}if(allowOwnerBootstrap&&portalKind==="owner"){const [owner,configured]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_credential_configured`,{method:"POST",headers:headers(session.accessToken,{"Content-Type":"application/json"}),body:"{}"})]);if(owner.ok&&configured.ok){const isOwner=Boolean(await owner.json());const isConfigured=Boolean(await configured.json());if(!cancelled){setCanBootstrap(isOwner&&!isConfigured);setMessage(isOwner&&!isConfigured?"Owner credential setup is ready. Choose a private handle and password.":"Enter your Owner handle and password.");}}}}check();return()=>{cancelled=true;};},[allowOwnerBootstrap,onUnlocked,portalKind]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!accessToken||saving)return;const cleanHandle=handle.trim().toLowerCase();if(!/^[a-z0-9._@-]{3,64}$/.test(cleanHandle)){setMessage("Handle must be 3–64 lowercase letters, numbers, dots, @, hyphens, or underscores.");return;}if(password.length<12){setMessage("Privileged portal passwords must be at least 12 characters.");return;}setSaving(true);try{if(canBootstrap){if(password!==confirmPassword)throw new Error("The two Owner passwords do not match.");const bootstrap=await fetch(`${SUPABASE_URL}/rest/v1/rpc/bootstrap_owner_credential`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_handle:cleanHandle,requested_password:password})});if(!bootstrap.ok)throw new Error("Owner credentials could not be created.");setCanBootstrap(false);}
 const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/verify_privileged_portal_login`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_portal:portalKind,requested_handle:cleanHandle,requested_password:password})});if(!response.ok||!await response.json())throw new Error(`${portalKind==="owner"?"Owner":"Administrator"} credentials were not accepted.`);setPassword("");setConfirmPassword("");setMessage("Privileged portal unlocked.");onUnlocked();}catch(error){setMessage(error instanceof Error?error.message:"Privileged portal sign-in failed.");}finally{setSaving(false);}}
 return <section className="portal-account-card" aria-labelledby={`${portalKind}-signin-title`}><p className="eyebrow">{portalKind==="owner"?"OWNER SIGN IN":"ADMINISTRATOR SIGN IN"}</p><h2 id={`${portalKind}-signin-title`}>{canBootstrap?"Create your Owner credentials":"Additional verification required"}</h2><p className="portal-account-note">Discord verifies the account first. This handle/password is a separate privileged gate and is never stored in plaintext.</p><form onSubmit={submit} style={{display:"grid",gap:10,marginTop:14}}><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:4}}>PRIVILEGED HANDLE</span><input value={handle} onChange={event=>setHandle(event.target.value)} autoComplete="username" maxLength={64} required style={{width:"100%",boxSizing:"border-box",padding:9}}/></label><label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:4}}>PASSWORD</span><input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete={canBootstrap?"new-password":"current-password"} required style={{width:"100%",boxSizing:"border-box",padding:9}}/></label>{canBootstrap&&<label><span style={{display:"block",fontSize:8,fontWeight:700,marginBottom:4}}>CONFIRM PASSWORD</span><input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} autoComplete="new-password" required style={{width:"100%",boxSizing:"border-box",padding:9}}/></label>}<button className="discord-button" type="submit" disabled={saving}>{saving?"Verifying…":canBootstrap?"Create Owner Sign In":"Unlock Portal"}</button></form><small aria-live="polite">{message}</small></section>;
}
