"use client";

import {ChangeEvent,KeyboardEvent as ReactKeyboardEvent,PointerEvent,useCallback,useEffect,useMemo,useRef,useState} from "react";
import styles from "./ProfileStudioPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type WidgetType="text"|"image"|"card"|"link"|"divider"|"sticker"|"quote"|"playlist"|"photo_strip"|"badge"|"marquee"|"guestbook";
type Canvas={character_id:string;canvas_width:number;canvas_height:number;background:string;background_image_url:string|null;grid_enabled:boolean;snap_enabled:boolean};
type Widget={id:string;character_id:string;widget_type:WidgetType;x:number;y:number;width:number;height:number;z_index:number;rotation:number;opacity:number;content:Record<string,string>;style:Record<string,string|number>;locked:boolean};
type Snapshot=Widget[];
type DragState={startX:number;startY:number;scale:number;bases:{id:string;x:number;y:number}[]};
type ResizeState={id:string;startX:number;startY:number;scale:number;width:number;height:number};
type Props={accessToken:string;characterId:string};

type DefaultWidget={w:number;h:number;content:Record<string,string>;style:Record<string,string|number>};
const defaults:Record<WidgetType,DefaultWidget>={
 text:{w:360,h:90,content:{text:"Double-click your idea here"},style:{fontSize:32,fontFamily:"Georgia, serif",color:"#17375f",textAlign:"left",background:"transparent",borderRadius:0,borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"none"}},
 image:{w:320,h:220,content:{url:"",storage_path:"",alt:"Profile image"},style:{background:"#eef3f8",borderRadius:12,borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"none",objectFit:"cover",objectPosition:"50% 50%",flipX:1,flipY:1}},
 card:{w:360,h:180,content:{text:"Add a note, bio block, favorites list, or anything else."},style:{fontSize:18,fontFamily:"Arial, sans-serif",color:"#17375f",background:"#ffffff",borderRadius:14,borderWidth:1,borderColor:"#d7b9c5",borderStyle:"solid",boxShadow:"none"}},
 link:{w:280,h:58,content:{text:"My link",url:"https://"},style:{fontSize:16,fontFamily:"Arial, sans-serif",color:"#ffffff",background:"#17375f",borderRadius:10,textAlign:"center",borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"none"}},
 divider:{w:420,h:12,content:{},style:{background:"#d7a7bb",borderRadius:99,borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"none"}},
 sticker:{w:120,h:120,content:{text:"花"},style:{fontSize:64,fontFamily:"Georgia, serif",color:"#9b315b",background:"#f7dce7",borderRadius:22,textAlign:"center",borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"0 4px 10px rgba(23,55,95,.12)"}},
 quote:{w:430,h:150,content:{text:"“Put a character quote or favorite saying here.”",credit:"— Character note"},style:{fontSize:24,fontFamily:"Georgia, serif",color:"#17375f",background:"#fff7fb",borderRadius:18,textAlign:"left",borderWidth:1,borderColor:"#ead0dc",borderStyle:"solid",boxShadow:"none"}},
 playlist:{w:430,h:260,content:{text:"NOW PLAYING\n01. Track title — Artist\n02. Track title — Artist\n03. Track title — Artist"},style:{fontSize:17,fontFamily:"Courier New, monospace",color:"#17375f",background:"#eef3f8",borderRadius:12,textAlign:"left",borderWidth:1,borderColor:"#b8c8d9",borderStyle:"solid",boxShadow:"none"}},
 photo_strip:{w:520,h:180,content:{text:"PHOTO STRIP",url:"",storage_path:"",alt:"Profile photo strip"},style:{fontSize:16,fontFamily:"Arial, sans-serif",color:"#17375f",background:"#ffffff",borderRadius:8,textAlign:"center",borderWidth:1,borderColor:"#d7b9c5",borderStyle:"solid",boxShadow:"0 3px 8px rgba(23,55,95,.10)",objectFit:"cover",objectPosition:"50% 50%",flipX:1,flipY:1}},
 badge:{w:180,h:70,content:{text:"HANAMI CLUB"},style:{fontSize:16,fontFamily:"Arial, sans-serif",color:"#ffffff",background:"#8f365b",borderRadius:99,textAlign:"center",borderWidth:0,borderColor:"#17375f",borderStyle:"solid",boxShadow:"none"}},
 marquee:{w:560,h:58,content:{text:"★ welcome to my hanami page ★"},style:{fontSize:18,fontFamily:"Courier New, monospace",color:"#8f365b",background:"#fff4f7",borderRadius:4,textAlign:"center",borderWidth:1,borderColor:"#e8bfd0",borderStyle:"solid",boxShadow:"none"}},
 guestbook:{w:460,h:240,content:{text:"GUESTBOOK / LINK BOARD\nUse this for character links, shout-outs, and profile navigation."},style:{fontSize:17,fontFamily:"Arial, sans-serif",color:"#17375f",background:"#ffffff",borderRadius:12,textAlign:"left",borderWidth:1,borderColor:"#d7b9c5",borderStyle:"solid",boxShadow:"none"}}
};
const basicTypes:WidgetType[]=["text","image","card","link","divider","sticker"];
const socialTypes:WidgetType[]=["quote","playlist","photo_strip","badge","marquee","guestbook"];
const clone=(items:Widget[])=>items.map(w=>({...w,content:{...w.content},style:{...w.style}}));

export default function ProfileStudioV2Panel({accessToken,characterId}:Props){
 const [canvas,setCanvas]=useState<Canvas|null>(null);const [widgets,setWidgets]=useState<Widget[]>([]);const [selectedIds,setSelectedIds]=useState<string[]>([]);const [status,setStatus]=useState("Opening Profile Studio V2…");const [saving,setSaving]=useState(false);const [past,setPast]=useState<Snapshot[]>([]);const [future,setFuture]=useState<Snapshot[]>([]);const [mediaUrls,setMediaUrls]=useState<Record<string,string>>({});const [zoom,setZoom]=useState(0.8);const [copiedStyle,setCopiedStyle]=useState<Record<string,string|number>|null>(null);const [showLayers,setShowLayers]=useState(true);
 const drag=useRef<DragState|null>(null);const resize=useRef<ResizeState|null>(null);const studioRef=useRef<HTMLElement|null>(null);
 const selectedWidgets=useMemo(()=>widgets.filter(w=>selectedIds.includes(w.id)),[widgets,selectedIds]);const selected=selectedWidgets[selectedWidgets.length-1]??null;
 const checkpoint=useCallback(()=>{setPast(v=>[...v.slice(-24),clone(widgets)]);setFuture([]);},[widgets]);
 const loadMedia=useCallback(async(items:Widget[])=>{const paths=[...new Set(items.map(w=>w.content.storage_path).filter(Boolean))];const next:Record<string,string>={};await Promise.all(paths.map(async path=>{const r=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/profile-media/${encodeURI(path)}`,{headers:headers(accessToken)});if(r.ok)next[path]=URL.createObjectURL(await r.blob());}));setMediaUrls(old=>{Object.values(old).forEach(url=>url.startsWith("blob:")&&URL.revokeObjectURL(url));return next;});},[accessToken]);
 const load=useCallback(async()=>{const [c,w]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?select=character_id,canvas_width,canvas_height,background,background_image_url,grid_enabled,snap_enabled&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?select=id,character_id,widget_type,x,y,width,height,z_index,rotation,opacity,content,style,locked&character_id=eq.${encodeURIComponent(characterId)}&order=z_index.asc`,{headers:headers(accessToken)})]);if(!c.ok||!w.ok)throw new Error("Profile Studio could not be loaded.");let active=(await c.json() as Canvas[])[0]??null;if(!active){const create=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({character_id:characterId})});if(!create.ok)throw new Error("Profile canvas could not be created.");active=(await create.json() as Canvas[])[0]??null;}const rows=await w.json() as Widget[];setCanvas(active);setWidgets(rows);setSelectedIds([]);setPast([]);setFuture([]);await loadMedia(rows);setStatus(rows.length?`${rows.length} widget${rows.length===1?"":"s"} loaded. Enhanced editor ready.`:"Blank canvas ready.");},[accessToken,characterId,loadMedia]);
 useEffect(()=>{load().catch(e=>setStatus(e instanceof Error?e.message:"Profile Studio could not be loaded."));},[load]);
 async function persistWidget(widget:Widget){return fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?id=eq.${widget.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({x:widget.x,y:widget.y,width:widget.width,height:widget.height,z_index:widget.z_index,rotation:widget.rotation,opacity:widget.opacity,content:widget.content,style:widget.style,locked:widget.locked,updated_at:new Date().toISOString()})});}
 async function patchWidget(id:string,patch:Partial<Widget>,track=true){if(track)checkpoint();setWidgets(v=>v.map(w=>w.id===id?{...w,...patch}:w));const r=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!r.ok){setStatus("A widget change could not be saved. Reloading…");await load();}}
 async function patchMany(patches:Map<string,Partial<Widget>>,track=true){if(track)checkpoint();setWidgets(v=>v.map(w=>patches.has(w.id)?{...w,...patches.get(w.id)!}:w));const results=await Promise.all([...patches].map(([id,patch])=>fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})})));if(results.some(r=>!r.ok))await load();}
 async function patchCanvas(patch:Partial<Canvas>){if(!canvas)return;const previous=canvas;setCanvas({...canvas,...patch});const r=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?character_id=eq.${characterId}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!r.ok){setCanvas(previous);setStatus("Canvas setting could not be saved.");}}
 async function createWidget(type:WidgetType){if(!canvas||saving)return;const d=defaults[type];setSaving(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({character_id:characterId,widget_type:type,x:Math.min(canvas.canvas_width-d.w,50+widgets.length*18%240),y:Math.min(canvas.canvas_height-d.h,60+widgets.length*24%320),width:d.w,height:d.h,z_index:Math.max(0,...widgets.map(w=>w.z_index))+1,rotation:0,opacity:1,content:d.content,style:d.style,locked:false})});if(!r.ok)throw new Error("Widget could not be added.");const row=(await r.json() as Widget[])[0];if(row){setWidgets(v=>[...v,row]);setSelectedIds([row.id]);}setStatus(`${type.replaceAll("_"," ")} widget added.`);}catch(e){setStatus(e instanceof Error?e.message:"Widget could not be added.");}finally{setSaving(false);}}
 async function duplicateSelected(){if(!selected||saving)return;const d={...selected,id:undefined,character_id:undefined};setSaving(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({character_id:characterId,widget_type:selected.widget_type,x:selected.x+20,y:selected.y+20,width:selected.width,height:selected.height,z_index:Math.max(...widgets.map(w=>w.z_index),0)+1,rotation:selected.rotation,opacity:selected.opacity,content:{...selected.content},style:{...selected.style},locked:false})});if(!r.ok)throw new Error("Widget could not be duplicated.");const row=(await r.json() as Widget[])[0];if(row){setWidgets(v=>[...v,row]);setSelectedIds([row.id]);}setStatus("Widget duplicated with its styling.");}catch(e){setStatus(e instanceof Error?e.message:"Widget could not be duplicated.");}finally{setSaving(false);}}
 async function removeSelected(){if(!selectedIds.length||saving||!confirm(`Delete ${selectedIds.length} selected widget${selectedIds.length===1?"":"s"}?`))return;setSaving(true);try{for(const widget of widgets.filter(w=>selectedIds.includes(w.id))){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/delete_owned_profile_widget`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_widget_id:widget.id})});if(!r.ok||!Boolean(await r.json()))throw new Error("A widget could not be deleted.");if(widget.content.storage_path)await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${widget.content.storage_path}`,{method:"DELETE",headers:headers(accessToken)}).catch(()=>undefined);}setWidgets(v=>v.filter(w=>!selectedIds.includes(w.id)));setSelectedIds([]);setPast([]);setFuture([]);setStatus("Selected widgets permanently removed.");}catch(e){setStatus(e instanceof Error?e.message:"Widgets could not be deleted.");await load();}finally{setSaving(false);}}
 async function undo(){const previous=past[past.length-1];if(!previous)return;const current=clone(widgets);setPast(v=>v.slice(0,-1));setFuture(v=>[current,...v].slice(0,25));setWidgets(previous);await Promise.all(previous.map(persistWidget));setStatus("Undid last change.");}
 async function redo(){const next=future[0];if(!next)return;const current=clone(widgets);setFuture(v=>v.slice(1));setPast(v=>[...v,current].slice(-25));setWidgets(next);await Promise.all(next.map(persistWidget));setStatus("Redid change.");}
 function selectWidget(event:PointerEvent<HTMLDivElement>,widget:Widget){if(event.shiftKey){setSelectedIds(v=>v.includes(widget.id)?v.filter(id=>id!==widget.id):[...v,widget.id]);return;}if(!selectedIds.includes(widget.id))setSelectedIds([widget.id]);}
 function startDrag(event:PointerEvent<HTMLDivElement>,widget:Widget){selectWidget(event,widget);if(widget.locked){setStatus("This widget is locked. Unlock it in the inspector first.");return;}event.currentTarget.setPointerCapture(event.pointerId);checkpoint();const ids=selectedIds.includes(widget.id)?selectedIds:[widget.id];drag.current={startX:event.clientX,startY:event.clientY,scale:zoom,bases:widgets.filter(w=>ids.includes(w.id)&&!w.locked).map(w=>({id:w.id,x:w.x,y:w.y}))};}
 function moveDrag(event:PointerEvent<HTMLDivElement>){if(!drag.current||!canvas)return;const dx=(event.clientX-drag.current.startX)/drag.current.scale;const dy=(event.clientY-drag.current.startY)/drag.current.scale;setWidgets(v=>v.map(w=>{const base=drag.current?.bases.find(b=>b.id===w.id);if(!base)return w;let x=Math.max(0,Math.min(canvas.canvas_width-w.width,Math.round(base.x+dx)));let y=Math.max(0,Math.min(canvas.canvas_height-w.height,Math.round(base.y+dy)));if(canvas.snap_enabled){x=Math.round(x/10)*10;y=Math.round(y/10)*10;}return {...w,x,y};}));}
 async function endDrag(){const state=drag.current;if(!state)return;drag.current=null;const patches=new Map<string,Partial<Widget>>();state.bases.forEach(base=>{const w=widgets.find(x=>x.id===base.id);if(w)patches.set(w.id,{x:w.x,y:w.y});});await patchMany(patches,false);}
 function startResize(event:PointerEvent<HTMLButtonElement>,widget:Widget){event.stopPropagation();if(widget.locked)return;event.currentTarget.setPointerCapture(event.pointerId);checkpoint();resize.current={id:widget.id,startX:event.clientX,startY:event.clientY,scale:zoom,width:widget.width,height:widget.height};}
 function moveResize(event:PointerEvent<HTMLButtonElement>){event.stopPropagation();if(!resize.current||!canvas)return;const state=resize.current;const active=widgets.find(w=>w.id===state.id);if(!active)return;const width=Math.max(40,Math.min(canvas.canvas_width-active.x,Math.round(state.width+(event.clientX-state.startX)/state.scale)));const height=Math.max(active.widget_type==="divider"?4:24,Math.min(canvas.canvas_height-active.y,Math.round(state.height+(event.clientY-state.startY)/state.scale)));setWidgets(v=>v.map(w=>w.id===state.id?{...w,width,height}:w));}
 async function endResize(event:PointerEvent<HTMLButtonElement>){event.stopPropagation();const state=resize.current;if(!state)return;resize.current=null;const w=widgets.find(x=>x.id===state.id);if(w)await patchWidget(w.id,{width:w.width,height:w.height},false);}
 async function uploadSelectedImage(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file||!selected||!["image","photo_strip"].includes(selected.widget_type))return;if(!["image/jpeg","image/png","image/gif","image/webp"].includes(file.type)||file.size>5*1024*1024){setStatus("Use JPEG, PNG, GIF, or WebP files up to 5 MB.");return;}const ext=file.type==="image/jpeg"?"jpg":file.type.split("/")[1];const path=`${characterId}/${crypto.randomUUID()}.${ext}`;setSaving(true);try{const up=await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":file.type,"x-upsert":"false"}),body:file});if(!up.ok)throw new Error("Image upload failed.");const old=selected.content.storage_path;await patchWidget(selected.id,{content:{...selected.content,storage_path:path,url:"",alt:selected.content.alt||file.name}});setMediaUrls(v=>({...v,[path]:URL.createObjectURL(file)}));if(old&&old!==path)await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${old}`,{method:"DELETE",headers:headers(accessToken)}).catch(()=>undefined);setStatus("Image uploaded privately.");}catch(e){setStatus(e instanceof Error?e.message:"Image upload failed.");}finally{setSaving(false);}}
 function updateStyle(key:string,value:string|number){if(selected)patchWidget(selected.id,{style:{...selected.style,[key]:value}});}
 function updateContent(key:string,value:string){if(selected)patchWidget(selected.id,{content:{...selected.content,[key]:value}});}
 async function align(mode:"left"|"center"|"right"|"top"|"middle"|"bottom"){if(selectedWidgets.length<2)return;const left=Math.min(...selectedWidgets.map(w=>w.x)),right=Math.max(...selectedWidgets.map(w=>w.x+w.width)),top=Math.min(...selectedWidgets.map(w=>w.y)),bottom=Math.max(...selectedWidgets.map(w=>w.y+w.height));const patches=new Map<string,Partial<Widget>>();selectedWidgets.forEach(w=>{if(mode==="left")patches.set(w.id,{x:left});if(mode==="center")patches.set(w.id,{x:Math.round((left+right-w.width)/2)});if(mode==="right")patches.set(w.id,{x:right-w.width});if(mode==="top")patches.set(w.id,{y:top});if(mode==="middle")patches.set(w.id,{y:Math.round((top+bottom-w.height)/2)});if(mode==="bottom")patches.set(w.id,{y:bottom-w.height});});await patchMany(patches);}
 function copyStyle(){if(!selected)return;setCopiedStyle({...selected.style});setStatus("Widget style copied.");}
 async function pasteStyle(){if(!selected||!copiedStyle)return;await patchWidget(selected.id,{style:{...selected.style,...copiedStyle}});setStatus("Copied style applied.");}
 async function nudge(dx:number,dy:number){if(!selectedIds.length||!canvas)return;const patches=new Map<string,Partial<Widget>>();selectedWidgets.filter(w=>!w.locked).forEach(w=>patches.set(w.id,{x:Math.max(0,Math.min(canvas.canvas_width-w.width,w.x+dx)),y:Math.max(0,Math.min(canvas.canvas_height-w.height,w.y+dy))}));await patchMany(patches);}
 function handleKeyDown(event:ReactKeyboardEvent<HTMLElement>){if((event.target as HTMLElement).matches("input,textarea,select"))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="d"){event.preventDefault();duplicateSelected();return;}if(event.key==="Delete"||event.key==="Backspace"){if(selectedIds.length){event.preventDefault();removeSelected();}return;}const step=event.shiftKey?10:1;if(event.key==="ArrowLeft"){event.preventDefault();nudge(-step,0);}if(event.key==="ArrowRight"){event.preventDefault();nudge(step,0);}if(event.key==="ArrowUp"){event.preventDefault();nudge(0,-step);}if(event.key==="ArrowDown"){event.preventDefault();nudge(0,step);}}
 function renderWidget(widget:Widget){const s=widget.style;const common={width:"100%",height:"100%",background:String(s.background??"transparent"),color:String(s.color??"#17375f"),borderRadius:Number(s.borderRadius??0),borderWidth:Number(s.borderWidth??0),borderColor:String(s.borderColor??"#17375f"),borderStyle:String(s.borderStyle??"solid"),boxShadow:String(s.boxShadow??"none"),fontSize:Number(s.fontSize??18),fontFamily:String(s.fontFamily??"Arial, sans-serif"),textAlign:(s.textAlign??"left") as "left"|"center"|"right",display:"flex",alignItems:"center",justifyContent:s.textAlign==="center"?"center":s.textAlign==="right"?"flex-end":"flex-start",padding:widget.widget_type==="divider"?0:12,overflow:"hidden",whiteSpace:"pre-wrap" as const,boxSizing:"border-box" as const};const path=widget.content.storage_path;const src=path?mediaUrls[path]:widget.content.url;if(widget.widget_type==="image"||widget.widget_type==="photo_strip")return src?<img draggable={false} src={src} alt={widget.content.alt||"Profile image"} style={{width:"100%",height:"100%",objectFit:String(s.objectFit??"cover") as "cover"|"contain"|"fill",objectPosition:String(s.objectPosition??"50% 50%"),borderRadius:Number(s.borderRadius??0),borderWidth:Number(s.borderWidth??0),borderColor:String(s.borderColor??"#17375f"),borderStyle:String(s.borderStyle??"solid"),boxShadow:String(s.boxShadow??"none"),transform:`scale(${Number(s.flipX??1)},${Number(s.flipY??1)})`,pointerEvents:"none",boxSizing:"border-box"}}/>:<div style={common}>UPLOAD AN IMAGE</div>;if(widget.widget_type==="divider")return <div style={common}/>;if(widget.widget_type==="marquee")return <div style={common}><span className={styles.marqueeText}>{widget.content.text||"★ welcome ★"}</span></div>;if(widget.widget_type==="quote")return <div style={{...common,display:"block",padding:18}}>{widget.content.text}<small style={{display:"block",marginTop:10}}>{widget.content.credit}</small></div>;return <div style={common}>{widget.content.text||widget.widget_type.replaceAll("_"," ").toUpperCase()}</div>;}
 if(!canvas)return <section className={styles.loading}><p className="eyebrow">PROFILE STUDIO V2</p><h4>Opening your design canvas…</h4><p>{status}</p></section>;
 const layers=[...widgets].sort((a,b)=>b.z_index-a.z_index);
 return <section ref={studioRef} tabIndex={0} onKeyDown={handleKeyDown} className={styles.studio} aria-labelledby="profile-studio-v2-title">
  <div className={styles.heading}><div><p className="eyebrow">PROFILE STUDIO V2</p><h4 id="profile-studio-v2-title">Design your character page</h4></div><span>ENHANCED CANVA-STYLE EDITOR</span></div>
  <div className={styles.status} aria-live="polite">{status}</div>
  <div className={styles.paletteLabel}><strong>ADD CONTENT</strong><span>Upload-first media • freeform widgets</span></div>
  <div className={styles.toolbar}>{basicTypes.map(type=><button key={type} type="button" onClick={()=>createWidget(type)} disabled={saving}>+ {type}</button>)}{socialTypes.map(type=><button key={type} type="button" onClick={()=>createWidget(type)} disabled={saving}>+ {type.replaceAll("_"," ")}</button>)}</div>
  <div className={styles.toolbar}><button onClick={undo} disabled={!past.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={()=>setZoom(z=>Math.max(.35,Math.round((z-.1)*100)/100))}>− Zoom</button><strong style={{alignSelf:"center",fontSize:9}}>{Math.round(zoom*100)}%</strong><button onClick={()=>setZoom(z=>Math.min(1.5,Math.round((z+.1)*100)/100))}>+ Zoom</button><button onClick={()=>setZoom(.8)}>Fit</button><button onClick={()=>setShowLayers(v=>!v)}>{showLayers?"Hide":"Show"} layers</button>{selected&&<><button onClick={duplicateSelected}>Duplicate</button><button onClick={copyStyle}>Copy style</button><button onClick={pasteStyle} disabled={!copiedStyle}>Paste style</button><button onClick={()=>patchWidget(selected.id,{z_index:Math.max(0,...widgets.map(w=>w.z_index))+1})}>To front</button><button onClick={()=>patchWidget(selected.id,{z_index:0})}>To back</button></>}{selectedWidgets.length>1&&<><button onClick={()=>align("left")}>Align left</button><button onClick={()=>align("center")}>Center</button><button onClick={()=>align("right")}>Align right</button><button onClick={()=>align("top")}>Align top</button><button onClick={()=>align("middle")}>Middle</button><button onClick={()=>align("bottom")}>Align bottom</button></>}</div>
  <div className={styles.selectionHint}>Click to select • Shift-click for multi-select • Arrow keys nudge 1px • Shift + arrows nudge 10px • Ctrl/Cmd+D duplicates • Delete removes • Ctrl/Cmd+Z undo</div>
  <div style={{display:"grid",gridTemplateColumns:showLayers?"190px minmax(0,1fr) 285px":"minmax(0,1fr) 285px",minHeight:650}}>
   {showLayers&&<aside style={{padding:10,borderRight:"1px solid #c1ccd7",background:"#f7f9fb",overflow:"auto"}}><h5 style={{margin:"0 0 8px"}}>Layers</h5>{layers.map((w,index)=><button key={w.id} type="button" onClick={()=>setSelectedIds([w.id])} style={{display:"grid",gridTemplateColumns:"24px 1fr",width:"100%",padding:7,marginBottom:4,textAlign:"left",background:selectedIds.includes(w.id)?"#efe7f5":"#fff",border:"1px solid #c8d1da"}}><span>{layers.length-index}</span><span><strong>{w.widget_type.replaceAll("_"," ")}</strong><small style={{display:"block"}}>{w.locked?"🔒 Locked":"Editable"}</small></span></button>)}</aside>}
   <div className={styles.canvasArea} style={{overflow:"auto"}}><div className={`${styles.canvas} ${canvas.grid_enabled?styles.grid:""}`} onPointerDown={e=>{if(e.target===e.currentTarget)setSelectedIds([])}} style={{width:canvas.canvas_width*zoom,height:canvas.canvas_height*zoom,background:canvas.background}}>{widgets.map(w=>{const active=selectedIds.includes(w.id);return <div key={w.id} className={`${styles.widget} ${active?styles.selected:""}`} onPointerDown={e=>startDrag(e,w)} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} style={{left:w.x*zoom,top:w.y*zoom,width:w.width*zoom,height:w.height*zoom,zIndex:w.z_index,opacity:w.opacity,transform:`rotate(${w.rotation}deg)`}}>{renderWidget(w)}{w.locked&&<span className={styles.lock}>LOCKED</span>}{active&&!w.locked&&<button type="button" className={styles.resizeHandle} aria-label="Resize widget" onPointerDown={e=>startResize(e,w)} onPointerMove={moveResize} onPointerUp={endResize} onPointerCancel={endResize}/>}</div>})}</div></div>
   <aside className={styles.inspector}><h5>Canvas</h5><label><span>Page size</span><select value={`${canvas.canvas_width}x${canvas.canvas_height}`} onChange={e=>{const [canvas_width,canvas_height]=e.target.value.split("x").map(Number);patchCanvas({canvas_width,canvas_height});}}><option value="960x1200">Standard</option><option value="960x1600">Tall</option><option value="1200x1200">Square</option><option value="1200x1800">Showcase</option></select></label><label><span>Canvas color</span><input type="color" value={canvas.background.startsWith("#")?canvas.background:"#fffafc"} onChange={e=>patchCanvas({background:e.target.value})}/></label><div className={styles.toggles}><label><input type="checkbox" checked={canvas.grid_enabled} onChange={e=>patchCanvas({grid_enabled:e.target.checked})}/> Grid</label><label><input type="checkbox" checked={canvas.snap_enabled} onChange={e=>patchCanvas({snap_enabled:e.target.checked})}/> Snap</label></div>
    {selectedWidgets.length>1&&<div className={styles.multiNotice}><strong>{selectedWidgets.length} WIDGETS SELECTED</strong><span>Drag together, align from the toolbar, or nudge with arrow keys.</span></div>}
    {selected&&<><h5>Selected {selected.widget_type.replaceAll("_"," ")}</h5>{!["divider","image","photo_strip"].includes(selected.widget_type)&&<label><span>Text</span><textarea value={selected.content.text??""} onChange={e=>updateContent("text",e.target.value)}/></label>}{["image","photo_strip"].includes(selected.widget_type)&&<><label className={styles.uploadField}><span>Upload image</span><input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={uploadSelectedImage} disabled={saving}/><small>Private Hanami media • max 5 MB</small></label><label><span>Alt text</span><input value={selected.content.alt??""} onChange={e=>updateContent("alt",e.target.value)}/></label><label><span>Image fit</span><select value={String(selected.style.objectFit??"cover")} onChange={e=>updateStyle("objectFit",e.target.value)}><option value="cover">Crop to fill</option><option value="contain">Fit entire image</option><option value="fill">Stretch</option></select></label><label><span>Focal point</span><select value={String(selected.style.objectPosition??"50% 50%")} onChange={e=>updateStyle("objectPosition",e.target.value)}><option value="50% 50%">Center</option><option value="50% 0%">Top</option><option value="50% 100%">Bottom</option><option value="0% 50%">Left</option><option value="100% 50%">Right</option></select></label><div style={{display:"flex",gap:5,marginBottom:8}}><button type="button" onClick={()=>updateStyle("flipX",Number(selected.style.flipX??1)*-1)}>Flip horizontal</button><button type="button" onClick={()=>updateStyle("flipY",Number(selected.style.flipY??1)*-1)}>Flip vertical</button></div>{selected.content.storage_path&&<div className={styles.mediaNotice}><strong>PRIVATE HANAMI UPLOAD</strong><span>{selected.content.storage_path.split("/").pop()}</span></div>}</>}{selected.widget_type==="quote"&&<label><span>Quote credit</span><input value={selected.content.credit??""} onChange={e=>updateContent("credit",e.target.value)}/></label>}{selected.widget_type==="link"&&<label><span>Link URL</span><input value={selected.content.url??""} onChange={e=>updateContent("url",e.target.value)}/></label>}
     <div className={styles.numbers}><label><span>X</span><input type="number" value={selected.x} onChange={e=>patchWidget(selected.id,{x:Number(e.target.value)})}/></label><label><span>Y</span><input type="number" value={selected.y} onChange={e=>patchWidget(selected.id,{y:Number(e.target.value)})}/></label><label><span>Width</span><input type="number" min="40" value={selected.width} onChange={e=>patchWidget(selected.id,{width:Number(e.target.value)})}/></label><label><span>Height</span><input type="number" min={selected.widget_type==="divider"?4:24} value={selected.height} onChange={e=>patchWidget(selected.id,{height:Number(e.target.value)})}/></label></div>
     <label><span>Rotation</span><input type="range" min="-180" max="180" value={selected.rotation} onChange={e=>patchWidget(selected.id,{rotation:Number(e.target.value)})}/></label><label><span>Opacity</span><input type="range" min=".1" max="1" step=".05" value={selected.opacity} onChange={e=>patchWidget(selected.id,{opacity:Number(e.target.value)})}/></label>
     {!(["image","photo_strip","divider"].includes(selected.widget_type))&&<><label><span>Background</span><input type="color" value={String(selected.style.background??"#ffffff").startsWith("#")?String(selected.style.background):"#ffffff"} onChange={e=>updateStyle("background",e.target.value)}/></label><label><span>Text color</span><input type="color" value={String(selected.style.color??"#17375f")} onChange={e=>updateStyle("color",e.target.value)}/></label><label><span>Font</span><select value={String(selected.style.fontFamily??"Arial, sans-serif")} onChange={e=>updateStyle("fontFamily",e.target.value)}><option value="Arial, sans-serif">Sans serif</option><option value="Georgia, serif">Serif</option><option value="Courier New, monospace">Monospace</option><option value="Trebuchet MS, sans-serif">Trebuchet</option><option value="Times New Roman, serif">Times</option></select></label><label><span>Font size</span><input type="number" min="8" max="120" value={Number(selected.style.fontSize??18)} onChange={e=>updateStyle("fontSize",Number(e.target.value))}/></label></>}
     <label><span>Corner presets</span><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4}}><button type="button" onClick={()=>updateStyle("borderRadius",0)}>Sharp</button><button type="button" onClick={()=>updateStyle("borderRadius",10)}>Soft</button><button type="button" onClick={()=>updateStyle("borderRadius",24)}>Rounded</button><button type="button" onClick={()=>updateStyle("borderRadius",99)}>Pill</button></div></label><label><span>Custom corner radius</span><input type="number" min="0" max="100" value={Number(selected.style.borderRadius??0)} onChange={e=>updateStyle("borderRadius",Number(e.target.value))}/></label>
     <div className={styles.numbers}><label><span>Border width</span><input type="number" min="0" max="12" value={Number(selected.style.borderWidth??0)} onChange={e=>updateStyle("borderWidth",Number(e.target.value))}/></label><label><span>Border color</span><input type="color" value={String(selected.style.borderColor??"#17375f")} onChange={e=>updateStyle("borderColor",e.target.value)}/></label></div><label><span>Border style</span><select value={String(selected.style.borderStyle??"solid")} onChange={e=>updateStyle("borderStyle",e.target.value)}><option value="solid">Solid</option><option value="dashed">Dashed</option><option value="dotted">Dotted</option><option value="double">Double</option></select></label><label><span>Shadow</span><select value={String(selected.style.boxShadow??"none")} onChange={e=>updateStyle("boxShadow",e.target.value)}><option value="none">None</option><option value="0 3px 8px rgba(23,55,95,.16)">Soft</option><option value="0 8px 22px rgba(23,55,95,.22)">Floating</option><option value="4px 4px 0 rgba(23,55,95,.28)">Retro hard</option><option value="0 0 16px rgba(180,73,114,.35)">Glow</option></select></label><label className={styles.lockToggle}><input type="checkbox" checked={selected.locked} onChange={e=>patchWidget(selected.id,{locked:e.target.checked})}/> Lock position</label><button type="button" className={styles.delete} onClick={removeSelected}>Delete selected</button></>}
   </aside>
  </div>
  <div className={styles.note}><strong>PROFILE STUDIO V2</strong><span>Enhanced editing includes zoom, layers, keyboard nudging, explicit corner presets, borders, shadows, image fitting/focal controls, style copy/paste, private uploads, multi-select alignment, and undo/redo.</span></div>
 </section>;
}
