"use client";

import {FormEvent,useState} from "react";
import styles from "./ProfileLookupPanel.module.css";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type VisibleProfile={character_id:string;display_name:string;handle:string;role:"student"|"faculty";visibility:"public"|"friends_only"|"private";headline:string;bio:string;status_message:string};
type Canvas={canvas_width:number;canvas_height:number;background:string;background_image_url:string|null};
type Widget={id:string;widget_type:"text"|"image"|"card"|"link"|"divider"|"sticker";x:number;y:number;width:number;height:number;z_index:number;rotation:number;opacity:number;content:Record<string,string>;style:Record<string,string|number>};
type Design={canvas:Canvas;widgets:Widget[]};type Props={accessToken:string;viewerCharacterId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function widgetView(widget:Widget){const s=widget.style;const base={width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:s.textAlign==="center"?"center":s.textAlign==="right"?"flex-end":"flex-start",padding:widget.widget_type==="divider"?0:10,boxSizing:"border-box" as const,overflow:"hidden",background:String(s.background??"transparent"),color:String(s.color??"#17375f"),fontFamily:String(s.fontFamily??"Arial, sans-serif"),fontSize:Number(s.fontSize??16),textAlign:(s.textAlign??"left") as "left"|"center"|"right",borderRadius:Number(s.borderRadius??0)};if(widget.widget_type==="image")return widget.content.url?<img src={widget.content.url} alt={widget.content.alt||"Profile image"} style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:Number(s.borderRadius??0)}}/>:<div style={base}>IMAGE</div>;if(widget.widget_type==="divider")return <div style={base}/>;return <div style={base}>{widget.content.text||widget.widget_type.toUpperCase()}</div>}
export default function ProfileLookupPanel({accessToken,viewerCharacterId}:Props){
 const [handle,setHandle]=useState("");const [profile,setProfile]=useState<VisibleProfile|null>(null);const [design,setDesign]=useState<Design|null>(null);const [message,setMessage]=useState("Search an exact Hanami handle to view an available character profile.");const [loading,setLoading]=useState(false);
 async function search(event:FormEvent<HTMLFormElement>){event.preventDefault();const clean=handle.trim().replace(/^@/,"").toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(clean)){setProfile(null);setDesign(null);setMessage("Enter a valid Hanami handle using lowercase letters, numbers, or underscores.");return;}setLoading(true);setProfile(null);setDesign(null);setMessage(`Checking profile visibility for @${clean}…`);try{const payload=JSON.stringify({viewer_character_id:viewerCharacterId,target_handle:clean});const [profileResponse,designResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/lookup_visible_character_profile`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:payload}),fetch(`${SUPABASE_URL}/rest/v1/rpc/lookup_visible_profile_design`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:payload})]);if(!profileResponse.ok||!designResponse.ok)throw new Error("The Hanami profile lookup could not be completed.");const profileRows=await profileResponse.json() as VisibleProfile[];const designRows=await designResponse.json() as {canvas:Canvas;widgets:Widget[]}[];const result=profileRows[0]??null;setProfile(result);setDesign(designRows[0]??null);setMessage(result?`@${clean} is visible to your active character.`:`@${clean} is private, friends-only without an accepted friendship, unavailable, or does not exist.`);}catch(error){setMessage(error instanceof Error?error.message:"The Hanami profile lookup could not be completed.");}finally{setLoading(false);}}
 const previewWidth=760;const scale=design?Math.min(1,previewWidth/design.canvas.canvas_width):1;
 return <section className={styles.panel} aria-labelledby="profile-search-title"><div className={styles.heading}><div><p className="eyebrow">HANAMI PROFILES</p><h4 id="profile-search-title">Character lookup</h4></div><span>PRIVACY-AWARE</span></div><form className={styles.search} onSubmit={search}><label><span>Exact Hanami handle</span><div><b>@</b><input value={handle} onChange={event=>setHandle(event.target.value)} maxLength={24} placeholder="character_handle" autoComplete="off"/><button type="submit" disabled={loading}>{loading?"Checking…":"View profile"}</button></div></label></form><div className={styles.status} aria-live="polite">{message}</div>{profile&&<><article className={styles.card}><div className={styles.avatar}>花</div><div className={styles.identity}><p className="eyebrow">{profile.role.toUpperCase()} • {profile.visibility.replace("_"," ").toUpperCase()}</p><h5>{profile.display_name}</h5><span>@{profile.handle}</span>{profile.status_message&&<blockquote>{profile.status_message}</blockquote>}</div><div className={styles.copy}><strong>{profile.headline||"Hanami character profile"}</strong><p>{profile.bio||"This character has not added a biography yet."}</p></div></article>{design&&<div className={styles.designWrap}><div className={styles.designLabel}><strong>CUSTOM PROFILE DESIGN</strong><span>{design.widgets.length} WIDGET{design.widgets.length===1?"":"S"}</span></div><div className={styles.previewScroller}><div className={styles.preview} style={{width:design.canvas.canvas_width*scale,height:Math.min(design.canvas.canvas_height*scale,760),background:design.canvas.background,backgroundImage:design.canvas.background_image_url?`url(${design.canvas.background_image_url})`:undefined,backgroundSize:"cover"}}>{design.widgets.map(widget=><div key={widget.id} className={styles.previewWidget} style={{left:widget.x*scale,top:widget.y*scale,width:widget.width*scale,height:widget.height*scale,zIndex:widget.z_index,opacity:widget.opacity,transform:`rotate(${widget.rotation}deg)`}}>{widgetView(widget)}</div>)}</div></div></div>}</>}<div className={styles.privacy}><strong>VISIBILITY RULE</strong><span>Public profiles can be viewed by signed-in Hanami members. Friends-only profiles are visible to accepted character friends. Private profiles remain owner-only.</span></div></section>;
}
