"use client";

import {ChangeEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const IMAGE_TYPES=["image/jpeg","image/png","image/webp"];
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Props={accessToken:string;characterId:string;onChanged:()=>void};
type Pack={name:string;label:string;background:string;accent:string;secondary:string;emoji:string;heading:string;tagline:string};
type LayoutWidget={id:string;widget_type:string;x:number;y:number;width:number;height:number;locked:boolean;updated_at?:string};
type CanvasRow={canvas_width:number;canvas_height:number;updated_at?:string};
type SaveState="Saved just now"|"Saving…"|"Failed to save"|"Autosave active";
const packs:Pack[]=[
 {name:"sakura",label:"Sakura",background:"#fff4f8",accent:"#d75f91",secondary:"#f2bfd2",emoji:"🌸",heading:"SAKURA SEASON",tagline:"petals, spring notes & hanami memories"},
 {name:"matsuri",label:"Summer Matsuri",background:"#fff8e8",accent:"#d85b38",secondary:"#f4c66f",emoji:"🏮",heading:"SUMMER MATSURI",tagline:"festival nights, lanterns & fireworks"},
 {name:"halloween",label:"Halloween",background:"#fff4e8",accent:"#7b4c87",secondary:"#e5a85d",emoji:"🎃",heading:"HALLOWEEN AT HANAMI",tagline:"costumes, club parties & autumn rumors"},
 {name:"winter",label:"Winter",background:"#f3f8ff",accent:"#4c7fa6",secondary:"#b9d7ec",emoji:"❄️",heading:"WINTER TERM",tagline:"snow days, scarves & after-school lights"},
 {name:"graduation",label:"Graduation",background:"#fffaf0",accent:"#8f365b",secondary:"#d8bd75",emoji:"🎓",heading:"GRADUATION",tagline:"memories, signatures & final school days"},
 {name:"culture-festival",label:"Culture Festival",background:"#fff8fb",accent:"#9b315b",secondary:"#e2b4c6",emoji:"🎪",heading:"CULTURE FESTIVAL",tagline:"class booths, performances & festival plans"},
 {name:"sports-day",label:"Sports Day",background:"#f8fbff",accent:"#315e91",secondary:"#d05050",emoji:"🏅",heading:"SPORTS DAY",tagline:"teams, points & class pride"},
];

async function imageToStickerPng(file:File,removeBackground:boolean,tolerance:number){
 const bitmap=await createImageBitmap(file);const max=900;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const width=Math.max(1,Math.round(bitmap.width*scale));const height=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)throw new Error("Sticker canvas is unavailable in this browser.");ctx.drawImage(bitmap,0,0,width,height);bitmap.close();
 if(removeBackground){const data=ctx.getImageData(0,0,width,height);const p=data.data;const sample=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]].map(([x,y])=>{const i=(y*width+x)*4;return [p[i],p[i+1],p[i+2]]});const target=sample.reduce((a,c)=>[a[0]+c[0],a[1]+c[1],a[2]+c[2]],[0,0,0]).map(v=>v/sample.length);for(let i=0;i<p.length;i+=4){const d=Math.sqrt((p[i]-target[0])**2+(p[i+1]-target[1])**2+(p[i+2]-target[2])**2);if(d<=tolerance)p[i+3]=0;}ctx.putImageData(data,0,0);}
 return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Sticker PNG could not be generated.")),"image/png"));
}

export default function ProfileStudioRoadmapTools({accessToken,characterId,onChanged}:Props){
 const [file,setFile]=useState<File|null>(null);const [removeBackground,setRemoveBackground]=useState(true);const [tolerance,setTolerance]=useState(42);const [busy,setBusy]=useState("");const [status,setStatus]=useState("Create transparent stickers, seasonal packs, and precise layouts without leaving Profile Studio.");
 const [layoutWidgets,setLayoutWidgets]=useState<LayoutWidget[]>([]);const [canvasRow,setCanvasRow]=useState<CanvasRow>({canvas_width:960,canvas_height:1200});const [layoutSelection,setLayoutSelection]=useState<string[]>([]);const [guides,setGuides]=useState(false);const [saveState,setSaveState]=useState<SaveState>("Autosave active");const [lastSaved,setLastSaved]=useState<number|null>(null);
 const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]);
 const selectedLayout=useMemo(()=>layoutWidgets.filter(w=>layoutSelection.includes(w.id)&&!w.locked),[layoutWidgets,layoutSelection]);

 const loadLayout=useCallback(async()=>{const [w,c]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?select=id,widget_type,x,y,width,height,locked,updated_at&character_id=eq.${encodeURIComponent(characterId)}&order=z_index.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?select=canvas_width,canvas_height,updated_at&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)})
 ]);if(w.ok){const rows=await w.json() as LayoutWidget[];setLayoutWidgets(rows);setLayoutSelection(ids=>ids.filter(id=>rows.some(row=>row.id===id)));}if(c.ok){const rows=await c.json() as CanvasRow[];if(rows[0])setCanvasRow(rows[0]);}},[accessToken,characterId]);
 useEffect(()=>{void loadLayout();},[loadLayout]);
 useEffect(()=>{const timer=window.setInterval(()=>void loadLayout(),5000);return()=>window.clearInterval(timer);},[loadLayout]);

 useEffect(()=>{const original=window.fetch.bind(window);window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url;const method=(init?.method??(typeof input!=="string"&&!(input instanceof URL)?input.method:"GET")).toUpperCase();const profileSave=(url.includes("/rest/v1/character_profile_widgets")||url.includes("/rest/v1/character_profile_canvases")||url.includes("/rest/v1/rpc/delete_owned_profile_widget"))&&["POST","PATCH","DELETE"].includes(method);if(profileSave)setSaveState("Saving…");try{const response=await original(input as RequestInfo|URL,init);if(profileSave){if(response.ok){setSaveState("Saved just now");setLastSaved(Date.now());window.setTimeout(()=>setSaveState(current=>current==="Saved just now"?"Autosave active":current),2500);}else setSaveState("Failed to save");}return response;}catch(error){if(profileSave)setSaveState("Failed to save");throw error;}};return()=>{window.fetch=original;};},[]);

 useEffect(()=>{if(!guides)return;function applyGuides(){const root=document.querySelector<HTMLElement>('section[aria-labelledby="profile-studio-v2-title"]');if(!root)return;const candidates=[...root.querySelectorAll<HTMLElement>('div[class*="canvas"]')];const target=candidates.find(el=>Boolean(el.style.width)&&Boolean(el.style.height)&&!el.className.toLowerCase().includes("area"));if(!target)return;target.querySelectorAll('[data-hanami-layout-guide="true"]').forEach(node=>node.remove());if(getComputedStyle(target).position==="static")target.style.position="relative";const make=(style:Partial<CSSStyleDeclaration>)=>{const el=document.createElement("div");el.dataset.hanamiLayoutGuide="true";Object.assign(el.style,{position:"absolute",zIndex:"9998",pointerEvents:"none",...style});target.appendChild(el);};make({left:"50%",top:"0",bottom:"0",width:"1px",background:"rgba(155,49,91,.75)"});make({top:"50%",left:"0",right:"0",height:"1px",background:"rgba(155,49,91,.75)"});make({left:"0",top:"0",right:"0",height:"16px",background:"repeating-linear-gradient(90deg,rgba(23,55,95,.55) 0 1px,transparent 1px 10px)",borderBottom:"1px solid rgba(23,55,95,.35)"});make({left:"0",top:"0",bottom:"0",width:"16px",background:"repeating-linear-gradient(180deg,rgba(23,55,95,.55) 0 1px,transparent 1px 10px)",borderRight:"1px solid rgba(23,55,95,.35)"});}
 applyGuides();const timer=window.setInterval(applyGuides,600);return()=>{window.clearInterval(timer);document.querySelectorAll('[data-hanami-layout-guide="true"]').forEach(node=>node.remove());};},[guides]);

 function chooseFile(event:ChangeEvent<HTMLInputElement>){const next=event.target.files?.[0]??null;if(next&&(!IMAGE_TYPES.includes(next.type)||next.size>5*1024*1024)){setFile(null);setStatus("Sticker images must be JPEG, PNG, or WebP and 5 MB or smaller.");return;}setFile(next);}
 async function createSticker(){if(!file||busy)return;setBusy("sticker");setStatus("Preparing transparent sticker…");try{const png=await imageToStickerPng(file,removeBackground,tolerance);const path=`${characterId}/sticker-${crypto.randomUUID()}.png`;const upload=await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"image/png","x-upsert":"false"}),body:png});if(!upload.ok)throw new Error("Sticker image could not be uploaded.");const create=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({character_id:characterId,widget_type:"sticker",x:80,y:80,width:180,height:180,z_index:99,rotation:0,opacity:1,content:{storage_path:path,alt:file.name,text:""},style:{background:"transparent",borderRadius:0,borderWidth:0,boxShadow:"none",objectFit:"contain",objectPosition:"50% 50%"},locked:false})});if(!create.ok)throw new Error("Sticker was uploaded but could not be added to the canvas.");setFile(null);setStatus("Sticker created and added to the canvas. Move, resize, rotate, or duplicate it like any other widget.");await loadLayout();onChanged();}catch(error){setStatus(error instanceof Error?error.message:"Sticker could not be created.");}finally{setBusy("");}}
 async function addPack(pack:Pack){if(busy)return;setBusy(pack.name);setStatus(`Adding ${pack.label} pack…`);try{const canvas=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?character_id=eq.${encodeURIComponent(characterId)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({background:pack.background,updated_at:new Date().toISOString()})});if(!canvas.ok)throw new Error("Seasonal canvas color could not be applied.");const widgets=[
  {character_id:characterId,widget_type:"text",x:70,y:55,width:620,height:90,z_index:60,rotation:0,opacity:1,content:{text:`${pack.emoji} ${pack.heading}`},style:{fontSize:38,fontFamily:"Georgia, serif",color:pack.accent,background:"transparent",textAlign:"left",borderRadius:0},locked:false},
  {character_id:characterId,widget_type:"card",x:70,y:165,width:520,height:120,z_index:59,rotation:0,opacity:1,content:{text:pack.tagline},style:{fontSize:18,fontFamily:"Arial, sans-serif",color:"#17375f",background:"#ffffff",textAlign:"left",borderRadius:14,borderWidth:1,borderColor:pack.secondary,borderStyle:"solid"},locked:false},
  {character_id:characterId,widget_type:"divider",x:70,y:320,width:720,height:12,z_index:58,rotation:0,opacity:1,content:{},style:{background:pack.secondary,borderRadius:99},locked:false},
  {character_id:characterId,widget_type:"sticker",x:720,y:70,width:130,height:130,z_index:61,rotation:7,opacity:1,content:{text:pack.emoji},style:{fontSize:68,fontFamily:"Arial, sans-serif",color:pack.accent,background:"transparent",textAlign:"center",borderRadius:18},locked:false}
 ];const create=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(widgets)});if(!create.ok)throw new Error("Seasonal widgets could not be added. Your existing canvas was left intact.");setStatus(`${pack.label} pack added. Existing widgets were preserved.`);await loadLayout();onChanged();}catch(error){setStatus(error instanceof Error?error.message:"Seasonal pack could not be applied.");}finally{setBusy("");}}

 async function saveLayout(next:Map<string,{x?:number;y?:number}>){if(!next.size)return;setSaveState("Saving…");const results=await Promise.all([...next].map(([id,patch])=>fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})})));if(results.some(r=>!r.ok)){setSaveState("Failed to save");setStatus("One or more layout changes failed to save.");return;}setSaveState("Saved just now");setLastSaved(Date.now());setStatus("Layout changes saved to Profile Studio.");await loadLayout();onChanged();}
 async function alignLayout(mode:"left"|"center"|"right"|"top"|"middle"|"bottom"){if(selectedLayout.length<2)return;const left=Math.min(...selectedLayout.map(w=>w.x)),right=Math.max(...selectedLayout.map(w=>w.x+w.width)),top=Math.min(...selectedLayout.map(w=>w.y)),bottom=Math.max(...selectedLayout.map(w=>w.y+w.height));const next=new Map<string,{x?:number;y?:number}>();for(const w of selectedLayout){if(mode==="left")next.set(w.id,{x:left});if(mode==="center")next.set(w.id,{x:Math.round((left+right-w.width)/2)});if(mode==="right")next.set(w.id,{x:right-w.width});if(mode==="top")next.set(w.id,{y:top});if(mode==="middle")next.set(w.id,{y:Math.round((top+bottom-w.height)/2)});if(mode==="bottom")next.set(w.id,{y:bottom-w.height});}await saveLayout(next);}
 async function snapCenter(axis:"x"|"y"){if(!selectedLayout.length)return;const next=new Map<string,{x?:number;y?:number}>();for(const w of selectedLayout)next.set(w.id,axis==="x"?{x:Math.max(0,Math.round((canvasRow.canvas_width-w.width)/2))}:{y:Math.max(0,Math.round((canvasRow.canvas_height-w.height)/2))});await saveLayout(next);}
 async function distribute(axis:"x"|"y"){if(selectedLayout.length<3)return;const ordered=[...selectedLayout].sort((a,b)=>axis==="x"?a.x-b.x:a.y-b.y);const first=ordered[0],last=ordered[ordered.length-1];const firstEdge=axis==="x"?first.x:first.y;const lastEdge=axis==="x"?last.x+last.width:last.y+last.height;const totalSize=ordered.reduce((sum,w)=>sum+(axis==="x"?w.width:w.height),0);const gap=(lastEdge-firstEdge-totalSize)/(ordered.length-1);let cursor=firstEdge;const next=new Map<string,{x?:number;y?:number}>();for(const w of ordered){next.set(w.id,axis==="x"?{x:Math.round(cursor)}:{y:Math.round(cursor)});cursor+=(axis==="x"?w.width:w.height)+gap;}await saveLayout(next);}

 return <section style={{marginTop:12,border:"1px solid #c8b5bf",background:"#fffafc",padding:12,display:"grid",gap:12}} aria-label="Profile Studio roadmap tools"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><p className="eyebrow">PROFILE STUDIO ROADMAP TOOLS</p><h4 style={{margin:"3px 0",font:"400 20px Georgia,serif"}}>Sticker Creator, seasonal packs & precision layout</h4><small>{status}</small></div><div aria-live="polite" style={{border:"1px solid #c9d2dc",background:"#fff",padding:"7px 9px",fontSize:9}}><strong>{saveState}</strong>{lastSaved&&<small style={{display:"block"}}>Last save {new Date(lastSaved).toLocaleTimeString([], {hour:"numeric",minute:"2-digit",second:"2-digit"})}</small>}</div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",gap:12}}><div style={{border:"1px solid #e4d5dc",padding:10}}><strong>Sticker Creator</strong><p style={{fontSize:9}}>Upload an image. Hanami can remove a flat corner-matched background and save the result as a private transparent PNG sticker.</p><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile}/>{preview&&<img src={preview} alt="Sticker preview" style={{display:"block",maxWidth:150,maxHeight:120,objectFit:"contain",marginTop:8}}/>}<label style={{display:"block",marginTop:7,fontSize:9}}><input type="checkbox" checked={removeBackground} onChange={e=>setRemoveBackground(e.target.checked)}/> Remove background automatically</label>{removeBackground&&<label style={{display:"block",marginTop:5,fontSize:9}}>Background tolerance <input type="range" min="8" max="100" value={tolerance} onChange={e=>setTolerance(Number(e.target.value))}/> {tolerance}</label>}<button type="button" disabled={!file||Boolean(busy)} onClick={createSticker} style={{marginTop:7}}>{busy==="sticker"?"Creating…":"Create sticker"}</button></div>
 <div style={{border:"1px solid #e4d5dc",padding:10}}><strong>Seasonal Template Packs</strong><p style={{fontSize:9}}>Adds a themed heading, card, divider, sticker, and canvas color. Existing widgets stay in place.</p><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{packs.map(pack=><button key={pack.name} type="button" disabled={Boolean(busy)} onClick={()=>addPack(pack)}>{busy===pack.name?"Adding…":`${pack.emoji} ${pack.label}`}</button>)}</div></div>
 <div style={{border:"1px solid #e4d5dc",padding:10,gridColumn:"1/-1"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"}}><div><strong>Canvas Guides, Rulers & Alignment</strong><p style={{fontSize:9,margin:"4px 0"}}>Choose widgets below, then align, distribute, or snap them to the canvas center. Guides overlay directly on the live Profile Studio canvas.</p></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button type="button" onClick={()=>setGuides(v=>!v)}>{guides?"Hide rulers & guides":"Show rulers & guides"}</button><button type="button" onClick={()=>setLayoutSelection(layoutWidgets.filter(w=>!w.locked).map(w=>w.id))}>Select all editable</button><button type="button" onClick={()=>setLayoutSelection([])}>Clear selection</button><button type="button" onClick={()=>void loadLayout()}>Refresh widgets</button></div></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(220px,.8fr) minmax(280px,1.2fr)",gap:10,marginTop:9}}><div style={{maxHeight:260,overflow:"auto",border:"1px solid #d8dfe6",padding:7,background:"#fff"}}>{layoutWidgets.map((w,index)=><label key={w.id} style={{display:"grid",gridTemplateColumns:"auto 1fr auto",gap:6,alignItems:"center",padding:"5px 0",borderBottom:"1px solid #eef1f4",fontSize:9}}><input type="checkbox" disabled={w.locked} checked={layoutSelection.includes(w.id)} onChange={e=>setLayoutSelection(ids=>e.target.checked?[...new Set([...ids,w.id])]:ids.filter(id=>id!==w.id))}/><span><strong>{index+1}. {w.widget_type.replaceAll("_"," ")}</strong><small style={{display:"block"}}>x {w.x} • y {w.y} • {w.width}×{w.height}</small></span><small>{w.locked?"LOCKED":""}</small></label>)}</div>
 <div><div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:8}}>{(["left","center","right","top","middle","bottom"] as const).map(mode=><button key={mode} type="button" disabled={selectedLayout.length<2} onClick={()=>void alignLayout(mode)}>Align {mode}</button>)}<button type="button" disabled={!selectedLayout.length} onClick={()=>void snapCenter("x")}>Snap to horizontal center</button><button type="button" disabled={!selectedLayout.length} onClick={()=>void snapCenter("y")}>Snap to vertical center</button><button type="button" disabled={selectedLayout.length<3} onClick={()=>void distribute("x")}>Distribute evenly ↔</button><button type="button" disabled={selectedLayout.length<3} onClick={()=>void distribute("y")}>Distribute evenly ↕</button></div>
 <div style={{position:"relative",height:210,border:"1px solid #b9c5d1",background:"#fff",overflow:"hidden",padding:18}} aria-label="Profile canvas ruler preview"><div style={{position:"absolute",left:18,right:0,top:0,height:18,background:"repeating-linear-gradient(90deg,#73859a 0 1px,transparent 1px 10px)",opacity:.55}}/><div style={{position:"absolute",top:18,bottom:0,left:0,width:18,background:"repeating-linear-gradient(180deg,#73859a 0 1px,transparent 1px 10px)",opacity:.55}}/><div style={{position:"relative",width:"100%",height:"100%",background:"#fffafc"}}><div style={{position:"absolute",left:"50%",top:0,bottom:0,borderLeft:"1px dashed #9b315b"}}/><div style={{position:"absolute",top:"50%",left:0,right:0,borderTop:"1px dashed #9b315b"}}/>{layoutWidgets.map(w=><div key={w.id} title={`${w.widget_type} @ ${w.x},${w.y}`} style={{position:"absolute",left:`${Math.min(100,(w.x/canvasRow.canvas_width)*100)}%`,top:`${Math.min(100,(w.y/canvasRow.canvas_height)*100)}%`,width:`${Math.max(2,(w.width/canvasRow.canvas_width)*100)}%`,height:`${Math.max(2,(w.height/canvasRow.canvas_height)*100)}%`,border:layoutSelection.includes(w.id)?"2px solid #9b315b":"1px solid #7d8ea1",background:layoutSelection.includes(w.id)?"rgba(215,95,145,.18)":"rgba(125,142,161,.08)",boxSizing:"border-box"}}/>)}</div></div></div></div></div>
 </div></section>;
}
