"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./ProfileSocialControlsPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Settings={character_id:string;message_policy:"everyone"|"friends"|"none";comment_policy:"everyone"|"friends"|"none";friend_request_policy:"everyone"|"friends_of_friends"|"none";activity_visibility:"everyone"|"friends"|"private";show_status:boolean;show_visit_counter:boolean;named_profile_visitors:boolean};
type Presence={character_id:string;status_kind:string;status_message:string;do_not_disturb:boolean;dnd_until:string|null};
type Friendship={friendship_id:string;status:string;other_character_id:string;display_name:string;handle:string};
type TopFriend={friend_character_id:string;position:number};type Badge={id:string;label:string;badge_type:string;icon_text:string;description:string;visible:boolean};
const defaults=(id:string):Settings=>({character_id:id,message_policy:"everyone",comment_policy:"friends",friend_request_policy:"everyone",activity_visibility:"friends",show_status:true,show_visit_counter:true,named_profile_visitors:false});
export default function ProfileSocialControlsPanel({accessToken,characterId}:{accessToken:string;characterId:string}){
 const [settings,setSettings]=useState<Settings>(defaults(characterId));const [presence,setPresence]=useState<Presence>({character_id:characterId,status_kind:"online",status_message:"",do_not_disturb:false,dnd_until:null});const [friends,setFriends]=useState<Friendship[]>([]);const [top,setTop]=useState<TopFriend[]>([]);const [badges,setBadges]=useState<Badge[]>([]);const [visits,setVisits]=useState(0);const [namedVisits,setNamedVisits]=useState(0);const [notice,setNotice]=useState("Loading profile interaction controls…");const [dndUntil,setDndUntil]=useState("");
 const load=useCallback(async()=>{const [s,p,f,t,b,c,n]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/profile_interaction_settings?select=*&character_id=eq.${characterId}&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/character_presence?select=*&character_id=eq.${characterId}&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/character_friendship_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({viewer_character_id:characterId})}),
  fetch(`${SUPABASE_URL}/rest/v1/profile_top_friends?select=friend_character_id,position&character_id=eq.${characterId}&order=position`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/character_profile_badges?select=id,label,badge_type,icon_text,description,visible&character_id=eq.${characterId}&order=awarded_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/profile_visit_counters?select=total_visits&character_id=eq.${characterId}&limit=1`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/profile_named_visits?select=id&profile_character_id=eq.${characterId}`,{headers:headers(accessToken)})
 ]);if(s.ok){const rows=await s.json() as Settings[];setSettings(rows[0]??defaults(characterId));}if(p.ok){const rows=await p.json() as Presence[];if(rows[0]){setPresence(rows[0]);if(rows[0].dnd_until)setDndUntil(new Date(rows[0].dnd_until).toISOString().slice(0,16));}}if(f.ok)setFriends((await f.json() as Friendship[]).filter(x=>x.status==="accepted"));if(t.ok)setTop(await t.json());if(b.ok)setBadges((await b.json() as Badge[]).filter(x=>x.visible));if(c.ok){const rows=await c.json() as Array<{total_visits:number}>;setVisits(Number(rows[0]?.total_visits??0));}if(n.ok){const rows=await n.json() as Array<{id:string}>;setNamedVisits(rows.length);}setNotice("Profile interaction controls ready.");},[accessToken,characterId]);
 useEffect(()=>{void load();},[load]);
 async function saveSettings(next:Settings){setSettings(next);const r=await fetch(`${SUPABASE_URL}/rest/v1/profile_interaction_settings?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({...next,updated_at:new Date().toISOString()})});setNotice(r.ok?"Profile interaction privacy saved.":"Privacy settings could not be saved.");}
 async function savePresence(next:Presence){setPresence(next);const savedUntil=next.do_not_disturb&&dndUntil?new Date(dndUntil).toISOString():null;const r=await fetch(`${SUPABASE_URL}/rest/v1/character_presence?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({...next,dnd_until:savedUntil,updated_at:new Date().toISOString()})});if(r.ok){setPresence({...next,dnd_until:savedUntil});window.dispatchEvent(new CustomEvent("hanami-presence-changed",{detail:{characterId}}));setNotice("Character status saved.");}else setNotice("Character status could not be saved.");}
 async function setTopFriend(friendId:string,position:number){await fetch(`${SUPABASE_URL}/rest/v1/profile_top_friends?character_id=eq.${characterId}&position=eq.${position}`,{method:"DELETE",headers:headers(accessToken)});if(!friendId){setNotice(`Top Friend slot ${position} cleared.`);await load();return;}const r=await fetch(`${SUPABASE_URL}/rest/v1/profile_top_friends`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({character_id:characterId,friend_character_id:friendId,position})});if(r.ok){setNotice(`Top Friend slot ${position} updated.`);await load();}else setNotice("Top Friend could not be saved. Only accepted friends can be selected.");}
 const topRows=useMemo(()=>[1,2,3,4,5,6,7,8].map(position=>({position,current:top.find(t=>t.position===position)})),[top]);
 return <section className={styles.panel} aria-labelledby="social-profile-title"><div className={styles.header}><div><p className="eyebrow">2006 PROFILE NETWORK</p><h4 id="social-profile-title">Social profile controls</h4></div><p className={styles.notice} aria-live="polite">{notice}</p></div><div className={styles.grid}>
  <section className={styles.card}><h5>Interaction privacy</h5><div className={styles.statusRow}><label>Who can message me <select value={settings.message_policy} onChange={e=>saveSettings({...settings,message_policy:e.target.value as Settings["message_policy"]})}><option value="everyone">Everyone</option><option value="friends">Friends only</option><option value="none">No one</option></select></label><label>Who can comment <select value={settings.comment_policy} onChange={e=>saveSettings({...settings,comment_policy:e.target.value as Settings["comment_policy"]})}><option value="everyone">Everyone</option><option value="friends">Friends only</option><option value="none">No one</option></select></label><label>Friend requests <select value={settings.friend_request_policy} onChange={e=>saveSettings({...settings,friend_request_policy:e.target.value as Settings["friend_request_policy"]})}><option value="everyone">Everyone</option><option value="friends_of_friends">Friends of friends</option><option value="none">No one</option></select></label><label>Who can see my activity <select value={settings.activity_visibility} onChange={e=>saveSettings({...settings,activity_visibility:e.target.value as Settings["activity_visibility"]})}><option value="everyone">Everyone</option><option value="friends">Friends only</option><option value="private">Private</option></select></label><label className={styles.check}><input type="checkbox" checked={settings.show_visit_counter} onChange={e=>saveSettings({...settings,show_visit_counter:e.target.checked})}/> Show profile visit counter</label><label className={styles.check}><input type="checkbox" checked={settings.named_profile_visitors} onChange={e=>saveSettings({...settings,named_profile_visitors:e.target.checked})}/> Remember named visitors for me</label></div><div className={styles.statStrip}><div className={styles.stat}><strong>{visits}</strong><span>Total profile visits</span></div><div className={styles.stat}><strong>{settings.named_profile_visitors?namedVisits:"—"}</strong><span>Named visit records</span></div></div><p className={styles.hint}>These controls affect profile interactions only. School, moderation, and administrative access rules stay separate.</p></section>
  <section className={styles.card}><h5>Status & Do Not Disturb</h5><div className={styles.statusRow}><label>Presence <select value={presence.status_kind} onChange={e=>setPresence({...presence,status_kind:e.target.value})}><option value="online">Online</option><option value="studying">Studying</option><option value="club_practice">At club practice</option><option value="away">Away</option><option value="offline">Offline</option><option value="custom">Custom</option></select></label><label>Status message <input className={styles.full} value={presence.status_message} onChange={e=>setPresence({...presence,status_message:e.target.value})} placeholder="What are you doing right now?" maxLength={120}/></label><label className={styles.check}><input type="checkbox" checked={presence.do_not_disturb} onChange={e=>setPresence({...presence,do_not_disturb:e.target.checked})}/> Do Not Disturb</label>{presence.do_not_disturb&&<label>Until <input type="datetime-local" value={dndUntil} onChange={e=>setDndUntil(e.target.value)}/></label>}</div><div className={styles.actions}><button type="button" onClick={()=>savePresence(presence)}>Save status</button></div><p className={styles.hint}>DND suppresses nonessential portal notifications. Safety, moderation, and administrative notices remain visible.</p></section>
  <section className={styles.card}><h5>Top Friends</h5><p className={styles.hint}>Choose up to eight accepted friends to feature on your profile. This list is platonic-only.</p>{topRows.map(slot=>{const currentFriend=friends.find(f=>f.other_character_id===slot.current?.friend_character_id);return <label key={slot.position} className={styles.friendRow}><strong>#{slot.position}</strong><select value={slot.current?.friend_character_id??""} onChange={e=>setTopFriend(e.target.value,slot.position)}><option value="">Empty slot</option>{friends.map(f=><option key={f.other_character_id} value={f.other_character_id}>{f.display_name} (@{f.handle})</option>)}</select>{currentFriend&&<small>Current: {currentFriend.display_name}</small>}</label>})}</section>
  <section className={styles.card}><h5>Profile badges</h5>{badges.length?badges.map(b=><article key={b.id} className={styles.badge}><strong>{b.icon_text} {b.label}</strong><div className={styles.badgeMeta}>{b.badge_type.replaceAll("_"," ")}</div>{b.description&&<p className={styles.hint}>{b.description}</p>}</article>):<p className={styles.hint}>Visible club officer, Student Council, honor roll, event, graduating class, Faculty-role, and tester badges will appear here when awarded.</p>}</section>
 </div></section>;
}
