"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Props={accessToken:string;characterId:string};
type Widget={widget_type:string;x:number;y:number;width:number;height:number;z_index:number;rotation:number;opacity:number;content:Record<string,string>;style:Record<string,string|number>;locked:boolean};
type Canvas={canvas_width:number;canvas_height:number;background:string;grid_enabled:boolean;snap_enabled:boolean};
type TemplateData={canvas?:Canvas;widgets?:Widget[]};
type Template={id:string;owner_character_id:string;title:string;description:string;template_data:TemplateData;status:string;updated_at:string};
const card:React.CSSProperties={border:"1px solid #c7d1db",background:"#fff",padding:10};
function safeContent(widget:Widget){const content={...widget.content};delete content.storage_path;delete content.photo_paths;delete content.url;if(widget.widget_type==="image")content.alt=content.alt||"Template image placeholder";if(widget.widget_type==="photo_strip")content.text=content.text||"ADD YOUR PHOTOS";return content;}
export default function ProfileTemplateMarketplacePanel({accessToken,characterId}:Props){
 const [templates,setTemplates]=useState<Template[]>([]);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [notice,setNotice]=useState("Loading the non-monetary Profile Template Library…");const [busy,setBusy]=useState(false);
 const own=useMemo(()=>templates.filter(t=>t.owner_character_id===characterId),[templates,characterId]);const published=useMemo(()=>templates.filter(t=>t.status==="published"),[templates]);
 const load=useCallback(async()=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/profile_template_library?select=id,owner_character_id,title,description,template_data,status,updated_at&or=(status.eq.published,owner_character_id.eq.${encodeURIComponent(characterId)})&order=updated_at.desc`,{headers:headers(accessToken)});if(r.ok){setTemplates(await r.json() as Template[]);setNotice("Profile Template Library ready. Templates are shared without money or credits.");}else setNotice("Profile Template Library could not be loaded.");},[accessToken,characterId]);useEffect(()=>{void load();},[load]);
 async function saveCurrent(e:FormEvent){e.preventDefault();if(!title.trim()||busy)return;setBusy(true);try{const [canvasResponse,widgetsResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?select=canvas_width,canvas_height,background,grid_enabled,snap_enabled&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?select=widget_type,x,y,width,height,z_index,rotation,opacity,content,style,locked&character_id=eq.${encodeURIComponent(characterId)}&order=z_index.asc`,{headers:headers(accessToken)})]);if(!canvasResponse.ok||!widgetsResponse.ok)throw new Error("Current Profile Studio layout could not be read.");const canvas=(await canvasResponse.json() as Canvas[])[0];const widgets=await widgetsResponse.json() as Widget[];const templateData:TemplateData={canvas,widgets:widgets.map(w=>({...w,content:safeContent(w),locked:false})).slice(0,40)};const create=await fetch(`${SUPABASE_URL}/rest/v1/profile_template_library`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({owner_character_id:characterId,title:title.trim(),description:description.trim(),template_data:templateData,status:"draft"})});if(!create.ok)throw new Error("Template draft could not be saved.");setTitle("");setDescription("");setNotice("Template draft saved. Submit it for moderation when ready.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Template draft could not be saved.");}finally{setBusy(false);}}
 async function submit(template:Template){setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/submit_profile_template_for_review`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_template_id:template.id,target_character_id:characterId})});if(!r.ok||!Boolean(await r.json()))throw new Error("Template could not be submitted for review.");setNotice("Template submitted to the shared Content Approval Queue.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Template could not be submitted.");}finally{setBusy(false);}}
 async function applyTemplate(template:Template){if(busy||template.status!=="published")return;setBusy(true);try{const countResponse=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets?select=id&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)});if(!countResponse.ok)throw new Error("Profile capacity could not be checked.");const current=(await countResponse.json() as {id:string}[]).length;const room=Math.max(0,40-current);const widgets=(template.template_data?.widgets??[]).slice(0,room);if(!room||!widgets.length)throw new Error(room?"This template has no reusable widgets.":"This profile already has the 40-widget maximum.");const maxZ=current+10;const rows=widgets.map((w,index)=>({character_id:characterId,widget_type:w.widget_type,x:w.x,y:w.y,width:w.width,height:w.height,z_index:maxZ+index,rotation:w.rotation??0,opacity:w.opacity??1,content:safeContent(w),style:w.style??{},locked:false}));const create=await fetch(`${SUPABASE_URL}/rest/v1/character_profile_widgets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(rows)});if(!create.ok)throw new Error("Template widgets could not be applied.");if(template.template_data?.canvas?.background){await fetch(`${SUPABASE_URL}/rest/v1/character_profile_canvases?character_id=eq.${encodeURIComponent(characterId)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({background:template.template_data.canvas.background,updated_at:new Date().toISOString()})});}window.dispatchEvent(new CustomEvent("hanami-profile-studio-refresh",{detail:{characterId}}));setNotice(`Applied ${rows.length} widget${rows.length===1?"":"s"} from “${template.title}”. Existing widgets were preserved.`);}catch(error){setNotice(error instanceof Error?error.message:"Template could not be applied.");}finally{setBusy(false);}}
 return <section style={{border:"1px solid #b7c3d0",background:"#f7f9fb",padding:12,display:"grid",gap:12}} aria-label="Profile template marketplace"><div><p className="eyebrow">PROFILE TEMPLATE LIBRARY</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Community Templates • Non-monetary</h4><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:12}}><article style={card}><h5>Save My Current Layout</h5><form onSubmit={saveCurrent} style={{display:"grid",gap:6}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Template title" required/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the layout" rows={2}/><button disabled={busy}>Save template draft</button></form>{own.map(t=><div key={t.id} style={{borderTop:"1px solid #e2e7ec",padding:"7px 0"}}><strong>{t.title}</strong><small style={{display:"block"}}>{t.status.replaceAll("_"," ")} • {t.description}</small>{["draft","rejected"].includes(t.status)&&<button type="button" disabled={busy} onClick={()=>void submit(t)}>Submit for review</button>}</div>)}</article><article style={card}><h5>Published Templates</h5>{published.length?published.map(t=><div key={t.id} style={{borderTop:"1px solid #e2e7ec",padding:"7px 0"}}><strong>{t.title}</strong><small style={{display:"block"}}>{t.description||"Community Profile Studio layout"}</small><small style={{display:"block"}}>{t.template_data?.widgets?.length??0} reusable widgets • media is intentionally excluded</small><button type="button" disabled={busy} onClick={()=>void applyTemplate(t)}>Apply to my canvas</button></div>):<p>No moderated community templates are published yet.</p>}</article></div></section>;
}
