"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function rpc<T>(token:string,name:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}

type Props={accessToken:string;characterId:string;role:"student"|"faculty"};
type Match={group_id:string;name:string;subject:string;meeting_location:string|null;meeting_schedule:string|null;member_count:number;member_limit:number;shared_course:boolean;match_score:number};
type Group={id:string;creator_character_id:string;name:string;description:string;subject:string;meeting_location:string|null;meeting_schedule:string|null;member_limit:number;status:string};
type Membership={group_id:string;character_id:string;role:string};
type MatchProfile={availability_text:string;preferred_subjects:string[];is_matchable:boolean};
type EventRow={id:string;title:string;description:string;location:string|null;starts_at:string;ends_at:string|null;all_day:boolean;category:string;registration_open:boolean};
type Rsvp={event_id:string;response:"attending"|"maybe"|"not_attending";note:string};

const panel:React.CSSProperties={border:"1px solid #b7c3d0",background:"#f7f9fb",padding:12,display:"grid",gap:12};
const card:React.CSSProperties={border:"1px solid #ccd6df",background:"#fff",padding:10};
function tokyo(value:string){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));}

export default function RoadmapSocialProgramsPanel({accessToken,characterId,role}:Props){
 const [matches,setMatches]=useState<Match[]>([]);const [groups,setGroups]=useState<Group[]>([]);const [memberships,setMemberships]=useState<Membership[]>([]);const [profile,setProfile]=useState<MatchProfile>({availability_text:"",preferred_subjects:[],is_matchable:true});const [events,setEvents]=useState<EventRow[]>([]);const [rsvps,setRsvps]=useState<Rsvp[]>([]);const [notice,setNotice]=useState("Loading study matching and event RSVPs…");const [busy,setBusy]=useState(false);
 const [availability,setAvailability]=useState("");const [subjects,setSubjects]=useState("");const [groupName,setGroupName]=useState("");const [groupSubject,setGroupSubject]=useState("");const [groupDescription,setGroupDescription]=useState("");const [groupLocation,setGroupLocation]=useState("");const [groupSchedule,setGroupSchedule]=useState("");
 const membershipSet=useMemo(()=>new Set(memberships.filter(m=>m.character_id===characterId).map(m=>m.group_id)),[memberships,characterId]);
 const rsvpMap=useMemo(()=>new Map(rsvps.map(r=>[r.event_id,r])),[rsvps]);

 const load=useCallback(async()=>{try{const requests:Promise<Response>[]=[
   fetch(`${SUPABASE_URL}/rest/v1/study_groups?select=id,creator_character_id,name,description,subject,meeting_location,meeting_schedule,member_limit,status&status=eq.open&order=created_at.desc`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/study_group_members?select=group_id,character_id,role`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/study_match_profiles?select=availability_text,preferred_subjects,is_matchable&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/school_calendar_events?select=id,title,description,location,starts_at,ends_at,all_day,category,registration_open&status=eq.published&starts_at=gte.${encodeURIComponent(new Date(Date.now()-86400000).toISOString())}&order=starts_at.asc&limit=20`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/event_rsvps?select=event_id,response,note&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)})
  ];const [g,m,p,e,r]=await Promise.all(requests);if(g.ok)setGroups(await g.json() as Group[]);if(m.ok)setMemberships(await m.json() as Membership[]);if(p.ok){const rows=await p.json() as MatchProfile[];const next=rows[0]??{availability_text:"",preferred_subjects:[],is_matchable:true};setProfile(next);setAvailability(next.availability_text);setSubjects((next.preferred_subjects??[]).join(", "));}if(e.ok)setEvents(await e.json() as EventRow[]);if(r.ok)setRsvps(await r.json() as Rsvp[]);if(role==="student")setMatches(await rpc<Match[]>(accessToken,"study_group_matches",{viewer_character_id:characterId}).catch(()=>[]));setNotice("Study matching and event RSVP systems ready.");}catch(error){setNotice(error instanceof Error?error.message:"Study and RSVP systems could not be loaded.");}},[accessToken,characterId,role]);
 useEffect(()=>{void load();},[load]);

 async function saveMatchProfile(event:FormEvent){event.preventDefault();if(role!=="student")return;setBusy(true);try{const preferred=[...new Set(subjects.split(",").map(v=>v.trim()).filter(Boolean))].slice(0,12);const response=await fetch(`${SUPABASE_URL}/rest/v1/study_match_profiles?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({character_id:characterId,availability_text:availability.trim(),preferred_subjects:preferred,is_matchable:profile.is_matchable,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Study-match availability could not be saved.");setNotice("Study-match preferences saved.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Study-match preferences could not be saved.");}finally{setBusy(false);}}
 async function setMatchable(value:boolean){if(role!=="student")return;setProfile(current=>({...current,is_matchable:value}));const response=await fetch(`${SUPABASE_URL}/rest/v1/study_match_profiles?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({character_id:characterId,availability_text:availability.trim(),preferred_subjects:subjects.split(",").map(v=>v.trim()).filter(Boolean),is_matchable:value,updated_at:new Date().toISOString()})});setNotice(response.ok?(value?"Study matching enabled.":"Study matching hidden."):"Study matching preference could not be changed.");}
 async function createGroup(event:FormEvent){event.preventDefault();if(role!=="student"||!groupName.trim()||!groupSubject.trim())return;setBusy(true);try{const create=await fetch(`${SUPABASE_URL}/rest/v1/study_groups`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({creator_character_id:characterId,name:groupName.trim(),subject:groupSubject.trim(),description:groupDescription.trim(),meeting_location:groupLocation.trim()||null,meeting_schedule:groupSchedule.trim()||null,member_limit:8,status:"open"})});if(!create.ok)throw new Error("Study group could not be created.");const row=(await create.json() as Group[])[0];if(!row)throw new Error("Study group creation could not be confirmed.");const join=await fetch(`${SUPABASE_URL}/rest/v1/study_group_members`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({group_id:row.id,character_id:characterId,role:"organizer"})});if(!join.ok)throw new Error("Study group was created but organizer membership failed.");setGroupName("");setGroupSubject("");setGroupDescription("");setGroupLocation("");setGroupSchedule("");setNotice("Study group created and you were added as organizer.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Study group could not be created.");}finally{setBusy(false);}}
 async function toggleGroup(groupId:string){if(role!=="student")return;setBusy(true);try{const joined=membershipSet.has(groupId);const endpoint=joined?`${SUPABASE_URL}/rest/v1/study_group_members?group_id=eq.${groupId}&character_id=eq.${encodeURIComponent(characterId)}`:`${SUPABASE_URL}/rest/v1/study_group_members`;const response=await fetch(endpoint,{method:joined?"DELETE":"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:joined?undefined:JSON.stringify({group_id:groupId,character_id:characterId,role:"member"})});if(!response.ok)throw new Error(joined?"Study group could not be left.":"Study group could not be joined.");setNotice(joined?"You left the study group.":"You joined the study group.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Study group membership could not be changed.");}finally{setBusy(false);}}
 async function setRsvp(eventId:string,responseValue:Rsvp["response"]){setBusy(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/event_rsvps?on_conflict=event_id,character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({event_id:eventId,character_id:characterId,response:responseValue,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Event RSVP could not be saved.");setNotice(`RSVP saved: ${responseValue.replaceAll("_"," ")}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Event RSVP could not be saved.");}finally{setBusy(false);}}

 return <section style={panel} aria-label="Roadmap social programs"><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",alignItems:"center"}}><div><p className="eyebrow">ROADMAP SOCIAL PROGRAMS</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Study Groups & Event RSVPs</h4></div><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}>
 {role==="student"&&<article style={card}><h5>Study Group Matching</h5><form onSubmit={saveMatchProfile} style={{display:"grid",gap:6}}><textarea value={availability} onChange={e=>setAvailability(e.target.value)} placeholder="Availability, e.g. Tue/Thu after 4 PM" rows={2}/><input value={subjects} onChange={e=>setSubjects(e.target.value)} placeholder="Preferred subjects, comma separated"/><label style={{fontSize:9}}><input type="checkbox" checked={profile.is_matchable} onChange={e=>void setMatchable(e.target.checked)}/> Let other Students find my study-match profile</label><button disabled={busy}>Save matching preferences</button></form><div style={{marginTop:9}}>{matches.length?matches.slice(0,10).map(match=><div key={match.group_id} style={{borderTop:"1px solid #e2e7ec",padding:"8px 0"}}><strong>{match.name}</strong><small style={{display:"block"}}>{match.subject||"General study"} • {match.member_count}/{match.member_limit} members{match.shared_course?" • shared class":""}{match.match_score>0?` • match ${match.match_score}`:""}</small><small style={{display:"block"}}>{match.meeting_schedule||"Schedule flexible"}{match.meeting_location?` • ${match.meeting_location}`:""}</small><button type="button" disabled={busy} onClick={()=>void toggleGroup(match.group_id)}>{membershipSet.has(match.group_id)?"Leave group":"Join group"}</button></div>):<p>No open study-group matches yet.</p>}</div></article>}
 {role==="student"&&<article style={card}><h5>Create Study Group</h5><form onSubmit={createGroup} style={{display:"grid",gap:6}}><input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Group name" required/><input value={groupSubject} onChange={e=>setGroupSubject(e.target.value)} placeholder="Subject / class" required/><textarea value={groupDescription} onChange={e=>setGroupDescription(e.target.value)} placeholder="What will the group work on?" rows={2}/><input value={groupSchedule} onChange={e=>setGroupSchedule(e.target.value)} placeholder="Meeting availability / schedule"/><input value={groupLocation} onChange={e=>setGroupLocation(e.target.value)} placeholder="Meeting location"/><button disabled={busy}>Create study group</button></form><div style={{marginTop:9}}>{groups.filter(g=>membershipSet.has(g.id)).map(g=><p key={g.id}><strong>{g.name}</strong><small style={{display:"block"}}>{g.subject} • {g.meeting_schedule||"flexible"}</small></p>)}</div></article>}
 <article style={{...card,gridColumn:role==="faculty"?"1/-1":undefined}}><h5>Optional Event RSVP</h5><p style={{fontSize:9}}>Mark attending, maybe, or not attending for optional published school events. This does not replace required-event attendance or formal registration.</p>{events.length?events.map(event=><div key={event.id} style={{borderTop:"1px solid #e2e7ec",padding:"8px 0"}}><strong>{event.title}</strong><small style={{display:"block"}}>{tokyo(event.starts_at)}{event.location?` • ${event.location}`:""} • {String(event.category).replaceAll("_"," ")}</small>{event.description&&<p style={{fontSize:9}}>{event.description}</p>}<div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{(["attending","maybe","not_attending"] as const).map(value=><button key={value} type="button" disabled={busy} onClick={()=>void setRsvp(event.id,value)} style={{fontWeight:rsvpMap.get(event.id)?.response===value?700:400}}>{rsvpMap.get(event.id)?.response===value?"✓ ":""}{value.replaceAll("_"," ")}</button>)}</div></div>):<p>No upcoming published events are available for RSVP.</p>}</article>
 </div></section>;
}
