"use client";

import {useCallback,useEffect,useState} from "react";
import DashboardShell,{type ActiveCharacter} from "./DashboardShell";
import GuidedFirstLoginTour from "./GuidedFirstLoginTour";
import StudentSettingsDrawer from "./StudentSettingsDrawer";
import StudentAcceptanceExperience from "./StudentAcceptanceExperience";
import styles from "./RolePortalClient.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";const CHARACTER_SESSION_KEY_PREFIX="hanami.portal.character.v2";const OWNER_PREVIEW_KEY="hanami.owner.preview.v1";const OWNER_PREVIEW_PREFIX="owner-preview-";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};type Role="student"|"faculty";type Props={role:Role};type RoleSync={student:boolean;faculty:boolean;administrator:boolean;owner:boolean;synced_at:string|null;sync_status:"pending"|"synced"|"not_member"|"error"};type AccountStatus={account_status:string;suspension_reason:string|null};type OwnerPreviewMeta={characterId:string;name:string;role:Role;startedAt:number};
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
function readPreview():OwnerPreviewMeta|null{try{const raw=localStorage.getItem(OWNER_PREVIEW_KEY);if(!raw)return null;const v=JSON.parse(raw) as OwnerPreviewMeta;return v&&typeof v.characterId==="string"?v:null;}catch{return null;}}
function characterSessionKey(userId:string){return `${CHARACTER_SESSION_KEY_PREFIX}.${userId}`;}
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
async function refreshSession(session:PortalSession):Promise<PortalSession|null>{const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return null;const data=await response.json() as {access_token?:string;refresh_token?:string;expires_in?:number;token_type?:string};if(!data.access_token||!data.refresh_token)return null;const next={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+(data.expires_in??3600)*1000,tokenType:data.token_type??"bearer"};localStorage.setItem(SESSION_KEY,JSON.stringify(next));return next;}
async function currentUserId(accessToken:string){const response=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(accessToken),cache:"no-store"});if(!response.ok)return null;const user=await response.json() as {id?:string};return user.id??null;}
async function refreshDiscordRoles(accessToken:string){try{await fetch(`${SUPABASE_URL}/functions/v1/discord-role-sync`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,apikey:SUPABASE_PUBLISHABLE_KEY}});}catch{}const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_discord_role_sync`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return null;const rows=await response.json() as RoleSync[];return rows[0]??null;}
async function currentAccountStatus(accessToken:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_account_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return null;const rows=await response.json() as AccountStatus[];return rows[0]??null;}
async function currentOwnerStatus(accessToken:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return false;return Boolean(await response.json());}
async function fetchCharacters(accessToken:string,query:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,slot,role,display_name,handle,visibility,is_active,owner_user_id&${query}`,{headers:headers(accessToken),cache:"no-store"});if(!response.ok)throw new Error("Your Hanami characters could not be restored.");return await response.json() as (ActiveCharacter&{owner_user_id?:string})[];}
function ownerPreviewCharacter(role:Role):ActiveCharacter{return {id:`${OWNER_PREVIEW_PREFIX}${role}`,slot:0,role,display_name:`Owner ${role==="student"?"Student":"Faculty"} Preview`,handle:`owner_${role}_preview`,visibility:"private",is_active:false};}

export default function RolePortalClient({role}:Props){
 const [session,setSession]=useState<PortalSession|null>(null);const [character,setCharacter]=useState<ActiveCharacter|null>(null);const [accountUserId,setAccountUserId]=useState("");const [state,setState]=useState<"loading"|"ready"|"blocked">("loading");const [message,setMessage]=useState("Restoring your Hanami character session…");const [ownerPreview,setOwnerPreview]=useState<OwnerPreviewMeta|null>(null);
 const logout=useCallback(async()=>{const active=session;try{if(active&&character&&!character.id.startsWith(OWNER_PREVIEW_PREFIX)&&!ownerPreview&&accountUserId)await fetch(`${SUPABASE_URL}/rest/v1/characters?owner_user_id=eq.${encodeURIComponent(accountUserId)}&is_active=eq.true`,{method:"PATCH",headers:headers(active.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({is_active:false})});}finally{localStorage.removeItem(SESSION_KEY);if(accountUserId)localStorage.removeItem(characterSessionKey(accountUserId));localStorage.removeItem("hanami.portal.character.v1");localStorage.removeItem(OWNER_PREVIEW_KEY);window.location.assign("../");}},[character,session,ownerPreview,accountUserId]);
 useEffect(()=>{let cancelled=false;async function initialize(){try{let stored=readSession();if(!stored){if(!cancelled){setState("blocked");setMessage("You are signed out. Return to the portal gateway to sign in with Discord.");}return;}if(stored.expiresAt-Date.now()<120000){stored=await refreshSession(stored);if(!stored){localStorage.removeItem(SESSION_KEY);localStorage.removeItem("hanami.portal.character.v1");if(!cancelled){setState("blocked");setMessage("Your Hanami session expired. Sign in again from the portal gateway.");}return;}}
 const userId=await currentUserId(stored.accessToken);if(!userId){localStorage.removeItem(SESSION_KEY);if(!cancelled){setState("blocked");setMessage("Your authenticated Hanami account could not be verified. Please sign in again.");}return;}localStorage.removeItem("hanami.portal.character.v1");if(!cancelled)setAccountUserId(userId);
 const [accountStatus,roleSync,isOwner]=await Promise.all([currentAccountStatus(stored.accessToken),refreshDiscordRoles(stored.accessToken),currentOwnerStatus(stored.accessToken)]);if(accountStatus?.account_status==="suspended"){if(!cancelled){setSession(stored);setState("blocked");setMessage(`This Hanami account is suspended.${accountStatus.suspension_reason?` Reason: ${accountStatus.suspension_reason}`:""}`);}return;}
 const previewMeta=isOwner?readPreview():null;const rememberedId=previewMeta?.role===role?previewMeta.characterId:localStorage.getItem(characterSessionKey(userId));let activeCharacter:(ActiveCharacter&{owner_user_id?:string})|null=null;if(rememberedId&&!rememberedId.startsWith(OWNER_PREVIEW_PREFIX)){const remembered=(await fetchCharacters(stored.accessToken,`id=eq.${encodeURIComponent(rememberedId)}&owner_user_id=eq.${encodeURIComponent(userId)}&limit=1`))[0]??null;if(remembered?.role===role&&remembered.owner_user_id===userId)activeCharacter=remembered;else localStorage.removeItem(characterSessionKey(userId));}
 if(!activeCharacter&&isOwner){if(previewMeta?.role===role&&!previewMeta.characterId.startsWith(OWNER_PREVIEW_PREFIX)){const preview=(await fetchCharacters(stored.accessToken,`id=eq.${encodeURIComponent(previewMeta.characterId)}&limit=1`))[0]??null;if(preview?.role===role)activeCharacter=preview;}if(!activeCharacter)activeCharacter=ownerPreviewCharacter(role);}
 if(!activeCharacter&&!isOwner){const active=await fetchCharacters(stored.accessToken,`owner_user_id=eq.${encodeURIComponent(userId)}&is_active=eq.true&role=eq.${role}&limit=1`);activeCharacter=active[0]??null;}
 if(!activeCharacter){if(!cancelled){setSession(stored);setState("blocked");setMessage("No matching character is active for this account. Choose a character from the portal gateway first.");}return;}
 if(activeCharacter.role!==role){if(!cancelled){setSession(stored);setCharacter(activeCharacter);setState("blocked");setMessage(`Your active character is a ${activeCharacter.role}. Open the matching portal section or switch characters.`);}return;}
 if(!isOwner&&roleSync?.sync_status==="not_member"){if(!cancelled){setSession(stored);setState("blocked");setMessage("Your Discord account is not currently a member of the configured Hanami server.");}return;}if(!isOwner&&roleSync?.sync_status==="synced"&&!roleSync[role]){if(!cancelled){setSession(stored);setState("blocked");setMessage(`Your Discord account does not currently have the Hanami ${role==="student"?"Student":"Faculty"} role required for this portal.`);}return;}
 const ownerShellPreview=isOwner&&activeCharacter.id.startsWith(OWNER_PREVIEW_PREFIX);if(!ownerShellPreview&&!ownerPreview)localStorage.setItem(characterSessionKey(userId),activeCharacter.id);if(!cancelled){setSession(stored);setCharacter(activeCharacter);setOwnerPreview(previewMeta?.characterId===activeCharacter.id?previewMeta:null);setState("ready");setMessage(ownerShellPreview?`Owner ${role} portal shell preview opened without an OC.`:ownerPreview?`Owner previewing the ${role} portal as ${activeCharacter.display_name}.`:`${activeCharacter.display_name} restored as your active character.`);}}catch(error){if(!cancelled){setState("blocked");setMessage(error instanceof Error?error.message:"The portal session could not be restored.");}}}initialize();return()=>{cancelled=true;};},[role]);
 if(state!=="ready"||!session||!character)return <section className={styles.gate}><p className="eyebrow">{role.toUpperCase()} PORTAL</p><h2>{state==="loading"?"Opening your school desk…":"Portal access paused"}</h2><p>{message}</p><div className={styles.actions}><a href="../">Return to character gateway</a>{session&&<button type="button" onClick={logout}>Logout</button>}</div></section>;
 const ownerShellPreview=character.id.startsWith(OWNER_PREVIEW_PREFIX);
 function exitOwnerPreview(){localStorage.removeItem(OWNER_PREVIEW_KEY);window.location.assign("../owner/");}
 return <div className={styles.portal}>{ownerPreview&&<div style={{position:"sticky",top:0,zIndex:2000,padding:"9px 12px",borderBottom:"1px solid #a97821",background:"#fff1b8",font:"600 11px Arial,sans-serif",display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><span>OWNER PREVIEW MODE • Viewing the complete {ownerPreview.role} portal as {ownerPreview.name}. Your Owner account remains active; this does not sign in as the user.</span><button type="button" onClick={exitOwnerPreview} style={{border:"1px solid #7a5411",background:"#fff",padding:"5px 8px",font:"600 10px Arial,sans-serif"}}>Return to Owner Portal</button></div>}{ownerShellPreview&&<div style={{padding:"8px 12px",borderBottom:"1px solid #d9c576",background:"#fff7d8",font:"600 11px Arial,sans-serif"}}>OWNER PREVIEW • This is a read-only empty portal shell because no {role} character exists. Use Owner → Role Tester to inspect real user portals.</div>}<DashboardShell character={character} accessToken={session.accessToken} onLogout={logout}/>{!ownerShellPreview&&!ownerPreview&&<><StudentSettingsDrawer accessToken={session.accessToken} characterId={character.id}/>{role==="student"&&<StudentAcceptanceExperience accessToken={session.accessToken} characterId={character.id} displayName={character.display_name}/>}<GuidedFirstLoginTour characterId={character.id} role={role}/></>}</div>;
}