"use client";

import {useCallback,useEffect,useState} from "react";
import DashboardShell,{type ActiveCharacter} from "./DashboardShell";
import GuidedFirstLoginTour from "./GuidedFirstLoginTour";
import styles from "./RolePortalClient.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";const CHARACTER_SESSION_KEY="hanami.portal.character.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};type Role="student"|"faculty";type Props={role:Role};type RoleSync={student:boolean;faculty:boolean;administrator:boolean;owner:boolean;synced_at:string|null;sync_status:"pending"|"synced"|"not_member"|"error"};type AccountStatus={account_status:string;suspension_reason:string|null};
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
async function refreshSession(session:PortalSession):Promise<PortalSession|null>{const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return null;const data=await response.json() as {access_token?:string;refresh_token?:string;expires_in?:number;token_type?:string};if(!data.access_token||!data.refresh_token)return null;const next={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+(data.expires_in??3600)*1000,tokenType:data.token_type??"bearer"};localStorage.setItem(SESSION_KEY,JSON.stringify(next));return next;}
async function refreshDiscordRoles(accessToken:string){try{await fetch(`${SUPABASE_URL}/functions/v1/discord-role-sync`,{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,apikey:SUPABASE_PUBLISHABLE_KEY}});}catch{}const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_discord_role_sync`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return null;const rows=await response.json() as RoleSync[];return rows[0]??null;}
async function currentAccountStatus(accessToken:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_account_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return null;const rows=await response.json() as AccountStatus[];return rows[0]??null;}
async function currentOwnerStatus(accessToken:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)return false;return Boolean(await response.json());}
export default function RolePortalClient({role}:Props){
 const [session,setSession]=useState<PortalSession|null>(null);const [character,setCharacter]=useState<ActiveCharacter|null>(null);const [state,setState]=useState<"loading"|"ready"|"blocked">("loading");const [message,setMessage]=useState("Restoring your Hanami character session…");
 const logout=useCallback(async()=>{const active=session;try{if(active)await fetch(`${SUPABASE_URL}/rest/v1/characters?is_active=eq.true`,{method:"PATCH",headers:headers(active.accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({is_active:false})});}finally{localStorage.removeItem(SESSION_KEY);localStorage.removeItem(CHARACTER_SESSION_KEY);window.location.assign("../");}},[session]);
 useEffect(()=>{let cancelled=false;async function initialize(){try{let stored=readSession();if(!stored){if(!cancelled){setState("blocked");setMessage("You are signed out. Return to the portal gateway to sign in with Discord.");}return;}if(stored.expiresAt-Date.now()<120000){stored=await refreshSession(stored);if(!stored){localStorage.removeItem(SESSION_KEY);localStorage.removeItem(CHARACTER_SESSION_KEY);if(!cancelled){setState("blocked");setMessage("Your Hanami session expired. Sign in again from the portal gateway.");}return;}}
  const [accountStatus,roleSync,isOwner]=await Promise.all([currentAccountStatus(stored.accessToken),refreshDiscordRoles(stored.accessToken),currentOwnerStatus(stored.accessToken)]);if(accountStatus?.account_status==="suspended"){if(!cancelled){setSession(stored);setState("blocked");setMessage(`This Hanami account is suspended.${accountStatus.suspension_reason?` Reason: ${accountStatus.suspension_reason}`:""}`);}return;}const rememberedId=localStorage.getItem(CHARACTER_SESSION_KEY);const query=rememberedId?`id=eq.${encodeURIComponent(rememberedId)}&is_active=eq.true`:`is_active=eq.true`;const response=await fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,slot,role,display_name,handle,visibility,is_active&${query}&limit=1`,{headers:headers(stored.accessToken)});if(!response.ok)throw new Error("Your active character could not be restored.");const rows=await response.json() as ActiveCharacter[];const activeCharacter=rows[0]??null;if(!activeCharacter){if(!cancelled){setSession(stored);setState("blocked");setMessage("No character is active. Choose a character from the portal gateway first.");}return;}if(activeCharacter.role!==role){if(!cancelled){setSession(stored);setCharacter(activeCharacter);setState("blocked");setMessage(`Your active character is a ${activeCharacter.role}. Open the matching portal section or switch characters.`);}return;}const ownerTestFaculty=isOwner&&role==="faculty"&&activeCharacter.handle.startsWith("testfaculty_");if(roleSync?.sync_status==="not_member"&&!ownerTestFaculty){if(!cancelled){setSession(stored);setState("blocked");setMessage("Your Discord account is not currently a member of the configured Hanami server.");}return;}if(roleSync?.sync_status==="synced"&&!roleSync[role]&&!ownerTestFaculty){if(!cancelled){setSession(stored);setState("blocked");setMessage(`Your Discord account does not currently have the Hanami ${role==="student"?"Student":"Faculty"} role required for this portal.`);}return;}localStorage.setItem(CHARACTER_SESSION_KEY,activeCharacter.id);if(!cancelled){setSession(stored);setCharacter(activeCharacter);setState("ready");setMessage(`${activeCharacter.display_name} restored as your active character.`);}}catch(error){if(!cancelled){setState("blocked");setMessage(error instanceof Error?error.message:"The portal session could not be restored.");}}}initialize();return()=>{cancelled=true;};},[role]);
 if(state!=="ready"||!session||!character)return <section className={styles.gate}><p className="eyebrow">{role.toUpperCase()} PORTAL</p><h2>{state==="loading"?"Opening your school desk…":"Portal access paused"}</h2><p>{message}</p><div className={styles.actions}><a href="../">Return to character gateway</a>{session&&<button type="button" onClick={logout}>Logout</button>}</div></section>;
 return <div className={styles.portal}><DashboardShell character={character} accessToken={session.accessToken} onLogout={logout}/><GuidedFirstLoginTour characterId={character.id} role={role}/></div>;
}
