"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Rumor={id:string;display_alias:string;rumor_text:string;status:string;published_at:string|null;created_at:string};
export default function RumorsBoardPanel({accessToken,characterId}:{accessToken:string;characterId:string}){const [rows,setRows]=useState<Rumor[]>([]);const [text,setText]=useState("");const [alias,setAlias]=useState("Anonymous Student");const [notice,setNotice]=useState("Loading approved rumors…");const load=useCallback(async()=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/school_rumors?select=id,display_alias,rumor_text,status,published_at,created_at&order=published_at.desc.nullslast,created_at.desc&limit=40`,{headers:headers(accessToken)});if(r.ok){setRows(await r.json());setNotice("Rumors Board updated. Published posts were reviewed by staff.");}},[accessToken]);useEffect(()=>{void load();},[load]);async function submit(){if(text.trim().length<10){setNotice("Rumor submissions must be at least 10 characters.");return;}const r=await fetch(`${SUPABASE_URL}/rest/v1/school_rumors`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({submitted_by_character_id:characterId,display_alias:alias.trim()||"Anonymous Student",rumor_text:text.trim()})});if(r.ok){await fetch(`${SUPABASE_URL}/rest/v1/content_approval_queue`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({content_type:"rumor",submitted_by_character_id:characterId,title:"Rumor submission",summary:text.trim().slice(0,180),payload:{alias:alias.trim()||"Anonymous Student"}})}).catch(()=>undefined);setText("");setNotice("Rumor submitted for Broadcast Committee/Admin review. Your identity is hidden from readers but retained internally for moderation.");await load();}else setNotice("Rumor could not be submitted.");}
 return <section style={{marginTop:12,border:"1px solid #b7a4ad",background:"#fff9fb"}}><div style={{padding:11,borderBottom:"1px solid #dfcfd6"}}><p className="eyebrow">SCHOOL RUMORS BOARD</p><h4 style={{margin:"3px 0",font:"400 20px Georgia,serif"}}>Anonymous in-character submissions</h4><small>{notice}</small></div><div style={{padding:12,display:"grid",gridTemplateColumns:"minmax(240px,.8fr) minmax(280px,1.2fr)",gap:12}}><div><input value={alias} onChange={e=>setAlias(e.target.value)} maxLength={60} placeholder="Display alias" style={{width:"100%",boxSizing:"border-box"}}/><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={1200} placeholder="Submit an in-character school rumor. No harassment, NSFW, romance, or rule-breaking content." style={{width:"100%",minHeight:100,boxSizing:"border-box",marginTop:6}}/><button type="button" onClick={submit}>Submit for review</button><p style={{fontSize:9}}>Readers never see who submitted a rumor. Moderators retain the internal submitter character ID so abuse cannot hide behind anonymity.</p></div><div>{rows.filter(r=>r.status==="published").length?rows.filter(r=>r.status==="published").map(r=><article key={r.id} style={{padding:9,border:"1px solid #e0d4d9",marginBottom:7,background:"#fff"}}><strong>{r.display_alias}</strong><p style={{fontSize:10}}>{r.rumor_text}</p><small>{r.published_at?new Date(r.published_at).toLocaleString():"Published"}</small></article>):<p>No approved rumors have been published yet.</p>}</div></div></section>;
}
