"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./SchedulePanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";

type Meeting={id:string;weekday:number;starts_at:string;ends_at:string;label:string|null};
type Course={code:string;title:string;department:string;credits:number};
type Section={id:string;section_code:string;term:string;room:string|null;academic_courses:Course|null;section_meetings:Meeting[]};
type Membership={relationship:"student"|"instructor";class_sections:Section|null};
type InstructorRow={section_id:string;characters:{display_name:string;handle:string}|null};
type CharacterPreference={class_banner_colors:Record<string,string>};
type Props={accessToken:string;characterId:string;role:"student"|"faculty"};

function authHeaders(accessToken:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`};}
function timeLabel(value:string){const [hourRaw,minute]=value.split(":");const hour=Number(hourRaw);const suffix=hour>=12?"PM":"AM";return `${hour%12||12}:${minute} ${suffix}`;}
const DAY_SHORT=["","Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function validHex(value:string|undefined){return Boolean(value&&/^#[0-9a-f]{6}$/i.test(value));}

export default function SchedulePanel({accessToken,characterId,role}:Props){
 const [memberships,setMemberships]=useState<Membership[]>([]);const [instructors,setInstructors]=useState<InstructorRow[]>([]);const [bannerColors,setBannerColors]=useState<Record<string,string>>({});const [state,setState]=useState<"loading"|"ready"|"error">("loading");const [message,setMessage]=useState("Loading your Hanami classes…");
 useEffect(()=>{let cancelled=false;async function load(){setState("loading");setMessage("Loading your Hanami classes…");try{const select="relationship,class_sections(id,section_code,term,room,academic_courses(code,title,department,credits),section_meetings(id,weekday,starts_at,ends_at,label))";const [response,prefResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}`,{headers:authHeaders(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?select=class_banner_colors&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:authHeaders(accessToken)})]);if(!response.ok)throw new Error("Your classes could not be loaded.");const rows=await response.json() as Membership[];const pref=prefResponse.ok?(await prefResponse.json() as CharacterPreference[])[0]:null;const expected=role==="student"?"student":"instructor";const sectionIds=rows.filter(row=>row.relationship===expected).map(row=>row.class_sections?.id).filter((id):id is string=>Boolean(id));let teacherRows:InstructorRow[]=[];if(sectionIds.length){const filter=`(${sectionIds.join(",")})`;const teacherResponse=await fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id,characters(display_name,handle)&relationship=eq.instructor&section_id=in.${encodeURIComponent(filter)}`,{headers:authHeaders(accessToken)});if(teacherResponse.ok)teacherRows=await teacherResponse.json() as InstructorRow[];}if(cancelled)return;setMemberships(rows);setInstructors(teacherRows);setBannerColors(pref?.class_banner_colors??{});setState("ready");const count=rows.filter(row=>row.relationship===expected).length;setMessage(count?`${count} course${count===1?"":"s"} available.`:`No ${role==="student"?"courses":"teaching sections"} have been assigned yet.`);}catch(error){if(cancelled)return;setMemberships([]);setInstructors([]);setBannerColors({});setState("error");setMessage(error instanceof Error?error.message:"Your classes could not be loaded.");}}void load();function refresh(event:Event){const target=(event as CustomEvent<{characterId?:string}>).detail?.characterId;if(!target||target===characterId)void load();}window.addEventListener("hanami-character-identity-changed",refresh);return()=>{cancelled=true;window.removeEventListener("hanami-character-identity-changed",refresh);};},[accessToken,characterId,role]);
 const expectedRelationship=role==="student"?"student":"instructor";const roleMemberships=memberships.filter(item=>item.relationship===expectedRelationship);const meetings=useMemo(()=>roleMemberships.flatMap(item=>item.class_sections?.section_meetings??[]),[roleMemberships]);
 function teacherLabel(sectionId:string){const rows=instructors.filter(row=>row.section_id===sectionId&&row.characters);return rows.length?rows.map(row=>row.characters!.display_name).join(", "):"Faculty pending";}
 function scheduleLabel(section:Section){if(!section.section_meetings.length)return "Schedule not posted";return section.section_meetings.slice().sort((a,b)=>a.weekday-b.weekday||a.starts_at.localeCompare(b.starts_at)).map(item=>`${DAY_SHORT[item.weekday]} ${timeLabel(item.starts_at)}`).join(" • ");}
 return <section className={styles.panel} aria-labelledby="schedule-title"><div className={styles.heading}><div><p className="eyebrow">COURSES</p><h4 id="schedule-title">{role==="student"?"All courses":"Teaching courses"}</h4></div><span>{roleMemberships.length} {role==="student"?"ENROLLED":"ASSIGNED"}</span></div><div className={`${styles.status} ${state==="error"?styles.error:""}`} aria-live="polite">{message}</div>{state==="ready"&&roleMemberships.length===0?<div className={styles.empty}><strong>No {role==="student"?"courses":"teaching sections"} yet</strong><p>When Administration assigns this character to a section, its course card will appear here.</p></div>:null}{roleMemberships.length>0&&<div className={styles.classroomGrid}>{roleMemberships.map((membership,index)=>{const section=membership.class_sections;if(!section)return null;const course=section.academic_courses;const custom=bannerColors[section.id];const customStyle=validHex(custom)?{background:`linear-gradient(120deg,${custom},color-mix(in srgb, ${custom} 68%, #111))`}:undefined;const card=<><div className={`${styles.classBanner} ${customStyle?"":styles[`banner${index%6}`]}`} style={customStyle}><span className={styles.code}>{course?.code??"COURSE"} • SECTION {section.section_code}</span><h5>{course?.title??"Untitled course"}</h5><p>{section.term}</p><small>{teacherLabel(section.id)}</small></div><div className={styles.classBody}><div className={styles.classInfo}><span>{section.room?`Room ${section.room}`:"Room TBA"}</span><span>{scheduleLabel(section)}</span></div><div className={styles.cardSpacer}/><div className={styles.cardActions}>{role==="student"?<><span>Assignments</span><span>Grades</span><strong>Open course →</strong></>:<><span>Assignments</span><span>People</span><strong>Manage course →</strong></>}</div></div></>;return <article key={section.id} className={styles.classCard}>{role==="student"?<a className={styles.classLink} href={`./class/?section=${encodeURIComponent(section.id)}`} aria-label={`Open ${course?.title??"course"}`}>{card}</a>:card}</article>;})}</div>}{meetings.length>0&&<div className={styles.weekStrip}><strong>COURSE SCHEDULE</strong><span>{meetings.length} scheduled meeting{meetings.length===1?"":"s"} across these courses</span></div>}</section>;
}
