"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./SchoolLifeEventsPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string;characterId:string};
type Tab="broadcast"|"newspaper"|"recruitment"|"festival"|"sports"|"elections"|"events"|"passport"|"homeroom";
type Broadcast={id:string;title:string;body:string;broadcast_type:string;status:string;scheduled_for:string|null;audio_url:string|null};
type NewspaperApp={id:string;writing_sample:string;interests:string[];availability:string;why_join:string;status:string;reviewer_note:string|null;created_at:string};
type Article={id:string;section:string;headline:string;dek:string|null;status:string;published_at:string|null};
type Recruitment={id:string;activity_id:string;title:string;banner_url:string|null;booth_location:string|null;application_prompt:string|null;starts_at:string|null;ends_at:string|null;is_open:boolean};
type Activity={id:string;name:string;kind:string};
type FestivalPlan={id:string;owner_type:string;owner_id:string;title:string;description:string|null;booth_location:string|null;attraction_type:string|null;starts_at:string|null;ends_at:string|null;status:string};
type Team={id:string;name:string;sport:string;season:string|null;description:string|null};
type Fixture={id:string;team_id:string;opponent:string;starts_at:string;location:string|null;home_away:string;status:string;hanami_score:number|null;opponent_score:number|null;result_note:string|null};
type Election={id:string;title:string;description:string|null;status:string;nominations_open_at:string|null;nominations_close_at:string|null;voting_open_at:string|null;voting_close_at:string|null};
type Position={id:string;election_id:string;title:string;description:string|null;eligibility_note:string|null};
type CandidateApp={id:string;position_id:string;campaign_slogan:string|null;platform:string;requirements_acknowledged:boolean;status:string;reviewer_note:string|null};
type Nomination={id:string;position_id:string;candidate_character_id:string;statement:string;status:string};
type Character={id:string;display_name:string;handle:string};
type Event={id:string;title:string;description:string|null;location:string|null;starts_at:string;ends_at:string|null;category:string;status:string;registration_open:boolean};
type RSVP={id:string;event_id:string;response:string;note:string|null};
type Volunteer={id:string;event_id:string;role_label:string|null;status:string;note:string|null};
type Passport={id:string;festival_key:string;created_at:string};
type Stamp={id:string;passport_id:string;stamp_key:string;label:string;awarded_at:string};
type ClubBadge={id:string;label:string;description:string|null;icon:string|null};
type EarnedBadge={id:string;badge_id:string;awarded_at:string;note:string|null};
type HomeroomMembership={homeroom_id:string;student_year:number};
type Homeroom={id:string;code:string;room_label:string|null};
type HomeroomNotice={id:string;homeroom_id:string;title:string;body:string;published_at:string|null};
type Competition={id:string;title:string;competition_type:string;status:string;description:string|null};
type CompetitionPoint={id:string;competition_id:string;homeroom_id:string;points:number;reason:string|null};

function h(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function get<T>(token:string,path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:h(token)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}
async function mutate(token:string,path:string,method:string,body:unknown,prefer="return=minimal"){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method,headers:h(token,{"Content-Type":"application/json",Prefer:prefer}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r;}
function nice(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function when(value:string|null){return value?new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)):"TBA";}

export default function SchoolLifeEventsPanel({accessToken,characterId}:Props){
 const [tab,setTab]=useState<Tab>("broadcast"),[message,setMessage]=useState("Loading school-life systems…");
 const [broadcasts,setBroadcasts]=useState<Broadcast[]>([]),[apps,setApps]=useState<NewspaperApp[]>([]),[articles,setArticles]=useState<Article[]>([]),[recruitment,setRecruitment]=useState<Recruitment[]>([]),[activities,setActivities]=useState<Activity[]>([]),[festivalPlans,setFestivalPlans]=useState<FestivalPlan[]>([]),[teams,setTeams]=useState<Team[]>([]),[fixtures,setFixtures]=useState<Fixture[]>([]),[elections,setElections]=useState<Election[]>([]),[positions,setPositions]=useState<Position[]>([]),[candidateApps,setCandidateApps]=useState<CandidateApp[]>([]),[nominations,setNominations]=useState<Nomination[]>([]),[characters,setCharacters]=useState<Character[]>([]),[events,setEvents]=useState<Event[]>([]),[rsvps,setRsvps]=useState<RSVP[]>([]),[volunteers,setVolunteers]=useState<Volunteer[]>([]),[passports,setPassports]=useState<Passport[]>([]),[stamps,setStamps]=useState<Stamp[]>([]),[clubBadges,setClubBadges]=useState<ClubBadge[]>([]),[earnedBadges,setEarnedBadges]=useState<EarnedBadge[]>([]),[homeMembership,setHomeMembership]=useState<HomeroomMembership|null>(null),[homerooms,setHomerooms]=useState<Homeroom[]>([]),[notices,setNotices]=useState<HomeroomNotice[]>([]),[competitions,setCompetitions]=useState<Competition[]>([]),[points,setPoints]=useState<CompetitionPoint[]>([]);
 const [newspaperDraft,setNewspaperDraft]=useState({writing_sample:"",interests:"School News,Clubs",availability:"After school",why_join:""});
 const [candidateDraft,setCandidateDraft]=useState({position_id:"",campaign_slogan:"",platform:"",requirements:false});
 const activityMap=useMemo(()=>new Map(activities.map(x=>[x.id,x.name])),[activities]);const charMap=useMemo(()=>new Map(characters.map(x=>[x.id,x])),[characters]);const home=homeMembership?homerooms.find(x=>x.id===homeMembership.homeroom_id):null;

 async function load(){try{setMessage("Refreshing school-life systems…");const [b,a,articlesRows,r,acts,fPlans,t,fx,e,p,cApps,n,chars,ev,rv,v,pp,ss,cb,eb,hm,hrs,hn,cc,cp]=await Promise.all([
  get<Broadcast[]>(accessToken,"broadcast_posts?select=id,title,body,broadcast_type,status,scheduled_for,audio_url&status=in.(published,scheduled)&order=scheduled_for.desc.nullslast,created_at.desc&limit=20"),
  get<NewspaperApp[]>(accessToken,`newspaper_applications?select=id,writing_sample,interests,availability,why_join,status,reviewer_note,created_at&character_id=eq.${characterId}&order=created_at.desc`),
  get<Article[]>(accessToken,"newspaper_articles?select=id,section,headline,dek,status,published_at&status=eq.published&order=published_at.desc&limit=20"),
  get<Recruitment[]>(accessToken,"club_recruitment_campaigns?select=id,activity_id,title,banner_url,booth_location,application_prompt,starts_at,ends_at,is_open&order=starts_at.desc.nullslast"),
  get<Activity[]>(accessToken,"campus_activities?select=id,name,kind&is_active=eq.true&order=name.asc"),
  get<FestivalPlan[]>(accessToken,"festival_plans?select=id,owner_type,owner_id,title,description,booth_location,attraction_type,starts_at,ends_at,status&status=in.(approved,published,open)&order=starts_at.asc.nullslast"),
  get<Team[]>(accessToken,"sports_teams?select=id,name,sport,season,description&is_active=eq.true&order=sport.asc,name.asc"),
  get<Fixture[]>(accessToken,"sports_fixtures?select=id,team_id,opponent,starts_at,location,home_away,status,hanami_score,opponent_score,result_note&order=starts_at.desc&limit=50"),
  get<Election[]>(accessToken,"school_elections?select=id,title,description,status,nominations_open_at,nominations_close_at,voting_open_at,voting_close_at&order=created_at.desc"),
  get<Position[]>(accessToken,"election_positions?select=id,election_id,title,description,eligibility_note&order=sort_order.asc"),
  get<CandidateApp[]>(accessToken,`election_candidate_applications?select=id,position_id,campaign_slogan,platform,requirements_acknowledged,status,reviewer_note&candidate_character_id=eq.${characterId}&order=created_at.desc`),
  get<Nomination[]>(accessToken,"election_nominations?select=id,position_id,candidate_character_id,statement,status&status=eq.approved&order=created_at.asc"),
  get<Character[]>(accessToken,"characters?select=id,display_name,handle&role=eq.student"),
  get<Event[]>(accessToken,"school_calendar_events?select=id,title,description,location,starts_at,ends_at,category,status,registration_open&status=eq.published&order=starts_at.asc&limit=40"),
  get<RSVP[]>(accessToken,`event_rsvps?select=id,event_id,response,note&character_id=eq.${characterId}`),
  get<Volunteer[]>(accessToken,`event_volunteer_signups?select=id,event_id,role_label,status,note&character_id=eq.${characterId}`),
  get<Passport[]>(accessToken,`festival_passports?select=id,festival_key,created_at&character_id=eq.${characterId}&order=created_at.desc`),
  get<Stamp[]>(accessToken,"festival_stamps?select=id,passport_id,stamp_key,label,awarded_at&order=awarded_at.desc"),
  get<ClubBadge[]>(accessToken,"club_achievement_badges?select=id,label,description,icon&active=eq.true&order=label.asc"),
  get<EarnedBadge[]>(accessToken,`character_club_badges?select=id,badge_id,awarded_at,note&character_id=eq.${characterId}&order=awarded_at.desc`),
  get<HomeroomMembership[]>(accessToken,`homeroom_memberships?select=homeroom_id,student_year&student_character_id=eq.${characterId}&limit=1`),
  get<Homeroom[]>(accessToken,"homerooms?select=id,code,room_label&is_active=eq.true"),
  get<HomeroomNotice[]>(accessToken,"homeroom_notices?select=id,homeroom_id,title,body,published_at&order=published_at.desc.nullslast&limit=30"),
  get<Competition[]>(accessToken,"class_competitions?select=id,title,competition_type,status,description&status=in.(active,open,published,completed)&order=created_at.desc"),
  get<CompetitionPoint[]>(accessToken,"class_competition_points?select=id,competition_id,homeroom_id,points,reason&order=created_at.desc")
 ]);setBroadcasts(b);setApps(a);setArticles(articlesRows);setRecruitment(r);setActivities(acts);setFestivalPlans(fPlans);setTeams(t);setFixtures(fx);setElections(e);setPositions(p);setCandidateApps(cApps);setNominations(n);setCharacters(chars);setEvents(ev);setRsvps(rv);setVolunteers(v);setPassports(pp);setStamps(ss);setClubBadges(cb);setEarnedBadges(eb);setHomeMembership(hm[0]??null);setHomerooms(hrs);setNotices(hn);setCompetitions(cc);setPoints(cp);setMessage("School-life & events batch is ready.");}catch(error){setMessage(error instanceof Error?error.message:"School-life data could not be loaded.");}}
 useEffect(()=>{void load();},[accessToken,characterId]);

 async function submitNewspaper(e:FormEvent){e.preventDefault();if(newspaperDraft.writing_sample.trim().length<80||!newspaperDraft.why_join.trim())return setMessage("Add a writing sample of at least 80 characters and explain why you want to join.");try{await mutate(accessToken,"newspaper_applications","POST",{character_id:characterId,writing_sample:newspaperDraft.writing_sample.trim(),interests:newspaperDraft.interests.split(",").map(x=>x.trim()).filter(Boolean),availability:newspaperDraft.availability.trim(),why_join:newspaperDraft.why_join.trim(),status:"pending"});setNewspaperDraft({writing_sample:"",interests:"School News,Clubs",availability:"After school",why_join:""});await load();setMessage("Newspaper application sent to Administration and the Owner.");}catch(error){setMessage(error instanceof Error?error.message:"Application could not be sent.");}}
 async function submitCandidate(e:FormEvent){e.preventDefault();if(!candidateDraft.position_id||!candidateDraft.platform.trim()||!candidateDraft.requirements)return setMessage("Choose a position, write your platform, and acknowledge the candidacy requirements.");try{await mutate(accessToken,"election_candidate_applications","POST",{position_id:candidateDraft.position_id,candidate_character_id:characterId,campaign_slogan:candidateDraft.campaign_slogan||null,platform:candidateDraft.platform.trim(),requirements_acknowledged:true,application_answers:{conduct_acknowledged:true,school_rules_acknowledged:true},status:"pending"});setCandidateDraft({position_id:"",campaign_slogan:"",platform:"",requirements:false});await load();setMessage("Student Council candidacy application sent to Administration and the Owner.");}catch(error){setMessage(error instanceof Error?error.message:"Candidacy application could not be sent.");}}
 async function rsvp(eventId:string,response:string){try{const existing=rsvps.find(x=>x.event_id===eventId);if(existing)await mutate(accessToken,`event_rsvps?id=eq.${existing.id}`,"PATCH",{response,updated_at:new Date().toISOString()});else await mutate(accessToken,"event_rsvps","POST",{event_id:eventId,character_id:characterId,response});await load();}catch(error){setMessage(error instanceof Error?error.message:"RSVP could not be saved.");}}
 async function volunteer(eventId:string){try{const existing=volunteers.find(x=>x.event_id===eventId);if(existing)return setMessage(`Volunteer signup already ${existing.status}.`);await mutate(accessToken,"event_volunteer_signups","POST",{event_id:eventId,character_id:characterId,role_label:"General volunteer",status:"pending"});await load();setMessage("Volunteer signup sent.");}catch(error){setMessage(error instanceof Error?error.message:"Volunteer signup could not be sent.");}}
 async function applyClub(campaign:Recruitment){try{const prompt=campaign.application_prompt||`I would like to join ${activityMap.get(campaign.activity_id)??"this club"}.`;await mutate(accessToken,"organization_applications","POST",{activity_id:campaign.activity_id,student_character_id:characterId,statement:prompt,status:"pending"});setMessage("Club application sent.");}catch(error){setMessage(error instanceof Error?error.message:"Club application could not be sent.");}}
 const activeElection=elections.find(x=>["nominations","voting","open","active"].includes(x.status))??elections[0];const electionPositions=activeElection?positions.filter(x=>x.election_id===activeElection.id):[];const homeNotices=home?notices.filter(x=>x.homeroom_id===home.id):[];const competitionTotals=useMemo(()=>competitions.map(c=>({competition:c,rows:Array.from(new Set(points.filter(p=>p.competition_id===c.id).map(p=>p.homeroom_id))).map(homeroom_id=>({homeroom_id,total:points.filter(p=>p.competition_id===c.id&&p.homeroom_id===homeroom_id).reduce((s,p)=>s+p.points,0)})).sort((a,b)=>b.total-a.total)})),[competitions,points]);
 const tabs:[Tab,string][]=[["broadcast","PA / Broadcast"],["newspaper","Newspaper"],["recruitment","Club Recruitment"],["festival","Cultural Festival"],["sports","Sports"],["elections","Student Council"],["events","Events & Volunteer"],["passport","Festival Passport"],["homeroom","Homeroom"]];
 return <section className={styles.panel}><header className={styles.header}><div><p className="eyebrow">SCHOOL LIFE & EVENTS</p><h3>Hanami campus systems</h3><p>Broadcasts, clubs, festivals, sports, elections, volunteering, and homeroom life.</p></div><span>{message}</span></header><nav className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="broadcast"&&<div className={styles.stack}>{broadcasts.map(b=><article className={`${styles.card} ${styles.broadcast}`} key={b.id}><div className={styles.row}><strong>HANAMI PA • {nice(b.broadcast_type)}</strong><span>{when(b.scheduled_for)}</span></div><h4>{b.title}</h4><p>{b.body}</p>{b.audio_url&&<audio controls preload="none" src={b.audio_url}/>}</article>)}{!broadcasts.length&&<div className={styles.card}>No current PA broadcasts.</div>}</div>}
 {tab==="newspaper"&&<div className={styles.split}><form className={styles.card} onSubmit={submitNewspaper}><h4>Apply to The Hanami Chronicle</h4><p>Student writers must be approved by Administration or the Owner before newsroom access is granted.</p><label>Writing sample<textarea rows={8} value={newspaperDraft.writing_sample} onChange={e=>setNewspaperDraft({...newspaperDraft,writing_sample:e.target.value})}/></label><label>Sections you are interested in<input value={newspaperDraft.interests} onChange={e=>setNewspaperDraft({...newspaperDraft,interests:e.target.value})}/></label><label>Availability<input value={newspaperDraft.availability} onChange={e=>setNewspaperDraft({...newspaperDraft,availability:e.target.value})}/></label><label>Why do you want to join?<textarea rows={4} value={newspaperDraft.why_join} onChange={e=>setNewspaperDraft({...newspaperDraft,why_join:e.target.value})}/></label><button>Submit application</button>{apps.map(a=><p className={styles.status} key={a.id}>Application: <b>{nice(a.status)}</b>{a.reviewer_note?` • ${a.reviewer_note}`:""}</p>)}</form><div className={styles.stack}>{articles.map(a=><article className={styles.card} key={a.id}><small>{a.section.toUpperCase()}</small><h4>{a.headline}</h4>{a.dek&&<p>{a.dek}</p>}<span>{when(a.published_at)}</span></article>)}</div></div>}
 {tab==="recruitment"&&<div className={styles.grid}>{recruitment.map(r=><article className={styles.card} key={r.id}>{r.banner_url&&<img className={styles.banner} src={r.banner_url} alt=""/>}<small>{activityMap.get(r.activity_id)??"Hanami Club"}</small><h4>{r.title}</h4><p>{r.application_prompt||"Recruitment is open."}</p><div className={styles.meta}><span>Booth: {r.booth_location||"TBA"}</span><span>{when(r.starts_at)}–{when(r.ends_at)}</span></div><button disabled={!r.is_open} onClick={()=>applyClub(r)}>{r.is_open?"Apply to club":"Applications closed"}</button></article>)}{!recruitment.length&&<div className={styles.card}>Club recruitment campaigns will appear here during recruitment week.</div>}</div>}
 {tab==="festival"&&<div className={styles.grid}>{festivalPlans.map(f=><article className={styles.card} key={f.id}><small>{nice(f.owner_type)} • {nice(f.status)}</small><h4>{f.title}</h4>{f.description&&<p>{f.description}</p>}<div className={styles.meta}><span>{nice(f.attraction_type||"Attraction")}</span><span>{f.booth_location||"Location TBA"}</span><span>{when(f.starts_at)}–{when(f.ends_at)}</span></div></article>)}{!festivalPlans.length&&<div className={styles.card}>Approved Cultural Festival booths and attractions will appear here.</div>}</div>}
 {tab==="sports"&&<div className={styles.stack}>{teams.map(team=><article className={styles.card} key={team.id}><div className={styles.row}><div><small>{team.sport.toUpperCase()} • {team.season||"Season"}</small><h4>{team.name}</h4></div><span>{fixtures.filter(f=>f.team_id===team.id&&f.status==="completed"&&Number(f.hanami_score)>Number(f.opponent_score)).length} WINS</span></div>{team.description&&<p>{team.description}</p>}<div className={styles.fixtureList}>{fixtures.filter(f=>f.team_id===team.id).slice(0,8).map(f=><div key={f.id}><span>{when(f.starts_at)}</span><strong>Hanami vs. {f.opponent}</strong><span>{f.status==="completed"?`${f.hanami_score??0}–${f.opponent_score??0}`:nice(f.status)}</span></div>)}</div></article>)}</div>}
 {tab==="elections"&&<div className={styles.split}><form className={styles.card} onSubmit={submitCandidate}><h4>Student Council candidacy application</h4><p>Candidates must apply first. Administration/Owner approval is required before a nomination/campaign becomes public.</p><select value={candidateDraft.position_id} onChange={e=>setCandidateDraft({...candidateDraft,position_id:e.target.value})}><option value="">Choose a position…</option>{electionPositions.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select>{candidateDraft.position_id&&<p>{positions.find(p=>p.id===candidateDraft.position_id)?.eligibility_note||"Candidate must be in good standing and follow election rules."}</p>}<input placeholder="Campaign slogan" value={candidateDraft.campaign_slogan} onChange={e=>setCandidateDraft({...candidateDraft,campaign_slogan:e.target.value})}/><textarea rows={7} placeholder="Explain your platform and what you would do in office…" value={candidateDraft.platform} onChange={e=>setCandidateDraft({...candidateDraft,platform:e.target.value})}/><label className={styles.check}><input type="checkbox" checked={candidateDraft.requirements} onChange={e=>setCandidateDraft({...candidateDraft,requirements:e.target.checked})}/> I meet the position requirements and agree to Hanami election rules.</label><button>Submit candidacy application</button>{candidateApps.map(a=><p className={styles.status} key={a.id}>Candidacy: <b>{nice(a.status)}</b>{a.reviewer_note?` • ${a.reviewer_note}`:""}</p>)}</form><article className={styles.card}><h4>{activeElection?.title??"Student Council Elections"}</h4><p>{activeElection?.description||"Approved candidates and campaign pages will appear here."}</p>{electionPositions.map(p=><section className={styles.position} key={p.id}><strong>{p.title}</strong><small>{p.eligibility_note}</small>{nominations.filter(n=>n.position_id===p.id).map(n=><div key={n.id}><b>{charMap.get(n.candidate_character_id)?.display_name??"Candidate"}</b><p>{n.statement}</p></div>)}</section>)}</article></div>}
 {tab==="events"&&<div className={styles.grid}>{events.map(ev=>{const saved=rsvps.find(x=>x.event_id===ev.id);const vol=volunteers.find(x=>x.event_id===ev.id);return <article className={styles.card} key={ev.id}><small>{nice(ev.category)} • {when(ev.starts_at)}</small><h4>{ev.title}</h4>{ev.description&&<p>{ev.description}</p>}<p>{ev.location||"Location TBA"}</p><div className={styles.actions}><button className={saved?.response==="going"?styles.selected:""} onClick={()=>rsvp(ev.id,"going")}>Going</button><button className={saved?.response==="interested"?styles.selected:""} onClick={()=>rsvp(ev.id,"interested")}>Interested</button><button className={saved?.response==="not_going"?styles.selected:""} onClick={()=>rsvp(ev.id,"not_going")}>Not going</button><button onClick={()=>volunteer(ev.id)}>{vol?`Volunteer: ${nice(vol.status)}`:"Volunteer"}</button></div></article>})}</div>}
 {tab==="passport"&&<div className={styles.split}><div className={styles.stack}>{passports.map(p=><article className={styles.passport} key={p.id}><div><small>HANAMI FESTIVAL PASSPORT</small><h4>{nice(p.festival_key)}</h4></div><div className={styles.stamps}>{stamps.filter(s=>s.passport_id===p.id).map(s=><span key={s.id} title={when(s.awarded_at)}>★<small>{s.label}</small></span>)}</div></article>)}{!passports.length&&<div className={styles.card}>Festival passports are issued when a passport-enabled school festival begins.</div>}</div><article className={styles.card}><h4>Club achievements</h4><div className={styles.badges}>{earnedBadges.map(e=>{const badge=clubBadges.find(b=>b.id===e.badge_id);return <span key={e.id}>{badge?.icon||"✦"}<b>{badge?.label||"Club Achievement"}</b><small>{e.note||when(e.awarded_at)}</small></span>})}{!earnedBadges.length&&<p>No club achievement badges yet.</p>}</div></article></div>}
 {tab==="homeroom"&&<div className={styles.split}><div className={styles.stack}><article className={styles.card}><small>YOUR HOMEROOM</small><h4>{home?.code??"Not assigned"}</h4><p>{home?.room_label?`Room ${home.room_label}`:"Your homeroom bulletin will appear after assignment."}</p></article>{homeNotices.map(n=><article className={styles.card} key={n.id}><small>CLASSROOM BULLETIN • {when(n.published_at)}</small><h4>{n.title}</h4><p>{n.body}</p></article>)}</div><div className={styles.stack}>{competitionTotals.map(({competition,rows})=><article className={styles.card} key={competition.id}><small>{nice(competition.competition_type)} • {nice(competition.status)}</small><h4>{competition.title}</h4>{competition.description&&<p>{competition.description}</p>}<ol className={styles.ranking}>{rows.map(row=><li key={row.homeroom_id} className={home?.id===row.homeroom_id?styles.homeRank:""}><span>{homerooms.find(h=>h.id===row.homeroom_id)?.code??"Homeroom"}</span><b>{row.total} pts</b></li>)}</ol></article>)}</div></div>}
 </section>;
}
