"use client";

import {ChangeEvent,FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Tab="forms"|"documents"|"handbook"|"traditions"|"it"|"appeals"|"feedback";
type SchoolForm={id:string;title:string;description:string;category:string;fields:Array<{key:string;label:string;type:string;required?:boolean}>};
type DocumentRow={id:string;title:string;category:string;description:string;storage_path:string;rp_year:number|null};
type Handbook={id:string;slug:string;category:string;title:string;body:string;policy_version:string;acknowledgement_required:boolean};
type Tradition={id:string;title:string;event_type:string;rp_year:number;season:string|null;description:string;traditions:string[];highlights:string[]};
type Submission={id:string;status:string;created_at:string};
export default function SchoolResourcesPanel({accessToken,characterId}:{accessToken:string;characterId:string}){
 const [tab,setTab]=useState<Tab>("forms");const [notice,setNotice]=useState("Loading School Resources…");const [forms,setForms]=useState<SchoolForm[]>([]);const [docs,setDocs]=useState<DocumentRow[]>([]);const [handbook,setHandbook]=useState<Handbook[]>([]);const [traditions,setTraditions]=useState<Tradition[]>([]);const [acks,setAcks]=useState<Array<{section_id:string;policy_version:string}>>([]);const [selectedForm,setSelectedForm]=useState("");const [formValues,setFormValues]=useState<Record<string,string>>({});const [submissions,setSubmissions]=useState<Submission[]>([]);const [search,setSearch]=useState("");const [itCategory,setItCategory]=useState("site_bug");const [itSubject,setItSubject]=useState("");const [itDescription,setItDescription]=useState("");const [itPriority,setItPriority]=useState("normal");const [appealType,setAppealType]=useState("other");const [appealReference,setAppealReference]=useState("");const [appealReason,setAppealReason]=useState("");const [feedbackCategory,setFeedbackCategory]=useState("bug");const [feedbackPage,setFeedbackPage]=useState("");const [feedbackSeverity,setFeedbackSeverity]=useState("medium");const [feedbackDescription,setFeedbackDescription]=useState("");const [feedbackScreenshot,setFeedbackScreenshot]=useState<File|null>(null);
 const load=useCallback(async()=>{const req=(p:string)=>fetch(`${SUPABASE_URL}/rest/v1/${p}`,{headers:headers(accessToken)});const [f,d,h,t,a,s]=await Promise.all([req("school_forms?select=id,title,description,category,fields&is_active=eq.true&order=title.asc"),req("school_documents?select=id,title,category,description,storage_path,rp_year&status=eq.published&order=category.asc,title.asc"),req("handbook_sections?select=id,slug,category,title,body,policy_version,acknowledgement_required&status=eq.published&order=sort_order.asc"),req("school_traditions?select=id,title,event_type,rp_year,season,description,traditions,highlights&status=eq.published&order=rp_year.desc,title.asc"),req("policy_acknowledgements?select=section_id,policy_version"),req("school_form_submissions?select=id,status,created_at&order=created_at.desc&limit=20")]);if(f.ok){const rows=await f.json();setForms(rows);if(!selectedForm&&rows[0])setSelectedForm(rows[0].id);}if(d.ok)setDocs(await d.json());if(h.ok)setHandbook(await h.json());if(t.ok)setTraditions(await t.json());if(a.ok)setAcks(await a.json());if(s.ok)setSubmissions(await s.json());setNotice("School Resources are live.");},[accessToken,selectedForm]);
 useEffect(()=>{load().catch(()=>setNotice("School Resources could not be loaded."));},[load]);
 const activeForm=forms.find(f=>f.id===selectedForm);const filteredHandbook=useMemo(()=>handbook.filter(x=>`${x.title} ${x.category} ${x.body}`.toLowerCase().includes(search.toLowerCase())),[handbook,search]);
 async function submitForm(e:FormEvent){e.preventDefault();if(!activeForm)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/school_form_submissions`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({form_id:activeForm.id,submitted_by_character_id:characterId,response_data:formValues})});if(r.ok){setFormValues({});setNotice("School form submitted.");await load();}else setNotice("School form could not be submitted.");}
 async function downloadDocument(doc:DocumentRow){const r=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/document-center/${encodeURI(doc.storage_path)}`,{headers:headers(accessToken)});if(!r.ok){setNotice("Document could not be opened.");return;}const url=URL.createObjectURL(await r.blob());window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);}
 async function acknowledge(section:Handbook){const r=await fetch(`${SUPABASE_URL}/rest/v1/policy_acknowledgements`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:section.id,character_id:characterId,policy_version:section.policy_version})});if(r.ok){setAcks(v=>[...v,{section_id:section.id,policy_version:section.policy_version}]);setNotice("Policy acknowledgement recorded.");}else setNotice("Policy acknowledgement could not be recorded (it may already be acknowledged).");}
 async function submitIT(e:FormEvent){e.preventDefault();const r=await fetch(`${SUPABASE_URL}/rest/v1/it_help_tickets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requester_character_id:characterId,category:itCategory,subject:itSubject.trim(),description:itDescription.trim(),priority:itPriority})});if(r.ok){setItSubject("");setItDescription("");setNotice("IT Help Desk ticket submitted.");}else setNotice("IT Help Desk ticket could not be submitted.");}
 async function submitAppeal(e:FormEvent){e.preventDefault();const r=await fetch(`${SUPABASE_URL}/rest/v1/moderation_appeals`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({appellant_character_id:characterId,action_type:appealType,action_reference:appealReference.trim()||null,reason:appealReason.trim()})});if(r.ok){setAppealReference("");setAppealReason("");setNotice("Appeal submitted for staff review.");}else setNotice("Appeal could not be submitted.");}
 async function chooseScreenshot(e:ChangeEvent<HTMLInputElement>){setFeedbackScreenshot(e.target.files?.[0]??null);}
 async function submitFeedback(e:FormEvent){e.preventDefault();let path:string|null=null;if(feedbackScreenshot){if(!["image/jpeg","image/png","image/gif","image/webp"].includes(feedbackScreenshot.type)||feedbackScreenshot.size>8*1024*1024){setNotice("Screenshots must be JPEG/PNG/GIF/WebP and 8 MB or smaller.");return;}const ext=feedbackScreenshot.type==="image/jpeg"?"jpg":feedbackScreenshot.type.split("/")[1];path=`${characterId}/${crypto.randomUUID()}.${ext}`;const up=await fetch(`${SUPABASE_URL}/storage/v1/object/bug-feedback-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":feedbackScreenshot.type}),body:feedbackScreenshot});if(!up.ok){setNotice("Screenshot could not be uploaded.");return;}}const r=await fetch(`${SUPABASE_URL}/rest/v1/bug_feedback_reports`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({reporter_character_id:characterId,page_path:feedbackPage.trim()||location.pathname,category:feedbackCategory,description:feedbackDescription.trim(),severity:feedbackSeverity,screenshot_storage_path:path})});if(r.ok){setFeedbackDescription("");setFeedbackScreenshot(null);setNotice("Bug/feedback report submitted.");}else setNotice("Bug/feedback report could not be submitted.");}
 const tabs:Tab[]=["forms","documents","handbook","traditions","it","appeals","feedback"];
 return <section style={{marginTop:16,border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:"12px 14px",background:"#eef3f8",borderBottom:"1px solid #c5ced8"}}><p className="eyebrow">SCHOOL INFORMATION HUB</p><h4 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>School Resources</h4><small>{notice}</small></div><nav style={{display:"flex",gap:5,flexWrap:"wrap",padding:10,background:"#f8f1f5"}}>{tabs.map(x=><button key={x} type="button" onClick={()=>setTab(x)}>{x==="it"?"IT Help Desk":x==="feedback"?"Bug / Feedback":x}</button>)}</nav>
 {tab==="forms"&&<div style={{padding:14,display:"grid",gap:12}}><div><label>Form <select value={selectedForm} onChange={e=>{setSelectedForm(e.target.value);setFormValues({});}}>{forms.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select></label></div>{activeForm&&<form onSubmit={submitForm} style={{display:"grid",gap:7}}><strong>{activeForm.title}</strong><p>{activeForm.description}</p>{activeForm.fields.map(field=><label key={field.key}>{field.label}{field.type==="textarea"?<textarea required={field.required} value={formValues[field.key]??""} onChange={e=>setFormValues(v=>({...v,[field.key]:e.target.value}))}/>:<input required={field.required} value={formValues[field.key]??""} onChange={e=>setFormValues(v=>({...v,[field.key]:e.target.value}))}/>}</label>)}<button>Submit form</button></form>}<div><h5>Recent submissions</h5>{submissions.map(s=><div key={s.id}>{new Date(s.created_at).toLocaleDateString()} • {s.status}</div>)}</div></div>}
 {tab==="documents"&&<div style={{padding:14,display:"grid",gap:7}}>{docs.length?docs.map(d=><article key={d.id} style={{padding:10,border:"1px solid #d1d8df"}}><strong>{d.title}</strong><div>{d.category.replaceAll("_"," ")}{d.rp_year?` • ${d.rp_year}`:""}</div><p>{d.description}</p><button type="button" onClick={()=>downloadDocument(d)}>Open document</button></article>):<p>No published documents yet.</p>}</div>}
 {tab==="handbook"&&<div style={{padding:14}}><input style={{width:"100%",marginBottom:10}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search rules, uniforms, attendance, conduct, grading, technology, clubs…"/>{filteredHandbook.map(h=><article key={h.id} style={{padding:"10px 0",borderBottom:"1px dotted #bdc7d2"}}><small>{h.category.replaceAll("_"," ").toUpperCase()} • VERSION {h.policy_version}</small><h5>{h.title}</h5><p style={{whiteSpace:"pre-wrap"}}>{h.body}</p>{h.acknowledgement_required&&(()=>{const done=acks.some(a=>a.section_id===h.id&&a.policy_version===h.policy_version);return done?<strong>✓ Acknowledged</strong>:<button type="button" onClick={()=>acknowledge(h)}>Mark policy as read</button>;})()}</article>)}</div>}
 {tab==="traditions"&&<div style={{padding:14,display:"grid",gap:10}}>{traditions.map(t=><article key={t.id} style={{padding:12,border:"1px solid #d8b7c5",background:"#fffafc"}}><small>{t.rp_year} • {t.season??"Annual"} • {t.event_type.replaceAll("_"," ")}</small><h4>{t.title}</h4><p>{t.description}</p>{t.traditions.length>0&&<p><strong>Traditions:</strong> {t.traditions.join(" • ")}</p>}{t.highlights.length>0&&<p><strong>Highlights:</strong> {t.highlights.join(" • ")}</p>}</article>)}</div>}
 {tab==="it"&&<form onSubmit={submitIT} style={{padding:14,display:"grid",gap:7}}><h5>IT Help Desk</h5><select value={itCategory} onChange={e=>setItCategory(e.target.value)}><option value="account">Account</option><option value="password">Password / access</option><option value="device">Device</option><option value="site_bug">Website bug</option><option value="profile_studio">Profile Studio</option><option value="messaging">Messaging</option><option value="accessibility">Accessibility</option><option value="other">Other</option></select><input value={itSubject} onChange={e=>setItSubject(e.target.value)} placeholder="Subject" required/><textarea value={itDescription} onChange={e=>setItDescription(e.target.value)} placeholder="Describe the technical problem" required/><select value={itPriority} onChange={e=>setItPriority(e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><button>Submit IT ticket</button></form>}
 {tab==="appeals"&&<form onSubmit={submitAppeal} style={{padding:14,display:"grid",gap:7}}><h5>Appeal a moderation action</h5><select value={appealType} onChange={e=>setAppealType(e.target.value)}><option value="warning">Warning</option><option value="conduct_case">Conduct case</option><option value="content_removal">Content removal</option><option value="account_suspension">Account suspension</option><option value="organization_action">Organization action</option><option value="other">Other</option></select><input value={appealReference} onChange={e=>setAppealReference(e.target.value)} placeholder="Case/reference ID if available"/><textarea value={appealReason} onChange={e=>setAppealReason(e.target.value)} placeholder="Explain why this action should be reviewed" required minLength={20}/><button>Submit appeal</button></form>}
 {tab==="feedback"&&<form onSubmit={submitFeedback} style={{padding:14,display:"grid",gap:7}}><h5>Bug Report / Feedback Center</h5><select value={feedbackCategory} onChange={e=>setFeedbackCategory(e.target.value)}><option value="bug">Bug</option><option value="feedback">Feedback</option><option value="accessibility">Accessibility</option><option value="performance">Performance</option><option value="content">Content</option><option value="other">Other</option></select><input value={feedbackPage} onChange={e=>setFeedbackPage(e.target.value)} placeholder="Affected page (defaults to current page)"/><select value={feedbackSeverity} onChange={e=>setFeedbackSeverity(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><textarea value={feedbackDescription} onChange={e=>setFeedbackDescription(e.target.value)} placeholder="What happened? What did you expect?" required minLength={10}/><label>Optional screenshot <input type="file" accept="image/jpeg,image/png,image/gif,image/webp" onChange={chooseScreenshot}/></label><button>Submit report</button></form>}
 </section>;
}
