"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./SchoolCalendarPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type EventRow={id:string;title:string;description:string;location:string|null;starts_at:string;ends_at:string|null;all_day:boolean;category:string;featured:boolean;is_test_data:boolean;registration_open:boolean;registration_capacity:number|null};
type Registration={id:string;event_id:string;status:string};
type Props={accessToken:string;characterId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}

export default function SchoolCalendarPanel({accessToken,characterId}:Props){
 const [items,setItems]=useState<EventRow[]>([]);const [registrations,setRegistrations]=useState<Registration[]>([]);const [status,setStatus]=useState("Loading upcoming school events…");
 const load=useCallback(async()=>{try{const now=encodeURIComponent(new Date().toISOString());const [eventsResponse,registrationResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/school_calendar_events?select=id,title,description,location,starts_at,ends_at,all_day,category,featured,is_test_data,registration_open,registration_capacity&starts_at=gte.${now}&order=featured.desc,starts_at.asc&limit=6`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/event_registrations?select=id,event_id,status&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)})]);if(!eventsResponse.ok||!registrationResponse.ok)throw new Error("Upcoming school events could not be loaded.");const rows=await eventsResponse.json() as EventRow[];setItems(rows);setRegistrations(await registrationResponse.json() as Registration[]);setStatus(rows.length?`${rows.length} upcoming school event${rows.length===1?"":"s"}.`:"No upcoming school events have been published.");}catch(error){setStatus(error instanceof Error?error.message:"Upcoming school events could not be loaded.");}},[accessToken,characterId]);
 useEffect(()=>{void load();},[load]);
 async function register(eventId:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/event_registrations`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({event_id:eventId,character_id:characterId})});if(!response.ok){setStatus("Event registration could not be completed or already exists.");return;}const row=(await response.json() as Registration[])[0];if(row)setRegistrations(current=>[...current,row]);setStatus(row?.status==="waitlisted"?"This event is full. You were added to the waitlist.":"RSVP confirmed.");}
 async function cancel(registrationId:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/event_registrations?id=eq.${encodeURIComponent(registrationId)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:"cancelled",updated_at:new Date().toISOString()})});if(response.ok){setRegistrations(current=>current.map(r=>r.id===registrationId?{...r,status:"cancelled"}:r));setStatus("Event RSVP cancelled.");}else setStatus("Event RSVP could not be cancelled.");}
 return <section className={styles.panel} aria-labelledby="school-calendar-title"><div className={styles.heading}><div><p className="eyebrow">HANAMI SCHOOL CALENDAR</p><h4 id="school-calendar-title">Upcoming School Events</h4></div><span>LIVE CALENDAR</span></div><div className={styles.status} aria-live="polite">{status}</div>{items.length>0&&<div className={styles.list}>{items.map(item=>{const start=new Date(item.starts_at);const registration=registrations.find(r=>r.event_id===item.id&&r.status!=="cancelled");return <article key={item.id} className={styles.item}><div className={styles.date}><strong>{new Intl.DateTimeFormat("en-US",{day:"2-digit",timeZone:"Asia/Tokyo"}).format(start)}</strong><span>{new Intl.DateTimeFormat("en-US",{month:"short",timeZone:"Asia/Tokyo"}).format(start).toUpperCase()}</span></div><div><p className="eyebrow">{item.category.toUpperCase()}{item.featured?" • FEATURED":""}{item.is_test_data?" • TEST":""}</p><h5>{item.title}</h5><p>{item.description}</p><small>{new Intl.DateTimeFormat("en-US",{weekday:"short",hour:item.all_day?undefined:"numeric",minute:item.all_day?undefined:"2-digit",timeZone:"Asia/Tokyo"}).format(start)}{item.location?` • ${item.location}`:""}</small>{item.registration_open&&<div style={{marginTop:8}}>{registration?<><strong>{registration.status==="waitlisted"?"WAITLISTED":"RSVP CONFIRMED"}</strong><button type="button" onClick={()=>cancel(registration.id)} style={{marginLeft:8}}>Cancel RSVP</button></>:<button type="button" onClick={()=>register(item.id)}>RSVP{item.registration_capacity?` • Capacity ${item.registration_capacity}`:""}</button>}</div>}</div></article>;})}</div>}<div style={{padding:"10px 12px",borderTop:"1px solid #c2ccd7",background:"#f8fafc"}}><a className="secondary-action" href="../../calendar/">View complete calendar →</a></div></section>;
}
