"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./StudentOpportunityPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Opportunity={id:string;opportunity_type:"job"|"volunteer"|"internship"|"student_leadership";title:string;department:string;description:string;location:string|null;closes_at:string|null;is_test_data:boolean};
type Application={id:string;opportunity_id:string;statement:string;status:"submitted"|"under_review"|"accepted"|"declined"|"withdrawn";staff_response:string|null;submitted_at:string;updated_at:string};
type Props={accessToken:string;characterId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function tokyo(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}

export default function StudentOpportunityPanel({accessToken,characterId}:Props){
 const [opportunities,setOpportunities]=useState<Opportunity[]>([]);const [applications,setApplications]=useState<Application[]>([]);const [drafts,setDrafts]=useState<Record<string,string>>({});const [status,setStatus]=useState("Loading campus opportunities…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const [oppResponse,appResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/campus_opportunities?select=id,opportunity_type,title,department,description,location,closes_at,is_test_data&status=eq.published&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/campus_opportunity_applications?select=id,opportunity_id,statement,status,staff_response,submitted_at,updated_at&character_id=eq.${encodeURIComponent(characterId)}&order=submitted_at.desc`,{headers:headers(accessToken)})]);if(!oppResponse.ok||!appResponse.ok)throw new Error("Campus Opportunities could not be loaded.");const [oppRows,appRows]=await Promise.all([oppResponse.json() as Promise<Opportunity[]>,appResponse.json() as Promise<Application[]>]);setOpportunities(oppRows);setApplications(appRows);setStatus(oppRows.length?`${oppRows.length} campus opportunit${oppRows.length===1?"y":"ies"} available.`:"No campus opportunities are open right now.");},[accessToken,characterId]);
 useEffect(()=>{load().catch(error=>setStatus(error instanceof Error?error.message:"Campus Opportunities could not be loaded."));},[load]);
 const byOpportunity=useMemo(()=>new Map(applications.map(row=>[row.opportunity_id,row])),[applications]);
 async function apply(event:FormEvent<HTMLFormElement>,opportunityId:string){event.preventDefault();const statement=(drafts[opportunityId]??"").trim();if(!statement){setStatus("Add a short application statement before submitting.");return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/campus_opportunity_applications`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({opportunity_id:opportunityId,character_id:characterId,statement,status:"submitted"})});if(!response.ok)throw new Error("This application could not be submitted.");setDrafts(current=>({...current,[opportunityId]:""}));await load();setStatus("Application submitted inside Hanami.");}catch(error){setStatus(error instanceof Error?error.message:"This application could not be submitted.");}finally{setSaving(false);}}
 async function withdraw(application:Application){if(application.status!=="submitted"||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/campus_opportunity_applications?id=eq.${encodeURIComponent(application.id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:"withdrawn",updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("The application could not be withdrawn.");await load();setStatus("Application withdrawn.");}catch(error){setStatus(error instanceof Error?error.message:"The application could not be withdrawn.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="campus-opportunities-title"><div className={styles.heading}><div><p className="eyebrow">CAMPUS OPPORTUNITIES</p><h4 id="campus-opportunities-title">Jobs, internships & service</h4></div><span>STUDENT APPLICATION DESK</span></div><div className={styles.status} aria-live="polite">{status}</div><div className={styles.list}>{opportunities.map(opp=>{const application=byOpportunity.get(opp.id);return <article key={opp.id} className={styles.card}><div className={styles.cardHead}><div><b>{opp.title}</b><span>{opp.department} • {opp.opportunity_type.replace("_"," ")}{opp.location?` • ${opp.location}`:""}</span></div>{opp.is_test_data&&<strong className={styles.test}>TEST</strong>}</div><p>{opp.description}</p>{opp.closes_at&&<small>Closes {tokyo(opp.closes_at)} Tokyo</small>}{application?<div className={styles.application}><strong>{application.status.replace("_"," ").toUpperCase()}</strong><p>{application.statement}</p>{application.staff_response&&<div className={styles.response}><b>SCHOOL RESPONSE</b><span>{application.staff_response}</span></div>}<small>Submitted {tokyo(application.submitted_at)}</small>{application.status==="submitted"&&<button type="button" onClick={()=>withdraw(application)} disabled={saving}>Withdraw application</button>}</div>:<form className={styles.form} onSubmit={event=>apply(event,opp.id)}><label><span>Why are you interested?</span><textarea value={drafts[opp.id]??""} onChange={event=>setDrafts(current=>({...current,[opp.id]:event.target.value}))} maxLength={4000} placeholder="Write a short in-character application statement."/></label><button type="submit" disabled={saving}>{saving?"Submitting…":"Apply inside Hanami"}</button></form>}</article>})}</div></section>;
}
