"use client";

import {ChangeEvent,useCallback,useEffect,useState} from "react";
import {createPortal} from "react-dom";
import NotificationAccessibilityPanel from "./NotificationAccessibilityPanel";
import styles from "./StudentSettingsDrawer.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const FONT_TYPES=["font/ttf","font/otf","font/woff","font/woff2","application/x-font-ttf","application/x-font-opentype","application/font-woff","application/font-woff2"];
const MAX_FONT_SIZE=5*1024*1024;
type Skin={sidebar?:string;surface?:string;radius?:string;pattern?:string;fontFamily?:string;websiteBackground?:string;customFontPath?:string;customFontName?:string};
type Props={accessToken:string;characterId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
const FONT_OPTIONS=[["default","Hanami Default"],["Arial, Helvetica, sans-serif","Arial"],["Verdana, Geneva, sans-serif","Verdana"],["Trebuchet MS, Arial, sans-serif","Trebuchet MS"],["Georgia, Times New Roman, serif","Georgia"],["Times New Roman, Times, serif","Times New Roman"],["system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif","System UI"]] as const;

export default function StudentSettingsDrawer({accessToken,characterId}:Props){
 const [open,setOpen]=useState(false),[skin,setSkin]=useState<Skin>({}),[fontFamily,setFontFamily]=useState("default"),[websiteBackground,setWebsiteBackground]=useState("#fffafa"),[notice,setNotice]=useState(""),[railBottom,setRailBottom]=useState<HTMLElement|null>(null),[fontUploading,setFontUploading]=useState(false);
 const apply=useCallback((font:string,bg:string)=>{const root=document.documentElement;if(font==="default")root.style.removeProperty("--hanami-user-font-family");else root.style.setProperty("--hanami-user-font-family",font);root.style.setProperty("--hanami-website-background",bg);},[]);
 const loadCustomFont=useCallback(async(path?:string,name?:string)=>{if(!path)return false;try{const response=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/profile-media/${encodeURI(path)}`,{headers:headers(accessToken)});if(!response.ok)return false;const blob=await response.blob();const url=URL.createObjectURL(blob);const family=`HanamiCustom-${characterId.slice(0,8)}`;const face=new FontFace(family,`url(${url})`);await face.load();document.fonts.add(face);setFontFamily(`"${family}"`);apply(`"${family}"`,websiteBackground);setNotice(`${name??"Custom font"} loaded.`);return true;}catch{return false;}},[accessToken,apply,characterId,websiteBackground]);
 const load=useCallback(async()=>{try{const response=await fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?select=portal_skin&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)});if(!response.ok)return;const row=(await response.json() as {portal_skin:Skin|null}[])[0];const next=row?.portal_skin??{};setSkin(next);const bg=next.websiteBackground??"#fffafa";setWebsiteBackground(bg);if(next.customFontPath){const loaded=await loadCustomFont(next.customFontPath,next.customFontName);if(loaded)return;}const font=next.fontFamily??"default";setFontFamily(font);apply(font,bg);}catch{}},[accessToken,characterId,apply,loadCustomFont]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const target=document.querySelector('aside[aria-label$="global navigation"] > div:last-child');setRailBottom(target instanceof HTMLElement?target:null);},[]);
 async function persist(next:Skin){setSkin(next);setNotice("Saving…");const response=await fetch(`${SUPABASE_URL}/rest/v1/character_portal_preferences?on_conflict=character_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({character_id:characterId,portal_skin:next})});setNotice(response.ok?"Settings saved.":"Settings could not be saved.");if(response.ok)window.dispatchEvent(new CustomEvent("hanami-character-identity-changed",{detail:{characterId}}));return response.ok;}
 async function save(nextFont=fontFamily,nextBg=websiteBackground){const merged:Skin={...skin,fontFamily:nextFont,websiteBackground:nextBg,customFontPath:nextFont===fontFamily?skin.customFontPath:undefined,customFontName:nextFont===fontFamily?skin.customFontName:undefined};setSkin(merged);apply(nextFont,nextBg);await persist(merged);}
 function resetVisuals(){setFontFamily("default");setWebsiteBackground("#fffafa");const next={...skin,fontFamily:"default",websiteBackground:"#fffafa",customFontPath:undefined,customFontName:undefined};setSkin(next);apply("default","#fffafa");void persist(next);}
 async function uploadFont(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;const ext=file.name.split(".").pop()?.toLowerCase();if(!["ttf","otf","woff","woff2"].includes(ext??"")||(!FONT_TYPES.includes(file.type)&&file.type!=="")){setNotice("Upload a .ttf, .otf, .woff, or .woff2 font file.");return;}if(file.size>MAX_FONT_SIZE){setNotice("Custom fonts must be 5 MB or smaller.");return;}setFontUploading(true);setNotice("Uploading custom font…");try{const path=`${characterId}/font-${crypto.randomUUID()}.${ext}`;const upload=await fetch(`${SUPABASE_URL}/storage/v1/object/profile-media/${path}`,{method:"POST",headers:headers(accessToken,{"Content-Type":file.type||"font/ttf","x-upsert":"false"}),body:file});if(!upload.ok)throw new Error("Custom font upload failed.");const family=`HanamiCustom-${characterId.slice(0,8)}`;const media=await fetch(`${SUPABASE_URL}/storage/v1/object/authenticated/profile-media/${encodeURI(path)}`,{headers:headers(accessToken)});if(!media.ok)throw new Error("Custom font could not be opened after upload.");const url=URL.createObjectURL(await media.blob());const face=new FontFace(family,`url(${url})`);await face.load();document.fonts.add(face);const familyValue=`"${family}"`;const next={...skin,fontFamily:familyValue,customFontPath:path,customFontName:file.name,websiteBackground};setFontFamily(familyValue);setSkin(next);apply(familyValue,websiteBackground);if(!await persist(next))throw new Error("Custom font settings could not be saved.");setNotice(`${file.name} is now your website font.`);}catch(error){setNotice(error instanceof Error?error.message:"Custom font could not be uploaded.");}finally{setFontUploading(false);}}
 const trigger=<button type="button" className={styles.settingsButton} onClick={()=>setOpen(true)} aria-label="Open portal settings"><span aria-hidden="true">⚙</span><b>Settings</b></button>;
 return <>{railBottom?createPortal(trigger,railBottom):null}{open&&<div className={styles.backdrop} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="student-settings-title"><header className={styles.header}><div><small>PORTAL SETTINGS</small><h2 id="student-settings-title">Settings</h2><p>Personalize how the Hanami website looks and behaves for you.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close settings">×</button></header><div className={styles.content}><section className={styles.visualSection}><div className={styles.sectionHeading}><div><h3>Website appearance</h3><p>These settings change the portal website itself, not your dashboard wallpaper or course-card designs.</p></div><button type="button" onClick={resetVisuals}>Reset appearance</button></div><div className={styles.controlGrid}><label>Website font<select value={FONT_OPTIONS.some(([v])=>v===fontFamily)?fontFamily:"default"} onChange={e=>{setFontFamily(e.target.value);apply(e.target.value,websiteBackground);void save(e.target.value,websiteBackground);}}>{FONT_OPTIONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Website background color<div className={styles.colorRow}><input type="color" value={websiteBackground} onChange={e=>{setWebsiteBackground(e.target.value);apply(fontFamily,e.target.value);}} onBlur={()=>void save()}/><input type="text" value={websiteBackground} onChange={e=>setWebsiteBackground(e.target.value)} onBlur={()=>void save()} aria-label="Website background hex color"/></div></label></div><div className={styles.customFont}><div><strong>Custom font</strong><span>Upload a font file you are allowed to use, including fonts downloaded from DaFont. TTF, OTF, WOFF and WOFF2 are supported.</span>{skin.customFontName&&<small>Current: {skin.customFontName}</small>}</div><label className={styles.fontUpload}>{fontUploading?"Uploading…":"Upload font"}<input type="file" accept=".ttf,.otf,.woff,.woff2,font/ttf,font/otf,font/woff,font/woff2" disabled={fontUploading} onChange={uploadFont}/></label></div><div className={styles.preview} style={{fontFamily:fontFamily==="default"?undefined:fontFamily,background:websiteBackground}}><strong>Preview</strong><span>Hanami High • Student Portal • Assignments • Messages</span></div>{notice&&<p className={styles.notice}>{notice}</p>}</section><NotificationAccessibilityPanel accessToken={accessToken} characterId={characterId}/></div></section></div>}</>;
}
