"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./StudentDashboardOverview.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Meeting={weekday:number;starts_at:string;ends_at:string;label:string|null};
type Course={code:string;title:string};
type Section={id:string;section_code:string;room:string|null;academic_courses:Course|null;section_meetings:Meeting[]};
type Membership={relationship:"student"|"instructor";class_sections:Section|null};
type SchoolBlock={id:string;block_type:string;title:string;weekday:number|null;starts_at:string;ends_at:string;homeroom_label:string|null};
type TodayItem={key:string;starts_at:string;ends_at:string;title:string;meta:string;kind:"class"|"school"};
type Props={accessToken:string;characterId:string;onOpenCourses:()=>void;onOpenSchedule:()=>void};
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`};}
function timeLabel(value:string){const [h,m]=value.split(":");const hour=Number(h);return `${hour%12||12}:${m} ${hour>=12?"PM":"AM"}`;}
function isSchoolwide(block:SchoolBlock){const label=(block.homeroom_label??"").trim().toLowerCase();return !label||label==="all homerooms"||label==="school wide"||label==="school-wide"||label==="all";}
function tokyoWeekday(){const name=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(new Date());return ["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].indexOf(name);}
export default function StudentDashboardOverview({accessToken,characterId,onOpenCourses,onOpenSchedule}:Props){
 const [sections,setSections]=useState<Section[]>([]),[today,setToday]=useState<TodayItem[]>([]),[state,setState]=useState<"loading"|"ready"|"error">("loading");
 useEffect(()=>{let cancelled=false;async function load(){setState("loading");try{const select="relationship,class_sections(id,section_code,room,academic_courses(code,title),section_meetings(weekday,starts_at,ends_at,label))";const [membershipResponse,blockResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.student`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,block_type,title,weekday,starts_at,ends_at,homeroom_label&order=weekday.asc,starts_at.asc`,{headers:headers(accessToken)})]);if(!membershipResponse.ok)throw new Error("Dashboard data unavailable");const memberships=await membershipResponse.json() as Membership[];const blocks=blockResponse.ok?await blockResponse.json() as SchoolBlock[]:[];const enrolled=memberships.map(row=>row.class_sections).filter((section):section is Section=>Boolean(section));const day=tokyoWeekday();const items:TodayItem[]=[];enrolled.forEach(section=>(section.section_meetings??[]).filter(m=>m.weekday===day).forEach((meeting,index)=>items.push({key:`class-${section.id}-${index}`,starts_at:meeting.starts_at,ends_at:meeting.ends_at,title:section.academic_courses?.title??"Class",meta:`${section.academic_courses?.code??"COURSE"} · ${section.section_code}${section.room?` · Room ${section.room}`:""}`,kind:"class"})));blocks.filter(block=>block.weekday===day&&isSchoolwide(block)).forEach(block=>items.push({key:`block-${block.id}`,starts_at:block.starts_at,ends_at:block.ends_at,title:block.title,meta:block.block_type.replaceAll("_"," "),kind:"school"}));items.sort((a,b)=>a.starts_at.localeCompare(b.starts_at));if(!cancelled){setSections(enrolled);setToday(items);setState("ready");}}catch{if(!cancelled)setState("error");}}void load();return()=>{cancelled=true};},[accessToken,characterId]);
 const dayName=useMemo(()=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(new Date()),[]);
 return <div className={styles.grid}><section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">TODAY · JST</p><h3>{dayName} schedule</h3></div><button type="button" onClick={onOpenSchedule}>Full schedule</button></div>{state==="loading"?<p className={styles.status}>Loading today&apos;s schedule…</p>:state==="error"?<p className={styles.status}>Today&apos;s schedule could not be loaded.</p>:today.length?<div className={styles.timeline}>{today.map(item=><div key={item.key} className={`${styles.slot} ${item.kind==="school"?styles.school:""}`}><time>{timeLabel(item.starts_at)}–{timeLabel(item.ends_at)}</time><div><strong>{item.title}</strong><small>{item.meta}</small></div></div>)}</div>:<p className={styles.status}>No school schedule is posted for today.</p>}</section><section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">MY COURSES</p><h3>Enrolled classes</h3></div><button type="button" onClick={onOpenCourses}>View courses</button></div>{state==="loading"?<p className={styles.status}>Loading your classes…</p>:sections.length?<div className={styles.courses}>{sections.map(section=><button type="button" key={section.id} onClick={onOpenCourses}><span><strong>{section.academic_courses?.title??"Untitled course"}</strong><small>{section.academic_courses?.code??"COURSE"} · {section.section_code}</small></span><b>→</b></button>)}</div>:<p className={styles.status}>No classes are assigned yet.</p>}</section></div>;
}
