"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./StudentLifeSystemsPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function rpc<T>(token:string,name:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}

type Role="student"|"faculty";
type Announcement={id:string;title:string;body:string;category:string;severity:string;featured:boolean;audience_scope:string;requires_acknowledgement:boolean;published_at:string|null;expires_at:string|null;is_read:boolean;acknowledged_at:string|null};
type HallPass={id:string;student_character_id:string;pass_type:string;destination:string;reason:string;status:string;valid_from:string|null;valid_until:string|null;staff_note:string};
type Excuse={id:string;student_character_id:string;absence_date:string;excuse_type:string;explanation:string;status:string;staff_response:string;reviewed_at:string|null};
type Conduct={id:string;case_type:string;title:string;details:string;resolution:string;status:string;detention_at:string|null;appeal_status:string;created_at:string};
type Session={id:string;code:string;title:string;school_year:string;chapter_number:number;season:string;status:string;starts_at:string|null;ends_at:string|null;summary:string;graduation_year_level:string|null};
type SchoolId={character_id:string;school_number:string;barcode_value:string;status:string;issued_at:string;expires_at:string|null};
type StudentDirectory={character_id:string;display_name:string;handle:string};

type Props={accessToken:string;characterId:string;role:Role};
function tokyo(value:string|null){return value?new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value)):"—";}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}

export default function StudentLifeSystemsPanel({accessToken,characterId,role}:Props){
 const isStudent=role==="student";
 const [announcements,setAnnouncements]=useState<Announcement[]>([]);const [passes,setPasses]=useState<HallPass[]>([]);const [excuses,setExcuses]=useState<Excuse[]>([]);const [conduct,setConduct]=useState<Conduct[]>([]);const [sessions,setSessions]=useState<Session[]>([]);const [schoolId,setSchoolId]=useState<SchoolId|null>(null);const [students,setStudents]=useState<StudentDirectory[]>([]);const [status,setStatus]=useState("Loading Hanami life systems…");const [saving,setSaving]=useState(false);
 const [passType,setPassType]=useState("nurse");const [destination,setDestination]=useState("");const [passReason,setPassReason]=useState("");
 const [absenceDate,setAbsenceDate]=useState(today());const [excuseType,setExcuseType]=useState("absence");const [excuseText,setExcuseText]=useState("");
 const [detentionStudent,setDetentionStudent]=useState("");const [detentionTitle,setDetentionTitle]=useState("");const [detentionDetails,setDetentionDetails]=useState("");const [detentionAt,setDetentionAt]=useState("");

 const load=useCallback(async()=>{try{
   const announcementPromise=rpc<Announcement[]>(accessToken,"visible_hanami_announcements",{viewer_character_id:characterId});
   const passPromise=isStudent?rpc<HallPass[]>(accessToken,"student_hall_pass_feed",{viewer_character_id:characterId}):fetch(`${SUPABASE_URL}/rest/v1/hall_passes?select=id,student_character_id,pass_type,destination,reason,status,valid_from,valid_until,staff_note&order=created_at.desc&limit=30`,{headers:headers(accessToken)}).then(async r=>r.ok?await r.json() as HallPass[]:[]);
   const excusePromise=isStudent?rpc<Excuse[]>(accessToken,"student_attendance_excuse_feed",{viewer_character_id:characterId}):fetch(`${SUPABASE_URL}/rest/v1/attendance_excuses?select=id,student_character_id,absence_date,excuse_type,explanation,status,staff_response,reviewed_at&order=created_at.desc&limit=30`,{headers:headers(accessToken)}).then(async r=>r.ok?await r.json() as Excuse[]:[]);
   const sessionPromise=fetch(`${SUPABASE_URL}/rest/v1/roleplay_sessions?select=id,code,title,school_year,chapter_number,season,status,starts_at,ends_at,summary,graduation_year_level&status=in.(active,closing)&order=created_at.desc&limit=2`,{headers:headers(accessToken)}).then(async r=>r.ok?await r.json() as Session[]:[]);
   const idPromise=fetch(`${SUPABASE_URL}/rest/v1/character_school_ids?select=character_id,school_number,barcode_value,status,issued_at,expires_at&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}).then(async r=>r.ok?await r.json() as SchoolId[]:[]);
   const conductPromise=isStudent?rpc<Conduct[]>(accessToken,"student_conduct_view",{viewer_character_id:characterId}).catch(()=>[]):Promise.resolve([] as Conduct[]);
   const studentsPromise=!isStudent?rpc<StudentDirectory[]>(accessToken,"faculty_student_directory",{faculty_character_id:characterId}).catch(()=>[]):Promise.resolve([] as StudentDirectory[]);
   const [a,p,e,s,ids,c,sd]=await Promise.all([announcementPromise,passPromise,excusePromise,sessionPromise,idPromise,conductPromise,studentsPromise]);
   setAnnouncements(a);setPasses(p);setExcuses(e);setSessions(s);setSchoolId(ids[0]??null);setConduct(c);setStudents(sd);if(!detentionStudent&&sd[0])setDetentionStudent(sd[0].character_id);
   setStatus("Hanami life systems are live.");
 }catch(error){setStatus(error instanceof Error?error.message:"Some Hanami life systems could not be loaded.");}},[accessToken,characterId,isStudent,detentionStudent]);
 useEffect(()=>{void load();},[load]);
 const unreadAnnouncements=useMemo(()=>announcements.filter(a=>!a.is_read).length,[announcements]);

 async function markAnnouncement(item:Announcement,acknowledge=false){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/announcement_receipts?on_conflict=announcement_id,user_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({announcement_id:item.id,character_id:characterId,read_at:new Date().toISOString(),acknowledged_at:acknowledge?new Date().toISOString():item.acknowledged_at})});if(!response.ok)throw new Error("Announcement receipt could not be saved.");await load();setStatus(acknowledge?"Announcement acknowledged.":"Announcement marked read.");}catch(error){setStatus(error instanceof Error?error.message:"Announcement could not be updated.");}finally{setSaving(false);}}
 async function requestPass(event:FormEvent){event.preventDefault();if(!isStudent)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/hall_passes`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({student_character_id:characterId,requested_by_character_id:characterId,pass_type:passType,destination:destination.trim(),reason:passReason.trim()})});if(!response.ok)throw new Error("Hall pass request could not be submitted.");setDestination("");setPassReason("");await load();setStatus("Hall pass request submitted.");}catch(error){setStatus(error instanceof Error?error.message:"Hall pass request could not be submitted.");}finally{setSaving(false);}}
 async function reviewPass(item:HallPass,next:"approved"|"denied"){if(isStudent)return;setSaving(true);try{const now=new Date();const until=new Date(now.getTime()+30*60*1000);const response=await fetch(`${SUPABASE_URL}/rest/v1/hall_passes?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,issued_by_character_id:characterId,valid_from:next==="approved"?now.toISOString():null,valid_until:next==="approved"?until.toISOString():null,updated_at:now.toISOString()})});if(!response.ok)throw new Error("Hall pass decision could not be saved.");await load();setStatus(`Hall pass ${next}.`);}catch(error){setStatus(error instanceof Error?error.message:"Hall pass decision could not be saved.");}finally{setSaving(false);}}
 async function submitExcuse(event:FormEvent){event.preventDefault();if(!isStudent)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/attendance_excuses`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({student_character_id:characterId,absence_date:absenceDate,excuse_type:excuseType,explanation:excuseText.trim()})});if(!response.ok)throw new Error("Attendance excuse could not be submitted.");setExcuseText("");await load();setStatus("Attendance excuse submitted for review.");}catch(error){setStatus(error instanceof Error?error.message:"Attendance excuse could not be submitted.");}finally{setSaving(false);}}
 async function reviewExcuse(item:Excuse,next:"approved"|"denied"){if(isStudent)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/attendance_excuses?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,reviewed_by_character_id:characterId,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Attendance excuse decision could not be saved.");await load();setStatus(`Attendance excuse ${next}.`);}catch(error){setStatus(error instanceof Error?error.message:"Attendance excuse decision could not be saved.");}finally{setSaving(false);}}
 async function assignDetention(event:FormEvent){event.preventDefault();if(isStudent||!detentionStudent)return;setSaving(true);try{await rpc<string>(accessToken,"faculty_assign_detention",{faculty_character_id:characterId,student_character_id:detentionStudent,detention_title:detentionTitle.trim(),detention_details:detentionDetails.trim(),detention_time:new Date(detentionAt).toISOString()});setDetentionTitle("");setDetentionDetails("");setDetentionAt("");setStatus("Detention assigned. Escalated conduct actions remain restricted to higher staff.");}catch(error){setStatus(error instanceof Error?error.message:"Detention could not be assigned.");}finally{setSaving(false);}}
 async function appealConduct(item:Conduct){if(!isStudent)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/moderation_appeals`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({appellant_character_id:characterId,conduct_case_id:item.id,action_type:item.case_type,action_reference:item.id,reason:`Requesting review of: ${item.title}`})});if(!response.ok)throw new Error("Appeal could not be submitted.");setStatus("Conduct appeal submitted for staff review.");}catch(error){setStatus(error instanceof Error?error.message:"Appeal could not be submitted.");}finally{setSaving(false);}}

 const myPasses=isStudent?passes.filter(p=>p.student_character_id===characterId):passes.filter(p=>p.status==="requested");const myExcuses=isStudent?excuses.filter(e=>e.student_character_id===characterId):excuses.filter(e=>["submitted","needs_information"].includes(e.status));
 return <section className={styles.panel} aria-labelledby="life-systems-title"><div className={styles.heading}><div><p className="eyebrow">HANAMI LIFE SYSTEMS</p><h4 id="life-systems-title">School life control center</h4></div><span>{status}</span></div>
  <div className={styles.summary}><div><strong>{unreadAnnouncements}</strong><span>Unread notices</span></div><div><strong>{myPasses.filter(p=>["requested","approved","active"].includes(p.status)).length}</strong><span>{isStudent?"My passes":"Pass requests"}</span></div><div><strong>{myExcuses.filter(e=>["submitted","needs_information"].includes(e.status)).length}</strong><span>{isStudent?"Excuses pending":"Excuses to review"}</span></div><div><strong>{sessions[0]?.chapter_number??"—"}</strong><span>Current chapter</span></div></div>
  <div className={styles.grid}>
   <details className={styles.card} open><summary><span>Announcements</span><small>{unreadAnnouncements} unread</small><b>⌄</b></summary><div className={styles.body}>{announcements.length?announcements.slice(0,8).map(item=><article key={item.id} className={`${styles.row} ${!item.is_read?styles.unread:""}`}><div className={styles.meta}>{item.severity.toUpperCase()} • {item.audience_scope.replaceAll("_"," ").toUpperCase()} • {tokyo(item.published_at)}</div><strong>{item.title}</strong><p>{item.body}</p><div className={styles.actions}>{!item.is_read&&<button type="button" disabled={saving} onClick={()=>markAnnouncement(item,false)}>Mark read</button>}{item.requires_acknowledgement&&!item.acknowledged_at&&<button type="button" disabled={saving} onClick={()=>markAnnouncement(item,true)}>Acknowledge</button>}{item.acknowledged_at&&<span>✓ Acknowledged</span>}</div></article>):<p>No current announcements.</p>}</div></details>
   <details className={styles.card}><summary><span>Hall Passes</span><small>{myPasses.length} shown</small><b>⌄</b></summary><div className={styles.body}>{isStudent&&<form className={styles.form} onSubmit={requestPass}><select value={passType} onChange={e=>setPassType(e.target.value)}><option value="nurse">Nurse</option><option value="counselor">Counselor</option><option value="library">Library</option><option value="club_activity">Club activity</option><option value="early_dismissal">Early dismissal</option><option value="office">School office</option><option value="restroom">Restroom</option><option value="other">Other</option></select><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Destination"/><textarea value={passReason} onChange={e=>setPassReason(e.target.value)} placeholder="Reason for request" required/><button disabled={saving}>Request pass</button></form>}{myPasses.map(item=><article className={styles.row} key={item.id}><strong>{item.pass_type.replaceAll("_"," ")} • {item.status}</strong><span>{item.destination||"No destination listed"}{item.valid_until?` • valid until ${tokyo(item.valid_until)}`:""}</span><p>{item.reason}</p>{item.staff_note&&<p>{item.staff_note}</p>}{!isStudent&&item.status==="requested"&&<div className={styles.actions}><button type="button" disabled={saving} onClick={()=>reviewPass(item,"approved")}>Approve 30 min</button><button type="button" disabled={saving} onClick={()=>reviewPass(item,"denied")}>Deny</button></div>}</article>)}{!myPasses.length&&<p>No hall-pass items right now.</p>}</div></details>
   <details className={styles.card}><summary><span>Attendance Excuses</span><small>{myExcuses.length} shown</small><b>⌄</b></summary><div className={styles.body}>{isStudent&&<form className={styles.form} onSubmit={submitExcuse}><input type="date" value={absenceDate} onChange={e=>setAbsenceDate(e.target.value)}/><select value={excuseType} onChange={e=>setExcuseType(e.target.value)}><option value="absence">Absence</option><option value="tardy">Tardy</option><option value="early_dismissal">Early dismissal</option></select><textarea value={excuseText} onChange={e=>setExcuseText(e.target.value)} placeholder="Explain the absence or tardy" required/><button disabled={saving}>Submit excuse</button></form>}{myExcuses.map(item=><article className={styles.row} key={item.id}><strong>{item.absence_date} • {item.excuse_type.replaceAll("_"," ")} • {item.status}</strong><p>{item.explanation}</p>{item.staff_response&&<p>{item.staff_response}</p>}{!isStudent&&["submitted","needs_information"].includes(item.status)&&<div className={styles.actions}><button type="button" disabled={saving} onClick={()=>reviewExcuse(item,"approved")}>Approve</button><button type="button" disabled={saving} onClick={()=>reviewExcuse(item,"denied")}>Deny</button></div>}</article>)}{!myExcuses.length&&<p>No attendance-excuse items right now.</p>}</div></details>
   <details className={styles.card}><summary><span>Discipline & Detention</span><small>{isStudent?`${conduct.length} case${conduct.length===1?"":"s"}`:"Faculty detention tools"}</small><b>⌄</b></summary><div className={styles.body}>{isStudent?<>{conduct.map(item=><article className={styles.row} key={item.id}><strong>{item.case_type.replaceAll("_"," ")} • {item.status}</strong><span>{item.detention_at?`Detention: ${tokyo(item.detention_at)}`:`Opened ${tokyo(item.created_at)}`}</span><p>{item.title}</p><p>{item.details}</p>{item.resolution&&<p><b>Resolution:</b> {item.resolution}</p>}<div className={styles.actions}><button type="button" disabled={saving||item.appeal_status!=="none"} onClick={()=>appealConduct(item)}>{item.appeal_status==="none"?"Appeal":"Appeal on file"}</button></div></article>)}{!conduct.length&&<p>No active or historical conduct cases are visible to this character.</p>}</>:<form className={styles.form} onSubmit={assignDetention}><select value={detentionStudent} onChange={e=>setDetentionStudent(e.target.value)} required>{students.map(student=><option key={student.character_id} value={student.character_id}>{student.display_name} (@{student.handle})</option>)}</select><input value={detentionTitle} onChange={e=>setDetentionTitle(e.target.value)} placeholder="Detention reason/title" required/><textarea value={detentionDetails} onChange={e=>setDetentionDetails(e.target.value)} placeholder="What happened?" required/><input type="datetime-local" value={detentionAt} onChange={e=>setDetentionAt(e.target.value)} required/><button disabled={saving||!students.length}>Assign detention</button><small>Faculty may assign detention only. Suspension, expulsion, sanctions, and escalated conduct actions stay with higher staff/Owner.</small></form>}</div></details>
   <details className={styles.card}><summary><span>Session / Chapter</span><small>{sessions[0]?.status??"No active session"}</small><b>⌄</b></summary><div className={styles.body}>{sessions.length?sessions.map(session=><article className={styles.row} key={session.id}><div className={styles.meta}>{session.school_year} • {session.season.toUpperCase()} • CHAPTER {session.chapter_number}</div><strong>{session.title}</strong><p>{session.summary||"Session details will be posted by Administration."}</p><span>{session.starts_at?`Started ${tokyo(session.starts_at)}`:"Start TBA"}{session.ends_at?` • closes ${tokyo(session.ends_at)}`:""}</span>{session.graduation_year_level&&<span>Graduation group: {session.graduation_year_level}</span>}</article>):<p>No active roleplay session is published yet.</p>}</div></details>
   <details className={styles.card}><summary><span>School ID</span><small>{schoolId?.status??"Pending"}</small><b>⌄</b></summary><div className={styles.body}>{schoolId?<div className={styles.idCard}><span>花見高等学校 • HANAMI HIGH</span><strong>{schoolId.school_number}</strong><b>{schoolId.barcode_value}</b><small>Issued {new Date(schoolId.issued_at).toLocaleDateString()} • {schoolId.status.toUpperCase()}</small></div>:<p>Your school ID has not been issued yet. Administration can issue or reissue IDs without changing your character account.</p>}</div></details>
  </div>
 </section>;
}
