"use client";

import {useEffect,useMemo,useState,type ReactNode} from "react";
import {hanamiRoleplayNow} from "../components/roleplay-date";
import styles from "./StudentDashboardOverview.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const DEFAULT_WIDGETS=["today","schedule","assignments","grades","attendance","events","clubs","friends","study"];
type Meeting={weekday:number;starts_at:string;ends_at:string;label:string|null};
type Course={code:string;title:string};
type Section={id:string;section_code:string;room:string|null;academic_courses:Course|null;section_meetings:Meeting[]};
type Membership={relationship:"student"|"instructor";class_sections:Section|null};
type SchoolBlock={id:string;block_type:string;title:string;weekday:number|null;starts_at:string;ends_at:string;homeroom_label:string|null};
type HomeroomMembership={homerooms:{code:string}|null};
type ActivityMembership={activity_id:string};
type ActivityEvent={id:string;activity_id:string|null;title:string;starts_at:string;ends_at:string|null;location:string|null};
type TodayItem={key:string;starts_at:string;ends_at:string;title:string;meta:string;kind:"class"|"school"|"club"};
type Assignment={id:string;section_id:string;title:string;due_at:string|null;points:number;class_sections:{academic_courses:{code:string;title:string}|null}|null};
type Submission={assignment_id:string;status:"draft"|"submitted"|"returned";grade:number|null};
type Attendance={id:string;attendance_date:string;status:string};
type Event={id:string;title:string;starts_at:string;location:string|null};
type Friendship={id:string};
type StudyStreak={current_streak:number;longest_streak:number;last_study_date:string|null};
type StudySession={id:string;duration_minutes:number|null};
type DashboardLayout={layout:string[];hidden_widgets:string[]};
type Props={accessToken:string;characterId:string;onOpenCourses:()=>void;onOpenSchedule:()=>void};
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`};}
function timeLabel(value:string){const [h,m]=value.split(":");const hour=Number(h);return `${hour%12||12}:${m} ${hour>=12?"PM":"AM"}`;}
function timeMinutes(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
function dueLabel(value:string|null){if(!value)return "No due date";return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));}
function normalizedHomeroom(value:string|null){const clean=(value??"").trim().toUpperCase();if(!clean)return "";const match=clean.match(/([A-Z])$/);return match?.[1]??clean;}
function isSchoolwide(block:SchoolBlock){const label=(block.homeroom_label??"").trim().toLowerCase();return !label||label==="all homerooms"||label==="school wide"||label==="school-wide"||label==="all";}
function roleplayWeekday(value:Date){const name=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(value);return ["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].indexOf(name);}
function eventWeekday(value:string){const name=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(new Date(value));return ["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].indexOf(name);}
function eventClock(value:string){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));return `${parts.find(p=>p.type==="hour")?.value??"00"}:${parts.find(p=>p.type==="minute")?.value??"00"}:00`;}
function nowMinutes(value:Date){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(value);return Number(parts.find(p=>p.type==="hour")?.value??0)*60+Number(parts.find(p=>p.type==="minute")?.value??0);}
function roleplayStamp(value:Date){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",month:"2-digit",day:"2-digit"}).formatToParts(value);const month=parts.find(p=>p.type==="month")?.value??"01";const day=parts.find(p=>p.type==="day")?.value??"01";return `2006-${month}-${day}T00:00:00+09:00`;}

export default function StudentDashboardOverview({accessToken,characterId,onOpenCourses,onOpenSchedule}:Props){
 const [sections,setSections]=useState<Section[]>([]),[today,setToday]=useState<TodayItem[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[events,setEvents]=useState<Event[]>([]),[friendships,setFriendships]=useState<Friendship[]>([]),[studyStreak,setStudyStreak]=useState<StudyStreak|null>(null),[studySessions,setStudySessions]=useState<StudySession[]>([]),[layout,setLayout]=useState<DashboardLayout>({layout:DEFAULT_WIDGETS,hidden_widgets:[]}),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[clock,setClock]=useState(()=>hanamiRoleplayNow());
 useEffect(()=>{const timer=window.setInterval(()=>setClock(hanamiRoleplayNow()),30000);return()=>window.clearInterval(timer);},[]);
 useEffect(()=>{let cancelled=false;async function load(){setState("loading");try{
  const select="relationship,class_sections(id,section_code,room,academic_courses(code,title),section_meetings(weekday,starts_at,ends_at,label))";
  const [membershipResponse,blockResponse,homeroomResponse,activityMembershipResponse,eventResponse,attendanceResponse,calendarResponse,friendResponse,streakResponse,sessionResponse,layoutResponse]=await Promise.all([
   fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=${encodeURIComponent(select)}&character_id=eq.${encodeURIComponent(characterId)}&relationship=eq.student`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,block_type,title,weekday,starts_at,ends_at,homeroom_label&order=weekday.asc,starts_at.asc`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/homeroom_memberships?select=homerooms(code)&student_character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/campus_activity_memberships?select=activity_id&character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/campus_activity_events?select=id,activity_id,title,starts_at,ends_at,location&is_public=eq.true&starts_at=gte.2006-04-01T00:00:00%2B09:00&starts_at=lt.2007-04-01T00:00:00%2B09:00&order=starts_at.asc&limit=50`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/attendance_records?select=id,attendance_date,status&student_character_id=eq.${encodeURIComponent(characterId)}&order=attendance_date.desc&limit=100`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/school_calendar_events?select=id,title,starts_at,location&status=eq.published&starts_at=gte.${encodeURIComponent(roleplayStamp(hanamiRoleplayNow()))}&order=starts_at.asc&limit=5`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/character_friendships?select=id&status=eq.accepted&or=(requester_character_id.eq.${encodeURIComponent(characterId)},addressee_character_id.eq.${encodeURIComponent(characterId)})`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/study_streaks?select=current_streak,longest_streak,last_study_date&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/study_sessions?select=id,duration_minutes&character_id=eq.${encodeURIComponent(characterId)}&order=created_at.desc&limit=50`,{headers:headers(accessToken)}),
   fetch(`${SUPABASE_URL}/rest/v1/dashboard_layouts?select=layout,hidden_widgets&character_id=eq.${encodeURIComponent(characterId)}&limit=1`,{headers:headers(accessToken)})
  ]);
  if(!membershipResponse.ok)throw new Error("Dashboard data unavailable");
  const memberships=await membershipResponse.json() as Membership[];const blocks=blockResponse.ok?await blockResponse.json() as SchoolBlock[]:[];const homeroom=(homeroomResponse.ok?(await homeroomResponse.json() as HomeroomMembership[]):[])[0]?.homerooms?.code??"";const activityMemberships=activityMembershipResponse.ok?await activityMembershipResponse.json() as ActivityMembership[]:[];const activityEvents=eventResponse.ok?await eventResponse.json() as ActivityEvent[]:[];
  const enrolled=memberships.map(row=>row.class_sections).filter((section):section is Section=>Boolean(section));const day=roleplayWeekday(hanamiRoleplayNow());const roomLetter=normalizedHomeroom(homeroom);const items:TodayItem[]=[];
  enrolled.forEach(section=>(section.section_meetings??[]).filter(m=>m.weekday===day).forEach((meeting,index)=>items.push({key:`class-${section.id}-${index}`,starts_at:meeting.starts_at,ends_at:meeting.ends_at,title:section.academic_courses?.title??"Class",meta:`${section.academic_courses?.code??"COURSE"} · ${section.section_code}${section.room?` · Room ${section.room}`:""}`,kind:"class"})));
  blocks.filter(block=>block.weekday===day&&(isSchoolwide(block)||normalizedHomeroom(block.homeroom_label)===roomLetter)).forEach(block=>items.push({key:`block-${block.id}`,starts_at:block.starts_at,ends_at:block.ends_at,title:block.title,meta:block.block_type.replaceAll("_"," "),kind:"school"}));
  const joinedIds=new Set(activityMemberships.map(item=>item.activity_id));activityEvents.filter(event=>event.activity_id&&joinedIds.has(event.activity_id)&&eventWeekday(event.starts_at)===day).forEach(event=>items.push({key:`club-${event.id}`,starts_at:eventClock(event.starts_at),ends_at:event.ends_at?eventClock(event.ends_at):eventClock(event.starts_at),title:event.title,meta:`Club activity${event.location?` · ${event.location}`:""}`,kind:"club"}));items.sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
  const sectionIds=enrolled.map(section=>section.id);let assignmentRows:Assignment[]=[];let submissionRows:Submission[]=[];if(sectionIds.length){const inFilter=`(${sectionIds.join(",")})`;const [assignmentResponse,submissionResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/course_assignments?select=id,section_id,title,due_at,points,class_sections(academic_courses(code,title))&section_id=in.${encodeURIComponent(inFilter)}&status=eq.published&order=due_at.asc.nullslast&limit=20`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/assignment_submissions?select=assignment_id,status,grade&student_character_id=eq.${encodeURIComponent(characterId)}`,{headers:headers(accessToken)})]);if(assignmentResponse.ok)assignmentRows=await assignmentResponse.json() as Assignment[];if(submissionResponse.ok)submissionRows=await submissionResponse.json() as Submission[];}
  if(!cancelled){setSections(enrolled);setToday(items);setAssignments(assignmentRows);setSubmissions(submissionRows);setAttendance(attendanceResponse.ok?await attendanceResponse.json() as Attendance[]:[]);setEvents(calendarResponse.ok?await calendarResponse.json() as Event[]:[]);setFriendships(friendResponse.ok?await friendResponse.json() as Friendship[]:[]);setStudyStreak((streakResponse.ok?await streakResponse.json() as StudyStreak[]:[])[0]??null);setStudySessions(sessionResponse.ok?await sessionResponse.json() as StudySession[]:[]);const saved=(layoutResponse.ok?await layoutResponse.json() as DashboardLayout[]:[])[0];if(saved)setLayout({layout:Array.isArray(saved.layout)?saved.layout:DEFAULT_WIDGETS,hidden_widgets:Array.isArray(saved.hidden_widgets)?saved.hidden_widgets:[]});setState("ready");}
 }catch{if(!cancelled)setState("error");}}void load();return()=>{cancelled=true};},[accessToken,characterId]);
 const dayName=useMemo(()=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"long"}).format(clock),[clock]);const weekday=roleplayWeekday(clock);const minute=nowMinutes(clock);const live=useMemo(()=>{const current=today.find(item=>minute>=timeMinutes(item.starts_at)&&minute<timeMinutes(item.ends_at))??null;const next=today.find(item=>timeMinutes(item.starts_at)>minute)??null;return {current,next};},[minute,today]);const clockLabel=useMemo(()=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"numeric",minute:"2-digit"}).format(clock),[clock]);const submissionMap=useMemo(()=>new Map(submissions.map(item=>[item.assignment_id,item.status])),[submissions]);const priorities=useMemo(()=>assignments.filter(item=>!(["submitted","returned"] as string[]).includes(submissionMap.get(item.id)??"")).slice(0,4),[assignments,submissionMap]);const graded=submissions.filter(item=>item.grade!==null);const gradeAverage=graded.length?graded.reduce((sum,item)=>sum+Number(item.grade),0)/graded.length:null;const present=attendance.filter(item=>item.status==="present").length;const attendanceRate=attendance.length?Math.round((present/attendance.length)*100):null;const studyMinutes=studySessions.reduce((sum,item)=>sum+(item.duration_minutes??0),0);const clubItems=today.filter(item=>item.kind==="club");
 const schoolPhase=useMemo(()=>{if(weekday===6||weekday===7)return "weekend";if(minute<510)return "before-school";if(minute<530)return "homeroom";if(minute>=760&&minute<805)return "lunch";if(minute>=935)return weekday===2||weekday===3?"clubs":"after-school";return "classes";},[minute,weekday]);
 const ordered=useMemo(()=>{const saved=[...new Set([...layout.layout,...DEFAULT_WIDGETS])].filter(id=>DEFAULT_WIDGETS.includes(id)&&!layout.hidden_widgets.includes(id));const promoted:string[]=["today"];if(priorities.length)promoted.push("assignments");if(schoolPhase==="before-school"||schoolPhase==="homeroom"||schoolPhase==="classes")promoted.push("schedule","attendance");if(schoolPhase==="lunch")promoted.push("friends","events");if(schoolPhase==="clubs")promoted.push("clubs","events");if(schoolPhase==="weekend")promoted.push("events","clubs");if(schoolPhase==="after-school")promoted.push("assignments","study","events");if(graded.length)promoted.push("grades");return [...new Set([...promoted,...saved])].filter(id=>saved.includes(id));},[layout,priorities.length,schoolPhase,graded.length]);
 const widgets:Record<string,ReactNode>={
  today:<section className={styles.command} key="today"><div><p className="eyebrow">LIVE SCHOOL DAY · {clockLabel} JST</p><h3>{live.current?live.current.title:live.next?"Passing / open time":schoolPhase==="weekend"?"Weekend campus":"School day complete"}</h3><p>{live.current?`${timeLabel(live.current.starts_at)}–${timeLabel(live.current.ends_at)} · ${live.current.meta}`:live.next?`Next: ${live.next.title} at ${timeLabel(live.next.starts_at)}`:schoolPhase==="weekend"?"Weekend sports and published campus events are emphasized today.":"No more scheduled items today."}</p></div><div className={styles.commandNext}><span>NEXT UP</span><strong>{live.next?.title??(schoolPhase==="clubs"?"Club activities":"Nothing else scheduled")}</strong><small>{live.next?`${timeLabel(live.next.starts_at)} · ${live.next.meta}`:"You are clear for the day."}</small></div><div className={styles.quickActions}><button type="button" onClick={onOpenSchedule}>Open schedule</button><button type="button" onClick={onOpenCourses}>Open courses</button></div></section>,
  schedule:<section className={styles.panel} key="schedule"><div className={styles.heading}><div><p className="eyebrow">TODAY · JST · ROLEPLAY CALENDAR</p><h3>{dayName} schedule</h3></div><button type="button" onClick={onOpenSchedule}>Full schedule</button></div>{state==="loading"?<p className={styles.status}>Loading today&apos;s schedule…</p>:state==="error"?<p className={styles.status}>Today&apos;s schedule could not be loaded.</p>:today.length?<div className={styles.timeline}>{today.map(item=><div key={item.key} className={`${styles.slot} ${item.kind==="school"?styles.school:""} ${live.current?.key===item.key?styles.current:""}`}><time>{timeLabel(item.starts_at)}–{timeLabel(item.ends_at)}</time><div><strong>{item.title}</strong><small>{item.meta}</small></div></div>)}</div>:<p className={styles.status}>{schoolPhase==="weekend"?"No class schedule today. Check campus events and weekend sports instead.":"No school schedule is posted for today."}</p>}</section>,
  assignments:<section className={styles.panel} key="assignments"><div className={styles.heading}><div><p className="eyebrow">PLANNER</p><h3>Assignment priorities</h3></div><span>{priorities.length} OPEN</span></div>{priorities.length?<div className={styles.priorities}>{priorities.map(item=><article key={item.id}><div><strong>{item.title}</strong><small>{item.class_sections?.academic_courses?.code??"COURSE"} · {item.points} pts</small></div><time>{dueLabel(item.due_at)}</time></article>)}</div>:<p className={styles.status}>You&apos;re caught up — no open assignment priorities right now.</p>}</section>,
  grades:<section className={styles.panel} key="grades"><div className={styles.heading}><div><p className="eyebrow">ACADEMICS</p><h3>Grades snapshot</h3></div><span>{graded.length} GRADED</span></div><div className={styles.metric}><strong>{gradeAverage===null?"—":gradeAverage.toFixed(1)}</strong><span>{gradeAverage===null?"No graded submissions have been posted yet.":"Average across graded submissions"}</span><button type="button" onClick={onOpenCourses}>Open courses</button></div></section>,
  attendance:<section className={styles.panel} key="attendance"><div className={styles.heading}><div><p className="eyebrow">ATTENDANCE</p><h3>Attendance snapshot</h3></div><span>{attendance.length} RECORDS</span></div><div className={styles.metric}><strong>{attendanceRate===null?"—":`${attendanceRate}%`}</strong><span>{attendance.length?`${present} present record${present===1?"":"s"} in your visible history`:"Attendance will appear after faculty record your first school day."}</span></div></section>,
  events:<section className={styles.panel} key="events"><div className={styles.heading}><div><p className="eyebrow">UPCOMING</p><h3>School events</h3></div><span>{events.length}</span></div>{events.length?<div className={styles.priorities}>{events.slice(0,4).map(event=><article key={event.id}><div><strong>{event.title}</strong><small>{event.location??"Location TBA"}</small></div><time>{new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric"}).format(new Date(event.starts_at))}</time></article>)}</div>:<p className={styles.status}>No upcoming school events are posted. Your calendar is clear.</p>}</section>,
  clubs:<section className={styles.panel} key="clubs"><div className={styles.heading}><div><p className="eyebrow">{weekday===6||weekday===7?"WEEKEND ACTIVITIES":"AFTER SCHOOL"}</p><h3>{weekday===6||weekday===7?"Sports & activity schedule":"Club activity today"}</h3></div><span>{clubItems.length}</span></div>{clubItems.length?<div className={styles.priorities}>{clubItems.map(item=><article key={item.key}><div><strong>{item.title}</strong><small>{item.meta}</small></div><time>{timeLabel(item.starts_at)}</time></article>)}</div>:<p className={styles.status}>{weekday===2||weekday===3?"No joined club activity is scheduled today.":weekday===6||weekday===7?"No joined weekend activity is posted yet.":"Regular clubs meet Tuesday and Wednesday; check back on club days."}</p>}</section>,
  friends:<section className={styles.panel} key="friends"><div className={styles.heading}><div><p className="eyebrow">SOCIAL</p><h3>Friends</h3></div><span>{friendships.length}</span></div><div className={styles.metric}><strong>{friendships.length}</strong><span>{friendships.length?`Accepted Hanami friendship${friendships.length===1?"":"s"}`:"No accepted connections yet — the Community area can help you find classmates and friends."}</span></div></section>,
  study:<section className={styles.panel} key="study"><div className={styles.heading}><div><p className="eyebrow">STUDY</p><h3>Study progress</h3></div><span>{studyStreak?.current_streak??0} DAY STREAK</span></div><div className={styles.metric}><strong>{studyMinutes} min</strong><span>{studyStreak?`Current streak ${studyStreak.current_streak} · best ${studyStreak.longest_streak}`:"Complete a study session when you want to start an optional streak."}</span></div></section>
 };
 return <><div className={styles.customNotice}>Your saved <b>My Space → Dashboard Layout</b> still controls visibility and preference order. <b>School Day Priority</b> temporarily brings the most useful visible cards forward for {schoolPhase.replace("-"," ")}.</div><div className={styles.widgets}>{ordered.map(id=>widgets[id])}</div><section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">MY COURSES</p><h3>Enrolled classes</h3></div><button type="button" onClick={onOpenCourses}>View courses</button></div>{state==="loading"?<p className={styles.status}>Loading your classes…</p>:sections.length?<div className={styles.courses}>{sections.map(section=><button type="button" key={section.id} onClick={onOpenCourses}><span><strong>{section.academic_courses?.title??"Untitled course"}</strong><small>{section.academic_courses?.code??"COURSE"} · {section.section_code}</small></span><b>→</b></button>)}</div>:<p className={styles.status}>No classes are assigned yet. Your dashboard will populate automatically after enrollment.</p>}</section></>;
}
