"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./SupportTicketPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Ticket={id:string;category:string;subject:string;body:string;status:string;priority:string;tags:string[];created_at:string};
type Message={id:string;ticket_id:string;body:string;is_staff_reply:boolean;created_at:string};
export default function SupportTicketPanel({accessToken,characterId}:{accessToken:string;characterId:string}){
 const [tickets,setTickets]=useState<Ticket[]>([]),[messages,setMessages]=useState<Message[]>([]),[userId,setUserId]=useState(""),[category,setCategory]=useState("general"),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[reply,setReply]=useState<Record<string,string>>({}),[status,setStatus]=useState("Loading Support Center…");
 const load=useCallback(async()=>{try{const userResponse=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(accessToken)});if(!userResponse.ok)throw new Error();const user=await userResponse.json() as {id?:string};if(!user.id)throw new Error();setUserId(user.id);const ticketResponse=await fetch(`${SUPABASE_URL}/rest/v1/support_tickets?select=id,category,subject,body,status,priority,tags,created_at&requester_user_id=eq.${user.id}&order=created_at.desc`,{headers:headers(accessToken)});if(!ticketResponse.ok)throw new Error();const rows=await ticketResponse.json() as Ticket[];setTickets(rows);if(rows.length){const ids=`(${rows.map(t=>t.id).join(",")})`;const messageResponse=await fetch(`${SUPABASE_URL}/rest/v1/support_ticket_messages?select=id,ticket_id,body,is_staff_reply,created_at&ticket_id=in.${encodeURIComponent(ids)}&order=created_at.asc`,{headers:headers(accessToken)});setMessages(messageResponse.ok?await messageResponse.json() as Message[]:[]);}else setMessages([]);setStatus("Support Center ready.");}catch{setStatus("Support tickets could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function createTicket(event:FormEvent){event.preventDefault();if(!userId||subject.trim().length<2||body.trim().length<5)return;const response=await fetch(`${SUPABASE_URL}/rest/v1/support_tickets`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requester_user_id:userId,requester_character_id:characterId,category,subject:subject.trim(),body:body.trim(),status:"open",priority:"normal"})});if(response.ok){setSubject("");setBody("");setStatus("Support ticket submitted.");await load();}else setStatus("Support ticket could not be submitted.");}
 async function sendReply(ticketId:string){const text=(reply[ticketId]??"").trim();if(!text||!userId)return;const response=await fetch(`${SUPABASE_URL}/rest/v1/support_ticket_messages`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({ticket_id:ticketId,author_user_id:userId,body:text})});if(response.ok){setReply(current=>({...current,[ticketId]:""}));setStatus("Reply sent to Support.");await load();}else setStatus("Support reply could not be sent.");}
 const fmt=(v:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">HANAMI SUPPORT CENTER</p><h4>Support Tickets</h4></div><span>{status}</span></div><form className={styles.form} onSubmit={createTicket}><select value={category} onChange={e=>setCategory(e.target.value)}><option value="bug">Website bug</option><option value="account">Account</option><option value="portal">Portal access</option><option value="content">Content</option><option value="safety">Safety</option><option value="general">General</option></select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Ticket subject" maxLength={180}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Describe what you need help with" maxLength={5000}/><button type="submit">Submit support ticket</button></form><div className={styles.list}>{tickets.length?tickets.map(ticket=><article key={ticket.id}><div className={styles.meta}><strong>{ticket.priority.toUpperCase()} • {ticket.status.toUpperCase()}</strong><span>{ticket.category} • {fmt(ticket.created_at)}{ticket.tags.length?` • ${ticket.tags.join(", ")}`:""}</span></div><h5>{ticket.subject}</h5><p>{ticket.body}</p>{messages.filter(m=>m.ticket_id===ticket.id).map(m=><div key={m.id} className={m.is_staff_reply?styles.staffReply:styles.userReply}><strong>{m.is_staff_reply?"HANAMI SUPPORT":"YOU"}</strong><span>{fmt(m.created_at)}</span><p>{m.body}</p></div>)}{ticket.status!=="closed"&&<div className={styles.reply}><textarea value={reply[ticket.id]??""} onChange={e=>setReply(current=>({...current,[ticket.id]:e.target.value}))} placeholder="Reply to this ticket"/><button type="button" onClick={()=>sendReply(ticket.id)}>Send reply</button></div>}</article>):<p>No support tickets yet.</p>}</div></section>;
}
