import { useCallback,useEffect,useState } from 'react'
import { supabase } from '../lib/supabase'
import { useIdentity } from '../state/IdentityContext'

type Mode='chronicle'|'yearbook'|'lost-found'|'school-store'|'library'|'music-room'|'art-gallery'|'photo-booth'|'radio'|'suggestion-box'
type Props={mode:Mode;onMode:(mode:Mode)=>void;onClose:()=>void}
const nav:[Mode,string,string][]=[['chronicle','Hanami Chronicle','School newspaper'],['yearbook','Yearbook','2006 memories'],['lost-found','Lost & Found','Campus items'],['school-store','School Store','Boutique & supplies'],['library','Library','Study resources'],['music-room','Music Room','Music community'],['art-gallery','Art Gallery','Creative showcase'],['photo-booth','Photo Booth','Purikura cards'],['radio','School Radio','Shows & programs'],['suggestion-box','Suggestion Box','Send ideas']]

export function CampusLifePortal({mode,onMode,onClose}:Props){
 const {account,activeCharacter}=useIdentity();const client=supabase as any
 const [chronicle,setChronicle]=useState<any[]>([]);const [yearbook,setYearbook]=useState<any>(null);const [yearbookPublic,setYearbookPublic]=useState<any[]>([]);const [lost,setLost]=useState<any[]>([]);const [radio,setRadio]=useState<any[]>([]);const [events,setEvents]=useState<any[]>([]);const [photoCards,setPhotoCards]=useState<any[]>([]);const [suggestions,setSuggestions]=useState<any[]>([]);const [help,setHelp]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
 const [quote,setQuote]=useState('');const [memory,setMemory]=useState('');const [activities,setActivities]=useState('');const [lostName,setLostName]=useState('');const [lostDesc,setLostDesc]=useState('');const [lostLocation,setLostLocation]=useState('');const [lostStatus,setLostStatus]=useState('lost');const [caption,setCaption]=useState('');const [frameStyle,setFrameStyle]=useState('sakura');const [suggestionSubject,setSuggestionSubject]=useState('');const [suggestionBody,setSuggestionBody]=useState('');const [suggestionCategory,setSuggestionCategory]=useState('campus')
 const load=useCallback(async()=>{if(!client||!account||!activeCharacter)return;setLoading(true);setError(null);const [c,y,yp,l,r,e,p,s,h]=await Promise.all([client.from('chronicle_articles').select('*').eq('state','published').order('featured',{ascending:false}).order('published_school_date',{ascending:false}),client.from('yearbook_entries').select('*').eq('character_id',activeCharacter.id).eq('school_year',2006).maybeSingle(),client.from('yearbook_entries').select('*').eq('school_year',2006).eq('published',true).limit(40),client.from('campus_lost_found').select('*').order('created_at',{ascending:false}).limit(60),client.from('school_radio_posts').select('*').eq('state','published').order('school_date',{ascending:false}),client.from('campus_events').select('*').eq('status','published').order('school_date'),client.from('photo_booth_cards').select('*').eq('character_id',activeCharacter.id).order('created_at',{ascending:false}),client.from('campus_suggestions').select('*').eq('account_id',account.id).order('created_at',{ascending:false}),client.from('help_articles').select('*').eq('published',true).order('sort_order')]);setLoading(false);const first=[c,y,yp,l,r,e,p,s,h].find(x=>x.error);if(first?.error){setError(first.error.message);return}setChronicle(c.data||[]);setYearbook(y.data);setYearbookPublic(yp.data||[]);setLost(l.data||[]);setRadio(r.data||[]);setEvents(e.data||[]);setPhotoCards(p.data||[]);setSuggestions(s.data||[]);setHelp(h.data||[]);if(y.data){setQuote(y.data.quote||'');setMemory(y.data.memory||'');setActivities((y.data.activities||[]).join(', '))}},[client,account?.id,activeCharacter?.id])
 useEffect(()=>{void load()},[load])
 async function saveYearbook(e:React.FormEvent){e.preventDefault();if(!activeCharacter)return;const payload={character_id:activeCharacter.id,school_year:2006,quote:quote.trim(),memory:memory.trim(),activities:activities.split(',').map(v=>v.trim()).filter(Boolean),published:yearbook?.published||false,updated_at:new Date().toISOString()};const r=await client.from('yearbook_entries').upsert(payload,{onConflict:'character_id,school_year'});if(r.error)return setError(r.error.message);setNotice('Yearbook entry saved.');await load()}
 async function publishYearbook(){if(!activeCharacter)return;const r=await client.from('yearbook_entries').upsert({character_id:activeCharacter.id,school_year:2006,quote:quote.trim(),memory:memory.trim(),activities:activities.split(',').map(v=>v.trim()).filter(Boolean),published:true,updated_at:new Date().toISOString()},{onConflict:'character_id,school_year'});if(r.error)return setError(r.error.message);setNotice('Yearbook entry published.');await load()}
 async function addLost(e:React.FormEvent){e.preventDefault();if(!activeCharacter||!lostName.trim())return;const r=await client.from('campus_lost_found').insert({created_by_character_id:activeCharacter.id,item_name:lostName.trim(),description:lostDesc.trim(),location:lostLocation.trim(),status:lostStatus,school_date:'2006-09-09'});if(r.error)return setError(r.error.message);setLostName('');setLostDesc('');setLostLocation('');setNotice('Lost & Found post added.');await load()}
 async function createPhoto(e:React.FormEvent){e.preventDefault();if(!activeCharacter)return;const r=await client.from('photo_booth_cards').insert({character_id:activeCharacter.id,frame_style:frameStyle,caption:caption.trim(),sticker_payload:[]});if(r.error)return setError(r.error.message);setCaption('');setNotice('Photo booth card saved.');await load()}
 async function submitSuggestion(e:React.FormEvent){e.preventDefault();if(!account||!activeCharacter||!suggestionSubject.trim()||!suggestionBody.trim())return;const r=await client.from('campus_suggestions').insert({account_id:account.id,character_id:activeCharacter.id,category:suggestionCategory,subject:suggestionSubject.trim(),body:suggestionBody.trim(),anonymous_to_community:true});if(r.error)return setError(r.error.message);setSuggestionSubject('');setSuggestionBody('');setNotice('Suggestion sent to the school office.');await load()}
 const name=activeCharacter?.display_name||[activeCharacter?.first_name,activeCharacter?.last_name].filter(Boolean).join(' ')||'Hanami Student'
 return <section className="portal-window campus-life-portal"><header className="portal-titlebar"><div><span>CAMPUS LIFE · HANAMI HIGH</span><strong>{name}</strong></div><button onClick={onClose}>×</button></header><div className="portal-layout"><aside className="portal-nav"><div className="portal-id-mini"><div className="portal-mini-avatar">✿</div><strong>Campus Life</strong><span>After school · 2006</span><small>Clubs, media & student services</small></div>{nav.map(([id,label,desc])=><button key={id} className={mode===id?'active':''} onClick={()=>onMode(id)}><b>{label}</b><small>{desc}</small></button>)}</aside><main className="portal-main">{error&&<div className="identity-notice error">{error}</div>}{notice&&<div className="identity-notice success">{notice}</div>}{loading?<div className="portal-loading">Opening Campus Life…</div>:<>
 {mode==='chronicle'&&<><Heading e="HANAMI CHRONICLE" t="The school newspaper" p="Published campus stories, event coverage, club features, interviews, and school-life reporting."/><div className="chronicle-grid">{chronicle.map(a=><article key={a.id} className={a.featured?'featured':''}><span>{a.category}{a.featured?' · FEATURED':''}</span><h2>{a.title}</h2><p className="dek">{a.dek}</p><p>{a.body}</p><small>{a.published_school_date||'Hanami High · 2006'}</small></article>)}{!chronicle.length&&<Empty text="The Chronicle has not published an issue yet."/>}</div></>}
 {mode==='yearbook'&&<><Heading e="YEARBOOK 2006" t="Leave your mark on the school year" p="Build a character-specific yearbook entry with a quote, activities, and one memory. Publish when you are ready for other members to see it."/><div className="portal-columns"><Panel title="My yearbook entry"><form className="portal-form multi" onSubmit={saveYearbook}><input value={quote} onChange={e=>setQuote(e.target.value)} maxLength={220} placeholder="Yearbook quote"/><input value={activities} onChange={e=>setActivities(e.target.value)} placeholder="Activities, comma separated"/><textarea value={memory} onChange={e=>setMemory(e.target.value)} placeholder="Favorite memory from Hanami High"/><div className="form-actions"><button>Save draft</button><button type="button" onClick={()=>void publishYearbook()}>Publish</button></div></form></Panel><Panel title="Published classmates">{yearbookPublic.map(y=><article className="yearbook-card" key={y.id}><strong>{y.quote||'Hanami High · 2006'}</strong><p>{y.memory||'No memory written.'}</p><small>{(y.activities||[]).join(' · ')}</small></article>)}{!yearbookPublic.length&&<Empty text="No yearbook entries are public yet."/>}</Panel></div></>}
 {mode==='lost-found'&&<><Heading e="LOST & FOUND" t="Campus items board" p="Post an item you lost or found and update it when it is returned."/><form className="portal-form" onSubmit={addLost}><select value={lostStatus} onChange={e=>setLostStatus(e.target.value)}><option value="lost">Lost</option><option value="found">Found</option></select><input value={lostName} onChange={e=>setLostName(e.target.value)} placeholder="Item name"/><input value={lostLocation} onChange={e=>setLostLocation(e.target.value)} placeholder="Location"/><input value={lostDesc} onChange={e=>setLostDesc(e.target.value)} placeholder="Description"/><button>Post</button></form><div className="lost-grid">{lost.map(i=><article key={i.id} className={`status-${i.status}`}><span>{i.status}</span><h3>{i.item_name}</h3><p>{i.description}</p><small>{i.location||'Location unknown'} · {i.school_date||'2006'}</small></article>)}</div></>}
 {mode==='school-store'&&<><Heading e="SCHOOL STORE" t="Supplies, collectibles & Hanami goods" p="The Hanami Boutique is the account-owned collectible store. School-store utilities can expand here without creating a second economy."/><div className="campus-feature-hero"><div><span>HANAMI BOUTIQUE</span><h2>Frames, effects, nameplates, stickers, fonts & more</h2><p>Browse permanent and seasonal collections, including matching Halloween 2006 sets. Cosmetic ownership is account-wide and equipment is per character.</p><a href="#/boutique/featured">Open Hanami Boutique →</a></div></div></>}
 {mode==='library'&&<><Heading e="HANAMI LIBRARY" t="Study resources & quiet campus tools" p="A calm study hub that points students toward classes, assignments, Help Center material, and study groups rather than creating a campus directory."/><div className="portal-card-grid"><article><span>ACADEMICS</span><h3>Course resources</h3><p>Open your classes for teacher-posted resources, assignments, submissions, and feedback.</p><a href="#/academics/classes">My classes →</a></article><article><span>STUDY</span><h3>Study groups</h3><p>Create private groups around a subject or upcoming assessment.</p><a href="#/portal/student/study-groups">Study groups →</a></article>{help.slice(0,4).map(a=><article key={a.id}><span>{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p></article>)}</div></>}
 {mode==='music-room'&&<><Heading e="MUSIC ROOM" t="Practice, performance & after-school sound" p="A roleplay-facing music hub for school performances, music-club activity, radio programs, and upcoming events."/><div className="portal-columns"><Panel title="Music & performance events">{events.filter(e=>/music|concert|performance|festival/i.test(`${e.title} ${e.description} ${e.event_type}`)).map(e=><article className="portal-list-row" key={e.id}><b>{e.school_date}</b><strong>{e.title}</strong><small>{e.location}</small></article>)}<EmptyIf rows={events.filter(e=>/music|concert|performance|festival/i.test(`${e.title} ${e.description} ${e.event_type}`))} text="No music events are currently posted."/></Panel><Panel title="Hanami Radio">{radio.slice(0,8).map(r=><article className="portal-list-row" key={r.id}><b>{r.show_name}</b><strong>{r.title}</strong><small>{r.school_date||'2006'} {r.starts_at?`· ${String(r.starts_at).slice(0,5)}`:''}</small></article>)}<EmptyIf rows={radio} text="No radio programs are posted."/></Panel></div></>}
 {mode==='art-gallery'&&<><Heading e="ART GALLERY" t="Student creativity on display" p="A campus showcase for art-focused events, creative projects, profiles, themes, and community work."/><div className="portal-card-grid"><article><span>PROFILE CREATORS</span><h3>Creator Marketplace</h3><p>Browse community-made profile themes and reusable components with creator attribution.</p><a href="#/hanami-plus/marketplace">Browse themes →</a></article><article><span>CREATIVE EVENTS</span><h3>Design contests</h3><p>Hanami+ creative contests and challenges can feature published themes without making core social access premium.</p><a href="#/hanami-plus/creator-contests">Creative contests →</a></article>{events.filter(e=>/art|gallery|creative|design|festival/i.test(`${e.title} ${e.description} ${e.event_type}`)).slice(0,6).map(e=><article key={e.id}><span>{e.school_date}</span><h3>{e.title}</h3><p>{e.description}</p></article>)}</div></>}
 {mode==='photo-booth'&&<><Heading e="PHOTO BOOTH" t="Make a little Hanami photo card" p="Save purikura-inspired character cards with a decorative frame choice and caption. Sticker placement can build on the existing Decoration Library."/><div className="portal-columns"><Panel title="New card"><form className="portal-form multi" onSubmit={createPhoto}><select value={frameStyle} onChange={e=>setFrameStyle(e.target.value)}><option value="sakura">Sakura</option><option value="notebook">Notebook</option><option value="pixel">Pixel</option><option value="celestial">Celestial</option><option value="halloween">Halloween 2006</option></select><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Caption"/><button>Save photo card</button></form><PhotoCard name={name} handle={String(activeCharacter?.handle||'')} style={frameStyle} caption={caption}/></Panel><Panel title="Saved cards">{photoCards.map(c=><PhotoCard key={c.id} name={name} handle={String(activeCharacter?.handle||'')} style={c.frame_style} caption={c.caption}/>)}</Panel></div></>}
 {mode==='radio'&&<><Heading e="SCHOOL RADIO" t="Hanami on the air" p="Scheduled shows, music blocks, announcements, and student-hosted programming."/><div className="radio-list">{radio.map(r=><article key={r.id}><div className="radio-dial">◉</div><div><span>{r.show_name}</span><h3>{r.title}</h3><p>{r.description}</p><small>{r.school_date||'2006'} {r.starts_at?`· ${String(r.starts_at).slice(0,5)}`:''}</small></div></article>)}{!radio.length&&<Empty text="The radio schedule is quiet right now."/>}</div></>}
 {mode==='suggestion-box'&&<><Heading e="SUGGESTION BOX" t="Send an idea to the school office" p="Suggestions are private to you and authorized school administrators. Community anonymity does not hide the account from authorized moderation/audit systems."/><form className="portal-form multi" onSubmit={submitSuggestion}><select value={suggestionCategory} onChange={e=>setSuggestionCategory(e.target.value)}><option value="campus">Campus</option><option value="academics">Academics</option><option value="events">Events</option><option value="website">Website</option><option value="other">Other</option></select><input value={suggestionSubject} onChange={e=>setSuggestionSubject(e.target.value)} placeholder="Subject"/><textarea value={suggestionBody} onChange={e=>setSuggestionBody(e.target.value)} placeholder="Your suggestion"/><button>Submit suggestion</button></form><div className="portal-card-grid">{suggestions.map(s=><article key={s.id}><span>{s.state} · {s.category}</span><h3>{s.subject}</h3><p>{s.body}</p><small>{new Date(s.created_at).toLocaleDateString()}</small></article>)}</div></>}
 </>}</main></div></section>
}

function PhotoCard({name,handle,style,caption}:{name:string;handle:string;style:string;caption:string}){return <div className={`photo-card photo-${style}`}><div className="photo-card-image"><span>花</span><b>✦</b><i>♡</i></div><strong>{name}</strong><span>@{handle}</span><p>{caption||'Hanami High · 2006'}</p></div>}
function Heading({e,t,p}:{e:string;t:string;p:string}){return <header className="portal-page-heading"><span className="eyebrow">{e}</span><h1>{t}</h1><p>{p}</p></header>}
function Panel({title,children}:{title:string;children:any}){return <section className="portal-panel"><header><strong>{title}</strong></header><div>{children}</div></section>}
function Empty({text}:{text:string}){return <p className="empty-copy">{text}</p>}
function EmptyIf({rows,text}:{rows:any[];text:string}){return rows.length?null:<Empty text={text}/>}
