import { useCallback,useEffect,useMemo,useState } from 'react'
import { supabase } from '../lib/supabase'
import { useIdentity } from '../state/IdentityContext'

type Mode='today'|'gradebook'|'seating'|'lesson-plans'|'templates'|'office-hours'|'advisor'
type Props={mode:Mode;onMode:(mode:Mode)=>void;onClose:()=>void}
type Snapshot={sections:any[];assignments:any[];office_hours:any[];lesson_plans:any[];templates:any[];ungraded_count:number;advisor_homeroom:any|null}
const empty:Snapshot={sections:[],assignments:[],office_hours:[],lesson_plans:[],templates:[],ungraded_count:0,advisor_homeroom:null}
const nav:[Mode,string,string][]=[['today','Teacher Home','Today & workload'],['gradebook','Gradebook','Students × assignments'],['seating','Seating Charts','Drag-style seat grid'],['lesson-plans','Lesson Planner','Objectives & notes'],['templates','Templates','Reusable assessments'],['office-hours','Office Hours','Student help times'],['advisor','Advisor Dashboard','Homeroom responsibilities']]
const weekdays=['','Monday','Tuesday','Wednesday','Thursday','Friday']

export function FacultyPortal({mode,onMode,onClose}:Props){
 const {activeCharacter}=useIdentity();const client=supabase as any
 const [data,setData]=useState<Snapshot>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
 const [sectionId,setSectionId]=useState('');const [roster,setRoster]=useState<any[]>([]);const [sectionAssignments,setSectionAssignments]=useState<any[]>([]);const [gradeRows,setGradeRows]=useState<any[]>([]);const [seats,setSeats]=useState<Record<string,{x:number;y:number}>>({})
 const [planTitle,setPlanTitle]=useState('');const [planDate,setPlanDate]=useState('2006-09-09');const [planObjectives,setPlanObjectives]=useState('');const [templateTitle,setTemplateTitle]=useState('');const [templateKind,setTemplateKind]=useState('homework');const [officeDay,setOfficeDay]=useState('1');const [officeStart,setOfficeStart]=useState('15:50');const [officeEnd,setOfficeEnd]=useState('16:30');const [officeLocation,setOfficeLocation]=useState('Faculty Office')
 const load=useCallback(async()=>{if(!client||!activeCharacter)return;setLoading(true);setError(null);const r=await client.rpc('faculty_portal_snapshot');setLoading(false);if(r.error){setError(r.error.message);return}const next={...empty,...(r.data||{})};setData(next);if(!sectionId&&next.sections[0])setSectionId(next.sections[0].id)},[client,activeCharacter?.id,sectionId])
 useEffect(()=>{void load()},[activeCharacter?.id])
 const loadClass=useCallback(async()=>{if(!sectionId||!client)return;const [enrollments,assignments,seating]=await Promise.all([client.from('academic_enrollments').select('student_character_id,status').eq('section_id',sectionId).eq('status','enrolled'),client.from('academic_assignments').select('id,title,points_possible,due_school_date,state').eq('section_id',sectionId).order('due_school_date'),client.from('class_seating_assignments').select('*').eq('section_id',sectionId)]);if(enrollments.error||assignments.error||seating.error){setError(enrollments.error?.message||assignments.error?.message||seating.error?.message);return}const ids=(enrollments.data||[]).map((e:any)=>e.student_character_id);const chars=ids.length?await client.from('characters').select('id,display_name,first_name,last_name,handle').in('id',ids):{data:[],error:null};if(chars.error){setError(chars.error.message);return}const as=assignments.data||[];const grades=as.length&&ids.length?await client.from('academic_grades').select('*').in('assignment_id',as.map((a:any)=>a.id)).in('student_character_id',ids):{data:[],error:null};if(grades.error){setError(grades.error.message);return}setRoster(chars.data||[]);setSectionAssignments(as);setGradeRows(grades.data||[]);setSeats(Object.fromEntries((seating.data||[]).map((s:any)=>[s.student_character_id,{x:s.seat_x,y:s.seat_y}])));},[client,sectionId])
 useEffect(()=>{if(mode==='gradebook'||mode==='seating')void loadClass()},[mode,loadClass])
 const name=activeCharacter?.display_name||[activeCharacter?.first_name,activeCharacter?.last_name].filter(Boolean).join(' ')||'Hanami Faculty'
 const selectedSection=data.sections.find(s=>s.id===sectionId)
 const gradeMap=useMemo(()=>new Map(gradeRows.map(g=>[`${g.student_character_id}:${g.assignment_id}`,g])),[gradeRows])
 async function saveGrade(studentId:string,assignment:any,value:string){const n=value.trim()===''?null:Number(value);if(n!==null&&!Number.isFinite(n))return;const existing=gradeMap.get(`${studentId}:${assignment.id}`);const payload={assignment_id:assignment.id,student_character_id:studentId,points_earned:n,graded_by_character_id:activeCharacter?.id,graded_at:new Date().toISOString()};const r=existing?await client.from('academic_grades').update(payload).eq('assignment_id',assignment.id).eq('student_character_id',studentId):await client.from('academic_grades').insert(payload);if(r.error)return setError(r.error.message);setNotice('Gradebook saved.');await loadClass()}
 async function assignSeat(studentId:string,x:number,y:number){if(!activeCharacter||!sectionId)return;const r=await client.from('class_seating_assignments').upsert({section_id:sectionId,student_character_id:studentId,assigned_by_character_id:activeCharacter.id,seat_x:x,seat_y:y,updated_at:new Date().toISOString()});if(r.error)return setError(r.error.message);setSeats(s=>({...s,[studentId]:{x,y}}))}
 async function addPlan(e:React.FormEvent){e.preventDefault();if(!activeCharacter||!planTitle.trim())return;const r=await client.from('faculty_lesson_plans').insert({faculty_character_id:activeCharacter.id,section_id:sectionId||null,school_date:planDate,title:planTitle.trim(),objectives:planObjectives});if(r.error)return setError(r.error.message);setPlanTitle('');setPlanObjectives('');setNotice('Lesson plan saved.');await load()}
 async function addTemplate(e:React.FormEvent){e.preventDefault();if(!activeCharacter||!templateTitle.trim())return;const r=await client.from('faculty_assignment_templates').insert({faculty_character_id:activeCharacter.id,template_kind:templateKind,title:templateTitle.trim()});if(r.error)return setError(r.error.message);setTemplateTitle('');setNotice('Assignment template saved.');await load()}
 async function addOffice(e:React.FormEvent){e.preventDefault();if(!activeCharacter)return;const r=await client.from('faculty_office_hours').insert({faculty_character_id:activeCharacter.id,weekday:Number(officeDay),starts_at:officeStart,ends_at:officeEnd,location:officeLocation,is_active:true});if(r.error)return setError(r.error.message);setNotice('Office hours published.');await load()}
 return <section className="portal-window portal-faculty"><header className="portal-titlebar"><div><span>FACULTY PORTAL · HANAMI HIGH</span><strong>{name}</strong></div><button onClick={onClose}>×</button></header><div className="portal-layout"><aside className="portal-nav"><div className="portal-id-mini"><div className="portal-mini-avatar">教</div><strong>{name}</strong><span>@{activeCharacter?.handle}</span><small>Faculty / Teacher</small></div>{nav.map(([id,label,desc])=><button key={id} className={mode===id?'active':''} onClick={()=>onMode(id)}><b>{label}</b><small>{desc}</small></button>)}</aside><main className="portal-main">{error&&<div className="identity-notice error">{error}</div>}{notice&&<div className="identity-notice success">{notice}</div>}{loading?<div className="portal-loading">Opening faculty desk…</div>:<>
 {mode==='today'&&<><Heading e="TEACHER HOME" t="Your teaching day" p="Classes, ungraded work, lesson planning, office hours, and homeroom advising in one desk."/><div className="portal-stat-grid"><Stat label="Assigned classes" value={String(data.sections.length)} detail="Active sections"/><Stat label="Ungraded" value={String(data.ungraded_count||0)} detail="Submitted work needing grades"/><Stat label="Lesson plans" value={String(data.lesson_plans.length)} detail="Saved plans"/><Stat label="Advisor" value={data.advisor_homeroom?.code||'—'} detail={data.advisor_homeroom?'Assigned homeroom':'No homeroom assigned'}/></div><div className="portal-columns"><Panel title="Classes">{data.sections.map(s=><a className="portal-list-row" href={`#/academics/classes/${s.id}`} key={s.id}><b>{s.course_code}</b><strong>{s.course_name}</strong><small>{s.section_code} · {s.room||'Room TBD'}</small></a>)}{!data.sections.length&&<Empty text="No active class sections are assigned to this faculty character."/>}</Panel><Panel title="Next planning items">{data.lesson_plans.slice(0,8).map(p=><div className="portal-list-row" key={p.id}><b>{p.school_date}</b><strong>{p.title}</strong><small>{p.objectives||'No objectives written yet.'}</small></div>)}{!data.lesson_plans.length&&<Empty text="No lesson plans saved yet."/>}</Panel></div></>}
 {mode==='gradebook'&&<><Heading e="GRADEBOOK" t="Spreadsheet-style grading" p="Select a class, review students against assignments, and save grades without leaving the faculty portal."/><ClassPicker data={data} value={sectionId} setValue={setSectionId}/><div className="gradebook-wrap"><table className="gradebook-table"><thead><tr><th>Student</th>{sectionAssignments.map(a=><th key={a.id}><span>{a.title}</span><small>{a.points_possible??'—'} pts</small></th>)}</tr></thead><tbody>{roster.map(student=><tr key={student.id}><th>{student.display_name||`${student.first_name||''} ${student.last_name||''}`.trim()}<small>@{student.handle}</small></th>{sectionAssignments.map(a=>{const g=gradeMap.get(`${student.id}:${a.id}`);return <td key={a.id}><input aria-label={`${student.display_name} ${a.title}`} defaultValue={g?.points_earned??''} onBlur={e=>void saveGrade(student.id,a,e.target.value)}/></td>})}</tr>)}</tbody></table>{!roster.length&&<Empty text="This class has no enrolled students yet."/>}</div></>}
 {mode==='seating'&&<><Heading e="SEATING CHART" t={selectedSection?`${selectedSection.course_code} · ${selectedSection.section_code}`:'Classroom seating'} p="Choose a student, then click a desk to place them. Seat positions save per class."/><ClassPicker data={data} value={sectionId} setValue={setSectionId}/><SeatingBoard roster={roster} seats={seats} onAssign={assignSeat}/></>}
 {mode==='lesson-plans'&&<><Heading e="LESSON PLANNER" t="Prepare the school day" p="Save objectives, materials, notes, homework, and private teacher notes by date and class."/><form className="portal-form multi" onSubmit={addPlan}><select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">General / no class</option>{data.sections.map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.section_code}</option>)}</select><input type="date" value={planDate} onChange={e=>setPlanDate(e.target.value)}/><input value={planTitle} onChange={e=>setPlanTitle(e.target.value)} placeholder="Lesson title"/><textarea value={planObjectives} onChange={e=>setPlanObjectives(e.target.value)} placeholder="Objectives"/><button>Save lesson plan</button></form><div className="portal-card-grid">{data.lesson_plans.map(p=><article key={p.id}><span>{p.school_date}</span><h3>{p.title}</h3><p>{p.objectives||'No objectives entered.'}</p></article>)}</div></>}
 {mode==='templates'&&<><Heading e="ASSIGNMENT TEMPLATES" t="Reusable assessment starters" p="Keep reusable homework, quiz, exam, essay, project, presentation, participation, and lab templates."/><form className="portal-form" onSubmit={addTemplate}><select value={templateKind} onChange={e=>setTemplateKind(e.target.value)}>{['homework','quiz','exam','essay','project','presentation','participation','lab'].map(k=><option key={k}>{k}</option>)}</select><input value={templateTitle} onChange={e=>setTemplateTitle(e.target.value)} placeholder="Template title"/><button>Save template</button></form><div className="portal-card-grid">{data.templates.map(t=><article key={t.id}><span>{t.template_kind}</span><h3>{t.title}</h3><p>{t.description||'Reusable faculty template.'}</p><small>{t.default_points?`${t.default_points} points`:''}</small></article>)}</div></>}
 {mode==='office-hours'&&<><Heading e="OFFICE HOURS" t="Publish help availability" p="Let students know when and where they can find you for tutoring, questions, or assignment help."/><form className="portal-form" onSubmit={addOffice}><select value={officeDay} onChange={e=>setOfficeDay(e.target.value)}>{[1,2,3,4,5].map(d=><option value={d} key={d}>{weekdays[d]}</option>)}</select><input type="time" value={officeStart} onChange={e=>setOfficeStart(e.target.value)}/><input type="time" value={officeEnd} onChange={e=>setOfficeEnd(e.target.value)}/><input value={officeLocation} onChange={e=>setOfficeLocation(e.target.value)} placeholder="Location"/><button>Publish</button></form><div className="portal-card-grid">{data.office_hours.map(o=><article key={o.id}><span>{weekdays[o.weekday]}</span><h3>{String(o.starts_at).slice(0,5)}–{String(o.ends_at).slice(0,5)}</h3><p>{o.location}</p><small>{o.notes}</small></article>)}{!data.office_hours.length&&<Empty text="No office hours published yet."/>}</div></>}
 {mode==='advisor'&&<><Heading e="ADVISOR DASHBOARD" t={data.advisor_homeroom?.code||'Homeroom advisor'} p="Homeroom announcements, roster access, student progress signals, and daily responsibilities belong here."/>{data.advisor_homeroom?<div className="homeroom-card"><span>FACULTY ADVISORY</span><h2>{data.advisor_homeroom.code}</h2><p>{data.advisor_homeroom.description||'Mixed-year Hanami homeroom.'}</p><dl><div><dt>Room</dt><dd>{data.advisor_homeroom.room_label}</dd></div><div><dt>Advisor</dt><dd>{name}</dd></div></dl><a href={`#/academics/homeroom/${data.advisor_homeroom.id}`}>Open homeroom room →</a></div>:<Empty text="This faculty character is not assigned as a homeroom advisor."/>}</>}
 }</>}</main></div></section>
}

function ClassPicker({data,value,setValue}:{data:Snapshot;value:string;setValue:(v:string)=>void}){return <label className="class-picker"><span>Class</span><select value={value} onChange={e=>setValue(e.target.value)}>{data.sections.map(s=><option key={s.id} value={s.id}>{s.course_code} · {s.section_code} · {s.course_name}</option>)}</select></label>}
function SeatingBoard({roster,seats,onAssign}:{roster:any[];seats:Record<string,{x:number;y:number}>;onAssign:(studentId:string,x:number,y:number)=>void}){const [selected,setSelected]=useState(roster[0]?.id||'');useEffect(()=>{if(!selected&&roster[0])setSelected(roster[0].id)},[roster,selected]);const occupied=new Map(Object.entries(seats).map(([id,pos])=>[`${pos.x}:${pos.y}`,id]));return <div className="seating-layout"><aside><strong>Students</strong>{roster.map(s=><button className={selected===s.id?'active':''} key={s.id} onClick={()=>setSelected(s.id)}>{s.display_name||s.handle}<small>{seats[s.id]?`Seat ${seats[s.id].x+1}-${seats[s.id].y+1}`:'Unseated'}</small></button>)}</aside><div className="seat-board"><div className="teacher-desk">TEACHER / BOARD</div>{Array.from({length:20},(_,i)=>{const x=i%5,y=Math.floor(i/5);const studentId=occupied.get(`${x}:${y}`);const student=roster.find(s=>s.id===studentId);return <button key={i} className={student?'occupied':''} onClick={()=>selected&&onAssign(selected,x,y)}><b>{x+1}-{y+1}</b><span>{student?.display_name||student?.handle||'Empty'}</span></button>})}</div></div>}
function Heading({e,t,p}:{e:string;t:string;p:string}){return <header className="portal-page-heading"><span className="eyebrow">{e}</span><h1>{t}</h1><p>{p}</p></header>}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <article className="portal-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Panel({title,children}:{title:string;children:any}){return <section className="portal-panel"><header><strong>{title}</strong></header><div>{children}</div></section>}
function Empty({text}:{text:string}){return <p className="empty-copy">{text}</p>}
