import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type GuestSection='home'|'about'|'academics'|'student-life'|'community'|'boutique'|'hanami-plus'|'enrollment'|'search'
type Snapshot={announcements:any[];events:any[];chronicle:any[];profiles:any[];boutique:any[];radio:any[];help:any[]}
const empty:Snapshot={announcements:[],events:[],chronicle:[],profiles:[],boutique:[],radio:[],help:[]}
const nav:[GuestSection,string][]=[['home','Home'],['about','About Hanami'],['academics','Academics'],['student-life','Student Life'],['community','Community'],['boutique','Boutique Preview'],['hanami-plus','Hanami+'],['enrollment','Enrollment'],['search','Search']]

function sectionFromHash():GuestSection{const part=window.location.hash.replace(/^#\/guest\/?/,'').split('/')[0] as GuestSection;return nav.some(([id])=>id===part)?part:'home'}
function go(section:GuestSection){window.location.hash=`#/guest/${section}`}

export function GuestView(){
 const [section,setSection]=useState<GuestSection>(sectionFromHash)
 const [data,setData]=useState<Snapshot>(empty)
 const [loading,setLoading]=useState(true)
 const [error,setError]=useState<string|null>(null)
 const [query,setQuery]=useState('')
 useEffect(()=>{const sync=()=>setSection(sectionFromHash());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[])
 useEffect(()=>{const client=supabase as any;if(!client)return;let alive=true;(async()=>{setLoading(true);const result=await client.rpc('guest_public_snapshot');if(!alive)return;setLoading(false);if(result.error){setError(result.error.message);return}setData({...empty,...(result.data||{})})})();return()=>{alive=false}},[])
 const searchResults=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];const rows=[...data.announcements.map(x=>({kind:'Announcement',title:x.title,detail:x.body})),...data.events.map(x=>({kind:'Event',title:x.title,detail:x.description})),...data.chronicle.map(x=>({kind:'Chronicle',title:x.title,detail:x.dek})),...data.profiles.map(x=>({kind:'Public Profile',title:x.display_name,detail:`@${x.handle} · ${x.school_role}`})),...data.boutique.map(x=>({kind:'Boutique',title:x.name,detail:`${x.collection_name||''} ${x.description||''}`})),...data.help.map(x=>({kind:'Help',title:x.title,detail:x.summary}))];return rows.filter(x=>`${x.title} ${x.detail}`.toLowerCase().includes(q)).slice(0,30)},[data,query])

 return <main className="guest-view-shell">
  <header className="guest-topbar"><div className="guest-brand"><span className="guest-mark">花</span><div><strong>Hanami High</strong><small>Public School Network · Tokyo · 2006</small></div></div><div className="guest-actions"><span className="guest-stamp">VISITOR / GUEST</span><button onClick={()=>{window.location.hash='';window.location.reload()}}>Sign In</button><button className="primary" onClick={()=>go('enrollment')}>Apply</button></div></header>
  <div className="guest-layout"><aside><div className="guest-sidebar-title"><span>PUBLIC LINKS</span><strong>Explore Hanami</strong></div>{nav.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>go(id)}>{label}</button>)}<div className="guest-note"><strong>Guest privacy</strong><p>Guests can only see public school information, published community content, public profiles, and Boutique previews. Messages, grades, attendance, private profiles, staff tools, and account information stay hidden.</p></div></aside>
  <section className="guest-content">{loading&&<div className="portal-loading">Opening the public school network…</div>}{error&&<div className="identity-notice error">{error}</div>}
   {!loading&&section==='home'&&<><section className="guest-hero"><span className="eyebrow">WELCOME TO HANAMI HIGH</span><h1>A slice-of-life school network set in 2006.</h1><p>Browse the public side of Hanami High, learn how the school works, see public community activity, preview customization, and decide whether you want to enroll.</p><div><button className="primary" onClick={()=>go('about')}>Learn about Hanami</button><button onClick={()=>go('student-life')}>See student life</button></div></section><div className="guest-grid three"><article><span>ROLEPLAY DATE</span><strong>School Year 2006</strong><p>Hanami’s in-universe calendar follows real days while remaining in 2006.</p></article><article><span>CHARACTERS</span><strong>Up to 2 per member</strong><p>One Discord member has one Hanami account with up to two roleplay characters.</p></article><article><span>HANAMI+</span><strong>Optional customization</strong><p>Core school, social, academic, and messaging features do not require Hanami+.</p></article></div><GuestCards title="Public announcements" rows={data.announcements} empty="No public announcements are posted right now."/><GuestCards title="Upcoming public events" rows={data.events} empty="No public events are published right now."/></>}
   {!loading&&section==='about'&&<><PortalHeading eyebrow="ABOUT HANAMI" title="Hanami High School" text="A Japanese high-school slice-of-life roleplay community with a connected school intranet, character profiles, academics, social spaces, and creative customization."/><div className="guest-grid two"><Info title="School identity">Hanami High opened in-universe on April 7, 2006. The network uses Tokyo time and a school-year calendar designed around daily roleplay.</Info><Info title="Community model">The experience combines structured school systems with character-driven social roleplay. Students have homerooms, classes, clubs, messages, profiles, and campus events.</Info><Info title="Accounts">Discord is the identity provider. One member has one Hanami account and may create at most two characters.</Info><Info title="School access">Accepted students begin as New Students and remain in that role until the Owner manually promotes them.</Info></div><section className="guest-faq"><h2>Frequently asked questions</h2>{[['Do I need Hanami+?','No. Hanami+ is for optional prestige, customization, and convenience.'],['Can guests see private profiles?','No. Guest View only displays profiles explicitly published as public.'],['Are emails used?','No. Hanami communication is handled through the website and Discord-linked identity rather than personal email.'],['Can I have more than two characters?','No. Each member is limited to two characters.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></>}
   {!loading&&section==='academics'&&<><PortalHeading eyebrow="ACADEMICS" title="A real school-day structure" text="Hanami uses six class periods plus shared school-day blocks such as morning homeroom, lunch, cleaning, afternoon homeroom, and club activities."/><div className="guest-grid three"><Info title="Core subjects">English, Mathematics, General Science, Modern Japanese & World History, and rotating physical education/elective periods.</Info><Info title="Homerooms">First- and second-year students share mixed homerooms. Homeroom is both an academic organization and a community space.</Info><Info title="Student records">Members can see their own assignments, submissions, grades, attendance, and teacher feedback after enrollment.</Info></div><div className="guest-day"><h2>Example school day</h2>{[['8:30','Arrival'],['8:35','Shoe Change'],['8:40','Morning Homeroom · Asa-no-kai'],['8:50','Period 1'],['9:50','Period 2'],['10:50','Period 3'],['11:50','Period 4'],['12:40','Lunch'],['1:25','Period 5'],['2:25','Period 6'],['3:15','Classroom Cleaning · Soji'],['3:35','Afternoon Homeroom · Kaeri-no-kai'],['4:00','Club Activities · Bukatsu']].map(([time,label])=><div key={time}><time>{time}</time><strong>{label}</strong></div>)}</div></>}
   {!loading&&section==='student-life'&&<><PortalHeading eyebrow="STUDENT LIFE" title="Life outside class matters too." text="Clubs, events, student council, the Chronicle, Yearbook, radio, photo booth, creative profiles, and school traditions give characters reasons to exist outside class periods."/><div className="guest-grid three"><Info title="Clubs & organizations">Students can join clubs, participate in events, and use club spaces after school.</Info><Info title="Hanami Chronicle">The school newspaper publishes public campus stories and selected community coverage.</Info><Info title="Yearbook">Characters can build a 2006 yearbook entry with a quote, activities, memory, and photo.</Info><Info title="School Radio">Public radio listings can announce scheduled shows, music blocks, and student-hosted programming.</Info><Info title="Seasonal events">Owner-managed events can connect homepage themes, announcements, Boutique collections, achievements, and school activities.</Info><Info title="Photo Booth">Members can create decorative purikura-style school photo cards from their character identity.</Info></div><GuestCards title="School radio" rows={data.radio} empty="No radio programs are currently posted."/></>}
   {!loading&&section==='community'&&<><PortalHeading eyebrow="COMMUNITY" title="See the public side of campus." text="Guest View only exposes content members or staff deliberately publish to the public network."/><GuestCards title="Hanami Chronicle" rows={data.chronicle} empty="The Chronicle has no published stories yet."/><section className="guest-profile-grid"><h2>Public character profiles</h2><div>{data.profiles.length?data.profiles.map(p=><article key={p.character_id}><div className="guest-avatar">{p.avatar_path?<img src={p.avatar_path} alt=""/>:<span>{String(p.display_name||'?')[0]}</span>}</div><strong>{p.display_name}</strong><span>@{p.handle}</span><small>{p.school_role}</small><p>{p.custom_status||p.bio||'Public Hanami profile'}</p></article>):<p className="empty-copy">No public profiles are available.</p>}</div></section></>}
   {!loading&&section==='boutique'&&<><PortalHeading eyebrow="BOUTIQUE PREVIEW" title="Collectible Hanami cosmetics" text="Guests can browse a sample of published cosmetics. Purchasing, ownership, equipping, Petals, and inventory require a member account."/><div className="guest-shop-grid">{data.boutique.map(item=><article key={item.id}><div className={`guest-shop-art ${item.is_animated?'animated':''}`}><span>✦</span><b>{item.item_type?.replaceAll('_',' ')}</b></div><small>{item.collection_name||item.season}</small><strong>{item.name}</strong><p>{item.description}</p><footer><span>{item.rarity}</span><b>{item.pricing_state==='tbd'?'Price TBD':`❀ ${item.price_petals}`}</b></footer></article>)}</div></>}
   {!loading&&section==='hanami-plus'&&<><PortalHeading eyebrow="HANAMI+" title="A creative membership, not a paywall." text="Hanami+ expands profile, interface, creator, font, animation, personal-space, and collectible customization while keeping the school and community itself available to standard members."/><div className="guest-grid three"><Info title="Profile creativity">Advanced themes, fonts, user tags, scenes, reusable components, animations, custom colors, decorative assets, and more.</Info><Info title="Personal spaces">Customize a digital locker, desk, character phone, and 2000s desktop.</Info><Info title="Creator ecosystem">Publish themes and components, remix with attribution, build a portfolio, follow creators, and join creative challenges.</Info><Info title="Site-wide typography">Members can use premium or properly licensed uploaded fonts across supported Hanami surfaces.</Info><Info title="Collectibles">Boutique frames, effects, nameplates, stickers, emojis, decorative assets, and matching collections are account-owned.</Info><Info title="Optional access">Hanami+ can be earned, gifted, trialed, or purchased with Petals when configured. Core school access remains standard.</Info></div></>}
   {!loading&&section==='enrollment'&&<><PortalHeading eyebrow="ENROLLMENT" title="Interested in attending Hanami High?" text="Enrollment begins with the Hanami community and a Discord-linked account. Accepted applicants enter as New Students before the Owner promotes them to Student."/><div className="enrollment-flow"><article><b>1</b><strong>Join the community</strong><p>Enter through Hanami’s Discord-linked application flow.</p></article><article><b>2</b><strong>Create your character</strong><p>Each member may have up to two character slots.</p></article><article><b>3</b><strong>Submit enrollment</strong><p>Complete the character application and acknowledge the roleplay rules.</p></article><article><b>4</b><strong>Begin orientation</strong><p>Accepted characters enter as New Students and complete onboarding.</p></article></div><button className="guest-enroll-button" onClick={()=>{window.location.hash='';window.location.reload()}}>Sign in with Discord to begin</button></>}
   {!loading&&section==='search'&&<><PortalHeading eyebrow="PUBLIC SEARCH" title="Search the guest-safe network" text="Search announcements, public events, Chronicle stories, public profiles, Boutique items, and Help Center articles."/><label className="guest-search"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Hanami High…"/></label><div className="guest-search-results">{query&&!searchResults.length&&<p>No public results match “{query}”.</p>}{searchResults.map((row,i)=><article key={`${row.kind}-${i}`}><span>{row.kind}</span><strong>{row.title}</strong><p>{row.detail}</p></article>)}</div></>}
  </section></div>
 </main>
}

function PortalHeading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <header className="portal-page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></header>}
function Info({title,children}:{title:string;children:any}){return <article className="guest-info-card"><strong>{title}</strong><p>{children}</p></article>}
function GuestCards({title,rows,empty}:{title:string;rows:any[];empty:string}){return <section className="guest-list"><h2>{title}</h2>{rows.length?rows.slice(0,8).map((row,i)=><article key={row.id||i}><span>{row.category||row.event_type||row.show_name||'Hanami High'}</span><strong>{row.title}</strong><p>{row.body||row.description||row.dek||''}</p><small>{row.school_date||row.published_school_date||''}{row.location?` · ${row.location}`:''}</small></article>):<p className="empty-copy">{empty}</p>}</section>}
