import { useCallback,useEffect,useMemo,useState } from 'react'
import { supabase } from '../lib/supabase'
import { useIdentity } from '../state/IdentityContext'
import { ApplicationReviewPanel } from './ApplicationReviewPanel'
import { NewStudentManagementPanel } from './NewStudentManagementPanel'
import { SchoolAdministrationPanel } from './SchoolAdministrationPanel'
import { AdministratorOperationsPanel } from './AdministratorOperationsPanel'
import { OwnerOperationsPanel } from './OwnerOperationsPanel'

type Kind='owner'|'admin'|'moderator'
type Props={kind:Kind;mode:string;onMode:(mode:string)=>void;onClose:()=>void}
type Snapshot={applications:any[];feature_flags:any[];seasonal_events:any[];moderation_reports:any[];suggestions:any[];stats:Record<string,number>}
const empty:Snapshot={applications:[],feature_flags:[],seasonal_events:[],moderation_reports:[],suggestions:[],stats:{}}
const ownerTabs=[['overview','Control Center'],['view-as','View As'],['admissions','Admissions'],['new-students','New Students'],['school','School Office'],['feature-flags','Feature Flags'],['economy','Economy'],['hanami-plus','Hanami+'],['boutique','Boutique'],['seasonal','Seasonal Events'],['announcements','Announcements'],['platform','Platform Ops']]
const adminTabs=[['overview','Operations'],['admissions','Enrollment'],['school','School Office'],['faculty','Faculty'],['calendar','Calendar'],['announcements','Announcements'],['feature-flags','Feature Flags'],['suggestions','Suggestions'],['platform','Administration']]
const moderatorTabs=[['reports','Reports'],['content-review','Content Review'],['history','Action History']]

export function ManagementPortal({kind,mode,onMode,onClose}:Props){
 const {account,capabilities}=useIdentity();const client=supabase as any
 const [data,setData]=useState<Snapshot>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
 const [eventTitle,setEventTitle]=useState('');const [eventSlug,setEventSlug]=useState('');const [eventStart,setEventStart]=useState('2006-10-01');const [eventEnd,setEventEnd]=useState('2006-10-31');const [eventTheme,setEventTheme]=useState('');const [eventBoutique,setEventBoutique]=useState('')
 const [announcementTitle,setAnnouncementTitle]=useState('');const [announcementBody,setAnnouncementBody]=useState('');const [preview,setPreview]=useState<'guest'|'student'|'faculty'|'administrator'|null>(null)
 const tabs=kind==='owner'?ownerTabs:kind==='admin'?adminTabs:moderatorTabs
 const load=useCallback(async()=>{if(!client||!account)return;setLoading(true);setError(null);const r=await client.rpc('management_portal_snapshot');setLoading(false);if(r.error){setError(r.error.message);return}setData({...empty,...(r.data||{})})},[client,account?.id])
 useEffect(()=>{void load()},[load])
 const pending=useMemo(()=>data.applications.filter(a=>a.status==='submitted').length,[data.applications]);const activeEvents=useMemo(()=>data.seasonal_events.filter(e=>['active','scheduled'].includes(e.state)).length,[data.seasonal_events]);const openReports=useMemo(()=>data.moderation_reports.filter(r=>!['resolved','dismissed','closed'].includes(r.status)).length,[data.moderation_reports])
 async function toggleFlag(flag:any){const r=await client.from('school_feature_flags').update({enabled:!flag.enabled,updated_by_account_id:account?.id,updated_at:new Date().toISOString()}).eq('flag_key',flag.flag_key);if(r.error)return setError(r.error.message);setNotice(`${flag.label} ${flag.enabled?'disabled':'enabled'}.`);await load()}
 async function createEvent(e:React.FormEvent){e.preventDefault();if(!eventTitle.trim()||!eventSlug.trim()||!account)return;const r=await client.from('seasonal_event_configs').insert({slug:eventSlug.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),title:eventTitle.trim(),starts_school_date:eventStart,ends_school_date:eventEnd,state:'scheduled',homepage_theme:eventTheme||null,boutique_collection:eventBoutique||null,created_by_account_id:account.id});if(r.error)return setError(r.error.message);setEventTitle('');setEventSlug('');setNotice('Seasonal event scheduled.');await load()}
 async function createAnnouncement(e:React.FormEvent){e.preventDefault();if(!announcementTitle.trim()||!announcementBody.trim()||!account)return;const r=await client.from('school_announcements').insert({title:announcementTitle.trim(),body:announcementBody.trim(),category:'school',state:'published',pinned:false,school_date:'2006-09-09',created_by_account_id:account.id});if(r.error)return setError(r.error.message);setAnnouncementTitle('');setAnnouncementBody('');setNotice('School announcement published.');}
 async function resolveReport(report:any,status:'reviewing'|'resolved'|'dismissed'){const r=await client.from('moderation_reports').update({status,resolution_note:status==='reviewing'?'Under moderator review.':status==='resolved'?'Resolved by moderator.':'Dismissed after review.',reviewed_by_account_id:account?.id,updated_at:new Date().toISOString()}).eq('id',report.id);if(r.error)return setError(r.error.message);setNotice(`Report marked ${status}.`);await load()}
 async function updateSuggestion(s:any,state:string){const r=await client.from('campus_suggestions').update({state}).eq('id',s.id);if(r.error)return setError(r.error.message);await load()}
 const label=kind==='owner'?'OWNER CONTROL CENTER':kind==='admin'?'ADMINISTRATION PORTAL':'MODERATOR PORTAL'
 return <section className={`portal-window management-portal management-${kind}`}><header className="portal-titlebar"><div><span>{label} · HANAMI HIGH</span><strong>{account?.discord_username||kind}</strong></div><button onClick={onClose}>×</button></header><div className="portal-layout"><aside className="portal-nav management-nav"><div className="portal-id-mini"><div className="portal-mini-avatar">{kind==='owner'?'◆':kind==='admin'?'▣':'⚑'}</div><strong>{kind==='owner'?'Owner':kind==='admin'?'Administrator':'Moderator'}</strong><span>Account-level access</span><small>{capabilities.length} visible capabilities</small></div>{tabs.map(([id,name])=><button className={mode===id?'active':''} key={id} onClick={()=>onMode(id)}><b>{name}</b><small>{tabDescription(id)}</small></button>)}</aside><main className="portal-main">{error&&<div className="identity-notice error">{error}</div>}{notice&&<div className="identity-notice success">{notice}</div>}{loading?<div className="portal-loading">Opening management console…</div>:<>
 {mode==='overview'&&<><Heading e={label} t="School operations at a glance" p="Enrollment, people, events, moderation, platform systems, and seasonal operations without mixing these tools into a roleplay character."/><div className="portal-stat-grid"><Stat label="Active accounts" value={String(data.stats.accounts||0)} detail="Hanami accounts"/><Stat label="Students" value={String(data.stats.students||0)} detail="Student + New Student characters"/><Stat label="Faculty" value={String(data.stats.faculty||0)} detail="Teacher characters"/><Stat label="Applications" value={String(pending)} detail="Waiting for review"/><Stat label="Seasonal events" value={String(activeEvents)} detail="Scheduled or active"/><Stat label="Open reports" value={String(openReports)} detail="Moderation queue"/></div><div className="portal-columns"><Panel title="Operational shortcuts"><div className="management-shortcuts">{tabs.filter(([id])=>id!=='overview').slice(0,8).map(([id,name])=><button key={id} onClick={()=>onMode(id)}><b>{name}</b><span>{tabDescription(id)}</span></button>)}</div></Panel><Panel title="System snapshot"><dl className="management-metrics"><div><dt>Characters</dt><dd>{data.stats.characters||0}</dd></div><div><dt>Published events</dt><dd>{data.stats.published_events||0}</dd></div><div><dt>Boutique items</dt><dd>{data.stats.published_boutique_items||0}</dd></div><div><dt>Suggestions</dt><dd>{data.suggestions.length}</dd></div></dl></Panel></div></>}
 {mode==='view-as'&&<><Heading e="VIEW AS" t="Preview Hanami from another role" p="Owner preview mode is for checking portal structure and permissions. It does not silently impersonate another user or mutate their records."/><div className="view-as-grid">{(['guest','student','faculty','administrator'] as const).map(v=><button key={v} className={preview===v?'active':''} onClick={()=>setPreview(v)}><b>{v==='guest'?'Visitor / Guest':v[0].toUpperCase()+v.slice(1)}</b><span>{v==='guest'?'Public school network':v==='student'?'Student dashboard, academics, mail, social':v==='faculty'?'Teaching, gradebook, plans, advising':'School operations and configuration'}</span></button>)}</div>{preview&&<div className="view-as-preview"><span className="preview-ribbon">OWNER PREVIEW · {preview.toUpperCase()}</span>{preview==='guest'?<><h2>Public Hanami High</h2><p>Home · About · Academics · Student Life · Community · Boutique Preview · Hanami+ · Enrollment · Search</p><button onClick={()=>{window.location.hash='#/guest/home'}}>Open full Guest View</button></>:preview==='student'?<><h2>Student Portal</h2><p>Today · Planner · Homeroom · Student ID · Progress · Study Groups · School Mailbox · Hanami Passport · Saved · Help</p></>:preview==='faculty'?<><h2>Faculty Portal</h2><p>Teacher Home · Gradebook · Seating Charts · Lesson Planner · Templates · Office Hours · Advisor Dashboard</p></>:<><h2>Administration Portal</h2><p>Enrollment · School Office · Faculty · Calendar · Announcements · Feature Flags · Suggestions · Platform Administration</p></>}</div>}</>}
 {mode==='admissions'&&<><Heading e="ENROLLMENT MANAGEMENT" t="Applicant → Accepted → New Student → Active Student" p="Use the established review workflow so acceptance continues to initialize orientation and New Student status correctly."/><ApplicationReviewPanel/><section className="pipeline-board">{['draft','submitted','changes_requested','accepted','denied'].map(s=><article key={s}><header><strong>{s.replaceAll('_',' ')}</strong><span>{data.applications.filter(a=>a.status===s).length}</span></header>{data.applications.filter(a=>a.status===s).slice(0,12).map(a=><div key={a.character_id}><b>{a.nickname||'Applicant'}</b><small>Year {a.school_year} · {a.submitted_at?new Date(a.submitted_at).toLocaleDateString():'Not submitted'}</small></div>)}</article>)}</section></>}
 {mode==='new-students'&&<><Heading e="NEW STUDENTS" t="Orientation & promotion" p="New Student remains persistent until the Owner explicitly removes it through the established promotion workflow."/><NewStudentManagementPanel/></>}
 {(mode==='school'||mode==='faculty'||mode==='calendar')&&<><Heading e={mode==='faculty'?'FACULTY MANAGEMENT':mode==='calendar'?'SCHOOL CALENDAR MANAGER':'SCHOOL OPERATIONS'} t={mode==='faculty'?'People, classes, and responsibilities':mode==='calendar'?'Academic dates and school events':'Run the school day'} p={mode==='faculty'?'Assign faculty responsibilities through the existing school administration foundation.':mode==='calendar'?'Manage the operational calendar and campus event systems from one school-office surface.':'Homerooms, classes, announcements, events, and school structure use the existing V2 administration layer.'}/><SchoolAdministrationPanel/></>}
 {mode==='feature-flags'&&<><Heading e="FEATURE FLAGS" t="Turn major Hanami systems on or off" p="These switches are account-level platform configuration. The global feature guard uses them to block disabled user-facing sections."/><div className="flag-grid">{data.feature_flags.map(flag=><article key={flag.flag_key} className={flag.enabled?'enabled':'disabled'}><div><span>{flag.flag_key}</span><strong>{flag.label}</strong><p>{flag.description}</p></div><button onClick={()=>void toggleFlag(flag)}>{flag.enabled?'Enabled · turn off':'Disabled · turn on'}</button></article>)}</div></>}
 {mode==='seasonal'&&<><Heading e="SEASONAL EVENT MANAGER" t="Coordinate a whole school season" p="Schedule an event and connect its school dates, homepage direction, and Boutique collection without inventing rewards or Petal prices."/><form className="portal-form multi" onSubmit={createEvent}><input value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Event title"/><input value={eventSlug} onChange={e=>setEventSlug(e.target.value)} placeholder="event-slug"/><label>Starts<input type="date" value={eventStart} onChange={e=>setEventStart(e.target.value)}/></label><label>Ends<input type="date" value={eventEnd} onChange={e=>setEventEnd(e.target.value)}/></label><input value={eventTheme} onChange={e=>setEventTheme(e.target.value)} placeholder="Homepage theme key (optional)"/><input value={eventBoutique} onChange={e=>setEventBoutique(e.target.value)} placeholder="Boutique collection (optional)"/><button>Schedule event</button></form><div className="portal-card-grid">{data.seasonal_events.map(ev=><article key={ev.id}><span>{ev.state}</span><h3>{ev.title}</h3><p>{ev.starts_school_date} → {ev.ends_school_date}</p><small>{[ev.homepage_theme,ev.boutique_collection].filter(Boolean).join(' · ')||'No linked presentation yet'}</small></article>)}</div></>}
 {mode==='announcements'&&<><Heading e="ANNOUNCEMENT COMPOSER" t="Publish to the school network" p="Create official school notices. Audience-targeted school mail remains separate from public announcements."/><form className="portal-form multi" onSubmit={createAnnouncement}><input value={announcementTitle} onChange={e=>setAnnouncementTitle(e.target.value)} placeholder="Announcement title"/><textarea value={announcementBody} onChange={e=>setAnnouncementBody(e.target.value)} placeholder="Announcement body"/><button>Publish announcement</button></form></>}
 {mode==='suggestions'&&<><Heading e="SUGGESTION BOX" t="Review student ideas" p="Suggestions are account-private to the submitter and school administrators unless intentionally shared elsewhere."/><div className="mail-list">{data.suggestions.map(s=><article key={s.id}><div><span>{s.category}</span><strong>{s.subject}</strong><small>{s.state} · {new Date(s.created_at).toLocaleDateString()}</small></div><p>{s.body}</p><div><button onClick={()=>void updateSuggestion(s,'reviewing')}>Reviewing</button><button onClick={()=>void updateSuggestion(s,'planned')}>Planned</button><button onClick={()=>void updateSuggestion(s,'closed')}>Close</button></div></article>)}</div></>}
 {['economy','hanami-plus','boutique'].includes(mode)&&kind==='owner'&&<><Heading e={mode.toUpperCase()} t={`${mode==='economy'?'Petal economy':mode==='hanami-plus'?'Hanami+ management':'Boutique management'} control`} p="This workspace uses the existing audited Owner operations rather than creating a second management path."/><OwnerOperationsPanel/></>}
 {mode==='platform'&&<><Heading e="PLATFORM OPERATIONS" t="Account-level administration" p="Audit-aware platform operations remain separated from roleplay character tools."/>{kind==='owner'?<OwnerOperationsPanel/>:<AdministratorOperationsPanel/>}</>}
 {mode==='reports'&&<><Heading e="MODERATION QUEUE" t="Reports needing attention" p="Review reported content and resolve or dismiss reports without exposing private conversations outside the authorized moderation surface."/><div className="moderation-list">{data.moderation_reports.map(r=><article key={r.id}><header><span>{r.target_type}</span><strong>{r.reason}</strong><small>{r.status}</small></header><p>{r.details||'No additional details.'}</p><footer><button onClick={()=>void resolveReport(r,'reviewing')}>Take review</button><button onClick={()=>void resolveReport(r,'resolved')}>Resolve</button><button onClick={()=>void resolveReport(r,'dismissed')}>Dismiss</button></footer></article>)}{!data.moderation_reports.length&&<p className="empty-copy">No reports are visible in your moderation queue.</p>}</div></>}
 {mode==='content-review'&&<><Heading e="CONTENT REVIEW" t="Custom identity & creator moderation" p="Review profile reports, custom titles/tags, creator marketplace concerns, and uploaded-asset issues from one moderation desk."/><div className="portal-card-grid"><article><span>USER TAGS</span><h3>Custom identity</h3><p>Moderated text remains separate from official staff roles and permissions.</p></article><article><span>CREATOR CONTENT</span><h3>Marketplace reports</h3><p>Theme and component attribution, licensing, and safety concerns use report review rather than silent removal.</p></article><article><span>UPLOADED ASSETS</span><h3>Fonts & media</h3><p>Uploaded fonts remain account-scoped and require a rights confirmation; reports can be escalated for review.</p></article></div></>}
 {mode==='history'&&<><Heading e="MODERATION HISTORY" t="Resolved report activity" p="Use the current report queue as the visible history source; platform audit logs remain Owner/Admin capability gated."/><div className="moderation-list">{data.moderation_reports.filter(r=>['resolved','dismissed','closed'].includes(r.status)).map(r=><article key={r.id}><header><span>{r.target_type}</span><strong>{r.reason}</strong><small>{r.status}</small></header><p>{r.resolution_note||'No resolution note.'}</p></article>)}</div></>}
 }</>}</main></div></section>
}

function tabDescription(id:string){const map:Record<string,string>={overview:'Metrics & shortcuts','view-as':'Role previews',admissions:'Applications pipeline','new-students':'Orientation & promotion',school:'Homerooms, classes, events','feature-flags':'System switches',economy:'Petals & wallet controls','hanami-plus':'Membership controls',boutique:'Shop operations',seasonal:'Season-wide configuration',announcements:'Official notices',platform:'Accounts & platform',faculty:'Faculty assignments',calendar:'School calendar',suggestions:'Student feedback',reports:'Reported content', 'content-review':'Tags, creators, uploads',history:'Resolved cases'};return map[id]||''}
function Heading({e,t,p}:{e:string;t:string;p:string}){return <header className="portal-page-heading"><span className="eyebrow">{e}</span><h1>{t}</h1><p>{p}</p></header>}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <article className="portal-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Panel({title,children}:{title:string;children:any}){return <section className="portal-panel"><header><strong>{title}</strong></header><div>{children}</div></section>}
