import { useCallback, useEffect, useMemo, useState, type CSSProperties } from 'react'
import { supabase } from '../lib/supabase'
import { getSignedProfileMediaUrl } from '../lib/profileMedia'
import { useIdentity } from '../state/IdentityContext'
import type { Json, PublishedProfileWidget, SocialPost } from '../types/database'
import type { PublishedCharacterProfileWithCosmetics } from '../types/database-customization'
import { GuestbookPanel } from './GuestbookPanel'
import { ShellTopbar } from './ShellTopbar'

type Props={targetCharacterId?:string;onSearch:()=>void;onNotifications:()=>void;unreadCount:number}
type Tab='board'|'activity'|'guestbook'
type Theme={background:string;panel:string;accent:string;ink:string;displayFont:string;displayEffect:string;displayColor:string}
type Cosmetics={avatarDecoration?:string;frame?:string;effect?:string;nameplate?:string;profileCard?:string;backgroundPack?:string}
const fallback:Theme={background:'#111214',panel:'#f2f3f5',accent:'#d86f8b',ink:'#1e1f22',displayFont:'ui',displayEffect:'solid',displayColor:'#e0b641'}
function obj(value:Json){return value&&!Array.isArray(value)&&typeof value==='object'?value as Record<string,Json|undefined>:{} }
function stringValue(value:Json,key:string,fallbackValue=''){const v=obj(value)[key];return typeof v==='string'?v:fallbackValue}
function themeFrom(value:Json):Theme{const s=obj(value);return{background:typeof s.background==='string'?s.background:fallback.background,panel:typeof s.panel==='string'?s.panel:fallback.panel,accent:typeof s.accent==='string'?s.accent:fallback.accent,ink:typeof s.ink==='string'?s.ink:fallback.ink,displayFont:typeof s.displayFont==='string'?s.displayFont:'ui',displayEffect:typeof s.displayEffect==='string'?s.displayEffect:'solid',displayColor:typeof s.displayColor==='string'?s.displayColor:'#e0b641'}}
function cosmeticsFrom(value:Json):Cosmetics{const s=obj(value);return{avatarDecoration:typeof s.avatarDecoration==='string'?s.avatarDecoration:undefined,frame:typeof s.frame==='string'?s.frame:undefined,effect:typeof s.effect==='string'?s.effect:undefined,nameplate:typeof s.nameplate==='string'?s.nameplate:undefined,profileCard:typeof s.profileCard==='string'?s.profileCard:undefined,backgroundPack:typeof s.backgroundPack==='string'?s.backgroundPack:undefined}}
function widgetContent(value:Json){return stringValue(value,'content')}
function widgetPath(value:Json){const p=obj(value).storagePath;return typeof p==='string'?p:null}
function roleLabel(role:string|null){if(role==='new_faculty')return'New Teacher';if(role==='faculty')return'Teacher';if(role==='administration')return'Staff';if(role==='new_student')return'New Student';if(role==='student')return'Student';return role?role.split('_').map(p=>p[0]?.toUpperCase()+p.slice(1)).join(' '):'Hanami Member'}
function noteKey(id:string){return`hanami-profile-note:${id}`}
function safeClass(value?:string){return(value||'none').replace(/[^a-z0-9-]/gi,'-').toLowerCase()}

export function ProfileView({targetCharacterId,onSearch,onNotifications,unreadCount}:Props){
 const {activeCharacter}=useIdentity();const characterId=targetCharacterId||activeCharacter?.id;const own=Boolean(activeCharacter&&characterId===activeCharacter.id)
 const [profile,setProfile]=useState<PublishedCharacterProfileWithCosmetics|null>(null);const[widgets,setWidgets]=useState<PublishedProfileWidget[]>([]);const[posts,setPosts]=useState<SocialPost[]>([]);const[media,setMedia]=useState<Record<string,string>>({});const[memberSince,setMemberSince]=useState<string|null>(null);const[note,setNote]=useState('');const[tab,setTab]=useState<Tab>('board');const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null)
 const hydrate=useCallback(async(p:PublishedCharacterProfileWithCosmetics|null,w:PublishedProfileWidget[])=>{if(!p)return;const paths=Array.from(new Set([p.avatar_path,p.banner_path,...w.map(x=>widgetPath(x.config))].filter((x):x is string=>Boolean(x))));const pairs=await Promise.all(paths.map(async path=>{try{const url=await getSignedProfileMediaUrl(path);return url?[path,url]as const:null}catch{return null}}));setMedia(Object.fromEntries(pairs.filter((x):x is readonly[string,string]=>Boolean(x))))},[])
 const load=useCallback(async()=>{const client=supabase;if(!client||!characterId)return;setLoading(true);setError(null);const[p,c,w,a]=await Promise.all([client.from('published_character_profiles').select('*').eq('character_id',characterId).maybeSingle(),client.from('characters').select('created_at').eq('id',characterId).maybeSingle(),client.from('published_profile_widgets').select('*').eq('character_id',characterId).order('y').order('x'),client.from('social_posts').select('*').eq('author_character_id',characterId).eq('state','published').order('published_at',{ascending:false}).limit(12)]);setLoading(false);const first=[p.error,c.error,w.error,a.error].find(Boolean);if(first)return setError(first.message);setProfile(p.data);setWidgets(w.data??[]);setPosts(a.data??[]);setMemberSince(c.data?.created_at??null);void hydrate(p.data,w.data??[])},[characterId,hydrate])
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(characterId)setNote(localStorage.getItem(noteKey(characterId))||'')},[characterId])
 const theme=useMemo(()=>themeFrom(profile?.theme??{}),[profile?.theme]);const cosmetics=useMemo(()=>cosmeticsFrom(profile?.cosmetics??{}),[profile?.cosmetics]);if(!activeCharacter||!characterId)return null
 const ownName=activeCharacter.display_name||[activeCharacter.first_name,activeCharacter.last_name].filter(Boolean).join(' ')||'Your Character';const name=profile?.display_name||(own?ownName:'Hanami Profile');const handle=profile?.handle?`.${profile.handle}`:'.hanami';const css={ '--profile-accent':theme.accent,'--profile-panel':theme.panel,'--profile-ink':theme.ink,'--display-color':theme.displayColor }as CSSProperties
 return <main className="content-area published-profile-page"><ShellTopbar eyebrow={own?'MY PROFILE':'PROFILE'} title={name} onSearch={onSearch} onNotifications={onNotifications} unreadCount={unreadCount}/>{error&&<div className="identity-notice error">{error}</div>}{loading?<div className="studio-loading">Loading profile…</div>:!profile?<section className="shell-module-card"><h2>{own?'Publish your profile first.':'Profile unavailable.'}</h2></section>:<section className={`discord-full-profile cosmetic-frame-${safeClass(cosmetics.frame)} cosmetic-avatar-${safeClass(cosmetics.avatarDecoration)} cosmetic-effect-${safeClass(cosmetics.effect)} cosmetic-card-${safeClass(cosmetics.profileCard)} cosmetic-bg-${safeClass(cosmetics.backgroundPack)}`} style={css}>
   <div className="discord-full-profile-left">
    <article className="discord-profile-exact-card">
      <div className="discord-exact-banner" style={{background:theme.accent}}>{profile.banner_path&&media[profile.banner_path]&&<img src={media[profile.banner_path]} alt={`${name} banner`}/>}</div>
      <div className="discord-exact-avatar-wrap"><div className="discord-exact-avatar">{profile.avatar_path&&media[profile.avatar_path]?<img src={media[profile.avatar_path]} alt={`${name} avatar`}/>:name.slice(0,2).toUpperCase()}</div><span className="discord-exact-status online"/></div>
      <div className="discord-exact-body"><h1 className={`display-name-demo font-${theme.displayFont} effect-${theme.displayEffect}`}>{name}</h1><div className="discord-exact-handle"><span>{handle}</span>{profile.pronouns&&<><b>•</b><em>{profile.pronouns}</em></>}</div><div className="discord-exact-badges"><span title="Hanami member">✿</span><span title={roleLabel(profile.school_role)}>◇</span><span>🎓</span><span>💻</span></div>{profile.custom_status&&<p className="discord-exact-status-copy">{profile.custom_status}</p>}
      <div className="discord-exact-actions">{own?<a href="#/profile/profile-studio">Edit Profile</a>:<a href="#/messages/friends">Message</a>}<a href="#/social/friends">♟</a><button type="button">•••</button></div>
      <div className="discord-exact-info">{profile.bio&&<section><strong>Bio</strong><p>{profile.bio}</p></section>}<section><strong>Roles</strong><div className="discord-exact-role"><i/><span>{roleLabel(profile.school_role)}</span><span>Hanami High</span></div></section><section><strong>Member Since</strong><p>{memberSince?new Date(memberSince).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):new Date(profile.published_at).toLocaleDateString()}</p></section><section><strong>Connections</strong><div className="discord-exact-connections"><span>✿ Hanami High</span><span>🎓 {roleLabel(profile.school_role)}</span></div></section><section><strong>Note</strong><textarea value={note} placeholder="Click to add a private note" onChange={e=>setNote(e.target.value)} onBlur={()=>localStorage.setItem(noteKey(characterId),note)}/></section></div></div>
    </article>
   </div>
   <div className="discord-full-profile-right"><nav className="discord-profile-tabs"><button className={tab==='board'?'active':''} onClick={()=>setTab('board')}>Board</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Activity</button><button className={tab==='guestbook'?'active':''} onClick={()=>setTab('guestbook')}>Guestbook</button></nav>
    {tab==='board'&&<div className="discord-profile-board">{widgets.length===0?<div className="discord-profile-empty"><strong>No widgets yet.</strong><span>{own?'Open Profile Studio to customize your board.':'This member has not added board widgets.'}</span></div>:<div className="discord-profile-widget-grid">{widgets.map(widget=><article key={widget.id} className={`widget-${widget.widget_type}`}><header><strong>{widget.title||widget.widget_type.replaceAll('_',' ')}</strong></header>{widget.widget_type==='image'&&widgetPath(widget.config)&&media[widgetPath(widget.config)!]?<img src={media[widgetPath(widget.config)!]} alt={widget.title||'Profile widget'}/>:<p>{widgetContent(widget.config)||'Profile widget'}</p>}</article>)}</div>}</div>}
    {tab==='activity'&&<div className="discord-profile-activity-list">{posts.length===0?<div className="discord-profile-empty">No public activity yet.</div>:posts.map(post=><article key={post.id}><span>{post.post_type}</span><div><strong>{post.title||name}</strong><p>{post.body}</p><small>{new Date(post.published_at||post.created_at).toLocaleString()}</small></div></article>)}</div>}
    {tab==='guestbook'&&<div className="discord-profile-guestbook"><GuestbookPanel targetCharacterId={characterId} guestbookVisibility={profile.guestbook_visibility} management={own}/></div>}
   </div>
 </section>}</main>
}
