import { useCallback,useEffect,useState } from 'react'
import { supabase } from '../lib/supabase'
import { useIdentity } from '../state/IdentityContext'

type Mode='status-history'|'polls'|'reposts'|'memories'
type Props={mode:Mode;onMode:(mode:Mode)=>void;onClose:()=>void}
const nav:[Mode,string,string][]=[['status-history','Status History','Moods & away notes'],['polls','Polls','Add polls to posts'],['reposts','Reposts','Share posts'],['memories','Memories','Character archive']]

export function SocialExtrasPortal({mode,onMode,onClose}:Props){
 const {account,activeCharacter}=useIdentity();const client=supabase as any
 const [statuses,setStatuses]=useState<any[]>([]);const [posts,setPosts]=useState<any[]>([]);const [polls,setPolls]=useState<any[]>([]);const [reposts,setReposts]=useState<any[]>([]);const [memories,setMemories]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
 const [statusText,setStatusText]=useState('');const [mood,setMood]=useState('');const [postId,setPostId]=useState('');const [pollOptions,setPollOptions]=useState('Yes\nNo');const [repostPostId,setRepostPostId]=useState('');const [repostComment,setRepostComment]=useState('');const [memoryTitle,setMemoryTitle]=useState('');const [memoryBody,setMemoryBody]=useState('');const [memoryDate,setMemoryDate]=useState('');const [memoryVisibility,setMemoryVisibility]=useState('private')
 const load=useCallback(async()=>{if(!client||!account||!activeCharacter)return;setLoading(true);setError(null);const [s,p,o,r,m]=await Promise.all([client.from('character_status_history').select('*').eq('character_id',activeCharacter.id).order('created_at',{ascending:false}).limit(40),client.from('social_posts').select('id,title,body,post_type,state,visibility,published_at,created_at').eq('author_character_id',activeCharacter.id).order('created_at',{ascending:false}).limit(40),client.from('social_poll_options').select('*').order('sort_order'),client.from('social_post_reposts').select('*').eq('account_id',account.id).order('created_at',{ascending:false}),client.from('character_memories').select('*').eq('character_id',activeCharacter.id).order('memory_school_date',{ascending:false}).order('created_at',{ascending:false})]);setLoading(false);const first=[s,p,o,r,m].find(x=>x.error);if(first?.error){setError(first.error.message);return}setStatuses(s.data||[]);setPosts(p.data||[]);setPolls(o.data||[]);setReposts(r.data||[]);setMemories(m.data||[])},[client,account?.id,activeCharacter?.id])
 useEffect(()=>{void load()},[load])
 async function addStatus(e:React.FormEvent){e.preventDefault();if(!activeCharacter||!statusText.trim())return;const r=await client.from('character_status_history').insert({character_id:activeCharacter.id,status_text:statusText.trim(),mood:mood.trim()});if(r.error)return setError(r.error.message);setStatusText('');setMood('');setNotice('Status saved to your history.');await load()}
 async function addPoll(e:React.FormEvent){e.preventDefault();if(!postId)return;const options=pollOptions.split('\n').map(v=>v.trim()).filter(Boolean).slice(0,8);if(options.length<2){setError('A poll needs at least two options.');return}const rows=options.map((label,index)=>({post_id:postId,label,sort_order:index}));const r=await client.from('social_poll_options').insert(rows);if(r.error)return setError(r.error.message);setNotice('Poll added to your post.');await load()}
 async function addRepost(e:React.FormEvent){e.preventDefault();if(!account||!activeCharacter||!repostPostId.trim())return;const r=await client.from('social_post_reposts').upsert({post_id:repostPostId.trim(),account_id:account.id,character_id:activeCharacter.id,comment:repostComment.trim()});if(r.error)return setError(r.error.message);setRepostPostId('');setRepostComment('');setNotice('Post shared to your repost archive.');await load()}
 async function removeRepost(postId:string){const r=await client.from('social_post_reposts').delete().eq('account_id',account?.id).eq('post_id',postId);if(r.error)return setError(r.error.message);await load()}
 async function addMemory(e:React.FormEvent){e.preventDefault();if(!activeCharacter||!memoryTitle.trim())return;const r=await client.from('character_memories').insert({character_id:activeCharacter.id,title:memoryTitle.trim(),body:memoryBody.trim(),memory_school_date:memoryDate||null,visibility:memoryVisibility});if(r.error)return setError(r.error.message);setMemoryTitle('');setMemoryBody('');setMemoryDate('');setNotice('Memory archived.');await load()}
 async function removeMemory(id:string){const r=await client.from('character_memories').delete().eq('id',id);if(r.error)return setError(r.error.message);await load()}
 const name=activeCharacter?.display_name||[activeCharacter?.first_name,activeCharacter?.last_name].filter(Boolean).join(' ')||'Hanami Member'
 return <section className="portal-window social-extras-portal"><header className="portal-titlebar"><div><span>SOCIAL EXTRAS · HANAMI HIGH</span><strong>{name}</strong></div><button onClick={onClose}>×</button></header><div className="portal-layout"><aside className="portal-nav"><div className="portal-id-mini"><div className="portal-mini-avatar">♡</div><strong>Social Archive</strong><span>@{activeCharacter?.handle}</span><small>Character-specific extras</small></div>{nav.map(([id,label,desc])=><button key={id} className={mode===id?'active':''} onClick={()=>onMode(id)}><b>{label}</b><small>{desc}</small></button>)}</aside><main className="portal-main">{error&&<div className="identity-notice error">{error}</div>}{notice&&<div className="identity-notice success">{notice}</div>}{loading?<div className="portal-loading">Opening social archive…</div>:<>
 {mode==='status-history'&&<><Heading e="STATUS HISTORY" t="Moods, away notes & little moments" p="Keep a private character history of custom statuses and moods. Your current public status still lives in Profile Studio/social identity settings."/><form className="portal-form" onSubmit={addStatus}><input value={statusText} onChange={e=>setStatusText(e.target.value)} maxLength={140} placeholder="small heart, big feelings…"/><input value={mood} onChange={e=>setMood(e.target.value)} placeholder="Mood (optional)"/><button>Save status</button></form><div className="status-history-list">{statuses.map(s=><article key={s.id}><span>{s.mood||'status'}</span><strong>{s.status_text}</strong><small>{new Date(s.created_at).toLocaleString()}</small></article>)}{!statuses.length&&<Empty text="No saved statuses yet."/>}</div></>}
 {mode==='polls'&&<><Heading e="POST POLLS" t="Ask your circle something" p="Attach a simple poll to one of your own social posts. Core post visibility still controls who can see the post itself."/><form className="portal-form multi" onSubmit={addPoll}><select value={postId} onChange={e=>setPostId(e.target.value)}><option value="">Choose one of your posts</option>{posts.map(p=><option key={p.id} value={p.id}>{p.title||String(p.body||'Untitled post').slice(0,60)}</option>)}</select><textarea value={pollOptions} onChange={e=>setPollOptions(e.target.value)} placeholder={'One option per line\nAt least two options'}/><button>Add poll</button></form><div className="portal-card-grid">{posts.filter(p=>polls.some(o=>o.post_id===p.id)).map(p=><article key={p.id}><span>{p.post_type}</span><h3>{p.title||String(p.body||'Post').slice(0,70)}</h3><div className="poll-preview">{polls.filter(o=>o.post_id===p.id).map(o=><div key={o.id}><span>{o.label}</span><i/></div>)}</div></article>)}{!posts.some(p=>polls.some(o=>o.post_id===p.id))&&<Empty text="None of your posts have polls yet."/>}</div></>}
 {mode==='reposts'&&<><Heading e="REPOSTS" t="Share something from the social network" p="Reposts create a character-attributed share record with an optional comment. They do not overwrite or copy the original post."/><form className="portal-form multi" onSubmit={addRepost}><input value={repostPostId} onChange={e=>setRepostPostId(e.target.value)} placeholder="Post ID"/><textarea value={repostComment} onChange={e=>setRepostComment(e.target.value)} placeholder="Optional repost comment"/><button>Repost</button></form><div className="portal-card-grid">{reposts.map(r=><article key={r.post_id}><span>REPOST</span><h3>{r.post_id}</h3><p>{r.comment||'Shared without comment.'}</p><small>{new Date(r.created_at).toLocaleString()}</small><button onClick={()=>void removeRepost(r.post_id)}>Remove repost</button></article>)}{!reposts.length&&<Empty text="You have not reposted anything yet."/>}</div></>}
 {mode==='memories'&&<><Heading e="CHARACTER MEMORIES" t="A private archive of your time at Hanami" p="Save moments by in-universe school date and choose whether each memory stays private, is shared with friends, or can appear publicly later."/><form className="portal-form multi" onSubmit={addMemory}><input value={memoryTitle} onChange={e=>setMemoryTitle(e.target.value)} placeholder="Memory title"/><input type="date" value={memoryDate} onChange={e=>setMemoryDate(e.target.value)}/><select value={memoryVisibility} onChange={e=>setMemoryVisibility(e.target.value)}><option value="private">Private</option><option value="friends">Friends</option><option value="public">Public</option></select><textarea value={memoryBody} onChange={e=>setMemoryBody(e.target.value)} placeholder="What happened?"/><button>Save memory</button></form><div className="memory-timeline">{memories.map(m=><article key={m.id}><time>{m.memory_school_date||'2006'}</time><div><span>{m.visibility}</span><h3>{m.title}</h3><p>{m.body}</p></div><button onClick={()=>void removeMemory(m.id)}>×</button></article>)}{!memories.length&&<Empty text="Your memory archive is empty."/>}</div></>}
 }</>}</main></div></section>
}
function Heading({e,t,p}:{e:string;t:string;p:string}){return <header className="portal-page-heading"><span className="eyebrow">{e}</span><h1>{t}</h1><p>{p}</p></header>}
function Empty({text}:{text:string}){return <p className="empty-copy">{text}</p>}
