import { useCallback,useEffect,useMemo,useState } from 'react'
import { supabase } from '../lib/supabase'
import { useIdentity } from '../state/IdentityContext'

type Mode='today'|'planner'|'homeroom'|'student-id'|'progress'|'study-groups'|'mailbox'|'passport'|'bookmarks'|'help'
type Props={mode:Mode;onMode:(mode:Mode)=>void;onClose:()=>void}
type Snapshot={planner:any[];mail:any[];assignments:any[];grades:any[];attendance:any[];homeroom:any|null;passport:any[];study_groups:any[];yearbook:any|null;bookmarks:any[];recent:any[]}
const empty:Snapshot={planner:[],mail:[],assignments:[],grades:[],attendance:[],homeroom:null,passport:[],study_groups:[],yearbook:null,bookmarks:[],recent:[]}
const nav:[Mode,string,string][]=[['today','Today','Daily dashboard'],['planner','Planner','Tasks & reminders'],['homeroom','Homeroom','Class hub'],['student-id','Student ID','School identity'],['progress','Progress','Grades & attendance'],['study-groups','Study Groups','Private study spaces'],['mailbox','School Mailbox','Official notices'],['passport','Hanami Passport','Milestones & stamps'],['bookmarks','Saved','Bookmarks & recent'],['help','Help Center','How Hanami works']]

function tokyoClock(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tokyo',hour12:false,hour:'2-digit',minute:'2-digit',weekday:'short',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';return{weekday:get('weekday'),month:get('month'),day:get('day'),minutes:Number(get('hour'))*60+Number(get('minute'))}}
const schoolBlocks=[['Arrival',8*60+30,8*60+35],['Shoe Change',8*60+35,8*60+40],['Morning Homeroom',8*60+40,8*60+50],['Period 1',8*60+50,9*60+40],['Passing Time',9*60+40,9*60+50],['Period 2',9*60+50,10*60+40],['Passing Time',10*60+40,10*60+50],['Period 3',10*60+50,11*60+40],['Passing Time',11*60+40,11*60+50],['Period 4',11*60+50,12*60+40],['Lunch',12*60+40,13*60+25],['Period 5',13*60+25,14*60+15],['Passing Time',14*60+15,14*60+25],['Period 6',14*60+25,15*60+15],['Classroom Cleaning · Soji',15*60+15,15*60+35],['Afternoon Homeroom',15*60+35,15*60+50],['Club Activities · Bukatsu',16*60,18*60+30]] as const
function timeLabel(min:number){const h=Math.floor(min/60),m=min%60;const hr=h>12?h-12:h;return`${hr}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}

export function StudentPortal({mode,onMode,onClose}:Props){
 const {account,activeCharacter}=useIdentity();const client=supabase as any
 const [data,setData]=useState<Snapshot>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
 const [title,setTitle]=useState('');const [kind,setKind]=useState('task');const [due,setDue]=useState('');const [priority,setPriority]=useState('normal');const [groupTitle,setGroupTitle]=useState('');const [groupSubject,setGroupSubject]=useState('');const [help,setHelp]=useState<any[]>([])
 const load=useCallback(async()=>{if(!client||!account||!activeCharacter)return;setLoading(true);setError(null);const [snap,helpRows]=await Promise.all([client.rpc('student_portal_snapshot'),client.from('help_articles').select('*').eq('published',true).order('sort_order')]);setLoading(false);if(snap.error){setError(snap.error.message);return}setData({...empty,...(snap.data||{})});if(!helpRows.error)setHelp(helpRows.data||[])},[client,account?.id,activeCharacter?.id])
 useEffect(()=>{void load()},[load])
 const clock=useMemo(tokyoClock,[mode,loading]);const currentBlock=schoolBlocks.find(b=>clock.minutes>=b[1]&&clock.minutes<b[2]);const nextBlock=schoolBlocks.find(b=>clock.minutes<b[1]);const dueToday=useMemo(()=>data.assignments.filter(a=>a.due_school_date===`2006-${clock.month}-${clock.day}`),[data.assignments,clock.month,clock.day]);const unread=data.mail.filter(m=>!m.read_at).length
 const gradeSummary=useMemo(()=>{let earned=0,possible=0;for(const g of data.grades){const p=Number(g.points_possible||0);const e=Number(g.points_earned||0);if(p>0){earned+=e;possible+=p}}return possible?Math.round(earned/possible*100):null},[data.grades]);const attendanceSummary=useMemo(()=>{const total=data.attendance.length;const present=data.attendance.filter(a=>['present','late'].includes(a.status)).length;return total?Math.round(present/total*100):null},[data.attendance])
 async function addPlanner(e:React.FormEvent){e.preventDefault();if(!title.trim()||!account||!activeCharacter)return;const {error:e2}=await client.from('student_planner_items').insert({account_id:account.id,character_id:activeCharacter.id,title:title.trim(),item_kind:kind,due_school_date:due||null,priority});if(e2)return setError(e2.message);setTitle('');setDue('');setNotice('Planner item added.');await load()}
 async function togglePlanner(item:any){const {error:e}=await client.from('student_planner_items').update({completed:!item.completed,updated_at:new Date().toISOString()}).eq('id',item.id);if(e)return setError(e.message);await load()}
 async function deletePlanner(id:string){const {error:e}=await client.from('student_planner_items').delete().eq('id',id);if(e)return setError(e.message);await load()}
 async function createGroup(e:React.FormEvent){e.preventDefault();if(!groupTitle.trim()||!activeCharacter)return;const {data:g,error:e2}=await client.from('study_groups').insert({owner_character_id:activeCharacter.id,title:groupTitle.trim(),subject:groupSubject.trim(),visibility:'invite'}).select('*').single();if(e2)return setError(e2.message);const m=await client.from('study_group_members').insert({group_id:g.id,character_id:activeCharacter.id,member_role:'owner'});if(m.error)return setError(m.error.message);setGroupTitle('');setGroupSubject('');setNotice('Study group created.');await load()}
 async function markMail(id:string){const {error:e}=await client.from('school_mail_messages').update({read_at:new Date().toISOString()}).eq('id',id);if(e)return setError(e.message);await load()}
 async function removeBookmark(id:string){const {error:e}=await client.from('global_bookmarks').delete().eq('id',id);if(e)return setError(e.message);await load()}
 const name=activeCharacter?.display_name||[activeCharacter?.first_name,activeCharacter?.last_name].filter(Boolean).join(' ')||'Hanami Student'
 return <section className="portal-window portal-student"><header className="portal-titlebar"><div><span>STUDENT PORTAL · 2006–07</span><strong>{name}</strong></div><button onClick={onClose}>×</button></header><div className="portal-layout"><aside className="portal-nav"><div className="portal-id-mini"><div className="portal-mini-avatar">{account?.discord_avatar_url?<img src={account.discord_avatar_url} alt=""/>:<span>花</span>}</div><strong>{name}</strong><span>@{activeCharacter?.handle}</span><small>{activeCharacter?.school_role?.replace('_',' ')||'Student'}</small></div>{nav.map(([id,label,desc])=><button key={id} className={mode===id?'active':''} onClick={()=>onMode(id)}><b>{label}</b><small>{desc}</small></button>)}</aside><main className="portal-main">{error&&<div className="identity-notice error">{error}</div>}{notice&&<div className="identity-notice success">{notice}</div>}{loading?<div className="portal-loading">Loading your student desk…</div>:<>
 {mode==='today'&&<><Heading e="TODAY AT HANAMI" t={`Sat, ${clock.month}/${clock.day}/2006`} p="Your personal school-day dashboard combines classes, assignments, homeroom, mail, and after-school activity."/><div className="portal-stat-grid"><Stat label="Current block" value={currentBlock?.[0]||'Outside school hours'} detail={currentBlock?`${timeLabel(currentBlock[1])}–${timeLabel(currentBlock[2])}`:nextBlock?`Next: ${nextBlock[0]} at ${timeLabel(nextBlock[1])}`:'School day complete'}/><Stat label="Next" value={nextBlock?.[0]||'No more blocks'} detail={nextBlock?timeLabel(nextBlock[1]):'See you tomorrow'}/><Stat label="Due today" value={String(dueToday.length)} detail="Published assignments"/><Stat label="School mailbox" value={String(unread)} detail="Unread notices"/></div><div className="portal-columns"><Panel title="School-day timeline">{schoolBlocks.map(b=><div className={`timeline-row ${currentBlock?.[0]===b[0]?'current':''}`} key={`${b[0]}-${b[1]}`}><time>{timeLabel(b[1])}</time><strong>{b[0]}</strong><span>{timeLabel(b[2])}</span></div>)}</Panel><Panel title="What needs attention">{data.assignments.slice(0,6).map(a=><a className="portal-list-row" href="#/academics/assignments" key={a.id}><b>{a.course_code}</b><strong>{a.title}</strong><small>{a.due_school_date||'No due date'}</small></a>)}{!data.assignments.length&&<Empty text="No published assignments right now."/>}<hr/><strong className="portal-subtitle">Homeroom</strong>{data.homeroom?<p><b>{data.homeroom.code}</b> · {data.homeroom.room_label}<br/><small>Advisor: {data.homeroom.advisor_name||'TBD'} · Year {data.homeroom.student_year}</small></p>:<Empty text="No homeroom assignment yet."/>}</Panel></div></>}
 {mode==='planner'&&<><Heading e="STUDENT PLANNER" t="Your 2006 school planner" p="Track assignments, tests, projects, club responsibilities, events, and personal reminders."/><form className="portal-form planner-form" onSubmit={addPlanner}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What do you need to do?"/><select value={kind} onChange={e=>setKind(e.target.value)}><option>task</option><option>assignment</option><option>test</option><option>project</option><option>club</option><option>event</option><option>reminder</option></select><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><button>Add</button></form><div className="planner-list">{data.planner.map(item=><article className={`${item.completed?'done':''} priority-${item.priority}`} key={item.id}><button className="planner-check" onClick={()=>void togglePlanner(item)}>{item.completed?'✓':'○'}</button><div><span>{item.item_kind} · {item.priority}</span><strong>{item.title}</strong><small>{item.due_school_date?`Due ${item.due_school_date}`:'No due date'}</small></div><button className="danger-link" onClick={()=>void deletePlanner(item.id)}>Delete</button></article>)}{!data.planner.length&&<Empty text="Your planner is empty."/>}</div></>}
 {mode==='homeroom'&&<><Heading e="HOMEROOM HUB" t={data.homeroom?.code||'My Homeroom'} p="Your class home for advisor information, homeroom identity, shared notices, and quick access to the private room."/>{data.homeroom?<div className="homeroom-card"><span>HANAMI HIGH · 2006–07</span><h2>{data.homeroom.code}</h2><p>{data.homeroom.description||'Mixed first- and second-year homeroom.'}</p><dl><div><dt>Room</dt><dd>{data.homeroom.room_label}</dd></div><div><dt>Advisor</dt><dd>{data.homeroom.advisor_name||'TBD'}</dd></div><div><dt>Your year</dt><dd>Year {data.homeroom.student_year}</dd></div></dl><a href={`#/academics/homeroom/${data.homeroom.id}`}>Open homeroom room →</a></div>:<Empty text="You have not been assigned to a homeroom yet."/>}</>}
 {mode==='student-id'&&<><Heading e="DIGITAL STUDENT ID" t="Hanami identification card" p="Your character’s school identity. Hanami+ cosmetic ID skins can layer over this core card later."/><div className="student-id-card"><header><span>HANAMI HIGH SCHOOL</span><b>2006–07</b></header><div className="student-id-body"><div className="student-id-photo">{account?.discord_avatar_url?<img src={account.discord_avatar_url} alt=""/>:<span>花</span>}</div><div><small>STUDENT</small><h2>{name}</h2><p>@{activeCharacter?.handle}</p><dl><div><dt>Role</dt><dd>{activeCharacter?.school_role?.replace('_',' ')||'Student'}</dd></div><div><dt>Homeroom</dt><dd>{data.homeroom?.code||'Unassigned'}</dd></div><div><dt>Year</dt><dd>{data.homeroom?.student_year?`Year ${data.homeroom.student_year}`:'—'}</dd></div><div><dt>Issued</dt><dd>2006</dd></div></dl></div></div><footer><span>花見高校</span><span>School Network ID</span></footer></div></>}
 {mode==='progress'&&<><Heading e="ACADEMIC PROGRESS" t="Semester overview" p="A single view of grades, feedback, attendance, and completion signals."/><div className="portal-stat-grid"><Stat label="Grade average" value={gradeSummary===null?'—':`${gradeSummary}%`} detail={`${data.grades.length} graded item${data.grades.length===1?'':'s'}`}/><Stat label="Attendance" value={attendanceSummary===null?'—':`${attendanceSummary}%`} detail={`${data.attendance.length} recorded class meetings`}/><Stat label="Upcoming work" value={String(data.assignments.length)} detail="Published assignments"/><Stat label="Planner open" value={String(data.planner.filter(i=>!i.completed).length)} detail="Incomplete personal items"/></div><div className="portal-columns"><Panel title="Recent grades">{data.grades.slice(0,12).map((g,i)=><div className="grade-row" key={`${g.assignment_id}-${i}`}><div><strong>{g.title}</strong><small>{g.feedback||'No teacher comment'}</small></div><b>{g.points_possible?`${g.points_earned??'—'} / ${g.points_possible}`:g.points_earned??'—'}</b></div>)}{!data.grades.length&&<Empty text="No grades have been posted yet."/>}</Panel><Panel title="Attendance history">{data.attendance.slice(0,15).map((a,i)=><div className="attendance-row" key={`${a.school_date}-${i}`}><time>{a.school_date}</time><strong>{a.status}</strong><small>{a.note||''}</small></div>)}{!data.attendance.length&&<Empty text="No attendance records yet."/>}</Panel></div></>}
 {mode==='study-groups'&&<><Heading e="STUDY GROUPS" t="Private study circles" p="Create a small study space around a subject or upcoming session. Membership stays private to invited participants."/><form className="portal-form" onSubmit={createGroup}><input value={groupTitle} onChange={e=>setGroupTitle(e.target.value)} placeholder="Group name"/><input value={groupSubject} onChange={e=>setGroupSubject(e.target.value)} placeholder="Subject / class"/><button>Create study group</button></form><div className="portal-card-grid">{data.study_groups.map(g=><article key={g.id}><span>{g.subject||'Study group'}</span><h3>{g.title}</h3><p>{g.description||'Private student study space.'}</p><small>{g.next_session_at?`Next session: ${new Date(g.next_session_at).toLocaleString()}`:'No session scheduled'}</small></article>)}{!data.study_groups.length&&<Empty text="You are not in any study groups yet."/>}</div></>}
 {mode==='mailbox'&&<><Heading e="SCHOOL MAILBOX" t="Official school communications" p="Faculty, administration, homeroom, club, and system notices stay separate from normal direct messages."/><div className="mail-list">{data.mail.map(m=><article className={m.read_at?'read':'unread'} key={m.id}><div><span>{m.category}</span><strong>{m.subject}</strong><small>{new Date(m.created_at).toLocaleString()}</small></div><p>{m.body}</p>{!m.read_at&&<button onClick={()=>void markMail(m.id)}>Mark read</button>}</article>)}{!data.mail.length&&<Empty text="Your school mailbox is empty."/>}</div></>}
 {mode==='passport'&&<><Heading e="HANAMI PASSPORT" t="Your life at Hanami, stamped." p="Enrollment, school, club, social, event, achievement, and Hanami+ milestones live in one character-specific progression book."/><div className="passport-book"><div className="passport-cover"><span>花見高校</span><h2>{name}</h2><p>HANAMI PASSPORT · 2006</p><small>@{activeCharacter?.handle}</small></div><div className="passport-stamps">{data.passport.map(s=><article key={s.id}><b>{s.icon}</b><div><span>{s.category}</span><strong>{s.title}</strong><p>{s.description}</p><small>{s.school_date||new Date(s.awarded_at).toLocaleDateString()}</small></div></article>)}{!data.passport.length&&<Empty text="Your Passport is ready for its first school milestone."/>}</div></div></>}
 {mode==='bookmarks'&&<><Heading e="SAVED & RECENT" t="Your school-network shortcuts" p="Bookmark important profiles, posts, assignments, clubs, events, Boutique items, creator pages, and Help articles. Recent pages are tracked only for your own account."/><div className="portal-columns"><Panel title="Bookmarks">{data.bookmarks.map(b=><div className="bookmark-row" key={b.id}><a href={b.route_hash}><span>{b.resource_type}</span><strong>{b.label||b.resource_id}</strong></a><button onClick={()=>void removeBookmark(b.id)}>×</button></div>)}{!data.bookmarks.length&&<Empty text="You have not bookmarked anything yet."/>}</Panel><Panel title="Recently viewed">{data.recent.map((r,i)=><a className="portal-list-row" href={r.route_hash} key={`${r.resource_type}-${r.resource_id}-${i}`}><b>{r.resource_type}</b><strong>{r.label||r.resource_id}</strong><small>{new Date(r.viewed_at).toLocaleString()}</small></a>)}{!data.recent.length&&<Empty text="Recent history will appear as you browse Hanami."/>}</Panel></div></>}
 {mode==='help'&&<><Heading e="HANAMI HELP CENTER" t="How can we help?" p="Searchable guidance for accounts, profiles, Petals, academics, privacy, and school systems."/><div className="help-article-grid">{help.map(a=><details key={a.id}><summary><span>{a.category}</span><strong>{a.title}</strong><small>{a.summary}</small></summary><p>{a.body}</p></details>)}</div></>}
 </>}</main></div></section>
}

function Heading({e,t,p}:{e:string;t:string;p:string}){return <header className="portal-page-heading"><span className="eyebrow">{e}</span><h1>{t}</h1><p>{p}</p></header>}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <article className="portal-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Panel({title,children}:{title:string;children:any}){return <section className="portal-panel"><header><strong>{title}</strong></header><div>{children}</div></section>}
function Empty({text}:{text:string}){return <p className="empty-copy">{text}</p>}
