import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { presenceStorageKey, savedPresence, type HanamiPresenceStatus } from '../hooks/usePresenceHeartbeat'
import { useIdentity } from '../state/IdentityContext'
import type { HanamiCharacter } from '../types/database'

function characterName(character: HanamiCharacter) { return character.display_name || [character.first_name, character.last_name].filter(Boolean).join(' ') || `Character Slot ${character.slot_no}` }
function roleLabel(character: HanamiCharacter) { if(character.character_kind==='faculty'&&character.school_role==='new_faculty')return'New Teacher';if(character.character_kind==='faculty'&&(character.school_role==='faculty'||character.school_role===null))return'Teacher';if(character.school_role==='administration')return'Staff';if(!character.school_role)return'Applicant';return character.school_role.split('_').map(part=>part[0]?.toUpperCase()+part.slice(1)).join(' ') }
const statusMeta:Record<HanamiPresenceStatus,{label:string;description:string;icon:string}>={online:{label:'Online',description:'Available on Hanami',icon:'●'},idle:{label:'Idle',description:'Away for a bit',icon:'◔'},dnd:{label:'Do Not Disturb',description:'Suppress desktop notifications',icon:'⛔'},invisible:{label:'Invisible',description:'Appear offline to others',icon:'○'}}

export function UserPanel(){
 const {activeCharacter,characters,selectCharacter,clearActiveCharacter,isOwner,isPlatformAdmin,enterOwnerMode,enterAdminMode,signOut,mutating}=useIdentity();const[presence,setPresenceState]=useState<HanamiPresenceStatus>('online');const[statusOpen,setStatusOpen]=useState(false)
 useEffect(()=>{if(activeCharacter)setPresenceState(savedPresence(activeCharacter.id))},[activeCharacter])
 if(!activeCharacter)return null
 const name=characterName(activeCharacter),initials=name.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()
 async function setPresence(status:HanamiPresenceStatus){const client=supabase;if(!client||!activeCharacter)return;localStorage.setItem(presenceStorageKey(activeCharacter.id),status);setPresenceState(status);setStatusOpen(false);const now=new Date().toISOString();await client.from('character_presence').upsert({character_id:activeCharacter.id,account_id:activeCharacter.account_id,status,current_section:null,current_subsection:null,last_seen_at:now,updated_at:now},{onConflict:'character_id'});window.dispatchEvent(new CustomEvent('hanami-presence-change',{detail:{characterId:activeCharacter.id}}))}
 return <div className="user-panel discord-user-panel">
   <button className="discord-user-identity" type="button" onClick={()=>setStatusOpen(open=>!open)}><div className="avatar-placeholder">{initials}<span className={`presence-dot status-${presence}`}/></div><div className="user-copy"><strong>{name}</strong><span>{presence==='dnd'?'Do Not Disturb':presence==='invisible'?'Invisible':statusMeta[presence].label}</span></div></button>
   <div className="discord-user-quick-actions"><button type="button" title="Mute">♩</button><button type="button" title="Deafen">◉</button></div>
   {statusOpen&&<div className="discord-presence-popover">{(Object.keys(statusMeta) as HanamiPresenceStatus[]).map(status=><button type="button" key={status} className={presence===status?'active':''} onClick={()=>void setPresence(status)}><span className={`presence-choice status-${status}`}>{statusMeta[status].icon}</span><div><strong>{statusMeta[status].label}</strong><small>{statusMeta[status].description}</small></div>{presence===status&&<b>✓</b>}</button>)}</div>}
   <details className="user-menu"><summary title="Character and account menu">⚙</summary><div className="user-menu-popover"><span className="user-menu-label">PROFILE</span><a href="#/profile/view-profile">View Profile</a><a href="#/profile/profile-studio">Edit Profile</a><div className="user-menu-rule"/><span className="user-menu-label">SWITCH CHARACTER</span>{characters.map(character=><button key={character.id} type="button" disabled={mutating||character.character_state!=='active'||character.id===activeCharacter.id} onClick={()=>void selectCharacter(character.id)}>{character.id===activeCharacter.id?'✓ ':''}{characterName(character)} · {character.character_state==='active'?roleLabel(character):character.character_state}</button>)}<button type="button" disabled={mutating} onClick={()=>void clearActiveCharacter()}>Character selection…</button>{(isOwner||isPlatformAdmin)&&<div className="user-menu-rule"/>}{isOwner&&<><span className="user-menu-label">OWNER</span><button type="button" onClick={enterOwnerMode}>Open Owner Console</button></>}{isPlatformAdmin&&<><span className="user-menu-label">ADMINISTRATOR</span><button type="button" onClick={enterAdminMode}>Open Administrator Console</button></>}<div className="user-menu-rule"/><button type="button" onClick={()=>void signOut()}>Sign out</button></div></details>
 </div>
}
