"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
const CHARACTER_KEY="hanami.portal.character.v1";
type Session={accessToken:string};
type Journal={id:string;title:string;body:string;visibility:string;created_at:string};
type Guestbook={id:string;body:string;status:string;created_at:string};
type Group={id:string;name:string;subject:string|null;meeting_location:string|null;meeting_schedule:string|null;status:string};
type Presence={status_kind:string;status_message:string|null};
type Locker={id:string;title:string;visibility:string};
type Relationship={id:string;relationship_type:string;label:string|null;visibility:string;target_character_id:string};
type Character={id:string;display_name:string;handle:string};
function auth(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)??"null") as Session|null}catch{return null}}
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,...extra}}
const card:React.CSSProperties={border:"1px solid #c8cdd6",background:"#fff",padding:16,boxShadow:"0 1px 2px rgba(0,0,0,.05)"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:"9px 10px",border:"1px solid #aeb6c2",font:"inherit",background:"#fff"};
const button:React.CSSProperties={padding:"9px 12px",border:"1px solid #45556e",background:"#304b72",color:"white",fontWeight:700,cursor:"pointer"};

export default function StudentExperiencePage(){
 const [token,setToken]=useState("");const [characterId,setCharacterId]=useState("");const [me,setMe]=useState<Character|null>(null);const [message,setMessage]=useState("Opening your Student Experience Hub…");
 const [presence,setPresence]=useState<Presence>({status_kind:"available",status_message:""});const [journals,setJournals]=useState<Journal[]>([]);const [guestbook,setGuestbook]=useState<Guestbook[]>([]);const [groups,setGroups]=useState<Group[]>([]);const [relationships,setRelationships]=useState<Relationship[]>([]);const [locker,setLocker]=useState<Locker|null>(null);
 const [journalTitle,setJournalTitle]=useState("");const [journalBody,setJournalBody]=useState("");const [journalVisibility,setJournalVisibility]=useState("private");const [lockerNote,setLockerNote]=useState("");const [confession,setConfession]=useState("");const [newspaperWhy,setNewspaperWhy]=useState("");const [writingSample,setWritingSample]=useState("");const [targetHandle,setTargetHandle]=useState("");const [relationshipType,setRelationshipType]=useState("friend");const [relationshipLabel,setRelationshipLabel]=useState("");
 const [qEnabled,setQEnabled]=useState(true);const [qAnonymous,setQAnonymous]=useState(true);const [studySeconds,setStudySeconds]=useState(0);const [studying,setStudying]=useState(false);const timerRef=useRef<number|null>(null);
 const minutes=useMemo(()=>Math.floor(studySeconds/60),[studySeconds]);
 useEffect(()=>{const session=auth();const cid=localStorage.getItem(CHARACTER_KEY)??"";if(!session?.accessToken||!cid){setMessage("Sign in and choose a character before opening this hub.");return;}setToken(session.accessToken);setCharacterId(cid);void load(session.accessToken,cid);return()=>{if(timerRef.current)window.clearInterval(timerRef.current)}},[]);
 async function load(accessToken:string,cid:string){try{const h=headers(accessToken);const [meR,pR,jR,gR,sR,lR,relR,qR]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&id=eq.${encodeURIComponent(cid)}&limit=1`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/character_presence?select=status_kind,status_message&character_id=eq.${encodeURIComponent(cid)}&limit=1`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/character_journals?select=id,title,body,visibility,created_at&character_id=eq.${encodeURIComponent(cid)}&order=created_at.desc&limit=20`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/profile_guestbook_entries?select=id,body,status,created_at&profile_character_id=eq.${encodeURIComponent(cid)}&order=created_at.desc&limit=20`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/study_groups?select=id,name,subject,meeting_location,meeting_schedule,status&status=eq.open&order=created_at.desc&limit=20`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/student_lockers?select=id,title,visibility&character_id=eq.${encodeURIComponent(cid)}&limit=1`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/character_relationships?select=id,relationship_type,label,visibility,target_character_id&source_character_id=eq.${encodeURIComponent(cid)}&order=updated_at.desc&limit=30`,{headers:h}),
  fetch(`${SUPABASE_URL}/rest/v1/anonymous_question_settings?select=enabled,allow_anonymous&character_id=eq.${encodeURIComponent(cid)}&limit=1`,{headers:h})]);
  if(meR.ok)setMe((await meR.json())[0]??null);if(pR.ok)setPresence((await pR.json())[0]??{status_kind:"available",status_message:""});if(jR.ok)setJournals(await jR.json());if(gR.ok)setGuestbook(await gR.json());if(sR.ok)setGroups(await sR.json());if(relR.ok)setRelationships(await relR.json());if(qR.ok){const q=(await qR.json())[0];if(q){setQEnabled(q.enabled);setQAnonymous(q.allow_anonymous)}}
  if(lR.ok){const found=(await lR.json())[0]??null;if(found)setLocker(found);else{const created=await fetch(`${SUPABASE_URL}/rest/v1/student_lockers`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify({character_id:cid})});if(created.ok)setLocker((await created.json())[0]??null)}}setMessage("Your Student Experience Hub is ready.");
 }catch{setMessage("Some Student Experience systems could not be loaded.")}}
 async function saveStatus(e:FormEvent){e.preventDefault();if(!token)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/character_presence?on_conflict=character_id`,{method:"POST",headers:headers(token,{"Content-Type":"application/json","Prefer":"resolution=merge-duplicates"}),body:JSON.stringify({character_id:characterId,...presence,updated_at:new Date().toISOString()})});setMessage(r.ok?"Status updated.":"Status could not be updated.")}
 async function addJournal(e:FormEvent){e.preventDefault();if(!token||!journalTitle.trim()||!journalBody.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/character_journals`,{method:"POST",headers:headers(token,{"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify({character_id:characterId,title:journalTitle.trim(),body:journalBody.trim(),visibility:journalVisibility,published_at:journalVisibility==="private"?null:new Date().toISOString()})});if(r.ok){setJournals([...(await r.json()),...journals]);setJournalTitle("");setJournalBody("");setMessage("Journal entry saved.")}else setMessage("Journal entry could not be saved.")}
 async function addLockerNote(e:FormEvent){e.preventDefault();if(!token||!locker||!lockerNote.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/locker_items`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({locker_id:locker.id,item_type:"note",label:lockerNote.trim(),x:20,y:20})});if(r.ok){setLockerNote("");setMessage("Locker note added. Drag-and-drop locker design is the next visual layer.")}else setMessage("Locker item could not be added.")}
 async function saveQuestions(){if(!token)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/anonymous_question_settings?on_conflict=character_id`,{method:"POST",headers:headers(token,{"Content-Type":"application/json","Prefer":"resolution=merge-duplicates"}),body:JSON.stringify({character_id:characterId,enabled:qEnabled,allow_anonymous:qAnonymous,moderation_mode:"owner_review",updated_at:new Date().toISOString()})});setMessage(r.ok?"Question-box settings saved.":"Question-box settings could not be saved.")}
 async function submitConfession(e:FormEvent){e.preventDefault();if(!token||!confession.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/school_confessions`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({author_character_id:characterId,body:confession.trim(),is_anonymous:true,status:"pending"})});if(r.ok){setConfession("");setMessage("Confession submitted for moderation.")}else setMessage("Confession could not be submitted.")}
 async function submitNewspaper(e:FormEvent){e.preventDefault();if(!token||!newspaperWhy.trim()||!writingSample.trim())return;const r=await fetch(`${SUPABASE_URL}/rest/v1/newspaper_applications`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({character_id:characterId,writing_sample:writingSample.trim(),why_join:newspaperWhy.trim(),interests:["school news"],status:"submitted"})});if(r.ok){setWritingSample("");setNewspaperWhy("");setMessage("Newspaper application sent to Administration and Owner review.")}else setMessage("Newspaper application could not be submitted.")}
 async function addRelationship(e:FormEvent){e.preventDefault();if(!token||!targetHandle.trim())return;const lookup=await fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&handle=eq.${encodeURIComponent(targetHandle.trim().replace(/^@/,""))}&limit=1`,{headers:headers(token)});const target=lookup.ok?(await lookup.json())[0] as Character|undefined:undefined;if(!target){setMessage("That character handle could not be found.");return;}const r=await fetch(`${SUPABASE_URL}/rest/v1/character_relationships`,{method:"POST",headers:headers(token,{"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify({source_character_id:characterId,target_character_id:target.id,relationship_type:relationshipType,label:relationshipLabel.trim()||null,visibility:"friends_only"})});if(r.ok){setRelationships([...(await r.json()),...relationships]);setTargetHandle("");setRelationshipLabel("");setMessage("Platonic relationship added.")}else setMessage("Relationship could not be added.")}
 function toggleTimer(){if(studying){if(timerRef.current)window.clearInterval(timerRef.current);timerRef.current=null;setStudying(false);return;}setStudying(true);timerRef.current=window.setInterval(()=>setStudySeconds(v=>v+1),1000)}
 async function saveStudy(){if(!token||studySeconds<1)return;const r=await fetch(`${SUPABASE_URL}/rest/v1/study_sessions`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify({character_id:characterId,started_at:new Date(Date.now()-studySeconds*1000).toISOString(),ended_at:new Date().toISOString(),duration_minutes:Math.max(1,Math.round(studySeconds/60))})});if(r.ok){setStudySeconds(0);setMessage("Study session saved.")}else setMessage("Study session could not be saved.")}
 if(!token||!characterId)return <main style={{maxWidth:900,margin:"40px auto",padding:20}}><h1>Student Experience Hub</h1><p>{message}</p><a href="../">Return to Portal</a></main>;
 return <main style={{maxWidth:1180,margin:"28px auto 80px",padding:"0 18px",fontFamily:"Arial,Helvetica,sans-serif",color:"#24344d"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"end",flexWrap:"wrap",marginBottom:18}}><div><p style={{fontSize:11,fontWeight:800,letterSpacing:".12em",margin:0,color:"#8f365b"}}>HANAMI STUDENT EXPERIENCE</p><h1 style={{font:"400 36px Georgia,serif",margin:"5px 0"}}>{me?.display_name??"Your"} school life hub</h1><p style={{maxWidth:760,margin:0}}>Social, roleplay, study, school-life, and customization tools in one place. Relationships are strictly platonic.</p></div><div style={{display:"flex",gap:8}}><a href="../student/">Student Portal</a><a href="../../features/">Feature Center</a></div></header>
  <p style={{padding:10,border:"1px solid #d9c576",background:"#fff8dc",marginBottom:16}}>{message}</p>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(310px,1fr))",gap:14}}>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Custom status</h2><form onSubmit={saveStatus} style={{display:"grid",gap:8}}><select style={input} value={presence.status_kind} onChange={e=>setPresence({...presence,status_kind:e.target.value})}><option value="available">At school</option><option value="class">In class</option><option value="club">At club</option><option value="studying">Studying</option><option value="away">Away</option></select><input style={input} maxLength={120} placeholder="Studying in the library…" value={presence.status_message??""} onChange={e=>setPresence({...presence,status_message:e.target.value})}/><button style={button}>Save status</button></form></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Virtual locker</h2><p>{locker?.title??"Creating locker…"} · {locker?.visibility??"private"}</p><form onSubmit={addLockerNote} style={{display:"grid",gap:8}}><input style={input} placeholder="Add a note or memory…" value={lockerNote} onChange={e=>setLockerNote(e.target.value)}/><button style={button}>Add locker note</button></form><small>Sticker/photo placement data is supported; the drag-and-drop designer is being layered onto this foundation.</small></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Character journal</h2><form onSubmit={addJournal} style={{display:"grid",gap:8}}><input style={input} placeholder="Entry title" value={journalTitle} onChange={e=>setJournalTitle(e.target.value)}/><textarea style={{...input,minHeight:100}} placeholder="Write a roleplay diary entry…" value={journalBody} onChange={e=>setJournalBody(e.target.value)}/><select style={input} value={journalVisibility} onChange={e=>setJournalVisibility(e.target.value)}><option value="private">Private</option><option value="friends_only">Friends only</option><option value="public">Public</option></select><button style={button}>Save entry</button></form>{journals.slice(0,3).map(j=><article key={j.id} style={{borderTop:"1px solid #e3e6ea",marginTop:10,paddingTop:9}}><strong>{j.title}</strong><small style={{display:"block"}}>{j.visibility}</small></article>)}</section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Platonic relationships</h2><form onSubmit={addRelationship} style={{display:"grid",gap:8}}><input style={input} placeholder="@character_handle" value={targetHandle} onChange={e=>setTargetHandle(e.target.value)}/><select style={input} value={relationshipType} onChange={e=>setRelationshipType(e.target.value)}><option>friend</option><option>best_friend</option><option>classmate</option><option>teammate</option><option>clubmate</option><option>sibling</option><option>cousin</option><option>mentor</option><option>mentee</option><option>acquaintance</option><option>rival</option><option>neighbor</option><option>coworker</option><option value="other_platonic">other platonic</option></select><input style={input} placeholder="Optional label" value={relationshipLabel} onChange={e=>setRelationshipLabel(e.target.value)}/><button style={button}>Add relationship</button></form><small>{relationships.length} relationship{relationships.length===1?"":"s"} on your page.</small></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Profile guestbook / wall</h2><p>{guestbook.length} recent wall entr{guestbook.length===1?"y":"ies"}.</p>{guestbook.slice(0,5).map(g=><blockquote key={g.id} style={{margin:"8px 0",padding:"8px 10px",borderLeft:"3px solid #aab4c4",background:"#f6f7f9"}}>{g.body}<small style={{display:"block"}}>{g.status}</small></blockquote>)}</section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Anonymous question box</h2><label style={{display:"block",marginBottom:8}}><input type="checkbox" checked={qEnabled} onChange={e=>setQEnabled(e.target.checked)}/> Enable my question box</label><label style={{display:"block",marginBottom:10}}><input type="checkbox" checked={qAnonymous} onChange={e=>setQAnonymous(e.target.checked)}/> Allow anonymous questions</label><button style={button} onClick={saveQuestions}>Save question settings</button><p><small>Moderation defaults to Owner/Admin review controls.</small></p></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>School confession board</h2><form onSubmit={submitConfession} style={{display:"grid",gap:8}}><textarea style={{...input,minHeight:90}} placeholder="Submit an anonymous school confession…" value={confession} onChange={e=>setConfession(e.target.value)}/><button style={button}>Submit for moderation</button></form><small>Nothing is public until approved by staff.</small></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Study timer</h2><div style={{font:"700 32px monospace",marginBottom:10}}>{String(minutes).padStart(2,"0")}:{String(studySeconds%60).padStart(2,"0")}</div><div style={{display:"flex",gap:8}}><button style={button} onClick={toggleTimer}>{studying?"Pause":"Start"}</button><button style={button} onClick={saveStudy} disabled={!studySeconds}>Save session</button></div><p><small>Saved sessions feed optional study streaks and progress badges.</small></p></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>Study-group finder</h2>{groups.length?groups.slice(0,6).map(g=><article key={g.id} style={{borderTop:"1px solid #e3e6ea",padding:"8px 0"}}><strong>{g.name}</strong><small style={{display:"block"}}>{g.subject??"General"} · {g.meeting_schedule??"Schedule TBD"} · {g.meeting_location??"Location TBD"}</small></article>):<p>No open study groups yet.</p>}</section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>School newspaper application</h2><p>Students must be approved before becoming Hanami newspaper writers.</p><form onSubmit={submitNewspaper} style={{display:"grid",gap:8}}><textarea style={{...input,minHeight:90}} placeholder="Why do you want to join the newspaper?" value={newspaperWhy} onChange={e=>setNewspaperWhy(e.target.value)}/><textarea style={{...input,minHeight:110}} placeholder="Writing sample" value={writingSample} onChange={e=>setWritingSample(e.target.value)}/><button style={button}>Send application</button></form><small>Applications are visible to Administration and Owner review.</small></section>
   <section style={card}><h2 style={{font:"400 22px Georgia,serif"}}>More school-life systems</h2><p>Seating charts, PA broadcasts, recruitment week, festival planning, elections, RSVPs, festival passports, honors, graduation progress, hall passes, volunteer hours, mentorship, birthday board, transit, moderation appeals, handbook acknowledgements, homeroom competitions, office hours, and more are tracked in the Feature Center as they are connected to portal screens.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><a href="../../features/">Open Feature Center</a><a href="../../ideas/">Feature Request Board</a><a href="../../changelog/">Website Changelog</a></div></section>
  </div>
 </main>
}
