"use client";

import {useCallback,useEffect,useState} from "react";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Lore={id:string;title:string;slug:string;category:string;summary:string;body:string;status:string};
type Canon={id:string;subject:string;fact:string;classification:string;source_note:string};
const card:React.CSSProperties={border:"1px solid #cad2dc",background:"#fff",padding:10};
export default function AdminLoreCanonEditor({accessToken}:{accessToken:string}){
 const [lore,setLore]=useState<Lore[]>([]),[canon,setCanon]=useState<Canon[]>([]),[notice,setNotice]=useState("Loading editorial workspace…"),[busy,setBusy]=useState(false);
 const [loreEdits,setLoreEdits]=useState<Record<string,Lore>>({}),[canonEdits,setCanonEdits]=useState<Record<string,Canon>>({});
 const load=useCallback(async()=>{try{const [lr,cr]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/lore_pages?select=id,title,slug,category,summary,body,status&order=updated_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/canon_facts?select=id,subject,fact,classification,source_note&order=created_at.desc`,{headers:headers(accessToken)})]);if(!lr.ok||!cr.ok)throw new Error("Editorial data could not be loaded.");const l=await lr.json() as Lore[],c=await cr.json() as Canon[];setLore(l);setCanon(c);setLoreEdits(Object.fromEntries(l.map(x=>[x.id,{...x}])));setCanonEdits(Object.fromEntries(c.map(x=>[x.id,{...x}])));setNotice("Lore and canon editorial workspace ready.");}catch(error){setNotice(error instanceof Error?error.message:"Editorial workspace could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function saveLore(id:string){const row=loreEdits[id];if(!row)return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/lore_pages?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({title:row.title.trim(),category:row.category,summary:row.summary.trim(),body:row.body.trim(),status:row.status,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Lore article could not be saved.");setNotice(`Saved ${row.title}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Lore article could not be saved.");}finally{setBusy(false);}}
 async function saveCanon(id:string){const row=canonEdits[id];if(!row)return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/canon_facts?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({subject:row.subject.trim(),fact:row.fact.trim(),classification:row.classification,source_note:row.source_note.trim()})});if(!r.ok)throw new Error("Canon entry could not be saved.");setNotice(`Updated canon entry for ${row.subject}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Canon entry could not be saved.");}finally{setBusy(false);}}
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14}} aria-label="Lore and canon editor"><p className="eyebrow">LORE & CANON EDITORIAL</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Living Wiki & Canon Desk</h3><small>{notice}</small><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:12,marginTop:12}}>
 <article style={card}><h4>Lore Articles</h4>{lore.length?lore.map(base=>{const row=loreEdits[base.id]??base;return <details key={base.id} style={{borderTop:"1px solid #e1e6eb",padding:"7px 0"}}><summary><strong>{base.title}</strong> • {base.status}</summary><div style={{display:"grid",gap:5,marginTop:7}}><input value={row.title} onChange={e=>setLoreEdits(v=>({...v,[base.id]:{...row,title:e.target.value}}))}/><select value={row.category} onChange={e=>setLoreEdits(v=>({...v,[base.id]:{...row,category:e.target.value}}))}>{["school_history","city_history","neighborhood","tradition","event","principal","alumni","location","other"].map(x=><option key={x}>{x}</option>)}</select><textarea rows={2} value={row.summary} onChange={e=>setLoreEdits(v=>({...v,[base.id]:{...row,summary:e.target.value}}))} placeholder="Short summary"/><textarea rows={8} value={row.body} onChange={e=>setLoreEdits(v=>({...v,[base.id]:{...row,body:e.target.value}}))} placeholder="Full lore article"/><select value={row.status} onChange={e=>setLoreEdits(v=>({...v,[base.id]:{...row,status:e.target.value}}))}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><button disabled={busy} onClick={()=>void saveLore(base.id)}>Save lore article</button></div></details>}):<p>No lore articles yet.</p>}</article>
 <article style={card}><h4>Canon Tracker</h4>{canon.length?canon.map(base=>{const row=canonEdits[base.id]??base;return <details key={base.id} style={{borderTop:"1px solid #e1e6eb",padding:"7px 0"}}><summary><strong>{base.subject}</strong> • {base.classification}</summary><div style={{display:"grid",gap:5,marginTop:7}}><input value={row.subject} onChange={e=>setCanonEdits(v=>({...v,[base.id]:{...row,subject:e.target.value}}))}/><textarea rows={4} value={row.fact} onChange={e=>setCanonEdits(v=>({...v,[base.id]:{...row,fact:e.target.value}}))}/><select value={row.classification} onChange={e=>setCanonEdits(v=>({...v,[base.id]:{...row,classification:e.target.value}}))}><option value="confirmed">Confirmed canon</option><option value="rumor">Rumor</option><option value="headcanon">Headcanon</option><option value="retconned">Retconned</option></select><textarea rows={2} value={row.source_note} onChange={e=>setCanonEdits(v=>({...v,[base.id]:{...row,source_note:e.target.value}}))} placeholder="Source/session/retcon note"/><button disabled={busy} onClick={()=>void saveCanon(base.id)}>Save canon entry</button></div></details>}):<p>No canon entries yet.</p>}</article>
 </div></section>;
}
