"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import styles from "./AdminScheduleManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const DAYS=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
type Tab="catalog"|"sections"|"homerooms"|"schedule"|"rosters"|"faculty"|"periods";
type Course={id:string;code:string;title:string;department:string;description:string;credits:number};
type Section={id:string;course_id:string;section_code:string;term:string;room:string|null;capacity:number};
type Homeroom={id:string;code:string;name:string;school_year:string;is_active:boolean;sort_order:number};
type Period={id:string;period_number:number;label:string;starts_at:string;ends_at:string;is_instructional:boolean;is_active:boolean};
type Assignment={id:string;homeroom_id:string;weekday:number;period_id:string;section_id:string|null;activity_title:string|null;instructor_character_id:string|null;room:string|null;notes:string|null};
type DirectoryRow={character_id:string;display_name:string;handle:string;role:"student"|"faculty"};
type Membership={section_id:string;relationship:"student"|"instructor"};
type Props={accessToken:string};

function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
async function apiError(response:Response,fallback:string){try{const data=await response.json() as {message?:string;details?:string;hint?:string;code?:string};const detail=[data.message,data.details,data.hint].filter(Boolean).join(" ");if(data.code==="23505"||/duplicate key|unique constraint/i.test(detail))return "That slot conflicts with an existing homeroom, teacher, room, course code, or period number.";if(/Academic manager access required|permission denied|not authorized/i.test(detail))return "Owner or Site Admin authorization could not be verified. Reopen the privileged portal and try again.";return detail||fallback;}catch{return fallback;}}
function clock(value:string){const [h,m]=value.split(":");const hour=Number(h);return `${hour%12||12}:${m} ${hour>=12?"PM":"AM"}`;}

export default function AdminScheduleManager({accessToken}:Props){
 const [tab,setTab]=useState<Tab>("catalog");const [courses,setCourses]=useState<Course[]>([]);const [sections,setSections]=useState<Section[]>([]);const [homerooms,setHomerooms]=useState<Homeroom[]>([]);const [periods,setPeriods]=useState<Period[]>([]);const [assignments,setAssignments]=useState<Assignment[]>([]);const [directory,setDirectory]=useState<DirectoryRow[]>([]);const [memberships,setMemberships]=useState<Membership[]>([]);const [notice,setNotice]=useState("Loading academic scheduling…");const [saving,setSaving]=useState(false);
 const [courseCode,setCourseCode]=useState("");const [courseTitle,setCourseTitle]=useState("");const [department,setDepartment]=useState("");const [description,setDescription]=useState("");const [credits,setCredits]=useState(1);
 const [sectionCourse,setSectionCourse]=useState("");const [sectionCode,setSectionCode]=useState("A");const [term,setTerm]=useState("2006-2007");const [sectionRoom,setSectionRoom]=useState("");const [capacity,setCapacity]=useState(24);
 const [homeCode,setHomeCode]=useState("");const [homeName,setHomeName]=useState("");const [schoolYear,setSchoolYear]=useState("2006-2007");
 const [periodNumber,setPeriodNumber]=useState(7);const [periodLabel,setPeriodLabel]=useState("Period 7");const [periodStart,setPeriodStart]=useState("15:10");const [periodEnd,setPeriodEnd]=useState("16:00");const [instructional,setInstructional]=useState(true);
 const [scheduleHomeroom,setScheduleHomeroom]=useState("");const [weekday,setWeekday]=useState(1);const [schedulePeriod,setSchedulePeriod]=useState("");const [scheduleSection,setScheduleSection]=useState("");const [activityTitle,setActivityTitle]=useState("");const [teacherId,setTeacherId]=useState("");const [scheduleRoom,setScheduleRoom]=useState("");const [scheduleNotes,setScheduleNotes]=useState("");
 const [rosterSection,setRosterSection]=useState("");const [rosterHandle,setRosterHandle]=useState("");

 const load=useCallback(async()=>{try{const [courseRes,sectionRes,homeRes,periodRes,assignmentRes,membershipRes,directoryRes]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=id,code,title,department,description,credits&order=code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,course_id,section_code,term,room,capacity&order=term.desc,section_code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_homerooms?select=id,code,name,school_year,is_active,sort_order&order=sort_order.asc,code.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_periods?select=id,period_number,label,starts_at,ends_at,is_instructional,is_active&order=period_number.asc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/school_schedule_assignments?select=id,homeroom_id,weekday,period_id,section_id,activity_title,instructor_character_id,room,notes`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id,relationship`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/administration_character_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({search_term:null})})
 ]);if(!courseRes.ok||!sectionRes.ok||!homeRes.ok||!periodRes.ok||!assignmentRes.ok)throw new Error("Academic scheduling records could not be loaded. Apply the scheduling migration before using this workspace.");const nextCourses=await courseRes.json() as Course[];const nextSections=await sectionRes.json() as Section[];const nextHomes=await homeRes.json() as Homeroom[];const nextPeriods=await periodRes.json() as Period[];setCourses(nextCourses);setSections(nextSections);setHomerooms(nextHomes);setPeriods(nextPeriods);setAssignments(await assignmentRes.json() as Assignment[]);setMemberships(membershipRes.ok?await membershipRes.json() as Membership[]:[]);setDirectory(directoryRes.ok?(await directoryRes.json() as DirectoryRow[]):[]);if(!sectionCourse&&nextCourses[0])setSectionCourse(nextCourses[0].id);if(!scheduleHomeroom&&nextHomes[0])setScheduleHomeroom(nextHomes[0].id);if(!schedulePeriod&&nextPeriods[0])setSchedulePeriod(nextPeriods[0].id);if(!scheduleSection&&nextSections[0])setScheduleSection(nextSections[0].id);if(!rosterSection&&nextSections[0])setRosterSection(nextSections[0].id);setNotice(`${nextCourses.length} courses • ${nextSections.length} sections • ${nextHomes.length} homerooms loaded.`);}catch(error){setNotice(error instanceof Error?error.message:"Academic scheduling could not be loaded.");}},[accessToken,sectionCourse,scheduleHomeroom,schedulePeriod,scheduleSection,rosterSection]);
 useEffect(()=>{void load();},[load]);
 const faculty=directory.filter(row=>row.role==="faculty");
 const courseName=(id:string)=>{const c=courses.find(item=>item.id===id);return c?`${c.code} • ${c.title}`:"Unknown course";};
 const sectionName=(id:string|null)=>{if(!id)return "";const s=sections.find(item=>item.id===id);return s?`${courseName(s.course_id)} • ${s.section_code}`:"Unknown section";};
 const teacherName=(id:string|null)=>{if(!id)return "Faculty TBA";const row=faculty.find(item=>item.character_id===id);return row?row.display_name:"Faculty TBA";};
 const activePeriods=periods.filter(item=>item.is_active);const activeHomes=homerooms.filter(item=>item.is_active);
 const selectedAssignments=useMemo(()=>assignments.filter(item=>item.homeroom_id===scheduleHomeroom),[assignments,scheduleHomeroom]);
 async function createCourse(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_create_academic_course`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_code:courseCode.trim().toUpperCase(),requested_title:courseTitle.trim(),requested_department:department.trim(),requested_description:description.trim(),requested_credits:credits})});if(!response.ok)throw new Error(await apiError(response,"The course could not be created."));setCourseCode("");setCourseTitle("");setDepartment("");setDescription("");setCredits(1);await load();setNotice("Course created.");}catch(error){setNotice(error instanceof Error?error.message:"The course could not be created.");}finally{setSaving(false);}}
 async function createSection(event:FormEvent){event.preventDefault();if(!sectionCourse)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/class_sections`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=minimal"}),body:JSON.stringify({course_id:sectionCourse,section_code:sectionCode.trim(),term:term.trim(),room:sectionRoom.trim()||null,capacity})});if(!response.ok)throw new Error(await apiError(response,"The section could not be created."));setSectionCode("A");setSectionRoom("");await load();setNotice("Section created.");}catch(error){setNotice(error instanceof Error?error.message:"The section could not be created.");}finally{setSaving(false);}}
 async function createHomeroom(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_homerooms`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=minimal"}),body:JSON.stringify({code:homeCode.trim().toUpperCase(),name:homeName.trim(),school_year:schoolYear.trim(),sort_order:homerooms.length+1})});if(!response.ok)throw new Error(await apiError(response,"The homeroom could not be created."));setHomeCode("");setHomeName("");await load();setNotice("Homeroom created.");}catch(error){setNotice(error instanceof Error?error.message:"The homeroom could not be created.");}finally{setSaving(false);}}
 async function createPeriod(event:FormEvent){event.preventDefault();setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_periods`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=minimal"}),body:JSON.stringify({period_number:periodNumber,label:periodLabel.trim(),starts_at:periodStart,ends_at:periodEnd,is_instructional:instructional})});if(!response.ok)throw new Error(await apiError(response,"The period could not be created."));setPeriodNumber(value=>value+1);setPeriodLabel(`Period ${periodNumber+1}`);await load();setNotice("Period created.");}catch(error){setNotice(error instanceof Error?error.message:"The period could not be created.");}finally{setSaving(false);}}
 async function saveSchedule(event:FormEvent){event.preventDefault();if(!scheduleHomeroom||!schedulePeriod||(!scheduleSection&&!activityTitle.trim()))return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_schedule_assignments`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json","Prefer":"return=minimal"}),body:JSON.stringify({homeroom_id:scheduleHomeroom,weekday,period_id:schedulePeriod,section_id:scheduleSection||null,activity_title:scheduleSection?null:activityTitle.trim(),instructor_character_id:teacherId||null,room:scheduleRoom.trim()||null,notes:scheduleNotes.trim()||null})});if(!response.ok)throw new Error(await apiError(response,"The schedule assignment could not be saved."));setActivityTitle("");setScheduleNotes("");await load();setNotice("Schedule assignment saved.");}catch(error){setNotice(error instanceof Error?error.message:"The schedule assignment could not be saved.");}finally{setSaving(false);}}
 async function removeSchedule(id:string){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_schedule_assignments?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers(accessToken,{"Prefer":"return=minimal"})});if(!response.ok)throw new Error(await apiError(response,"The schedule assignment could not be removed."));await load();setNotice("Schedule assignment removed.");}catch(error){setNotice(error instanceof Error?error.message:"The schedule assignment could not be removed.");}finally{setSaving(false);}}
 async function assignCharacter(event:FormEvent,relationship:"student"|"instructor"){event.preventDefault();if(!rosterSection)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_assign_character_to_section`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_section_id:rosterSection,target_handle:rosterHandle.trim().replace(/^@/,"").toLowerCase(),target_relationship:relationship})});if(!response.ok)throw new Error(await apiError(response,"The class assignment could not be saved."));setRosterHandle("");await load();setNotice(relationship==="student"?"Student enrollment saved.":"Faculty assignment saved.");}catch(error){setNotice(error instanceof Error?error.message:"The class assignment could not be saved.");}finally{setSaving(false);}}
 const tabs:[Tab,string][]=[["catalog","Course Catalog"],["sections","Sections"],["homerooms","Homerooms"],["schedule","Weekly Schedule"],["rosters","Rosters"],["faculty","Faculty Assignments"],["periods","Period Settings"]];
 return <section className={styles.panel} aria-labelledby="academic-schedule-title"><div className={styles.toolbar}><div><p className="eyebrow">ACADEMIC MANAGEMENT</p><h3 id="academic-schedule-title">Courses & Scheduling</h3><p>Create future classes and assign each homeroom independently by day and period.</p></div></div><nav className={styles.tabs} aria-label="Course management tabs">{tabs.map(([key,label])=><button key={key} type="button" className={tab===key?styles.active:""} onClick={()=>setTab(key)}>{label}</button>)}</nav><div className={styles.notice} aria-live="polite">{notice}</div>
 {tab==="catalog"&&<><form className={styles.form} onSubmit={createCourse}><label><span>Course code</span><input value={courseCode} onChange={e=>setCourseCode(e.target.value)} placeholder="MATH-101" pattern="[A-Za-z]{2,6}-[0-9]{3}" required/></label><label><span>Course title</span><input value={courseTitle} onChange={e=>setCourseTitle(e.target.value)} placeholder="Mathematical Reasoning" required/></label><label><span>Department</span><input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Mathematics" required/></label><label><span>Credits</span><input type="number" min="1" max="6" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><label><span>Description</span><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Course description"/></label><button disabled={saving}>Create course</button></form><div className={styles.list}>{courses.map(course=><div className={styles.row} key={course.id}><strong>{course.code}</strong><div><b>{course.title}</b><small>{course.department} • {course.credits} credit{course.credits===1?"":"s"}</small></div><small>{course.description||"No description yet."}</small></div>)}</div></>}
 {tab==="sections"&&<><form className={styles.form} onSubmit={createSection}><label><span>Course</span><select value={sectionCourse} onChange={e=>setSectionCourse(e.target.value)}>{courses.map(course=><option key={course.id} value={course.id}>{course.code} • {course.title}</option>)}</select></label><label><span>Section / homeroom code</span><input value={sectionCode} onChange={e=>setSectionCode(e.target.value)} required/></label><label><span>Term</span><input value={term} onChange={e=>setTerm(e.target.value)} required/></label><label><span>Default room</span><input value={sectionRoom} onChange={e=>setSectionRoom(e.target.value)}/></label><label><span>Capacity</span><input type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><button disabled={saving||!courses.length}>Create section</button></form><div className={styles.list}>{sections.map(section=><div className={styles.row} key={section.id}><strong>{section.section_code}</strong><div><b>{courseName(section.course_id)}</b><small>{section.term} • {section.room?`Room ${section.room}`:"Room TBA"}</small></div><small>{memberships.filter(row=>row.section_id===section.id&&row.relationship==="student").length}/{section.capacity} students</small></div>)}</div></>}
 {tab==="homerooms"&&<><form className={styles.form} onSubmit={createHomeroom}><label><span>Code</span><input value={homeCode} onChange={e=>setHomeCode(e.target.value)} placeholder="D" required/></label><label><span>Name</span><input value={homeName} onChange={e=>setHomeName(e.target.value)} placeholder="Homeroom D" required/></label><label><span>School year</span><input value={schoolYear} onChange={e=>setSchoolYear(e.target.value)} required/></label><button disabled={saving}>Add homeroom</button></form><div className={styles.list}>{homerooms.map(home=><div className={styles.row} key={home.id}><strong>{home.code}</strong><div><b>{home.name}</b><small>{home.school_year}</small></div><small>{home.is_active?"Active":"Archived"}</small></div>)}</div></>}
 {tab==="periods"&&<><form className={styles.form} onSubmit={createPeriod}><label><span>Period number</span><input type="number" min="1" max="20" value={periodNumber} onChange={e=>setPeriodNumber(Number(e.target.value))}/></label><label><span>Label</span><input value={periodLabel} onChange={e=>setPeriodLabel(e.target.value)} required/></label><label><span>Starts</span><input type="time" value={periodStart} onChange={e=>setPeriodStart(e.target.value)}/></label><label><span>Ends</span><input type="time" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)}/></label><label><span>Type</span><select value={instructional?"class":"activity"} onChange={e=>setInstructional(e.target.value==="class")}><option value="class">Instructional</option><option value="activity">Break / activity</option></select></label><button disabled={saving}>Add period</button></form><div className={styles.list}>{periods.map(period=><div className={styles.row} key={period.id}><strong>{period.period_number}</strong><div><b>{period.label}</b><small>{clock(period.starts_at)} – {clock(period.ends_at)}</small></div><small>{period.is_instructional?"Instructional":"Activity"}</small></div>)}</div></>}
 {tab==="schedule"&&<><div className={styles.weekControls}><label><span>View homeroom</span><select value={scheduleHomeroom} onChange={e=>setScheduleHomeroom(e.target.value)}>{activeHomes.map(home=><option key={home.id} value={home.id}>{home.name}</option>)}</select></label></div><form className={styles.form} onSubmit={saveSchedule}><label><span>Day</span><select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.slice(1,6).map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label><label><span>Period</span><select value={schedulePeriod} onChange={e=>setSchedulePeriod(e.target.value)}>{activePeriods.map(period=><option key={period.id} value={period.id}>{period.label} • {clock(period.starts_at)}</option>)}</select></label><label><span>Course section</span><select value={scheduleSection} onChange={e=>setScheduleSection(e.target.value)}><option value="">Non-course activity</option>{sections.map(section=><option key={section.id} value={section.id}>{sectionName(section.id)}</option>)}</select></label>{!scheduleSection&&<label><span>Activity</span><input value={activityTitle} onChange={e=>setActivityTitle(e.target.value)} placeholder="Study Period" required/></label>}<label><span>Faculty</span><select value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Faculty TBA</option>{faculty.map(person=><option key={person.character_id} value={person.character_id}>{person.display_name} (@{person.handle})</option>)}</select></label><label><span>Room</span><input value={scheduleRoom} onChange={e=>setScheduleRoom(e.target.value)} placeholder="201"/></label><label><span>Notes</span><input value={scheduleNotes} onChange={e=>setScheduleNotes(e.target.value)} placeholder="Optional"/></label><button disabled={saving||!activeHomes.length||!activePeriods.length}>Assign period</button></form><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Period</th>{DAYS.slice(1,6).map(day=><th key={day}>{day}</th>)}</tr></thead><tbody>{activePeriods.map(period=><tr key={period.id}><th className={styles.periodCell}>{period.label}<small>{clock(period.starts_at)}</small></th>{[1,2,3,4,5].map(day=>{const item=selectedAssignments.find(a=>a.weekday===day&&a.period_id===period.id);return <td key={day}><div className={styles.cell}>{item?<><strong>{item.section_id?sectionName(item.section_id):item.activity_title}</strong><span>{teacherName(item.instructor_character_id)}</span><small>{item.room?`Room ${item.room}`:"Room TBA"}</small><div className={styles.actions}><button type="button" className={`${styles.secondary} ${styles.danger}`} disabled={saving} onClick={()=>void removeSchedule(item.id)}>Remove</button></div></>:<span className={styles.empty}>Open</span>}</div></td>;})}</tr>)}</tbody></table></div></>}
 {(tab==="rosters"||tab==="faculty")&&<><form className={styles.form} onSubmit={event=>assignCharacter(event,tab==="rosters"?"student":"instructor")}><label><span>Section</span><select value={rosterSection} onChange={e=>setRosterSection(e.target.value)}>{sections.map(section=><option key={section.id} value={section.id}>{sectionName(section.id)}</option>)}</select></label><label><span>Exact Hanami handle</span><input value={rosterHandle} onChange={e=>setRosterHandle(e.target.value)} placeholder={tab==="rosters"?"@student_handle":"@faculty_handle"} required/></label><button disabled={saving||!sections.length}>{tab==="rosters"?"Enroll student":"Assign faculty"}</button></form><div className={styles.list}>{sections.map(section=><div className={styles.row} key={section.id}><strong>{section.section_code}</strong><div><b>{courseName(section.course_id)}</b><small>{section.term}</small></div><small>{memberships.filter(row=>row.section_id===section.id&&row.relationship===(tab==="rosters"?"student":"instructor")).length} {tab==="rosters"?"students":"faculty"}</small></div>)}</div></>}
 </section>;
}
