"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./AdminOfficeRequestManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Status="submitted"|"in_review"|"waiting_on_member"|"resolved"|"closed";
type Row={request_id:string;request_type:string;status:Status;subject:string;body:string;staff_note:string;created_at:string;updated_at:string;character_id:string;display_name:string;handle:string;role:"student"|"faculty"};
type Props={accessToken:string;userId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function timeLabel(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}

export default function AdminOfficeRequestManager({accessToken,userId}:Props){
 const [rows,setRows]=useState<Row[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [message,setMessage]=useState("Loading School Office queue…");const [saving,setSaving]=useState("");
 const activeRows=useMemo(()=>rows.filter(row=>row.status==="submitted"||row.status==="in_review"),[rows]);
 const waitingRows=useMemo(()=>rows.filter(row=>row.status==="waiting_on_member"),[rows]);
 const archiveRows=useMemo(()=>rows.filter(row=>row.status==="resolved"||row.status==="closed"),[rows]);
 const load=useCallback(async()=>{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/office_request_queue`,{method:"POST",cache:"no-store",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok)throw new Error("School Office queue could not be loaded.");const data=await response.json() as Row[];setRows(data);setNotes(current=>{const next={...current};for(const row of data)if(next[row.request_id]===undefined)next[row.request_id]=row.staff_note;return next;});const actionCount=data.filter(row=>row.status==="submitted"||row.status==="in_review").length;setMessage(actionCount?`${actionCount} request${actionCount===1?"":"s"} need staff action.`:"No School Office requests need staff action.");},[accessToken]);
 useEffect(()=>{load().catch(error=>setMessage(error instanceof Error?error.message:"School Office queue could not be loaded."));},[load]);
 async function update(row:Row,status:Status){setSaving(row.request_id);try{const note=(notes[row.request_id]??"").trim();const response=await fetch(`${SUPABASE_URL}/rest/v1/school_office_requests?id=eq.${encodeURIComponent(row.request_id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,staff_note:note,assigned_to:status==="closed"||status==="waiting_on_member"?null:userId,closed_at:status==="closed"?new Date().toISOString():null,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("The School Office request could not be updated.");await load();setMessage(status==="waiting_on_member"?"Request sent back to the member and removed from the active staff queue.":`Request moved to ${status.replaceAll("_"," ")}.`);}catch(error){setMessage(error instanceof Error?error.message:"The School Office request could not be updated.");}finally{setSaving("");}}
 function renderRows(items:Row[],mode:"active"|"waiting"|"archive"){return <div className={styles.list}>{items.length?items.map(row=><article key={row.request_id}><div className={styles.top}><div><strong>{row.subject}</strong><span>@{row.handle} • {row.display_name} • {row.role.toUpperCase()} • {row.request_type.replaceAll("_"," ").toUpperCase()}</span></div><b data-status={row.status}>{row.status.replaceAll("_"," ").toUpperCase()}</b></div><p>{row.body}</p><small>Opened {timeLabel(row.created_at)} • Updated {timeLabel(row.updated_at)}</small>{mode!=="archive"&&<label><span>Staff response shown to member</span><textarea value={notes[row.request_id]??""} onChange={event=>setNotes(current=>({...current,[row.request_id]:event.target.value}))} maxLength={5000} placeholder="Type the School Office response here…"/></label>}{mode==="active"&&<div className={styles.actions}><button type="button" onClick={()=>update(row,"in_review")} disabled={Boolean(saving)}>In review</button><button type="button" onClick={()=>update(row,"waiting_on_member")} disabled={Boolean(saving)}>Send to member</button><button type="button" onClick={()=>update(row,"resolved")} disabled={Boolean(saving)}>Resolve</button><button type="button" onClick={()=>update(row,"closed")} disabled={Boolean(saving)}>Close</button></div>}{mode==="waiting"&&<div className={styles.actions}><span>Waiting for the member to send a follow-up. This item is not in the active staff queue.</span><button type="button" onClick={()=>update(row,"in_review")} disabled={Boolean(saving)}>Return to staff review</button></div>}</article>):<p className={styles.empty}>No requests in this section.</p>}</div>;}
 return <section className={styles.panel} aria-labelledby="admin-office-title"><div className={styles.heading}><div><p className="eyebrow">SCHOOL OFFICE QUEUE</p><h3 id="admin-office-title">Member requests</h3></div><span>{activeRows.length} NEED ACTION</span></div><div className={styles.status} aria-live="polite">{message}</div><div className={styles.sectionHead}><strong>NEEDS STAFF ACTION</strong><span>{activeRows.length}</span></div>{renderRows(activeRows,"active")}<div className={styles.sectionHead}><strong>AWAITING MEMBER RESPONSE</strong><span>{waitingRows.length}</span></div>{renderRows(waitingRows,"waiting")}<details className={styles.archive}><summary>Completed / archive ({archiveRows.length})</summary>{renderRows(archiveRows,"archive")}</details></section>;
}
