"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function tokyo(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}

type Account={user_id:string;display_name:string;discord_username:string;discord_user_id:string;account_status:string;suspension_reason:string|null;created_at:string;character_count:number};
type Audit={id:number;actor_user_id:string|null;actor_name:string|null;action:string;target_type:string;target_id:string|null;details:Record<string,unknown>;created_at:string};
type Props={accessToken:string;ownerMode?:boolean};

export default function AdminGovernancePanel({accessToken,ownerMode=false}:Props){
 const [accounts,setAccounts]=useState<Account[]>([]);const [audit,setAudit]=useState<Audit[]>([]);const [search,setSearch]=useState("");const [message,setMessage]=useState("Loading account governance…");const [busy,setBusy]=useState(false);
 const load=useCallback(async(term="")=>{try{const [accountsResponse,auditResponse]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/rpc/account_governance_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({search_text:term})}),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/system_audit_log_feed`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({limit_rows:100})})
 ]);if(!accountsResponse.ok||!auditResponse.ok)throw new Error("Governance data could not be loaded.");const accountRows=await accountsResponse.json() as Account[];const auditRows=await auditResponse.json() as Audit[];setAccounts(accountRows);setAudit(auditRows);setMessage(`${accountRows.length} account${accountRows.length===1?"":"s"} shown • ${auditRows.length} recent audit event${auditRows.length===1?"":"s"}.`);}catch(error){setMessage(error instanceof Error?error.message:"Governance data could not be loaded.");}},[accessToken]);
 useEffect(()=>{const task=setTimeout(()=>{void load();},0);return()=>clearTimeout(task);},[load]);
 async function submitSearch(event:FormEvent){event.preventDefault();await load(search.trim());}
 async function setStatus(account:Account,status:"active"|"suspended"){
  if(busy)return;let reason:string|null=null;if(status==="suspended"){reason=window.prompt(`Reason for suspending ${account.display_name||account.discord_username||account.discord_user_id}:`,account.suspension_reason??"");if(reason===null)return;if(reason.trim().length<3){setMessage("Suspension reason must be at least 3 characters.");return;}}
  if(!window.confirm(status==="suspended"?"Suspend this Hanami account? Their portal access will be blocked until reactivated.":"Reactivate this Hanami account?"))return;
  setBusy(true);setMessage(status==="suspended"?"Suspending account…":"Reactivating account…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/set_account_status`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_user:account.user_id,new_status:status,reason:reason?.trim()||null})});if(!response.ok||!Boolean(await response.json()))throw new Error("Account status could not be changed.");await load(search.trim());setMessage(status==="suspended"?"Account suspended and recorded in the audit log.":"Account reactivated and recorded in the audit log.");}catch(error){setMessage(error instanceof Error?error.message:"Account status could not be changed.");}finally{setBusy(false);}
 }
 return <section style={{marginTop:16,border:"1px solid #aab7c6",background:"#fffdf9"}} aria-labelledby="governance-title">
  <div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"14px 16px",background:ownerMode?"#fff4d7":"#eaf0f7",borderBottom:"1px solid #b7c4d2",flexWrap:"wrap"}}><div><p className="eyebrow">{ownerMode?"OWNER GOVERNANCE":"SITE ADMIN • GOVERNANCE"}</p><h4 id="governance-title" style={{margin:"3px 0 0",font:"400 22px Georgia,serif"}}>Accounts & audit log</h4></div><span style={{alignSelf:"flex-start",padding:"6px 8px",background:"#17375f",color:"#fff",fontSize:8,fontWeight:700}}>NETWORK CONTROL</span></div>
  <div style={{padding:"8px 14px",background:"#fff8dc",borderBottom:"1px solid #dbc981",fontSize:9,color:"#675a2c"}} aria-live="polite">{message}</div>
  <form onSubmit={submitSearch} style={{display:"flex",gap:8,padding:12,borderBottom:"1px solid #d6dee7",flexWrap:"wrap"}}><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search display name, Discord username or ID" style={{flex:"1 1 260px",minHeight:34,padding:"7px 9px",border:"1px solid #a8b4c1"}}/><button type="submit" style={{minHeight:34,padding:"7px 12px",border:"1px solid #17375f",background:"#17375f",color:"white",fontWeight:700}}>Search accounts</button><button type="button" onClick={()=>{setSearch("");void load("");}} style={{minHeight:34,padding:"7px 12px",border:"1px solid #17375f",background:"white",color:"#17375f"}}>Clear</button></form>
  <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.15fr) minmax(0,.85fr)"}} className="governance-grid">
   <div style={{padding:12,borderRight:"1px solid #d6dee7",overflowX:"auto"}}><strong style={{display:"block",marginBottom:8,fontSize:9,letterSpacing:'.06em'}}>ACCOUNT DIRECTORY</strong>{accounts.length===0?<p style={{fontSize:9,color:"#6d7987"}}>No matching accounts.</p>:accounts.map(account=><article key={account.user_id} style={{padding:"10px 0",borderBottom:"1px dotted #c6ced7"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start",flexWrap:"wrap"}}><div><strong style={{font:"400 15px Georgia,serif",color:"#17375f"}}>{account.display_name||account.discord_username||"Hanami member"}</strong><div style={{fontSize:8,color:"#6b7786"}}>@{account.discord_username||"discord"} • Discord {account.discord_user_id||"unknown"}</div><div style={{fontSize:8,color:"#6b7786"}}>{account.character_count} character{Number(account.character_count)===1?"":"s"} • joined {tokyo(account.created_at)}</div>{account.suspension_reason&&<div style={{marginTop:5,padding:6,background:"#fff1f3",fontSize:8,color:"#8b2632"}}>Reason: {account.suspension_reason}</div>}</div><div style={{display:"grid",gap:6,justifyItems:"end"}}><span style={{padding:"4px 6px",background:account.account_status==="suspended"?"#8b2632":"#eaf5e7",color:account.account_status==="suspended"?"#fff":"#3f6a3e",fontSize:7,fontWeight:700}}>{account.account_status.toUpperCase()}</span>{account.account_status==="suspended"?<button type="button" disabled={busy} onClick={()=>setStatus(account,"active")}>Reactivate</button>:<button type="button" disabled={busy} onClick={()=>setStatus(account,"suspended")}>Suspend</button>}</div></div></article>)}</div>
   <div style={{padding:12,maxHeight:620,overflow:"auto"}}><strong style={{display:"block",marginBottom:8,fontSize:9,letterSpacing:'.06em'}}>RECENT AUDIT LOG</strong>{audit.length===0?<p style={{fontSize:9,color:"#6d7987"}}>No audit events yet.</p>:audit.map(item=><article key={item.id} style={{padding:"9px 0",borderBottom:"1px dotted #c6ced7"}}><strong style={{display:"block",fontSize:9,color:"#17375f"}}>{item.action}</strong><span style={{display:"block",marginTop:2,fontSize:7,color:"#7a8693"}}>{item.actor_name||"System"} • {tokyo(item.created_at)}</span><span style={{display:"block",marginTop:4,fontSize:8,color:"#536174"}}>{item.target_type}{item.target_id?` • ${item.target_id}`:""}</span></article>)}</div>
  </div>
  <style jsx>{`@media(max-width:860px){.governance-grid{grid-template-columns:1fr!important}.governance-grid>div:first-child{border-right:0!important;border-bottom:1px solid #d6dee7}}`}</style>
 </section>;
}
