"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function rpc<T>(token:string,name:string,body:Record<string,unknown>={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}

type Student={character_id:string;display_name:string;handle:string;grade_level:number|null;homeroom_code:string|null};
type Line={id:string;code:string;name:string};
type Stop={id:string;line_id:string;stop_name:string;neighborhood:string;stop_order:number;notes:string};
type Shift={id:string;character_id:string;workplace_name:string;shift_date:string;starts_at:string;ends_at:string;status:string;notes:string};
type Volunteer={id:string;character_id:string;activity_name:string;hours:number;service_date:string;note:string;verified_by:string|null};
type MentorReq={id:string;mentee_character_id:string;mentor_character_id:string|null;topic:string;note:string;status:string;created_at:string};
type RsvpSummary={event_id:string;title:string;attending:number;maybe:number;not_attending:number};
const panel:React.CSSProperties={margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14};
const box:React.CSSProperties={border:"1px solid #c6d0da",background:"#fff",padding:10};

export default function AdminRoadmapOperationsPanel({accessToken,userId,canModerate}:{accessToken:string;userId:string;canModerate:boolean}){
 const [students,setStudents]=useState<Student[]>([]);const [lines,setLines]=useState<Line[]>([]);const [stops,setStops]=useState<Stop[]>([]);const [shifts,setShifts]=useState<Shift[]>([]);const [hours,setHours]=useState<Volunteer[]>([]);const [mentorRequests,setMentorRequests]=useState<MentorReq[]>([]);const [rsvpSummary,setRsvpSummary]=useState<RsvpSummary[]>([]);const [notice,setNotice]=useState("Loading roadmap operations…");const [busy,setBusy]=useState(false);
 const [lineId,setLineId]=useState("");const [stopName,setStopName]=useState("");const [neighborhood,setNeighborhood]=useState("");const [stopOrder,setStopOrder]=useState("1");const [stopNotes,setStopNotes]=useState("");
 const [shiftStudent,setShiftStudent]=useState("");const [workplace,setWorkplace]=useState("");const [shiftDate,setShiftDate]=useState("");const [shiftStart,setShiftStart]=useState("16:00");const [shiftEnd,setShiftEnd]=useState("20:00");const [shiftNotes,setShiftNotes]=useState("");
 const [volunteerStudent,setVolunteerStudent]=useState("");const [activity,setActivity]=useState("");const [volunteerDate,setVolunteerDate]=useState("");const [volunteerHours,setVolunteerHours]=useState("1");const [volunteerNote,setVolunteerNote]=useState("");
 const [mentorChoice,setMentorChoice]=useState<Record<string,string>>({});
 const studentMap=useMemo(()=>new Map(students.map(s=>[s.character_id,s])),[students]);
 const load=useCallback(async()=>{try{const [studentRows,lineResponse,stopResponse,shiftResponse,hourResponse,rsvps]=await Promise.all([
  rpc<Student[]>(accessToken,"roadmap_student_directory"),
  fetch(`${SUPABASE_URL}/rest/v1/city_transit_lines?select=id,code,name&order=display_order`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/city_transit_stops?select=id,line_id,stop_name,neighborhood,stop_order,notes&order=line_id,stop_order`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/student_work_shifts?select=id,character_id,workplace_name,shift_date,starts_at,ends_at,status,notes&order=shift_date.desc&limit=80`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/volunteer_hours?select=id,character_id,activity_name,hours,service_date,note,verified_by&order=service_date.desc&limit=80`,{headers:headers(accessToken)}),
  rpc<RsvpSummary[]>(accessToken,"roadmap_event_rsvp_summary").catch(()=>[])
 ]);setStudents(studentRows);if(lineResponse.ok)setLines(await lineResponse.json() as Line[]);if(stopResponse.ok)setStops(await stopResponse.json() as Stop[]);if(shiftResponse.ok)setShifts(await shiftResponse.json() as Shift[]);if(hourResponse.ok)setHours(await hourResponse.json() as Volunteer[]);setRsvpSummary(rsvps);if(!lineId&&lineResponse.ok){const rows=await fetch(`${SUPABASE_URL}/rest/v1/city_transit_lines?select=id&order=display_order&limit=1`,{headers:headers(accessToken)}).then(r=>r.ok?r.json():[] as unknown);const first=(rows as Array<{id:string}>)[0];if(first)setLineId(first.id);}if(!shiftStudent&&studentRows[0])setShiftStudent(studentRows[0].character_id);if(!volunteerStudent&&studentRows[0])setVolunteerStudent(studentRows[0].character_id);
 if(canModerate){const response=await fetch(`${SUPABASE_URL}/rest/v1/mentorship_requests?select=id,mentee_character_id,mentor_character_id,topic,note,status,created_at&order=created_at.desc&limit=80`,{headers:headers(accessToken)});if(response.ok)setMentorRequests(await response.json() as MentorReq[]);}setNotice("Roadmap operations ready.");}catch(error){setNotice(error instanceof Error?error.message:"Roadmap operations could not be loaded.");}},[accessToken,canModerate,lineId,shiftStudent,volunteerStudent]);
 useEffect(()=>{void load();},[load]);
 async function post(table:string,body:Record<string,unknown>,success:string){setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(`${success.replace(/\.$/,"")} failed.`);setNotice(success);await load();}catch(error){setNotice(error instanceof Error?error.message:"Roadmap operation failed.");}finally{setBusy(false);}}
 async function patch(table:string,id:string,body:Record<string,unknown>,success:string){setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error("Update failed.");setNotice(success);await load();}catch(error){setNotice(error instanceof Error?error.message:"Update failed.");}finally{setBusy(false);}}
 async function addStop(e:FormEvent){e.preventDefault();if(!lineId||!stopName.trim())return;await post("city_transit_stops",{line_id:lineId,stop_name:stopName.trim(),neighborhood:neighborhood.trim(),stop_order:Number(stopOrder)||1,notes:stopNotes.trim()},"Transit stop added.");setStopName("");setNeighborhood("");setStopNotes("");}
 async function addShift(e:FormEvent){e.preventDefault();if(!shiftStudent||!workplace.trim()||!shiftDate)return;await post("student_work_shifts",{character_id:shiftStudent,workplace_name:workplace.trim(),shift_date:shiftDate,starts_at:shiftStart,ends_at:shiftEnd,notes:shiftNotes.trim(),status:"scheduled"},"Work shift scheduled.");setWorkplace("");setShiftNotes("");}
 async function addVolunteer(e:FormEvent){e.preventDefault();if(!volunteerStudent||!activity.trim()||!volunteerDate)return;await post("volunteer_hours",{character_id:volunteerStudent,activity_name:activity.trim(),hours:Number(volunteerHours),service_date:volunteerDate,note:volunteerNote.trim(),verified_by:userId},"Volunteer hours verified and recorded.");setActivity("");setVolunteerNote("");}
 async function decideMentor(row:MentorReq,decision:"matched"|"declined"){if(!canModerate)return;const mentor=mentorChoice[row.id]||row.mentor_character_id||"";if(decision==="matched"&&!mentor){setNotice("Choose an upper-year Student mentor first.");return;}await patch("mentorship_requests",row.id,{status:decision,mentor_character_id:decision==="matched"?mentor:null,reviewed_by:userId},decision==="matched"?"Mentorship match approved.":"Mentorship request declined.");}
 function mentorOptions(row:MentorReq){const mentee=studentMap.get(row.mentee_character_id);return students.filter(s=>s.character_id!==row.mentee_character_id&&(!mentee?.grade_level||!s.grade_level||s.grade_level>mentee.grade_level));}
 return <section style={panel} aria-label="Roadmap operations"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><p className="eyebrow">ROADMAP OPERATIONS</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Roadmap Completion Desk</h3></div><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:12,marginTop:12}}>
 <article style={box}><h4>Transit Stops</h4><form onSubmit={addStop} style={{display:"grid",gap:6}}><select value={lineId} onChange={e=>setLineId(e.target.value)}>{lines.map(l=><option key={l.id} value={l.id}>{l.code} · {l.name}</option>)}</select><input value={stopName} onChange={e=>setStopName(e.target.value)} placeholder="Stop name" required/><input value={neighborhood} onChange={e=>setNeighborhood(e.target.value)} placeholder="Neighborhood"/><input type="number" min="1" value={stopOrder} onChange={e=>setStopOrder(e.target.value)}/><input value={stopNotes} onChange={e=>setStopNotes(e.target.value)} placeholder="Stop notes / commute info"/><button disabled={busy}>Add stop</button></form>{stops.slice(0,12).map(s=><small key={s.id} style={{display:"block",marginTop:4}}>{s.stop_order}. {s.stop_name}{s.neighborhood?` • ${s.neighborhood}`:""}</small>)}</article>
 <article style={box}><h4>Part-time Work Shifts</h4><form onSubmit={addShift} style={{display:"grid",gap:6}}><select value={shiftStudent} onChange={e=>setShiftStudent(e.target.value)}>{students.map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle})</option>)}</select><input value={workplace} onChange={e=>setWorkplace(e.target.value)} placeholder="Approved workplace" required/><input type="date" value={shiftDate} onChange={e=>setShiftDate(e.target.value)} required/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}><input type="time" value={shiftStart} onChange={e=>setShiftStart(e.target.value)}/><input type="time" value={shiftEnd} onChange={e=>setShiftEnd(e.target.value)}/></div><input value={shiftNotes} onChange={e=>setShiftNotes(e.target.value)} placeholder="Shift notes"/><button disabled={busy}>Schedule shift</button></form>{shifts.slice(0,10).map(s=><p key={s.id} style={{fontSize:9}}><strong>{studentMap.get(s.character_id)?.display_name??"Student"} • {s.workplace_name}</strong><small style={{display:"block"}}>{s.shift_date} • {s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)} • {s.status}</small>{s.status!=="cancelled"&&<button type="button" disabled={busy} onClick={()=>void patch("student_work_shifts",s.id,{status:"cancelled"},"Work shift cancelled.")}>Cancel</button>}</p>)}</article>
 <article style={box}><h4>Volunteer Hours</h4><form onSubmit={addVolunteer} style={{display:"grid",gap:6}}><select value={volunteerStudent} onChange={e=>setVolunteerStudent(e.target.value)}>{students.map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle})</option>)}</select><input value={activity} onChange={e=>setActivity(e.target.value)} placeholder="Activity / event work" required/><input type="date" value={volunteerDate} onChange={e=>setVolunteerDate(e.target.value)} required/><input type="number" min="0.25" max="24" step="0.25" value={volunteerHours} onChange={e=>setVolunteerHours(e.target.value)}/><input value={volunteerNote} onChange={e=>setVolunteerNote(e.target.value)} placeholder="Verification note"/><button disabled={busy}>Verify hours</button></form>{hours.slice(0,10).map(h=><small key={h.id} style={{display:"block",marginTop:5}}>{studentMap.get(h.character_id)?.display_name??"Student"} • {h.activity_name} • {h.hours}h • {h.service_date}</small>)}</article>
 {canModerate&&<article style={box}><h4>Mentorship Oversight</h4>{mentorRequests.filter(r=>["pending","matched"].includes(r.status)).map(row=><div key={row.id} style={{borderTop:"1px solid #e2e7ec",padding:"7px 0"}}><strong>{studentMap.get(row.mentee_character_id)?.display_name??"Student"} • {row.topic}</strong><small style={{display:"block"}}>{row.note||"No note"} • {row.status}</small>{row.status==="pending"&&<><select value={mentorChoice[row.id]??""} onChange={e=>setMentorChoice(v=>({...v,[row.id]:e.target.value}))} style={{width:"100%",margin:"5px 0"}}><option value="">Choose upper-year mentor</option>{mentorOptions(row).map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle}){s.grade_level?` • Year ${s.grade_level}`:""}</option>)}</select><div style={{display:"flex",gap:5}}><button type="button" disabled={busy} onClick={()=>void decideMentor(row,"matched")}>Approve match</button><button type="button" disabled={busy} onClick={()=>void decideMentor(row,"declined")}>Decline</button></div></>}</div>)}{!mentorRequests.length&&<p>No mentorship requests.</p>}</article>}
 <article style={box}><h4>Event RSVP Summary</h4>{rsvpSummary.length?rsvpSummary.slice(0,12).map(r=><p key={r.event_id} style={{fontSize:9}}><strong>{r.title}</strong><small style={{display:"block"}}>Attending {r.attending} • Maybe {r.maybe} • Not attending {r.not_attending}</small></p>):<p>No RSVP responses yet.</p>}</article>
 </div></section>;
}
