"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./AdminCommandCenter.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type Character={id:string;role:"student"|"faculty";is_active:boolean};
type OfficeRow={status:string};
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
export default function AdminCommandCenter({accessToken}:Props){const [characters,setCharacters]=useState<Character[]>([]),[sections,setSections]=useState(0),[office,setOffice]=useState<OfficeRow[]>([]),[message,setMessage]=useState("Loading school operations…");useEffect(()=>{let dead=false;(async()=>{try{const [c,s,o]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,role,is_active`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/rpc/office_request_queue`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"})]);if(!c.ok||!s.ok)throw new Error("Administration overview could not be loaded.");const chars=await c.json() as Character[],sectionRows=await s.json() as {id:string}[],officeRows=o.ok?await o.json() as OfficeRow[]:[];if(!dead){setCharacters(chars);setSections(sectionRows.length);setOffice(officeRows);setMessage("School operations overview is current.");}}catch(error){if(!dead)setMessage(error instanceof Error?error.message:"Administration overview unavailable.");}})();return()=>{dead=true};},[accessToken]);const students=useMemo(()=>characters.filter(x=>x.role==="student").length,[characters]),faculty=useMemo(()=>characters.filter(x=>x.role==="faculty").length,[characters]),active=useMemo(()=>characters.filter(x=>x.is_active).length,[characters]),needsAction=useMemo(()=>office.filter(x=>x.status==="submitted"||x.status==="in_review").length,[office]);return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">SCHOOL OPERATIONS</p><h3>Administration command center</h3></div><span>LIVE OVERVIEW</span></div><div className={styles.stats}><article><span>STUDENTS</span><strong>{students}</strong></article><article><span>FACULTY</span><strong>{faculty}</strong></article><article><span>ACTIVE CHARACTERS</span><strong>{active}</strong></article><article><span>CLASS SECTIONS</span><strong>{sections}</strong></article><article><span>OFFICE ACTIONS</span><strong>{needsAction}</strong></article></div><div className={styles.workflow}><div><strong>People & enrollment</strong><span>Use People → Directory and School IDs for student/faculty records.</span></div><div><strong>Master academics</strong><span>Use Courses → Courses & Sections, Homerooms, and Schedule Blocks.</span></div><div><strong>Needs attention</strong><span>{needsAction?`${needsAction} School Office request${needsAction===1?"":"s"} currently need staff action.`:"No School Office requests currently need staff action."}</span></div></div><p className={styles.status}>{message}</p></section>}
