"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Session={id:string;code:string;title:string;status:string};
type Entry={id:string;session_id:string|null;entry_type:string;title:string;summary:string;sort_date:string|null;created_at:string};
export default function AdminContinuityArchiveManager({accessToken,userId}:{accessToken:string;userId:string}){
 const [sessions,setSessions]=useState<Session[]>([]);const [entries,setEntries]=useState<Entry[]>([]);const [sessionId,setSessionId]=useState("");const [type,setType]=useState("session_milestone");const [title,setTitle]=useState("");const [summary,setSummary]=useState("");const [sortDate,setSortDate]=useState("");const [notice,setNotice]=useState("Loading continuity archive…");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [s,e]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/roleplay_sessions?select=id,code,title,status&order=created_at.desc&limit=50`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/roleplay_continuity_archive?select=id,session_id,entry_type,title,summary,sort_date,created_at&order=sort_date.desc.nullslast,created_at.desc&limit=100`,{headers:headers(accessToken)})]);if(s.ok){const rows=await s.json() as Session[];setSessions(rows);setSessionId(v=>v||rows[0]?.id||"");}if(e.ok)setEntries(await e.json() as Entry[]);setNotice("Continuity archive ready.");},[accessToken]);useEffect(()=>{const task=setTimeout(()=>{void load();},0);return()=>clearTimeout(task);},[load]);
 async function create(e:FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/roleplay_continuity_archive`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({session_id:sessionId||null,entry_type:type,title:title.trim(),summary:summary.trim(),payload:{source:"admin_continuity_archive"},sort_date:sortDate||null,created_by:userId})});if(!r.ok)throw new Error("Continuity entry could not be archived.");setTitle("");setSummary("");setSortDate("");setNotice("Continuity entry archived and available to members.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Continuity entry could not be archived.");}finally{setBusy(false);}}
 async function remove(id:string){if(!confirm("Delete this continuity archive entry?"))return;const r=await fetch(`${SUPABASE_URL}/rest/v1/roleplay_continuity_archive?id=eq.${id}`,{method:"DELETE",headers:headers(accessToken)});setNotice(r.ok?"Continuity entry deleted.":"Continuity entry could not be deleted.");if(r.ok)await load();}
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14}} aria-label="Roleplay continuity archive manager"><div><p className="eyebrow">ROLEPLAY CONTINUITY</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Continuity Archive Manager</h3><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"minmax(280px,.8fr) minmax(320px,1.2fr)",gap:12,marginTop:12}}><form onSubmit={create} style={{display:"grid",gap:6,border:"1px solid #c7d0d9",background:"#fff",padding:10}}><select value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">General / no session</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.code} • {s.title} • {s.status}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{["session_milestone","event_outcome","character_milestone","school_history","city_history","graduation","canon_update","other"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Continuity title" required/><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Confirmed outcome / fact to preserve" rows={4}/><input type="date" value={sortDate} onChange={e=>setSortDate(e.target.value)}/><button disabled={busy}>{busy?"Archiving…":"Archive continuity entry"}</button></form><div style={{border:"1px solid #c7d0d9",background:"#fff",padding:10,maxHeight:420,overflow:"auto"}}>{entries.map(row=><div key={row.id} style={{borderBottom:"1px solid #e2e7ec",padding:"7px 0"}}><strong>{row.title}</strong><small style={{display:"block"}}>{row.entry_type.replaceAll("_"," ")} • {row.sort_date??new Date(row.created_at).toLocaleDateString()}</small><p style={{fontSize:9}}>{row.summary}</p><button type="button" onClick={()=>void remove(row.id)}>Delete</button></div>)}{!entries.length&&<p>No continuity entries yet.</p>}</div></div></section>;
}
