"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
async function rpc<T>(token:string,name:string,body:Record<string,unknown>={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(token,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}
type Competition={id:string;title:string;competition_type:string;status:string;description:string;starts_at:string|null;ends_at:string|null};
type ExamMode={key:string;enabled:boolean;title:string;starts_on:string|null;ends_on:string|null;temporary_style:string;announcement:string};
type Student={character_id:string;display_name:string;handle:string;grade_level:number|null;homeroom_code:string|null};
type Honor={id:string;student_character_id:string;term:string;honor_title:string;description:string;class_rank:number|null;show_rank_publicly:boolean};
const box:React.CSSProperties={border:"1px solid #c4ced8",background:"#fff",padding:10};
export default function AdminCompetitionExamManager({accessToken,userId}:{accessToken:string;userId:string}){
 const [competitions,setCompetitions]=useState<Competition[]>([]);const [examMode,setExamMode]=useState<ExamMode|null>(null);const [students,setStudents]=useState<Student[]>([]);const [honors,setHonors]=useState<Honor[]>([]);const [notice,setNotice]=useState("Loading competition and Exams Week administration…");const [busy,setBusy]=useState(false);
 const [title,setTitle]=useState("");const [type,setType]=useState("sports_day");const [description,setDescription]=useState("");const [starts,setStarts]=useState("");const [ends,setEnds]=useState("");
 const [examEnabled,setExamEnabled]=useState(false);const [examTitle,setExamTitle]=useState("Exams Week");const [examStart,setExamStart]=useState("");const [examEnd,setExamEnd]=useState("");const [examAnnouncement,setExamAnnouncement]=useState("");
 const [honorStudent,setHonorStudent]=useState("");const [honorTerm,setHonorTerm]=useState("2006–07");const [honorTitle,setHonorTitle]=useState("");const [honorDescription,setHonorDescription]=useState("");const [classRank,setClassRank]=useState("");const [showRank,setShowRank]=useState(false);
 const load=useCallback(async()=>{try{const [c,m,s,h]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/class_competitions?select=id,title,competition_type,status,description,starts_at,ends_at&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/exam_week_config?select=key,enabled,title,starts_on,ends_on,temporary_style,announcement&key=eq.current&limit=1`,{headers:headers(accessToken)}),rpc<Student[]>(accessToken,"roadmap_student_directory"),fetch(`${SUPABASE_URL}/rest/v1/student_honors?select=id,student_character_id,term,honor_title,description,class_rank,show_rank_publicly&order=created_at.desc&limit=100`,{headers:headers(accessToken)})]);if(c.ok)setCompetitions(await c.json() as Competition[]);if(m.ok){const row=(await m.json() as ExamMode[])[0]??null;setExamMode(row);if(row){setExamEnabled(row.enabled);setExamTitle(row.title);setExamStart(row.starts_on??"");setExamEnd(row.ends_on??"");setExamAnnouncement(row.announcement);}}setStudents(s);if(!honorStudent&&s[0])setHonorStudent(s[0].character_id);if(h.ok)setHonors(await h.json() as Honor[]);setNotice("Competition and Exams Week administration ready.");}catch(error){setNotice(error instanceof Error?error.message:"Competition and Exams Week administration could not be loaded.");}},[accessToken,honorStudent]);
 useEffect(()=>{void load();},[load]);
 async function createCompetition(e:FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/class_competitions`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({title:title.trim(),competition_type:type,description:description.trim(),starts_at:starts?new Date(starts).toISOString():null,ends_at:ends?new Date(ends).toISOString():null,status:"active",created_by:userId})});if(!r.ok)throw new Error("Competition could not be created.");setTitle("");setDescription("");setStarts("");setEnds("");setNotice("Class competition published.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Competition could not be created.");}finally{setBusy(false);}}
 async function setCompetitionStatus(id:string,status:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/class_competitions?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status})});setNotice(r.ok?`Competition ${status}.`:"Competition status could not be changed.");if(r.ok)await load();}
 async function saveExamMode(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/exam_week_config?on_conflict=key`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates"}),body:JSON.stringify({key:"current",enabled:examEnabled,title:examTitle.trim()||"Exams Week",starts_on:examStart||null,ends_on:examEnd||null,temporary_style:"exam",announcement:examAnnouncement.trim(),updated_by:userId,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Exams Week mode could not be saved.");setNotice(examEnabled?"Exams Week mode activated.":"Exams Week mode disabled.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Exams Week mode could not be saved.");}finally{setBusy(false);}}
 async function awardHonor(e:FormEvent){e.preventDefault();if(!honorStudent||!honorTitle.trim())return;setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/student_honors`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({student_character_id:honorStudent,term:honorTerm.trim(),honor_title:honorTitle.trim(),description:honorDescription.trim(),class_rank:classRank?Number(classRank):null,show_rank_publicly:showRank,awarded_by:userId})});if(!r.ok)throw new Error("Honor could not be recorded.");setHonorTitle("");setHonorDescription("");setClassRank("");setShowRank(false);setNotice("Student honor recorded. Rank visibility follows the selected privacy setting.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Honor could not be recorded.");}finally{setBusy(false);}}
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14}} aria-label="Competition and Exams Week administration"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><p className="eyebrow">ACADEMIC EVENTS</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Competitions, Exams Week & Honors</h3></div><small>{notice}</small></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:12,marginTop:12}}>
 <article style={box}><h4>Class Competition</h4><form onSubmit={createCompetition} style={{display:"grid",gap:6}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Competition title" required/><select value={type} onChange={e=>setType(e.target.value)}>{["sports_day","culture_festival","academics","cleanup","attendance","spirit","other"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="How points are earned" rows={2}/><input type="datetime-local" value={starts} onChange={e=>setStarts(e.target.value)}/><input type="datetime-local" value={ends} onChange={e=>setEnds(e.target.value)}/><button disabled={busy}>Publish competition</button></form>{competitions.slice(0,8).map(c=><p key={c.id} style={{fontSize:9}}><strong>{c.title}</strong><small style={{display:"block"}}>{c.competition_type.replaceAll("_"," ")} • {c.status}</small>{c.status==="active"&&<button type="button" onClick={()=>void setCompetitionStatus(c.id,"completed")}>Complete</button>}</p>)}</article>
 <article style={box}><h4>Exams Week Mode</h4><form onSubmit={saveExamMode} style={{display:"grid",gap:6}}><label><input type="checkbox" checked={examEnabled} onChange={e=>setExamEnabled(e.target.checked)}/> Enable global Exams Week mode</label><input value={examTitle} onChange={e=>setExamTitle(e.target.value)} placeholder="Mode title"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:5}}><input type="date" value={examStart} onChange={e=>setExamStart(e.target.value)}/><input type="date" value={examEnd} onChange={e=>setExamEnd(e.target.value)}/></div><textarea value={examAnnouncement} onChange={e=>setExamAnnouncement(e.target.value)} placeholder="Schedule changes / exam-week notice" rows={3}/><button disabled={busy}>Save Exams Week mode</button></form>{examMode&&<small style={{display:"block",marginTop:7}}>Current: {examMode.enabled?"ACTIVE":"inactive"} • style {examMode.temporary_style}</small>}</article>
 <article style={box}><h4>Honors & Optional Class Rank</h4><p style={{fontSize:9}}>Honors do not require public ranking. Class rank stays private unless staff deliberately enables its display for that honor record.</p><form onSubmit={awardHonor} style={{display:"grid",gap:6}}><select value={honorStudent} onChange={e=>setHonorStudent(e.target.value)}>{students.map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle})</option>)}</select><input value={honorTerm} onChange={e=>setHonorTerm(e.target.value)} placeholder="Term"/><input value={honorTitle} onChange={e=>setHonorTitle(e.target.value)} placeholder="Honor title" required/><textarea value={honorDescription} onChange={e=>setHonorDescription(e.target.value)} placeholder="Honor description" rows={2}/><input type="number" min="1" value={classRank} onChange={e=>setClassRank(e.target.value)} placeholder="Optional class rank"/><label><input type="checkbox" checked={showRank} onChange={e=>setShowRank(e.target.checked)}/> Allow this rank to display to the Student</label><button disabled={busy}>Record honor</button></form>{honors.slice(0,8).map(h=><small key={h.id} style={{display:"block",marginTop:5}}>{students.find(s=>s.character_id===h.student_character_id)?.display_name??"Student"} • {h.honor_title}{h.class_rank?` • rank ${h.show_rank_publicly?h.class_rank:"private"}`:""}</small>)}</article>
 </div></section>;
}
