"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminScheduleBlockManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const DAYS=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const TYPES=[["homeroom","Homeroom"],["class_period","Class period"],["break","Break"],["lunch","Lunch"],["closing_advisory","Closing / Advisory"],["dismissal","Dismissal"],["club","Clubs"],["study","Study period"],["extracurricular","Extracurricular"],["assembly","Assembly"],["other","Other"]] as const;
type Block={id:string;block_type:string;title:string;weekday:number;starts_at:string;ends_at:string;homeroom_label:string|null;notes:string|null;sort_order:number};
type Props={accessToken:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function timeLabel(value:string){const [h,m]=value.split(":");const hour=Number(h);return `${hour%12||12}:${m} ${hour>=12?"PM":"AM"}`;}

export default function AdminScheduleBlockManager({accessToken}:Props){
 const [blocks,setBlocks]=useState<Block[]>([]),[notice,setNotice]=useState("Loading school schedule…"),[saving,setSaving]=useState(false);
 const [blockType,setBlockType]=useState("homeroom"),[title,setTitle]=useState("Homeroom"),[weekday,setWeekday]=useState(1),[startsAt,setStartsAt]=useState("08:00"),[endsAt,setEndsAt]=useState("08:30"),[homeroom,setHomeroom]=useState("All homerooms"),[notes,setNotes]=useState("");
 const load=useCallback(async()=>{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?select=id,block_type,title,weekday,starts_at,ends_at,homeroom_label,notes,sort_order&order=weekday.asc,starts_at.asc,sort_order.asc`,{headers:headers(accessToken)});if(!response.ok){setNotice("School schedule blocks could not be loaded.");return;}const rows=await response.json() as Block[];setBlocks(rows);setNotice(`${rows.length} schedule block${rows.length===1?"":"s"} configured.`);},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function addBlock(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;if(endsAt<=startsAt){setNotice("End time must be later than start time.");return;}setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({block_type:blockType,title:title.trim(),weekday,starts_at:startsAt,ends_at:endsAt,homeroom_label:homeroom.trim()||null,notes:notes.trim()||null})});if(!response.ok)throw new Error("The schedule block could not be added.");setNotes("");await load();setNotice(`${title.trim()} added to ${DAYS[weekday]}.`);}catch(error){setNotice(error instanceof Error?error.message:"The schedule block could not be added.");}finally{setSaving(false);}}
 async function removeBlock(id:string){if(saving||!window.confirm("Remove this schedule block?"))return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/school_schedule_blocks?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers(accessToken)});if(!response.ok)throw new Error("The schedule block could not be removed.");await load();setNotice("Schedule block removed.");}catch(error){setNotice(error instanceof Error?error.message:"The schedule block could not be removed.");}finally{setSaving(false);}}
 function chooseType(next:string){setBlockType(next);const label=TYPES.find(([value])=>value===next)?.[1]??"Schedule block";setTitle(label);if(next==="homeroom"){setStartsAt("08:00");setEndsAt("08:30");}else if(next==="lunch"){setStartsAt("11:50");setEndsAt("12:50");}else if(next==="closing_advisory"){setStartsAt("14:20");setEndsAt("15:00");}else if(next==="dismissal"){setStartsAt("15:00");setEndsAt("15:01");}else if(next==="club"){setStartsAt("15:30");setEndsAt("16:30");}}
 return <section className={styles.panel} aria-labelledby="schedule-block-manager-title"><div className={styles.intro}><div><p className="eyebrow">SCHOOL DAY BUILDER</p><h3 id="schedule-block-manager-title">Schedule Blocks</h3><p>Add non-class parts of the day such as homeroom, breaks, lunch, closing/advisory, dismissal, clubs, study periods, assemblies, and custom blocks.</p></div><span>{blocks.length} BLOCKS</span></div><div className={styles.notice} aria-live="polite">{notice}</div><form className={styles.form} onSubmit={addBlock}><h4>Add schedule block</h4><label>Type<select value={blockType} onChange={e=>chooseType(e.target.value)}>{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Day<select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.slice(1,6).map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label><label>Starts<input type="time" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></label><label>Ends<input type="time" value={endsAt} onChange={e=>setEndsAt(e.target.value)} required/></label><label className={styles.wide}>Title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} required/></label><label className={styles.wide}>Homeroom / audience<input value={homeroom} onChange={e=>setHomeroom(e.target.value)} placeholder="All homerooms, Homeroom A, Faculty…"/></label><label className={styles.full}>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={2} placeholder="Optional details"/></label><button type="submit" disabled={saving}>{saving?"Saving…":"Add to schedule"}</button></form><div className={styles.days}>{DAYS.slice(1,6).map((day,index)=>{const dayNumber=index+1;const rows=blocks.filter(block=>block.weekday===dayNumber);return <section className={styles.day} key={day}><h4>{day}</h4>{rows.length?rows.map(block=><article className={styles.block} key={block.id}><strong>{block.title}</strong><span>{timeLabel(block.starts_at)}–{timeLabel(block.ends_at)}</span><small>{block.homeroom_label??"All school"}{block.notes?` • ${block.notes}`:""}</small><button type="button" disabled={saving} onClick={()=>void removeBlock(block.id)}>Remove</button></article>):<div className={styles.block}><small>No blocks yet.</small></div>}</section>})}</div></section>;
}
