"use client";

import {useEffect,useState} from "react";
import AdminAnnouncementManager from "./AdminAnnouncementManager";
import AdminModerationManager from "./AdminModerationManager";
import AdminCharacterDirectory from "./AdminCharacterDirectory";
import styles from "../RolePortalClient.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
type Access={site_admin:boolean;content_editor:boolean;moderator:boolean};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
async function refreshSession(session:PortalSession):Promise<PortalSession|null>{const response=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:SUPABASE_PUBLISHABLE_KEY,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return null;const data=await response.json() as {access_token?:string;refresh_token?:string;expires_in?:number;token_type?:string};if(!data.access_token||!data.refresh_token)return null;const next={accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+(data.expires_in??3600)*1000,tokenType:data.token_type??"bearer"};localStorage.setItem(SESSION_KEY,JSON.stringify(next));return next;}

export default function AdminPortalClient(){
 const [session,setSession]=useState<PortalSession|null>(null);const [access,setAccess]=useState<Access|null>(null);const [userId,setUserId]=useState("");const [state,setState]=useState<"loading"|"ready"|"blocked">("loading");const [message,setMessage]=useState("Checking Hanami administration permissions…");
 useEffect(()=>{let cancelled=false;async function initialize(){try{let stored=readSession();if(!stored){if(!cancelled){setState("blocked");setMessage("You are signed out. Sign in through the portal gateway first.");}return;}if(stored.expiresAt-Date.now()<120000){stored=await refreshSession(stored);if(!stored){localStorage.removeItem(SESSION_KEY);if(!cancelled){setState("blocked");setMessage("Your Hanami session expired. Sign in again from the portal gateway.");}return;}}
  const [userResponse,permissionResponse]=await Promise.all([fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:headers(stored.accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/rpc/current_account_admin_access`,{method:"POST",headers:headers(stored.accessToken,{"Content-Type":"application/json"}),body:"{}"})]);if(!userResponse.ok||!permissionResponse.ok)throw new Error("Administration access could not be verified.");const user=await userResponse.json() as {id?:string};const rows=await permissionResponse.json() as Access[];const permissions=rows[0]??{site_admin:false,content_editor:false,moderator:false};if(!user.id)throw new Error("Your Hanami account ID is unavailable.");if(!permissions.site_admin&&!permissions.content_editor&&!permissions.moderator){if(!cancelled){setSession(stored);setState("blocked");setMessage("This Hanami account does not have Administration permissions. Faculty characters do not grant admin access.");}return;}if(!cancelled){setSession(stored);setAccess(permissions);setUserId(user.id);setState("ready");setMessage("Administration permissions verified.");}}
  catch(error){if(!cancelled){setState("blocked");setMessage(error instanceof Error?error.message:"Administration access could not be verified.");}}}initialize();return()=>{cancelled=true;};},[]);
 function logout(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem("hanami.portal.character.v1");window.location.assign("../");}
 if(state!=="ready"||!session||!access||!userId)return <section className={styles.gate}><p className="eyebrow">ADMINISTRATION</p><h2>{state==="loading"?"Verifying administration access…":"Administration access unavailable"}</h2><p>{message}</p><div className={styles.actions}><a href="../">Return to portal gateway</a>{session&&<button type="button" onClick={logout}>Logout</button>}</div></section>;
 const canModerate=access.site_admin||access.moderator;
 return <div className={styles.portal}><div className={styles.sessionBar}><div><strong>ADMINISTRATION PORTAL</strong><span>{message} {access.site_admin?"Site Admin":access.content_editor&&access.moderator?"Content Editor + Moderator":access.content_editor?"Content Editor":"Moderator"}</span></div><div className={styles.actions}><a href="../">Portal gateway</a><button type="button" onClick={logout}>Logout</button></div></div>{(access.site_admin||access.content_editor)&&<AdminAnnouncementManager accessToken={session.accessToken} userId={userId} access={access}/>} {canModerate&&<><AdminModerationManager accessToken={session.accessToken} userId={userId} access={access}/><AdminCharacterDirectory accessToken={session.accessToken}/></>}</div>;
}
