"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminAcademicManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Course={id:string;code:string;title:string;department:string;description:string;credits:number;is_test_data:boolean};
type Section={id:string;course_id:string;section_code:string;term:string;room:string|null;capacity:number;is_test_data:boolean};
type Props={accessToken:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
async function responseError(response:Response,fallback:string){try{const data=await response.json() as {message?:string;details?:string;hint?:string;code?:string};const detail=[data.message,data.details,data.hint].filter(Boolean).join(" ");if(data.code==="23505"||/duplicate key|already exists/i.test(detail))return "That course code already exists.";if(data.code==="23514"||/check constraint/i.test(detail))return "One or more course values are invalid. Course codes must look like ENG-101 and credits must be between 1 and 6.";if(/Site Admin access required|permission denied|not authorized/i.test(detail))return "Site Admin authorization could not be verified. Lock and reopen the Administration portal, then try again.";return detail||fallback;}catch{return fallback;}}

export default function AdminAcademicManager({accessToken}:Props){
 const [courses,setCourses]=useState<Course[]>([]);const [sections,setSections]=useState<Section[]>([]);const [notice,setNotice]=useState("Loading academic administration…");const [saving,setSaving]=useState(false);
 const [courseCode,setCourseCode]=useState("");const [courseTitle,setCourseTitle]=useState("");const [department,setDepartment]=useState("");const [description,setDescription]=useState("");const [credits,setCredits]=useState(1);const [courseTest,setCourseTest]=useState(false);
 const [sectionCourse,setSectionCourse]=useState("");const [sectionCode,setSectionCode]=useState("A");const [term,setTerm]=useState("2006-2007");const [room,setRoom]=useState("");const [capacity,setCapacity]=useState(24);const [sectionTest,setSectionTest]=useState(false);
 const [meetingSection,setMeetingSection]=useState("");const [weekday,setWeekday]=useState(1);const [startsAt,setStartsAt]=useState("09:00");const [endsAt,setEndsAt]=useState("09:50");const [meetingLabel,setMeetingLabel]=useState("");
 const [rosterSection,setRosterSection]=useState("");const [rosterHandle,setRosterHandle]=useState("");const [relationship,setRelationship]=useState<"student"|"instructor">("student");
 const load=useCallback(async()=>{const [courseResponse,sectionResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=id,code,title,department,description,credits,is_test_data&order=code.asc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,course_id,section_code,term,room,capacity,is_test_data&order=term.desc,section_code.asc`,{headers:headers(accessToken)})]);if(!courseResponse.ok||!sectionResponse.ok)throw new Error("Academic records could not be loaded.");const nextCourses=await courseResponse.json() as Course[];const nextSections=await sectionResponse.json() as Section[];setCourses(nextCourses);setSections(nextSections);if(!sectionCourse&&nextCourses[0])setSectionCourse(nextCourses[0].id);if(!meetingSection&&nextSections[0])setMeetingSection(nextSections[0].id);if(!rosterSection&&nextSections[0])setRosterSection(nextSections[0].id);setNotice(`${nextCourses.length} courses • ${nextSections.length} sections loaded.`);},[accessToken,sectionCourse,meetingSection,rosterSection]);
 useEffect(()=>{load().catch(error=>setNotice(error instanceof Error?error.message:"Academic administration could not be loaded."));},[load]);
 async function createCourse(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_create_academic_course`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({requested_code:courseCode.trim().toUpperCase(),requested_title:courseTitle.trim(),requested_department:department.trim(),requested_description:description.trim(),requested_credits:credits,requested_is_test_data:courseTest})});if(!response.ok)throw new Error(await responseError(response,"The course could not be created."));setCourseCode("");setCourseTitle("");setDepartment("");setDescription("");setCredits(1);setCourseTest(false);await load();setNotice("Course created.");}catch(error){setNotice(error instanceof Error?error.message:"The course could not be created.");}finally{setSaving(false);}}
 async function createSection(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!sectionCourse||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/class_sections`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({course_id:sectionCourse,section_code:sectionCode.trim(),term:term.trim(),room:room.trim()||null,capacity,is_test_data:sectionTest})});if(!response.ok)throw new Error("The class section could not be created.");setSectionCode("A");setRoom("");setCapacity(24);setSectionTest(false);await load();setNotice("Class section created.");}catch(error){setNotice(error instanceof Error?error.message:"The class section could not be created.");}finally{setSaving(false);}}
 async function createMeeting(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!meetingSection||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/section_meetings`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({section_id:meetingSection,weekday,starts_at:startsAt,ends_at:endsAt,label:meetingLabel.trim()||null})});if(!response.ok)throw new Error("The meeting time could not be created.");setMeetingLabel("");setNotice("Meeting time added to the section.");}catch(error){setNotice(error instanceof Error?error.message:"The meeting time could not be created.");}finally{setSaving(false);}}
 async function assignCharacter(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!rosterSection||saving)return;setSaving(true);try{const cleanHandle=rosterHandle.trim().replace(/^@/,"").toLowerCase();const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_assign_character_to_section`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_section_id:rosterSection,target_handle:cleanHandle,target_relationship:relationship})});if(!response.ok){const detail=await response.text();throw new Error(detail.includes("student membership")?"That character is not a Student.":detail.includes("instructor membership")?"That character is not Faculty.":detail.includes("character not found")?"No character uses that exact Hanami handle.":"The roster assignment could not be saved.");}setRosterHandle("");setNotice(`${relationship==="student"?"Student enrollment":"Faculty instructor assignment"} saved.`);}catch(error){setNotice(error instanceof Error?error.message:"The roster assignment could not be saved.");}finally{setSaving(false);}}
 const courseName=(id:string)=>{const course=courses.find(item=>item.id===id);return course?`${course.code} • ${course.title}`:"Unknown course";};
 return <section className={styles.panel} aria-labelledby="academic-admin-title"><div className={styles.heading}><div><p className="eyebrow">ACADEMIC ADMINISTRATION</p><h3 id="academic-admin-title">Courses, Sections & Rosters</h3></div><span>SITE ADMIN ONLY</span></div><div className={styles.notice} aria-live="polite">{notice}</div><div className={styles.forms}>
 <form onSubmit={createCourse}><h4>Create course</h4><label><span>Course code</span><input value={courseCode} onChange={e=>setCourseCode(e.target.value)} placeholder="ENG-101" pattern="[A-Za-z]{2,6}-[0-9]{3}" title="Use 2–6 letters, a hyphen, and three digits (for example ENG-101)." required/></label><label><span>Title</span><input value={courseTitle} onChange={e=>setCourseTitle(e.target.value)} required/></label><label><span>Department</span><input value={department} onChange={e=>setDepartment(e.target.value)} required/></label><label><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><div className={styles.row}><label><span>Credits</span><input type="number" min="1" max="6" value={credits} onChange={e=>setCredits(Number(e.target.value))}/></label><label className={styles.check}><input type="checkbox" checked={courseTest} onChange={e=>setCourseTest(e.target.checked)}/> TEST data</label></div><button disabled={saving}>Create course</button></form>
 <form onSubmit={createSection}><h4>Create section</h4><label><span>Course</span><select value={sectionCourse} onChange={e=>setSectionCourse(e.target.value)}>{courses.map(course=><option key={course.id} value={course.id}>{course.code} • {course.title}</option>)}</select></label><label><span>Section code</span><input value={sectionCode} onChange={e=>setSectionCode(e.target.value)} required/></label><label><span>Term</span><input value={term} onChange={e=>setTerm(e.target.value)} required/></label><label><span>Room</span><input value={room} onChange={e=>setRoom(e.target.value)}/></label><div className={styles.row}><label><span>Capacity</span><input type="number" min="1" max="100" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label className={styles.check}><input type="checkbox" checked={sectionTest} onChange={e=>setSectionTest(e.target.checked)}/> TEST data</label></div><button disabled={saving||!courses.length}>Create section</button></form>
 <form onSubmit={createMeeting}><h4>Add meeting time</h4><label><span>Section</span><select value={meetingSection} onChange={e=>setMeetingSection(e.target.value)}>{sections.map(section=><option key={section.id} value={section.id}>{courseName(section.course_id)} • {section.section_code}</option>)}</select></label><label><span>Weekday</span><select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select></label><div className={styles.row}><label><span>Starts</span><input type="time" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label><span>Ends</span><input type="time" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label></div><label><span>Label</span><input value={meetingLabel} onChange={e=>setMeetingLabel(e.target.value)} placeholder="Optional"/></label><button disabled={saving||!sections.length}>Add meeting</button></form>
 <form onSubmit={assignCharacter}><h4>Assign character</h4><label><span>Section</span><select value={rosterSection} onChange={e=>setRosterSection(e.target.value)}>{sections.map(section=><option key={section.id} value={section.id}>{courseName(section.course_id)} • {section.section_code}</option>)}</select></label><label><span>Exact Hanami handle</span><input value={rosterHandle} onChange={e=>setRosterHandle(e.target.value)} placeholder="@character_handle" required/></label><label><span>Relationship</span><select value={relationship} onChange={e=>setRelationship(e.target.value as "student"|"instructor")}><option value="student">Student enrollment</option><option value="instructor">Faculty instructor</option></select></label><button disabled={saving||!sections.length}>Save assignment</button></form>
 </div><div className={styles.catalog}><h4>Current sections</h4>{sections.map(section=><article key={section.id}><div><strong>{courseName(section.course_id)}</strong><span>Section {section.section_code} • {section.term}{section.is_test_data?" • TEST":""}</span></div><small>{section.room||"Room TBD"} • Capacity {section.capacity}</small></article>)}</div></section>;
}
