"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./AdminDeletionManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Homeroom={id:string;code:string;grade_level:number;room_label:string|null};
type Section={id:string;section_code:string;term:string;room:string|null;course_id:string};
type Course={id:string;code:string;title:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}

export default function AdminDeletionManager({accessToken}:{accessToken:string}){
 const [homerooms,setHomerooms]=useState<Homeroom[]>([]);const [sections,setSections]=useState<Section[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [busy,setBusy]=useState("");const [notice,setNotice]=useState("Deletion is permanent and is restricted by Supabase permissions.");
 const load=useCallback(async()=>{const [h,s,c]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/homerooms?select=id,code,grade_level,room_label&order=code`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,section_code,term,room,course_id&order=term.desc,section_code.asc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=id,code,title&order=code`,{headers:headers(accessToken)})]);if(!h.ok||!s.ok||!c.ok)throw new Error("Deletion manager could not load school records.");setHomerooms(await h.json() as Homeroom[]);setSections(await s.json() as Section[]);setCourses(await c.json() as Course[]);},[accessToken]);
 useEffect(()=>{void load().catch(error=>setNotice(error instanceof Error?error.message:"Deletion manager could not load."));},[load]);
 const courseName=(id:string)=>{const c=courses.find(x=>x.id===id);return c?`${c.code} • ${c.title}`:"Unknown course";};
 async function remove(table:"homerooms"|"class_sections",id:string,label:string){const warning=table==="homerooms"?`Delete homeroom ${label}? This permanently removes the homeroom and its homeroom memberships, representatives, notices, and events. This cannot be undone.`:`Delete class ${label}? This permanently removes this scheduled class section and its linked roster, meeting times, assignments, submissions, and section records. The underlying course subject remains in the catalog. This cannot be undone.`;if(!window.confirm(warning))return;setBusy(id);setNotice(`Deleting ${label}…`);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`,{method:"DELETE",headers:headers(accessToken,{Prefer:"return=representation"})});if(!response.ok){const text=await response.text();throw new Error(text||`Could not delete ${label}.`);}const rows=await response.json() as unknown[];if(!rows.length)throw new Error("Nothing was deleted. Your account may not have permission for this action.");await load();setNotice(`${label} was permanently deleted.`);}catch(error){setNotice(error instanceof Error?error.message:`Could not delete ${label}.`);}finally{setBusy("");}}
 return <section className={styles.panel} aria-labelledby="danger-zone-title"><div className={styles.heading}><div><p className="eyebrow">ADMIN / OWNER ONLY</p><h4 id="danger-zone-title">Class & homeroom deletion</h4><p>Use this area only when a scheduled class or homeroom should be permanently removed from Hanami High.</p></div><span className={styles.badge}>DANGER ZONE</span></div><div className={styles.grid}><article className={styles.group}><h5>Homerooms</h5>{homerooms.length?homerooms.map(h=><div className={styles.row} key={h.id}><div><strong>{h.code}</strong><span>Grade {h.grade_level} • {h.room_label??"Room TBA"}</span></div><button type="button" disabled={busy===h.id} onClick={()=>remove("homerooms",h.id,h.code)}>Delete homeroom</button></div>):<p>No homerooms found.</p>}</article><article className={styles.group}><h5>Scheduled classes</h5>{sections.length?sections.map(s=>{const label=`${courseName(s.course_id)} • Section ${s.section_code}`;return <div className={styles.row} key={s.id}><div><strong>{courseName(s.course_id)}</strong><span>Section {s.section_code} • {s.term}{s.room?` • Room ${s.room}`:""}</span></div><button type="button" disabled={busy===s.id} onClick={()=>remove("class_sections",s.id,label)}>Delete class</button></div>}):<p>No class sections found.</p>}</article></div><div className={styles.notice} aria-live="polite">{notice}</div></section>;
}
