"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminOpportunityManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type OpportunityType="job"|"volunteer"|"internship"|"student_leadership";
type Opportunity={id:string;opportunity_type:OpportunityType;title:string;department:string;description:string;location:string|null;status:"draft"|"published"|"closed";opens_at:string|null;closes_at:string|null;is_test_data:boolean};
type QueueRow={application_id:string;opportunity_title:string;opportunity_type:OpportunityType;character_display_name:string;character_handle:string;statement:string;application_status:"submitted"|"under_review"|"accepted"|"declined"|"withdrawn";staff_response:string|null;submitted_at:string};
type Props={accessToken:string;userId:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
function tokyo(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));}

export default function AdminOpportunityManager({accessToken,userId}:Props){
 const [rows,setRows]=useState<Opportunity[]>([]);const [queue,setQueue]=useState<QueueRow[]>([]);const [type,setType]=useState<OpportunityType>("job");const [title,setTitle]=useState("");const [department,setDepartment]=useState("");const [description,setDescription]=useState("");const [location,setLocation]=useState("");const [responses,setResponses]=useState<Record<string,string>>({});const [status,setStatus]=useState("Loading Campus Opportunities…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const [oppResponse,queueResponse]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/campus_opportunities?select=id,opportunity_type,title,department,description,location,status,opens_at,closes_at,is_test_data&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/rpc/administration_campus_application_queue`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"})]);if(!oppResponse.ok||!queueResponse.ok)throw new Error("Campus Opportunities administration could not be loaded.");setRows(await oppResponse.json() as Opportunity[]);setQueue(await queueResponse.json() as QueueRow[]);setStatus("Campus Opportunities administration loaded.");},[accessToken]);
 useEffect(()=>{load().catch(error=>setStatus(error instanceof Error?error.message:"Campus Opportunities administration could not be loaded."));},[load]);
 async function createOpportunity(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!title.trim()||!department.trim()||!description.trim())return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/campus_opportunities`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({opportunity_type:type,title:title.trim(),department:department.trim(),description:description.trim(),location:location.trim()||null,status:"draft",created_by:userId})});if(!response.ok)throw new Error("Opportunity could not be created.");setTitle("");setDepartment("");setDescription("");setLocation("");await load();setStatus("Draft opportunity created.");}catch(error){setStatus(error instanceof Error?error.message:"Opportunity could not be created.");}finally{setSaving(false);}}
 async function changeOpportunity(row:Opportunity,next:"published"|"closed"){setSaving(true);try{const now=new Date().toISOString();const response=await fetch(`${SUPABASE_URL}/rest/v1/campus_opportunities?id=eq.${encodeURIComponent(row.id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,opens_at:next==="published"?(row.opens_at??now):row.opens_at,closes_at:next==="closed"?(row.closes_at??now):row.closes_at,updated_at:now})});if(!response.ok)throw new Error("Opportunity status could not be updated.");await load();}finally{setSaving(false);}}
 async function review(application:QueueRow,next:"under_review"|"accepted"|"declined"){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/campus_opportunity_applications?id=eq.${encodeURIComponent(application.application_id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,staff_response:(responses[application.application_id]??application.staff_response??"").trim()||null,reviewed_by:userId,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Application review could not be saved.");await load();setStatus(`Application marked ${next.replace("_"," ")}.`);}catch(error){setStatus(error instanceof Error?error.message:"Application review could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">CAMPUS OPPORTUNITIES</p><h4>Opportunity & application management</h4></div><span>CONTENT EDITOR</span></div><div className={styles.status}>{status}</div><form className={styles.form} onSubmit={createOpportunity}><select value={type} onChange={event=>setType(event.target.value as OpportunityType)}><option value="job">Job</option><option value="volunteer">Volunteer</option><option value="internship">Internship</option><option value="student_leadership">Student leadership</option></select><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Opportunity title" maxLength={120}/><input value={department} onChange={event=>setDepartment(event.target.value)} placeholder="Department / office" maxLength={120}/><input value={location} onChange={event=>setLocation(event.target.value)} placeholder="Location (optional)"/><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Description" maxLength={5000}/><button disabled={saving}>Create draft</button></form><div className={styles.columns}><div><h5>OPPORTUNITIES</h5>{rows.map(row=><article key={row.id} className={styles.card}><b>{row.title}</b><span>{row.opportunity_type.replace("_"," ")} • {row.status.toUpperCase()}</span><p>{row.description}</p>{row.status!=="published"&&<button onClick={()=>changeOpportunity(row,"published")} disabled={saving}>Publish</button>}{row.status!=="closed"&&<button onClick={()=>changeOpportunity(row,"closed")} disabled={saving}>Close</button>}</article>)}</div><div><h5>APPLICATION QUEUE</h5>{queue.map(app=><article key={app.application_id} className={styles.card}><b>{app.character_display_name} <small>@{app.character_handle}</small></b><span>{app.opportunity_title} • {app.application_status.replace("_"," ").toUpperCase()}</span><p>{app.statement}</p><small>Submitted {tokyo(app.submitted_at)}</small><textarea value={responses[app.application_id]??app.staff_response??""} onChange={event=>setResponses(current=>({...current,[app.application_id]:event.target.value}))} placeholder="Staff response"/><div className={styles.actions}><button onClick={()=>review(app,"under_review")} disabled={saving}>Under review</button><button onClick={()=>review(app,"accepted")} disabled={saving}>Accept</button><button onClick={()=>review(app,"declined")} disabled={saving}>Decline</button></div></article>)}</div></div></section>;
}
