"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminHomeroomManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type Homeroom={id:string;code:string;grade_level:number;school_year:string;room_label:string|null;description:string;is_active:boolean;student_count:number};
type Student={character_id:string;display_name:string;handle:string;homeroom_id:string|null;homeroom_code:string|null;grade_level:number|null;school_year:string|null};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}
async function rpc(accessToken:string,name:string,body:Record<string,unknown>={}){return fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});}

export default function AdminHomeroomManager({accessToken}:Props){
 const [homerooms,setHomerooms]=useState<Homeroom[]>([]);const [students,setStudents]=useState<Student[]>([]);const [status,setStatus]=useState("Loading homerooms…");const [saving,setSaving]=useState(false);
 const [code,setCode]=useState("A");const [grade,setGrade]=useState(1);const [schoolYear,setSchoolYear]=useState("2006-2007");const [room,setRoom]=useState("");const [description,setDescription]=useState("");
 const [studentId,setStudentId]=useState("");const [homeroomId,setHomeroomId]=useState("");
 const load=useCallback(async()=>{const [h,s]=await Promise.all([rpc(accessToken,"admin_list_homerooms"),rpc(accessToken,"admin_list_students_for_homerooms")]);if(!h.ok||!s.ok)throw new Error("Homeroom data could not be loaded.");const nextH=await h.json() as Homeroom[];const nextS=await s.json() as Student[];setHomerooms(nextH);setStudents(nextS);if(!homeroomId&&nextH[0])setHomeroomId(nextH[0].id);if(!studentId&&nextS[0])setStudentId(nextS[0].character_id);setStatus(`${nextH.length} homeroom${nextH.length===1?"":"s"} • ${nextS.length} student${nextS.length===1?"":"s"}.`);},[accessToken,homeroomId,studentId]);
 useEffect(()=>{void load().catch(error=>setStatus(error instanceof Error?error.message:"Homerooms unavailable."));},[load]);
 async function create(event:FormEvent){event.preventDefault();if(saving)return;setSaving(true);setStatus("Creating homeroom…");try{const response=await rpc(accessToken,"admin_create_homeroom",{requested_code:code.trim().toUpperCase(),requested_grade_level:grade,requested_school_year:schoolYear.trim()||"2006-2007",requested_room_label:room.trim()||null,requested_description:description.trim()});if(!response.ok){const text=await response.text();throw new Error(text.includes("one letter")?"Use one homeroom letter such as A, B, or C.":"Homeroom could not be created.");}setDescription("");setRoom("");await load();setStatus(`Homeroom ${code.trim().toUpperCase()} created for ${schoolYear}.`);}catch(error){setStatus(error instanceof Error?error.message:"Homeroom could not be created.");}finally{setSaving(false);}}
 async function assign(event:FormEvent){event.preventDefault();if(!studentId||!homeroomId||saving)return;setSaving(true);setStatus("Assigning homeroom and matching class sections…");try{const response=await rpc(accessToken,"admin_assign_student_homeroom",{target_character_id:studentId,target_homeroom_id:homeroomId});if(!response.ok){const text=await response.text();throw new Error(text.includes("Homeroom not found")?"That homeroom is unavailable.":"Homeroom assignment could not be saved.");}const enrolled=Number(await response.json());await load();setStatus(`Homeroom assigned. ${enrolled} matching ${enrolled===1?"class section":"class sections"} automatically enrolled.`);}catch(error){setStatus(error instanceof Error?error.message:"Homeroom assignment could not be saved.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="homeroom-manager-title"><div className={styles.heading}><div><p className="eyebrow">HOMEROOM CONTROL</p><h3 id="homeroom-manager-title">Homerooms & automatic class placement</h3><p>Create A/B/C homerooms, assign students, and automatically enroll them into class sections whose section letter matches their homeroom for the same school year.</p></div><span>2006–2007</span></div><div className={styles.status}>{status}</div>
 <div className={styles.summary}>{homerooms.map(item=><article key={item.id}><strong>Homeroom {item.code}</strong><span>Year {item.grade_level} • {item.school_year}</span><small>{item.student_count} student{Number(item.student_count)===1?"":"s"}{item.room_label?` • ${item.room_label}`:""}</small></article>)}</div>
 <div className={styles.forms}><form onSubmit={create}><h4>Create homeroom</h4><div className={styles.row}><label><span>Homeroom letter</span><input maxLength={1} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} required/></label><label><span>Student year</span><select value={grade} onChange={e=>setGrade(Number(e.target.value))}><option value={1}>1st Year</option><option value={2}>2nd Year</option><option value={3}>3rd Year</option></select></label></div><label><span>School year</span><input value={schoolYear} onChange={e=>setSchoolYear(e.target.value)} required/></label><label><span>Room</span><input value={room} onChange={e=>setRoom(e.target.value)} placeholder="Optional"/></label><label><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional homeroom notes"/></label><button disabled={saving}>Create homeroom</button></form>
 <form onSubmit={assign}><h4>Assign student to homeroom</h4><label><span>Student</span><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(student=><option key={student.character_id} value={student.character_id}>{student.display_name} (@{student.handle}){student.homeroom_code?` • Current ${student.homeroom_code}`:""}</option>)}</select></label><label><span>Homeroom</span><select value={homeroomId} onChange={e=>setHomeroomId(e.target.value)}>{homerooms.map(item=><option key={item.id} value={item.id}>Homeroom {item.code} • Year {item.grade_level} • {item.school_year}</option>)}</select></label><div className={styles.autoNote}><strong>Automatic placement</strong><span>Assigning Homeroom A enrolls the student into every active 2006-2007 class section labeled A. The same applies to B and C. Their school ID year is synchronized too.</span></div><button disabled={saving||!students.length||!homerooms.length}>Assign & sync classes</button></form></div>
 </section>;
}
