"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./AdminStudentIdManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type StudentRow={character_id:string;display_name:string;handle:string;id_number:string|null;id_status:string|null;issued_at:string|null;homeroom_code:string|null;grade_level:number|null;school_year:string|null};
type Draft={idNumber:string;schoolYear:string;status:string};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}

export default function AdminStudentIdManager({accessToken}:Props){
 const [students,setStudents]=useState<StudentRow[]>([]);const [status,setStatus]=useState("Loading student IDs…");const [busy,setBusy]=useState<string|null>(null);const [drafts,setDrafts]=useState<Record<string,Draft>>({});
 const load=useCallback(async()=>{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_list_student_ids`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(!response.ok){setStatus("Student IDs could not be loaded.");return;}const rows=await response.json() as StudentRow[];setStudents(rows);setDrafts(Object.fromEntries(rows.map(row=>[row.character_id,{idNumber:row.id_number??"",schoolYear:row.school_year??"2006-2007",status:row.id_status??"active"}])));setStatus(`${rows.length} student character${rows.length===1?"":"s"} found.`);},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function issue(characterId:string){setBusy(characterId);setStatus("Issuing school ID…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_issue_student_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:characterId})});if(!response.ok){const body=await response.json().catch(()=>({})) as {message?:string};throw new Error(body.message??"School ID could not be issued.");}const id=await response.json() as string;setStatus(`School ID ${id} is active.`);await load();}catch(error){setStatus(error instanceof Error?error.message:"School ID could not be issued.");}finally{setBusy(null);}}
 async function save(characterId:string){const draft=drafts[characterId];if(!draft)return;setBusy(characterId);setStatus("Saving school ID…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/admin_update_student_id`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_character_id:characterId,requested_id_number:draft.idNumber.trim()||null,requested_school_year:draft.schoolYear.trim()||"2006-2007",requested_status:draft.status})});if(!response.ok){const text=await response.text();throw new Error(text.includes("HHS-0000-0000")?"Use the ID format HHS-0000-0000.":text.includes("duplicate")?"That student ID number is already in use.":"School ID changes could not be saved.");}const id=await response.json() as string;setStatus(`School ID ${id} updated.`);await load();}catch(error){setStatus(error instanceof Error?error.message:"School ID changes could not be saved.");}finally{setBusy(null);}}
 function updateDraft(characterId:string,patch:Partial<Draft>){setDrafts(current=>({...current,[characterId]:{...(current[characterId]??{idNumber:"",schoolYear:"2006-2007",status:"active"}),...patch}}));}
 return <section className={styles.panel} aria-labelledby="school-id-manager-title"><div className={styles.heading}><div><p className="eyebrow">STUDENT IDENTIFICATION</p><h3 id="school-id-manager-title">School ID issuance & editing</h3><p>Owner and Administration can issue IDs, edit ID numbers, set the official school year, and update card status. Homeroom information stays synchronized with the student&apos;s current assignment.</p></div><span>HHS ID OFFICE</span></div><div className={styles.status}>{status}</div><div className={styles.grid}>{students.length===0?<p className={styles.empty}>No student characters are available yet.</p>:students.map(student=>{const draft=drafts[student.character_id]??{idNumber:student.id_number??"",schoolYear:student.school_year??"2006-2007",status:student.id_status??"active"};return <article key={student.character_id} className={styles.card}><div className={styles.identity}><strong>{student.display_name}</strong><span>@{student.handle}</span><small>{student.homeroom_code?`Homeroom ${student.homeroom_code}${student.grade_level?` • Year ${student.grade_level}`:""}`:"Homeroom assigned with schedule"}</small></div><div className={styles.editor}><label><span>ID number</span><input value={draft.idNumber} onChange={e=>updateDraft(student.character_id,{idNumber:e.target.value.toUpperCase()})} placeholder="HHS-0000-0000"/></label><label><span>School year</span><input value={draft.schoolYear} onChange={e=>updateDraft(student.character_id,{schoolYear:e.target.value})} placeholder="2006-2007"/></label><label><span>Status</span><select value={draft.status} onChange={e=>updateDraft(student.character_id,{status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="reissued">Reissued</option></select></label></div><div className={styles.actions}><button type="button" disabled={busy===student.character_id} onClick={()=>void issue(student.character_id)}>{student.id_number?"Reactivate / confirm":"Issue school ID"}</button><button type="button" disabled={busy===student.character_id} onClick={()=>void save(student.character_id)}>Save ID changes</button></div>{student.issued_at&&<small className={styles.issued}>Issued {new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",year:"numeric"}).format(new Date(student.issued_at))}</small>}</article>;})}</div></section>;
}
