"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./AdminOperationsExpansionPanel.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Stats={student_characters:number;faculty_characters:number;active_characters:number;course_enrollments:number;organization_memberships:number;open_reports:number;open_office_requests:number;open_support_tickets:number};
type Homeroom={id:string;code:string;grade_level:number;room_label:string|null;is_active:boolean};type Room={id:string;room_number:string;building:string;floor_label:string;purpose:string;department:string|null;availability_status:string};type Wait={id:string;section_id:string;student_character_id:string;position:number;status:string};type Counseling={id:string;student_character_id:string;request_type:string;status:string;counselor_name:string|null;appointment_at:string|null;student_note:string;staff_note:string};type Health={id:string;student_character_id:string;reason:string;status:string;staff_response:string};type Ticket={id:string;subject:string;category:string;status:string;priority:string;tags:string[];assigned_to:string|null;created_at:string};type Conduct={id:string;student_character_id:string;case_type:string;title:string;status:string;appeal_status:string;details:string};type Team={id:string;name:string;sport:string;season:string;is_active:boolean};type Election={id:string;title:string;status:string;school_year:string};type Organization={activity_id:string;recruitment_status:string;application_required:boolean};

export default function AdminOperationsExpansionPanel({accessToken,userId}:{accessToken:string;userId:string}){
 const [stats,setStats]=useState<Stats|null>(null),[homerooms,setHomerooms]=useState<Homeroom[]>([]),[rooms,setRooms]=useState<Room[]>([]),[waits,setWaits]=useState<Wait[]>([]),[counseling,setCounseling]=useState<Counseling[]>([]),[health,setHealth]=useState<Health[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[conduct,setConduct]=useState<Conduct[]>([]),[teams,setTeams]=useState<Team[]>([]),[elections,setElections]=useState<Election[]>([]),[organizations,setOrganizations]=useState<Organization[]>([]),[status,setStatus]=useState("Loading school operations…");
 const [roomDraft,setRoomDraft]=useState({room_number:"",building:"Main Building",floor_label:"1F",purpose:"Classroom",department:""});const [homeroomDraft,setHomeroomDraft]=useState({code:"1-A",grade_level:1,room_label:""});const [teamDraft,setTeamDraft]=useState({name:"",sport:"",season:"2006-2007"});const [conductDraft,setConductDraft]=useState({student_character_id:"",case_type:"warning",title:"",details:""});const [electionTitle,setElectionTitle]=useState("");
 const load=useCallback(async()=>{try{const q=(path:string)=>fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:headers(accessToken)}).then(async r=>{if(!r.ok)throw new Error(path);return r.json();});const [s,h,r,w,c,hv,t,co,st,e,o]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/rpc/school_statistics_dashboard`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"}).then(x=>x.json() as Promise<Stats[]>),
  q("homerooms?select=id,code,grade_level,room_label,is_active&order=code"),q("school_rooms?select=id,room_number,building,floor_label,purpose,department,availability_status&order=building,floor_label,room_number"),q("section_waitlist_entries?select=id,section_id,student_character_id,position,status&status=in.(waiting,offered)&order=position"),q("counseling_appointments?select=id,student_character_id,request_type,status,counselor_name,appointment_at,student_note,staff_note&status=in.(requested,scheduled)&order=created_at"),q("health_office_visits?select=id,student_character_id,reason,status,staff_response&status=in.(requested,scheduled)&order=created_at"),q("support_tickets?select=id,subject,category,status,priority,tags,assigned_to,created_at&status=not.in.(resolved,closed)&order=created_at.desc"),q("student_conduct_cases?select=id,student_character_id,case_type,title,status,appeal_status,details&order=created_at.desc&limit=25"),q("sports_teams?select=id,name,sport,season,is_active&order=name"),q("school_elections?select=id,title,status,school_year&order=created_at.desc"),q("organization_profiles?select=activity_id,recruitment_status,application_required")
 ]);setStats(s[0]??null);setHomerooms(h as Homeroom[]);setRooms(r as Room[]);setWaits(w as Wait[]);setCounseling(c as Counseling[]);setHealth(hv as Health[]);setTickets(t as Ticket[]);setConduct(co as Conduct[]);setTeams(st as Team[]);setElections(e as Election[]);setOrganizations(o as Organization[]);setStatus("School operations updated.");}catch{setStatus("Some school operations could not be loaded. Your permissions may limit this console.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function insert(table:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});setStatus(r.ok?`${table.replaceAll("_"," ")} record created.`:`${table.replaceAll("_"," ")} record could not be created.`);if(r.ok)await load();}
 async function patch(table:string,id:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...body,updated_at:new Date().toISOString()})});setStatus(r.ok?"Record updated.":"Record could not be updated.");if(r.ok)await load();}
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">SCHOOL OPERATIONS CONSOLE</p><h4>Administration depth</h4></div><span>{status}</span></div>
  {stats&&<div className={styles.stats}>{Object.entries(stats).map(([k,v])=><div key={k}><strong>{v}</strong><span>{k.replaceAll("_"," ")}</span></div>)}</div>}
  <div className={styles.grid}>
   <article><h5>Homerooms</h5><div className={styles.form}><input value={homeroomDraft.code} onChange={e=>setHomeroomDraft(x=>({...x,code:e.target.value}))} placeholder="1-A"/><input type="number" min="1" max="4" value={homeroomDraft.grade_level} onChange={e=>setHomeroomDraft(x=>({...x,grade_level:Number(e.target.value)}))}/><input value={homeroomDraft.room_label} onChange={e=>setHomeroomDraft(x=>({...x,room_label:e.target.value}))} placeholder="Room 201"/><button onClick={()=>insert("homerooms",{...homeroomDraft,school_year:"2006-2007"})}>Create homeroom</button></div>{homerooms.map(h=><p key={h.id}><strong>{h.code}</strong> • Grade {h.grade_level} • {h.room_label??"Room TBA"} • {h.is_active?"Active":"Inactive"}</p>)}</article>
   <article><h5>Room Directory</h5><div className={styles.form}><input value={roomDraft.room_number} onChange={e=>setRoomDraft(x=>({...x,room_number:e.target.value}))} placeholder="201"/><input value={roomDraft.building} onChange={e=>setRoomDraft(x=>({...x,building:e.target.value}))}/><input value={roomDraft.floor_label} onChange={e=>setRoomDraft(x=>({...x,floor_label:e.target.value}))}/><input value={roomDraft.purpose} onChange={e=>setRoomDraft(x=>({...x,purpose:e.target.value}))}/><input value={roomDraft.department} onChange={e=>setRoomDraft(x=>({...x,department:e.target.value}))} placeholder="Department"/><button onClick={()=>insert("school_rooms",roomDraft)}>Add room</button></div>{rooms.slice(0,10).map(r=><p key={r.id}><strong>{r.room_number}</strong> • {r.building} {r.floor_label} • {r.purpose} • {r.availability_status}</p>)}</article>
   <article><h5>Class Waitlists</h5>{waits.length?waits.map(w=><div className={styles.row} key={w.id}><span>Position {w.position} • Student {w.student_character_id.slice(0,8)}… • Section {w.section_id.slice(0,8)}…</span><select value={w.status} onChange={e=>patch("section_waitlist_entries",w.id,{status:e.target.value,resolved_at:["enrolled","declined","removed"].includes(e.target.value)?new Date().toISOString():null})}><option>waiting</option><option>offered</option><option>enrolled</option><option>declined</option><option>removed</option></select></div>):<p>No active class waitlists.</p>}</article>
   <article><h5>Counseling Queue</h5>{counseling.length?counseling.map(c=><div className={styles.row} key={c.id}><strong>{c.request_type.replaceAll("_"," ")}</strong><span>{c.student_note}</span><select value={c.status} onChange={e=>patch("counseling_appointments",c.id,{status:e.target.value})}><option>requested</option><option>scheduled</option><option>completed</option><option>cancelled</option></select></div>):<p>No counseling requests waiting.</p>}</article>
   <article><h5>Health Office Queue</h5>{health.length?health.map(v=><div className={styles.row} key={v.id}><strong>{v.status.toUpperCase()}</strong><span>{v.reason}</span><select value={v.status} onChange={e=>patch("health_office_visits",v.id,{status:e.target.value})}><option>requested</option><option>scheduled</option><option>seen</option><option>cancelled</option></select></div>):<p>No Health Office requests waiting.</p>}</article>
   <article><h5>Support Tickets</h5>{tickets.length?tickets.map(t=><div className={styles.row} key={t.id}><strong>{t.priority.toUpperCase()} • {t.subject}</strong><span>{t.category} • {t.tags.join(", ")||"no tags"}</span><select value={t.status} onChange={e=>patch("support_tickets",t.id,{status:e.target.value,assigned_to:e.target.value==="assigned"?userId:t.assigned_to})}><option>open</option><option>assigned</option><option>waiting_on_requester</option><option>resolved</option><option>closed</option></select></div>):<p>No open support tickets.</p>}</article>
   <article><h5>Discipline / Conduct</h5><div className={styles.form}><input value={conductDraft.student_character_id} onChange={e=>setConductDraft(x=>({...x,student_character_id:e.target.value}))} placeholder="Student character UUID"/><select value={conductDraft.case_type} onChange={e=>setConductDraft(x=>({...x,case_type:e.target.value}))}><option>warning</option><option>incident</option><option>detention</option><option>other</option></select><input value={conductDraft.title} onChange={e=>setConductDraft(x=>({...x,title:e.target.value}))} placeholder="Case title"/><textarea value={conductDraft.details} onChange={e=>setConductDraft(x=>({...x,details:e.target.value}))} placeholder="Private case details"/><button onClick={()=>insert("student_conduct_cases",{...conductDraft,created_by:userId})}>Create conduct case</button></div>{conduct.slice(0,8).map(c=><div className={styles.row} key={c.id}><strong>{c.case_type.toUpperCase()} • {c.title}</strong><span>{c.status} • appeal {c.appeal_status}</span></div>)}</article>
   <article><h5>Sports Teams & Eligibility</h5><div className={styles.form}><input value={teamDraft.name} onChange={e=>setTeamDraft(x=>({...x,name:e.target.value}))} placeholder="Team name"/><input value={teamDraft.sport} onChange={e=>setTeamDraft(x=>({...x,sport:e.target.value}))} placeholder="Sport"/><button onClick={()=>insert("sports_teams",teamDraft)}>Create sports team</button></div>{teams.map(t=><p key={t.id}><strong>{t.name}</strong> • {t.sport} • {t.season}</p>)}<p className={styles.note}>Athletics eligibility is stored per Student and combines academic + attendance standing. Staff can manage individual eligibility records through the table-backed administration API.</p></article>
   <article><h5>School Elections</h5><div className={styles.form}><input value={electionTitle} onChange={e=>setElectionTitle(e.target.value)} placeholder="Student Council Election"/><button onClick={()=>insert("school_elections",{title:electionTitle,description:"",school_year:"2006-2007",created_by:userId})}>Create election cycle</button></div>{elections.map(e=><div className={styles.row} key={e.id}><strong>{e.title}</strong><select value={e.status} onChange={x=>patch("school_elections",e.id,{status:x.target.value})}><option>draft</option><option>nominations</option><option>voting</option><option>closed</option><option>archived</option></select></div>)}</article>
   <article><h5>Organization Recruitment</h5>{organizations.length?organizations.map(o=><div className={styles.row} key={o.activity_id}><span>Organization {o.activity_id.slice(0,8)}…</span><select value={o.recruitment_status} onChange={e=>fetch(`${SUPABASE_URL}/rest/v1/organization_profiles?activity_id=eq.${o.activity_id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({recruitment_status:e.target.value,updated_at:new Date().toISOString()})}).then(()=>load())}><option>open</option><option>closed</option><option>invite_only</option></select></div>):<p>No organization profiles configured yet.</p>}</article>
  </div>
 </section>;
}
