"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Theme={id:string;theme_key:string;title:string;starts_on:string;ends_on:string;enabled:boolean};
type Transit={id:string;code:string;name:string;mode:string;description:string;is_active:boolean};
type Lore={id:string;title:string;slug:string;category:string;summary:string;status:string};
type Canon={id:string;subject:string;fact:string;classification:string};
type Signup={id:string;title:string;signup_type:string;capacity:number|null;is_open:boolean};
type Channel={id:string;title:string;channel_key:string;description:string;is_active:boolean};
type Feedback={id:string;title:string;description:string;item_type:string;status:string};
const box:React.CSSProperties={border:"1px solid #b7c3d0",background:"#fff",padding:12};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",gap:12};

export default function AdminRoadmapManager({accessToken,userId}:{accessToken:string;userId:string}){
 const [themes,setThemes]=useState<Theme[]>([]);const [transit,setTransit]=useState<Transit[]>([]);const [lore,setLore]=useState<Lore[]>([]);const [canon,setCanon]=useState<Canon[]>([]);const [signups,setSignups]=useState<Signup[]>([]);const [channels,setChannels]=useState<Channel[]>([]);const [feedback,setFeedback]=useState<Feedback[]>([]);const [notice,setNotice]=useState("Loading roadmap administration…");
 const [themeKey,setThemeKey]=useState("sakura");const [themeTitle,setThemeTitle]=useState("Sakura Season");const [themeStart,setThemeStart]=useState("");const [themeEnd,setThemeEnd]=useState("");
 const [lineCode,setLineCode]=useState("");const [lineName,setLineName]=useState("");const [lineMode,setLineMode]=useState("train");
 const [loreTitle,setLoreTitle]=useState("");const [loreCategory,setLoreCategory]=useState("school_history");const [loreSummary,setLoreSummary]=useState("");
 const [canonSubject,setCanonSubject]=useState("");const [canonFact,setCanonFact]=useState("");const [canonClass,setCanonClass]=useState("confirmed");
 const [signupTitle,setSignupTitle]=useState("");const [signupType,setSignupType]=useState("volunteer");const [signupCapacity,setSignupCapacity]=useState("");
 const [channelKey,setChannelKey]=useState("preview");const [channelTitle,setChannelTitle]=useState("Hanami Preview");const [channelDescription,setChannelDescription]=useState("");
 const load=useCallback(async()=>{try{const rs=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/school_theme_schedule?select=id,theme_key,title,starts_on,ends_on,enabled&order=starts_on.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/city_transit_lines?select=id,code,name,mode,description,is_active&order=display_order`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/lore_pages?select=id,title,slug,category,summary,status&order=updated_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/canon_facts?select=id,subject,fact,classification&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/activity_signup_sheets?select=id,title,signup_type,capacity,is_open&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/tester_release_channels?select=id,title,channel_key,description,is_active&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/feature_feedback_items?select=id,title,description,item_type,status&order=created_at.desc&limit=100`,{headers:headers(accessToken)})
 ]);const setters=[setThemes,setTransit,setLore,setCanon,setSignups,setChannels,setFeedback] as Array<(value:any)=>void>;for(let i=0;i<rs.length;i++)if(rs[i].ok)setters[i](await rs[i].json());setNotice("Roadmap administration ready.");}catch{setNotice("Roadmap administration could not be fully loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function post(table:string,body:Record<string,unknown>,success:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});setNotice(response.ok?success:`${success.replace(/\.$/,"")} failed.`);if(response.ok)void load();}
 async function patch(table:string,id:string,body:Record<string,unknown>,success:string){const response=await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});setNotice(response.ok?success:"Update failed.");if(response.ok)void load();}
 function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")||`lore-${Date.now()}`;}
 async function createTheme(e:FormEvent){e.preventDefault();if(!themeStart||!themeEnd)return;await post("school_theme_schedule",{theme_key:themeKey,title:themeTitle,starts_on:themeStart,ends_on:themeEnd,enabled:true,created_by:userId},"Theme scheduled.");}
 async function createTransit(e:FormEvent){e.preventDefault();if(!lineCode.trim()||!lineName.trim())return;await post("city_transit_lines",{code:lineCode.trim().toUpperCase(),name:lineName.trim(),mode:lineMode,description:"Fictional Hanami City transit line",is_active:true},"Transit line created.");setLineCode("");setLineName("");}
 async function createLore(e:FormEvent){e.preventDefault();if(!loreTitle.trim())return;await post("lore_pages",{slug:slugify(loreTitle),title:loreTitle.trim(),category:loreCategory,summary:loreSummary.trim(),body:loreSummary.trim(),status:"draft",created_by:userId},"Lore draft created.");setLoreTitle("");setLoreSummary("");}
 async function createCanon(e:FormEvent){e.preventDefault();if(!canonSubject.trim()||!canonFact.trim())return;await post("canon_facts",{subject:canonSubject.trim(),fact:canonFact.trim(),classification:canonClass,created_by:userId},"Canon entry created.");setCanonSubject("");setCanonFact("");}
 async function createSignup(e:FormEvent){e.preventDefault();if(!signupTitle.trim())return;await post("activity_signup_sheets",{title:signupTitle.trim(),signup_type:signupType,capacity:signupCapacity?Number(signupCapacity):null,is_open:true,created_by:userId},"Sign-up sheet opened.");setSignupTitle("");setSignupCapacity("");}
 async function createChannel(e:FormEvent){e.preventDefault();if(!channelKey.trim()||!channelTitle.trim())return;await post("tester_release_channels",{channel_key:channelKey.trim().toLowerCase().replace(/\s+/g,"_"),title:channelTitle.trim(),description:channelDescription.trim(),is_active:true,created_by:userId},"Tester channel created.");}
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#eef3f8",padding:14}} aria-label="Roadmap administration"><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><p className="eyebrow">ROADMAP ADMINISTRATION</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Roadmap Systems Manager</h3></div><small>{notice}</small></div><div style={grid}>
 <article style={box}><h4>Schoolwide Theme Scheduler</h4><form onSubmit={createTheme} style={{display:"grid",gap:6}}><select value={themeKey} onChange={e=>setThemeKey(e.target.value)}>{["standard","sakura","rainy_season","summer_matsuri","halloween","autumn","winter","culture_festival","sports_day","graduation","web_2006"].map(v=><option key={v}>{v}</option>)}</select><input value={themeTitle} onChange={e=>setThemeTitle(e.target.value)} placeholder="Theme title"/><input type="date" value={themeStart} onChange={e=>setThemeStart(e.target.value)}/><input type="date" value={themeEnd} onChange={e=>setThemeEnd(e.target.value)}/><button>Schedule theme</button></form>{themes.slice(0,5).map(t=><p key={t.id}><strong>{t.title}</strong><small style={{display:"block"}}>{t.starts_on}–{t.ends_on} • {t.enabled?"enabled":"disabled"}</small><button type="button" onClick={()=>patch("school_theme_schedule",t.id,{enabled:!t.enabled},t.enabled?"Theme disabled.":"Theme enabled.")}>{t.enabled?"Disable":"Enable"}</button></p>)}</article>
 <article style={box}><h4>Hanami City Transit</h4><form onSubmit={createTransit} style={{display:"grid",gap:6}}><input value={lineCode} onChange={e=>setLineCode(e.target.value)} placeholder="Line code (H1)"/><input value={lineName} onChange={e=>setLineName(e.target.value)} placeholder="Line name"/><select value={lineMode} onChange={e=>setLineMode(e.target.value)}><option value="train">Train</option><option value="bus">Bus</option></select><button>Create line</button></form>{transit.map(line=><p key={line.id}><strong>{line.code} · {line.name}</strong><small style={{display:"block"}}>{line.mode} • {line.is_active?"active":"hidden"}</small></p>)}</article>
 <article style={box}><h4>Lore Wiki</h4><form onSubmit={createLore} style={{display:"grid",gap:6}}><input value={loreTitle} onChange={e=>setLoreTitle(e.target.value)} placeholder="Lore page title"/><select value={loreCategory} onChange={e=>setLoreCategory(e.target.value)}>{["school_history","city_history","neighborhood","tradition","event","principal","alumni","location","other"].map(v=><option key={v}>{v}</option>)}</select><textarea value={loreSummary} onChange={e=>setLoreSummary(e.target.value)} placeholder="Summary / starting text" rows={3}/><button>Create draft</button></form>{lore.slice(0,8).map(page=><p key={page.id}><strong>{page.title}</strong><small style={{display:"block"}}>{page.category} • {page.status}</small>{page.status!=="published"&&<button type="button" onClick={()=>patch("lore_pages",page.id,{status:"published",updated_at:new Date().toISOString()},"Lore page published.")}>Publish</button>}</p>)}</article>
 <article style={box}><h4>Canon Tracker</h4><form onSubmit={createCanon} style={{display:"grid",gap:6}}><input value={canonSubject} onChange={e=>setCanonSubject(e.target.value)} placeholder="Subject"/><textarea value={canonFact} onChange={e=>setCanonFact(e.target.value)} placeholder="Fact / rumor / headcanon" rows={3}/><select value={canonClass} onChange={e=>setCanonClass(e.target.value)}><option value="confirmed">Confirmed</option><option value="rumor">Rumor</option><option value="headcanon">Headcanon</option><option value="retconned">Retconned</option></select><button>Add entry</button></form>{canon.slice(0,8).map(item=><p key={item.id}><strong>{item.subject}</strong><small style={{display:"block"}}>{item.classification} • {item.fact}</small></p>)}</article>
 <article style={box}><h4>Sign-up Sheets</h4><form onSubmit={createSignup} style={{display:"grid",gap:6}}><input value={signupTitle} onChange={e=>setSignupTitle(e.target.value)} placeholder="Activity title"/><select value={signupType} onChange={e=>setSignupType(e.target.value)}>{["volunteer","festival_shift","club_booth","tutoring","sports_day","other"].map(v=><option key={v}>{v}</option>)}</select><input type="number" min="1" value={signupCapacity} onChange={e=>setSignupCapacity(e.target.value)} placeholder="Capacity (optional)"/><button>Open sign-up</button></form>{signups.slice(0,8).map(sheet=><p key={sheet.id}><strong>{sheet.title}</strong><small style={{display:"block"}}>{sheet.signup_type} • {sheet.capacity??"unlimited"} • {sheet.is_open?"open":"closed"}</small><button type="button" onClick={()=>patch("activity_signup_sheets",sheet.id,{is_open:!sheet.is_open},sheet.is_open?"Sign-up closed.":"Sign-up reopened.")}>{sheet.is_open?"Close":"Reopen"}</button></p>)}</article>
 <article style={box}><h4>Tester Release Channels</h4><form onSubmit={createChannel} style={{display:"grid",gap:6}}><input value={channelKey} onChange={e=>setChannelKey(e.target.value)} placeholder="Channel key"/><input value={channelTitle} onChange={e=>setChannelTitle(e.target.value)} placeholder="Channel title"/><textarea value={channelDescription} onChange={e=>setChannelDescription(e.target.value)} placeholder="What testers receive" rows={2}/><button>Create channel</button></form>{channels.map(channel=><p key={channel.id}><strong>{channel.title}</strong><small style={{display:"block"}}>{channel.channel_key} • {channel.is_active?"active":"closed"}</small><button type="button" onClick={()=>patch("tester_release_channels",channel.id,{is_active:!channel.is_active},channel.is_active?"Tester channel closed.":"Tester channel reopened.")}>{channel.is_active?"Close":"Reopen"}</button></p>)}</article>
 <article style={{...box,gridColumn:"1/-1"}}><h4>Feedback Voting Queue</h4>{feedback.length?feedback.map(item=><div key={item.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,borderTop:"1px solid #d9dfe6",padding:"8px 0"}}><span><strong>{item.title}</strong><small style={{display:"block"}}>{item.item_type} • {item.status} • {item.description}</small></span><select value={item.status} onChange={e=>patch("feature_feedback_items",item.id,{status:e.target.value},"Feedback status updated.")}><option value="open">Open</option><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="declined">Declined</option></select></div>):<p>No feedback items yet.</p>}</article>
 </div></section>;
}
