"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminAnnouncementManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";

type Access={site_admin:boolean;content_editor:boolean;moderator:boolean};
type Announcement={id:string;title:string;body:string;category:"general"|"event"|"urgent";status:"draft"|"published"|"archived";featured:boolean;is_test_data:boolean;published_at:string|null;expires_at:string|null;created_at:string;updated_at:string};
type Props={accessToken:string;userId:string;access:Access};
function headers(accessToken:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${accessToken}`,...extra};}

export default function AdminAnnouncementManager({accessToken,userId,access}:Props){
 const [items,setItems]=useState<Announcement[]>([]);const [title,setTitle]=useState("");const [body,setBody]=useState("");const [category,setCategory]=useState<Announcement["category"]>("general");const [featured,setFeatured]=useState(false);const [testData,setTestData]=useState(false);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState("Loading school announcements…");
 const canEdit=access.site_admin||access.content_editor;
 const load=useCallback(async()=>{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_announcements?select=id,title,body,category,status,featured,is_test_data,published_at,expires_at,created_at,updated_at&order=updated_at.desc`,{headers:headers(accessToken)});if(!response.ok)throw new Error("Announcements could not be loaded.");const rows=await response.json() as Announcement[];setItems(rows);setNotice(rows.length?`${rows.length} announcement record${rows.length===1?"":"s"} loaded.`:"No announcement records yet.");},[accessToken]);
 useEffect(()=>{load().catch(error=>setNotice(error instanceof Error?error.message:"Announcements could not be loaded."));},[load]);
 async function createAnnouncement(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!canEdit||saving)return;const cleanTitle=title.trim();const cleanBody=body.trim();if(cleanTitle.length<2||cleanBody.length<1)return;setSaving(true);setNotice("Saving announcement draft…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_announcements`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({title:cleanTitle,body:cleanBody,category,status:"draft",featured,is_test_data:testData,created_by:userId})});if(!response.ok)throw new Error("The announcement draft could not be created.");setTitle("");setBody("");setCategory("general");setFeatured(false);setTestData(false);await load();setNotice("Announcement saved as a draft.");}catch(error){setNotice(error instanceof Error?error.message:"The announcement could not be created.");}finally{setSaving(false);}}
 async function patch(id:string,changes:Partial<Announcement>){if(!canEdit||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_announcements?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...changes,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("The announcement could not be updated.");await load();setNotice("Announcement updated.");}catch(error){setNotice(error instanceof Error?error.message:"The announcement could not be updated.");}finally{setSaving(false);}}
 async function publish(item:Announcement){await patch(item.id,{status:"published",published_at:item.published_at??new Date().toISOString()});}
 async function remove(item:Announcement){if(!access.site_admin||saving)return;if(!window.confirm(`Permanently delete “${item.title}”? This cannot be undone.`))return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/site_announcements?id=eq.${encodeURIComponent(item.id)}`,{method:"DELETE",headers:headers(accessToken)});if(!response.ok)throw new Error("The announcement could not be deleted.");await load();setNotice("Announcement permanently deleted.");}catch(error){setNotice(error instanceof Error?error.message:"The announcement could not be deleted.");}finally{setSaving(false);}}
 return <section className={styles.panel} aria-labelledby="announcement-admin-title"><div className={styles.heading}><div><p className="eyebrow">SITE CONTENT</p><h3 id="announcement-admin-title">Announcement Management</h3></div><span>{canEdit?"EDITOR ACCESS":"READ ONLY"}</span></div><div className={styles.notice} aria-live="polite">{notice}</div>{canEdit&&<form className={styles.form} onSubmit={createAnnouncement}><label><span>Title</span><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} required/></label><label><span>Announcement body</span><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={5000} required/></label><div className={styles.row}><label><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value as Announcement["category"])}><option value="general">General</option><option value="event">Event</option><option value="urgent">Urgent</option></select></label><label className={styles.check}><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/> Featured</label><label className={styles.check}><input type="checkbox" checked={testData} onChange={e=>setTestData(e.target.checked)}/> TEST data</label></div><button type="submit" disabled={saving}>Save draft</button></form>}<div className={styles.list}>{items.map(item=><article key={item.id} className={styles.item}><div className={styles.itemTop}><div><p className="eyebrow">{item.category.toUpperCase()} • {item.status.toUpperCase()}{item.is_test_data?" • TEST":""}</p><h4>{item.title}</h4></div>{item.featured&&<span>FEATURED</span>}</div><p>{item.body}</p><div className={styles.meta}>Updated {new Date(item.updated_at).toLocaleString()} {item.published_at?`• Published ${new Date(item.published_at).toLocaleString()}`:""}</div>{canEdit&&<div className={styles.actions}>{item.status!=="published"&&<button type="button" onClick={()=>publish(item)} disabled={saving}>Publish</button>}{item.status==="published"&&<button type="button" onClick={()=>patch(item.id,{status:"archived"})} disabled={saving}>Archive</button>}{item.status==="archived"&&<button type="button" onClick={()=>patch(item.id,{status:"draft",published_at:null})} disabled={saving}>Return to draft</button>}<button type="button" onClick={()=>patch(item.id,{featured:!item.featured})} disabled={saving}>{item.featured?"Unfeature":"Feature"}</button>{access.site_admin&&<button type="button" className={styles.danger} onClick={()=>remove(item)} disabled={saving}>Delete permanently</button>}</div>}</article>)}</div></section>;
}
