"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import styles from "./AdminClubPublishingPanel.module.css";

const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";

type Activity={id:string;name:string};
type Campaign={id:string;activity_id:string|null;title:string;banner_url:string|null;booth_location:string|null;application_prompt:string|null;starts_at:string;ends_at:string;is_open:boolean;created_at:string};

type Draft={activity_id:string;title:string;banner_url:string;booth_location:string;application_prompt:string;starts_at:string;ends_at:string;is_open:boolean};
const emptyDraft:Draft={activity_id:"",title:"",banner_url:"",booth_location:"",application_prompt:"",starts_at:"",ends_at:"",is_open:true};

function headers(token:string,extra:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${token}`,...extra}}
function localDate(value:string){return new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value))}

export default function AdminClubPublishingPanel({accessToken}:{accessToken:string}){
 const [activities,setActivities]=useState<Activity[]>([]);const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [draft,setDraft]=useState<Draft>(emptyDraft);const [status,setStatus]=useState("Loading club publishing…");const [saving,setSaving]=useState(false);
 const activityNames=useMemo(()=>new Map(activities.map(a=>[a.id,a.name])),[activities]);
 async function load(){try{const [a,c]=await Promise.all([fetch(`${U}/rest/v1/campus_activities?select=id,name&kind=eq.club&is_active=eq.true&order=name.asc`,{headers:headers(accessToken)}),fetch(`${U}/rest/v1/club_recruitment_campaigns?select=id,activity_id,title,banner_url,booth_location,application_prompt,starts_at,ends_at,is_open,created_at&order=created_at.desc`,{headers:headers(accessToken)})]);if(!a.ok||!c.ok)throw new Error("Club publishing data could not be loaded.");setActivities(await a.json() as Activity[]);setCampaigns(await c.json() as Campaign[]);setStatus("Club publishing is current.")}catch(e){setStatus(e instanceof Error?e.message:"Club publishing data could not be loaded.")}}
 useEffect(()=>{void load()},[accessToken]);
 async function createCampaign(e:FormEvent){e.preventDefault();if(!draft.title.trim()||!draft.starts_at||!draft.ends_at)return;setSaving(true);try{const r=await fetch(`${U}/rest/v1/club_recruitment_campaigns`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({activity_id:draft.activity_id||null,title:draft.title.trim(),banner_url:draft.banner_url.trim()||null,booth_location:draft.booth_location.trim()||null,application_prompt:draft.application_prompt.trim()||null,starts_at:new Date(draft.starts_at).toISOString(),ends_at:new Date(draft.ends_at).toISOString(),is_open:draft.is_open})});if(!r.ok)throw new Error(await r.text());setDraft(emptyDraft);await load();setStatus("Club recruitment campaign published.")}catch(e){setStatus(e instanceof Error?e.message:"Club recruitment campaign could not be published.")}finally{setSaving(false)}}
 async function setOpen(id:string,is_open:boolean){try{const r=await fetch(`${U}/rest/v1/club_recruitment_campaigns?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json",Prefer:"return=minimal"}),body:JSON.stringify({is_open})});if(!r.ok)throw new Error(await r.text());await load();setStatus(is_open?"Recruitment campaign reopened.":"Recruitment campaign closed.")}catch(e){setStatus(e instanceof Error?e.message:"Campaign status could not be changed.")}}
 async function remove(id:string){if(!window.confirm("Delete this recruitment campaign? This removes the school publishing record."))return;try{const r=await fetch(`${U}/rest/v1/club_recruitment_campaigns?id=eq.${id}`,{method:"DELETE",headers:headers(accessToken,{Prefer:"return=minimal"})});if(!r.ok)throw new Error(await r.text());await load();setStatus("Recruitment campaign deleted.")}catch(e){setStatus(e instanceof Error?e.message:"Campaign could not be deleted.")}}
 return <section className={styles.panel} aria-label="Club Publishing">
  <header className={styles.head}><div><h2>Club Publishing</h2><p>Publish recruitment windows for active Hanami clubs without granting access to festival, sports, volunteer, or other Campus Operations tools.</p></div><span className={styles.status}>{status}</span></header>
  <form className={styles.form} onSubmit={createCampaign}><label>Club<select value={draft.activity_id} onChange={e=>setDraft({...draft,activity_id:e.target.value})}><option value="">General club recruitment</option>{activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Campaign title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required/></label><label>Starts<input type="datetime-local" value={draft.starts_at} onChange={e=>setDraft({...draft,starts_at:e.target.value})} required/></label><label>Ends<input type="datetime-local" value={draft.ends_at} onChange={e=>setDraft({...draft,ends_at:e.target.value})} required/></label><label>Booth / meeting location<input value={draft.booth_location} onChange={e=>setDraft({...draft,booth_location:e.target.value})}/></label><label>Banner URL<input value={draft.banner_url} onChange={e=>setDraft({...draft,banner_url:e.target.value})}/></label><label className={styles.wide}>Application prompt<textarea value={draft.application_prompt} onChange={e=>setDraft({...draft,application_prompt:e.target.value})} placeholder="What should interested students know or answer?"/></label><label className={styles.checks}><input type="checkbox" checked={draft.is_open} onChange={e=>setDraft({...draft,is_open:e.target.checked})}/> Open recruitment immediately</label><button disabled={saving}>{saving?"Publishing…":"Publish recruitment"}</button></form>
  <div className={styles.list}>{campaigns.map(c=><article className={styles.item} key={c.id}><div><h3>{c.title}</h3><p>{activityNames.get(c.activity_id??"")??"General club recruitment"}{c.booth_location?` · ${c.booth_location}`:""}</p><small>{c.is_open?"OPEN":"CLOSED"} · {localDate(c.starts_at)} → {localDate(c.ends_at)}</small>{c.application_prompt?<p>{c.application_prompt}</p>:null}</div><div className={styles.actions}><button type="button" onClick={()=>void setOpen(c.id,!c.is_open)}>{c.is_open?"Close":"Reopen"}</button><button type="button" onClick={()=>void remove(c.id)}>Delete</button></div></article>)}{!campaigns.length?<div className={styles.empty}>No recruitment campaigns have been published yet.</div>:null}</div>
 </section>;
}
