"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}

type Pass={id:string;student_character_id:string;requested_by_character_id:string|null;issued_by_character_id:string|null;pass_type:string;destination:string;reason:string;status:string;valid_from:string|null;valid_until:string|null;staff_note:string;created_at:string;updated_at:string};
type CharacterRow={character_id:string;display_name:string;handle:string;role:"student"|"faculty"};

export default function AdminHallPassManager({accessToken}:{accessToken:string}){
 const [passes,setPasses]=useState<Pass[]>([]);const [characters,setCharacters]=useState<CharacterRow[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [notice,setNotice]=useState("Loading hall pass requests…");const [saving,setSaving]=useState("");
 const names=useMemo(()=>new Map(characters.map(c=>[c.character_id,c])),[characters]);
 const load=useCallback(async()=>{try{const [passResponse,directoryResponse]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/hall_passes?select=id,student_character_id,requested_by_character_id,issued_by_character_id,pass_type,destination,reason,status,valid_from,valid_until,staff_note,created_at,updated_at&order=created_at.desc&limit=100`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/rpc/administration_character_directory`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({search_term:null})})
 ]);if(!passResponse.ok)throw new Error("Hall pass requests could not be loaded.");const rows=await passResponse.json() as Pass[];setPasses(rows);if(directoryResponse.ok)setCharacters(await directoryResponse.json() as CharacterRow[]);setNotice(`${rows.filter(p=>p.status==="requested").length} pending hall pass request${rows.filter(p=>p.status==="requested").length===1?"":"s"}.`);}catch(error){setNotice(error instanceof Error?error.message:"Hall pass requests could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function review(pass:Pass,status:"approved"|"denied"){setSaving(pass.id);try{const now=new Date();const until=new Date(now.getTime()+30*60*1000);const payload=status==="approved"?{status,staff_note:(notes[pass.id]??"").trim(),valid_from:now.toISOString(),valid_until:until.toISOString(),updated_at:now.toISOString()}:{status,staff_note:(notes[pass.id]??"").trim(),valid_from:null,valid_until:null,updated_at:now.toISOString()};const response=await fetch(`${SUPABASE_URL}/rest/v1/hall_passes?id=eq.${encodeURIComponent(pass.id)}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(payload)});if(!response.ok)throw new Error("Hall pass review could not be saved.");setNotice(status==="approved"?"Hall pass approved for 30 minutes.":"Hall pass request denied.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Hall pass review could not be saved.");}finally{setSaving("");}}
 const pending=passes.filter(p=>p.status==="requested");const recent=passes.filter(p=>p.status!=="requested").slice(0,20);
 const who=(id:string)=>{const row=names.get(id);return row?`${row.display_name} (@${row.handle})`:id;};
 const card=(pass:Pass,reviewable:boolean)=><article key={pass.id} style={{border:"1px solid #c6d0db",padding:12,background:"#fff",display:"grid",gap:6}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><strong>{who(pass.student_character_id)}</strong><span>{pass.status.toUpperCase()}</span></div><div><b>{pass.pass_type.replaceAll("_"," ")}</b> → {pass.destination}</div><p style={{margin:0}}>{pass.reason}</p><small>Requested {new Date(pass.created_at).toLocaleString()}</small>{pass.valid_until&&<small>Valid until {new Date(pass.valid_until).toLocaleString()}</small>}{reviewable&&<><textarea value={notes[pass.id]??pass.staff_note??""} onChange={e=>setNotes(v=>({...v,[pass.id]:e.target.value}))} placeholder="Optional staff note"/><div style={{display:"flex",gap:8}}><button type="button" disabled={saving===pass.id} onClick={()=>review(pass,"approved")}>Approve 30 min</button><button type="button" disabled={saving===pass.id} onClick={()=>review(pass,"denied")}>Deny</button></div></>}</article>;
 return <section style={{marginTop:16,border:"1px solid #aab7c6",background:"#f7f9fb"}} aria-label="Hall pass administration"><div style={{padding:"12px 14px",background:"#e9eff5",borderBottom:"1px solid #c5ced8"}}><p className="eyebrow">STUDENT MOVEMENT</p><h3 style={{margin:"3px 0"}}>Hall Pass Requests</h3><small aria-live="polite">{notice}</small></div><div style={{padding:14,display:"grid",gap:14}}><div><h4>Pending requests ({pending.length})</h4><div style={{display:"grid",gap:8}}>{pending.length?pending.map(p=>card(p,true)):<p>No hall pass requests are waiting for review.</p>}</div></div><details><summary>Recent reviewed passes ({recent.length})</summary><div style={{display:"grid",gap:8,marginTop:10}}>{recent.map(p=>card(p,false))}</div></details></div></section>;
}
