"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminRoleplaySystemsManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Access={site_admin:boolean;content_editor:boolean;moderator:boolean};
type Session={id:string;code:string;title:string;school_year:string;chapter_number:number;season:string;status:string;starts_at:string|null;ends_at:string|null;summary:string;graduation_year_level:string|null};
type Application={id:string;character_id:string;application_type:string;statement:string;status:string;reviewer_note:string;reviewed_at:string|null;created_at:string};
type Character={id:string;display_name:string;handle:string;role:"student"|"faculty"};
export default function AdminRoleplaySystemsManager({accessToken,access}:{accessToken:string;access:Access}){
 const [sessions,setSessions]=useState<Session[]>([]);const [applications,setApplications]=useState<Application[]>([]);const [characters,setCharacters]=useState<Character[]>([]);const [notice,setNotice]=useState("Loading roleplay systems…");const [saving,setSaving]=useState(false);
 const [code,setCode]=useState("");const [title,setTitle]=useState("");const [schoolYear,setSchoolYear]=useState("2006");const [chapter,setChapter]=useState(1);const [season,setSeason]=useState("spring");const [summary,setSummary]=useState("");const [graduationLevel,setGraduationLevel]=useState("");const [startsAt,setStartsAt]=useState("");const [endsAt,setEndsAt]=useState("");const [notes,setNotes]=useState<Record<string,string>>({});
 const canReview=access.site_admin||access.moderator;
 const load=useCallback(async()=>{const [s,a,c]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/roleplay_sessions?select=id,code,title,school_year,chapter_number,season,status,starts_at,ends_at,summary,graduation_year_level&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/character_applications?select=id,character_id,application_type,statement,status,reviewer_note,reviewed_at,created_at&order=created_at.desc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle,role&order=display_name.asc`,{headers:headers(accessToken)})]);if(s.ok)setSessions(await s.json());if(a.ok){const rows=await a.json() as Application[];setApplications(rows);setNotes(Object.fromEntries(rows.map(x=>[x.id,x.reviewer_note??""])));}if(c.ok)setCharacters(await c.json());setNotice("Roleplay session and character review tools ready.");},[accessToken]);
 useEffect(()=>{void load();},[load]);
 const name=(id:string)=>{const c=characters.find(x=>x.id===id);return c?`${c.display_name} (@${c.handle}) • ${c.role}`:id.slice(0,8);};
 async function createSession(event:FormEvent){event.preventDefault();if(!access.site_admin||saving)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/roleplay_sessions`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({code:code.trim(),title:title.trim(),school_year:schoolYear.trim(),chapter_number:chapter,season,status:"planning",summary:summary.trim(),graduation_year_level:graduationLevel.trim()||null,starts_at:startsAt?new Date(startsAt).toISOString():null,ends_at:endsAt?new Date(endsAt).toISOString():null})});if(!response.ok)throw new Error("Session could not be created.");setCode("");setTitle("");setSummary("");setStartsAt("");setEndsAt("");await load();setNotice("Roleplay session created in planning state.");}catch(error){setNotice(error instanceof Error?error.message:"Session could not be created.");}finally{setSaving(false);}}
 async function setSessionStatus(item:Session,status:string){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/roleplay_sessions?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Session status could not be changed.");await load();setNotice(`${item.title} is now ${status}.`);}catch(error){setNotice(error instanceof Error?error.message:"Session could not be changed.");}finally{setSaving(false);}}
 async function reviewApplication(item:Application,status:"approved"|"changes_requested"|"denied"){if(!canReview)return;setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/character_applications?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,reviewer_note:notes[item.id]??"",reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Character application decision could not be saved.");await load();setNotice(`${name(item.character_id)} application marked ${status.replaceAll("_"," ")}.`);}catch(error){setNotice(error instanceof Error?error.message:"Character application could not be reviewed.");}finally{setSaving(false);}}
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">ROLEPLAY OPERATIONS</p><h3>Sessions & Character Applications</h3></div><span>{access.site_admin?"SITE ADMIN":"MODERATION"}</span></div><div className={styles.notice}>{notice}</div><div className={styles.grid}>
  {access.site_admin&&<div className={styles.block}><h4>Session / Chapter Manager</h4><form onSubmit={createSession}><div className={styles.row}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Code, e.g. S1-2006" required/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Session title" required/></div><div className={styles.row}><input value={schoolYear} onChange={e=>setSchoolYear(e.target.value)} placeholder="School year"/><input type="number" min="1" value={chapter} onChange={e=>setChapter(Number(e.target.value))}/><select value={season} onChange={e=>setSeason(e.target.value)}><option value="spring">Spring</option><option value="summer">Summer</option><option value="autumn">Autumn</option><option value="winter">Winter</option><option value="graduation">Graduation</option></select></div><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Session/chapter summary"/><input value={graduationLevel} onChange={e=>setGraduationLevel(e.target.value)} placeholder="Graduation group, optional"/><div className={styles.row}><label>Starts <input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label>Ends <input type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label></div><button disabled={saving}>Create planning session</button></form><div className={styles.list}>{sessions.map(item=><article key={item.id}><strong>{item.title}</strong><span>{item.code} • {item.school_year} • chapter {item.chapter_number} • {item.season} • {item.status}</span><p>{item.summary||"No summary yet."}</p><div className={styles.actions}>{item.status==="planning"&&<button onClick={()=>setSessionStatus(item,"active")}>Activate</button>}{item.status==="active"&&<button onClick={()=>setSessionStatus(item,"closing")}>Begin closing</button>}{item.status==="closing"&&<button onClick={()=>setSessionStatus(item,"archived")}>Archive session</button>}{item.status==="archived"&&<button onClick={()=>setSessionStatus(item,"planning")}>Reopen planning</button>}</div></article>)}</div></div>}
  {canReview&&<div className={styles.block}><h4>Character Application Review</h4><p>Use this for foreign Students/Faculty, delinquents, Gyaru concepts, and other characters that require approval.</p><div className={styles.list}>{applications.length?applications.map(item=><article key={item.id}><strong>{name(item.character_id)}</strong><span>{item.application_type.replaceAll("_"," ")} • {item.status.replaceAll("_"," ")}</span><p>{item.statement||"No statement supplied."}</p><textarea value={notes[item.id]??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Reviewer note"/><div className={styles.actions}><button disabled={saving} onClick={()=>reviewApplication(item,"approved")}>Approve</button><button disabled={saving} onClick={()=>reviewApplication(item,"changes_requested")}>Request changes</button><button disabled={saving} onClick={()=>reviewApplication(item,"denied")}>Deny</button></div></article>):<p>No character applications are currently visible to this role.</p>}</div></div>}
 </div></section>;
}
