"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./AdminCommandCenter.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Access={site_admin:boolean;content_editor:boolean;moderator:boolean};type Props={accessToken:string;access:Access};type Character={id:string;role:"student"|"faculty";is_active:boolean};type OfficeRow={status:string};type StatusRow={status:string};
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
export default function AdminCommandCenter({accessToken,access}:Props){const [characters,setCharacters]=useState<Character[]>([]),[sections,setSections]=useState(0),[office,setOffice]=useState<OfficeRow[]>([]),[support,setSupport]=useState<StatusRow[]>([]),[newspaper,setNewspaper]=useState<StatusRow[]>([]),[elections,setElections]=useState<StatusRow[]>([]),[festival,setFestival]=useState<StatusRow[]>([]),[volunteers,setVolunteers]=useState<StatusRow[]>([]),[message,setMessage]=useState("Loading school operations…");useEffect(()=>{let dead=false;(async()=>{try{const [c,s,o,t,n,e,f,v]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,role,is_active`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/rpc/office_request_queue`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/support_tickets?select=status`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/newspaper_applications?select=status`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/election_candidate_applications?select=status`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/festival_plans?select=status`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/event_volunteer_signups?select=status`,{headers:headers(accessToken)})]);if(!c.ok||!s.ok)throw new Error("Administration overview could not be loaded.");const chars=await c.json() as Character[],sectionRows=await s.json() as {id:string}[];if(!dead){setCharacters(chars);setSections(sectionRows.length);setOffice(o.ok?await o.json():[]);setSupport(t.ok?await t.json():[]);setNewspaper(n.ok?await n.json():[]);setElections(e.ok?await e.json():[]);setFestival(f.ok?await f.json():[]);setVolunteers(v.ok?await v.json():[]);setMessage("School operations and review queues are current.");}}catch(error){if(!dead)setMessage(error instanceof Error?error.message:"Administration overview unavailable.");}})();return()=>{dead=true};},[accessToken]);
 const students=useMemo(()=>characters.filter(x=>x.role==="student").length,[characters]),faculty=useMemo(()=>characters.filter(x=>x.role==="faculty").length,[characters]),active=useMemo(()=>characters.filter(x=>x.is_active).length,[characters]);const queue=useMemo(()=>({office:office.filter(x=>["submitted","in_review"].includes(x.status)).length,support:support.filter(x=>["open","in_progress","waiting"].includes(x.status)).length,newspaper:newspaper.filter(x=>["submitted","pending"].includes(x.status)).length,elections:elections.filter(x=>x.status==="pending").length,festival:festival.filter(x=>["submitted","pending_review"].includes(x.status)).length,volunteers:volunteers.filter(x=>x.status==="pending").length}),[office,support,newspaper,elections,festival,volunteers]);const total=Object.values(queue).reduce((a,b)=>a+b,0);const canEditContent=access.site_admin||access.content_editor,canModerate=access.site_admin||access.moderator;
 function open(view:string,tool:string){window.dispatchEvent(new CustomEvent("hanami-admin-command",{detail:{view,tool}}))}
 return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">SCHOOL OPERATIONS</p><h3>Administration command center</h3></div><span>{total?`${total} ITEM${total===1?"":"S"} NEED REVIEW`:"QUEUES CLEAR"}</span></div><div className={styles.stats}><article><span>STUDENTS</span><strong>{students}</strong></article><article><span>FACULTY</span><strong>{faculty}</strong></article><article><span>ACTIVE CHARACTERS</span><strong>{active}</strong></article><article><span>CLASS SECTIONS</span><strong>{sections}</strong></article><article><span>TOTAL QUEUE</span><strong>{total}</strong></article></div><div className={styles.workflow}>{canEditContent&&<button type="button" onClick={()=>open("communications","requests")}><strong>School Office</strong><span>{queue.office} request{queue.office===1?"":"s"} need review.</span></button>}{canModerate&&<button type="button" onClick={()=>open("communications","tickets")}><strong>Support</strong><span>{queue.support} ticket{queue.support===1?"":"s"} open or waiting.</span></button>}{access.site_admin&&<button type="button" onClick={()=>open("people","applications")}><strong>Applications</strong><span>{queue.newspaper} newspaper · {queue.elections} election</span></button>}{access.site_admin&&<button type="button" onClick={()=>open("campus","campusOps")}><strong>Campus Operations</strong><span>{queue.festival} festival · {queue.volunteers} volunteer</span></button>}</div><p className={styles.status}>{message}</p></section>}
