"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Election={id:string;title:string;description:string;school_year:string;status:string;nominations_open_at:string|null;nominations_close_at:string|null;voting_open_at:string|null;voting_close_at:string|null};
type Position={id:string;election_id:string;title:string;description:string;eligibility_note:string;sort_order:number};
type Nomination={id:string;position_id:string;candidate_character_id:string;statement:string;status:string};
type Character={id:string;display_name:string;handle:string};
type Activity={id:string;name:string;kind:string};
type OrgProfile={activity_id:string;recruitment_status:string;application_required:boolean};
type OrgApplication={id:string;activity_id:string;student_character_id:string;statement:string;status:string;staff_response:string};
const card:React.CSSProperties={border:"1px solid #c5ced8",background:"#fff",padding:10};

export default function AdminCommunityOperationsPanel({accessToken,userId}:{accessToken:string;userId:string}){
 const [elections,setElections]=useState<Election[]>([]),[positions,setPositions]=useState<Position[]>([]),[nominations,setNominations]=useState<Nomination[]>([]),[characters,setCharacters]=useState<Character[]>([]),[activities,setActivities]=useState<Activity[]>([]),[profiles,setProfiles]=useState<OrgProfile[]>([]),[applications,setApplications]=useState<OrgApplication[]>([]);
 const [notice,setNotice]=useState("Loading community operations…"),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[schoolYear,setSchoolYear]=useState("2006-2007");
 const [electionId,setElectionId]=useState(""),[positionTitle,setPositionTitle]=useState(""),[positionDescription,setPositionDescription]=useState(""),[eligibility,setEligibility]=useState("");
 const [responses,setResponses]=useState<Record<string,string>>({});
 const chars=useMemo(()=>new Map(characters.map(c=>[c.id,c])),[characters]);const acts=useMemo(()=>new Map(activities.map(a=>[a.id,a])),[activities]);
 const load=useCallback(async()=>{try{const urls=[
  `${SUPABASE_URL}/rest/v1/school_elections?select=id,title,description,school_year,status,nominations_open_at,nominations_close_at,voting_open_at,voting_close_at&order=created_at.desc`,
  `${SUPABASE_URL}/rest/v1/election_positions?select=id,election_id,title,description,eligibility_note,sort_order&order=sort_order`,
  `${SUPABASE_URL}/rest/v1/election_nominations?select=id,position_id,candidate_character_id,statement,status&order=created_at.desc`,
  `${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&order=display_name`,
  `${SUPABASE_URL}/rest/v1/campus_activities?select=id,name,kind&is_active=eq.true&order=name`,
  `${SUPABASE_URL}/rest/v1/organization_profiles?select=activity_id,recruitment_status,application_required`,
  `${SUPABASE_URL}/rest/v1/organization_applications?select=id,activity_id,student_character_id,statement,status,staff_response&order=created_at.desc`
 ];const rs=await Promise.all(urls.map(url=>fetch(url,{headers:headers(accessToken)})));const json=await Promise.all(rs.map(async r=>r.ok?await r.json():[]));setElections(json[0]);setPositions(json[1]);setNominations(json[2]);setCharacters(json[3]);setActivities(json[4]);setProfiles(json[5]);setApplications(json[6]);setResponses(Object.fromEntries((json[6] as OrgApplication[]).map(a=>[a.id,a.staff_response??""])));setElectionId(v=>v||(json[0] as Election[])[0]?.id||"");setNotice("Community operations ready.");}catch(error){setNotice(error instanceof Error?error.message:"Community operations could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function post(table:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error("Create operation failed.");}
 async function patch(table:string,id:string,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({...body,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Update operation failed.");}
 async function createElection(e:FormEvent){e.preventDefault();if(!title.trim())return;setBusy(true);try{await post("school_elections",{title:title.trim(),description:description.trim(),school_year:schoolYear.trim(),status:"draft",created_by:userId});setTitle("");setDescription("");setNotice("Election draft created.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Election could not be created.");}finally{setBusy(false);}}
 async function setElectionStatus(row:Election,status:string){setBusy(true);try{await patch("school_elections",row.id,{status});setNotice(`${row.title} moved to ${status}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Election status could not be changed.");}finally{setBusy(false);}}
 async function createPosition(e:FormEvent){e.preventDefault();if(!electionId||!positionTitle.trim())return;setBusy(true);try{await post("election_positions",{election_id:electionId,title:positionTitle.trim(),description:positionDescription.trim(),eligibility_note:eligibility.trim(),sort_order:positions.filter(p=>p.election_id===electionId).length});setPositionTitle("");setPositionDescription("");setEligibility("");setNotice("Election position added.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Position could not be added.");}finally{setBusy(false);}}
 async function reviewNomination(row:Nomination,status:"approved"|"rejected"){setBusy(true);try{await patch("election_nominations",row.id,{status});setNotice(`Nomination ${status}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Nomination could not be reviewed.");}finally{setBusy(false);}}
 async function reviewApplication(row:OrgApplication,status:"approved"|"declined"|"under_review"){setBusy(true);try{await patch("organization_applications",row.id,{status,staff_response:responses[row.id]??""});setNotice(`Organization application marked ${status.replaceAll("_"," ")}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Organization application could not be reviewed.");}finally{setBusy(false);}}
 async function setRecruitment(profile:OrgProfile,status:string){setBusy(true);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/organization_profiles?activity_id=eq.${profile.activity_id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({recruitment_status:status,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Recruitment status could not be changed.");setNotice("Organization recruitment updated.");await load();}catch(error){setNotice(error instanceof Error?error.message:"Recruitment status could not be changed.");}finally{setBusy(false);}}
 const name=(id:string)=>{const c=chars.get(id);return c?`${c.display_name} (@${c.handle})`:id.slice(0,8);};
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14}} aria-label="Community operations"><p className="eyebrow">COMMUNITY OPERATIONS</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Organizations & School Elections</h3><small>{notice}</small><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12,marginTop:12}}>
 <article style={card}><h4>Election Lifecycle</h4><form onSubmit={createElection} style={{display:"grid",gap:5}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Election title" required/><input value={schoolYear} onChange={e=>setSchoolYear(e.target.value)} placeholder="School year"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description"/><button disabled={busy}>Create draft election</button></form>{elections.map(row=><div key={row.id} style={{borderTop:"1px solid #e1e5ea",padding:"7px 0"}}><strong>{row.title}</strong><small style={{display:"block"}}>{row.school_year} • {row.status}</small><div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:4}}>{row.status==="draft"&&<button disabled={busy} onClick={()=>void setElectionStatus(row,"nominations")}>Open nominations</button>}{row.status==="nominations"&&<button disabled={busy} onClick={()=>void setElectionStatus(row,"voting")}>Open voting</button>}{row.status==="voting"&&<button disabled={busy} onClick={()=>void setElectionStatus(row,"closed")}>Close voting</button>}{row.status==="closed"&&<button disabled={busy} onClick={()=>void setElectionStatus(row,"archived")}>Archive</button>}</div></div>)}</article>
 <article style={card}><h4>Election Positions</h4><form onSubmit={createPosition} style={{display:"grid",gap:5}}><select value={electionId} onChange={e=>setElectionId(e.target.value)}>{elections.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><input value={positionTitle} onChange={e=>setPositionTitle(e.target.value)} placeholder="Position title" required/><input value={positionDescription} onChange={e=>setPositionDescription(e.target.value)} placeholder="Position description"/><input value={eligibility} onChange={e=>setEligibility(e.target.value)} placeholder="Eligibility note"/><button disabled={busy||!electionId}>Add position</button></form>{positions.filter(p=>!electionId||p.election_id===electionId).map(p=><small key={p.id} style={{display:"block",marginTop:5}}><strong>{p.title}</strong>{p.eligibility_note?` • ${p.eligibility_note}`:""}</small>)}</article>
 <article style={card}><h4>Nomination Review</h4>{nominations.filter(n=>n.status==="submitted").length?nominations.filter(n=>n.status==="submitted").map(n=><div key={n.id} style={{borderTop:"1px solid #e1e5ea",padding:"7px 0"}}><strong>{name(n.candidate_character_id)}</strong><small style={{display:"block"}}>{positions.find(p=>p.id===n.position_id)?.title??"Election position"}</small><p style={{fontSize:9}}>{n.statement}</p><button disabled={busy} onClick={()=>void reviewNomination(n,"approved")}>Approve</button> <button disabled={busy} onClick={()=>void reviewNomination(n,"rejected")}>Reject</button></div>):<p>No nominations await review.</p>}</article>
 <article style={card}><h4>Organization Recruitment</h4>{profiles.map(p=><div key={p.activity_id} style={{borderTop:"1px solid #e1e5ea",padding:"7px 0"}}><strong>{acts.get(p.activity_id)?.name??"Organization"}</strong><small style={{display:"block"}}>Applications {p.application_required?"required":"optional"}</small><select value={p.recruitment_status} disabled={busy} onChange={e=>void setRecruitment(p,e.target.value)}><option value="open">Open</option><option value="limited">Limited</option><option value="closed">Closed</option></select></div>)}</article>
 <article style={card}><h4>Organization Applications</h4>{applications.filter(a=>!["approved","declined","withdrawn"].includes(a.status)).length?applications.filter(a=>!["approved","declined","withdrawn"].includes(a.status)).map(a=><div key={a.id} style={{borderTop:"1px solid #e1e5ea",padding:"7px 0"}}><strong>{name(a.student_character_id)} • {acts.get(a.activity_id)?.name??"Organization"}</strong><p style={{fontSize:9}}>{a.statement}</p><textarea value={responses[a.id]??""} onChange={e=>setResponses(v=>({...v,[a.id]:e.target.value}))} placeholder="Staff response" rows={2} style={{width:"100%"}}/><div style={{display:"flex",gap:5,flexWrap:"wrap"}}><button disabled={busy} onClick={()=>void reviewApplication(a,"under_review")}>Mark reviewing</button><button disabled={busy} onClick={()=>void reviewApplication(a,"approved")}>Approve</button><button disabled={busy} onClick={()=>void reviewApplication(a,"declined")}>Decline</button></div></div>):<p>No organization applications await action.</p>}</article>
 </div></section>;
}
