"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminDraftWorkspace.module.css";
const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type Draft={id:string;draft_type:string;title:string;content:Record<string,unknown>;status:string;scheduled_for:string|null;created_at:string;updated_at:string};
function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}function pretty(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}async function rpc<T>(token:string,name:string,body:Record<string,unknown>={}){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:"POST",headers:h(token,{"Content-Type":"application/json"}),body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return await r.json() as T;}
export default function AdminDraftWorkspace({accessToken}:Props){const [rows,setRows]=useState<Draft[]>([]),[status,setStatus]=useState("Loading drafts…"),[saving,setSaving]=useState(false),[form,setForm]=useState({draft_type:"announcement",title:"",body:"",scheduled_for:""});
 const load=useCallback(async()=>{try{let released=0;try{released=await rpc<number>(accessToken,"admin_publish_due_content_drafts");}catch{}const r=await fetch(`${U}/rest/v1/admin_content_drafts?select=id,draft_type,title,content,status,scheduled_for,created_at,updated_at&order=updated_at.desc`,{headers:h(accessToken)});if(!r.ok)throw new Error("Draft workspace could not be loaded.");const data=await r.json() as Draft[];setRows(data);setStatus(released?`${released} scheduled item${released===1?"":"s"} published • ${data.length} drafts in workspace.`:`${data.length} draft${data.length===1?"":"s"} in the workspace.`);}catch(e){setStatus(e instanceof Error?e.message:"Draft workspace unavailable.");}},[accessToken]);useEffect(()=>{void load()},[load]);
 async function create(event:FormEvent){event.preventDefault();if(!form.title.trim())return;setSaving(true);try{const r=await fetch(`${U}/rest/v1/admin_content_drafts`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({draft_type:form.draft_type,title:form.title.trim(),content:{body:form.body.trim()},status:"draft",scheduled_for:form.scheduled_for?new Date(form.scheduled_for).toISOString():null})});if(!r.ok)throw new Error("Draft could not be saved.");setForm({draft_type:"announcement",title:"",body:"",scheduled_for:""});await load();setStatus("Draft saved. Mark it Ready to release automatically when its scheduled target is due.");}catch(e){setStatus(e instanceof Error?e.message:"Draft could not be saved.");}finally{setSaving(false)}}
 async function update(id:string,next:string){setSaving(true);try{const r=await fetch(`${U}/rest/v1/admin_content_drafts?id=eq.${id}`,{method:"PATCH",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Draft status could not be updated.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Draft status could not be updated.");}finally{setSaving(false)}}
 async function publish(item:Draft){setSaving(true);try{await rpc<string>(accessToken,"admin_publish_content_draft",{target_draft_id:item.id,force_publish:true});await load();setStatus(`${item.title} was published into its live Hanami system.`);}catch(e){setStatus(e instanceof Error?e.message:"Draft could not be published.");}finally{setSaving(false)}}
 async function runDue(){setSaving(true);try{const count=await rpc<number>(accessToken,"admin_publish_due_content_drafts");await load();setStatus(count?`${count} due scheduled item${count===1?"":"s"} published.`:"No scheduled drafts are due yet.");}catch(e){setStatus(e instanceof Error?e.message:"Scheduled publishing check failed.");}finally{setSaving(false)}}
 const publishable=(type:string)=>["announcement","event","newspaper","roleplay_prompt"].includes(type);
 return <section className={styles.panel}><header><div><p className="eyebrow">ADMIN DRAFT WORKSPACE</p><h3>Unpublished & scheduled school content</h3></div><div><span>{status}</span><button type="button" disabled={saving} onClick={()=>void runDue()}>Run due schedules</button></div></header><div className={styles.layout}><form onSubmit={create}><label>Draft type<select value={form.draft_type} onChange={e=>setForm({...form,draft_type:e.target.value})}><option value="announcement">Announcement</option><option value="event">Event</option><option value="newspaper">Newspaper</option><option value="roleplay_prompt">RP prompt</option><option value="policy">Policy update</option><option value="school_state">School state note</option></select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Working copy<textarea rows={8} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Keep unfinished content here before publishing it through the final tool."/></label><label>Optional scheduled target<input type="datetime-local" value={form.scheduled_for} onChange={e=>setForm({...form,scheduled_for:e.target.value})}/></label><button disabled={saving}>Save draft</button><small>Announcements, events, newspaper stories, and RP prompts can publish directly from this workspace. Policy and school-state notes stay in their dedicated tools.</small></form><div className={styles.list}>{rows.map(item=><article key={item.id}><div><small>{pretty(item.draft_type)} · {pretty(item.status)} · updated {new Date(item.updated_at).toLocaleString()}</small><h4>{item.title}</h4><p>{String(item.content?.body??"No working copy yet.")}</p>{item.scheduled_for&&<b>Target: {new Date(item.scheduled_for).toLocaleString()}</b>}</div><div><button disabled={saving} onClick={()=>update(item.id,"draft")}>Draft</button><button disabled={saving} onClick={()=>update(item.id,"ready")}>{item.scheduled_for?"Ready / Schedule":"Ready"}</button>{publishable(item.draft_type)&&item.status!=="published"&&<button disabled={saving} onClick={()=>void publish(item)}>Publish now</button>}<button disabled={saving} onClick={()=>update(item.id,"archived")}>Archive</button></div></article>)}{!rows.length&&<p className={styles.empty}>No unfinished content is waiting here.</p>}</div></div></section>}
