"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Metric={metric:string;value:number};
export default function AdminStaffAnalyticsPanel({accessToken}:{accessToken:string}){const [rows,setRows]=useState<Metric[]>([]);const [notice,setNotice]=useState("Loading aggregate school analytics…");const load=useCallback(async()=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/staff_analytics_summary`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:"{}"});if(r.ok){setRows(await r.json());setNotice("Aggregate analytics updated.");}else setNotice("Analytics could not be loaded for this staff role.");},[accessToken]);useEffect(()=>{void load();},[load]);const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());return <section style={{marginTop:18,border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:12,background:"#eef3f8",borderBottom:"1px solid #c5ced8",display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><div><p className="eyebrow">STAFF ANALYTICS</p><h3 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Aggregate School Activity</h3><small>{notice}</small></div><button type="button" onClick={()=>void load()}>Refresh</button></div><div style={{padding:12,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}>{rows.map(row=><article key={row.metric} style={{padding:10,border:"1px solid #d3dae1"}}><small>{label(row.metric)}</small><strong style={{display:"block",fontSize:20}}>{row.value}</strong></article>)}</div><p style={{padding:"0 12px 12px",fontSize:9,color:"#667789"}}>Aggregate only: no private message contents, browsing histories, profile-view identities, or per-user behavior reports are collected for this dashboard.</p></section>;}
