"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminClassDayChangesPanel.module.css";
const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};type Section={id:string;section_code:string;room:string|null;academic_courses:{title:string}|null};type Faculty={id:string;display_name:string};type Change={id:string;section_id:string;roleplay_date:string;change_type:string;replacement_room:string|null;substitute_character_id:string|null;note:string;created_at:string};
function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}function pretty(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
export default function AdminClassDayChangesPanel({accessToken}:Props){const [sections,setSections]=useState<Section[]>([]),[faculty,setFaculty]=useState<Faculty[]>([]),[changes,setChanges]=useState<Change[]>([]),[msg,setMsg]=useState("Loading day changes…"),[saving,setSaving]=useState(false),[form,setForm]=useState({section_id:"",roleplay_date:"2006-04-07",change_type:"room_change",replacement_room:"",substitute_character_id:"",note:""});
 const load=useCallback(async()=>{try{const [s,f,c]=await Promise.all([fetch(`${U}/rest/v1/class_sections?select=id,section_code,room,academic_courses(title)&order=section_code.asc`,{headers:h(accessToken)}),fetch(`${U}/rest/v1/characters?select=id,display_name&role=eq.faculty&order=display_name.asc`,{headers:h(accessToken)}),fetch(`${U}/rest/v1/class_day_changes?select=id,section_id,roleplay_date,change_type,replacement_room,substitute_character_id,note,created_at&order=roleplay_date.desc,created_at.desc&limit=80`,{headers:h(accessToken)})]);if(!s.ok||!f.ok||!c.ok)throw new Error("Class day changes could not be loaded.");const ss=await s.json() as Section[];setSections(ss);setFaculty(await f.json());setChanges(await c.json());setForm(x=>({...x,section_id:x.section_id||ss[0]?.id||""}));setMsg("Class day changes are ready.");}catch(e){setMsg(e instanceof Error?e.message:"Class day changes unavailable.");}},[accessToken]);useEffect(()=>{void load()},[load]);
 async function save(event:FormEvent){event.preventDefault();if(!form.section_id)return;setSaving(true);try{const body={section_id:form.section_id,roleplay_date:form.roleplay_date,change_type:form.change_type,replacement_room:form.change_type==="room_change"?form.replacement_room.trim()||null:null,substitute_character_id:form.change_type==="substitute"?form.substitute_character_id||null:null,note:form.note.trim(),updated_at:new Date().toISOString()};const r=await fetch(`${U}/rest/v1/class_day_changes?on_conflict=section_id,roleplay_date,change_type`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify(body)});if(!r.ok)throw new Error("Class change could not be saved.");setForm(x=>({...x,replacement_room:"",substitute_character_id:"",note:""}));await load();setMsg("Class-day notice saved and visible to enrolled students.");}catch(e){setMsg(e instanceof Error?e.message:"Class-day notice could not be saved.");}finally{setSaving(false)}}
 async function remove(id:string){setSaving(true);try{const r=await fetch(`${U}/rest/v1/class_day_changes?id=eq.${id}`,{method:"DELETE",headers:h(accessToken)});if(!r.ok)throw new Error("Change could not be removed.");await load();}finally{setSaving(false)}}
 const sectionName=(id:string)=>{const s=sections.find(x=>x.id===id);return s?`${s.academic_courses?.title??"Class"} · ${s.section_code}`:"Class"};const facultyName=(id:string|null)=>faculty.find(x=>x.id===id)?.display_name??"Unassigned substitute";
 return <section className={styles.panel}><header><div><p className="eyebrow">CLASSROOM DAY OPERATIONS</p><h3>Room changes & substitute mode</h3></div><span>{msg}</span></header><div className={styles.layout}><form onSubmit={save}><label>Class<select value={form.section_id} onChange={e=>setForm({...form,section_id:e.target.value})}>{sections.map(s=><option key={s.id} value={s.id}>{s.academic_courses?.title??"Class"} · {s.section_code}</option>)}</select></label><label>RP date<input type="date" value={form.roleplay_date} onChange={e=>setForm({...form,roleplay_date:e.target.value})}/></label><label>Change type<select value={form.change_type} onChange={e=>setForm({...form,change_type:e.target.value})}><option value="room_change">Room change</option><option value="substitute">Substitute teacher</option><option value="cancelled">Class cancelled</option><option value="special_instructions">Special instructions</option></select></label>{form.change_type==="room_change"&&<label>Replacement room<input value={form.replacement_room} onChange={e=>setForm({...form,replacement_room:e.target.value})} placeholder="e.g. 2-B"/></label>}{form.change_type==="substitute"&&<label>Substitute<select value={form.substitute_character_id} onChange={e=>setForm({...form,substitute_character_id:e.target.value})}><option value="">Choose faculty member…</option>{faculty.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label>}<label>Notice / instructions<textarea rows={5} value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="What should students know today?"/></label><button disabled={saving}>Save day change</button></form><div className={styles.list}>{changes.map(x=><article key={x.id}><div><small>{x.roleplay_date} · {pretty(x.change_type)}</small><h4>{sectionName(x.section_id)}</h4>{x.replacement_room&&<b>Room → {x.replacement_room}</b>}{x.substitute_character_id&&<b>Substitute → {facultyName(x.substitute_character_id)}</b>}<p>{x.note||"No additional instructions."}</p></div><button disabled={saving} onClick={()=>remove(x.id)}>Remove</button></article>)}{!changes.length&&<p>No special class-day changes are scheduled.</p>}</div></div></section>}
