"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import styles from "./AdminDraftWorkspace.module.css";
const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Props={accessToken:string};
type Draft={id:string;draft_type:string;title:string;content:Record<string,unknown>;status:string;scheduled_for:string|null;created_at:string;updated_at:string};
function h(t:string,e:Record<string,string>={}){return{apikey:K,Authorization:`Bearer ${t}`,...e}}function pretty(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
export default function AdminDraftWorkspace({accessToken}:Props){const [rows,setRows]=useState<Draft[]>([]),[status,setStatus]=useState("Loading drafts…"),[saving,setSaving]=useState(false),[form,setForm]=useState({draft_type:"announcement",title:"",body:"",scheduled_for:""});
 const load=useCallback(async()=>{try{const r=await fetch(`${U}/rest/v1/admin_content_drafts?select=id,draft_type,title,content,status,scheduled_for,created_at,updated_at&order=updated_at.desc`,{headers:h(accessToken)});if(!r.ok)throw new Error("Draft workspace could not be loaded.");const data=await r.json() as Draft[];setRows(data);setStatus(`${data.length} draft${data.length===1?"":"s"} in the workspace.`);}catch(e){setStatus(e instanceof Error?e.message:"Draft workspace unavailable.");}},[accessToken]);useEffect(()=>{void load()},[load]);
 async function create(event:FormEvent){event.preventDefault();if(!form.title.trim())return;setSaving(true);try{const r=await fetch(`${U}/rest/v1/admin_content_drafts`,{method:"POST",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({draft_type:form.draft_type,title:form.title.trim(),content:{body:form.body.trim()},status:"draft",scheduled_for:form.scheduled_for?new Date(form.scheduled_for).toISOString():null})});if(!r.ok)throw new Error("Draft could not be saved.");setForm({draft_type:"announcement",title:"",body:"",scheduled_for:""});await load();setStatus("Draft saved.");}catch(e){setStatus(e instanceof Error?e.message:"Draft could not be saved.");}finally{setSaving(false)}}
 async function update(id:string,next:string){setSaving(true);try{const r=await fetch(`${U}/rest/v1/admin_content_drafts?id=eq.${id}`,{method:"PATCH",headers:h(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:next,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Draft status could not be updated.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Draft status could not be updated.");}finally{setSaving(false)}}
 return <section className={styles.panel}><header><div><p className="eyebrow">ADMIN DRAFT WORKSPACE</p><h3>Unpublished school content</h3></div><span>{status}</span></header><div className={styles.layout}><form onSubmit={create}><label>Draft type<select value={form.draft_type} onChange={e=>setForm({...form,draft_type:e.target.value})}><option value="announcement">Announcement</option><option value="event">Event</option><option value="newspaper">Newspaper</option><option value="roleplay_prompt">RP prompt</option><option value="policy">Policy update</option><option value="school_state">School state note</option></select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Working copy<textarea rows={8} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Keep unfinished content here before publishing it through the final tool."/></label><label>Optional scheduled target<input type="datetime-local" value={form.scheduled_for} onChange={e=>setForm({...form,scheduled_for:e.target.value})}/></label><button disabled={saving}>Save draft</button></form><div className={styles.list}>{rows.map(item=><article key={item.id}><div><small>{pretty(item.draft_type)} · {pretty(item.status)} · updated {new Date(item.updated_at).toLocaleString()}</small><h4>{item.title}</h4><p>{String(item.content?.body??"No working copy yet.")}</p>{item.scheduled_for&&<b>Target: {new Date(item.scheduled_for).toLocaleString()}</b>}</div><div><button disabled={saving} onClick={()=>update(item.id,"draft")}>Draft</button><button disabled={saving} onClick={()=>update(item.id,"ready")}>Ready</button><button disabled={saving} onClick={()=>update(item.id,"published")}>Published</button><button disabled={saving} onClick={()=>update(item.id,"archived")}>Archive</button></div></article>)}{!rows.length&&<p className={styles.empty}>No unfinished content is waiting here.</p>}</div></div></section>}
