"use client";

import {useCallback,useEffect,useState} from "react";
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Row={id:string;label:string;is_active:boolean;table:string};
export default function AdminCityLifecyclePanel({accessToken}:{accessToken:string}){
 const [rows,setRows]=useState<Row[]>([]);const [notice,setNotice]=useState("Loading Hanami City lifecycle controls…");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [lines,services,routes,hoods]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/city_transit_lines?select=id,code,name,is_active&order=display_order`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/city_transit_services?select=id,service_name,is_active&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/city_commute_routes?select=id,title,is_active&order=created_at.desc`,{headers:headers(accessToken)}),
  fetch(`${SUPABASE_URL}/rest/v1/city_neighborhoods?select=id,name,is_active&order=name`,{headers:headers(accessToken)})
 ]);const all:Row[]=[];if(lines.ok)all.push(...(await lines.json() as Array<{id:string;code:string;name:string;is_active:boolean}>).map(x=>({id:x.id,label:`${x.code} · ${x.name}`,is_active:x.is_active,table:"city_transit_lines"})));if(services.ok)all.push(...(await services.json() as Array<{id:string;service_name:string;is_active:boolean}>).map(x=>({id:x.id,label:x.service_name,is_active:x.is_active,table:"city_transit_services"})));if(routes.ok)all.push(...(await routes.json() as Array<{id:string;title:string;is_active:boolean}>).map(x=>({id:x.id,label:x.title,is_active:x.is_active,table:"city_commute_routes"})));if(hoods.ok)all.push(...(await hoods.json() as Array<{id:string;name:string;is_active:boolean}>).map(x=>({id:x.id,label:x.name,is_active:x.is_active,table:"city_neighborhoods"})));setRows(all);setNotice("Hanami City lifecycle controls ready.");}catch(error){setNotice(error instanceof Error?error.message:"City lifecycle controls could not be loaded.");}},[accessToken]);
 useEffect(()=>{void load();},[load]);
 async function toggle(row:Row){setBusy(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/${row.table}?id=eq.${row.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({is_active:!row.is_active})});if(!response.ok)throw new Error("Visibility could not be changed.");setNotice(`${row.label} is now ${row.is_active?"hidden":"active"}.`);await load();}catch(error){setNotice(error instanceof Error?error.message:"Visibility could not be changed.");}finally{setBusy(false);}}
 const title=(table:string)=>table==="city_transit_lines"?"Transit Lines":table==="city_transit_services"?"Schedules":table==="city_commute_routes"?"Commute Routes":"Neighborhoods";
 return <section style={{margin:"16px 0",border:"1px solid #9eacbb",background:"#f4f7fa",padding:14}} aria-label="Hanami City lifecycle"><p className="eyebrow">HANAMI CITY LIFECYCLE</p><h3 style={{margin:"4px 0",font:"400 24px Georgia,serif"}}>Publish / Hide City Content</h3><small>{notice}</small><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12,marginTop:12}}>{["city_transit_lines","city_transit_services","city_commute_routes","city_neighborhoods"].map(table=><article key={table} style={{border:"1px solid #cad2dc",background:"#fff",padding:10}}><h4>{title(table)}</h4>{rows.filter(r=>r.table===table).length?rows.filter(r=>r.table===table).map(row=><div key={row.id} style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center",borderTop:"1px solid #e5e9ed",padding:"7px 0"}}><span><strong>{row.label}</strong><small style={{display:"block"}}>{row.is_active?"Published":"Hidden"}</small></span><button type="button" disabled={busy} onClick={()=>void toggle(row)}>{row.is_active?"Hide":"Publish"}</button></div>):<p>No entries yet.</p>}</article>)}</div></section>;
}
