"use client";

import {useCallback,useEffect,useState} from "react";
import styles from "./AdminCourseRegistrationManager.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type Request={id:string;student_character_id:string;section_id:string;note:string;status:string;faculty_note:string;admin_note:string;created_at:string};type Section={id:string;course_id:string;section_code:string;term:string;capacity:number};type Course={id:string;code:string;title:string};type Character={id:string;display_name:string;handle:string};
export default function AdminCourseRegistrationManager({accessToken}:{accessToken:string}){const [requests,setRequests]=useState<Request[]>([]);const [sections,setSections]=useState<Section[]>([]);const [courses,setCourses]=useState<Course[]>([]);const [characters,setCharacters]=useState<Character[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [notice,setNotice]=useState("Loading course registration requests…");const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const [r,s,c,ch]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?select=id,student_character_id,section_id,note,status,faculty_note,admin_note,created_at&order=created_at.asc`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,course_id,section_code,term,capacity`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/academic_courses?select=id,code,title`,{headers:headers(accessToken)}),fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&role=eq.student`,{headers:headers(accessToken)})]);if(r.ok){const rows=await r.json() as Request[];setRequests(rows);setNotes(Object.fromEntries(rows.map(x=>[x.id,x.admin_note??""])));}if(s.ok)setSections(await s.json());if(c.ok)setCourses(await c.json());if(ch.ok)setCharacters(await ch.json());setNotice("Course registration queue ready.");},[accessToken]);useEffect(()=>{const task=setTimeout(()=>{void load();},0);return()=>clearTimeout(task);},[load]);
 const label=(item:Request)=>{const student=characters.find(x=>x.id===item.student_character_id);const sec=sections.find(x=>x.id===item.section_id);const course=sec?courses.find(x=>x.id===sec.course_id):null;return {student:student?`${student.display_name} (@${student.handle})`:item.student_character_id.slice(0,8),course:course?`${course.code} • ${course.title}`:"Course section",section:sec?`${sec.term} • ${sec.section_code} • cap ${sec.capacity}`:"Unknown section"};};
 async function finalize(item:Request){setSaving(true);try{const noteResponse=await fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({admin_note:notes[item.id]??"",status:"admin_review",updated_at:new Date().toISOString()})});if(!noteResponse.ok)throw new Error("Admin review note could not be saved.");const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/finalize_course_registration`,{method:"POST",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({target_request_id:item.id})});if(!response.ok)throw new Error("Registration could not be finalized.");const result=String(await response.json());await load();setNotice(result==="enrolled"?"Student enrolled into the class.":"Class was full, so the Student was placed on the waitlist.");}catch(error){setNotice(error instanceof Error?error.message:"Registration could not be finalized.");}finally{setSaving(false);}}
 async function deny(item:Request){setSaving(true);try{const response=await fetch(`${SUPABASE_URL}/rest/v1/course_registration_requests?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status:"denied",admin_note:notes[item.id]??"",admin_reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error("Registration denial could not be saved.");await load();setNotice("Course request denied.");}catch(error){setNotice(error instanceof Error?error.message:"Registration denial could not be saved.");}finally{setSaving(false);}}
 const pending=requests.filter(x=>!["enrolled","waitlisted","denied","withdrawn"].includes(x.status));return <section className={styles.panel}><div className={styles.heading}><div><p className="eyebrow">ACADEMIC OPERATIONS</p><h3>Course Registration Queue</h3></div><span>{pending.length} PENDING</span></div><div className={styles.notice}>{notice}</div><div className={styles.list}>{pending.length?pending.map(item=>{const info=label(item);return <article key={item.id}><strong>{info.student}</strong><span>{info.course} • {info.section} • {item.status.replaceAll("_"," ")}</span>{item.note&&<p><b>Student:</b> {item.note}</p>}{item.faculty_note&&<p><b>Faculty:</b> {item.faculty_note}</p>}<textarea value={notes[item.id]??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Administration scheduling note"/><div><button disabled={saving} onClick={()=>finalize(item)}>Finalize registration</button><button disabled={saving} onClick={()=>deny(item)}>Deny</button></div></article>}):<p>No course registration requests are waiting for Administration.</p>}</div></section>}
