"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
function headers(token:string,extra:Record<string,string>={}){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,...extra};}
type QueueItem={id:string;content_type:string;source_id:string|null;submitted_by_character_id:string|null;title:string;summary:string;payload:Record<string,unknown>;status:string;reviewer_note:string;submitted_at:string};
export default function AdminContentApprovalPanel({accessToken}:{accessToken:string}){const [rows,setRows]=useState<QueueItem[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [notice,setNotice]=useState("Loading moderation queue…");const load=useCallback(async()=>{const r=await fetch(`${SUPABASE_URL}/rest/v1/content_approval_queue?select=id,content_type,source_id,submitted_by_character_id,title,summary,payload,status,reviewer_note,submitted_at&status=in.(pending,changes_requested)&order=submitted_at.asc`,{headers:headers(accessToken)});if(r.ok){setRows(await r.json());setNotice("Unified content approval queue ready.");}else setNotice("Approval queue could not be loaded.");},[accessToken]);useEffect(()=>{void load();},[load]);async function review(item:QueueItem,status:"approved"|"changes_requested"|"rejected"){const r=await fetch(`${SUPABASE_URL}/rest/v1/content_approval_queue?id=eq.${item.id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify({status,reviewer_note:notes[item.id]?.trim()??"",reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(r.ok){if(item.content_type==="rumor"&&item.source_id){await fetch(`${SUPABASE_URL}/rest/v1/school_rumors?id=eq.${item.source_id}`,{method:"PATCH",headers:headers(accessToken,{"Content-Type":"application/json"}),body:JSON.stringify(status==="approved"?{status:"published",approved_at:new Date().toISOString(),published_at:new Date().toISOString()}:{status:status==="rejected"?"rejected":"pending"})});}setNotice(`Content ${status.replaceAll("_"," ")}.`);await load();}else setNotice("Review decision could not be saved.");}
 return <section style={{marginTop:18,border:"1px solid #aab7c6",background:"#fff"}}><div style={{padding:12,background:"#eef3f8",borderBottom:"1px solid #c5ced8"}}><p className="eyebrow">CONTENT MODERATION</p><h3 style={{margin:"3px 0",font:"400 21px Georgia,serif"}}>Unified Approval Queue</h3><small>{notice}</small></div><div style={{padding:12,display:"grid",gap:8}}>{rows.length?rows.map(item=><article key={item.id} style={{padding:10,border:"1px solid #d2d9e0"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><strong>{item.title||item.content_type.replaceAll("_"," ")}</strong><span style={{fontSize:8}}>{item.content_type.replaceAll("_"," ").toUpperCase()} • {new Date(item.submitted_at).toLocaleString()}</span></div><p style={{fontSize:9}}>{item.summary||"No summary supplied."}</p><textarea value={notes[item.id]??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Reviewer note / requested changes" style={{width:"100%",minHeight:55,boxSizing:"border-box"}}/><div style={{display:"flex",gap:6,marginTop:6,flexWrap:"wrap"}}><button type="button" onClick={()=>review(item,"approved")}>Approve</button><button type="button" onClick={()=>review(item,"changes_requested")}>Request changes</button><button type="button" onClick={()=>review(item,"rejected")}>Reject</button></div></article>):<p>No content is waiting for review.</p>}</div><div style={{padding:"0 12px 12px",fontSize:9,color:"#687789"}}>Queue supports newspaper posts, guestbook comments, gallery uploads, rumors, profile templates, organization announcements, and future moderated content types.</div></section>;}
