"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./Guide.module.css";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";

type Role="all"|"public"|"student"|"faculty"|"admin"|"owner";
type Entry={id:string;title:string;roles:Role[];summary:string;steps:string[];tips?:string[]};
type AdminAccess={site_admin:boolean;content_editor:boolean;moderator:boolean};
type RoleSync={administrator:boolean;owner:boolean};
type StoredSession={accessToken?:string};

const PUBLIC_ENTRIES:Entry[]=[
 {id:"getting-started",title:"Getting Started",roles:["all","public","student","faculty"],summary:"How Hanami High is organized and what to do first.",steps:["Use the public website to explore school information, rules, academics, events, organizations, news, and applications.","Use Portal Login when you need a character-specific Student or Faculty portal.","The website uses Hanami roleplay time. The current day changes with real time while the school year remains in the 2006 roleplay timeline.","If a page looks outdated after an update, hard refresh the page before reporting a bug."],tips:["The public website and portal are separate experiences.","Your active character controls which student/faculty data you see."]},
 {id:"public-site",title:"Public Website",roles:["all","public"],summary:"Everything available before signing in.",steps:["Home shows school status, announcements, current roleplay date, featured content, news, and upcoming events.","Academics explains courses and academic pathways.","Campus Life covers clubs, activities, opportunities, volunteering, and school-life systems.","Calendar shows school events and important dates.","Organizations lists clubs and other student groups.","Newspaper opens The Hanami Chronicle.","Rooms, traditions, sports, elections, lore, rules, and updates provide deeper school information.","Apply directs prospective members into the enrollment/join flow."],tips:["Use the left navigation rail on the homepage for the fastest way around the site."]},
 {id:"accounts",title:"Accounts, Characters & Login",roles:["student","faculty"],summary:"How login, characters, and portal sessions work.",steps:["Sign in through the Portal Gateway.","Choose a character when entering a Student or Faculty portal.","The selected character stays active until you switch characters or log out.","Character deletion is permanent; use it only when you intend to remove that character and its linked roleplay data."],tips:["Only use the portal that matches the role of your selected character."]},
 {id:"student-home",title:"Student Portal Dashboard",roles:["student"],summary:"Your main school workspace.",steps:["Home summarizes the school day, current classes, announcements, assignments, events, and school-life information.","Use the navigation rail to move between Dashboard, Courses, Calendar, Inbox, Groups, Account, and other available student tools.","Dashboard layout controls allow you to reorder or hide supported widgets.","Appearance settings let you change your personal portal colors, wallpaper, profile image, and class banners."],tips:["Personal portal customization does not alter another user’s portal."]},
 {id:"classes",title:"Classes, Assignments & Grades",roles:["student","faculty"],summary:"How classroom pages work.",steps:["Students open a class card to enter the class page.","Class pages show course information, instructor, meeting schedule, assignments, submission status, grades, feedback, attendance, and late policies.","Students submit work through assignment tools when submission is enabled.","Faculty create and manage assignments, grading, comments, attendance, and classroom information from the Faculty portal."],tips:["Class access is enrollment-validated server-side."]},
 {id:"homeroom",title:"Homerooms & Schedules",roles:["student","faculty"],summary:"Homeroom life and weekly class schedules.",steps:["Students assigned to a homeroom see their class identity, adviser, classmates, bulletin board, events, rankings, and memories.","Homeroom placement automatically links students to the matching class sections.","Your weekly class schedule is generated from your assigned homeroom and its class timetable.","Faculty see the classes and schedule information connected to the sections they teach."],tips:["Schedule changes made by school staff appear automatically when published."]},
 {id:"social",title:"Social & Personalization",roles:["student"],summary:"Statuses, journals, relationships, guestbook, Q&A, feed, scrapbook, locker, and dashboard layout.",steps:["Status lets you set presence and a short status message.","Journal stores character diary entries with privacy settings.","Relationships tracks approved platonic relationship categories.","Guestbook lets you review messages left on your profile.","Q&A controls your anonymous question box and answers.","Friend Feed shows supported social activity.","Scrapbook stores school memories and uploaded images.","Locker Studio lets you decorate a personal locker with notes, photos, stickers, and keepsakes.","Dashboard Layout lets you reorder or hide available dashboard widgets."],tips:["Uploaded personal images use private Hanami storage instead of requiring image URLs."]},
 {id:"profile-studio",title:"Profile Studio",roles:["student","faculty"],summary:"The Canva-inspired profile editor.",steps:["Open the profile customization area and enter Profile Studio.","Use Canvas to place, resize, reorder, and edit widgets.","Use Templates to start from a prepared layout.","Use Decorations for presets, dividers, and visual extras.","Use Saved Designs to switch between saved profile layouts.","Use Studio Tools for advanced utilities.","Upload profile backgrounds and images directly from your device."],tips:["Reset Canvas permanently removes the current canvas layout, so use it carefully."]},
 {id:"appearance",title:"Portal Appearance & Themes",roles:["student","faculty"],summary:"How personal portal themes work.",steps:["Open Appearance/Customization.","Choose a quick theme or select your own text and accent colors.","Save colors to apply them to your portal shell.","Upload a dashboard wallpaper from your device and set its opacity.","Upload a profile image and class banner images from your device.","Your saved character theme should reload automatically on future visits."],tips:["The public website uses the Tokyo Slate + Burgundy school theme; personal portal themes remain independent."]},
 {id:"messages",title:"Messages & Communication",roles:["student","faculty"],summary:"How Hanami communication is handled.",steps:["Hanami messaging is handled inside the website rather than through real-world email.","Use Inbox/Message Center for supported direct or school communication.","Attachments use Hanami storage where enabled.","School announcements, PA broadcasts, notices, and newspaper posts are separate communication systems with different audiences."],tips:["Do not expect website messages to be delivered as external email."]},
 {id:"school-life",title:"School Life & Events",roles:["student","faculty"],summary:"Clubs, festivals, sports, student council, volunteering, and school activities.",steps:["PA/Broadcast displays school announcements and broadcasts.","Newspaper lets students apply to The Hanami Chronicle and read published work.","Club Recruitment shows active recruitment campaigns and applications.","Cultural Festival contains festival planning and participation systems.","Sports contains teams, fixtures, scores, and results.","Student Council handles elections, positions, candidacy, and nominations.","Events & Volunteer manages RSVPs and volunteer signups.","Festival Passport tracks festival participation and stamps."],tips:["Some actions require staff approval before they become active or public."]},
 {id:"faculty",title:"Faculty Portal",roles:["faculty"],summary:"Teaching, class management, and staff tools.",steps:["Open the Faculty portal using a faculty character.","Use Courses to reach assigned classes.","Create and manage assignments, assessment settings, late policies, attendance, grades, and feedback.","Use faculty-facing school information, announcements, schedules, and school-life tools as available.","Faculty permissions are limited to the classes and systems appropriate to their role."],tips:["If a class is missing, confirm that your faculty character is assigned as an instructor for that section."]},
 {id:"roleplay-time",title:"Roleplay Date, Time & School Year",roles:["all"],summary:"How the 2006 school timeline works.",steps:["The website follows real-world passage of time while presenting the roleplay school year in 2006.","Hanami City uses Japan Standard Time for school-facing date/time displays.","The roleplay clock affects school status, calendars, events, and date-sensitive systems."],tips:["A real-world date changing does not move the roleplay year out of 2006 unless the school timeline is intentionally changed."]},
 {id:"privacy",title:"Privacy, Moderation & Permissions",roles:["all"],summary:"Who can see and change what.",steps:["Most private portal data is protected by account ownership, character ownership, role, enrollment, or staff permission checks.","Profile, scrapbook, locker, journal, commute, relationship, and similar systems may include visibility controls.","Moderation and school-management tools are restricted to authorized staff.","Privileged actions are checked server-side.","Never share privileged credentials or account tokens."],tips:["If you can see a button but an action is denied, the server-side permission check takes priority."]},
 {id:"bugs",title:"Bugs, Updates & Troubleshooting",roles:["all"],summary:"What to do when something looks wrong.",steps:["Hard refresh after a deployment to clear stale browser assets.","Confirm you are signed into the correct account and active character.","If a portal section fails, note the exact page, action, and error message.","Use the website bug/feedback tools when available and include screenshots when helpful.","Check Updates/Changelog to see whether the behavior changed in a recent release."],tips:["Specific reproduction steps make bugs much easier to fix."]}
];

const ADMIN_ENTRY:Entry={id:"admin",title:"Administration Portal",roles:["admin"],summary:"School management tools for authorized administrators.",steps:["Dashboard provides school status, announcements, and operational summaries.","Classrooms manages the school’s academic structure, courses, homerooms, schedule changes, school blocks, exams, and related academic operations.","People manages directory, student overview, IDs, hall passes, narrative review, and moderation.","Content manages events, campus operations, drafts, opportunities, applications, approvals, roadmap content, and lore/canon.","Support manages office requests and support tickets.","Admin contains roleplay systems, continuity, roadmap operations, transit, city lifecycle, and community operations."],tips:["This section is only shown when the signed-in account has Administration access.","Available tools depend on site_admin, content_editor, and moderator permissions."]};
const OWNER_ENTRY:Entry={id:"owner",title:"Owner Portal",roles:["owner"],summary:"Full school oversight and Owner-only controls.",steps:["Owner access includes the school-management workspace plus Owner-only controls.","Use User Portal Viewer to inspect Student and Faculty portals without creating or switching to an OC.","Use Classrooms → Classroom Control Center to build each homeroom’s Monday–Friday timetable, compare homerooms, and resolve teacher or room conflicts before publishing.","Use Owner operations, system health, roleplay clock, governance, feedback, bug detection, Discord role sync, and administrator provisioning tools.","Owner can lock the privileged portal while keeping the normal Hanami account session active."],tips:["This section is only shown to the signed-in Owner account.","Owner tools are intentionally separated from normal student/faculty character workflows."]};

const BASE_ROLE_LABELS:Partial<Record<Role,string>>={all:"Everything",public:"Public Site",student:"Student",faculty:"Faculty"};
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}

export default function GuidePage(){
 const [query,setQuery]=useState("");const [role,setRole]=useState<Role>("all");
 const [canAdmin,setCanAdmin]=useState(false);const [canOwner,setCanOwner]=useState(false);
 useEffect(()=>{let cancelled=false;async function verify(){try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return;const stored=JSON.parse(raw) as StoredSession;const token=stored.accessToken;if(!token)return;const [adminResponse,ownerResponse,roleResponse]=await Promise.all([
   fetch(`${SUPABASE_URL}/rest/v1/rpc/current_account_admin_access`,{method:"POST",headers:headers(token),body:"{}"}),
   fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(token),body:"{}"}),
   fetch(`${SUPABASE_URL}/rest/v1/rpc/current_discord_role_sync`,{method:"POST",headers:headers(token),body:"{}"})
  ]);if(cancelled)return;let admin=false,owner=false;if(adminResponse.ok){const rows=await adminResponse.json() as AdminAccess[];const access=rows[0];admin=Boolean(access&&(access.site_admin||access.content_editor||access.moderator));}if(ownerResponse.ok)owner=Boolean(await ownerResponse.json());if(roleResponse.ok){const rows=await roleResponse.json() as RoleSync[];admin=admin||Boolean(rows[0]?.administrator)||Boolean(rows[0]?.owner);owner=owner||Boolean(rows[0]?.owner);}setCanAdmin(admin||owner);setCanOwner(owner);}catch{setCanAdmin(false);setCanOwner(false);}}void verify();return()=>{cancelled=true;};},[]);
 const entries=useMemo(()=>[...PUBLIC_ENTRIES,...(canAdmin?[ADMIN_ENTRY]:[]),...(canOwner?[OWNER_ENTRY]:[])],[canAdmin,canOwner]);
 const roleLabels=useMemo(()=>({...BASE_ROLE_LABELS,...(canAdmin?{admin:"Administration"}:{}),...(canOwner?{owner:"Owner"}:{})}) as Partial<Record<Role,string>>,[canAdmin,canOwner]);
 useEffect(()=>{if((role==="admin"&&!canAdmin)||(role==="owner"&&!canOwner))setRole("all");},[role,canAdmin,canOwner]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return entries.filter(entry=>(role==="all"||entry.roles.includes(role)||entry.roles.includes("all"))&&(!q||`${entry.title} ${entry.summary} ${entry.steps.join(" ")} ${(entry.tips??[]).join(" ")}`.toLowerCase().includes(q)));},[entries,query,role]);
 const roleKeys=(Object.keys(roleLabels) as Role[]).filter(key=>roleLabels[key]);
 return <main className={styles.page}><header className={styles.hero}><a className={styles.back} href="../">← Hanami High</a><p className={styles.eyebrow}>HANAMI HIGH • WEBSITE GUIDE</p><h1>How to use Hanami High</h1><p>This guide explains the public website, Student and Faculty portals, classroom tools, customization systems, school-life features, permissions, and troubleshooting. Privileged staff documentation appears only when the signed-in account has the matching role.</p></header><section className={styles.toolbar}><label>Search the guide<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search classes, locker, messages…"/></label><div className={styles.roles}>{roleKeys.map(key=><button key={key} type="button" className={role===key?styles.active:""} onClick={()=>setRole(key)}>{roleLabels[key]}</button>)}</div></section><div className={styles.layout}><aside className={styles.toc}><strong>GUIDE INDEX</strong>{visible.map(entry=><a key={entry.id} href={`#${entry.id}`}>{entry.title}</a>)}</aside><section className={styles.content}>{visible.length===0?<div className={styles.empty}>No guide sections match that search.</div>:visible.map((entry,index)=><article className={styles.card} id={entry.id} key={entry.id}><div className={styles.cardHeading}><span>{String(index+1).padStart(2,"0")}</span><div><h2>{entry.title}</h2><p>{entry.summary}</p></div></div><ol>{entry.steps.map(step=><li key={step}>{step}</li>)}</ol>{entry.tips?.length?<div className={styles.tips}><strong>Useful to know</strong>{entry.tips.map(tip=><p key={tip}>{tip}</p>)}</div>:null}</article>)}</section></div><footer className={styles.footer}><strong>HANAMI HIGH SCHOOL WEBSITE GUIDE</strong><span>Public, Student, and Faculty help is available to everyone. Privileged staff sections are role-gated.</span></footer></main>;
}
