import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RootApp } from './app/RootApp'
import { AccountSigninRecorder } from './components/AccountSigninRecorder'
import { MemberProfileNavigationBridge } from './components/MemberProfileNavigationBridge'
import { ProfileDraftPreviewLauncher } from './components/ProfileDraftPreviewLauncher'
import { ProfileStudioTools } from './components/ProfileStudioTools'
import { ProfileInteractiveLayer } from './components/ProfileInteractiveLayer'
import { InterfaceCustomizationLayer } from './components/InterfaceCustomizationLayer'
import { SocialIdentityLayer } from './components/SocialIdentityLayer'
import { ProfileScenePortal } from './components/ProfileScenePortal'
import { ProfileDesignCredits } from './components/ProfileDesignCredits'
import { AnimationPresetLayer } from './components/AnimationPresetLayer'
import { UserTagDesignerPortal } from './components/UserTagDesignerPortal'
import { PremiumFontLayer } from './components/PremiumFontLayer'
import { PremiumFontStudioPortal } from './components/PremiumFontStudioPortal'
import { IdentityProvider } from './state/IdentityContext'
import './styles/tokens.css'
import './styles/global.css'
import './styles/hanami-floral-theme.css'
import './styles/home-floral.css'
import './styles/home-earlyweb-live.css'
import './styles/identity.css'
import './styles/character-deletion.css'
import './styles/enrollment.css'
import './styles/orientation.css'
import './styles/shell.css'
import './styles/profile-studio.css'
import './styles/profile-studio-enhancements.css'
import './styles/discord-profile.css'
import './styles/hanami-profile.css'
import './styles/profile-display-styles.css'
import './styles/profile-studio-tools.css'
import './styles/profile-background-editor.css'
import './styles/profile-spacehey-layouts.css'
import './styles/profile-draft-preview.css'
import './styles/profile-public-blog.css'
import './styles/spacehey-profile-contact.css'
import './styles/saved-themes.css'
import './styles/personal-spaces.css'
import './styles/profile-interactive-layer.css'
import './styles/profile-scenes.css'
import './styles/profile-design-credits.css'
import './styles/animation-presets.css'
import './styles/friends.css'
import './styles/top-friends.css'
import './styles/social-posts.css'
import './styles/social-interactions.css'
import './styles/guestbook.css'
import './styles/guestbook-activity.css'
import './styles/messages.css'
import './styles/member-profile-popover.css'
import './styles/discord-profile-interactions.css'
import './styles/academics.css'
import './styles/campus.css'
import './styles/utilities.css'
import './styles/rewards.css'
import './styles/boutique-animated-collections.css'
import './styles/boutique-ownership.css'
import './styles/hanami-plus-hub.css'
import './styles/creator-marketplace.css'
import './styles/creator-portfolios.css'
import './styles/creator-following.css'
import './styles/theme-remix-lab.css'
import './styles/widget-kit-library.css'
import './styles/installed-component-management.css'
import './styles/interface-customization.css'
import './styles/social-identity-studio.css'
import './styles/settings.css'
import './styles/account-lockscreen.css'
import './styles/owner-operations.css'
import './styles/school-administration.css'
import './styles/access-modes.css'
import './styles/early-web-site.css'
import './styles/shell-mode-boundary.css'
import './styles/messages-discord.css'
import './styles/academic-rooms.css'
import './styles/communication-shell.css'
import './styles/v2-reference-polish.css'
import './styles/home-proportions-wide.css'
import './styles/interface-boutique-repair.css'
import './styles/v2-layout-system.css'
import './styles/boutique-v3.css'
import './styles/theme-builder-v2.css'
import './styles/v2-page-proportions.css'
import './styles/user-tag-designer.css'
import './styles/mini-profile-reference.css'
import './styles/messages-stacked-chat.css'
import './styles/premium-font-studio.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <IdentityProvider>
      <AccountSigninRecorder />
      <PremiumFontLayer />
      <RootApp />
      <MemberProfileNavigationBridge />
      <ProfileStudioTools />
      <ProfileInteractiveLayer />
      <InterfaceCustomizationLayer />
      <SocialIdentityLayer />
      <ProfileScenePortal />
      <ProfileDesignCredits />
      <AnimationPresetLayer />
      <ProfileDraftPreviewLauncher />
      <UserTagDesignerPortal />
      <PremiumFontStudioPortal />
    </IdentityProvider>
  </StrictMode>,
)
