-- Keep the School Blocks manager focused on canonical school-wide, non-class schedule entries.
-- Homeroom-specific rows generated by the Weekly Homeroom Scheduler remain separate.

delete from public.school_schedule_blocks
where notes is distinct from 'owner_homeroom_daily_schedule';

insert into public.school_schedule_blocks
  (block_type,title,weekday,starts_at,ends_at,homeroom_label,notes,sort_order)
select
  v.block_type,
  v.title,
  d.weekday,
  v.starts_at::time,
  v.ends_at::time,
  'All Homerooms',
  v.notes,
  v.sort_order
from (values
  ('other','Arrival','08:30','08:35','Students arrive on campus and prepare for the school day.',1),
  ('other','Shoe Change','08:35','08:40','Students change into indoor school shoes at their lockers.',2),
  ('homeroom','Morning Homeroom (Asa-no-kai)','08:40','08:50','Roll call, announcements, and preparation for the school day.',3),
  ('lunch','Lunch','12:40','13:25','Lunch period.',20),
  ('other','Soji (Cleaning)','15:15','15:35','Students clean their classroom and assigned school areas.',40),
  ('closing_advisory','Afternoon Homeroom (Kaeri-no-kai)','15:35','15:50','Closing announcements, reminders, and dismissal preparation.',41),
  ('club','Bukatsu (Clubs / Extracurriculars)','16:00','18:30','Official after-school club and extracurricular activity window.',50)
) as v(block_type,title,starts_at,ends_at,notes,sort_order)
cross join (values (1::smallint),(2::smallint),(3::smallint),(4::smallint),(5::smallint)) d(weekday);
