begin;
delete from public.assignment_submissions;
delete from public.course_assignments;
delete from public.attendance_records;
delete from public.attendance_excuses;
delete from public.classroom_seating_assignments;
delete from public.course_registration_requests;
delete from public.exam_assignments;
delete from public.section_grade_categories;
delete from public.section_meetings;
delete from public.section_memberships;
delete from public.section_waitlist_entries;
delete from public.student_report_cards;
delete from public.substitute_teacher_assignments;
delete from public.class_competition_points;
delete from public.class_competitions;
delete from public.student_honors;
delete from public.homeroom_events;
delete from public.homeroom_memberships;
delete from public.homeroom_notices;
delete from public.homeroom_representatives;
delete from public.homerooms;
delete from public.faculty_lesson_plans;
delete from public.faculty_schedule_swap_requests;
delete from public.faculty_substitute_requests;
delete from public.site_announcements where target_section_id is not null;
update public.study_groups set course_id=null where course_id is not null;
delete from public.class_sections;
delete from public.academic_courses;
update public.exam_week_config set enabled=false,starts_on=null,ends_on=null,announcement='',updated_at=now() where key='current';
delete from public.test_bot_faculty_section_assignments;
delete from public.test_bot_faculty;
delete from public.characters where lower(display_name) like '%[test]%' or lower(handle) like 'testfaculty%' or lower(display_name) like '%test bot%' or lower(handle) like '%testbot%';
commit;
