create table if not exists public.library_catalog (id uuid primary key default gen_random_uuid(),title text not null,author text not null default '',category text not null default 'general',description text not null default '',cover_url text,copies_total integer not null default 1 check(copies_total>=0),copies_available integer not null default 1 check(copies_available>=0),featured boolean not null default false,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.library_loans (id uuid primary key default gen_random_uuid(),book_id uuid not null references public.library_catalog(id) on delete cascade,character_id uuid not null references public.characters(id) on delete cascade,borrowed_at timestamptz not null default now(),due_at timestamptz not null,returned_at timestamptz,status text not null default 'borrowed' check(status in ('borrowed','returned','overdue','lost')));
create table if not exists public.library_room_reservations (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,room_label text not null,reserved_for timestamptz not null,duration_minutes integer not null default 60 check(duration_minutes between 15 and 180),party_size integer not null default 1 check(party_size between 1 and 12),status text not null default 'reserved' check(status in ('reserved','cancelled','completed')),created_at timestamptz not null default now());
create table if not exists public.library_recommendations (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,book_id uuid not null references public.library_catalog(id) on delete cascade,note text not null default '',created_at timestamptz not null default now(),unique(character_id,book_id));
alter table public.library_catalog enable row level security;alter table public.library_loans enable row level security;alter table public.library_room_reservations enable row level security;alter table public.library_recommendations enable row level security;
create policy library_catalog_read on public.library_catalog for select using (active or public.school_staff_can_manage());create policy library_catalog_staff on public.library_catalog for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy library_loans_self on public.library_loans for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy library_loans_staff on public.library_loans for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy library_rooms_self_read on public.library_room_reservations for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy library_rooms_self_insert on public.library_room_reservations for insert with check(public.current_user_owns_character(character_id));create policy library_rooms_self_update on public.library_room_reservations for update using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy library_recs_read on public.library_recommendations for select using(auth.uid() is not null);create policy library_recs_self on public.library_recommendations for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());

create table if not exists public.cafeteria_preferences (character_id uuid primary key references public.characters(id) on delete cascade,favorite_items text[] not null default '{}',packed_lunch_default boolean not null default false,note text not null default '',updated_at timestamptz not null default now());
create table if not exists public.cafeteria_menu_ratings (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,menu_id uuid not null references public.school_lunch_menus(id) on delete cascade,rating smallint not null check(rating between 1 and 5),comment text not null default '',created_at timestamptz not null default now(),unique(character_id,menu_id));
alter table public.cafeteria_preferences enable row level security;alter table public.cafeteria_menu_ratings enable row level security;create policy cafeteria_prefs_self on public.cafeteria_preferences for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy cafeteria_ratings_read on public.cafeteria_menu_ratings for select using(auth.uid() is not null);create policy cafeteria_ratings_self on public.cafeteria_menu_ratings for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());

create table if not exists public.school_store_items (id uuid primary key default gen_random_uuid(),slug text not null unique,label text not null,category text not null,description text not null default '',cost integer not null default 0 check(cost>=0),asset_url text,rarity text not null default 'common',season_key text,club_activity_id uuid references public.campus_activities(id) on delete set null,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.school_token_wallets (character_id uuid primary key references public.characters(id) on delete cascade,balance integer not null default 0 check(balance>=0),lifetime_earned integer not null default 0 check(lifetime_earned>=0),updated_at timestamptz not null default now());
create table if not exists public.school_token_transactions (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,amount integer not null,reason text not null,source_type text,source_id uuid,created_at timestamptz not null default now());
create table if not exists public.school_store_purchases (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,item_id uuid not null references public.school_store_items(id) on delete cascade,cost_paid integer not null,purchased_at timestamptz not null default now());
alter table public.school_store_items enable row level security;alter table public.school_token_wallets enable row level security;alter table public.school_token_transactions enable row level security;alter table public.school_store_purchases enable row level security;create policy store_items_read on public.school_store_items for select using(active or public.school_staff_can_manage());create policy store_items_staff on public.school_store_items for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy token_wallet_self on public.school_token_wallets for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy token_wallet_staff on public.school_token_wallets for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy token_transactions_self on public.school_token_transactions for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy token_transactions_staff on public.school_token_transactions for insert with check(public.school_staff_can_manage());create policy purchases_self on public.school_store_purchases for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy purchases_staff on public.school_store_purchases for insert with check(public.school_staff_can_manage());

create table if not exists public.achievement_definitions (id uuid primary key default gen_random_uuid(),achievement_key text not null unique,label text not null,description text not null default '',category text not null check(category in ('academics','social','clubs','sports','roleplay','events','volunteering','hidden')),icon text not null default '✦',token_reward integer not null default 0,hidden boolean not null default false,active boolean not null default true);
create table if not exists public.character_achievements (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,achievement_id uuid not null references public.achievement_definitions(id) on delete cascade,awarded_at timestamptz not null default now(),source_type text,source_id uuid,note text not null default '',unique(character_id,achievement_id));
alter table public.achievement_definitions enable row level security;alter table public.character_achievements enable row level security;create policy achievements_defs_read on public.achievement_definitions for select using(active or public.school_staff_can_manage());create policy achievements_defs_staff on public.achievement_definitions for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy character_achievements_read on public.character_achievements for select using(public.current_user_owns_character(character_id) or public.school_staff_can_manage() or exists(select 1 from public.achievement_definitions a where a.id=achievement_id and not a.hidden));create policy character_achievements_staff on public.character_achievements for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());

create table if not exists public.lost_found_posts (id uuid primary key default gen_random_uuid(),character_id uuid references public.characters(id) on delete set null,post_type text not null check(post_type in ('lost','found')),title text not null,description text not null default '',location text,roleplay_date date,status text not null default 'open' check(status in ('open','matched','returned','closed')),image_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.student_request_board (id uuid primary key default gen_random_uuid(),character_id uuid not null references public.characters(id) on delete cascade,request_type text not null check(request_type in ('study_partner','tutoring','club_help','festival_volunteer','photography','event_partner','missed_notes','other')),title text not null,body text not null default '',visibility text not null default 'school' check(visibility in ('friends_only','school')),status text not null default 'open' check(status in ('open','matched','closed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.lost_found_posts enable row level security;alter table public.student_request_board enable row level security;create policy lost_found_read on public.lost_found_posts for select using(auth.uid() is not null);create policy lost_found_insert on public.lost_found_posts for insert with check(character_id is null or public.current_user_owns_character(character_id));create policy lost_found_update on public.lost_found_posts for update using((character_id is not null and public.current_user_owns_character(character_id)) or public.school_staff_can_manage()) with check((character_id is not null and public.current_user_owns_character(character_id)) or public.school_staff_can_manage());create policy requests_read on public.student_request_board for select using(auth.uid() is not null);create policy requests_self on public.student_request_board for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());

create table if not exists public.peer_tutor_profiles (character_id uuid primary key references public.characters(id) on delete cascade,subjects text[] not null default '{}',bio text not null default '',available boolean not null default true,approved boolean not null default false,updated_at timestamptz not null default now());
create table if not exists public.peer_tutoring_requests (id uuid primary key default gen_random_uuid(),student_character_id uuid not null references public.characters(id) on delete cascade,tutor_character_id uuid references public.characters(id) on delete set null,subject text not null,note text not null default '',requested_for timestamptz,status text not null default 'open' check(status in ('open','matched','completed','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.academic_support_plans (id uuid primary key default gen_random_uuid(),student_character_id uuid not null references public.characters(id) on delete cascade,section_id uuid references public.class_sections(id) on delete cascade,support_type text not null check(support_type in ('tutoring','office_hours','study_plan','makeup_work','check_in')),title text not null,plan text not null default '',status text not null default 'active' check(status in ('active','completed','cancelled')),created_by uuid default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.peer_tutor_profiles enable row level security;alter table public.peer_tutoring_requests enable row level security;alter table public.academic_support_plans enable row level security;create policy tutor_profiles_read on public.peer_tutor_profiles for select using(approved or public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy tutor_profiles_self on public.peer_tutor_profiles for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy tutoring_requests_read on public.peer_tutoring_requests for select using(public.current_user_owns_character(student_character_id) or (tutor_character_id is not null and public.current_user_owns_character(tutor_character_id)) or public.school_staff_can_manage());create policy tutoring_requests_insert on public.peer_tutoring_requests for insert with check(public.current_user_owns_character(student_character_id));create policy tutoring_requests_update on public.peer_tutoring_requests for update using(public.current_user_owns_character(student_character_id) or (tutor_character_id is not null and public.current_user_owns_character(tutor_character_id)) or public.school_staff_can_manage()) with check(public.current_user_owns_character(student_character_id) or (tutor_character_id is not null and public.current_user_owns_character(tutor_character_id)) or public.school_staff_can_manage());create policy support_plans_read on public.academic_support_plans for select using(public.current_user_owns_character(student_character_id) or public.school_staff_can_manage());create policy support_plans_staff on public.academic_support_plans for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());

create table if not exists public.faculty_profile_details (character_id uuid primary key references public.characters(id) on delete cascade,teaching_philosophy text not null default '',favorite_subjects text[] not null default '{}',welcome_message text not null default '',office_location text,profile_banner_url text,updated_at timestamptz not null default now());
create table if not exists public.class_section_identity (section_id uuid primary key references public.class_sections(id) on delete cascade,banner_url text,welcome_message text not null default '',class_rules text not null default '',weekly_agenda text not null default '',updated_at timestamptz not null default now());
alter table public.faculty_profile_details enable row level security;alter table public.class_section_identity enable row level security;create policy faculty_details_read on public.faculty_profile_details for select using(auth.uid() is not null);create policy faculty_details_manage on public.faculty_profile_details for all using(public.current_user_owns_character(character_id) or public.school_staff_can_manage()) with check(public.current_user_owns_character(character_id) or public.school_staff_can_manage());create policy section_identity_read on public.class_section_identity for select using(auth.uid() is not null);create policy section_identity_staff on public.class_section_identity for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());

create table if not exists public.school_award_ceremonies (id uuid primary key default gen_random_uuid(),title text not null,term text not null,ceremony_at timestamptz,status text not null default 'draft' check(status in ('draft','nominations','published','archived')),description text not null default '',created_at timestamptz not null default now());
create table if not exists public.school_awards (id uuid primary key default gen_random_uuid(),ceremony_id uuid not null references public.school_award_ceremonies(id) on delete cascade,category text not null,title text not null,recipient_character_id uuid not null references public.characters(id) on delete cascade,note text not null default '',published boolean not null default false,created_at timestamptz not null default now());
alter table public.school_award_ceremonies enable row level security;alter table public.school_awards enable row level security;create policy award_ceremonies_read on public.school_award_ceremonies for select using(status='published' or public.school_staff_can_manage());create policy award_ceremonies_staff on public.school_award_ceremonies for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());create policy school_awards_read on public.school_awards for select using(published or public.school_staff_can_manage() or public.current_user_owns_character(recipient_character_id));create policy school_awards_staff on public.school_awards for all using(public.school_staff_can_manage()) with check(public.school_staff_can_manage());
