alter table public.account_profiles
  add column if not exists account_status text not null default 'active' check (account_status in ('active','suspended')),
  add column if not exists suspension_reason text,
  add column if not exists suspended_at timestamptz,
  add column if not exists suspended_by uuid references auth.users(id) on delete set null;

create table if not exists public.system_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.system_audit_log enable row level security;
revoke all on public.system_audit_log from anon, authenticated;

drop policy if exists "deny direct audit reads" on public.system_audit_log;
create policy "deny direct audit reads" on public.system_audit_log for select to authenticated using (false);

create or replace function private.write_audit_log_internal(action_name text,target_kind text,target_identifier text,detail_data jsonb default '{}'::jsonb)
returns void language sql security definer set search_path=public as $$
 insert into public.system_audit_log(actor_user_id,action,target_type,target_id,details)
 values(auth.uid(),action_name,target_kind,target_identifier,coalesce(detail_data,'{}'::jsonb));
$$;
revoke all on function private.write_audit_log_internal(text,text,text,jsonb) from public,anon,authenticated;

create or replace function private.account_governance_directory_internal(search_text text default '')
returns table(user_id uuid,display_name text,discord_username text,discord_user_id text,account_status text,suspension_reason text,created_at timestamptz,character_count bigint)
language sql stable security definer set search_path=public,private,auth as $$
 select p.user_id,p.display_name,p.discord_username,
   coalesce(u.raw_user_meta_data->>'provider_id',u.raw_user_meta_data->>'sub') as discord_user_id,
   p.account_status,p.suspension_reason,p.created_at,
   (select count(*) from public.characters c where c.owner_user_id=p.user_id) as character_count
 from public.account_profiles p
 join auth.users u on u.id=p.user_id
 where (private.account_has_permission(auth.uid(),'site_admin') or private.is_owner_discord_user())
   and (trim(coalesce(search_text,''))='' or p.display_name ilike '%'||trim(search_text)||'%' or coalesce(p.discord_username,'') ilike '%'||trim(search_text)||'%' or coalesce(u.raw_user_meta_data->>'provider_id',u.raw_user_meta_data->>'sub','') ilike '%'||trim(search_text)||'%')
 order by p.created_at desc limit 200;
$$;

create or replace function public.account_governance_directory(search_text text default '')
returns table(user_id uuid,display_name text,discord_username text,discord_user_id text,account_status text,suspension_reason text,created_at timestamptz,character_count bigint)
language sql stable security invoker set search_path=private as $$ select * from private.account_governance_directory_internal(search_text); $$;

create or replace function private.set_account_status_internal(target_user uuid,new_status text,reason text default null)
returns boolean language plpgsql security definer set search_path=public,private as $$
begin
 if not (private.account_has_permission(auth.uid(),'site_admin') or private.is_owner_discord_user()) then raise exception 'Site Admin or Owner required'; end if;
 if new_status not in ('active','suspended') then raise exception 'Invalid account status'; end if;
 if target_user=auth.uid() and new_status='suspended' then raise exception 'You cannot suspend your own account'; end if;
 if private.is_owner_discord_user() is false and exists(select 1 from public.account_permissions ap where ap.user_id=target_user and ap.permission='site_admin') and new_status='suspended' then raise exception 'Only Owner may suspend a Site Admin'; end if;
 update public.account_profiles set account_status=new_status,suspension_reason=case when new_status='suspended' then nullif(trim(reason),'') else null end,suspended_at=case when new_status='suspended' then now() else null end,suspended_by=case when new_status='suspended' then auth.uid() else null end,updated_at=now() where user_id=target_user;
 if not found then return false; end if;
 perform private.write_audit_log_internal('account_status_changed','account',target_user::text,jsonb_build_object('status',new_status,'reason',reason));
 return true;
end;$$;

create or replace function public.set_account_status(target_user uuid,new_status text,reason text default null)
returns boolean language sql security invoker set search_path=private as $$ select private.set_account_status_internal(target_user,new_status,reason); $$;

create or replace function private.system_audit_log_feed_internal(limit_rows integer default 100)
returns table(id bigint,actor_user_id uuid,actor_name text,action text,target_type text,target_id text,details jsonb,created_at timestamptz)
language sql stable security definer set search_path=public,private as $$
 select l.id,l.actor_user_id,coalesce(p.display_name,'System'),l.action,l.target_type,l.target_id,l.details,l.created_at
 from public.system_audit_log l left join public.account_profiles p on p.user_id=l.actor_user_id
 where private.account_has_permission(auth.uid(),'site_admin') or private.is_owner_discord_user()
 order by l.created_at desc limit greatest(1,least(coalesce(limit_rows,100),500));
$$;
create or replace function public.system_audit_log_feed(limit_rows integer default 100)
returns table(id bigint,actor_user_id uuid,actor_name text,action text,target_type text,target_id text,details jsonb,created_at timestamptz)
language sql stable security invoker set search_path=private as $$ select * from private.system_audit_log_feed_internal(limit_rows); $$;

grant execute on function private.account_governance_directory_internal(text) to authenticated;
grant execute on function private.set_account_status_internal(uuid,text,text) to authenticated;
grant execute on function private.system_audit_log_feed_internal(integer) to authenticated;
grant execute on function public.account_governance_directory(text) to authenticated;
grant execute on function public.set_account_status(uuid,text,text) to authenticated;
grant execute on function public.system_audit_log_feed(integer) to authenticated;
