"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./newspaper.module.css";
const U=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";const K=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
type Article={id:string;section:string;headline:string;dek:string;body:string;published_at:string;author_name:string|null;author_handle:string|null};
function pretty(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
export default function NewspaperPage(){const [articles,setArticles]=useState<Article[]>([]),[status,setStatus]=useState("Loading the latest issue…"),[section,setSection]=useState("all");
 useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch(`${U}/rest/v1/rpc/public_newspaper_feed`,{method:"POST",headers:{apikey:K,"Content-Type":"application/json"},body:JSON.stringify({row_limit:80}),cache:"no-store"});if(!r.ok)throw new Error("The newspaper could not be loaded.");const data=await r.json() as Article[];if(!dead){setArticles(data);setStatus(data.length?"The latest Hanami stories are live.":"No issue has been published yet.")}}catch(e){if(!dead)setStatus(e instanceof Error?e.message:"The newspaper could not be loaded.")}})();return()=>{dead=true}},[]);
 const sections=useMemo(()=>["all",...Array.from(new Set(articles.map(a=>a.section)))],[articles]);const visible=section==="all"?articles:articles.filter(a=>a.section===section);const lead=visible[0];const secondary=visible.slice(1,5);const archive=visible.slice(5);const issueLabel=lead?new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"long",year:"numeric"}).format(new Date(lead.published_at)):"2006";
 return <main className={styles.page}><header className={styles.masthead}><div><a href="../">HANAMI HIGH SCHOOL</a><p>STUDENT NEWSPAPER • HANAMI CITY • 2006</p></div><h1>The Hanami Chronicle</h1><span>{issueLabel.toUpperCase()} EDITION</span></header><nav className={styles.sections} aria-label="Newspaper sections">{sections.map(s=><button key={s} className={section===s?styles.active:""} onClick={()=>setSection(s)}>{s==="all"?"Front Page":pretty(s)}</button>)}</nav><div className={styles.status}>{status}</div>{lead?<><section className={styles.front}><article className={styles.lead}><p className={styles.kicker}>{pretty(lead.section)}</p><h2>{lead.headline}</h2><p className={styles.dek}>{lead.dek||lead.body.slice(0,180)}</p><div className={styles.byline}>BY {lead.author_name?.toUpperCase()||"HANAMI CHRONICLE STAFF"} • {new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",year:"numeric"}).format(new Date(lead.published_at))}</div><p className={styles.body}>{lead.body}</p></article><aside className={styles.side}>{secondary.map(a=><article key={a.id}><p className={styles.kicker}>{pretty(a.section)}</p><h3>{a.headline}</h3><p>{a.dek||a.body.slice(0,120)}</p><small>{a.author_name||"Chronicle Staff"} • {new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric"}).format(new Date(a.published_at))}</small></article>)}</aside></section>{archive.length>0&&<section className={styles.archive}><header><div><p>ARCHIVE</p><h2>Earlier stories</h2></div><span>{archive.length} ARTICLE{archive.length===1?"":"S"}</span></header><div>{archive.map(a=><article key={a.id}><p className={styles.kicker}>{pretty(a.section)}</p><h3>{a.headline}</h3><p>{a.dek||a.body.slice(0,130)}</p><small>{new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",month:"short",day:"numeric",year:"numeric"}).format(new Date(a.published_at))}</small></article>)}</div></section>}</>:<section className={styles.empty}><h2>The presses are quiet.</h2><p>When Hanami’s student writers publish the first approved story, it will become the front page here.</p></section>}<footer><a href="../">← School Home</a><a href="../portal/">Portal Login →</a></footer></main>}
