"use client";

import {useCallback,useEffect,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
type Student={character_id:string;display_name:string;handle:string;visibility:string;is_active:boolean};
type Snapshot={character:{id:string;display_name:string;handle:string;visibility:string;is_active:boolean;created_at:string};classes:Array<{section_id:string;section_code:string;term:string;room:string|null;relationship:string}>;submissions:Array<{assignment_id:string;title:string;status:string;submitted_at:string|null;grade:number|null;feedback:string|null}>;attendance:Array<{date:string;status:string;note:string|null;section_code:string|null}>;forms:Array<{submission_id:string;form_title:string|null;status:string;created_at:string;response_data:Record<string,unknown>;staff_notes:string|null}>};
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
function date(value:string|null){return value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"Asia/Tokyo"}).format(new Date(value)):"—";}

export default function OwnerStudentPortalViewer(){
 const [session,setSession]=useState<PortalSession|null>(null);const [students,setStudents]=useState<Student[]>([]);const [selected,setSelected]=useState("");const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [status,setStatus]=useState("Verifying Owner access…");
 const initialize=useCallback(async()=>{const stored=readSession();if(!stored){setStatus("Open the Owner Portal and sign in first.");return;}setSession(stored);const [owner,gate]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(stored.accessToken),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/rpc/has_privileged_portal_session`,{method:"POST",headers:headers(stored.accessToken),body:JSON.stringify({requested_portal:"owner"})})]);if(!owner.ok||!gate.ok||!Boolean(await owner.json())||!Boolean(await gate.json())){setStatus("Owner identity and privileged Owner sign-in are required.");return;}const directory=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_student_portal_directory`,{method:"POST",headers:headers(stored.accessToken),body:"{}"});if(!directory.ok){setStatus("Student directory could not be loaded.");return;}const rows=await directory.json() as Student[];setStudents(rows);if(rows[0])setSelected(rows[0].character_id);setStatus(rows.length?"Read-only moderation view ready.":"No Student characters found.");},[]);
 useEffect(()=>{queueMicrotask(()=>void initialize());},[initialize]);
 useEffect(()=>{if(!session||!selected)return;queueMicrotask(()=>{setStatus("Loading Student portal snapshot…");void fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_student_portal_snapshot`,{method:"POST",headers:headers(session.accessToken),body:JSON.stringify({target_character_id:selected})}).then(async r=>{if(!r.ok)throw new Error();setSnapshot(await r.json() as Snapshot);setStatus("Read-only moderation view ready.");}).catch(()=>{setSnapshot(null);setStatus("Student portal snapshot could not be loaded.");});});},[session,selected]);
 return <section style={{border:"1px solid #9babc0",background:"#fff",padding:16}}>
  <p className="eyebrow">OWNER • STUDENT PORTAL VIEWER</p><h2 style={{margin:"4px 0 8px",font:"400 28px Georgia,serif"}}>Moderation view</h2><p style={{maxWidth:820}}>Inspect a Student character&apos;s school portal data without impersonating them or changing their active session. This view is Owner-only and read-only.</p><div style={{padding:10,background:"#fff7d8",border:"1px solid #d9c576",marginBottom:14}}>{status}</div>
  {students.length>0&&<label style={{display:"grid",gap:5,maxWidth:520,marginBottom:16}}><strong>Student character</strong><select value={selected} onChange={e=>setSelected(e.target.value)}>{students.map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle})</option>)}</select></label>}
  {snapshot&&<div style={{display:"grid",gap:14}}>
   <section style={{padding:14,border:"1px solid #c7d0da",background:"#f8fafc"}}><strong>{snapshot.character.display_name}</strong><div>@{snapshot.character.handle} • {snapshot.character.visibility.replaceAll("_"," ")} • {snapshot.character.is_active?"Active":"Inactive"}</div><small>Character created {date(snapshot.character.created_at)}</small></section>
   <details open><summary style={{cursor:"pointer",fontWeight:700}}>Classes ({snapshot.classes.length})</summary><div style={{padding:"10px 0"}}>{snapshot.classes.length?snapshot.classes.map(c=><div key={c.section_id} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{c.section_code}</strong> • {c.term} • {c.room??"No room"} • {c.relationship}</div>):"No class memberships."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>Coursework submissions ({snapshot.submissions.length})</summary><div style={{padding:"10px 0"}}>{snapshot.submissions.length?snapshot.submissions.map((s,i)=><div key={`${s.assignment_id}-${i}`} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{s.title}</strong><div>{s.status} • Submitted {date(s.submitted_at)} • Grade {s.grade??"—"}</div>{s.feedback&&<small>Teacher feedback: {s.feedback}</small>}</div>):"No coursework submissions."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>Attendance ({snapshot.attendance.length})</summary><div style={{padding:"10px 0"}}>{snapshot.attendance.length?snapshot.attendance.map((a,i)=><div key={`${a.date}-${i}`} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{a.date}</strong> • {a.status} • {a.section_code??"Unknown section"}{a.note&&<div>{a.note}</div>}</div>):"No attendance records."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>School form submissions ({snapshot.forms.length})</summary><div style={{padding:"10px 0"}}>{snapshot.forms.length?snapshot.forms.map(f=><article key={f.submission_id} style={{padding:10,borderBottom:"1px dotted #c7d0da"}}><strong>{f.form_title??"School form"}</strong><div>{date(f.created_at)} • {f.status}</div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:12}}>{JSON.stringify(f.response_data,null,2)}</pre>{f.staff_notes&&<small>Staff notes: {f.staff_notes}</small>}</article>):"No school form submissions."}</div></details>
  </div>}
 </section>;
}
