"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mperfphbhqpjlqmaysmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_G-Pg-XwLz6rpRdlIWXcIgg_kxyd4gb0";
const SESSION_KEY="hanami.portal.session.v1";
type PortalSession={accessToken:string;refreshToken:string;expiresAt:number;tokenType:string};
type Student={character_id:string;display_name:string;handle:string;visibility:string;is_active:boolean};
type Snapshot={character:{id:string;display_name:string;handle:string;visibility:string;is_active:boolean;created_at:string};classes:Array<{section_id:string;section_code:string;term:string;room:string|null;relationship:string}>;submissions:Array<{assignment_id:string;title:string;status:string;submitted_at:string|null;grade:number|null;feedback:string|null}>;attendance:Array<{date:string;status:string;note:string|null;section_code:string|null}>;forms:Array<{submission_id:string;form_title:string|null;status:string;created_at:string;response_data:Record<string,unknown>;staff_notes:string|null}>};
type Homeroom={id:string;code:string;grade_level:number;school_year:string;adviser_character_id:string|null;room_label:string|null};
type Section={id:string;section_code:string;term:string;room:string|null;academic_courses:{code:string;title:string}|null};
type Faculty={id:string;display_name:string;handle:string};
type SectionMembership={section_id:string;character_id:string;relationship:"student"|"instructor"};
type HomeroomMembership={homeroom_id:string;student_character_id:string};
function headers(token:string){return {apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}
function readSession():PortalSession|null{try{const raw=localStorage.getItem(SESSION_KEY);if(!raw)return null;const value=JSON.parse(raw) as Partial<PortalSession>;if(typeof value.accessToken!=="string"||typeof value.refreshToken!=="string"||typeof value.expiresAt!=="number")return null;return {accessToken:value.accessToken,refreshToken:value.refreshToken,expiresAt:value.expiresAt,tokenType:value.tokenType??"bearer"};}catch{return null;}}
function date(value:string|null){return value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"Asia/Tokyo"}).format(new Date(value)):"—";}

export default function OwnerStudentPortalViewer(){
 const [session,setSession]=useState<PortalSession|null>(null);const [students,setStudents]=useState<Student[]>([]);const [selected,setSelected]=useState("");const [snapshot,setSnapshot]=useState<Snapshot|null>(null);const [status,setStatus]=useState("Verifying Owner access…");const [saving,setSaving]=useState(false);
 const [homerooms,setHomerooms]=useState<Homeroom[]>([]);const [sections,setSections]=useState<Section[]>([]);const [faculty,setFaculty]=useState<Faculty[]>([]);const [sectionMemberships,setSectionMemberships]=useState<SectionMembership[]>([]);const [homeroomMemberships,setHomeroomMemberships]=useState<HomeroomMembership[]>([]);
 const [homeroomChoice,setHomeroomChoice]=useState("");const [classChoice,setClassChoice]=useState("");const [facultySection,setFacultySection]=useState("");const [facultyChoice,setFacultyChoice]=useState("");const [adviserHomeroom,setAdviserHomeroom]=useState("");const [adviserChoice,setAdviserChoice]=useState("");

 const loadManagement=useCallback(async(token:string)=>{const [h,s,f,sm,hm]=await Promise.all([
  fetch(`${SUPABASE_URL}/rest/v1/homerooms?select=id,code,grade_level,school_year,adviser_character_id,room_label&is_active=eq.true&order=grade_level.asc,code.asc`,{headers:headers(token)}),
  fetch(`${SUPABASE_URL}/rest/v1/class_sections?select=id,section_code,term,room,academic_courses(code,title)&order=term.asc,section_code.asc`,{headers:headers(token)}),
  fetch(`${SUPABASE_URL}/rest/v1/characters?select=id,display_name,handle&role=eq.faculty&is_active=eq.true&order=display_name.asc`,{headers:headers(token)}),
  fetch(`${SUPABASE_URL}/rest/v1/section_memberships?select=section_id,character_id,relationship`,{headers:headers(token)}),
  fetch(`${SUPABASE_URL}/rest/v1/homeroom_memberships?select=homeroom_id,student_character_id`,{headers:headers(token)})
 ]);if(h.ok)setHomerooms(await h.json() as Homeroom[]);if(s.ok)setSections(await s.json() as Section[]);if(f.ok)setFaculty(await f.json() as Faculty[]);if(sm.ok)setSectionMemberships(await sm.json() as SectionMembership[]);if(hm.ok)setHomeroomMemberships(await hm.json() as HomeroomMembership[]);},[]);
 const initialize=useCallback(async()=>{const stored=readSession();if(!stored){setStatus("Open the Owner Portal and sign in first.");return;}setSession(stored);const [owner,gate]=await Promise.all([fetch(`${SUPABASE_URL}/rest/v1/rpc/current_owner_status`,{method:"POST",headers:headers(stored.accessToken),body:"{}"}),fetch(`${SUPABASE_URL}/rest/v1/rpc/has_privileged_portal_session`,{method:"POST",headers:headers(stored.accessToken),body:JSON.stringify({requested_portal:"owner"})})]);if(!owner.ok||!gate.ok||!Boolean(await owner.json())||!Boolean(await gate.json())){setStatus("Owner identity and privileged Owner sign-in are required.");return;}const directory=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_student_portal_directory`,{method:"POST",headers:headers(stored.accessToken),body:"{}"});if(!directory.ok){setStatus("Student directory could not be loaded.");return;}const rows=await directory.json() as Student[];setStudents(rows);if(rows[0])setSelected(rows[0].character_id);await loadManagement(stored.accessToken);setStatus(rows.length?"Owner student management ready.":"No Student characters found.");},[loadManagement]);
 useEffect(()=>{queueMicrotask(()=>void initialize());},[initialize]);
 const loadSnapshot=useCallback(async()=>{if(!session||!selected)return;setStatus("Loading Student portal snapshot…");try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/owner_student_portal_snapshot`,{method:"POST",headers:headers(session.accessToken),body:JSON.stringify({target_character_id:selected})});if(!r.ok)throw new Error();setSnapshot(await r.json() as Snapshot);await loadManagement(session.accessToken);setStatus("Owner student management ready.");}catch{setSnapshot(null);setStatus("Student portal snapshot could not be loaded.");}},[loadManagement,selected,session]);
 useEffect(()=>{if(session&&selected)queueMicrotask(()=>void loadSnapshot());},[loadSnapshot,selected,session]);

 const currentHomeroom=homeroomMemberships.find(row=>row.student_character_id===selected)?.homeroom_id??"";
 const currentStudentSections=useMemo(()=>new Set(sectionMemberships.filter(row=>row.character_id===selected&&row.relationship==="student").map(row=>row.section_id)),[sectionMemberships,selected]);
 const instructorsFor=(sectionId:string)=>sectionMemberships.filter(row=>row.section_id===sectionId&&row.relationship==="instructor").map(row=>faculty.find(f=>f.id===row.character_id)).filter((row):row is Faculty=>Boolean(row));
 const sectionLabel=(id:string)=>{const s=sections.find(row=>row.id===id);return s?`${s.academic_courses?.code??"COURSE"} • ${s.academic_courses?.title??"Untitled"} • ${s.section_code}`:id;};
 async function rpc(name:string,body:Record<string,unknown>,success:string){if(!session||saving)return;setSaving(true);setStatus("Saving Owner assignment…");try{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:headers(session.accessToken),body:JSON.stringify(body)});if(!response.ok)throw new Error(await response.text());await loadSnapshot();setStatus(success);}catch(error){setStatus(error instanceof Error?error.message:"Assignment could not be saved.");}finally{setSaving(false);}}
 async function saveHomeroom(){await rpc("owner_set_student_homeroom",{target_student_character_id:selected,target_homeroom_id:homeroomChoice||null},homeroomChoice?"Student homeroom assigned/reassigned.":"Student homeroom cleared.");}
 async function addClass(){if(!classChoice)return;await rpc("owner_set_section_membership",{target_character_id:selected,target_section_id:classChoice,target_relationship:"student",target_enabled:true},"Student class assignment saved.");}
 async function removeClass(sectionId:string){await rpc("owner_set_section_membership",{target_character_id:selected,target_section_id:sectionId,target_relationship:"student",target_enabled:false},"Student removed from class.");}
 async function assignFaculty(){if(!facultySection||!facultyChoice)return;await rpc("owner_set_section_membership",{target_character_id:facultyChoice,target_section_id:facultySection,target_relationship:"instructor",target_enabled:true},"Faculty instructor assignment saved.");}
 async function removeFaculty(sectionId:string,facultyId:string){await rpc("owner_set_section_membership",{target_character_id:facultyId,target_section_id:sectionId,target_relationship:"instructor",target_enabled:false},"Faculty instructor removed from class.");}
 async function saveAdviser(){if(!adviserHomeroom)return;await rpc("owner_set_homeroom_adviser",{target_homeroom_id:adviserHomeroom,target_faculty_character_id:adviserChoice||null},adviserChoice?"Homeroom adviser assigned/reassigned.":"Homeroom adviser cleared.");}

 return <section style={{border:"1px solid #9babc0",background:"#fff",padding:16}}>
  <p className="eyebrow">OWNER • STUDENT PORTAL VIEWER</p><h2 style={{margin:"4px 0 8px",font:"400 28px Georgia,serif"}}>Student management view</h2><p style={{maxWidth:860}}>Inspect a Student character&apos;s portal data without impersonating them. The Owner can also assign/reassign homerooms, class enrollments, Faculty instructors, and homeroom advisers from this page.</p><div style={{padding:10,background:"#fff7d8",border:"1px solid #d9c576",marginBottom:14}}>{status}</div>
  {students.length>0&&<label style={{display:"grid",gap:5,maxWidth:520,marginBottom:16}}><strong>Student character</strong><select value={selected} onChange={e=>setSelected(e.target.value)}>{students.map(s=><option key={s.character_id} value={s.character_id}>{s.display_name} (@{s.handle})</option>)}</select></label>}
  {snapshot&&<div style={{display:"grid",gap:14}}>
   <section style={{padding:14,border:"1px solid #c7d0da",background:"#f8fafc"}}><strong>{snapshot.character.display_name}</strong><div>@{snapshot.character.handle} • {snapshot.character.visibility.replaceAll("_"," ")} • {snapshot.character.is_active?"Active":"Inactive"}</div><small>Character created {date(snapshot.character.created_at)}</small></section>
   <section style={{padding:14,border:"2px solid #8f365b",background:"#fff8fb"}}><p className="eyebrow">OWNER ASSIGNMENT CONTROLS</p><h3 style={{margin:"4px 0 12px"}}>School assignments</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>
    <div style={{padding:10,border:"1px solid #d5c1ca",background:"#fff"}}><strong>Student homeroom</strong><p style={{fontSize:12}}>Current: {homerooms.find(h=>h.id===currentHomeroom)?.code??"None"}</p><select value={homeroomChoice} onChange={e=>setHomeroomChoice(e.target.value)} style={{width:"100%",marginBottom:6}}><option value="">No homeroom</option>{homerooms.map(h=><option key={h.id} value={h.id}>{h.code} • Grade {h.grade_level} • {h.school_year}</option>)}</select><button type="button" disabled={saving} onClick={()=>void saveHomeroom()}>Assign / reassign homeroom</button></div>
    <div style={{padding:10,border:"1px solid #d5c1ca",background:"#fff"}}><strong>Student classes</strong><select value={classChoice} onChange={e=>setClassChoice(e.target.value)} style={{width:"100%",margin:"8px 0 6px"}}><option value="">Choose class…</option>{sections.filter(s=>!currentStudentSections.has(s.id)).map(s=><option key={s.id} value={s.id}>{sectionLabel(s.id)}</option>)}</select><button type="button" disabled={saving||!classChoice} onClick={()=>void addClass()}>Assign class</button><div style={{marginTop:8}}>{[...currentStudentSections].map(id=><div key={id} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"5px 0",borderTop:"1px dotted #d6cbd0"}}><span>{sectionLabel(id)}</span><button type="button" disabled={saving} onClick={()=>void removeClass(id)}>Remove</button></div>)}</div></div>
    <div style={{padding:10,border:"1px solid #d5c1ca",background:"#fff"}}><strong>Class Faculty</strong><select value={facultySection} onChange={e=>setFacultySection(e.target.value)} style={{width:"100%",margin:"8px 0 6px"}}><option value="">Choose class…</option>{sections.map(s=><option key={s.id} value={s.id}>{sectionLabel(s.id)}</option>)}</select><select value={facultyChoice} onChange={e=>setFacultyChoice(e.target.value)} style={{width:"100%",marginBottom:6}}><option value="">Choose Faculty…</option>{faculty.map(f=><option key={f.id} value={f.id}>{f.display_name} (@{f.handle})</option>)}</select><button type="button" disabled={saving||!facultySection||!facultyChoice} onClick={()=>void assignFaculty()}>Assign Faculty to class</button>{facultySection&&<div style={{marginTop:8}}>{instructorsFor(facultySection).map(f=><div key={f.id} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"5px 0",borderTop:"1px dotted #d6cbd0"}}><span>{f.display_name}</span><button type="button" disabled={saving} onClick={()=>void removeFaculty(facultySection,f.id)}>Remove</button></div>)}</div>}</div>
    <div style={{padding:10,border:"1px solid #d5c1ca",background:"#fff"}}><strong>Homeroom adviser</strong><select value={adviserHomeroom} onChange={e=>setAdviserHomeroom(e.target.value)} style={{width:"100%",margin:"8px 0 6px"}}><option value="">Choose homeroom…</option>{homerooms.map(h=><option key={h.id} value={h.id}>{h.code} • Grade {h.grade_level}</option>)}</select><select value={adviserChoice} onChange={e=>setAdviserChoice(e.target.value)} style={{width:"100%",marginBottom:6}}><option value="">No adviser</option>{faculty.map(f=><option key={f.id} value={f.id}>{f.display_name} (@{f.handle})</option>)}</select><button type="button" disabled={saving||!adviserHomeroom} onClick={()=>void saveAdviser()}>Assign / reassign adviser</button></div>
   </div></section>
   <details open><summary style={{cursor:"pointer",fontWeight:700}}>Classes ({snapshot.classes.length})</summary><div style={{padding:"10px 0"}}>{snapshot.classes.length?snapshot.classes.map(c=><div key={c.section_id} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{c.section_code}</strong> • {c.term} • {c.room??"No room"} • {c.relationship}</div>):"No class memberships."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>Coursework submissions ({snapshot.submissions.length})</summary><div style={{padding:"10px 0"}}>{snapshot.submissions.length?snapshot.submissions.map((s,i)=><div key={`${s.assignment_id}-${i}`} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{s.title}</strong><div>{s.status} • Submitted {date(s.submitted_at)} • Grade {s.grade??"—"}</div>{s.feedback&&<small>Teacher feedback: {s.feedback}</small>}</div>):"No coursework submissions."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>Attendance ({snapshot.attendance.length})</summary><div style={{padding:"10px 0"}}>{snapshot.attendance.length?snapshot.attendance.map((a,i)=><div key={`${a.date}-${i}`} style={{padding:8,borderBottom:"1px dotted #c7d0da"}}><strong>{a.date}</strong> • {a.status} • {a.section_code??"Unknown section"}{a.note&&<div>{a.note}</div>}</div>):"No attendance records."}</div></details>
   <details><summary style={{cursor:"pointer",fontWeight:700}}>School form submissions ({snapshot.forms.length})</summary><div style={{padding:"10px 0"}}>{snapshot.forms.length?snapshot.forms.map(f=><article key={f.submission_id} style={{padding:10,borderBottom:"1px dotted #c7d0da"}}><strong>{f.form_title??"School form"}</strong><div>{date(f.created_at)} • {f.status}</div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",fontSize:12}}>{JSON.stringify(f.response_data,null,2)}</pre>{f.staff_notes&&<small>Staff notes: {f.staff_notes}</small>}</article>):"No school form submissions."}</div></details>
  </div>}
 </section>;
}
