import CampusDirectory from "../components/campus-directory";
import {hanamiRoleplayDate} from "../components/roleplay-date";

const services = [
  ["保", "Health Office", "First aid, health plans, wellness support, and referrals.", "Student Services • Room 104"],
  ["心", "Counseling", "Private appointments for personal, social, and academic support.", "Student Services • Room 108"],
  ["図", "Library", "Books, research help, quiet study, media, and technology lending.", "Learning Commons • Levels 1–2"],
  ["奉", "Volunteer Center", "School and community service projects with verified participation.", "Student Life • Room 202"],
] as const;
const government = [["Student Council", "Elected representatives coordinate student proposals, events, and campus initiatives."],["Class Representatives", "Each class selects a representative to raise concerns and share announcements."],["Broadcast Committee", "Student reporters publish notices, interviews, event coverage, and the hallway rumor column."]] as const;

export default function CampusLifePage(){
  const currentDate=hanamiRoleplayDate();
  return <main className="site-page campus-page">
    <a className="skip-link" href="#campus-main">Skip to main content</a>
    <header className="school-header" aria-label="Hanami High header"><div className="network-strip">HANAMI HIGH SCHOOL • PUBLIC SCHOOL NETWORK • EST. 2006</div><div className="brand-row"><a className="brand-lockup brand-link" href="../"><div className="school-mark" aria-hidden="true"><span>花</span></div><div><p className="jp-name">花見高等学校</p><p className="brand-name">HANAMI HIGH SCHOOL</p><p className="brand-subtitle">Knowledge • Character • Community</p></div></a><div className="school-clock"><strong>{currentDate.toUpperCase()}</strong><span>HANAMI CITY • ROLEPLAY YEAR 2006</span></div></div><div className="nav-row"><nav aria-label="Primary navigation"><a href="../">Home</a><a href="../about/">About</a><a href="../academics/">Academics</a><a className="active" href="./">Campus Life</a><a href="#directory">Clubs</a><a href="../calendar/">Calendar</a><a href="../#news">News</a><a href="../about/#directory">People</a><a href="#gallery">Gallery</a></nav><a className="portal-button" href="../portal/">↪ Login / Portal</a></div></header>
    <div className="about-breadcrumb"><a href="../">School Home</a><span>›</span><strong>Campus Life</strong></div>
    <section className="campus-hero" id="campus-main"><div><p className="eyebrow">HANAMI HIGH • LIFE BEYOND THE CLASSROOM</p><h1>Find your people.<br/>Make campus yours.</h1><p>Join a club, compete with a team, serve the community, attend an event, or help create one of Hanami High&apos;s first traditions.</p><div className="hero-actions"><a className="primary-action" href="#directory">Explore opportunities</a><a className="text-link" href="../calendar/">See upcoming events →</a></div></div><div className="campus-board"><p className="eyebrow">AFTER THE BELL</p><strong>3:30 PM</strong><span>Club rooms open</span><hr/><p>Applications and registrations stay inside the Student Portal and use your active character.</p></div></section>
    <div className="campus-page-layout"><aside className="campus-side"><section className="panel"><h2 className="panel-title">CAMPUS LIFE INDEX</h2><nav className="link-list"><a href="#directory"><span>01</span>Clubs & Athletics</a><a href="#government"><span>02</span>Student Government</a><a href="../calendar/"><span>03</span>Events</a><a href="#gallery"><span>04</span>Gallery</a><a href="#services"><span>05</span>Student Services</a><a href="#jobs"><span>06</span>Opportunities</a></nav></section><section className="panel"><h2 className="panel-title">CAMPUS STATUS</h2><div className="panel-body"><p><i className="status-dot"/> Activities operating normally</p><small>All schedules use Japan Standard Time.</small></div></section></aside>
      <div className="campus-page-content"><CampusDirectory/>
        <section className="info-section" id="government"><div className="section-heading"><h2>STUDENT GOVERNMENT</h2><span>VOICE • SERVICE • LEADERSHIP</span></div><div className="government-grid">{government.map(([title,copy],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p><a href="../portal/student/">View in Student Portal →</a></article>)}</div></section>
        <section className="info-section" id="events"><div className="section-heading"><h2>CAMPUS EVENTS CALENDAR</h2><span>2006 • JST</span></div><div className="campus-events"><article><time><strong>24</strong>AUG</time><div><p className="eyebrow">CLUBS</p><h3>Club Recruitment Week</h3><p>Meet student organizations in the courtyard after classes.</p></div><span>3:30 PM</span></article><article><time><strong>29</strong>AUG</time><div><p className="eyebrow">ATHLETICS</p><h3>Welcome Sports Day</h3><p>Open practices, team introductions, and friendly matches.</p></div><span>10:00 AM</span></article><article><time><strong>12</strong>SEP</time><div><p className="eyebrow">WHOLE SCHOOL</p><h3>Autumn Culture Festival</h3><p>Performances, class exhibits, club booths, art, and food.</p></div><span>10:00 AM</span></article></div><div className="calendar-actions"><a className="secondary-action" href="../calendar/">View complete calendar</a></div></section>
        <section className="info-section" id="gallery"><div className="section-heading"><h2>CAMPUS GALLERY</h2><span>STUDENT NETWORK ARCHIVE</span></div><div className="campus-gallery"><figure><div>桜</div><figcaption>Courtyard in bloom</figcaption></figure><figure><div>祭</div><figcaption>Culture Festival preparations</figcaption></figure><figure><div>部</div><figcaption>After-school club rooms</figcaption></figure><figure><div>競</div><figcaption>Athletics field</figcaption></figure></div><p className="content-note">Approved roleplay photography and student work can be added as the 2006 school year develops.</p></section>
        <section className="info-section" id="services"><div className="section-heading"><h2>HEALTH, COUNSELING & LIBRARY</h2><span>STUDENT SUPPORT</span></div><div className="campus-services">{services.map(([icon,title,copy,place])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{copy}</p><small>{place}</small><a href="../portal/student/">Open service in Student Portal →</a></article>)}</div></section>
        <section className="info-section" id="jobs"><div className="section-heading"><h2>CAMPUS OPPORTUNITIES</h2><span>JOBS • SERVICE • INTERNSHIPS • LEADERSHIP</span></div><div className="opportunity-grid"><article><p className="eyebrow">PART-TIME • LOCAL</p><h3>Bookshop Assistant</h3><p>Weekend shelving and customer support. Suitable for students aged 16+.</p><dl><div><dt>Hours</dt><dd>6–10 weekly</dd></div><div><dt>Closes</dt><dd>Aug 31</dd></div></dl><a className="secondary-action" href="../portal/student/">Apply in Student Portal</a></article><article><p className="eyebrow">VOLUNTEER • CAMPUS</p><h3>Festival Welcome Team</h3><p>Help visitors, distribute maps, and support accessibility during the Culture Festival.</p><dl><div><dt>Credit</dt><dd>Service hours</dd></div><div><dt>Closes</dt><dd>Sep 05</dd></div></dl><a className="secondary-action" href="../portal/student/">Apply in Student Portal</a></article><article><p className="eyebrow">INTERNSHIP</p><h3>Library Media Assistant</h3><p>Supervised cataloging and digital archive work for approved pathway credit.</p><dl><div><dt>Credit</dt><dd>1 pathway</dd></div><div><dt>Review</dt><dd>Guidance</dd></div></dl><a className="secondary-action" href="../portal/student/">Apply in Student Portal</a></article></div><p className="content-note">Published opportunities and application status are managed inside Hanami High. No external email forms are used.</p></section>
      </div></div>
    <footer><p>HANAMI HIGH SCHOOL • 花見高等学校 • HANAMI CITY • 2006</p><nav><a href="../about/#contact">Contact</a><a href="../portal/">Portal Help</a><a href="#campus-main">Back to top ↑</a></nav></footer>
  </main>;
}
